### ISSUE TITLE
pack/unpack seem to be for Buf but still docs and tests are associated with Str

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#10]
pack is documented (and unpack is mentioned) in S32/Str but not S32/Containers which describes Buf.  Tests similarly in S32-str.  Also don't see pack/unpack in doc.perl.org.  Noticed some doc here https://gist.github.com/1239203

Ron

**Comment by paultcochrane** [comment]
This issue seems to have been resolved by 634eac7.  @moritz: OK if I mark this issue as closed?

**Comment by moritz** [comment]
@paultcochrane no, nothing has been done about `pack` yet

**Comment by AlexDaniel** [comment]
``pack`` was documented in https://github.com/perl6/doc/commit/a208c5312a3d7bf1cdad4d8b0cba57ce048c2166
Given that the thing is experimental, I don't think that we should demand something else under this ticket. Feel free to open new tickets though.
