### ISSUE TITLE
Create language/nqp page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1005]
Another item from #728.

Not sure from what perspective this should be written. In fact, I am not sure if a page like this is appropriate for perl 6 documentation generally. But I know that I and lots of other users will enjoy reading it.

**Comment by coke** [comment]
NQP is very particular to Rakudo's implementation of Perl 6 - 'use nqp' appears 2x in roast, and that is probably in error.

Some information about NQP belongs in a page describing rakudo's architecture, but I think that belongs on rakudo's wiki page or web site, not in the docs.

I'll close this out in a week unless we get some discussino about why we should include it.

**Comment by AlexDaniel** [comment]
OK, that makes sense and I agree.

Yes, it belongs to [NQP wiki](https://github.com/perl6/nqp/wiki). I'm not sure who is going to visit it though, but yeah.
