### ISSUE TITLE
Make Perl 5 special variables searchable

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/doc#1009]
They're reference [here](https://docs.perl6.org/language/5to6-perlvar), but aren't searchable.

See https://irclog.perlgeek.de/perl6/2016-11-14#i_13562327

**Comment by gfldex** [comment]
`@INC` and  `%INC` indexed with d3f3d0cb8d

**Comment by gfldex** [comment]
I would go light on this. There are so many special variables in Perl 5 that we may end up adding plenty of noise.

**Comment by AlexDaniel** [comment]
So what's wrong with doing ``Ctrl``+``f`` [here](https://docs.perl6.org/language/5to6-perlvar)?

**Comment by MasterDuke17** [comment]
Several people have asked in #perl6 what the @INC equivalent is just in the past 6 months, so I assume they didn't find it in the docs. I agree we probably shouldn't do every Perl 5 variable, but a couple of the common one would be good, especially when the difference isn't just adding a * twigil and converting to kebab case.

**Comment by coke** [comment]
My recommendation is to index https://docs.perl6.org/language/5to6-perlvar#SPECIAL_VARIABLES as "Perl 5 Special Variables", rather than indexing each p5 var.
