### ISSUE TITLE
parse-base clarification

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1011]
This issue is for my comment on https://github.com/perl6/doc/commit/4b9944d69fe1bb244bde49315284230a642dd8b7 (so that it does not slip through the cracks).

> Performs the reverse of Numeric by converts a string with a base-$radix number to its base-10 Numeric equivalent.

What is a “base-10 Numeric equivalent”? Does not sound right.

**Comment by zoffixznet** [comment]
There was a typo: it's

> Performs the reverse of [`base`](https://docs.perl6.org/routine/base) by converting a string string with a base-`$radix` number to its base-10 [`Numeric`](https://docs.perl6.org/type/Numeric.html) equivalent.

**Comment by AlexDaniel** [comment]
Contains a number in base-10? Like in [BCD](https://en.wikipedia.org/wiki/Binary-coded_decimal)? Heh

If we say that its ``.Str`` returns a number in base-10, fine. Or, we say that it is stored in binary, that's fine as well (although then you'd have to get into more details, so I'd rather not mention that at all). But “base-10 numeric” doesn't mean anything (the number itself is practically baseless from the user point of view).

**Comment by zoffixznet** [comment]
Would you, please, change the text to how it would make sense to you?
