### ISSUE TITLE
Document other ways to specify return type (there are at least 4)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1027]
[We only list](https://docs.perl6.org/type/Signature#Constraining_Return_Types) 2:
* ``-->``
* ``returns``

But [there are](https://irclog.perlgeek.de/perl6/2016-01-23#i_11931052) at least two others:
* ``sub foo of Int {}``
* ``my Int sub foo {}``

**Comment by Altai-man** [comment]
And document about the difference between them, see the first item https://github.com/perl6/doc/issues/1024#issuecomment-264643481 here.

**Comment by Altai-man** [comment]
And this section is broken, because of missing subroutine name. I'll fix that in the next commit.
