### ISSUE TITLE
&emit and &done undocumented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1032]
The subroutine `emit` doesn't seem to be documented. Only methods on various classes listed in https://docs.perl6.org/routine/emit

**Comment by jonathanstowe** [comment]
Presumably the same applies to ```done``` - I actually thought they were inserted into the scope of the ```supply { }``` or ```react { }``` and didn't have a separate existence.  However they may not want to be documented standalone but rather as part of the *asynchronous mini language* ....

**Comment by jnthn** [comment]
They are normal subroutines that throw control exceptions, just like `take` and `last`.

**Comment by jonathanstowe** [comment]
yeah I realised that after I looked at the souce, however if they are documented as being standalone subroutines then there will need to be a load of boilerplate explaining how they only work in a certain context, so to avoid that it might be better to treat them as if they were special syntactical items (in my mind at least.)

**Comment by zoffixznet** [comment]
> a load of boilerplate explaining how they only work in a certain context

Wouldn't it be just a single sentence? Just like with `take`: https://docs.perl6.org/routine/take

**Comment by JJ** [comment]
Where would that go?

**Comment by AlexDaniel** [comment]
@JJ I was about to say “same place where [&done](https://github.com/rakudo/rakudo/blob/f559c6d8b/src/core/control.pm#L159-L164) is documented”, but it seems that sub &done is not documented also…

**Comment by AlexDaniel** [comment]
Maybe somewhere on https://docs.perl6.org/language/functions?

**Comment by JJ** [comment]
We need to fix this "not documented" thing using code... Maybe create a test or something. They stay open for ever, even when they are fixed.
But functions would be a good place.

**Comment by JJ** [comment]
Functions would *not* be a good place. It's mainly devoted to functional programming. So I'm starting a brand new page, This will help #2059 too.

**Comment by JJ** [comment]
`&emit` is done, `&done` is not. I'm reopening to do it.
