### ISSUE TITLE
proto methods in signatures

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#1033]
Do we really need them? I mean cases like that:
```
    proto method from-loop(|)  Seq:D
    multi method from-loop(&body)
    multi method from-loop(&body, &cond, :$repeat)
    multi method from-loop(&body, &cond, &afterward)
```
The first signature just shows internal implementation detail, not a usage interface(if I'm correct). Isn't it would be better to remove it and add `--> Seq:D` to the other three signatures?
```
➜  doc git:(consistent-return-types) ✗ grep -I -r 'proto method' doc/Type/ | wc -l
7
```
And it doesn't seems to be popular in the docs. Should be removed?

**Comment by jonathanstowe** [comment]
The only thing that the proto brings to the party is the return value.  This could be copied to the other signatures.

**Comment by AlexDaniel** [comment]
I am not sure about this. Look:
```
multi method from-loop(&body --> Seq:D)
multi method from-loop(&body, &cond, :$repeat --> Seq:D)
multi method from-loop(&body, &cond, &afterward --> Seq:D)
```
Somehow I don't think it looks better.


Maybe this?
```
multi method from-loop(&body                    --> Seq:D)
multi method from-loop(&body, &cond, :$repeat   --> Seq:D)
multi method from-loop(&body, &cond, &afterward --> Seq:D)
```

**Comment by Altai-man** [comment]
The question about indentation here is not so important, the main question is `proto` presence, imho.

About the return type... While I worked with our signatures, I find out a terrifying thing that our return type notion is totally random. I mean, some methods have it, some methods not without any system. So maybe it's a question for a next big(I mean, really big) issue. But this `proto` thing just looks like it was copied from the rakudo code in some places.

**Comment by AlexDaniel** [comment]
If there are only 7 instances, just remove it.

**Comment by jonathanstowe** [comment]
I think in a lot of cases they _have_ been copied from the source yes,
