### ISSUE TITLE
Description of the cmp operator seems weird

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1036]
In this section: https://docs.perl6.org/type/Order#infix_cmp
it says "**Coerces it's arguments to Stringy.**"

However, in the other section: https://docs.perl6.org/routine/cmp#(Operators)_infix_cmp
it says "**Compares strings with string semantics, numbers with number semantics,** Pair objects first by key and then by value etc."

Which one is the correct description ?

**Comment by nicqrocks** [comment]
From looking at the code in Rakudo ([See this link](https://github.com/rakudo/rakudo/blob/beec02a6fa69e3ac290b4dd24c07d87a9f248b13/src/core/Order.pm)) it looks like it will primarily use the stringy form to compare it's arguments, but will use the same code that `<=>` does when it gets an Int type.
From this it looks like the description given in the [Operators](https://docs.perl6.org/routine/cmp#(Operators)_infix_cmp) section of the docs is correct, and the description in the [Order](https://docs.perl6.org/type/Order#infix_cmp) type needs to be changed.
