### ISSUE TITLE
｢is default｣ for subs is not searchable

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1040]
```
<babydrop> m: multi foo (Int) is default {say "here"}; multi foo (Int) {say "there"}; foo 42
<camelia> rakudo-moar a98724: OUTPUT«here␤»
<babydrop> m: multi foo (Int) {say "here"}; multi foo (Int) is default {say "there"}; foo 42
<camelia> rakudo-moar a98724: OUTPUT«there␤»
<babydrop> Neat.
<babydrop> TIL
<AlexDaniel> hmmm
<AlexDaniel> so what does it do exactly?
<moritz> it disambiguates ambiguous dispatches
```
(IRC log: https://irclog.perlgeek.de/perl6/2016-12-08#i_13703911)

**Comment by nicqrocks** [comment]
Wrote a small thing to try and fix this. See pull #1052.

**Comment by AlexDaniel** [comment]
Make it searchable

**Comment by Altai-man** [comment]
You can add a subsection header like `=head2 is_default (sub trait)`(or something along the lines) and it will be added to the index automatically. And, I suspect, it will be more readable with such distinction. I assume that header on Variable page should be changed too, for some consistency between these two.

**Comment by nicqrocks** [comment]
Added headers and changed the one for variables a bit. See pull request #1100.

**Comment by Altai-man** [comment]
Closed with a merged pull request. Feel free to reopen or just patch as needed.

**Comment by AlexDaniel** [comment]
Still not searchable.

**Comment by Altai-man** [comment]
Hmm, it seems that `trait of` is also not searchable.

Judging by grep, 
```
➜  doc git:(master) ✗ grep -I -r 'is dynamic' doc/
doc/Type/Variable.pod6:=head2 trait is dynamic
doc/Type/Variable.pod6:    my $x B<is dynamic> = 23;
```
it should be done. And `is dynamic` search anchor doesn't look like injected as some exception.

As for me, it is more strange that `is dynamic` is indexed now.

**Comment by AlexDaniel** [comment]
It's now indexed… **twice**.

![image](https://user-images.githubusercontent.com/5507503/29999590-3734dfc0-9057-11e7-9660-a1c61be2ae48.png)

I'll close this issue and create a new one so that it looks less scary.
