### ISSUE TITLE
Information about lexical module loading

### ISSUE THREAD

**Issue by niner** [perl6/doc#1043]
https://gist.github.com/niner/70f7b46eefb7e22af78d896bea11efeb describes the effects of merging the lexical_module_loading branch and what users need to do about this. It would be useful to have a place in the documentation to point to when submitting pull requests for fixing such issues and for answering user's questions that will inevitably arise once we merge this branch. Therefore it would be nice if we could include the gist somewhere.

Note that the described fix in user code could be considered a best practice anyway (being explicit about what modules one expects to be loaded) and that it's fully backwards compatible with older rakudos.

**Comment by jonathanstowe** [comment]
I'd say it could quite happily fit in with the language/modules page as a section on its own.
