### ISSUE TITLE
uniprop-* are not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1045]
https://docs.perl6.org/type/Int#routine_unival
https://github.com/rakudo/rakudo/blob/5476d60d09ec31690161eac1d9a876b2886e5ee0/src/core/Str.pm#L2993

**Comment by Altai-man** [comment]
Please, can you clarify this issue? What is wrong with this - http://storage3.static.itmages.com/i/16/1211/h_1481449847_3051205_6b92fa7717.png ?

**Comment by AlexDaniel** [comment]
It says that there is a “method unival” in Int, but there is no such method in Int. The method form is actually in cool which calls the sub form… uh, it's complicated!

See this pull request (because after it this is going to change): https://github.com/rakudo/rakudo/pull/945

**Comment by Altai-man** [comment]
So the task is to understand current situation and move sub/method descriptions from OldType to NewType(with optional examples update)?

**Comment by AlexDaniel** [comment]
Yes, but we probably want to wait just a little bit for this PR to go through.

**Comment by Altai-man** [comment]
List of work:
- [ ] unival - in Str and Int
- [ ] uniprop - in Cool
- [ ] uniprop-int - mentioned in Cool, but doesn't described(do we need it?)
- [ ] uniprop-bool - mentioned in Cool, but doesn't described(do we need it?)
- [ ] uniprop-str - mentioned in Cool, but doesn't described(do we need it?)
- [ ] uniprops - in Cool
- [ ] unimatch - in Cool
- [ ] uniname - in Cool
- [ ] uninames - in Cool

**Comment by JJ** [comment]
The three "dash" properties, do we need to describe them? That would leave only unival, which is already described in Int and Str

**Comment by AlexDaniel** [comment]
We do need to document them, but either I don't understand their functionality or these subs are simply broken.

Another thing is that there's a table on Cool that says which is coerced to what, and I think that for some of the subs mentioned here the table is incorrect (for uniprop at least).
