### ISSUE TITLE
Lookahead in regex is undocumented

### ISSUE THREAD

**Issue by mdinger** [perl6/doc#105]
Is lookahead for regexes currently supported? It's [undocumented](http://doc.perl6.org/language/regexes#Lookahead_assertions) currently.

**Comment by vendethiel** [comment]
It's `before`. It's described in S05 as well - so it's "documented" just not in a user-friendly fashion.

**Comment by mdinger** [comment]
Thanks @vendethiel. I tried to document it in https://github.com/perl6/doc/pull/106

**Comment by mdinger** [comment]
Fixed in https://github.com/perl6/doc/pull/106
