### ISSUE TITLE
Docs for SQL Profile

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1055]
December release of Rakudo will contain SQL as one possible output of profiler's data, however, I'm unaware of any documentation for what is what in those tables.

Granted, my SQL knowledge is rudimentary, but I can't make out what is what in this schema. `callees` table seems to have the data I'm most interested in, but it just has `caller_id`... which is what? `id` from `routines`?

Considering this is currently the only viable way to view profiles for large programs, it'd be nice to have some sort of SQL Profile 101 docs. Explanation on what tables/columns are about and a few sqlite commands one can copy-paste to get some idea of what's the slowest part or something.

/cc @MasterDuke17 

```
sqlite> .s
CREATE TABLE allocations(id INT, spesh INT, jit INT, count INT);
CREATE TABLE allocators(id INTEGER PRIMARY KEY ASC, name TEXT);
CREATE TABLE callees(caller_id INT, id INT, osr INT, spech_entries INT, jit_entries INT, inlined_entries 
    INT, inclusive_time INT, exclusive_time INT, entries INT, deopt_one INT, rec_depth INT);
CREATE TABLE gcs(time INT, retained_bytes INT, promoted_bytes INT, gen2_roots INT, full INT, 
    cleared_bytes INT);
CREATE TABLE profile(total_time INT, spesh_time INT);
CREATE TABLE routines(id INTEGER PRIMARY KEY ASC, name TEXT, line INT, file TEXT);
```

**Comment by MasterDuke17** [comment]
I'll put something in https://github.com/perl6/doc/blob/master/doc/Language/performance.pod6

**Comment by MasterDuke17** [comment]
https://github.com/perl6/doc/commit/54ce95c57d3d5813bfd18e038d210fd388d1b872 provides at least the bare minimum to get started.

**Comment by zoffixznet** [comment]
Thanks.
