### ISSUE TITLE
use File::Temp, not .pick

### ISSUE THREAD

**Issue by coke** [perl6/doc#1062]
We're currently relying on a random number to generate a temp file. Should use the ecosystem module.

**Comment by MasterDuke17** [comment]
I haven't looked at the recent commit, but I've run into a problem with File::Temp before (https://github.com/perlpilot/p6-File-Temp/issues/18) and suggest someone make sure that won't be an issue with the way it's used here.

**Comment by coke** [comment]
While we're in there, we should also not use 'pyg' anymore, since we're using highlights now.

**Comment by AlexDaniel** [comment]
There's also https://github.com/zoffixznet/perl6-Temp-Path

**Comment by coke** [comment]
We already have a dep on File::Temp, in use by one of the test files.
