### ISSUE TITLE
consider not generating PNGs.

### ISSUE THREAD

**Issue by coke** [perl6/doc#1063]
http://caniuse.com/#feat=svg

I have no problem supporting the type graphs only on the supported browser lists.

Less to do when building the docs, the better. Please comment below if you want to vote on this issue.

**Comment by AlexDaniel** [comment]
“Less to do when building the docs, the better”
How long does it take?

**Comment by coke** [comment]
I just did a make clean locally and timed the "writing type graph images" section - it took 6 minutes 40 seconds. This is cached for future builds (but in an all or nothing way that is probably slightly borked)

Also, it's not just a question of time. Code removed is code that is doesn't have to be maintained.
