### ISSUE TITLE
Remove all old pygmentize code

### ISSUE THREAD

**Issue by coke** [perl6/doc#1070]
No need to keep it when we've got our own Perl 6 highlighter code (courtesy @samcv) generating the docs now. Also remove the old CSS we don't need.

**Comment by samcv** [comment]
Do we want to remove the CSS or just remove it from the html template? It might be nice being able to look at the old CSS while we are tweaking the new one.

**Comment by zoffixznet** [comment]
> Do we want to remove the CSS or just remove it from the html template? 

Remove all code that's no longer used.

> It might be nice being able to look at the old CSS while we are tweaking the new one.

The code can be viewed in older commits. I also built a pre-highlights-merge version on http://doc.perl6.party/ if you want to use some web tools to inspect old code (it's still building as I write this).

**Comment by coke** [comment]
This seems done. Closing ticket.
