### ISSUE TITLE
Arguments isn't a type

### ISSUE THREAD

**Issue by jonathanstowe** [perl6/doc#1075]
The https://docs.perl6.org/type/Arguments is probably mis-placed, I'd suggest it belongs as part of the https://docs.perl6.org/language/objects#Roles if it isn't already covered, or just removed.

**Comment by Altai-man** [comment]
This page returns 404 now. @jonathanstowe, is this issue can be closed or we need to rename it to something like "Explain Arguments in language/objects"?

**Comment by jonathanstowe** [comment]
If it's removed it's fixed
