### ISSUE TITLE
Focus jumps to search field on hitting escape

### ISSUE THREAD

**Issue by rightfold** [perl6/doc#1078]
When hitting the escape key, the focus jumps to the search field, and this focus change scrolls the page all the way up. This is irritating when using the escape key to hide the ctrl+F search field (at least in Chrome, I can't speak for other browsers).

Steps to reproduce:

1. Open Chrome.
2. Go to https://docs.perl6.org/type/Signature
3. Ctrl+F, "role".
4. Escape to hide the ctrl+F search field.

**Comment by vendethiel** [comment]
Seems like [it's coded to work like that](https://github.com/perl6/doc/blob/master/html/js/main.js#L31)

I agree it's bit me as well,though.
