### ISSUE TITLE
Summary of Cool is less cool than Cool

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1095]
The summary for Cool says

> Value that can be treated as a string or number interchangeably

But, the first sentence is a bit more expansive:

> Cool, also known as the Convenient OO Loop, is a base class for strings, numbers and other built-in classes that you are supposed to use mostly interchangeably.

So many types get methods from Cool, and the interesting part is that Cool coerces to the appropriate type. It doesn't seem primarily concerned with string or number types because it also deals with containers (the more general term than Perl 6 uses and for which I can't think of something better) like lists and hashes. Something like .elems isn't really concerned with strings or numbers.

Could there be a better summary sentence? Maybe just "Base class for interchangeable types"? Something else that keeps the flavor of that longer sentence?

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/18f5adcedd992a0f4d3309c856e396e9a3616dcb

The string and number *are* the interesting bits as `Numeric` and `Stringy` methods is what the `Cool` provides. `.elems` is just a means to provide numeric view of an Array and similar objects.
