### ISSUE TITLE
An Instant can respond to .DateTime, but it's not listed as a method

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1096]
DateTime is not listed as a method for [Instant](https://docs.perl6.org/type/Instant), but Instant responds to it. So far there are no tests in roast for that (or most anything in Instant).

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/b4e10b6fbeea25f7a5e49e7a460542978f4c54a6 And roast coverage report [shows it as covered](https://perl6.wtf/SETTING__src_core_Instant_pm.coverage.html)
