### ISSUE TITLE
Superscript exponent not documented as operator on doc/Language/operators.pod6

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#1098]
At some point (hopefully soon), the Unicode superscript exponent operator should be documented together with the '**' operator on the "operators" page (source: [doc/Language/operators.pod6](https://github.com/perl6/doc/blob/master/doc/Language/operators.pod6)) under "[Exponentiation Precedence](https://docs.perl6.org/language/operators#Exponentiation_Precedence)".  The two operators are fairly identical in theory, but there is an open [RT #130414](https://rt.perl.org/Ticket/Display.html?id=130414) on differences in associativity.  As noted on the ticket, roast tests have been added and so identical behavior is part of the current spec.  User facing documentation is intended to reflect working features and it may be appropriate to hold off on documentation until the ticket is resolved (but not sure).

**Comment by JJ** [comment]
Not clear what is the problem here. The tests have been merged, although the ticket is not resolved. Anyone can clarify?

**Comment by rafaelschipiura** [comment]
@JJ The superscript form still isn't documented.
