### ISSUE TITLE
Doc generation fails for bigpage due to dependencies

### ISSUE THREAD

**Issue by benignbala** [perl6/doc#1101]
make html depends on bigpage and bigpage apparently needs "pod2onepage". The target should check for the presence of the binary and if not found, either git clone the library like it does in init_highlights, or shout that there is no pod2onepage and die. 

pod2onepage --threads=1 -v --source-path=./doc --exclude=404.pod6,/.git,/precompiled > html/perl6.xhtml
/bin/sh: pod2onepage: command not found
Makefile:27: recipe for target 'bigpage' failed
make: *** [bigpage] Error 127

**Comment by gfldex** [comment]
Please follow the install instruction in the README.md. All dependencies are installed automatically and that list will grow in the future. If you don't want to run bigpage you can ask make to do so with: `make init-highlights sass; perl6 htmlify.p6 --parallel=1`.

**Comment by benignbala** [comment]
@gfldex Thanks. I did follow the install instructions. And for FreeBSD, it did not install the dependencies for the bigpage target.

**Comment by gfldex** [comment]
Then you need to file an issue for the failing target. If possible provide automatic testing on FreeBSD so we can catch those problems without human attention. Pod::To::BigPage is a fairly simple module and if that is broken then there will be much bigger problems up the dependency chain.

**Comment by gfldex** [comment]
use `make htmlify` to skip bigpage

fixed with 9d98a021fa0d05d747187fb6f7b9b90afbda2626
