### ISSUE TITLE
htmlify.p6 leaks memory

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#1104]
The smallish old laptop may be my fault but I am having trouble understanding how a few meg of hand written pod files require more than 2Gig to convert to web pages.  The memory footprint keeps growing and somewhere around a 2.5 Gig virtual size (about 2 Gig RAM) it crashes with

```
Writing type document for IO::Spec::Cygwin ...
duplicated path /tmp/ron-76609-pod_to_pyg.pod
duplicated path /tmp/ron-20623-pod_to_pyg.pod
duplicated path /tmp/ron-79720-pod_to_pyg.pod
... more duplicated path lines ...
MoarVM panic: Memory allocation failed; could not allocate 1884356 bytes

```

**Comment by ronaldxs** [comment]
```Perl6
use Pod::To::HTML;

# This sample code leaks.
# After noticing that perl6/doc/htmlify.p6 seemed to leak memory
# I tested for a leak against the smallest file in the doc tree ...
#   doc/Type/X/Pod.pod6
# If you take out the code block that pod does not seem to leak.

=begin pod

    No code block, no leak, no problem.

=end pod

my $last-pod;
loop (my $i = 0; $i < 1_000_000; $i++) {
    say $i if $i %% 10_000;
    $last-pod = Pod::To::HTML.render($=pod[0]);
}
say $last-pod;

```

**Comment by ronaldxs** [comment]
One likely culprit is a Proc::Async/tap leak documented in [RT #130494](https://rt.perl.org/Ticket/Display.html?id=130494)

**Comment by faraco** [comment]
I have 1GB ram for my machine, but it is require memory more than I expected. In the end, I have to download a precompiled documentation at https://docs.perl6.org/perl6.xhtml

**Comment by ronaldxs** [comment]
As noted on ticket [RT 130494](https://rt.perl.org/Ticket/Display.html?id=130494), the Proc::Async leak seems essentially fixed.   I then went and retested the POD codeblock leak and that seems fixed too. "make html" now builds for me on 32-bit Ubuntu with 2 GB ram.  If I don't hear back otherwise then planning to close this ticket in a day or two.
