### ISSUE TITLE
Mix/Bag/etc. mention method reverse which talks about order, but there is no order

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1105]
For example, the docs on [Mix](https://docs.perl6.org/type/Mix) include method reverse, which says this:

> Returns a list with the same elements in reverse order.

However, Mix is unordered, so there is no “reverse order”. Yes, this description gets mixed in from Any, but to someone reading the docs for the first time it may not be so clear.

Is there any way we can fix that?

**Comment by AlexDaniel** [comment]
Yes, it can return items in any order.

**Comment by JJ** [comment]
I wonder why reverse was placed so low in this hierarchy... Problem now is that the note will have to be repeated in all four classes.
