### ISSUE TITLE
Depending on Mix/Bag/etc. order is a trap, let's document it as such

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1107]
We should have a separate item in [traps](https://docs.perl6.org/language/traps) that will explain why depending on order of unordered collections is a bad idea. Also see https://github.com/perl6/doc/issues/1105 and https://github.com/perl6/doc/issues/1106.

**Comment by shadowcat-mst** [comment]
The traps entry would be a great place to make a parallel to the SQL SELECT-without-ORDER problem.

    18:55 < mst> note that lots and lots of people (including past-mst) run 
                 face-first into the fact that lots of SQL database implementations
    18:55 < mst> return things in PK order -most- of the time because that's more 
                 convenient to the implementation
    18:55 < mst> thereby leading to people not realising that the order is 
                 'whatever the db feels like' unless you provide ORDER BY
