### ISSUE TITLE
Add FAQ pages (like the ones perldoc has)

### ISSUE THREAD

**Issue by smls** [perl6/doc#112]
The [perldoc FAQs](http://perldoc.perl.org/index-faq.html) were always a popular part of Perl 5's official documentation, and I think it would be good to have something similar for p6doc as well.  
Especially since I've come across cases while improving language/ or type/ docs, where I though "Hey, ideally we'd factor out this longer example or side-discussion into a FAQ entry and merely link to it from here".

I think perdoc's categorization of FAQ entries into 9 topical pages is pretty good, so I'm suggesting a similar set of pages. However, the page names like `perlfaq6` *(which show up in the URL in the web interface, and can be entered by users directly in the console client)* aren't exactly user-friendly, so I'd like us to use descriptive names of the form `faq-regex` instead.

As for the page titles *(which show up at the top of each page, in links, and in the browser titlebar)*, I think using a `FAQ: ` prefix is important, because these pages will live in the same namespace as other language doc pages and we want to make them easily identifiable.

I'd also like us to use custom anchors for FAQ entries (see #111), because all those question marks and other stuff in the section URLs will get ugly, and these FAQ entries are things that people *will* want to link to.

So here's my proposed list of 9 FAQ pages (`Name` - **Title** - *Summary*):

---

* `faq-general` - **FAQ: General** - *General Questions About Perl 6*
  * What Perl 6 is
  * What it means for the language and implementation to be separate
  * Who created it & who maintains it
  * How it is licensed
  * How it compares to other languages
  * Larry's two rules (if those still apply)
  * Whom to contact for official purposes (Perl Foundation, right?)
  * ... (see [perlfaq1](http://perldoc.perl.org/perlfaq1.html) for inspiration)

* `faq-start` - **FAQ: Getting Started** - *Obtaining, learning, and getting comfortable with Perl 6*
  * What implementations exist, their status, and where to download them
  * How to play around with Perl 6 most easily (REPL, one-liners)
  * Where to find good books, tutorials and blogs about Perl 6
    * How to best learn Perl 6 as a Perl 5 programmer
  * Where to find Perl 6 modules (CPAN)
  * Where to helpful Perl 6 related forums, mailing lists, and IRC channels
  * Where to send bug reports
  * How to debug Perl 6 code (Rakudo's built-in debugger, Grammar::Debugger, ...)
  * How to enter the Unicode characters which are commonly seen in Perl 6  
    *(Currently there's a whole [stand-along language/ doc](http://doc.perl6.org/language/unicode_entry) about this, but I'd really like to kill it.)*
  * What editor/IDE support is available for Perl 6 (syntax highlighting,
    ctags integration, etc.)
  * ... (see [perlfaq2](http://perldoc.perl.org/perlfaq2.html) for inspiration)

* `faq-why` - **FAQ: Justifications** - *Why things are the way they are in Perl 6*
  Perldoc does not have an equivalent to this, but I think it makes sense for us to have it, so that there's an easy place to link to for this stuff.
  * Why it's called Perl 6 and not something else
  * Why Perl 6 has so many operators (compared to other languages)
  * Why Perl 6 has sigils
  * Why Perl 6 doesn't inflect sigils anymore like in Perl 5
  * Why the ternary conditional operator was changed
  * ... *([faq.perl6.org](http://faq.perl6.org) has some stuff that belongs here)*

* `faq-basics` - **FAQ: Basic Language Usage** - *General Perl 6 programming issues*
   Common questions about Perl 6 programming fundamentals ([faq.perl6.org](http://faq.perl6.org) has a bunch of stuff that belongs here, and also see [perlfaq7](http://perldoc.perl.org/perlfaq7.html) for inspiration)

* `faq-data` - **FAQ: Data Manipulation** - *Issues related to data structure munging in Perl 6*
  Anything related to data structures and data munging (except IO). (See [perlfaq4](http://perldoc.perl.org/perlfaq4.html) for inspiration.)

* `faq-regex` - **FAQ: Regexes & Grammars** - *Issues related to regexes and grammars in Perl 6*
  Should be self-explanatory. (See
  [perlfaq6](http://perldoc.perl.org/perlfaq6.html) for inspiration.)

* `faq-files` - **FAQ: Files & File Formats** - *Dealing with files, filesystems and file formats in Perl 6*
  Everything related to reading from / writing to / listing / finding / modifying files, as well as dealing with file formats. (See [perlfaq5](http://perldoc.perl.org/perlfaq5.html) for inspiration.)

* `faq-sys` - **FAQ: System Interaction** - *Interacting with the running computer system in Perl 6*
  * How to interact with the terminal
  * How to interact with pipes
  * How to fork
  * How to spawn and controll external processes (like `expect`)
  * How to interact with a Unix system and do various things that a sysadmin  
    might want to do (e.g. decrypt/parse password files)
  * How to interact with databases
  * ... *(see [perlfaq8](http://perldoc.perl.org/perlfaq8.html) for inspiration)*

* `faq-net` - **FAQ: Web & Networking** - *Dealing with the Web, Email & networks in Perl 6...*
  TBH, I'm not sure if we need this one. Perldoc probably has the corresponding [perlfaq9](http://perldoc.perl.org/perlfaq9.html) for historic reasons (the days when Perl was the glue of the WWW). But is it appropriate to have a whole FAQ page for this in p6doc, when there isn't even a stable web framweork nor a CGI solution for Perl 6? OTOH, "How do I download a webpage" wil be a common question that should be answered somewhere.

---

The one perldoc FAQ without an equivalent in this list is [perlfaq3 ("programmer tools and programming support")](http://perldoc.perl.org/perlfaq3.html) which seems like a somewhat messy collection of different things to me, which would be better sorted into one of the other categories. Not to mention that Perl 6, as a spec language, is less concerned with "official" tooling than perl was.

So (moritz and others), is this a plan you can support?
Any comments / suggestions?

PS: See also #114 for the larger roadmap which this ties in to.

**Comment by moritz** [comment]
FWIW http://faq.perl6.org/ exists, and it follows the philosophy of actually answering questions that are frequently asked (on #perl6 and/or the perl6-users mailing list), instead of trying to anticipate what the FAQ.

I think the idea of pre-structuring the FAQs is flawed before knowing which questions are/will be frequently asked. I'd rather collect more FAQs as they are asked, and group them once we have them.

**Comment by uvtc** [comment]
To me, a large faq may indicate that the actual docs need improvement. (After all, if it's asked so frequently, why isn't it covered in the regular docs?)

**Comment by coke** [comment]
My suggestion is to make faq.perl6.org redirect to a link under doc.perl6.org, and then we can maintain the FAQ with the rest of the docs.

**Comment by moritz** [comment]
I've followed @coke's suggestion and moved the FAQ to inside this repository.

And we only need a more structured FAQ once we get more of them. So I'm closing this now.

**Comment by jonathanstowe** [comment]
:+1:
