### ISSUE TITLE
Document use of method invocant to distinguish between class and object methods

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#1121]
See also perl6/roast [#217](https://github.com/perl6/roast/issues/217) and [IRC](https://irclog.perlgeek.de/perl6/2017-01-05#i_13862614).

The technique is sometimes used by examples in the docs but not really described in either of [Classes and Objects](https://docs.perl6.org/language/classtut) or [Object Orientation](https://docs.perl6.org/language/objects).  It would seem helpful to have it discussed directly someplace where someone might look for it.

```Perl6
class C {
    multi method f(::?CLASS:U:){say "class method"}
    multi method f(::?CLASS:D:){say "object method"}
}
C.f;       # says class method
C.new.f;   # says object method
```

**Comment by zakame** [comment]
Hi, I think I can help out on this.  I suppose this would be elaborated more on [Object Orientation](https://docs.perl6.org/language/objects), to keep the class tutorial simple?

**Comment by zoffixznet** [comment]
> I suppose this would be elaborated more on Object Orientation, to keep the class tutorial simple?

Sounds good. Perhaps in the [Methods](https://docs.perl6.org/language/objects#Methods) section?

**Comment by zakame** [comment]
Yep, that section sounds good.  And since `multi` is shown here, I suppose linking to [declarator `multi`](https://docs.perl6.org/syntax/multi) might be needed (since there's no example of multi-methods prior to this yet...)

**Comment by ronaldxs** [comment]
Move to "Class and Instance Methods" section after Classes/self.

PR discussion: https://github.com/perl6/doc/pull/1495#issuecomment-326747280

**Comment by zakame** [comment]
@ronaldxs I have the change to add header (before `Methods` and after `self`,) is that fine?  If so, I can commit it directly.

**Comment by ronaldxs** [comment]
planning to close soon if no objection ...
