### ISSUE TITLE
Precompiled documentation for download

### ISSUE THREAD

**Issue by faraco** [perl6/doc#1126]
I think it will be better if there is pre-compiled html(in zip/tar/gz)/pdf/epub/mobi  uploaded somewhere for anyone that doesn't have constant internet connection and for machines that have low memory - #1104 to compile them manually, to download for offline reading.

There is https://docs.perl6.org/perl6.xhtml, but I don't really know if it's updated to recent version.

**Comment by Altai-man** [comment]
I believe it is related to https://github.com/perl6/doc/issues/718.

**Comment by stmuk** [comment]
There is an existing p6doc which shows offline docs already

**Comment by faraco** [comment]
I can't believe I missed #718 in the issue search. So, this is officially duplicate I guess.
