### ISSUE TITLE
htmlify without --no-proc-async hangs on MacOS

### ISSUE THREAD

**Issue by coke** [perl6/doc#1129]
Using the default Promise-enabled highlight path you get when not specifying --no-proc-async hangs on OS X.

```
This is Rakudo version 2016.12-269-ge182deb built on MoarVM version 2016.12-100-gf9e14e9
implementing Perl 6.c.
```

Gets to "Writing programs document for Perl 6", and then hangs processing the highlights in the callback.

**Comment by coke** [comment]
Now it just dies:

```
$ perl6 htmlify.p6
Initializing ...

==================================================================================================================================================
"\$*DISTRO == macos, so Proc::Async will not be used.
            due to freezes from using Proc::Async.
            For more info see Issue #1129
==================================================================================================================================================

Cannot assign to an immutable value
  in sub MAIN at htmlify.p6 line 166
  in block <unit> at htmlify.p6 line 1018
```

**Comment by samcv** [comment]
It should hopefully work as of 54fa9b43

**Comment by AlexDaniel** [comment]
@coke, hm, can you test it again then?

**Comment by coke** [comment]
This seems to works around the problem by not allowing that option to be used on the mac; not ideal, but closes the original issue.

**Comment by samcv** [comment]
This should stay open until the actual source of the problem is fixed. Also the workaround prints out a reference to this ticket, so we should keep this open.

The freezing doesn't happen, but it's just worked around, not really solved.

**Comment by gfldex** [comment]
Please note that hfs+ is case-preserving but case-insensitive. As such quite a lot subs/methods will be unaccessible on OSX. To my knowledge apfs is case-sensitive but they may add mount options later to change that. So even if it would build, it's barely useful for QA.

**Comment by samcv** [comment]
@gfldex how is that relevant to this bug? Did post that on the wrong bug, or is there a problem with Proc::Async due to case-insensitivity in Rakudo?
