### ISSUE TITLE
Nil vs Any confusion (trap)

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1134]
Which should it be? Here's what it does now.

	grammar Number {
		rule TOP { \d+ }
		}

	my @strings = '137', '137 ', ' 137 ';

	for @strings -> $string {
		my $result = Number.parse( $string );
		say "Result is { $result.^name }";
		given $result {
			when Match { put "<$string> worked!" }
			when Any   { put "<$string> failed!" }
			}
		}

And the result:

	Result is Match
	<137> worked!
	Result is Match
	<137 > worked!
	Result is Any
	< 137 > failed!

**Comment by ronaldxs** [comment]
I think there may be some confusion about the behavior of Nil here.  From the docs [https://docs.perl6.org/type/Nil](https://docs.perl6.org/type/Nil) 

> When assigned to a container, the Nil value (but not any subclass of Nil) will attempt to revert the container to its default value; if no such default is declared, Perl 6 assumes Any. 

```perl6
grammar G { token TOP { a+ } };
my Nil $n = G.parse("zz");
say $n.WHAT;
my $result = G.parse("zz");
say $result.WHAT;
```
prints
```
Nil
(Any)
```

**Comment by jonathanstowe** [comment]
It does return Nil, what you are seeing there is the effect  of assigning  ```Nil``` to  an ```Any``` typed variable:

```
grammar G { token TOP { a+ } };
say G.parse("zz").WHAT; #  -> Nil
```

**Comment by briandfoy** [comment]
Duh. I'm an idiot. Thanks,

**Comment by AlexDaniel** [comment]
Do we have it explained somewhere in the docs? If yes, where?

**Comment by jonathanstowe** [comment]
Though it's not specific to Grammar, it's just what happens when you assign ```Nil``` to a variable, I don't know what happens under the hood, but the nett effect is that the variable is the same type object that it would have been without the assignment, It thus allows you to *unset* a variable without knowing what type it is.

I'd go with making sure this is documented clearly in the variables page  and make sure that Nil is searchable with a clear explanation somewhere.

**Comment by AlexDaniel** [comment]
I don't know where this could be documented, but I've seen this confusion a couple of times.
Another interesting point is that arrays can contain Nils:
```
my @a = 4, 8, 15, 16;
@a[2] = Nil;
say @a; # OUTPUT: «[4 8 (Any) 16]␤»
@a[3] := Nil;
say @a; # OUTPUT: «[4 8 (Any) Nil]␤»
```

Let's document it as a trap perhaps?

**Comment by W4anD0eR96** [comment]
https://irclog.perlgeek.de/perl6/2017-10-30#i_15374966

```
14:38 | lizmat | m: my %h is default(Nil) = a => Nil; dd %h
14:38 | camelia | rakudo-moar 497e0582e: OUTPUT: «Hash %h = {:a(Nil)}␤»
14:38 | lizmat | jdv79: ^^^
14:38 | jdv79 | oh, that makes sense
14:38 |            | thanks
14:40 | geekosaur | the core issue is that, in an assignment, Nil usually means use the default value for the type. so you need the default to also be Nil
```

**Comment by W4anD0eR96** [comment]
Text about it can be found at https://docs.perl6.org/type/Nil#index-entry-Nil_assignment

**Comment by JJ** [comment]
@briandfoy , would the text linked by @W4anD0eR96 be enough?
