### ISSUE TITLE
Create language/unicode page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1142]
> \<izmat\> m: say "\c[woman facepalming]"  # now that we can do this, maybe a docs.perl6.org page about emoji support would be applicable ?
> \<camelia\> rakudo-moar 2a7c27: OUTPUT«🤦‍♀️␤»

And not just emojis, we should have a page with more information on how Perl 6 supports unicode and what features are there.

**Comment by AlexDaniel** [comment]
@samcv ? :)

**Comment by samcv** [comment]
Yeah this would be good. I will write something up :)

What is needed to add a new docs page? Just put a Pod file into the correct folder?

**Comment by jonathanstowe** [comment]
@samcv yes pretty much

**Comment by Altai-man** [comment]
The page is created - https://docs.perl6.org/language/unicode, what features are missing there, but must be explained?

**Comment by AlexDaniel** [comment]
Something about normalization perhaps? And some links to other unicode pages?

**Comment by samcv** [comment]
Normalization and something about utf8-c8, and filenames are reading using utf8-c8, if you want to retain text in non-normalized form you need to spurt and slurp using :enc('utf8-c8') and such as well.

**Comment by rafaelschipiura** [comment]
It would also be nice to document the utf8 type.

**Comment by AlexDaniel** [comment]
For the third TODO item (utf8-c8) we now have:
* https://docs.perl6.org/language/unicode#File_Handles_and_I/O
* https://docs.perl6.org/language/unicode#UTF8-C8
* https://docs.perl6.org/language/traps#All_Text_is_Normalized_By_Default

For utf8 type:
* I created a separate issue: https://github.com/perl6/doc/issues/1516

The first TODO item is again mentioned here:
* https://docs.perl6.org/language/unicode#File_Handles_and_I/O
* https://docs.perl6.org/language/unicode#UTF8-C8
* https://docs.perl6.org/language/traps#All_Text_is_Normalized_By_Default
But it feels like something is lacking, so I created this ticket: https://github.com/perl6/doc/issues/1517
