### ISSUE TITLE
Avoid linking to anchors, since they don't work in extracted pages.

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1144]
Looking at https://docs.perl6.org/routine/made, there's an anchor link to https://docs.perl6.org/routine/made#method_make, but that anchor does not appear on that page. The links back to the defining classes have the same problem.

This is an extract for a single routine from another page with a list, so these sorts of links should be fixed-up in the translation.

**Comment by JJ** [comment]
Related to #561 , I guess.

**Comment by JJ** [comment]
There are quite a few:
```
doc [master] % git grep "L<#" | wc
     84     785    7633
doc [master] % git grep "|#" | wc 
    119    1811   75212
```
This creates lots of incorrec anchors in #561. We would need to go at them, one by one...

**Comment by JJ** [comment]
Also, discuss what is the "canonical" link, either to the "big", original page or to the generated page. I would opt for the first.

**Comment by JJ** [comment]
I'm afraid that after all this time, I'm closing this one. As indicated above, there are ~200 links that work that way, and they are mostly unavoidable. If you want to link a particular method in a particular class, you might have to use anchors if there are more that are called the same way. Either linking to the class page or to the method page, you'll have to use anchors. Of course, after #1823 we might find a unique URL for any such combination, but that would have to be a requisite which, for the time being, is not on the table.
