### ISSUE TITLE
Rules for escaping characters in enumerated character classes could be clearer

### ISSUE THREAD

**Issue by shicks** [perl6/doc#1146]
I was trying to write `<-[ \] \s ]>` but had a very difficult time figuring out how to do this from the documentation.  Perl5 mentions their special cases for `[^]]` pretty eagerly, so I was trying to do something similar.  Attempting to use `'` to quote didn't work either, and there were no examples of using `\` for simple escaping.

**Comment by AlexDaniel** [comment]
This ticket is about this section: https://docs.perl6.org/language/regexes#index-entry-regex_%3C%5B_%5D%3E-regex_%3C-%5B_%5D%3E-Enumerated_character_classes_and_ranges
