### ISSUE TITLE
Profile docs refer to broken bot function

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1147]
The profile docs mention [prof-m command](https://docs.perl6.org/language/performance#Profile_with_prof-m:_your_code_goes_here) but it seems [to be busted](https://irclog.perlgeek.de/perl6/2017-01-19#i_13954006) and gives a 404 URL

**Comment by coke** [comment]
Would be nice if prof-m got fixed instead of having to remove the section.

**Comment by coke** [comment]
... But we can only control our end. Removing…
