### ISSUE TITLE
add docs for dynamic LHS and RHS method calls

### ISSUE THREAD

**Issue by jdv** [perl6/doc#115]
Aka ::($c).m and A."$m"().

**Comment by AlexDaniel** [comment]
Where should this documentation go? What would be the first place people are going to look at to find these things?

**Comment by AlexDaniel** [comment]
There's some info here: https://docs.perl6.org/language/packages#index-entry-%3A%3A%28%29

**Comment by AlexDaniel** [comment]
- [ ] ::($c).m
- [ ] ::($c).m is searchable
- [ ] A."$m"()
- [ ] A."$m"() is searchable
