### ISSUE TITLE
make clean doesn't remove html/.html…

### ISSUE THREAD

**Issue by coke** [perl6/doc#1153]
…Ideally, we shouldn't even be creating this file, but since we are, clean it up.

BTW, the title is
```
  <title>Disambiguation for &#39;&#39;</title>
```

**Comment by coke** [comment]
in

```
doc/Language/5to6-nutshell.pod6
```

the line

```
=head3 X<C<constant>|constant>
```

is the first thing that causes an empty .html to be generated.

And it's this block of code from htmlify that extracts the empty name:

```
when :("", Pod::FormattingCode $, "") {
```

**Comment by JJ** [comment]
Why does it happen that way? Maybe because of the `C`?
