### ISSUE TITLE
Add syntax highlighting to code examples in docs

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1156]
Syntax highlighting to code examples (especially in tutorials) would help with readability / helping beginners see that it's not just line noise.

**Comment by coke** [comment]
We are already doing syntax highlighting.

Feel free to re-open if you have a specific example that isn't getting syntax highlighting.

**Comment by WildYorkies** [comment]
It must have broken everywhere then. 

You can see my UA info here: http://www.whatsmyua.com/#Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

And you can see a screenshot below.

![2017-01-23 13_59_26-object orientation](https://cloud.githubusercontent.com/assets/1299322/22218327/4b6d93ac-e174-11e6-9b7d-50ab66c5554a.png)

**Comment by Altai-man** [comment]
I double this issue. I thought highlighting was turned off for some reason. Latest firefox.

I do see highlighting classes in html, but they are still not colored. It used to work for me some time ago.

**Comment by jonathanstowe** [comment]
Yeah, I checked earlier, the highlighting transformation appears to be happening in most places but it isn't loading the stylesheet I think.

**Comment by coke** [comment]
samcv noted that one of the nodepm packages we depend on changed all their class names without warning. b1d51f1 was supposed to help, but I don't see any changes on the site yet.

**Comment by coke** [comment]
see also 0193f3e4dc and 9525968e78

**Comment by samcv** [comment]
docs.perl6.org is fixed now as of https://github.com/perl6/doc/commit/9525968e78ac239b69a975d8ff56fa2813aabe68
Closing!

**Comment by WildYorkies** [comment]
It looks like some are fixed depending on what css is:

![image](https://cloud.githubusercontent.com/assets/1299322/22228816/8f25571a-e1a1-11e6-928c-235f10cf1285.png)

`class="editor editor-colors"` works, but `class="pod-block-code"` does not.

**Comment by samcv** [comment]
That is not the same problem. That is related to what is in the pod6 files the docs are created from. Anything tagged as pod-block-code usually means that's what the block was inside tho doc file

'=begin code :allow<B L>` that is on the page you showed the screenshot of. If it has `:allow` then it renders as Pod not as perl 6 code

**Comment by WildYorkies** [comment]
@samcv Should it be left open as a "someone can feel free to change this so it's consistent" type of task?

**Comment by samcv** [comment]
I think there's another ticket for that, not sure which

**Comment by samcv** [comment]
But it's not the original issue, which is why I closed it. It's a separate problem

**Comment by samcv** [comment]
If you can't find one, please open an issue for it.
Make sure to paste this into the issue:

The pod6 file has `:allow` in the code designation:
`=begin code :allow<B L>` that is on the page you showed the screenshot of. If it has `:allow` then it renders as Pod not as perl 6 code

Thanks

**Comment by samcv** [comment]
@WildYorkies I have opened an issue here for this https://github.com/perl6/doc/issues/1164

I also wrote my proposed solution for this, and a more detailed explanation of why this currently happens.
