### ISSUE TITLE
Document the GLR

### ISSUE THREAD

**Issue by smls** [perl6/doc#116]
The GLR (Great List Re-implementation) is in full swing. For p6doc this will require documentation additions and changes all over the place. To coordinate those, let's use this github issue to list relevant doc changes that we'll want to undertake.

### Document the the list/iterating system in the language reference

This can be covered by the new "**Data Structures**" and "**Iterating**" pages proposed by issue #114. Discuss them there.

### Document the affected and newly added types in the API docs

Here are the user-visible types which are being added or affected by the GLR, as well as which subcategory we should put them into in our type index and what subtitles we could give them:

---

##### Types ⏵ Composite ⏵ <i>Arrays and friends</i>

<img src="http://i.imgur.com/N1hBMxt.png"></td>

<table>
<tr>
    <td>    <code>role</code>  </td>
    <td><b> <code>Positional</code>  </b></td>
    <td><i>       Object that supports looking up values by index  </i></td>
</tr><tr>
    <td>    <code>class</code>  </td></td>
    <td><b> <code>List</code>  </b></td>
    <td>          Immutable sequence of values  </td>
</tr><tr>
    <td>    <code>class</code>  </td></td>
    <td><b> <code>Slip</code>  </b></td>
    <td>          Immutable sequence of values that dissolves into parent lists  </td>
</tr><tr>
    <td>    <code>class</code>  </td></td>
    <td><b> <code>Array</code>  </b></td>
    <td>          Mutable sequence of values  </td></tr>
</tr>
</table>

##### Types ⏵ Composite ⏵ <i>Support types for iterating</i>

<img src="http://i.imgur.com/TmR5pGd.png"></td>

<table>
<tr>
    <td>    <code>role</code>  </td>
    <td><b> <code>Iterable</code>  </b></td>
    <td><i>       Object that can be traversed sequentially  </i></td>
</tr><tr>
    <td>    <code>role</code>  </td>
    <td><b> <code>HyperIterable</code>  </b></td>
    <td><i>       ...  </i></td>
</tr><tr>
    <td>    <code>class</code>  </td>
    <td><b> <code>Seq</code>  </b></td>
    <td>          Generator for a sequence of values  </td>
</tr><tr>
    <td>    <code>class</code>  </td></td>
    <td><b> <code>HyperSeq</code>  </b></td>
    <td>          Parallelized generator for a sequence of values  </td>
</tr>
</table>

##### Types ⏵ Domain-specific ⏵ <i>The iterator system (low-level)</i>

<table>
<tr>
    <td>    <code>role</code>  </td></td>
    <td><b> <code>Iterator</code>  </b></td>
    <td><i>       Internal state during traversal of a sequence of values  </i></td>
</tr><tr>
    <td>    <code>role</code>  </td></td>
    <td><b> <code>HyperIterator</code>  </b></td>
    <td><i>       Internal state during parallelized traversal of a sequence of values  </i></td>
</tr><tr>
    <td><code>    ...  </code></td>
    <td><b> <code>IterationBuffer</code>  </b></td>
    <td><i>       ...                                                                  </i></td>
</tr><tr>
    <td><code>    ...  </code></td>
    <td><b> <code>HyperWorkBatch </code>  </b></td>
    <td><i>       ...  </i></td>
</tr><tr>
    <td><code>    ...  </code></td>
    <td><b> <code>HyperConfiguration</code>  </b></td>
    <td><i>       ...  </i></td>
</tr><tr>
    <td><code>    ...  </code></td>
    <td><b> <code>PositionalBindFailover</code>  </b></td>
    <td><i>       ...  </i></td>
</tr><tr>
    <td></td><td> ... </td><td></td>
</tr>
</table>

---

I'll try to update this listing as things change.

### Misc

* Comb all docs for places that refer to `Parcel`, and update them to refer to `List` instead
* Comb all docs for places that show example snippets with the binding operator `:=` &ndash; many of them will want to use assignment instead, or be rewritten altogether.

Corrections/suggestions welcome.

**Comment by awwaiid** [comment]
I think most of this is done or obsolete now -- the main thing left is removing some stray := usages. I think almost all are fixed now though, so can we close this?

**Comment by awwaiid** [comment]
@smls what do you think -- closeable?

**Comment by awwaiid** [comment]
Hearing no objections, and having looked around for Parcel and other now-wrong references and finding none, closing this issue.
