### ISSUE TITLE
Modified quantifier should be better explained.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#1163]
https://docs.perl6.org/language/regexes#Modified_quantifier:_%

It's not clear that quantifier in `a+ % ','` example is applied to delimited items count instead of character class. I had to check Roast test to see that this:

```
$ perl6 -e 'say "aa,aaaa,aaa" ~~ /a+ % ","/'
｢a｣  # ooops!
```

Should be double wrapped like:

```
$ perl6 -e 'say "aa,aaaa,aaa" ~~ /[a+]+ % ","/'
｢aa,aaaa,aaa｣
```

I think adding additional more complex example should make it more clear:

```
$ perl6 -e 'say "foo,bar,baz" ~~ / [\w+] ** 2 % "," /'
｢foo,bar｣
```

And here is the design discussion for reference: https://irclog.perlgeek.de/perl6/2011-09-20#i_4453865

**Comment by AlexDaniel** [comment]
FWIW I agree that this is not a trap, but a simple misunderstanding that should be covered in ``language/regexes``. A trap would be something that makes you think that your code works, but in reality there are edge cases that may lead to disastrous results. We should delete some sections from ``language/traps`` that do not match this definition.

**Comment by rafaelschipiura** [comment]
So, reopening because the docs on quantifiers are still LTA.

**Comment by AlexDaniel** [comment]
@rafaelschipiura I was thinking that https://github.com/perl6/doc/commit/a206c6080ed02baa4eb593756f669b8c298f6e1f is enough, I guess not. What exactly is less than awesome?
