### ISSUE TITLE
Search box occasionally does not show up

### ISSUE THREAD

**Issue by moritz** [perl6/doc#117]
When I load http://perl6.org/ by entering the URL, the search box doesn't show up; when I follow a link to another page, it shows up on that page, and when I then follow a link to the front page, it shows up again. When reloading the front page, it occasionally shows up, but not always.

Others have reported similar issues for other pages as well.

**Comment by moritz** [comment]
Firebug says in the console window:

    ReferenceError: jQuery is not defined
    ReferenceError: $ is not defined

**Comment by moritz** [comment]
... probably because the jquery .js is included with `async`, so it might not be available at the time search.js is included.

**Comment by laben** [comment]
I can confirm the issue. Trying to force-reload with Ctrl+F5 in Chrome shows perfectly that the search box does not appear half the times.
