### ISSUE TITLE
Comments in a snippet about ｢throw｣ are weird

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1170]
https://docs.perl6.org/routine/throw

```perl6
    my $exception = X::AdHoc.new; # Totally fine
    try $exception.throw;             # Throws
    if ($!) { #`( some handling ) };                   # Suppress the exception in a
```

“Suppress the exception in a” ? Something is missing, not sure what exactly.

**Comment by Altai-man** [comment]
Yes, it was introduced by me during the last summer. I actually noticed and fixed it in my last big PR, but it is still on Coke review.
I can fix it separately, if the PR will be rejected, basically it should be "Suppress the exception above". "Suppress the exception" or something along the lines.

**Comment by coke** [comment]
I don't see a PR for this that is pending my review, assuming someone applied it.

**Comment by coke** [comment]
Also, please tag me with the "@" in comments so I get notified more directly.

**Comment by AlexDaniel** [comment]
@coke https://github.com/perl6/doc/pull/1165

**Comment by Altai-man** [comment]
Closed with "Suppress the exception". Though can be reworded in a better manner, but this can be done in just one direct commit if anyone concerns.
