### ISSUE TITLE
--parallel option to htmlify.p6 trips rakudo bugs

### ISSUE THREAD

**Issue by coke** [perl6/doc#1175]
Issue was golfed down on coke/bughunt branch - used to segfault, now just getting odd concurrency errors.

Need to fix this so we can make parallel building the default.

**Comment by jnthn** [comment]
With Rakudo HEAD, after fixing a few races in precompilation code, the golf in the `coke/bughunt` branch now seems to run reliably at least. Alas, `htmlify.p6 --parallel=2` in master still has issues. Investigating.

**Comment by coke** [comment]
This is a dupe of #664. Closing.
