### ISSUE TITLE
Add explanation that Str.comb(3) chunks the string in groups of 3

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1177]
https://docs.perl6.org/type/Str#routine_comb

Right now, no explanation that comb does double duty as a chunker.

**Comment by WildYorkies** [comment]
Because of the duplication of comb in Cool and Str, not sure where this should be added.

**Comment by coke** [comment]
It's there under Str:

```
multi sub    comb(Int:D $size, Str:D $input, $limit = Inf)
```

```
multi method comb(Str:D $input: Int:D $size, $limit = Inf)
```

'''
If the matcher is an integer value, it is considered to be a matcher that is similar to / . ** matcher /, but which is about 30x faster.
```

It's also referenced on class IO::Handle

The integer form is not supported on cool:

```
$ perl6 -e ' 123456.comb(/3/).say'
(3)
$ perl6 -e ' 123456.comb(3).say'
Cannot resolve caller comb(Int: Int); none of these signatures match:
    (Cool $: *%_)
    (Cool $: Regex $matcher, $limit = Inf, *%_)
    (Cool $: Str $matcher, $limit = Inf, *%_)
  in block <unit> at -e line 1
```

Rejecting ticket.

**Comment by WildYorkies** [comment]
You mind if I add an example that shows chunking?

It's a very commonly required task, and I would not expect people to know what "`it is considered to be a matcher that is similar to / . ** matcher /`" means. I certainly have no idea what that means.

**Comment by b2gills** [comment]
I think it is just a bug that this form of `.comb` doesn't work on Cool.

**Comment by WildYorkies** [comment]
https://github.com/perl6/doc/commit/11c89a09f865ad5ce9ec9e62d2ece27dfc281a6a

Added examples that explicitly show chunking on Str type.

@b2gills I guess there's a reason `routine comb` has a separate entry on Cool though. If it was meant to work the same for everything, it would only have one entry in the docs on the Cool type.

**Comment by b2gills** [comment]
Actually looking through the commits it was added to Cool
[Add limit to Str.comb, add comb(Int:D..) candidate](https://github.com/rakudo/rakudo/commit/bcbdc1d1fa65d7206a551b08185a761da93712f5)  
but is somehow not in the source at that very same [commit](https://github.com/rakudo/rakudo/blob/bcbdc1d1fa65d7206a551b08185a761da93712f5/src/core/Cool.pm#L280).

Like I said it is a bug
