### ISSUE TITLE
Postfix `for` examples

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1178]
> Mithaldu	would be nice if https://docs.perl6.org/language/control#for contained postfix examples

https://irclog.perlgeek.de/perl6/2017-02-03

**Comment by gfldex** [comment]
fixed with 9936aa808084d18f784b694624ae6dacfff5f49c

**Comment by LLFourn** [comment]
It's worth mentioning that the correct term for these is "statement
modifier" rather than "postfix".

Chcek out: http://perldoc.perl.org/perlsyn.html#Statement-Modifiers
