### ISSUE TITLE
Not each(or so it seems) operator is also available as a subroutine

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#1179]
https://docs.perl6.org/language/operators.html#Operator_classification
>Each operator is also available as a subroutine

Seems to be false, see
```
> m: circumfix:«( )»('a', 'b', 'c')
> rakudo-moar c98b3a: OUTPUT«===SORRY!=== Error while compiling <tmp>␤Undeclared routine:␤    circumfix:<( )> used at line 1. Did you mean 'circumfix:<{ }>', 'circumfix:<:{ }>', 'circumfix:<[ ]>'?␤␤»
```
And the example
```
m: circumfix:«( )»('a', 'b', 'c'); # same as ('a', 'b', 'c')
```
doesn't work. Needs investigation, clarification and fixing! @zoffixznet++.

**Comment by gfldex** [comment]
there is no circumfix:<( )> operator.
fixed with 02a3832889
