### ISSUE TITLE
Invalid HTML Is Generated (Double links)

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#118]
For example on this page: http://docs.perl6.org/routine/is-prime

If you look at the source, "routine is prime" is wrapped by two links:

![screenshot from 2015-08-22 09 51 07](https://cloud.githubusercontent.com/assets/5747918/9424249/a04a29a4-48b3-11e5-865e-15ddde2acf4d.png)

**Comment by coke** [comment]
Closing this in favor of #584
