### ISSUE TITLE
list.pod6 example is broken

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#1184]
https://docs.perl6.org/language/list.html#Sequences - the second example. The comment says about an error, but this code actually works and it loops forever. Seems like a pre-GLR example, so it needs to be investigated and resolved: do we need to remove this example or do we need to rewrite it?

Don't forget to remove `:skip-test`(if it will be there) if the result will be finite.

**Comment by coke** [comment]
This example was added by @skids in 4a47be526cf4631fee8a8bb862d84bee38ee6821 - just after Christmas.

I'm just going to remove that paragraph and example.

**Comment by gfldex** [comment]
m: my @s := Seq.new(<a b c>);
OUTPUT«Type check failed in binding to $iter; expected Iterator but got List ($("a", "b", "c"))␤  in block <unit> at <tmp> line 1␤␤»

**Comment by gfldex** [comment]
fixed with 1619a0683c
