### ISSUE TITLE
Match.chars missing

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#119]
Hi,

According to synopsis of regex (S05) the Match class has a ```chars()``` method which returns the difference of the values of methods ```to()``` and ```from()```. On the doc page about Match there is a ```chars()``` method mentioned under the Cool class. But that one has a different meaning.

Greets

**Comment by moritz** [comment]
It's not a different meaning. Match stringifies to the matched string, and its length is the same as `.to - .from`. And `Cool.chars` coerces to Str, so the two are the same.
