### ISSUE TITLE
Supply.skip, Any.skip, and Any.batch not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1195]
Implemented in https://github.com/rakudo/rakudo/commit/8a6bfc6, https://github.com/rakudo/rakudo/commit/d71bf1e , https://github.com/rakudo/rakudo/commit/15753fd , https://github.com/rakudo/rakudo/commit/e0201f15dffcef82af8750a3d8ca77341b0a8e7f , and https://github.com/rakudo/rakudo/commit/f6531d366f2f620ad5a79319ea47e66d96860596

Tests should be located in S17-supply/skip.t, S32-list/skip.t, and S32-list/batch.t

**Comment by dogbert17** [comment]
Supply.skip has now been fixed, see fe2398a56e1ea8f6d5dc466d09f2990103fee6d3.

**Comment by JJ** [comment]
- [ ] Document `any.skip`
- [ ] Document `any.batch`
