### ISSUE TITLE
extract examples fails silently to regen some files.

### ISSUE THREAD

**Issue by coke** [perl6/doc#1198]
```
run xt/examples-compilation.t Language/haskell-to-p6.p6
```

remove examples/Language/haskell-to-p6.p6

```
run xt/examples-compilation.t Language/haskell-to-p6.p6
```

This re-runs the extraction, but the deleted file is not regenerated.

**Comment by coke** [comment]
Ah, it's deliberately being skipped.

**Comment by Altai-man** [comment]
I left 5to6 and similar pages out of scope, because they naturally tend to have a lot of "skip-test" directives and it makes testing quite useless in such cases.

**Comment by coke** [comment]
-1 from me on skipping files. we should be marking the individual untestable snippets, and testing everything else. (even if the whole file is skipped - the time saved on each run for not processing the file is nothing compared to the maintenance issue of remembering to unskip when an un-skippable bit of code is added) There's another ticket for this specifically for the haskell file
