### ISSUE TITLE
Using constants as hash keys (trap)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1201]
Code:
```perl6
constant V = 'x';
my %h = V => 'a';
say %h
```

Output:
```
{V => a}
```

**Comment by zoffixznet** [comment]
A smorgasbord of ways to make it work, for reference: https://irclog.perlgeek.de/perl6/2017-02-17#i_14121957

**Comment by gfldex** [comment]
fixed with b8af670621
