### ISSUE TITLE
internet searches are unreliable for finding our stuff

### ISSUE THREAD

**Issue by timo** [perl6/doc#1205]
A recent mailing list thread alerted us to the problem that searching "perl 6 stderr" will not lead to our docs page at all. for that specific topic there's a result for the tablets which is helpful, but it's buried deep beneath unhelpful stuff, including the RFC about barewords from ~2004. The search engine used was duckduckgo in this example.

We might want to come up with a systematic approach for figuring out what features/topics will lead users to our docs page (or any similarly appropriate resource) and what sends the user off on a wild goose chase.

**Comment by toolforger** [comment]
On 20.02.2017 02:56, timo wrote:
> A recent mailing list thread alerted us to the problem that searching
> "perl 6 stderr" will not lead to our docs page at all.

The first hit on Google is https://docs.perl6.org/routine/stderr .
Is that not the right page?

 > The search engine used was duckduckgo in this example.

The first hit there is the same as with Google.

> We might want to come up with a systematic approach for figuring out
> what features/topics will lead users to our docs page (or any similarly
> appropriate resource) and what sends the user off on a wild goose chase.

Let me put up a warning sign here: One might think that SEO is an 
answer, and for commercial endeavors that can command lots of manpower 
this can even work.
My personal systematic approach would be "make the pages of interest 
easy to find from a landing page for humans, and search engines will 
follow". After all, search engines are programmed to pick up the lead of 
human interest (as well as they can, of course).

I think there are various systematic things one can do.

One would be to keep track of questions, cluster them (by keywords), and 
see which topics come up more often. Those that are more common are 
likely to be less easy to find, so work on these. (I.e. don't do a FAQ 
list, do a list of topics.)
I don't know how to keep the RTFM questions out of that list though. 
Maybe don't keep them out but rate questions on a newbie-to-expert scale.

Make sure that authoritative material is easily discernible as such.
There's a big amount of historic material. For much of that, no current 
authoritative material is available.

Listen if somebody complains that a given piece of information was hard 
to find.

Whenever you help somebody figure out something, ask yourself where an 
uninformed person would have found it.
Maybe set up a project: "Learn from the newbies". Describe the question 
and the answers found, and let uninformed people tell you where they 
would have looked for the answers.

FWIW :-)

**Comment by gfldex** [comment]
I try to link to the docs whenever I blog or post on reddit. If you post on stackoverflow please do the same.

**Comment by AlexDaniel** [comment]
So? What's the current problem?

**Comment by AlexDaniel** [comment]
OK I see. So somebody wrote “perl 6” into a search engine and got many unrelated historical stuff. I just tried it through Tor and there many good results actually. IMO this problem will be resolved once we [figure something out with the name](https://github.com/perl6/6.d-prep/tree/master/TODO#language-extended-naming), and then we'll be getting the freshest results (unless we go with something that is already overused like *psix*). As an example, you can search for `6lang` now and you'll see some actual perl 6-related results plus some weak unrelated stuff (even though nobody is using it yet!). Soo… maybe we can close this for now?

**Comment by AlexDaniel** [comment]
Checked again, in duckduckgo one of the results on the first page is https://www.perl.org/. Yes, internet searches are indeed unreliable for finding our stuff. Closing this issue according to my previous comment.
