### ISSUE TITLE
“without involving a shell (if possible)”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1208]
[Documentation for ``run``](https://docs.perl6.org/type/IO#sub_run):
> Runs an external command without involving a shell (if possible).

What's the idea behind this “if possible” remark? If it decides to pass your thing to the shell then all of sudden you have a security hole. I don't remember any code for that, so does anybody have any idea what this thing is about?

And also, if it's not covered by roast then let's just delete it.

**Comment by tbrowder** [comment]
@gfldex added that chunk, but the words seem familiar. (there seem to be formatting errors in the example).

**Comment by b2gills** [comment]
`system` in Perl 5 will go through the shell if given one string, and on Windows it does so even for `echo` and `dir` for example.

So it sounds like a copy paste of a description of that.

(mostly?) fixed with [the latest commit](https://github.com/perl6/doc/commit/a8feef1689a8a1657f3e5f16c122c390bffc5e23)

I would say something along the lines of <q>without involving the shell</q>, but what is there now is at least not wrong.

**Comment by gfldex** [comment]
Did anybody actually checked if `run` does not execute a shell on all supported OS and VMs?

**Comment by b2gills** [comment]
If it does that is a bug, it should call `spawn*` or `exec*` type system calls. If those involve the shell it is a bug in the operating system.

**Comment by zoffixznet** [comment]
> Did anybody actually checked if run does not execute a shell on all supported OS and VMs?

I'm no expert, but [`run`](https://github.com/rakudo/rakudo/blob/80e0bce/src/core/Proc.pm#L142-L149) / [`shell`](https://github.com/rakudo/rakudo/blob/80e0bce/src/core/Proc.pm#L150-L156) respectively call [`.spawn`](https://github.com/rakudo/rakudo/blob/80e0bce/src/core/Proc.pm#L102-L113) / [`.shell`](https://github.com/rakudo/rakudo/blob/80e0bce/src/core/Proc.pm#L115-L126) methods on Proc object. These map to [nqp ops `spawn` and `shell`](https://github.com/perl6/nqp/blob/master/src/vm/moar/QAST/QASTOperationsMAST.nqp#L2845-L2846) that [map](https://github.com/MoarVM/MoarVM/blob/16eac8499428cc69e2dfb257d094937aba27ad4d/src/core/interp.c#L3823-L3826) [to](https://github.com/MoarVM/MoarVM/blob/16eac8499428cc69e2dfb257d094937aba27ad4d/src/core/interp.c#L3687-L3691) MoarVM's [`MVM_proc_spawn`](https://github.com/MoarVM/MoarVM/blob/16eac8499428cc69e2dfb257d094937aba27ad4d/src/io/procops.c#L273-L350) and [`MVM_proc_shell`](https://github.com/MoarVM/MoarVM/blob/16eac8499428cc69e2dfb257d094937aba27ad4d/src/io/procops.c#L184-L271)

The shell version has obviously-looking shell bits, while the spawn doesn't.

Same with JVM version [`shell`](https://github.com/perl6/nqp/blob/9b67b175d80601b6a4c88a3c98b907b94db07081/src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java#L1064-L1080) has shell bits wrapped up first and then a call to some sort of `spawn` routine is done. And [`spawn` op](https://github.com/perl6/nqp/blob/9b67b175d80601b6a4c88a3c98b907b94db07081/src/vm/jvm/runtime/org/perl6/nqp/runtime/Ops.java#L1082-L1093) don't got any such bits.

JS backend just forwards [`spawn`](https://github.com/perl6/nqp/blob/9b67b175d80601b6a4c88a3c98b907b94db07081/src/vm/js/nqp-runtime/io.js#L419-L421) and [`shell`](https://github.com/perl6/nqp/blob/9b67b175d80601b6a4c88a3c98b907b94db07081/src/vm/js/nqp-runtime/io.js#L428-L430) just forwards to `nqpIo.spawn`  and `nqpIo.shell`; for which I've no idea where the sauce is at.

**Comment by coke** [comment]
The docs are up to date; any bugs in rakudo should be opened in RT.
