### ISSUE TITLE
Sleep routines are not documented

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#121]
It would be great to have them searchable in bar

**Comment by paultcochrane** [comment]
Just pushed some docs for the `sleep`-related functions.  It should be live on the server in half an hour or so.  If that's what you were after, simply close the ticket.  If not, let me know what else you'd like to have and I'll extend the docs.

**Comment by teodozjan** [comment]
Great, it seems to be enough to know how to use it. I reviewed it for copy-paste mistakes also.
