### ISSUE TITLE
backslash and fancy quotes confuse highlighter

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1210]
see example for https://docs.perl6.org/type/IO#sub_run

**Comment by coke** [comment]
If it's the highlighter, it's an issue with the external tool we're using, and should be raised there.

**Comment by AlexDaniel** [comment]
Also, I'm not seeing anything wrong on the page mentioned. So what's wrong exactly? I can open the issue in https://github.com/perl6/atom-language-perl6/issues and close this, but I'm not sure what the actual problem is.

**Comment by AlexDaniel** [comment]
Also, unassigning @samcv until the issue is clear enough. Issues filed in https://github.com/perl6/atom-language-perl6/issues get @samcv attention anyway.

**Comment by samcv** [comment]
@gfldex can you say what the problem is? I'm not sure what it is? I could have fixed the issue since then, or the docs could have changed, but if you can give me a snippet. I tried the below code, but maybe you remember what the issue was?

```perl6
‘blah\a’ blah
‘blah\\a’ blah
‘blah\\’ blah
```

**Comment by gfldex** [comment]
Seams to be fixed already. Spooky bugfix at a distance.
