### ISSUE TITLE
Make IO::Socket::Async first example more explicit

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1213]
https://github.com/perl6/doc/blob/master/doc/Type/IO/Socket/Async.pod6#L32

- [x] change `$p` to `$promise`
- [ ] change anonymous block to a pointy block with a good name. Does the promise return the listening socket, or does it return the connecting socket? I think it returns the connecting socket because it is `print`ing _to_ the listening socket and then it closes itself after it gets a response.
- [ ] Clear up where `.Supply` is coming from? The listening socket, I would presume.

**Comment by lancew** [comment]
Can be closed?

**Comment by moritz** [comment]
Sure, feel free!

**Comment by WildYorkies** [comment]
@lancew any thoughts on my other two checklist items?
