### ISSUE TITLE
Constraining Return Types needs an update

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1218]
https://docs.perl6.org/type/Signature#index-entry---%3E-returns-Constraining_Return_Types
> The return type arrow has to be placed at the end of the parameter list. The keyword returns following a signature declaration has the same function

AFAIK timtoady wants arrow to replace `returns`, but regardless, `-->` has some additional abilities that `returns` does not have. Can't recall what exactly.

**Comment by Altai-man** [comment]
Well, if you read a bit further, there will be:

>Although all the ways are valid, the --> form is preferred for several reasons: (1) it can handle constant values while the others can't; (2) for consistency, it is the only form accepted on this site; and (3) the returns form is planned for future removal.

It explains

>AFAIK timtoady wants arrow to replace returns

and it explains
> --> has some additional abilities that returns does not have

Does it need *more clear* explanation or not is arguable, but the info is still here. Can you exactly explain what do you want to see here?

**Comment by WildYorkies** [comment]
Ah, can't believe I missed that.

## What is the future of the other two forms?

`of is just the real name of the returns keyword, and the prefix(C-like) form can be used too`

Since `of` is an alias for `returns`, that will go the way of the dodo eventually too? What about the prefix form?

## Improve the organization of this section.

Perhaps it would be better to have this section broken into 4 clear subsections like:

* -->
* returns
* of
* prefix form

**Comment by Altai-man** [comment]
>What is the future of the other two forms?

Well, I believe this question should be discussed between core members.

>Improve the organization of this section.

This can be done to clarify the topic, I assume.

**Comment by WildYorkies** [comment]
I can draft up a quick version that re-organizes the section. Not sure where to open the issue for that question though.

**Comment by Altai-man** [comment]
You can ask on #perl6 irc channel. Though, all 4 forms exist for some reasons and I doubt there will be drastic syntax changes, but you always can ask.
The PR with re-organization will be welcome.

**Comment by WildYorkies** [comment]
a4fb28da9ecf0ac8b7879fd7dd38cc1177634bbd
