### ISSUE TITLE
! meta operator not documented

### ISSUE THREAD

**Issue by LLFourn** [perl6/doc#1227]
I just go burnt because I thought `!==` was the shorthand for negated `===` like `!=` is the shorthand for `==`. Turns out `!==` is actually the same as `!=` and the right answer is `!===`. I went to the docs and noticed:

1. `!==` is not searchable (`!=` is)
2. `!===` isn't mentioned anywhere /operators

**Comment by b2gills** [comment]
`!===` is not an operator.

It is the `!` meta operator combined with the `===` operator.

`!=` is just an alias to `!==` which is also a combination of two operators.

(I personally think that `!=` should be deprecated, partially for this reason)

**Comment by coke** [comment]
We could allow any search for !foo (perhaps only under Infix/Postfix, etc.) to return foo as a hit.

**Comment by LLFourn** [comment]
@b2gills I agree with deprecating `!=`. Fundamentally, its existence was the source of my confusion. 

Since `!` is a metaoperator I think the if you're searching for `!==` for example it should just come up with `! (negation meta operator)` and `==` as different results.  The negation meta operator page doesn't exist, we only have `! (prefix)`. I'm going to rename this ticket to reference that instead.

On another point we have a (meta operators)[https://docs.perl6.org/language/operators#Meta_Operators] section, but there is nothing listed underneath and it doesn't explain the concept at all.

**Comment by AlexDaniel** [comment]
Woah, woah… deprecating ``!=``. What a big stretch :)

That said, now that we have ``≠``, I wouldn't miss ``!=`` at all.

**Comment by AlexDaniel** [comment]
It's not that ! metaop is not searchable, it seems we have no documentation for it at all.

**Comment by AlexDaniel** [comment]
Actually, it is documented in https://docs.perl6.org/language/operators#Negated_Relational_Operators.
