### ISSUE TITLE
doc mexico form of ⁇ ‼

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1228]
depends on Rakudo release in March.

**Comment by AlexDaniel** [comment]
e4d341bbc532ff6f887230cd1feee9ba0d0f0631, anything else?

**Comment by AlexDaniel** [comment]
Yes, it's not searchable.

**Comment by zoffixznet** [comment]
Closing this until and if the characters are added again to Perl 6.

See https://rt.perl.org/Ticket/Display.html?id=131002
