### ISSUE TITLE
Undocumented :translate-nl option to Str.encode

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1233]
Added to Rakudo in https://github.com/rakudo/rakudo/commit/0a2eef8fb0adb24164999a2b71c415fd11fe748a but isn't documented.

**Comment by jnthn** [comment]
For what it's worth, it's not in roast either yet - which in turn reflects that I'm still pondering whether it's the right name and the right peg to hang it on.

**Comment by zoffixznet** [comment]
It's kinda long to type :)

**Comment by jnthn** [comment]
I don't expect it to be typed often. :-) I was wondering if `translate-crlf` would be more clear what it's about.

**Comment by jnthn** [comment]
By the way, the reason I don't expect it to be typed often is because most encoding happens at I/O boundaries, and we can make good defaults for 99% of cases (we already do so). So this would mostly be relevant to folks who are implementing their own I/O-like things. Not entirely common.

**Comment by JJ** [comment]
Still not in roast. Would it be worth the while to document it now, indicating it's Rakudo-specific?

**Comment by jnthn** [comment]
I think, having had time to get used to the name, we can roast it. We still need to do an audit of the various IO types where it might be used and make sure they expose it and pass it along to the decoders and encoders. I don't know if on handles or similar where you can read and write we should expose an in and out form. But for the decoder case of it as being discussed here, then it's pretty clear there's only one thing it's talking about.

**Comment by JJ** [comment]
OK. I can do the roast test, and then come back here to add the
documentation. Anyone else wants to do it, feel free.

**Comment by JJ** [comment]
It's now in roast after above PR was accepted, so I'll proceed to document it.
