### ISSUE TITLE
“Since” column on unicode_texas page is useless

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1236]
See [the table](https://docs.perl6.org/language/unicode_texas#Other_acceptable_single_codepoints).

For ``⁇ !!``, ``≤``, ``≥``, ``≠`` it says “v6.c”, but that's less than awesome because rakudo version 2015.12 (which implements v6.c) does not have them. There must be a way to indicate this somehow.

**Comment by b2gills** [comment]
Since it wasn't actually tested in `v6.c` it should say either `v6.c.1` or `v6.d`

**Comment by coke** [comment]
Neither of those are appropriate either, since those spec's haven't been decided on.

I would list, for now, the rakudo compiler version they first became available in; we can replace that with the spec once it's decided. I recommend, e.g.

```
[Starting in Rakudo-2017.02]
```

**Comment by coke** [comment]
Since we don't have this information anywhere else, and we don't have it here, I'm going to remove it. We can address it when we have a unified plan for how to address multiple versions of the spec/compiler adherence to same.
