### ISSUE TITLE
Another possible trap: %h<a b>:exists

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1242]
Not sure if this is a big enough trap, but it just got me, so…

I had code like this:
```perl6
my %h = <a 1 b 2>;
say ‘hello’ if %h<a>:exists;
say ‘world’ if %h<x>:exists;
```

Output:
```
hello
```

Then I decided to check for more than one element, and using slices is what came to my mind immediately:

```perl6
my %h = <a 1 b 2>;
say ‘hello’ if %h<a b>:exists;
say ‘world’ if %h<x y>:exists;
```

Output:
```
hello
world
```
Not exactly what I hoped for!

Thinking about it, it makes sense. Still, perhaps it is worth to mention something like this as one of the traps (are there any other traps similar to this one?).

**Comment by WildYorkies** [comment]
@AlexDaniel Why does that make sense? What happened exactly?

**Comment by b2gills** [comment]
%h<x y>:exists

returns a list of 2 elements, and that list is True

So you really need something like this

   say ‘world’ if all %h<x y>:exists;

**Comment by AlexDaniel** [comment]
Yes, depending on what you want exactly, you should use ``any`` *or* ``all``.

The fact that it returns the element itself (and not a list with one element) is a possible source for other traps. It makes sense because this is what you mean in most cases, but when you start generalizing you stumble upon completely different behavior.
