### ISSUE TITLE
Talk about low level constructs vs high level ones in Performance doc

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1243]
https://docs.perl6.org/language/performance#Solve_problems

Talk about the difference between writing multis and writing given/when constructs. Multis are on C level, given/when is on Perl 6 level (slower)

Any other situations that are like this?

**Comment by AlexDaniel** [comment]
Uhh… True, it would be nice to have something like this, but this is implementation-specific. I don't think we can have some language guarantees about performance.

**Comment by WildYorkies** [comment]
@AlexDaniel I didn't think about that. Good point.

**Comment by AlexDaniel** [comment]
@WildYorkies I think the right place for it is rakudo wiki: https://github.com/rakudo/rakudo/wiki

I don't know if we want to keep ticket this open or not.
