### ISSUE TITLE
Ruby uses ===, not ==, in case statements

### ISSUE THREAD

**Issue by dfhoughton** [perl6/doc#1247]
In the comparison of Perl 6 with Ruby, it says Ruby lacks a smart match operator and uses == instead. This isn't quite right. Ruby uses the `===` method, which performs a similar function to `~~`. So `Class === foo` matches if `foo` is a `Class`, `/rx/ === foo` matches if the regular expression matches `foo`, `1 === foo` matches if `foo` equals 1, `'string' === foo` matches ... In general `===` delegates to `==`, but it is overridden in `Class` and regular expressions, and can be overridden as needed to make case statements work more intuitively in other ways.

**Comment by dfhoughton** [comment]
I'd add the "docs" label, but it seems no labels are available to me.

**Comment by Altai-man** [comment]
If I remember correctly, it was @awwaiid who was an author Ruby-related document.
@awwaiid, what do you think about it?

**Comment by zoffixznet** [comment]
@dfhoughton I sent you an invite to Perl 6 GitHub org; you can accept it on https://github.com/perl6/

Would you be able to fix the docs and close this issue? I'm assuming you're talking about Ruby-to-Rakudo page, in which case you can just edit this file directly on GitHub: https://github.com/perl6/doc/edit/master/doc/Language/rb-nutshell.pod6

**Comment by awwaiid** [comment]
:+1:
