### ISSUE TITLE
Generated HTML shouldn't need to be run in docroot

### ISSUE THREAD

**Issue by coke** [perl6/doc#125]
To simplify testing, IWBNI all the HTML/JS/CSS links were relative.

Looks like all the HTML is in the top level directory, so we don't have to deal with different relative pathing at all.

**Comment by coke** [comment]
Bah, some content is in subdirectories, which means we do have to track the relative pathing. Still doable, though.

**Comment by coke** [comment]
... Found a third party tool that lets me serve up the directory as if it were root. Using that, rejecting my own ticket.

**Comment by moritz** [comment]
@coke, fwiw there's also a `app.pl` in the root dir of the repo, which serves the generated files via HTTML (it's a Mojolicious p5 app).
