### ISSUE TITLE
block following a sub call confuses highlighter

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1251]
```
say {1}.();
```
see https://docs.perl6.org/type/Block

**Comment by samcv** [comment]
This has been fixed in master for atom-language-perl6, and I've triggered this rebuild. Will close as soon as rebuild completes. I've added a test to the highlighter to cover this as well.

**Comment by samcv** [comment]
Fixed, closing :smile:

**Comment by MARTIMM** [comment]
Hi,
Found a mistake in the doc (or a misfuncton of my brain) on page 
http://docs.perl6.org/language/quoting at section 'Word quoting: qw'.
The first example uses the .words method at the end which I think should 
not be there for eqv to work.

Regards,
Marcel

P.s. Did I ever mention that the documentation is getting more awesome 
every day? Well, it is!
