### ISSUE TITLE
Error when running test

### ISSUE THREAD

**Issue by nkh** [perl6/doc#1264]
/pod-htmlify.t ......1/4No such method 'spurt' for invocant of type 'IO::Handle+{File::Temp::File::Temp::AutoUnlink}'
  in block <unit> at t/pod-htmlify.t line 58

**Comment by coke** [comment]
This is likely due to a recent change in rakudo's IO internals by @zoffixznet 

Should be fixed in the next release, or you update your rakudo to the latest on the nom branch.

**Comment by zoffixznet** [comment]
I reworded the test to avoid use of the super-new IO::Handle.spurt
