### ISSUE TITLE
Define "reify" somewhere

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1265]
These two sentences documenting Array.clone uses a form of "reify" several times. Various discussions outside of the docs throw it around freely.

> However, note that the reifier is shared between the two Arrays, so both Arrays will have the same elements even when each is randomly-generated on reification and each element will be reified just once, regardless of whether the reification was done by the clone or the original Array. Note: just as reifying an Array from multiple threads is not safe, so is, for example, reifying the clone from one thread while reifying the original from another thread is not safe.

As far as I can tell, the term is only used twice anywhere else in the docs. Once in [control.pod6](https://github.com/perl6/doc/blob/master/doc/Language/control.pod6) and once in [traps.pod6](https://github.com/perl6/doc/blob/master/doc/Language/traps.pod6). It does not show up where it matters: [Seq](https://docs.perl6.org/type/Seq) and [Range](https://docs.perl6.org/type/Range).

There's a definition in [S99](http://design.perl6.org/S99.html#reification), but it's a bit of a tarbaby for the beginner programmer who doesn't know the additional formal terms presented in that definition.

**Comment by raiph** [comment]
Fwiw, http://stackoverflow.com/a/31876747/1077672 begins with "Reification is the process of taking an abstract thing and creating a concrete thing.".

**Comment by briandfoy** [comment]
The more I think about it, the more I think "reify" shouldn't show up in user docs. It's only in three places.

In the Perl 6 docs, it's more important that the user know what is happening than the jargon used to describe it. Array.clone might say "If there are lazy lists in the array, the original and clone may share them and their future values" or something like that.

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/8472cde81cda620222429e23bfe2758622b2b6c5

> The more I think about it, the more I think "reify" shouldn't show up in user docs. It's only in three places.

It's only in three places because the docs are incomplete. The concept of reification is pretty important in Perl 6, both to know how to avoid it (e.g. huge lists) when you don't need it and to know how to cause it (e.g. when working with file handles and other resources that get closed/go away).

**Comment by JJ** [comment]
I am going to reopen this issue. We need to unify the definition of reify, which actually means two things:
* "Vivification" or computation of elements in a lazy list
* Itemization of elements in an array, turning the slot occupied for a container into its value.
Unifying concept is "turning a potential element into its computed value". And FWIW, I don't think a glossary entry is enough. Either its own page or something in the context page (item context, for instance).

**Comment by JJ** [comment]
Additionally, maybe it should just be called itemization.

**Comment by JJ** [comment]
The reification concept is now all over the documentation. I guess it's much better to explain what we mean in the glossary than changing everything. Anyway, where it's not clear what it could mean, I'll change it to "itemize" or "vivify"
