### ISSUE TITLE
The control exception namespace (and everything under it) is not documented

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1268]
I found an exception `CX::Warn` but that doesn't show up in the [Types](https://docs.perl6.org/type.html) documentation.

This comes from my Stackoverflow question [Where should I catch a Perl 6 warning control exception?](http://stackoverflow.com/q/43243412/2766176).

**Comment by AlexDaniel** [comment]
This is actually specced. E.g. see https://github.com/perl6/roast/search?utf8=%E2%9C%93&q=CX%3A%3AWarn&type=

**Comment by JJ** [comment]
See #517

**Comment by JJ** [comment]
The pages have been added, now we have to add the backlinks.
