### ISSUE TITLE
better cross-linking? Selective Importing

### ISSUE THREAD

**Issue by szabgab** [perl6/doc#1270]
I was looking to understand how to tell ```use``` that I'd like to selectively import functions.
I got to https://docs.perl6.org/syntax/use but there was nothing about it.
Later I was pointed at https://docs.perl6.org/language/modules#Exporting_and_Selective_Importing

As I understand the former page is actually an extract from the latter, but in any case I think it would be nice if the page about ```use``` pointed to the selective importing section in the other page.

**Comment by tbrowder** [comment]
I did the additional and work in the docs on selective importing sometime lst year, but discussed it better later in my Perl 6 Advent blog for 2016 (Dec 12).  Maybe it could be the basis of a doc section. Thoughts?

**Comment by szabgab** [comment]
@tbrowder I don't know about that, but I've added the link I was missing so closing this issue now.
