### ISSUE TITLE
Junctions and failures inside of them

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1271]
See [RT #131118](https://rt.perl.org/Ticket/Display.html?id=131118).

Basically, we should simply mention that failures inside Junctions are OK, but they *will* blow up when you try to use these Failures unintentionally

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/7628708384bdc049d74c997fc2059cf57fcf5a57
