### ISSUE TITLE
Document how try works, and what resume is doing

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1274]
I can't give a better title for this issue because there are so many hidden things I'm still unaware of. Jonathan explained some of them in [his answer](http://stackoverflow.com/a/43293323/2766176) to [Should this Perl 6 CATCH block be able to change variables in the lexical scope?](http://stackoverflow.com/q/43289842/2766176).

**Comment by AlexDaniel** [comment]
* ``try`` itself is explained here: https://docs.perl6.org/language/exceptions#try
* ``resume`` is mentioned in https://docs.perl6.org/language/exceptions#Resuming_of_Exceptions

Can we have a todo list of things that should be done? I'll start:

- [ ] ``use fatal`` is not mentioned

**Comment by tbrowder** [comment]
This **resune** section example mentioned by @AlexDaniel needs to be shown in a loop or other block to clearly show control flow with output.
