### ISSUE TITLE
Document the fatal pragma

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1275]
Jonathan mentions this in [Should this Perl 6 CATCH block be able to change variables in the lexical scope?](http://stackoverflow.com/a/43293323/2766176). It's referenced in [the docs for fail](https://docs.perl6.org/syntax/fail) and part of the list in [Pragmas](https://docs.perl6.org/language/pragmas).

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/8da79bb26e89709c30b8660d8dcdc0e9cc05fd7f
