### ISSUE TITLE
Possible trap when using constants

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1276]
See this tweet: https://twitter.com/zoffix/status/850511016303525888

**Comment by timo** [comment]
If you want run-time constants, just use sigilless variables instead? it
makes sense to me that constants would be compile-time, otherwise they'd
change value between compile time and run time and thus not be constant
in the first place ...

**Comment by AlexDaniel** [comment]
@timo do you think I can copy your message to the [traps page](https://docs.perl6.org/language/traps)? Or what's the point of your comment?

**Comment by timo** [comment]
with a little bit of better wording, probably :)

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/bcbef20ead1044f0211c5f450c23632f56badf0c
