### ISSUE TITLE
Perl 6 doesn't have kill

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1277]
The [p5-p6 perlfunc for kill](https://docs.perl6.org/language/5to6-perlfunc#kill) says

> Now part of the L<Proc::Async> class, but looks to work as in Perl 5.

As far as I can tell, this only lets you send a signal to a process you started and there's no (documented) way to provide a PID.

    method kill(Proc::Async:D: $signal = "HUP") {
        X::Proc::Async::MustBeStarted.new(:method<kill>, proc => self).throw if !$!started;
        nqp::killprocasync($!process_handle, $*KERNEL.signal($signal));
    }

That `killprocasync` is really in MoarVM as far as I can tell, but even at the NQP level I lose all my bearings. 

As such, it seems this doesn't work at all like the Perl 5 version. It might be too late to change the name of the method so it doesn't carry the baggage of the expectations of the real thing called `kill`, but it doesn't work as it does in Perl 5. I'd probably document this as "not in Perl 6, so shell out". 

I wasn't so much interested in the termination aspects of kill as the "is the process still running" abilities, especially for processes not started by the one I'm currently in.

**Comment by Leont** [comment]
> I wasn't so much interested in the termination aspects of kill as the "is the process still running" abilities, especially for processes not started by the one I'm currently in.

This is a rather POSIX specific expectation. perl5 puts effort into emulating it on Windows; it's not necessarily a sensible expectation or a sensible interface.

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/3bb170f8de89e5d33c4affdb9262d3b64df48b8d
