### ISSUE TITLE
\qq[] escape sequence not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1280]
... or at least, I was unable to find it.

There might be more similar escape sequences in existence. For example `\q[]` seems to be interpreted as well.

My knowledge of it is summed up with this:

```perl6
my $foo = 42;

# Single quotes still interpolate some stuff, like the \qq[] escape:
say  '$foo is \qq[$foo]'; # OUTPUT: $foo is 42

# To avoid it, use Q// quoter, which can be written with U+FF62 + U+FF63 chars
say Q'$foo is \qq[$foo]'; # OUTPUT: $foo is \qq[$foo]
say  ｢$foo is \qq[$foo]｣; # OUTPUT: $foo is \qq[$foo]

# The \qq[] escape can be handy when interpolating into HTML with CSS, where
# with liberal quoting you run the risk of the tags being interpreted as
# hash key lookup, and CSS/JS curlies as interpolated blocks.
#
# Don't shove backslashes all over the place! Just use the q// quoter with
# and use \qq[] escape sequence to insert your variables.
say '<foo><bar>$foo<ber>\qq[$foo]<ber> { stick \qq[$foo] CSS up in here }';
say q:to/♥/
  <foo><bar>$foo<ber>\qq[$foo]<ber> { stick \qq[$foo] CSS up in here }
  ♥
# OUTPUT:
# <foo><bar>$foo<ber>42<ber> { stick 42 CSS up in here }
# <foo><bar>$foo<ber>42<ber> { stick 42 CSS up in here }
```

**Comment by coke** [comment]
In the commit, you use the word "literallization" - what do you mean by this?

**Comment by JJ** [comment]
Made up word meaning "made literal". De-literallization would unmake that literallization. Maybe with single `l`, come to think of it...

**Comment by cfa** [comment]
I find this explanation confusing. (Note also that `\qq` is documented in the [Escaping: q](https://docs.perl6.org/language/quoting#Escaping:_q) section.)

How about simplifying

> Literal strings allow _unquoting_ by escaping the quoting construct, to indicate it _escapes_ literallization:

to something like:

> Literal strings permit interpolation of embedded quoting constructs using the following escape sequences: […]. Other escapes are ignored.

followed by the example?

I'm also having a hard time understanding:

> Using \ on any other quoting construct, and it within literal quotes will effectively allow de-literallization or the use of dynamic content within literal strings.

This is just saying that quoting constructs will be interpolated, right? I think this can be stated more simply at the outset.

Thoughts?

**Comment by coke** [comment]
I don't understand what you mean by "made literal".

Literal has a well defined meaning regarding a value in the code. like

```
my $a = "this is a literal string";
```

Can you clarify your intent here?
