### ISSUE TITLE
Searching or linking to .. operator doesn't work

### ISSUE THREAD

**Issue by bduggan** [perl6/doc#1283]
Typing `..` into the search bar and then clicking on `..` on docs.perl.org isn't working.

Also, these URLs are returning 404s:
   https://docs.perl6.org/routine/..
  https://docs.perl6.org/routine/$FULL_STOP$FULL_STOP

**Comment by samcv** [comment]
@bduggan This commit should hopefully have fixed this particular issue:
https://github.com/perl6/doc/commit/3ba0c0239029ede7303efd06520fa6ffc3e198af

Will close this one if ones ending in just periods get fixed, and leave the other one to track other nonworking URL's as well.

**Comment by samcv** [comment]
That page is accessible now. Closing! https://docs.perl6.org/routine/..html

**Comment by bduggan** [comment]
Thanks!
