### ISSUE TITLE
The Index of Syntax % is broken

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1286]
The target page of the index of Syntax `%` is: `https://docs.perl6.org/%`

As far as i know:
Opera: returns 400.
Edge: returns nothing. stays in the same page.

**Comment by samcv** [comment]
Fixed as of https://github.com/perl6/doc/commit/5c7901084e283c4408b065341c391558a009a258

Closing. (page is accessible as https://docs.perl6.org/routine/$PERCENT_SIGN now)
