### ISSUE TITLE
doc accessing symbols not imported by require by FQN

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1287]
```
require ::("Test"); my &mmk = ::("Test::EXPORT::DEFAULT::&ok"); mmk('oi‽');
```

**Comment by JJ** [comment]
I'm trying to figure out what this is about. That code returns `OUTPUT: «ok 1 - ␤»`. It's importing using the fully qualified name "Test", and what I understand is that a doc on how to access symbols from modules imported that way should be done, is that right?
