### ISSUE TITLE
404

### ISSUE THREAD

**Issue by coke** [perl6/doc#129]
Need a 404 page that still has the menu on it.

As terms come and go, we will have links go stale, it's already happening:

```
07:48 < ilmari> huh, the first hit on https://duckduckgo.com/?q=perl6+eqv is
                http://doc.perl6.org/routine/eqv, but that 404s
```

Need to make sure these have a landing page that lets users search

**Comment by jonathanstowe** [comment]
Is the setup of the server such that a 404 document can be defined?
