### ISSUE TITLE
Searching %% results in links that BAD REQUEST

### ISSUE THREAD

**Issue by con-mo8** [perl6/doc#1295]
If you search for '%%' you end up with links like /routine/%% that result in a bad request. When you take a look at the generated static search.js there are also references to %2525 for these links. I believe all of this stems around unescape-percent in [lib/Pod/Htmlify.pm6#L33](https://github.com/perl6/doc/blob/master/lib/Pod/Htmlify.pm6#L33) It's all a bit convoluted and terse for me to really see where the problem lies. It's not URI::Escape though, as that treats %% as %25%25 correctly. Im not sure if this is a different problem to the link created by the javascript client side.

**Comment by MattOates** [comment]
#1286 is the same issue

**Comment by samcv** [comment]
Fixed as of https://github.com/perl6/doc/commit/5c7901084e283c4408b065341c391558a009a258

Closing
