### ISSUE TITLE
provide example for list return value in sort callable

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1297]
```
my %h = :one(1), :two(2), :three(3); say %h.keys.sort({$^a.chars, $^a.Str})
# OUTPUT: «(one two three)␤»
```
It's not really a special case in `sort` but still not obvious (and darn usefull) so a nice example and maybe an explaination would be nice.

**Comment by JJ** [comment]
So you can use the comma for separating sorting criterium and return value?
