### ISSUE TITLE
Pages that end in periods or non-allowable characters are inaccessible

### ISSUE THREAD

**Issue by samcv** [perl6/doc#1298]
This page is inaccessible: https://docs.perl6.org/routine/...

*The problem is that URL's can't end with periods or certain other characters.*

**This page can be accessed just fine**:
https://docs.perl6.org/routine/....html

Solution: the links for pages that end in periods need to tack on .html or else it won't load properly, or there may be some rewriting we can do on the server (not sure, maybe somebody else can chime in).x

**Comment by bduggan** [comment]
another example: #1283

**Comment by JJ** [comment]
So would you consider this is fixed? Or would it better to have the two ways of accessing it?

**Comment by JJ** [comment]
These pages appear with `.html` now in the search file. Not too clear where or when it's been done, but it works. I'm closing it.
