### ISSUE TITLE
Doc bug in rb-nutshell

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1299]
From [RT #131269](https://rt.perl.org/Ticket/Display.html?id=131269):

> On https://docs.perl6.org/language/rb-nutshell, it says:
> 
> >   No space allowed before the opening parenthesis of an argument list.
> > ```
> > foo (3, 4, 1); # Not right in Ruby or Perl 6 (in Perl 6 this would
> >                # try to pass a single argument of type List to foo) 
> > foo(3, 4, 1);  # Ruby and Perl 6 
> > foo 3, 4, 1;   # Ruby and Perl 6 - alternative parentheses-less style 
> > ```
> This doc was probably written before the GLR, because even if the ‘foo (’ version does produce a
> single argument of type List, then the “Single argument rule” makes it behave the same as the others.
>
> Another bug, further down the the file is:
> > ```
> > perl6 example.p6 --length=abc
> >    Usage:
> >      c.p6 [--length=<Int>] [--file=<Any>] [--verbose]
> > ```
> Clearly that’s a copy-pasto, since the file can’t be named c.p6 and example.p6 both at the same time.

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/f897a9c7ab0dc732ddf2a826b505f8949d1c75dc

> then the “Single argument rule” makes

The OP is confused about the rule. The example is right.
