### ISSUE TITLE
How to access individual characters of a string? (FAQ)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1300]
See [RT #129843](https://rt.perl.org//Public/Bug/Display.html?id=129843).

Basically show that ``‘something’[2]`` is wrong and that one should use ``.comb``.

**Comment by zoffixznet** [comment]
> that one should use .comb.

Surely `.substr`

**Comment by AlexDaniel** [comment]
Absolutely right. Sorry for this brainfart.

**Comment by zoffixznet** [comment]
or [use a module](https://github.com/zoffixznet/perl6-Pythonic-Str/) 😛 

```perl6
    use Pythonic::Str;
    say 'foobar'[3];            # b
    say 'foobar'[3..*];         # bar
```
😹 😹 😹

**Comment by AlexDaniel** [comment]
By the way, there is a mention of this in [traps](https://docs.perl6.org/language/traps#Strings_are_not_iterable).

**Comment by coke** [comment]
From traps:

```
There are methods that Str inherits from Any that work on iterables like lists. Iterators on Strings contain one element that is the whole string. To use sort, reverse and friends, you need to split the string into a list first.
```
 
```Strings``` shouldn't be capitalized, and the types should probably be linked.
