### ISSUE TITLE
Is Inline::Python still needed?

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1301]
The [CONTRIBUTING docs mentions Inline::Python](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#inlinepython) as a prereq.

Is that still accurate? IIRC we swapped to a new highlighter that doesn't need that module/python anymore.

**Comment by samcv** [comment]
Nope not accurate anymore. Inline::Python has been totally removed.
