### ISSUE TITLE
Move documents spun off CONTRIBUTING.md to a new location.

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1302]
The [CONTRIBUTING.md](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md) doc is way too big (and [I'm not the only one who thinks so](https://irclog.perlgeek.de/perl6/2017-05-11#i_14567654)).

It covers everything under the moon, including website debug mode.

Most contributors don't need to be put through the pain of installing all the prereqs and building the local copy of the site. And IMO the CONTRIBUTING doc should just answer the questions:

- How to find what to edit to change a thing I see on the site?
- What writing style should I use?
- What the hell is POD6 and how do I write it?

To test the change doesn't break too much, users can just run the pod file they edited through Pod::To::Text (add `make render` target or something) instead of building anything and IMO the option of just editing stuff right on GitHub should be suggested as a possibility.

Everything else should be put into another document.

**Comment by coke** [comment]
I ripped out the part about writing/testing/skipping examples into EXAMPLES.md - probably want to have a new folder to put these in (which wants to be called docs/, except for how confusing that is with doc/)

**Comment by toolforger** [comment]
> (which 
> wants to be called docs/, except for how confusing that is with doc/)

Maybe writing-docs/ ?

**Comment by JJ** [comment]
`writing-docs/`is OK for me.

**Comment by JJ** [comment]
This document is now divided in several ones, and it seems to have eventually drifted to where to place the different documents. If everyone's OK with it, I'll change the issue title to reflect this fact if the initial concern has been addressed.
