### ISSUE TITLE
Missing web documentation for some Role (and other) related Metamodel classes/roles

### ISSUE THREAD

**Issue by BenGoldberg1** [perl6/doc#1306]
If I run `role R { }; R.HOW.say` the output is `Perl6::Metamodel::ParametricRoleGroupHOW.new␤` ... this does not seem to be documented...

On the same note, the type graph for Any on [https://docs.perl6.org/type/Any.html](url) has some links to Role related things which are 404 Page Not Found:

* [x] https://docs.perl6.org/type/Metamodel::RolePunning
* [x] https://docs.perl6.org/type/Metamodel::ConcreteRoleHOW
* [x] https://docs.perl6.org/type/Metamodel::CurriedRoleHOW
* [x] https://docs.perl6.org/type/Metamodel::ParametricRoleGroupHOW
* [x] https://docs.perl6.org/type/Metamodel::ParametricRoleHOW
* [ ] https://docs.perl6.org/type/Metamodel::PackageHOW

After figuring out why these pages weren't generated, please add automatic test so that, after all the web pages are generated, there are no links to 404 pages.

Thanks!

**Comment by coke** [comment]
(this ticket can be for docs, we can open a separate ticket for automatic testing)

**Comment by JJ** [comment]
Ref #1846

**Comment by JJ** [comment]
There are several problems with this issue:
* Those classes are now in the Perl6 namespace, thus not really there. For instance, [`Perl6::Metamodel::RolePunning](https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/RolePunning.nqp).  Actually, the ones that were inserted in #1846 are also wrong.
* There are many other classes that are not listed in type-graph.txt (or already in the documentation)
* They are implementation dependent, as @zoffixznet said. 

So I don't really know what to do with them. It does not make a lot of sense to hide them, not a lot of sense to list them exhaustively. Anyway, errors must be fixed...

**Comment by JJ** [comment]
Reopening and adding more classes that are not documented, like the one above. It should be included if only for completeness (enumHOW and other similar ones are ther) and it's also mentioned in several places.
