### ISSUE TITLE
Search doesn't link to &?ROUTINE, doesn't escape ?

### ISSUE THREAD

**Issue by labster** [perl6/doc#1308]
Typed `&?ROUTINE` into the search box (on Firefox, if that's relevant), and got a link to:
https://docs.perl6.org/syntax/&?ROUTINE

Unfortunately, the actual page is available at https://docs.perl6.org/syntax/&%3FROUTINE  Though we might consider escaping the `&` too.

**Comment by JJ** [comment]
Somehow, this has been fixed. I'm closing this, feel free to re-open if it's not been done to your satisfaction.
