### ISSUE TITLE
non-non breaking space used

### ISSUE THREAD

**Issue by coke** [perl6/doc#1312]
```
$ perl6 xt/perl-nbsp.t 2>/dev/null | grep "not ok"
not ok 23 - doc/Language/io-guide.pod6 (line 232): Perl followed by a version should have a single non-breaking space.
```

It's from a code snippet that could be using a nbsp (or not using the literal "Perl 6")

**Comment by coke** [comment]
Another lack of nbsp added in 6cdbe86624c4f5f974aa9b798b69a86612a080a1

**Comment by zoffixznet** [comment]
IMO code snippets should be exempt from this rule. Just too much potential for users copying the examples, modifying the code, and getting surprising results due to the hidden nbsp.

**Comment by coke** [comment]
Or the example could be rewritten to avoid the use of "Perl 6", which is much easier, although I agree, not ideal.

**Comment by AlexDaniel** [comment]
Code example or not, Perl 6 is Perl 6.

**Comment by zoffixznet** [comment]
> Edit: fucking github does not agree

![](http://i4.ytimg.com/vi/kdOPBP9vuZA/mqdefault.jpg)
