### ISSUE TITLE
.keys and .values returns Seq

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1323]
The documentation for [Map](https://docs.perl6.org/type/Map) says that `.keys`,  `.values`, `.kv`, `pairs` return lists. They actually return [Seq](https://docs.perl6.org/type/Seq). Other methods, such as `.antipairs`, correctly notes that it returns a sequence. This extends into docs that rely on [Map](https://docs.perl6.org/type/Map).

**Comment by AlexDaniel** [comment]
@lizmat maybe if you scroll through the thing you can notice other errors like this?
