### ISSUE TITLE
react and whenever missing

### ISSUE THREAD

**Issue by jdv** [perl6/doc#134]

**Comment by jonathanstowe** [comment]
I was planning on adding these to the lib/Language/concurrency at some point, trouble is (for me at least) is that they're syntax features rather than subs that could be documented in the Supply documentation.

**Comment by moritz** [comment]
I still think it makes sense to document them in Supply docs, since they are so closely coupled to the type.

**Comment by moritz** [comment]
http://doc.perl6.org/language/concurrency now mentions `react` and `whenever`.

**Comment by AlexDaniel** [comment]
But it is not searchable. Reopening.
