### ISSUE TITLE
Don't use a non-twigil ^ to explain the twigil ^

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1340]
in [Variables](https://docs.perl6.org/language/variables)

> The ^ twigil declares a formal positional parameter to blocks or subroutines.

The example includes the use of a different `^`:

	for ^4 {
		say "$^b follows $^a";
	}

I think it would be less confusing to the newbie to see only one type of `^` in that example.

**Comment by coke** [comment]
The merge 4 days ago fixed this.
