### ISSUE TITLE
https://docs.perl6.org/type/PseudoStash is 404

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1341]
The link to [PseudoStash](https://docs.perl6.org/type/PseudoStash) from the type diagram in [Any](https://docs.perl6.org/type/Any) is not found.

**Comment by JJ** [comment]
I have assigned a few who I have seen have worked on the module. The doc is simply not there. And I really have no idea how to start writing about it.

**Comment by jnthn** [comment]
`PseudoStash` is the stash type (hanging off `.WHO`) that backs various pseudo-packages. So, when you do `MY::` or `CALLER::`, that gives back a `PseudoStash`. In most cases, `PackageName::` gives back a `Stash`. Neither of these are objects the user is expected to create by themselves, but of course it's interesting to document what you can do once you have one (which boils down to "use it like a hash").

**Comment by JJ** [comment]
I can just take that and turn it into a page :-)

**Comment by lizmat** [comment]
> On 27 May 2017, at 13:21, Jonathan Worthington <notifications@github.com> wrote:
> 
> PseudoStash is the stash type (hanging off .WHO) that backs various pseudo-packages. So, when you do MY:: or CALLER::, that gives back a PseudoStash. In most cases, PackageName:: gives back a Stash. Neither of these are objects the user is expected to create by themselves, but of course it's interesting to document what you can do once you have one (which boils down to "use it like a hash").

To give you an example:

$ 6 'my $a = 42; my $b = q/$a/; dd MY::{$b}'
Int $a = 42

This shows that you can use a (pseudo-)stash to look up variable by name at runtime.


Does this help?



Liz

**Comment by coke** [comment]
Assigned @JJ based on his comment 16 days ago

**Comment by coke** [comment]
Also touched in 0a0d8463
