### ISSUE TITLE
Document utf8-c8

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1345]
[Buf](https://docs.perl6.org/type/Buf) mentions it and it's in a few tests, but I didn't find a specific description about what it's supposed to do and how it does it.

**Comment by smls** [comment]
I thought there was once a gist or something where jnthn explained it in detail, but now the best description I can find with google is from a more recent [P6Weekly post](https://p6weekly.wordpress.com/2017/01/02/2017-01-glancing-at-a-prime-time/):

> Jonathan Worthington re-implemented the utf8-c8 encoding (the one that tries to interpret the input as UTF-8, but starts creating synthetic codepoints for those byte-sequences that aren’t UTF-8), making sure it will never segfault anymore and will always roundtrip regardless of which garbage is thrown at it.

PS: The docs should also mention that this is the default encoding used for things like filenames.

**Comment by jnthn** [comment]
Maybe the [explanation from its implementation](https://github.com/MoarVM/MoarVM/blob/master/src/strings/utf8_c8.c#L3) could be nabbed for the docs.

**Comment by samcv** [comment]
I added documentation in this commit https://github.com/perl6/doc/commit/e556ea37438dd3394b1c60db43bf416554a5f140

It could use a bit more practical examples though. What do people think?

**Comment by AlexDaniel** [comment]
I like it. Can we also make it searchable and link all existing mentions to this? I think that would resolve the issue.

**Comment by dogbert17** [comment]
It's searchable and both mentions of UTF8-c8 in the text have had links added to them.

**Comment by dogbert17** [comment]
Closing, plz reopen if something has been overlooked
