### ISSUE TITLE
Searching for `.:` has two 404 pages

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1346]
Searching for `.:` on the docs gives two results that end up on 404 pages https://docs.perl6.org/routine/.:: and https://docs.perl6.org/routine/.:%3Cprefix%3E

**Comment by AlexDaniel** [comment]
These are now not indexed, but they are listed on https://docs.perl6.org/routine-operator.html

**Comment by W4anD0eR96** [comment]
This is because when link to `/routine/sub` is redirected to `/routine/sub.html`.
However, it's broken if the sub is itself starting with `.`.

**Comment by JJ** [comment]
They are indexed under different names, for instance, [prefix call](https://docs.perl6.org/language/operators#index-entry-prefix_call). But those 404 pages are not nice. Maybe they are related to #1971, since the file name they are generating is not correct.

**Comment by JJ** [comment]
The first one works now, the second one does not.
