### ISSUE TITLE
Short search strings don't find exact matches

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#1356]
Expected but doesn't happen: "try" finds "try".

Unexpected but happens: "try" finds things shorter than 3 characters
Unexpected but happens: "try" finds things like "utc", "rwx", "ord"

The fuzzy search appears to be too fuzzy.

Might be related to #247

**Comment by coke** [comment]
Fixed as part of #1404 

I can now find 'try' locally, will hit the site soon.

**Comment by coke** [comment]
(and also, NOT find most of the other stuff.)
