### ISSUE TITLE
nativecall.pod6 misses nativeconv

### ISSUE THREAD

**Issue by rurban** [perl6/doc#1357]
Hi, I'm just implementing the cperl ffi.

The perl6 design doc properly lists all 4 relevant nativecall traits:
* native(STRING), native
* symbol(STRING)
* encoded(STRING)
* nativeconv(STRING)

Here in `nativecall.pod6` nativeconv is missing, and esp. the relevant values. 
In the testsuite there's only lowercase "thisgnu", which sounds suspicious.

libffi supports mostly only one ABI. only on these platforms the following variants:

    arm (not aarch64): VFP, SYSV
    mips: O32, N32, N64, O32_SOFT_FLOAT, N32_SOFT_FLOAT, N64_SOFT_FLOAT
    powerpc: AIX, DARWIN
    powerpc (not aix, not darwin): SYSV, COMPAT_SYSV, COMPAT_GCC_SYSV,
             COMPAT_LINUX64, COMPAT_LINUX, COMPAT_LINUX_SOFT_FLOAT
      or powerpc64: LINUX
    x86_64: UNIX64, WIN64
    x86: SYSV, STDCALL, THISCALL, FASTCALL, MS_CDECL, PASCAL, REGISTER

It would be nice to know what nativeconv or dyncall does. I unsuccessfully grep'ed for `abi` or `thisgnu` or `native_call_convention` in rakudo, nqp, MoarVM and dyncall. Looks like it is ignored and not implemented yet.

dyncall itself has similar support as libffi, just different names:
e.g. for x86:
* DC_CALL_C_X86_CDECL
* DC_CALL_C_X86_WIN32_STD
* DC_CALL_C_X86_WIN32_FAST_MS
* DC_CALL_C_X86_WIN32_THIS_MS
* DC_CALL_C_X86_WIN32_FAST_GNU 
* DC_CALL_C_X86_WIN32_THIS_GNU (= cdecl)
* DC_CALL_SYS_DEFAULT
* DC_CALL_C_X86_PLAN9
* DC_CALL_SYS_X86_INT80H_LINUX
* DC_CALL_SYS_X86_INT80H_BSD

**Comment by Skarsnik** [comment]
hm, it's probably some internal stuff that does not really need documentation for the users of nativecall.

**Comment by rurban** [comment]
No it's not. In which ABI the shared lib is compiled is important on special platforms, and there's no ABI detection built in.

**Comment by JJ** [comment]
Greppable finds nothing, so I would say it's not specced

**Comment by JJ** [comment]
[These are the calling conventions available](https://github.com/MoarVM/MoarVM/blob/master/src/core/nativecall_dyncall.c). They don't seem to be tested.

**Comment by JJ** [comment]
@rurban that's the rakudo test suite, BTW. It's not in roast.

**Comment by rurban** [comment]
I see, it's collapsed to the one and only most probable one. Well, that helps, thanks.
