### ISSUE TITLE
Error in "Appending content' section of  https://docs.perl6.org/language/io-guide

### ISSUE THREAD

**Issue by legrady** [perl6/doc#1362]
The "Appending content" section has a short 4 line example, and then two paragraphs down, describes it as:

    "On the next couple of lines, we use the usual .print 
     method on that IO::Handle to print ten lines of text."

But this is $fh.print, without any explicit newlines. It winds up all on one line, certainly with my 2017.01 version of Rakudo, and same with 2017.04.3 / MoarVM version 2017.04-53-g66c6dda.

**Comment by zoffixznet** [comment]
Thank you for the report. This is now fixed in https://github.com/perl6/doc/commit/1a5ee4fd396b86d6de0b4bb7f744fef38cf0e13f
