### ISSUE TITLE
REPL link goes to page where it isn't on the page

### ISSUE THREAD

**Issue by samcv** [perl6/doc#1363]
1. Type REPL in the Search bar
2. Click on link. Link goes [here](https://docs.perl6.org/language/glossary#index-entry-REPL)
3. Ctrl+F and REPL or read eval print loop are not on the page anywhere

**Comment by coke** [comment]
```
=head1 Perl
X<|Perl>

The Perl programming language in its many forms.

=head1 PERL
X<|REPL>
```

Looks like a typo in the glossary
