### ISSUE TITLE
Should be able to search for ¹ et al.

### ISSUE THREAD

**Issue by coke** [perl6/doc#1373]
While this is part of the grammar, it would be nice to have a concise explanation of both:

* How to use superscripts to indicate power
* How p6 supports unicode numeric literals

And have there be a link between these two sections.

```
⁰¹²³⁴⁵⁶⁷⁸⁹
```
In case someone needs the literals to add as X<> markers.

**Comment by AlexDaniel** [comment]
FWIW, a little bit of that exists on [unicode_texas](https://docs.perl6.org/language/unicode_texas) page.

**Comment by coke** [comment]
Will hopefully address part of https://github.com/rakudo/rakudo/pull/1095

**Comment by ronaldxs** [comment]
See also issue #1098

Also:
> * How to use superscripts to indicate power

Receives somewhat relevant mention with last paragraph of https://docs.perl6.org/language/syntax#Identifiers

**Comment by AlexDaniel** [comment]
For proper documentation on ¹⁻⁹ see #1098. This ticket should be resolved after da26660ff53ab73bed7c60446e2eaad817b41a27.

**Comment by AlexDaniel** [comment]
Also, “How p6 supports unicode numeric literals” is already explained in https://docs.perl6.org/language/unicode_texas#Numeric_characters and https://docs.perl6.org/language/unicode_texas#Numeric_values
