### ISSUE TITLE
Binding does not "put into"

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#1378]
In https://docs.perl6.org/language/list, binding to an @-sigiled variable is described as "putting an actual List into an @-sigiled variable". It's descriptive, but seems semantically inaccurate. This could lead to a wrong understanding of any(lists, @-sigiled variables, binding).

On IRC, skids added: "Yeah, keeping the difference between containers and variables straight in the text is important.  Maybe we should figure out which verbs to use consistently for which operation."

**Comment by JJ** [comment]
Do we have that figured out or should I make my best guess?

**Comment by smls** [comment]
Here is what I'd use.  
(In the case of assignment, I'd differentiate between item assignment and list assignment.)

<hr>

``` perl6
my $a = (1, 2, 3);
````
&mdash; It **assigns** the List object to the item variable `$a`.
&mdash; It **places** the List object  **into** the item variable `$a`.

<hr>

``` perl6
my @a = (1, 2, 3);
````
&mdash; It **assigns** the List object to the array variable `@a`.
&mdash; It **fills** the existing Array object with the values from the given List object .


<hr>

``` perl6
my $a := (1, 2, 3);
my @a := (1, 2, 3);
````

&mdash; It **binds** the List object to the variable name `$a` (or `@a`).
&mdash; It makes the name `$a` (or `@a`) **refer directly to** the given List object.
&mdash; It makes the name `$a` (or `@a`) a **lexical alias** for the given List object.
