### ISSUE TITLE
Fix travis timeout

### ISSUE THREAD

**Issue by LLFourn** [perl6/doc#1384]
docs build sometimes takes so long travis times out. IMO: The solution that involves the least work is to use rakudo binaries rather than building rakudo before building to docs.

**Comment by rafaelschipiura** [comment]
Can you confirm the distro Travis runs on?

Depending on the distro, different options are available to give rakudos to Travis to eat.

**Comment by LLFourn** [comment]
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```
It looks like we've specified it be 12.04. We can probably change it. It's specified here:
```
https://travis-ci.org/perl6/doc/jobs/244777120/config
```

**Comment by rafaelschipiura** [comment]
Ubuntu 12.04 reached end-of-life in April 28. 

It's a very good idea to choose a more recent version.

**Comment by LLFourn** [comment]
It looks like it's some kind of limitation of travis itself 😞

You can use trusty but it's still in beta: https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by AlexDaniel** [comment]
Note that if you want the most recent rakudo, then I can expose [whateverable](https://github.com/perl6/whateverable) builds in some way so that it will be possible to just pull any version you want at any time. Just ping me if this is needed.

**Comment by LLFourn** [comment]
@AlexDaniel sounds good to me. I guess the process would be:
1. download/extract latest whateverable build
2. install zef and depends
3. run docs build

+ recent binaries are a useful thing to have generally.

**Comment by JJ** [comment]
There's also this rakudo docker container that is only 500megs and takes
very little to run (compared to compiling) :-)

**Comment by LLFourn** [comment]
@JJ that might be the way to go because then we can have zef in the docker image too. FYI you can reduce the size by rm -r the rakudo src directory. I have been doing some work in the same direction as you recently and managed to get a 33mb alpine-based rakudo docker image.

**Comment by JJ** [comment]
I'll do that in the next release, with the updated rakudo. I was actually wondering what I could safely remove to reduce size. Thanks!

**Comment by samcv** [comment]
Guys I have already setup travis to archive rakudo, so just get it to build the latest release instead of building a nightly maybe. It backs up many of the build files, though it likely could be optimized. Also I have nightly appimages that build as well if anybody wants to try with that:

https://github.com/samcv/rakudo-appimage-module-test-automation/tree/gh-pages

The appimages are only 7 MB

**Comment by probonopd** [comment]
@samcv great work. Minor nitpick: It's not good practice to store AppImages (or any other binaries) in git repositories. There's __GitHub Releases__ for that, check it out.

**Comment by AlexDaniel** [comment]
Given that nobody is complaining, I'll close this. If there's still an issue, let's open a new ticket and link this one.
