### ISSUE TITLE
p5 nutshell: Suggest .nextsame and .nextwith once they've been implemented in Rakudo.

### ISSUE THREAD

**Issue by coke** [perl6/doc#1389]
Original context:

https://github.com/perl6/doc/commit/97c24a51878b27797dcd9f06645438adaaa68def#diff-41d8ba5d58c8de99795c9c3779f777f6R233

**Comment by JJ** [comment]
They are already there, and [here are a few examples](https://rakudo.party/post/Perl6-But-Heres-My-Dispatch-So-Callwith-Maybe) to tap from.
