### ISSUE TITLE
Wrong page links to `Z`

### ISSUE THREAD

**Issue by samcv** [perl6/doc#1394]
There is a link here so if you search for Z you may end up at https://docs.perl6.org/language/about#index-entry-infix_Z-How_to_use_the_Z_infix

Which is a page about the docs not actually a documentation page about the zip operator.

**Comment by JJ** [comment]
The problems is that the doc is demonstrating that precise feature. I will try and figure out if this is really needed, and erase if not.

**Comment by AlexDaniel** [comment]
Sorry, I don't understand that last commit. `þ Infix`?? What's þ?

**Comment by AlexDaniel** [comment]
Ah. Ha-ha! I get it now :D
