### ISSUE TITLE
Verify format of pod files

### ISSUE THREAD

**Issue by szabgab** [perl6/doc#1398]
I think I've just noticed a case when there were multiple opening « without closing » in doc/Language/testing.pod6 which caused a large chunk of the documentation to be part of a link, effectively invisible to the reader. In this 4a2d0f21d387afa56235dff79520acd71f53f141 I think I fixed two of these, but there can be many others.
It would be nice if there was some sanity checking for the pod files.

**Comment by coke** [comment]
Unfortunately

perl6 --doc old/version/of/file.pod6

does not notice any issues in the version of the file from before your fix.

This might need to have a companion ticket on rakudo itself for --doc strictness

**Comment by coke** [comment]
We now do a basic sanity check.

Any further pod validation checks should be made part of the --doc processing in rakudo itself.
