### ISSUE TITLE
`reduce` doc mistakenly claims that a single element is returned immediately

### ISSUE THREAD

**Issue by smls** [perl6/doc#1399]
https://docs.perl6.org/routine/reduce.html#(List)_routine_reduce says:

> If @values contains just a single element, that element is returned immediately.

This is not the case: Rather, it calls the operator with one argument if the operator's signature allows it, and only failing that falls back to returning the element itself.

See [RT 128758](https://rt.perl.org/Ticket/Display.html?id=128758) and the commit message of [Rakudo commit b1c444f](https://github.com/rakudo/rakudo/commit/b1c444f0622bc348a2e860a43faa6d72e9a11558).

**Comment by zoffixznet** [comment]
The `[-]` used in the example was actually a [now-fixed bug](https://irclog.perlgeek.de/perl6/2018-04-07#i_16017540).

But even if that's fixed, the description seems wrong. There's no single-arg candidate for `&infix:<(elem)>`, yet in reduce it returns `True` instead of the original value:

```
<Zoffix__> m: say &infix:<(elem)>.candidates».signature
<camelia> rakudo-moar edbbc4426: OUTPUT: «((Str:D $a, Map:D $b --> Bool) ($a, Map:D $b --> Bool) (Int:D $a, Range:D $b --> Bool) ($a, Iterable:D $b --> Bool) ($a, Iterator:D $b --> Bool) ($a, QuantHash:D $b --> Bool) ($, Failure:D $b) (Failure:D $a, $) ($a, $b))␤»
<Zoffix__> m: say [(elem)] 2334
<camelia> rakudo-moar edbbc4426: OUTPUT: «True␤»
```

Is that a bug in rakudo? It uses `METAOP_REDUCE_CHAIN` instead of `METAOP_REDUCE_LEFT` the commit mentioned in the OP modifies.

**Comment by JJ** [comment]
What should actually happen if you call reduce with a single candidate? Is the example what's wrong or the behavior described above?

**Comment by zoffixznet** [comment]
I've no idea. @TimToady would probably know a lot about how all these meta ops are meant to behave.

**Comment by JJ** [comment]
The example is a bug (because the behavior in that case should have been
10-nil) but applying the operator in an unary fashion seems a sensible
enough default... Maybe less sensible that applying it in a binary way
using "none" as second operator.

**Comment by smls** [comment]
Here's what I think is going on:

1. Operator `(elem)` is marked as having `chain` associativity:   
   ``` perl6
   .say for &[(elem)].prec;
   ```   
   ```
   {assoc => chain, iffy => 1, pasttype => chain, prec => m=}
   ```
2. As a result of being chain-associative, it has a default identity value of `True`, even if it doesn't explicitly define a candidate for that.

(1) seems wrong &ndash; Unless I'm missing something, `(elem)` should be non-associative (`is assoc<non>`). Its [documentation](https://docs.perl6.org/language/setbagmix#infix_(elem)) currently doesn't state an associativity, either way.

(2) does makes sense, but TimToady & co. need to decide if it should be made official. If so, the rule I vstated in the top post needs to be complemented with this one.

**Comment by JJ** [comment]
Related to #2129
