### ISSUE TITLE
/language/traps should warn against using `[Z]` to get the transpose of a list-of-lists

### ISSUE THREAD

**Issue by smls** [perl6/doc#1400]
Every now and then, someone gets they idea that they can use `[Z]` to create the transpose of a list-of-lists:

``` perl6
my @matrix = <X Y>, <a b>, <1 2>;
my @transpose = [Z] @matrix;

say @transpose;  # [(X a 1) (Y b 2)] -- so far so good
```

And everything works fine... until you get an input `@matrix` with **exactly one** row (child list):

``` perl6
my @matrix = <X Y>,;
my @transpose = [Z] @matrix;

say @transpose;  # [(X Y)] -- not the expected transpose [(X) (Y)]
```

I've explained the cause of this surprising edge-case behavior, which basically ruins `[Z]` for variable-size inputs, in [this SO answer](https://stackoverflow.com/a/44831926/1160124) (which should be easy to understand without also having to read the associated SO question).

I think this has all the markings of a trap:

* The syntax is simple (so people will continue to "discover" it), and elegant (so they'll be happy to use it).
* It's quite sensible to expect, on first sight, that it will do the right thing.
* It does in fact do the right thing for *most* inputs, meaning that it might slip through unit tests etc.

Thus, I think the Perl 6 documentation should mention it in its "[Traps to avoid](https://docs.perl6.org/language/traps)" document.

**Comment by AlexDaniel** [comment]
FWIW, we now have this ticket: https://rt.perl.org/Ticket/Display.html?id=131686

**Comment by AlexDaniel** [comment]
Another interesting ticket (although maybe unrelated): https://github.com/rakudo/rakudo/issues/1210

**Comment by AlexDaniel** [comment]
I think this is now resolved in https://github.com/perl6/doc/commit/6519ef5399c36650c07c2aced90265aeab780922. I copied some parts of your OP here, let me know if that's a problem.
