### ISSUE TITLE
Method raw doesn't demonstrate method raw

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1401]
In [method raw](https://docs.perl6.org/type/Parameter#method_raw), it looks like the examples don't use the `raw` method but do use variables (sigiled and sigilless) named `raw`. That's pretty confusing.

The docs could use an example of the method's intent and use, or show how it is being used implicitly.

**Comment by dogbert17** [comment]
Have added an example which demonstrates the method itself. Retained the original text as it gives additional information about 'raw' parameters.

**Comment by briandfoy** [comment]
The issue of using the "raw" as an identifier is still there, and that's and important part of the issue.

**Comment by dogbert17** [comment]
Changed the variable names to something which is hopefully less confusing.

**Comment by dogbert17** [comment]
Atttempt 2 :)
