### ISSUE TITLE
unicode.pod6 needs hex codepoint example

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#1402]
The current doc/Language/unicode.pod6 doesn't show an example of using hex or decimal codepoint entry in strings.

**Comment by AlexDaniel** [comment]
I guess you are talking about this stuff?
```perl6
say “\c[80] \x[50]”         # OUTPUT: «P P␤»
say “\c[80, 81] \x[50, 51]” # OUTPUT: «PQ PQ␤»
```

**Comment by tbrowder** [comment]
yes, and i'll add an example later unless you beat me to it!
