### ISSUE TITLE
grapheme is not searchable

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#1403]

**Comment by AlexDaniel** [comment]
“NFG” also.

Possibly related: #724

**Comment by coke** [comment]
Adding doc tag, as there doesn't seem to be a specific paragraph/section for this yet. (a few mentions of grapheme scattered through the docs)

**Comment by AlexDaniel** [comment]
i think this would be the right page for it: https://docs.perl6.org/language/unicode

Note that we probably want to link all “grapheme” mentions once there is a proper description.

**Comment by AlexDaniel** [comment]
Not that anyone else couldn't write this, but… @samcv ? :)
