### ISSUE TITLE
Explain that it is possible to list several characters

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1405]
This is a continuation of https://github.com/perl6/doc/issues/1402.

Here is an example:
```perl6
say “\c[80] \x[50]”         # OUTPUT: «P P␤»
say “\c[80, 81] \x[50, 51]” # OUTPUT: «PQ PQ␤»
```
You can also do that with names.

**Comment by coke** [comment]
Closed in 6fd16df0fe68120fb8a108baaafb7c2b7acf0a75
