### ISSUE TITLE
using CSS from another perl6.org site

### ISSUE THREAD

**Issue by coke** [perl6/doc#1407]
This makes it impossible to run the site offline (as is) for development/testing.

If we need those styles specifically, we can pull them in via git so we have them available during build time, and don't necessarily need a network connection at run time.

Low priority, might be superseded by an update to the site CSS anyway.

Could also add a build rule to 'make run' that did a one shot curl of the file and used the local copy for make run only.

**Comment by zoffixznet** [comment]
Side note for this issue: it requires latest-and-greatest Pod::To::HTML; so if you're testing out the commited fix locally, be sure to get updated version of that module.
