### ISSUE TITLE
Python nutshell: explain that filter is grep

### ISSUE THREAD

**Issue by labster** [perl6/doc#1420]
This came up on perl6-users, and though I'm not sure, I'm guessing that the user came from pythonland because he was wondering where the missing filter function was.

I don't know Python very well at all, so I'm not going to write the examples, but this should be an easy one.

**Comment by bduggan-picwell** [comment]
I've added a little mention of it in the docs about list comprehensions (next to `map`).

**Comment by bduggan** [comment]
I've added a little mention of it in the docs about list comprehensions (next to `map`).
