### ISSUE TITLE
.+ and .* are inaccurate

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#1421]
"`$invocant.+method` calls all methods called `method`" is inaccurate because it does not call all candidates of a multi method, even though they have the same name.

Also, the term 'called' can be confusing here; my suggestion is to use 'named' instead.

Lastly, in example code naming a method `method` can also be confusing because that's a keyword.

**Comment by MasterDuke17** [comment]
What section of the docs?

**Comment by Juerd** [comment]
https://docs.perl6.org/language/operators#postfix_.+

**Comment by frithnanth** [comment]
Maybe an example might be useful here, to stress that the `.+method` calls all the methods with the same name in the inheritance chain; something along the line of:
`class A {
  method go() { 'A' }
}

class B is A {
  method go() { 'B' }
}

my B $b .= new;
my @res = $b.+go;
say @res;   # [B A]`

**Comment by JJ** [comment]
> "$invocant.+method calls all methods called method" is inaccurate because it does not call all candidates of a multi method, even though they have the same name.

What does it do in that case?
