### ISSUE TITLE
https://docs.perl6.org/syntax/$REVERSE_SOLIDUS is 404

### ISSUE THREAD

**Issue by daxim** [perl6/doc#1426]
https://docs.perl6.org/syntax/$REVERSE_SOLIDUS

![](https://user-images.githubusercontent.com/104814/28669905-93e85916-72d6-11e7-9da9-630427914104.png)

**Comment by coke** [comment]
Used to be valid, it was removed.

To close this ticket, we can either agree that we don't need to support the old URLs, or we can make them redirect to the new URL.

**Comment by toolforger** [comment]
A permanent redirect would be preferrable, for the benefit of webpage links and users' bookmarks.
I have no idea how much work that would be though.

**Comment by JJ** [comment]
Seems to be already redirected: https://github.com/perl6/doc/blob/e8ee9762dde5990e263eafdadefddd3b8d11d8ba/html/.htaccess
However, there seem to be lots of $SOLIDUS sprinkled in (404) links here and there still...

**Comment by JJ** [comment]
Related #561

**Comment by JJ** [comment]
I would say this page is now returning 404 because it does not exist. There are many different pages that include \, but all of them are qualified. So I am for the time being closing this issue.
