### ISSUE TITLE
A more precise definition for concurrency

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1427]
[The concurrency docs](https://docs.perl6.org/language/concurrency) say:

> (allowing more than one thing to happen at the same time)

But that's not concurrency. The wikipedia link immediately before that says:

> Concurrent computing is a form of computing in which several computations are executed during overlapping time periods

It doesn't help that that wikipedia article then goes on the discuss parallel computing even though it noted that it's distinct from concurrency.

Wikipedia then has [another article on concurrency](https://en.wikipedia.org/wiki/Concurrency_(computer_science)) that I think is closer to what the concurrency docs are trying to say about Perl 6:

> concurrency is the decomposability property of a program, algorithm, or problem into order-independent or partially-ordered components or units

Perl 6 can work on multiple tasks before it completes one of them, and that's all it should promise (um, heh).

**Comment by AlexDaniel** [comment]
To be honest, I like the current definition, mostly for how it does not make me feel like I'm reading a book on computer science :) I think this is good for 8-year olds and people whose native language is not English.

But we can probably do better. If somebody can come up with a better Simple English explanation, then sure!

**Comment by MorayJ** [comment]
Just to keep this alive...or give some further inspiration or something to argue against...

"Allowing a program, algorithm, or problem to be broken into parts that can be worked on at the same time as each other"

**Comment by briandfoy** [comment]
"at the same time" is part of the docs that is wrong. Concurrency doesn't deal with the when part of the problem and we shouldn't use temporal words to describe it.

**Comment by toolforger** [comment]
Putting up another Dummy for shoot-it-down practice:
"Concurrency is if you make blocks of code that are fit for execution in parallel. The hope is that the computer can work on unfinished blocks while it has spare CPU cycles to execute, e.g. when there are idle CPU cores, or when they are waiting for the disk, or for the user to type something."
I was aiming for completeness and simplicity, so it's probably too long.

**Comment by ngaywood** [comment]
To go another way and maybe too terse:
Perl 6 is designed to support concurrency (ordering units of code) and ..

**Comment by ngaywood** [comment]
Stealing some words from @jnthn slides, change the sub-heading and first paragraph:

_Parallel and Asynchronous Programming. Concurrency._

Perl 6 is designed to support parallel programming (choosing to do multiple things at once), asynchronous programming (sometimes called event driven or reactive programming - that is an event or change in some part of a program may lead to an event or change in some other part of the program asynchronously to the program flow), and concurrency (coordinating access and modification of some shared resource).

**Comment by JJ** [comment]
Is everyone OK with the latest reformulation by @ngaywood ?

**Comment by nxadm** [comment]
Sentences that are too long are hard to read, specially when dense on information. I would split them up like this:

> Perl 6 is designed to support parallelism, asynchronicity and concurrency. Parallelism is about doing multiple things at once. Asynchronicity, sometimes called event driven or reactive programming, is about supporting changes in the program flow caused by events triggered elsewhere in the program. Concurrency is about coordinating the access and the potential modification of shared resources.
