### ISSUE TITLE
Implicit EVAL in regexes (trap?)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1429]
Let's say you have this code:

```perl6
my $x = ‘hello’;
say ‘hello world’ ~~ /<{$x}>/
```

Result:
```
｢hello｣
```

So far everything looks alright. However, let's change the *input data* ($x) a little bit:
```perl6
my $x = ‘#hello’;
say ‘hello world’ ~~ /<{$x}>/
```

Result:
```
===SORRY!===
Regex not terminated.
at /home/alex/EVAL_0:1
------> anon regex { #hello}⏏<EOL>
Regex not terminated.
at /home/alex/EVAL_0:1
------> anon regex { #hello}⏏<EOL>
Malformed regex
at /home/alex/EVAL_0:1
------> anon regex { #hello}⏏<EOL>
    expecting any of:
        infix stopper
```

So it turns out you cannot use variables with arbitrary data in ``<{ }>``? To be honest, I'm not entirely sure what is happening here and if it should work like this. For example, if we're in EVAL, then why ``MONKEY-SEE-NO-EVAL`` plays no role here? Would be nice to have this explained somewhere.

**Comment by AlexDaniel** [comment]
Oh, actually, ``MONKEY-SEE-NO-EVAL`` does work here, but in a weird way:

Code:
```perl6
my $x = ‘Hello{say ‘boo!’}’;
say ‘#hello world’ ~~ / <{$x}> /
```

Result:
```
===SORRY!=== Error while compiling /home/alex/EVAL_0
Prohibited regex interpolation (use the MONKEY-SEE-NO-EVAL pragma to override this error,
but only if you're VERY sure your data contains no injection attacks)
at /home/alex/EVAL_0:1
------> anon regex { Hello⏏{say ‘boo!’}}
```

**Comment by AlexDaniel** [comment]
And also, let's say I want to generate some string and match against it, is it possible to do it without creating a temp variable? For example, let's say I have ``$x`` but I want to use ``$x.lc`` inside a regex, or ``$x // ‘blah’`` or whatever.

So far I came up with this:
```perl6
my $x = ‘#Hello’;
say ‘#hello world’ ~~ / <{ my $foo = $x.lc; /$foo/ }> /
```
*Maybe* it works, I'm not entirely sure. But that's ridiculous anyway. What's the proper way to do it?

**Comment by jnthn** [comment]
`/$($x.lc)/`

**Comment by AlexDaniel** [comment]
Yup! This is it. Not sure if I've ever seen it, but definitely expected something like this. Cool, thanks.
