### ISSUE TITLE
state the unit of timezone a little closer to home

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1446]
State that a timezone is an offset to GMT in seconds for:

https://docs.perl6.org/language/variables#index-entry-%24%2ATZ
https://docs.perl6.org/type/DateTime#method_now

There may be more spots that refere to timezone but don't explain what it is.

**Comment by AlexDaniel** [comment]
Oh. So the timezone is in seconds and we kinda have to mention that almost everywhere we talk about timezones, I think. I actually did not know this and had to search the docs a little bit to figure it out, in the end I simply dd-ed ``$*TZ`` out of frustration.

👍

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/6843510b5c
