### ISSUE TITLE
class Rat is not searchable

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1447]

**Comment by coke** [comment]
To be clear, the class is documented (and findable off the Types page), but isn't one of the search results. (but fatrat and ratstr both work as searches)

**Comment by coke** [comment]
It's because of all the matches.

There's a splice in place at the moment which limits it to the first 50 responses, and "operator" is drowning out the actual exact match.

I think restricting total number of results is desired, but we have to be smarter about which ones we keep.

**Comment by coke** [comment]
Closed in 71f40b44, which typo'd the ticket id.

**Comment by coke** [comment]
Site was updated... and it doesn't work. (worked fine with a local 'make run'). checking...

**Comment by coke** [comment]
fixed with f1ae818e
