### ISSUE TITLE
'react' isn't findable

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#1449]
https://irclog.perlgeek.de/perl6/2017-08-14#i_15014533

**Comment by coke** [comment]
But it is: Search for 'react' finds it under "Reference" as the first hit in that section.

**Comment by coke** [comment]
Tagging @lizmat

**Comment by AlexDaniel** [comment]
This issue is possibly related: https://github.com/perl6/doc/issues/1108.

The matched part is already highlighted with bold, but when I tried searching for “react” it felt like it is not enough (I couldn't easily see it in the list even though it was bold).
