### ISSUE TITLE
language/regexes - predefined subrule <|wb> should be <wb> or <?wb>

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#1451]
Correction to be made at end of section: https://docs.perl6.org/language/regexes#Backslashed,_predefined_character_classes

There is no implementation of `<|wb>` just `<|w>` and either (preferably) the '|' should be removed or `<|wb>`, `<ww>` are converted, as suggested during the [8/10 IRC](https://irclog.perlgeek.de/perl6/2017-08-10#i_14996100) discussion, to <?wb>, <?ww>.

The nqp implementation of "\<|" seems to be in src/QRegex/P6Regex/Actions.nqp - `method assertion:sym<|>`.  Only `<|w>` appears to be implemented there.  Other identifiers seem to always match.  The '|' assertion is only mentioned in the user facing docs in the context of `<|w>` and is not fully implemented as a generic boundary between a rule and its negation as described in [S05](http://design.perl6.org/S05.html#Extensible_metasyntax_(%3C...%3E)).  The '|' assertion is not simply a zero width assertion as suggested in the IRC discussion. While `<|w>` seems to work, `<|wb>` does not appear to behave differently from `<|nonesuch>`.

```bash
ron@ws-ubuntu:~/perl6/nqp$ perl6 -e 'say so "abc\ndef" ~~ /ab<|w>c/'
False
ron@ws-ubuntu:~/perl6/nqp$ perl6 -e 'say so "abc\ndef" ~~ /ab<|wb>c/'
True
ron@ws-ubuntu:~/perl6/nqp$ perl6 -e 'say so "abc\ndef" ~~ /ab<|nonesuch>c/'
True
ron@ws-ubuntu:~/perl6/nqp$ perl6 -e 'say so "abc\ndef" ~~ /abc<|w>/'
True
```

Just removing the '|' would allow `<wb>` to capture but use of `<?` to suppress capturing is not otherwise covered in the doc and the capture may make debugging easier.  If one wants to suppress
named capture for word break then it should be applied to both rules - perhaps something like:

```
<?wb>               Word Boundary (zero-width assertion, ? suppress capture)
<?ww>               Within Word (zero-width assertion, ? suppress capture)
```

I have prepared a branch with this doc change and will pull and merge on request.
https://github.com/ronaldxs/doc/tree/non-capture-wb

**Comment by moritz** [comment]
:+1: for merging that branch.

**Comment by coke** [comment]
If it's merged, can we close this?

**Comment by ronaldxs** [comment]
I am just waiting for issue #1457 so I can see that it looks right.

Thanks
