### ISSUE TITLE
minmax actually returns a Range

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1455]
The [docs for minmax](https://docs.perl6.org/routine/minmax) say they return Lists. But they actually return Ranges:

	> (1,2,3).minmax.^name
	Range

	> <a b c>.minmax.^name
	Range

I think the documented behavior is the one I'd prefer and expect (a list of two elements), but the tests in [S32-list/minmax.t](https://github.com/perl6/roast/blob/d1baf2e7a3e56cd6619c46040d04ed6daebc1d02/S32-list/minmax.t) show them returning Ranges.

**Comment by b2gills** [comment]
A workaround is to immediately call `.bounds` on the result
