### ISSUE TITLE
https://docs.perl6.org/language returns web server directory listing

### ISSUE THREAD

**Issue by smls** [perl6/doc#1461]
I think this used to redirect to `/language.html`.

---

PS: I actually think that `/language`, not `/language.html`, should be the canonical URL of that page, so that the URLs form a nice "tree":
* `/`
* `/language`
* `/language/grammars` etc.

(Might be good for SEO, as well.)

**Comment by toolforger** [comment]
> PS: I actually think that |/language|, not |/language.html|, should be 
> the canonical URL of that page, so that the URLs form a nice "tree":
> 
>   * |/|
>   * |/language|
>   * |/language/grammars| etc.

I think the extension would be giving useful information to humans.
E.g. what's a file and what's a directory, and that .html means the page 
can be safely cached locally.

> (Might be good for SEO, as well.)

My SEO expertise is pretty limited, but extensions are probably just a 
very low-ranking hint if they factor in at all.

**Comment by moritz** [comment]
Solved through a `RewriteRule` redirect in the `.htaccess` file.
