### ISSUE TITLE
show how to get the exit code out of Proc::Async

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1465]
`say (await Proc::Async.new('ls').start for 1..3)».exitcode;`
`#OUTPUT:  «(0 0 0)␤»`

**Comment by AlexDaniel** [comment]
I think we now have that: https://github.com/perl6/doc/blob/b8723fb8b2bb00ce77b064c28c4d907c982351e3/doc/Type/Proc/Async.pod6#L35

Feel free to reopen if there's something else we can do.
