### ISSUE TITLE
add more examples for destructuring in a Signature

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1466]
`for %h -> (:$key,:$value) { dd $key, $value }` # Destructuring works in pointies too and allows assignment to bare named vars.

**Comment by JJ** [comment]
What do you mean by bare named vars? This is the only reference I have found... https://irclog.perlgeek.de/perl6/2014-10-11

**Comment by AlexDaniel** [comment]
I think it simply talks about hash → named vars feature.
