### ISSUE TITLE
Add examples how to type unicode on Windows

### ISSUE THREAD

**Issue by pwr22** [perl6/doc#1467]
As a newbie who sometimes uses Windows, this would be useful to me

**Comment by JJ** [comment]
But that's kind of not specific for Perl 6, right?
Some editors too will have their own way of doing it. For instance, this
for VSCode https://github.com/freebroccolo/vscode-input-assist

**Comment by pwr22** [comment]
> But that's kind of not specific for Perl 6, right?

Indeed, but given the pervasive unicode support in Perl 6 and that there's already [this](https://docs.perl6.org/language/unicode_entry) page with *NIX info, wouldn't it make sense to not exclude Windows people there?

> Some editors too will have their own way of doing it

I don't see any docs telling me what editor I should use on Windows to get started and use the awesome unicode support of Perl 6. People will not try Perl 6 or features in it that they perceive to be difficult to use - this is a non-negotiable fact of the world - so is there any harm in reducing friction a little?

**Comment by JJ** [comment]
> I don't see any docs telling me what editor I should use on Windows to get
> started and use the awesome unicode support of Perl 6. People will not try
> Perl 6 or features in it that they perceive to be difficult to use - this
> is a non-negotiable fact of the world - so is there any harm in reducing
> friction a little?
>
Emacs, always :-)

No, really. I guess that people document what they actually use and it
might be that there are little to no users of Windows among the current
Perl 6 community. I, for one, don't use it and I would really have to go
out of my way to install a VM and test stuff. For that matter, any one can.
But you do have a point, it would help if we would have that in the
documentation... So if you use Windows and can can work this out, I'd
happily accept a pull request with instructions for that page you have
mentioned, which would probably be the best place to put that kind of
thing, I guess.

**Comment by zoffixznet** [comment]
Whenever we talk about Unicode ops, the number one question is how to type those fancy Unicode characters. It would be really awesome if we had a page that listed all the ways to do so easily on most of the popular OSes. The https://docs.perl6.org/language/unicode_entry page is a good start to that effort.

**Comment by 0racle** [comment]
AutoHotKey (AHK) is a great choice for creating custom keymaps on Windows. You can even configure them to only trigger when certain applications are active.

For example I use `Alt-x` for `×`, and a couple other Alt mappings (AHK uses `!` to denote the `Alt` key in keymap definitions)

```ahk
!/::Send ÷
!x::Send ×
!>::Send »
!<::Send «
```

Then there are also what AHK calls "hotstrings" which is kind of like ligature support in IDE's. You type one thing, and it replaces it with something else. This is great for the set ops because I can type the Texas ops and AHK replaces them with the Unicode versions

```ahk
::(elem)::∈
::(cont)::∋
```

**Comment by AlexDaniel** [comment]
What about https://github.com/samhocevar/wincompose ?

**Comment by AlexDaniel** [comment]
> [\<teatime\> I am an avid user of compose key on linux, have used wincompose on windows and it works great.](https://irclog.perlgeek.de/perl6/2017-09-01#i_15100558)

**Comment by AlexDaniel** [comment]
Split into two tickets:
* https://github.com/perl6/doc/issues/1531
* https://github.com/perl6/doc/issues/1532
