### ISSUE TITLE
Type constraint smileys conflate .defined-ness with .DEFINITE-ness

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1469]
The type smileys constrain based on whether an object is `.DEFINITE` (or "concrete" or a "type object" vs. "an instance"), but [the current description](https://docs.perl6.org/type/Signature#Constraining_Defined_and_Undefined_Values) describes the difference very loosely, and it's easy to misunderstand it to be saying that the smileys check for value of `.defined` instead.

(P.S.:  "type smileys" doesn't find any search results, even though [the docs do seem to use that term in a few places](https://www.google.com/search?q=site%3Adocs.perl6.org+smileys))

**Comment by zakame** [comment]
Wow, I almost fell to that trap while documenting for #1495 💦

**Comment by zakame** [comment]
Checking on https://design.perl6.org/S12.html#Abstract_vs_Concrete_types I can see why the initial description is loose:

```
    Int:_       Allow either defined or undefined Int values
    Int:D       Allow only defined (concrete) Int values
    Int:U       Allow only undefined (abstract) Int values

That is, these mean something like:

    Int:D       Int:_ where DEFINITE($_)
    Int:U       Int:_ where not(DEFINITE($_))
```

Digging deeper into https://design.perl6.org/S12.html#Introspection:

```
There is one more macro:

    DEFINITE    the object has a valid concrete representation

The DEFINITE macro serves as the default for the Mu.defined method.

For now Perl 6 reserves the right to change how all these macros...
```

I guess we could add a note along the lines of "under the hood" for these particular constraints, like below (please check for accuracy:)

>The `:D`, `:U`, and `:_` type constraints check for the I<definiteness> of the object, that is whether the object represents an instance (a I<concrete> object) or a type (an I<abstract> object.)  Under the hood, this calls the object's `.DEFINITE` method, which if not overridden in its class or parents, would default to `Mu.defined` method.

**Comment by zoffixznet** [comment]
> this calls the object's .DEFINITE method, which if not overridden in its class or parents, would default to Mu.defined method.

No, it's `Mu.defined` that defaults to `self.DEFINITE` not the other way around. You can't override .DEFINITE and no method is called under the hood (it's not a real method).

Something along the lines of...

> The `:D` type constraints for instances only, similar to how you could call `.DEFINITE` on an object, `:U` for type objects, and `:_` (the default) type constraints for either.

```perl6
say Int ~~ Any:D; # OUTPUT: «False␤»
say Int ~~ Any:U; # OUTPUT: «True␤»
say Int ~~ Any:_;  # OUTPUT: «True␤»

say 42 ~~ Any:D; # OUTPUT: «True␤»
say 42 ~~ Any:U; # OUTPUT: «False␤»
say 42 ~~ Any:_; # OUTPUT: «True␤» 
```

**Comment by zakame** [comment]
Thanks for clarifying, it seems I certainly fell into that trap from the Synopses. 😹

Furthermore, should we solidify calling these particular constraints as "type smileys"?  They're certainly catchy, FWIW.
