### ISSUE TITLE
Numeric values of signals mean nothing (bug)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1474]
Code:
```perl6
say +SIGUSR1
```
Result:
```
30
```
… and so I just SIGPWR-ed something that meant to receive SIGUSR1.

[“SIGUSR1 can be 30, 10, or 16”](https://stackoverflow.com/a/16667363/2698019). The number you get from Signals enum is not any relevant.

A bit of IRC log: https://irclog.perlgeek.de/perl6/2017-08-28#i_15078223

**Comment by AlexDaniel** [comment]
FWIW It feels like this is a rakudo bug that should be fixed, but I don't have enough tuits to defend this position.

**Comment by smls** [comment]
If the enum values can't be made platform-dependent, another idea might be to change it from an `Int`-based enum to a `Str`-based enum:

``` Perl 6
enum Signal (SIGHUP => "SIGHUP", SIGINT => "SIGINT", ...);
```

Less functionality, but at least no _incorrect_ functionality... :)

**Comment by AlexDaniel** [comment]
I filed it as a rakudobug anyway: [RT #132012](https://rt.perl.org/Ticket/Display.html?id=132012).

If we say that it is a bug, should we document it at all?

**Comment by AlexDaniel** [comment]
If so, then this is not a trap, and we can simply mention it in the docs on ``Signal``. However, ``Signal`` is not documented yet.
