### ISSUE TITLE
.of not documented in Scalar

### ISSUE THREAD

**Issue by sjn** [perl6/doc#1482]
Found a possible  documentation bug. Here's the discussion on #perl6

http://colabti.org/irclogger/irclogger_log/perl6?date=2017-08-31#l739

In short, .VAR returns the Scalar object according to https://docs.perl6.org/language/mop#index-entry-syntax_VAR-VAR

...but .of isn't documented there. Instead you find it in the Variable class. There seems to be no inheritance going on here, so something is probably wrong here. :-)

https://docs.perl6.org/type/Variable#trait_of

**Comment by moritz** [comment]
Resolved in b7ef4cb953.
