### ISSUE TITLE
Keep .dot files

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1505]
I don't know if that's exactly what we want, but this could make it easier to contribute to the type graph generation.

A crude patch may look like this:

```patch
diff --git a/lib/Perl6/TypeGraph/Viz.pm b/lib/Perl6/TypeGraph/Viz.pm
index a4f661fa..3d0c79b0 100644
--- a/lib/Perl6/TypeGraph/Viz.pm
+++ b/lib/Perl6/TypeGraph/Viz.pm
@@ -96,6 +96,7 @@ class Perl6::TypeGraph::Viz {
         }
         die "bad filename '$file'" unless $file;
 
+        spurt $file ~ ‘.dot’, self.as-dot(:$size).encode;
         my $dot = Proc::Async.new(:w, 'dot', '-T', $format, '-o', $file);
         my $promise = $dot.start;
         await($dot.write(self.as-dot(:$size).encode));

```
But I'm sure there's a better way.

**Comment by JJ** [comment]
Keep them where? In the repository?

**Comment by AlexDaniel** [comment]
No, when you run `make`. Otherwise you get just svgs so fixing issues related to graphs is a bit complicated.

**Comment by JJ** [comment]
Nobody's objected, so just go ahead and add this.
