### ISSUE TITLE
Crash when running make: Method 'append' not found for invocant of class 'Array'

### ISSUE THREAD

**Issue by ShaneKilkelly** [perl6/doc#151]
I tried cloning this repo and building the docs. I ran `make`, the `htmlify` module crashed with the following error: 

```
$ cd doc
$ make
perl6 htmlify.p6
Initializing ...
Creating html/ subdirectories ...
Reading type graph ...
Method 'append' not found for invocant of class 'Array'
  in method roles at /Users/shanek/code/perl6doc/doc/lib/Perl6/TypeGraph.pm:46
  in regex roles at /Users/shanek/code/perl6doc/doc/lib/Perl6/TypeGraph.pm:14
  in regex TOP at /Users/shanek/code/perl6doc/doc/lib/Perl6/TypeGraph.pm:22
  in method parse-from-file at /Users/shanek/code/perl6doc/doc/lib/Perl6/TypeGraph.pm:61
  in method new-from-file at /Users/shanek/code/perl6doc/doc/lib/Perl6/TypeGraph.pm:30
  in sub MAIN at htmlify.p6:124
  in block <unit> at htmlify.p6:764
```

I'm new to perl6, (and new to perl in general), but it looks like `Array.append` is not part of the language.

My environment (on OSX Yosemite) :

```
$ brew info rakudo-star
rakudo-star: stable 2015.09 (bottled)
Perl 6 compiler
http://rakudo.org/
Conflicts with: parrot
/usr/local/Cellar/rakudo-star/2015.09 (815 files, 37M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rakudo-star.rb

$ perl6 --version
This is perl6 version 2015.09 built on MoarVM version 2015.09
```

**Comment by zoffixznet** [comment]
Sorry, but your Rakudo is too old and I don't think there's a Rakudo Star release yet with the latest and greatest Rakudo in it. You could `rakudobrew` the latest and greatest though (scroll down further in the page for instructions): http://rakudo.org/how-to-get-rakudo/

We're still in Beta so things are changing rapidly :smile_cat: 

Another option would be to checkout an older commit. I believe anything earlier than this one will work: https://github.com/perl6/doc/commit/e675207e08eb12cac4618a849a33bb8fd85def9e

I've ran `make` with the latest rakudo and all seems to work fine.

Cheers,
ZZ
