### ISSUE TITLE
Table in Pod::Block is broken

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1510]
https://docs.perl6.org/type/Pod::Block

**Comment by hankache** [comment]
Fixed in 6edad73

**Comment by hankache** [comment]
@AlexDaniel kindly close the issue if this is what you were looking for.

**Comment by JJ** [comment]
Looks OK to me. @AlexDaniel , can you check?

**Comment by AlexDaniel** [comment]
Yea that looks good. Thanks everyone!
