### ISSUE TITLE
nativeInt (int) is the only native type that is documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1512]
This is a continuation of https://github.com/perl6/doc/issues/372.

I think the table we have in [nativecall](https://docs.perl6.org/language/nativecall#Passing_and_Returning_Values) is enough, but maybe not. In fact, I see that types that you can use in nativecall signatures are not identical to what you can use with variables, so I guess I'm missing something.

**Comment by JJ** [comment]
What do you think should be done? Document every possible type?

**Comment by zoffixznet** [comment]
FWIW the CaR grant branch that'll be merged after next release (2018-05-19) adds a ["Numerics" language page](https://github.com/perl6/doc/blob/car-grant-midrat/doc/Language/numerics.pod6) that does mention native types.
