### ISSUE TITLE
TBDs on nativecall page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1513]
See https://docs.perl6.org/language/nativecall and search for TBD.

**Comment by JJ** [comment]
* [ ] Typed pointers
* [ ] Buffers and blows
* [ ] Library path and names.

**Comment by Kaiepi** [comment]
Library paths and names I've had to work out a lot of problems with because of OpenBSD's... rather interesting way of naming, versioning, and storing them, so I could probably write that up.

**Comment by JJ** [comment]
Please do it :-) Thanks!

**Comment by JJ** [comment]
@Kaiepi did you have the chance to work on that part?

**Comment by JJ** [comment]
:loudspeaker: 
Just library path and names to go!

**Comment by JJ** [comment]
@Kaiepi can work on that if he wants, too.

**Comment by Kaiepi** [comment]
I'll get started on this tomorrow
