### ISSUE TITLE
｢is default｣ is indexed twice

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1514]
![image](https://user-images.githubusercontent.com/5507503/29999596-5f6c2e08-9057-11e7-86d5-d32cb4928a4f.png)

It appears under “Reference” and “Trait” at the same time.

This is a continuation of https://github.com/perl6/doc/issues/1040.

**Comment by AlexDaniel** [comment]
Other traits are like this too. For example ``is required``.

**Comment by JJ** [comment]
Is this really a problem? It's clearly said in the second case it's a trait...

**Comment by JJ** [comment]
So do you think it should be taken off one of the two categories?
