### ISSUE TITLE
Docs for != operator should say that it is an alias to !==

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1515]
https://docs.perl6.org/routine/!=

This is a continuation of https://github.com/perl6/doc/issues/1227

**Comment by lancew** [comment]
Suggestions on wording for this other than say:

`Is an alias to C«!==»`

Presume in doc/Language/operators.pod6 ?

**Comment by AlexDaniel** [comment]
Probably ``X<C«!==»>`` to make it searchable.

**Comment by AlexDaniel** [comment]
It may be a good opportunity to say that ``!`` in ``!==`` is a metaop.

See also https://github.com/perl6/doc/issues/1227.

**Comment by AlexDaniel** [comment]
@lancew 🍕
