### ISSUE TITLE
Document unicode normalization

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1517]
It is already mentioned here:
* https://docs.perl6.org/language/unicode#File_Handles_and_I/O
* https://docs.perl6.org/language/unicode#UTF8-C8
* https://docs.perl6.org/language/traps#All_Text_is_Normalized_By_Default

But it feels like something is lacking. What purpose does it serve? Why do we do it? Maybe some links to unicode.org? Maybe some examples?

**Comment by samcv** [comment]
What section should this be added to, or do we need a new section?

**Comment by AlexDaniel** [comment]
I think right at the top would be nice. `Normalization` sounds ok as a heading. Maybe needs a word or two about graphemes also, possibly just copypasted from https://github.com/perl6/doc/commit/c0159cac65#diff-5ea33ed4c36cc3533068127d13fa490fR714.

FWIW there's also https://docs.perl6.org/language/traps#All_Text_is_Normalized_By_Default
