### ISSUE TITLE
Confusing search

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#1519]
Searching for "sub" and clicking on "sub" under "Reference" in the search results leads to:

https://docs.perl6.org/language/nativecall#index-entry-sub-nativecast

**Comment by AlexDaniel** [comment]
Please check in a few minutes after the doc rebuild. ``nativecast`` should be searchable and ``sub`` should not point to ``nativecast``.

**Comment by rafaelschipiura** [comment]
I just confirmed it's fixed. Closing.
