### ISSUE TITLE
How to use wincompose (unicode_entry)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1531]
We should mention https://github.com/samhocevar/wincompose on https://docs.perl6.org/language/unicode_entry

**Comment by JJ** [comment]
Can anyone who actually uses Windows do this? Or I can just point to that resource and tell people to use it.

**Comment by JJ** [comment]
Do you mind if I assign this issue to you and you do that part? I don't have Windows even in a VM...

**Comment by JJ** [comment]
So, does anyone want this issue?

**Comment by mienaikage** [comment]
I use WinCompose on my gaming machine with [kragen/xcompose](https://github.com/kragen/xcompose/blob/master/dotXCompose). I could look into putting some instructions together :+1:

**Comment by JJ** [comment]
Thanks!
