### ISSUE TITLE
Long line in the footer

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1535]
>  Generated on 2017-09-04T23:54:19Z from HomePage.pod6 from perl6/doc on GitHub, commit f7c92249. This is a work in progress to document Perl 6, and known to be incomplete. Edit this page. Please report any issues. Your contribution is appreciated. [Debug: off]

Perhaps it should be split it into more than one line?

**Comment by zakame** [comment]
@AlexDaniel yep I'm working on that bit :muscle:

**Comment by lancew** [comment]
I almost did a PR on this during the squashathon.

Curious if others feel :"This is a work in progress to document Perl 6, and known to be incomplete." is required or could be removed/reduced?

Perhaps:

HomePage.pod6 from perl6/doc on GitHub, commit f7c9224

 Please report any issues or edit this page.

 Your contribution is appreciated. [Debug: off]

**Comment by zakame** [comment]
I have this now sitting on an upcoming commit:

![image](https://user-images.githubusercontent.com/110625/30147050-8f4f49be-93ce-11e7-96ce-90fa960e9254.png)

What do you guys think? :)

**Comment by zakame** [comment]
And this one is from e.g. `/routines/sort`:

![image](https://user-images.githubusercontent.com/110625/30147363-88ca984e-93d0-11e7-887d-5483994b840b.png)

**Comment by lancew** [comment]
Looks better I think

**Comment by zakame** [comment]
Note that I haven't adjusted the CSS yet, so that yellow block still stretches when the page is on a full, wide screen.  I recall that there's supposed to be a style update in the offing?
