### ISSUE TITLE
LEAVE trap (my $x = …; LEAVE $x.foo)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1539]
It is a [fairly common](https://gist.github.com/63cd9da70c23a9886f8c8971ab239489) mistake.

Basically, code like this is wrong:
```perl6
my $x = 42;
LEAVE say $x.Int; # ← WRONG; assumes that $x is not Nil
```
This is true even if $x is defined at the start of the block.

For example:
```perl6
sub foo($ where ‘abc’) {
    my $x = 42;
    LEAVE say $x.Int; # ← WRONG; assumes that $x is not Nil
}
say foo ‘hello’; # OUTPUT: «No such method 'Int' for invocant of type 'Any'␤»
```

**Comment by smls** [comment]
Are you sure that this is not a Rakudo bug?
Why does the phaser run even though the subroutine's signature didn't match?

**Comment by AlexDaniel** [comment]
It could be, but generally assuming that ``LEAVE $foo.bar`` will work is a common trap.
