### ISSUE TITLE
Which phasers are compatible with "will trait"?

### ISSUE THREAD

**Issue by molecules** [perl6/doc#1553]
[`will trait`](https://docs.perl6.org/language/phasers#index-entry-will_trait) needs more details. Like exactly which phasers can be used as traits on variables and perhaps some more examples. I know it says "Only phasers that can occur multiple times within a block are eligible for this per-variable form.", but it is not clear to me which ones those are.

**Comment by JJ** [comment]
That link has disappeared now. I'll try and see where it's gone
