### ISSUE TITLE
add invocant to glossary

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1557]
This invented word invokes confusion: https://irclog.perlgeek.de/perl6/2017-09-16#i_15171710

**Comment by jonathanstowe** [comment]
All words are made up but as computer terms go it's actually used quite close to the dictionary definition https://www.merriam-webster.com/dictionary/invocant - hardly any metaphorical leap required :)

**Comment by AlexDaniel** [comment]
@jonathanstowe yes, but even if so, it would be nice to explain it for everyone who may not know the definition or expect that the definition can be looked up in a regular dictionary (that includes non-native speakers and possibly six-year-olds). It's not the most common word after all.
