### ISSUE TITLE
Make enums of in the IO::Notification searchable

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1558]
Please mind the enum!

**Comment by JJ** [comment]
What do you mean here?

**Comment by AlexDaniel** [comment]
This ticket is about [this](https://github.com/rakudo/rakudo/blob/98e575de00db42101d4879e43fe740a34791c418/src/core/IO/Notification.pm6), I think. There are some tests in roast [here](https://github.com/perl6/roast/blob/105250627d18c5915f4a98346a282a0e40b0dd75/S17-supply/watch-path.t).

**Comment by JJ** [comment]
Still. Rewrite documentation? Add an example?
