### ISSUE TITLE
reduce metaops [ ] and [\ ] aren't immediately searchable

### ISSUE THREAD

**Issue by timo** [perl6/doc#1559]
when you search for `[\` or `[\ ]` and use the "web search" you can get to the reduce page directly, but searching for anything with an operator in between will give useless results, for example the front page itself is the first entry.

**Comment by coke** [comment]
For anything other than simple "this string must produce this search result", there has to be special logic in the JS search function. Can you help map out what you want that logic to look like?

Do you want [foo] to link to just foo? or to just [] ? or show both? (that sort of thing)

**Comment by rafaelschipiura** [comment]
[+] links to []. I think [<any operator>] should do the same. Should be an wildcard there.

**Comment by JJ** [comment]
I'll see how's this thing now.
