### ISSUE TITLE
Feature request: make '/' a shortcut to focus in the search box.

### ISSUE THREAD

**Issue by coke** [perl6/doc#156]
If we're not in a form field, hitting / anywhere on the page should focus on the search box.

**Comment by paultcochrane** [comment]
Something to take into consideration: this would likely cause problems with tools such as [vimperator](http://www.vimperator.org/vimperator), which use '/' as a shortcut for searching on a page.

**Comment by labster** [comment]
Typing slash brings up a page search in stock Firefox, no vimperator required.

**Comment by moritz** [comment]
How about mapping a different key, such as "s" (search) or 'f' (find)?

**Comment by zoffixznet** [comment]
The shortcut's already there. Just press `TAB` twice :D

I'm always wary binding stuff like that. I mean, there's nothing stopping me from remapping `/` to `s` for quicksearch and then getting issues.

I guess we can bind it to `s` and see if anyone complains? :smile_cat:

**Comment by coke** [comment]
@labster  - not page search, our built in search box.

@moritz  - I'm used to / from many other apps. If there's a better/more standard key, sure.

@zoffixznet  I get your concern. starting with focus there would eliminate the need for my keyboard shortcut most of the time.

**Comment by zoffixznet** [comment]
> @zoffixznet I get your concern. starting with focus there would eliminate the need for my keyboard shortcut most of the time.

I think that's the best solution. If we add any shortcuts that still leaves the issue of advertising that shortcut to the user. Starting with focus there facilitates ease of search, while still being able to press `TAB` to move away from the search box.

**Comment by coke** [comment]
+1

**Comment by AlexDaniel** [comment]
Just in case somebody stumbles upon this issue: we now provide ``f`` access key.
