### ISSUE TITLE
puzzle in class Capture's doc, it really  does Positional and does Associative ?

### ISSUE THREAD

**Issue by TisonKun** [perl6/doc#1565]
[21:07] <wander4096> m: my $c = class Foo { has $.foo = 42; }.new.Capture; say $c{"foo"}; say $c.does(Associative);
[21:07] <+camelia> rakudo-moar b76f7c: OUTPUT: «42␤False␤»
[21:08] <wander4096> `class Capture does Positional does Associative { }`
[21:08] <wander4096> m: my $c = class Foo { has $.foo = 42; }.new.Capture; say $c[0]; say $c.does(Positional);
[21:08] <+camelia> rakudo-moar b76f7c: OUTPUT: «Nil␤False␤»
[21:11] <wander4096> m: say Capture.does(Associative)
[21:11] <+camelia> rakudo-moar b76f7c: OUTPUT: «False␤»
[21:11] <wander4096> m: say Capture.does(Positional)
[21:11] <+camelia> rakudo-moar b76f7c: OUTPUT: «False␤»

**Comment by rafaelschipiura** [comment]
Well, it looks like it does to me:

    my $n := \('a', 'b', c => 3, d => 4); say $n[0, 1], $n<c d>

**Comment by jonathanstowe** [comment]
It  implements a sufficiency of the AT-KEY, AT-POS and related methods that it behaves like a Positional or an Associative (I don't believe a type *must* consume those roles to take a subscript,)

https://docs.perl6.org/language/subscripts#Custom_types

**Comment by b2gills** [comment]
I think Capture should probably do those roles, unless there is a very good reason not to.

    > my %a := \(:b);
    Type check failed in binding; expected Associative but got Capture (\(:b))
      in block <unit> at <unknown file> line 1

**Comment by W4anD0eR96** [comment]
@jonathanstowe it means that `Capture` does not really `does Positional does Associative` but acts like them?

**Comment by W4anD0eR96** [comment]
@rafaelschipiura yes my example on Positional is bad.
the check `Capture.does(Positional)` out False, does it imply a Capture acts like Positional but not exactly Positional?

**Comment by rafaelschipiura** [comment]
@W4anD0eR96 No, your bug report is fine, I didn't mean to contradict you at all. Captures do those roles through Duck Typing, but not through the formal Perl6 type system in Rakudo.

So, we have to either decide if we should formalize that they won't do those things (either in Rakudo or in the language) and document that, or we should register that Rakudo doesn't follow what Perl6 wants and then try to change that in the future.

Anyway, this involves the docs, the spec and Rakudo, so it will take some exploration to get to the right answer. Therefore this bug report should stay open until we have an answer.

**Comment by W4anD0eR96** [comment]
relevant RT#124485 RT#124484

from 2 years ago

**Comment by JJ** [comment]
Wouldn't this be NOTSPECCED rather than external?

**Comment by AlexDaniel** [comment]
@JJ arguably the tests are there, and we also seem to agree that it should do Positional and Associative, so it is specced. The problem is that rakudo does not pass these tests yet, so it's just a rakudobug.

**Comment by JJ** [comment]
I'll change external to bug then.

**Comment by JJ** [comment]
@TisonKun they describe some "skipped" tests for the time being, meaning they will stay that way for some time. When they are fixed, we'll have to change the documentation, but for the time being the docs have to match the definition, which does not include "does Associative does Positional".

**Comment by TisonKun** [comment]
@JJ thanks for the explanation. So I might prefer to file an issue to track the inconsistency between doc and spec. But I do not insist it.

**Comment by JJ** [comment]
It's actually inconsistent-ish. It's not defined that way, but it behaves as such. That's probably the reason why it's been left that way...
