### ISSUE TITLE
The "Variables" page should describe the `constant` declarator

### ISSUE THREAD

**Issue by lefth** [perl6/doc#1566]
I could only find `constant` mentioned on one of the perl 5-to-6 pages, which isn't where the meat of the documentation lives. When it's described, it would be helpful to list the non-obvious differences between `constant` and `my` or `our`. For example, constant variables can't have a type constraint.

**Comment by JJ** [comment]
I would say this should go to the Variable page. In fact, `constant` is used in several examples.
