### ISSUE TITLE
doc /type/Kernel

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1569]

**Comment by AlexDaniel** [comment]
That's a dup of https://github.com/perl6/doc/issues/503, but I don't really want to close this because I like smaller tickets. maybe https://github.com/perl6/doc/issues/503 should be split into 4 tickets (one of which is right here).

**Comment by lizmat** [comment]
Initial version pushed with df06cbc0709ec26848321eb . Comments welcome!

**Comment by AlexDaniel** [comment]
Although… I think we'll discuss it all in #503, so we can close this for now.
