### ISSUE TITLE
add operator declarators to /type/Sub

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1573]

**Comment by AlexDaniel** [comment]
I came here while squashathoning and I am a bit confused, what exactly should be added?

**Comment by W4anD0eR96** [comment]
@AlexDaniel #1646 relevant.

In fact we mention it somewhere at /language/operators/
so I think we need not to add so-call operator declarators, but think of how we rearrange the doc.

**Comment by JJ** [comment]
How would you want to rearrange it?

**Comment by JJ** [comment]
Well, no clarification here, so I guess what it means is that, in the same way as traits are explained here, the definition of operators should be explained too. I'll try and fix it that way, if that's not the case, please clarify.
