### ISSUE TITLE
Group All p5-to-p6 Docs Together

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#158]
The main `5to6` guide is all the way in the middle of the list and isn't obvious. It would be nice if it were grouped together with all the other `5to6` guides at the top:

![p6](https://cloud.githubusercontent.com/assets/5747918/10433949/24239f0a-70e4-11e5-9a6a-03dfe0ddbe73.png)

**Comment by dha** [comment]
I think that was suggested a while back along with a general restructuring of the docs. If we can agree on a good heading for a P5->P6 grouping, I'm all for it.

**Comment by zoffixznet** [comment]
`5to6-intro` for the `Perl 5 to Perl 6 Translation..` one sounds good to me. This way it will be grouped with the rest of `5to6` docs and appear as the first doc in that subset.

**Comment by pmichaud** [comment]
Perhaps "5to6-overview" is slightly better than "5to6-intro"?  "Overview" reminds me of the initial overview chapters in the camel books, and that way it can include material that might not be "introductory".

I might also suggest "5to6-nutshell", if that's a more accurate description of what is currently in the "How do I do what I used to do?" section.

**Comment by zoffixznet** [comment]
> I might also suggest "5to6-nutshell"

:+1:

**Comment by stmuk** [comment]
https://github.com/perl6/doc/commit/e135e36927a9432d90636ec083d6c1ef87acf8de
