### ISSUE TITLE
How to pipe two Proc::Asyncs

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1580]
The docs on [Proc](https://docs.perl6.org/type/Proc) have a nice example:
```perl6
my $p1 = run 'echo', 'Hello, world', :out;
my $p2 = run 'cat', '-n', :in($p1.out), :out;
say $p2.out.get;
```

We should provide the same thing for [Proc::Async](https://docs.perl6.org/type/Proc::Async).

See also: https://irclog.perlgeek.de/perl6/2017-09-25#i_15213849

**Comment by zoffixznet** [comment]
This seems to work: 
```
my $proc1 = Proc::Async.new: "cal"; my $proc2 = Proc::Async.new: «perl6 -e "slurp.uc.put"»; $proc2.bind-stdin: $proc1.stdout: :bin; await $proc1.start, $proc2.start
```

The `.bind-stdin`, `.bind-stdout` (and `.bind-stderr`) methods don't appear to be documented, but *are* featured in master roast.

**Comment by AlexDaniel** [comment]
I think this was resolved in https://github.com/perl6/doc/commit/db2e07bfb7290f21f14319a1c2db029576eeea16.

There's a separate issue for undecumented ``.bind-*`` methods: https://github.com/perl6/doc/issues/1470
