### ISSUE TITLE
Grammar.parse talks about :c but it is actually :pos

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1583]
```perl6
grammar G { regex TOP { \d } }; my $str = ‘123’; my $g = G.new; for ^3 { $g.parse($str, :pos(2)).say }
```
```
｢3｣
｢3｣
｢3｣
```

Same with .subparse.

Also, maybe we should provide a .subparse example? For example:

```perl6
grammar G { regex TOP { \d } }; my $str = ‘123’; my $g = G.new; for ^3 { $g.subparse($str, :pos($/.to // 0)).say }
```

**Comment by softmoth** [comment]
:c() and :pos() should both work. They don't do the same function (:pos() implicitly anchors the search at the position, :c() does not).

**Comment by W4anD0eR96** [comment]
@AlexDaniel where is its location? I cannot see this sentence inside the doc grammar or grammar_tutorial now

**Comment by AlexDaniel** [comment]
I think the issue was about this:

> Additional named arguments are used as options for matching, so you can specify things like :c(4) to start parsing from the fourth character

https://docs.perl6.org/routine/parse#(Grammar)_method_parse

https://github.com/perl6/doc/blob/0b5126a5772e5047cbd9acda83be81e4b9da8d10/doc/Type/Grammar.pod6#L44

**Comment by W4anD0eR96** [comment]
@AlexDaniel #1645 , how about other adverbs, I cannot figure it out

**Comment by AlexDaniel** [comment]
@W4anD0eR96 I think this can be closed? The original issue says that it should not talk about “:c(123)” and it no longer does, so that is it? I don't know about %opts, maybe create another issue for it?

**Comment by W4anD0eR96** [comment]
@AlexDaniel , agree with you.
