### ISSUE TITLE
Term "smartmatch" is not searchable

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1587]
It's a pretty common term, but typing "smartmatch" or "smart match" into search box shows nothing or "postmatch"

**Comment by coke** [comment]
Note that "smart-match" is searchable.

Need to add another anchor to "doc/Language/operators.pod6" line 1629.

**Comment by W4anD0eR96** [comment]
@coke since line 1630 has already added an anchor, should we add another line 1629?
The search for "smart-match" works well for me
