### ISSUE TITLE
Mention ｢my %h{Int}｣ syntax when talking about non-string keys

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1588]
See https://docs.perl6.org/type/Hash#Non-string_keys

There's a little useful hint on https://docs.perl6.org/type/Hash#method_keyof:
```
my %h2{Str} = 'oranges' => 7;            # (keys must be of type Str)
```
But it's hard to find it from “Non-string keys” section.

**Comment by BenGoldberg1** [comment]
It might also be worthwhile to also mention hashes with no restriction on keys `my %h3{Any};`

**Comment by W4anD0eR96** [comment]
I think this mention some of it: https://docs.perl6.org/type/Hash#Object_hashes_and_type_constraints
while it gets a wrong hierarchy in the doc -- it is below `Looping over hash keys and values'

**Comment by W4anD0eR96** [comment]
@AlexDaniel #1602 may fix it, and this issue can be closed

**Comment by AlexDaniel** [comment]
I think [it](https://docs.perl6.org/type/Hash#Non-string_keys_(object_hash)) is a bit convoluted and hard to read, but indeed this issue is resolved. I'll leave this open for just a little bit in case someone has any thoughts on how to reword it so that it reads better, but otherwise this can be closed.

**Comment by W4anD0eR96** [comment]
@AlexDaniel Yes, maybe it can be rewritten using more simple examples.
