### ISSUE TITLE
Duration and numeric context

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1589]
https://docs.perl6.org/type/Duration

> In numeric contexts (situations where a Duration is used as a number), a Duration will return either a Rat or a FatRat representing the number of seconds it holds.

```perl6
say WHAT (5 + Duration.new(5)) # (Duration)
```

So it does not really return anything other than Duration?

See also [RT #127341](https://rt.perl.org/Ticket/Display.html?id=127341)

**Comment by JJ** [comment]
Well, the type of the object is `Duration`, but `say  (½ + Duration.new(5))` returns 5.5, which is a `Rat`.
