### ISSUE TITLE
feature request: make p6doc customizable

### ISSUE THREAD

**Issue by skaji** [perl6/doc#159]
Currently p6doc uses Pod::To::Text to render pod.
I want to change it more colorful renderer (in that case `less` must be `less -R`).
It's nice I could change it like perl5 perldoc where we could change its behavior via PERLDOC.

**Comment by ab5tract** [comment]
All of those things :)

There are already other ENV vars 'P6DOC_DEBUG' and 'P6DOC_INTERACT', so no
problem to hook 'P6DOC_RENDERER' or such. Awesome!

**Comment by stmuk** [comment]
@shoichikaji if you set  POD_TO_TEXT_ANSI it will render in colour.

I was considering setting this as default since the perl6 errors are colour.

**Comment by shoichikaji** [comment]
I know that POD_TO_TEXT_ANSI enables Pod::To::Text color.
But I want more colors like perl5 Pod::Text::Color::Delight
(see japanese blog http://moznion.hatenadiary.com/entry/2013/10/26/235833 for screenshots)

If p6doc can change its renderer, I will port Pod::Text::Color::Delight to perl6.

**Comment by moritz** [comment]
I'll surely accept patches to make the renderer configurable, once there's an alternative.

I'd even be fine with preferring something more fancy by default if it's installed, and falling back to Pod::To::Text if not.

**Comment by ab5tract** [comment]
POD_TO_TEXT_ANSI is better served by a P6DOC_RENDERER as well. It seems
more useful to be able to choose one's own (or accept a default) rather
than name an env var after a specific library, It can perhaps become the
default if nothing is set there by the environment?

**Comment by AlexDaniel** [comment]
Can anybody figure out what this ticket is asking for exactly? For example, can we have a list of things we have to get done in order to close this?

**Comment by coke** [comment]
Also, p6doc is a very thin wrapper around perl6 --doc -- does this ticket belong in the Rakudo queue? (would we be changing our wrapper to support this, or would the change go to the perl 6 executable itself?)

**Comment by JJ** [comment]
Yep, it would belong to the Rakudo queue, not this one. I'm all for...

... wait for it...

Closing it :-)

**Comment by JJ** [comment]
Sorry, but I'm closing this. As indicated above, p6doc is a wrapper around perl6 --doc and thus, right now, it belongs to Rakudo, not documentation. So closing this, and if you want to raise the issue in Rakudo, please do it by all means.

**Comment by AlexDaniel** [comment]
Hm. I think you can already do perl6 --doc=Something, and it will use Pod::To::Something? So the feature already exists?
