### ISSUE TITLE
Broken Link for nextwith method

### ISSUE THREAD

**Issue by tushardave26** [perl6/doc#1592]
Hello,

Recently, I am reading about the ```clone``` method in the [docs](https://docs.perl6.org/routine/clone). The explanation of ```clone``` method for object cloning mentions about ```nextwith``` method. It is basically hyperlinked to the method specific page. The hyperlink for ```nextwith``` method is broken. Can someone please take a look at it?

Thanks.

**Comment by zoffixznet** [comment]
Fixed in https://github.com/perl6/doc/commit/57f7680f439e73f7932e6da81eb366d6f71a1820 

Thanks.
