### ISSUE TITLE
command line named para form

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1595]
Link: https://docs.perl6.org/language/functions#index-entry-MAIN
it says that you pass named para both `-v` or `--verbose`
sure the Usage message is: `main.p6 -v|--verbose=<Any>`
but it also works by `perl6 main.p6 -verbose=1 ` and `perl6 main.p6 --v=1 `
the program below

sub MAIN(:v(:$verbose) is required) {
  say $verbose;
  say "Accepted!";
}

so is it a bug, or just a missing doc?

@unclechu
@moritz

since i see your talk in https://irclog.perlgeek.de/perl6/2017-09-24#i_15209949

**Comment by CIAvash** [comment]
You missed the `Bool`. It should be `Bool :v(:$verbose)`.

**Comment by CIAvash** [comment]
Hmm, I missed the use of single dash (`-verbose`). I focused on your use of `=1`

**Comment by unclechu** [comment]
@W4anD0eR96 yep, @CIAvash is right, you should annotate type `Bool` explicitly to make it works as a flag:
```
sub MAIN(Bool :v(:$verbose) is required) {
  say $verbose;
  say "Accepted!";
}
```

**Comment by W4anD0eR96** [comment]
@unclechu so the program becomes

```
sub MAIN(Bool :v(:$verbose) is required) {
  say $verbose;
  say "Accepted!";
}
```

which also works

```
> perl6 main.p6 --v=True
True
Accepted!
```

what I focus is that `--v` but not `-v` as description `Usage: main.p6 -v|--verbose=<Any>`

**Comment by W4anD0eR96** [comment]
@unclechu 
And I find through this page and can't see what i focus
