### ISSUE TITLE
Signature has extra :

### ISSUE THREAD

**Issue by coke** [perl6/doc#1597]
https://github.com/perl6/doc/blob/master/doc/Type/Signature.pod6#L753

Test that it's fixed with:

```
perl6 xt/examples-compilation.t doc/Type/Signature.pod6
```

**Comment by W4anD0eR96** [comment]
below is the error msg

\# multi method ACCEPTS(Signature:D: Signature: $topic)
\# multi method ACCEPTS(Signature:D: Capture $topic)
\# multi method ACCEPTS(Signature:D: Mu \topic)
\# Can only use : as invocant marker in a signature after the first parameter
not ok 60 - doc/Type/Signature.pod6 chunk 60 compiles

\# Failed test 'doc/Type/Signature.pod6 chunk 60 compiles'
\# at xt/examples-compilation.t line 113

**Comment by coke** [comment]
This was fixed with b5437dc7
