### ISSUE TITLE
Link to "ACCEPTS" in doc for ~~ is broken

### ISSUE THREAD

**Issue by xiaq** [perl6/doc#1599]
In [doc for ~~](https://docs.perl6.org/language/operators#infix_~~) ACCEPTS links to https://docs.perl6.org/type/ACCEPTS. However it should be https://docs.perl6.org/routine/ACCEPTS.

**Comment by W4anD0eR96** [comment]
I try to fix it in #1600

**Comment by AlexDaniel** [comment]
Seems to be fixed now.  @W4anD0eR96++
