### ISSUE TITLE
WhateverCode on the LHS of ~~ (trap?)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1603]
A [question](https://irclog.perlgeek.de/perl6/2017-10-11#i_15290908) on #perl6 channel was asked today:
```perl6
my @a = <1 2 3>; say @a.grep( *.Int ~~ 2 );
```
```
Cannot use Bool as Matcher with '.grep'.  Did you mean to use $_ inside a block?
  in block <unit> at <tmp> line 1
```

> why is this? why doesn't this dwim?

Followed by:
> \<geekosaur\> 	I thought this was a listed/known trap

Yet I don't see it listed on the traps page. We have a similar item [there](https://docs.perl6.org/language/traps#Topicalizing_Operators)… similar but completely different. That being said, the trick that is mentioned there still applies:
```perl6
my @a = <1 2 3>; say @a.grep( 2 ~~ *.Int );
```
```
(2)
```
However, more common solution to this is to use a block instead:
```perl6
my @a = <1 2 3>; say @a.grep( {.Int ~~ 2} );
```
```
(2)
```

**Comment by W4anD0eR96** [comment]
IMO it's a trap, for
`*.Int ~~ 2` equals `2.ACCEPTS(*.Int)`, and return False(the latter is WhateverCode)
`2 ~~ *.Int` equals `*.Int.ACCEPTS(2)` and it is a instance of WhateverCode
