### ISSUE TITLE
Proc::Async.Supply not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1605]
```
Zoffix 	I thought you could merge STDOUT/STDERR with Proc::Async... looks like the info's gone from the docs, even though the code has $!merge_blah blah in it
jnthn 	It's just .Supply
```

**Comment by AlexDaniel** [comment]
As far as I know it's broken and shouldn't be mentioned. Let's find the ticket ID maybe.

**Comment by zoffixznet** [comment]
Broken where? The docs site documents the language.

**Comment by AlexDaniel** [comment]
Broken in rakudo. Yeah, it documents the language, but suggesting things that are outright broken is not going to do any good.

The ticket is here: [RT #131763](https://rt.perl.org/Ticket/Display.html?id=131763). That said, I think I cannot reproduce it on HEAD. Trying.

**Comment by AlexDaniel** [comment]
OK. Seems that RT #131763 is resolved (but stress tests are needed), so I guess there's no problem documenting this.

For further discussion on documenting rakudo issues see https://github.com/perl6/doc/issues/1486
