### ISSUE TITLE
Document `submethod DESTROY`, and its intricacies

### ISSUE THREAD

**Issue by smls** [perl6/doc#1606]
Custom classes can implement `submethod DESTROY` to do some clean-up when/if an object of that class is about to be garbage-collected.

AFAICT, p6doc currently does not explain this.

---

There are some intricacies to document:

* It is not guaranteed to be run (e.g. it'll never run for objects that aren't garbage collected before the end of the program).
* It is called by the garbage collector, on a thread whose normal control flow is currently paused.
* One mustn't make any assumptions about what the dynamic environment of that thread currently looks like.   <sup>("[just about *anything* can be on the call stack at the point a DESTROY is called](https://irclog.perlgeek.de/perl6/2017-10-14#i_15301619)" &mdash; jnthn)</sup>.
* For example...
  * if the thread in question has called `.protect(&code)` on a [`Lock`](http://docs.perl6.org/type/Lock)...  
  * and is in the middle of executing `&code` when it is paused by garbage collection...
  * and your `DESTROY` method calls `.protect(&cleanup)` on the same lock...

  ...then `&cleanup` will be executed immediately even though `&code` has not yet finished &ndash; because `Lock.protect` is idempotent (i.e. can be recursively locked from the same thread).
* In such cases, one can write a DESTROY method as follows to ensure it is run on a "clean" thread that is not in the middle of doing things which may cause surprises for your clean-up code:  
  `submethod DESTROY { start { ... } }`  
  I.e. in the `Lock` example:  
  `submethod DESTROY { start $lock.protect: { ... } }`  
  You can safely close over `self` in the `{ ... }` part, and object destruction will be deferred for as long as necessary <sup>(without calling `DESTROY` a second time &ndash; see jnthn's comment below)</sup>.
  See IRC discussion [starting here](https://irclog.perlgeek.de/perl6/2017-10-14#i_15301603).

**Comment by jnthn** [comment]
Also worth noting the "you only live twice" semantics - that is, if you bring an object back to life by referencing it from somewhere else again, then the second time it become free the `DESTROY` method will not be called a second time. For a given instance, `DESTROY` is called at most once.
