### ISSUE TITLE
The sequence operator infix:<...> is not listed

### ISSUE THREAD

**Issue by Grimy** [perl6/doc#1621]
The [operator list](https://docs.perl6.org/routine-operator.html) is missing the [sequence operator](https://docs.perl6.org/language/operators#infix_...) and its variants:

* There’s only one entry for `...`, which links to the yada yada yada operator.
* There are no entries at all for `...^`, `…`, and `…^`.

**Comment by AlexDaniel** [comment]
Should we have separate entries for all these? I think yes.
