### ISSUE TITLE
Adding more information near the title.

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#1624]
From splitting #1212 

- [ ]  Add a `( ... )` in small text following the title containing some stuff, as follows...

- [ ]  lang version (could initially be a hardcoded string `6.c`) ;

- [ ]  an `i` or info icon link to 'about doc` ;

- [x]  a pencil icon that links to the edit URL ;

**Comment by coke** [comment]
Language version has to be much more fine grained - basically at each heading level, since it could apply to a method, for example.

**Comment by JJ** [comment]
The pencil icon is there as far as I can tell. What do you mean with "about doc"? An about doc for the whole site? And what about lang version? Do we really need that? There are literally thousands of versions we would have to add at this level... And I don't get what is the point of the (...).

**Comment by JJ** [comment]
It's a wishlist item. It's as good as closed. But you opened it, you close it, fair enough.

**Comment by rafaelschipiura** [comment]
I closed it because it's duplicated in my view. Everything TODO here is already asked for in other bugs.

**Comment by JJ** [comment]
Could you please point out which ones?

**Comment by rafaelschipiura** [comment]
Sure, #1622 and #2690
