### ISSUE TITLE
install man pages

### ISSUE THREAD

**Issue by coke** [perl6/doc#1625]
Old TODO that was originally added by Tom Browder in 07d735dbf
 
```
    # TODO: For the moment rakudo doc pod files were copied
    #       from its repo to subdir doc/Programs and modified to Perl 6 pod.
    #       The rakudo install needs
    #       to (1) copy those files to its installation directory (share/pod)
    #       and (2) use Perl 5's pod2man to convert them to man pages in
    #       the installation directory (share/man).
    #
    #       Then they can be copied to doc/Programs.
```

**Comment by JJ** [comment]
Not clear what you mean here.

**Comment by tbrowder** [comment]
That was a while ago, but the TODO note was meant to suggest turning the POD text to a man page, but that was before I knew about p6doc.

**Comment by JJ** [comment]
So maybe close it now?

**Comment by tbrowder** [comment]
@JJ, let me take another look first...

**Comment by JJ** [comment]
OK

**Comment by tbrowder** [comment]
I still think we need to somehow generate *nix man pages from available pod6 and any other suitable docs available, but that whole idea is probably best left for more discussion on module and other program documentation requirements.

You may close this issue.

**Comment by Tyil** [comment]
I am all for a `Pod::To::Man` module, sadly I don't know too much on how to work with Pod to generate a man page out of it. Might be an interesting thing to look at when I'm bored, though.
