### ISSUE TITLE
doc >>. on lists of Callables

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1643]
```
say (&sin, &cos, &sqrt)».(0.5);
rakudo-moar dcf3e28c5: OUTPUT: «(0.479425538604203 0.877582561890373 0.707106781186548)␤»
```

**Comment by smls** [comment]
That's not a special construct, but a combination of these features:
1. `( )` is a postcircumfix operator *(documented [here](https://docs.perl6.org/language/operators#postcircumfix_(_)))*
1. postcircumfixes may be written in dot notation *(documented [here](https://docs.perl6.org/language/operators#postfix_.postfix_/_.postcircumfix))*
1. postcircumfixes can be hypered *(not yet documented)*:

``` Perl 6
@foo»[0]     # works
@foo».[0]    # works
@foo»{"a"}   # works
@foo».{"a"}  # works
@foo»<a>     # works
@foo».<a>    # works
@foo»()      # does NOT work, for some reason - bug?
@foo».()     # works
```

No.3 should be documented in [operators#Hyper_Operators](https://docs.perl6.org/language/operators#Hyper_Operators), which already documents hypered postfix operators and method calls.

(There's also [this section](https://docs.perl6.org/language/operators#postfix_%C2%BB._/_postfix_%3E%3E.), which is a bit dubious because that's not actually an operator as such.)

**Comment by W4anD0eR96** [comment]
@smls 
`@foo»(0.5)      # does NOT work, for some reason - bug?`
turns to, if `@foo = [&sin, &cos, &sqrt]`
`(0.5).CALL-ME(&sin)` and so on
so it complains "No such method 'CALL-ME' for invocant of type 'Rat'"

However, `@foo».(0.5)     # works`
turns to
`&sin.(0.5)` and so on

Not a bug I think

**Comment by smls** [comment]
> turns to [...] `(0.5).CALL-ME(&sin)` and so on

Shouldn't it turn into `&sin.CALL-ME(0.5)`?

Also, it looks like what's currently happening is even weirder:

    ➜  [&sin, &cos, &sqrt]»( &say );
    sub sin ($) { #`(Sub+{is-pure}|93829902580832) ... }sub say (| is raw) { #`(Sub|93829903363016) ... }
    sub cos ($) { #`(Sub+{is-pure}|93829902582048) ... }sub say (| is raw) { #`(Sub|93829903363016) ... }
    sub sqrt ($) { #`(Sub+{is-pure}|93829902595424) ... }sub say (| is raw) { #`(Sub|93829903363016) ... }

**Comment by W4anD0eR96** [comment]
@smls 
interesting,

```
> dd [&sin, &cos, &sqrt]»( &say );
sub sin ($) { #`(Sub+{is-pure}|140321546561448) ... }sub say (| is raw) { #`(Sub|140321547176936) ... }
sub cos ($) { #`(Sub+{is-pure}|140321546562664) ... }sub say (| is raw) { #`(Sub|140321547176936) ... }
sub sqrt ($) { #`(Sub+{is-pure}|140321546576040) ... }sub say (| is raw) { #`(Sub|140321547176936) ... }
[Bool::True, Bool::True, Bool::True]
```
I am going to rakudo to find out how `>>` works

**Comment by W4anD0eR96** [comment]
@smls 

https://github.com/rakudo/rakudo/blob/23776247298f24fe374903e5239cdd61f173078a/src/Perl6/Actions.nqp#L7511

take a look at examples below


13:35 | wander | m: sub see-what-pass { dd @_; }; [1,2,3]>>( &see-what-pass );
13:35 | camelia | rakudo-moar b386963a3: OUTPUT: «[1, sub see-what-pass (*@_) { #`(Sub\|60245232) ... }]␤[2, sub see-what-pass (*@_) { #`(Sub\|60245232) ... }]␤[3, sub see-what-pass (*@_) { #`(Sub\|60245232) ... }]␤»
13:37 | wander | m: sub postfix:<!> { dd @_; }; [1,2,3]>>!;
13:37 | camelia | rakudo-moar b386963a3: OUTPUT: «[1]␤[2]␤[3]␤»

so, normally use `>>` with postfix operator

**Comment by W4anD0eR96** [comment]
@gfldex I think "doc >>. on lists of Callables" is not so different from examples existing.

see 
```
say (<a b>, <c d e>)».elems;        # OUTPUT: «(2 3)␤» 
say (<a b>, <c d e>)».&{ .elems };  # OUTPUT: «((1 1) (1 1 1))␤» 
```

but if you find it worth to add new examples, you can do it by yourself and send a PR.

**Comment by W4anD0eR96** [comment]
@AlexDaniel , I don't think we have to document ">>. on lists of Callables".

Because it's no more than [obj1, obj2, ...]>>.method

And we may be going to rearrange the doc in a few days, so keep the doc from redundant.

To sum up, this issue can be closed.
