### ISSUE TITLE
How does regex greedy quantifier "!" work?

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1644]
[10:33] <wander> m: say 'fooobar' ~~ /fo**:{1..3}obar/;
[10:33] <+camelia> rakudo-moar 697e4ecff: OUTPUT: «Nil␤»
[10:33] <wander> m: say 'fooobar' ~~ /fo**:?{1..3}obar/;
[10:33] <+camelia> rakudo-moar 697e4ecff: OUTPUT: «｢fooobar｣␤»
[10:33] <wander> m: say 'fooobar' ~~ /fo**:!{1..3}obar/;
[10:33] <+camelia> rakudo-moar 697e4ecff: OUTPUT: «｢fooobar｣␤»

If "!" does be the explicit way to enable greed, and `/fo**:{1..3}obar/` using greedy, there is a way to explicitly request greedy with "!" in the regex.

**Comment by smls** [comment]
The following are the possible combinations of backtracking modifiers for the `** 1..3` quantifier:

* greedy matching with backtracking:

``` Perl 6
say "aaa" ~~ /           a **   1..3  a /;  # ｢aaa｣
say "aaa" ~~ /           a **!  1..3  a /;  # ｢aaa｣
say "aaa" ~~ /           a **:! 1..3  a /;  # ｢aaa｣
say "aaa" ~~ / :ratchet  a **!  1..3  a /;  # ｢aaa｣
say "aaa" ~~ / :ratchet  a **:! 1..3  a /;  # ｢aaa｣
```

* frugal matching with backtracking:

``` Perl 6
say "aaa" ~~ /           a **?  1..3  a /;  # ｢aa｣
say "aaa" ~~ /           a **:? 1..3  a /;  # ｢aa｣
say "aaa" ~~ / :ratchet  a **?  1..3  a /;  # ｢aa｣
say "aaa" ~~ / :ratchet  a **:? 1..3  a /;  # ｢aa｣
```

* greedy matching without backtracking ("ratchet"):

``` Perl 6
say "aaa" ~~ /           a **: 1..3  a /;  # Nil
say "aaa" ~~ / :ratchet  a **  1..3  a /;  # Nil
say "aaa" ~~ / :ratchet  a **: 1..3  a /;  # Nil
```

---

Some notes:

* `:!` is the default behavior. You only need to specify it explicitly when you used the `:ratchet` modifier but want to override it for a single atom.

* Similarly, you only need `:` when you're *not* in ratchet mode but want to prevent backtracking for a single atom.

* Also, `:!` and `:?` can be abbreviated to `!` and `?` when they're applied to a quantifier. The full form with the colon is only necessary when applying them to an alternation, as in:

``` Perl 6
"ab" ~~ / :ratchet [a || ab]:! $ /
```

**Comment by W4anD0eR96** [comment]
> `say "aabb" ~~ /           . **:! 1..4  b /;  # ｢aabb｣`
> (The quantifier first matches aabb, but then the next atom cannot match, so it backtracks to match aab, after which the b can match.)
> `say "aabb" ~~ /           . **: 1..4  b /;  # Nil`
> (The quantifier first matches aabb, but then the next atom cannot match, and backtracking into the quantifier is disabled so the match fails.)

So I can be `!` override `:`?

**Comment by W4anD0eR96** [comment]
09:13 | yoleaux | 06:32Z <wander> moritz: why `say 'fooobar' ~~ /fo**:{1..3}obar/;` results differently with `say 'fooobar' ~~ /fo**:!{1..3}obar/;`
09:14 | moritz | why wouldn't it? it's not the same regex :)
09:16 |   | with : you disable backtracking, so the first part matches all o's, causing the "obar" to fail
09:16 |   | with ! you re-enable it, so the quantifier can give up the extra o again
09:16 |   | :! seems kinda non-sensical
10:50 | wander | moritz, so can I say, in ":!", "!" override ":"? does it imply we can only have one modifier on quantifier?
10:53 | moritz | wander: yes, and I think so

**Comment by smls** [comment]
> so can I say, in ":!", "!" override ":"?

No, `:!` is a single modifier. (`!` is its short-hand form, for use with quantifiers.)  

`:` is a different modifier.

That both happen to contain a colon character like that, doesn't mean one is composed of the other.

Compare e.g. how in Perl 6, `+<` (left bit-shift) is not a composition of `<` (smaller-than) and `+` (addition), but a completely separate operator. Or the same with `~~` and `~`, etc.
