### ISSUE TITLE
False-positives on “Perl 6 Types” page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1649]
| Name | Declarator | Source |
- [ ] [`example`](https://docs.perl6.org/type/%20example) | `enum` | ` `
- [x] [`auto-punning`](https://docs.perl6.org/type/auto-punning) | `role` | ` `

These should not be listed.

**Comment by W4anD0eR96** [comment]
also 

- [ ] Parameters | role

I think it's because of wrong =head3. let me try to fix it.
