### ISSUE TITLE
`eof` docs need to explain different behaviour for EOF on non-seekable handles.

### ISSUE THREAD

**Issue by raiph** [perl6/doc#1650]
See [this comment](https://stackoverflow.com/questions/47046761/does-perl-6s-eof-give-up-too-quickly#comment81158008_47084610) on the page of the SO question [Does Perl 6's eof give up too quickly?](https://stackoverflow.com/questions/47046761/does-perl-6s-eof-give-up-too-quickly/47084610) to get a quick view of what led to filing this issue.

It seems there's an ambiguity in the current wording in the doc pages for `eof` that will trip some folk up especially if they are used to how P5's `eof` behaves.

The suggestion is to s/exhausted the contents of the handle/read all of the currently available input from the handle/ in the `eof` doc for `IO::Handle.

We'd also presumably want to tweak the `eof` doc for `IO::CatHandle` too.

**Comment by zoffixznet** [comment]
The docs for eof look fine to me. EOF is given when the IO::Handle's input has been consumed (i.e. the decoder has been emptied out too, not just when the source handle has finished).

I added [my answer on SO](https://stackoverflow.com/a/47106348/2410502). I suspect bdfoy is just hitting a recently-fixed EOF bug.

**Comment by zoffixznet** [comment]
There was actually [*another* bug with EOF](https://github.com/MoarVM/MoarVM/commit/2f0672f74523c6ddfe8a216728bbbea8fc7760ce) that SO demonstrated. Fixed now too.

-----------

We could go into the nitty-gritty details about decoders (an implementation-detail) and buffers but IMO that will just make `eof` docs too verbose. It's also something I don't think that needs clarification. It'd be expected for EOF to be set only when the user exhausted the IO::Handle not the whatever file handle it's hooked up to, which the user shouldn't care about.

The current description is accurate and is concise, so I'm closing this ticket.

**Comment by zoffixznet** [comment]
https://irclog.perlgeek.de/perl6-dev/2017-11-04#i_15401308

Depending on whether anything can be improved, we could need to document different behaviour for non-seekable handles, where we rely on empty reads to set EOF flag.
