### ISSUE TITLE
｢anon｣ is only documented for variables (it also applies to subroutines, and maybe for something else too)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1655]
https://docs.perl6.org/syntax/anon

Some examples:
```perl6
say anon sub foo($y) {} # OUTPUT: «sub foo ($y) { #`(Sub|94868689830392) ... }␤»
```
```perl6
say anon sub foo($y) {}; foo 42 # Undeclared routine: foo
```

**Comment by W4anD0eR96** [comment]
```
say anon class foo {} # OUTPUT: «(foo)␤»
say anon role foo {} # OUTPUT: «(foo)»
my anon $a = 42; # Type 'anon' is not declared
```

so `anon` applies to `role` and `class` too. and does it really apply to variable? the example of it is actually about `anon sub`, not variable

**Comment by W4anD0eR96** [comment]
```
> my $internal = anon regex { stuff }
regex { stuff }
> "stuff" ~~ $internal 
｢stuff｣
```

applies to `regex`, `rule` and `token` too, maybe these are a bit like `sub`

**Comment by JJ** [comment]
@W4anD0eR96 they are actually special kind of subs...

**Comment by W4anD0eR96** [comment]
@JJ Aha, I had no idea about that then.

**Comment by JJ** [comment]
Still classes and other things have to be also documented. Feel free to add
something :-)
