### ISSUE TITLE
"<!|w>" disappears in ToC of Regexes

### ISSUE THREAD

**Issue by saito-ta** [perl6/doc#1662]
Greetings,
In the Table of Contents of [Regexes](https://docs.perl6.org/language/regexes), "<" and ">" appears in raw in the HTML, resulting that "<!|w>" disappears.
Thank you.

**Comment by W4anD0eR96** [comment]
We should escapeHTML in `htmlify.p6`

**Comment by W4anD0eR96** [comment]
maybe it's an issue of `Pod::To:HTML`

**Comment by W4anD0eR96** [comment]
https://github.com/perl6/Pod-To-HTML/blob/db0b4144ed69e7eb3b89882bd7838b254a934d4e/lib/Pod/To/HTML.pm#L216-L219

Here, code block `$html` doesn't escape

**Comment by W4anD0eR96** [comment]
It should be fixed via perl6/Pod-To-HTML#27

I will close this issue once confirmed.

**Comment by saito-ta** [comment]
Confirmed, thank you!
