### ISSUE TITLE
Try to integrate the docs of Grammar

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1663]
I will try to integrate the docs of Grammar a week later or so. Because Grammar is the most attractive of Perl 6 to me now, but its doc is a little lack. What's worse, they are scattered in several pages.

At first I want to involve both Regex and Grammar, but it's too hard to make it in one pass.

Below are the pods considered to be integrated:
`language/grammars` and `language/grammar_tutorial`, these two should be one.

Besides `type/Grammar`, `type/Match` and `type/Cursor` may be involved. Because #1646 supposed what to document below `language` or `type`, the current text will be rearranged. Also I hope it be an example when filing document.

Anyway, Grammar is one of the most awesome features supplied by rakudo/Perl 6. 

Any suggestion like what you want to be mentioned(such as `method make/made`) or how it's supposed to be organized is welcome. 
Any question/problem is welcome, too.

**Comment by nxadm** [comment]
Maybe @drforr's blogpost can come handy (the Action part needs to be more verbose, though):

http://theperlfisher.blogspot.be/2016/02/from-regular-expressions-to-grammars-pt.html
http://theperlfisher.blogspot.be/2016/02/from-regular-expressions-to-grammars-pt_13.html
http://theperlfisher.blogspot.be/2016/02/from-regular-expressions-to-grammars-pt_20.html
http://theperlfisher.blogspot.be/2016/02/from-regular-expressions-to-grammars-pt_28.html

**Comment by W4anD0eR96** [comment]
@nxadm I've glanced over those blogs. It starts with regex, but as mentioned above, I prefer to integrate only docs of grammar and assume those who read grammar docs at least know the basic of regex.

As you say, Actions are important. Users parse text by grammar almost want to perform some actions on the fly. The most common action is make/made, which we talk little about it.

Besides, there's many traps(trap-like feature?) in grammar, especially when it comes to `$/`.

Anyway, thanks for your reply!

**Comment by W4anD0eR96** [comment]
Recently be busy with school things. Close for I cannot accomplish it as promise.
