### ISSUE TITLE
Cool tricks that numify things (trap)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1664]
We have this section on the traps page https://docs.perl6.org/language/traps#Cool_tricks

And it talks about all kind of things that get stringified, but not so much about things that turn into a number of elements.

Here is an example:
```perl6
say 42 %% <2 4 5>;        # OUTPUT: «True␤»
say 42 %% <2 4 5>.any;    # OUTPUT: «any(True, False, False)␤»
say 42 %% <2 4 5>.all;    # OUTPUT: «all(True, False, False)␤»
say so 42 %% <2 4 5>.any; # OUTPUT: «True␤»
say so 42 %% <2 4 5>.all; # OUTPUT: «False␤»
```

Similar question [was asked today](https://irclog.perlgeek.de/perl6/2017-11-06#i_15412142) on #perl6.

**Comment by JJ** [comment]
Last two examples do not really turn into a number of anything, right?

**Comment by AlexDaniel** [comment]
@JJ No, let's start again.

Lists in numeric contexts turn into a number of elements in that list. So ``42 %% <2 4 5>`` is basically “is 42 divisible by 3 (number of elements in the list)”. However, anyone writing code like rarely means that, instead they mean “is 42 divisible by any number in that list” or “is 42 divisible by all numbers in that list”. So line 2 and 3 show how to do that, and 4 and 5 are pretty much identical, but with Boolified results.

**Comment by AlexDaniel** [comment]
And the trap here is that it compiles fine, and gives the “right” answer roughly with 50% chance.
