### ISSUE TITLE
Discuss -n command line flag in more detail

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1668]
For example:

> is there a way to set code to be executed after the loop?

All loop phasers work in -n, so ``LAST { … }`` should do the trick.

Anything else we should cover?

**Comment by AlexDaniel** [comment]
Update: `LAST` does not work. Is it a bug?

**Comment by zoffixznet** [comment]
> Is it a bug?

Yes: https://rt.perl.org/Ticket/Display.html?id=128398#ticket-history

**Comment by JJ** [comment]
There's no longer a discussion of command line arguments in the documentation, it's gone to Rakudo, so I'm closing this for the time being.
