### ISSUE TITLE
tell difference in interaction of Nil in default params and default values

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1669]
```
sub f($a is raw = 42){ my $b is default('answer'); $b = True; $b = $a; say $b }; f Nil;
# rakudo-moar d6cd0d2f5: OUTPUT: «answer␤»
```

**Comment by W4anD0eR96** [comment]
We have some of it:

https://docs.perl6.org/type/Nil#index-entry-Nil_assignment

**Comment by JJ** [comment]
`f Nil` does not activate the default 42 value. Passing nothing does:

    sub f($a is raw = 42 ){ my $b is default('answer'); $b =  $a; say $b }; f; # OUTPUT: «42␤»

`$a` will take a Nil value even if it's not declared as raw:

    sub f($a){ my $b is default('answer'); say $a; $b = $a; say $b }; f Nil; # OUTPUT: «Nil␤answer␤»

I'll see how this can be explained better, maybe in Signatures.
