### ISSUE TITLE
Difference between //, m//, and rx// in regex

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1675]
https://github.com/hankache/perl6intro/issues/135

What might be a good/quick way to explain the differences in the intro guide?

**Comment by raiph** [comment]
* `/ ... /` declares a regex. If it's used in sink context or on the right of `~~` it is also run.

* `rx/ ... /` is the same as `/ ... /` except that `rx` can use alternative delimiters, eg. `rx { ... }`.

* `m/ ... /` is the same as `rx/ ... /` except that it is *always* immediately run.

**Comment by W4anD0eR96** [comment]
```
[12:55] <raiph> wander: yes. some adverbs apply *inside* the *declarations* of regexes, others apply to *matches* see https://docs.perl6.org/language/regexes#Matching_adverbs
[12:58] <wander> how about the difference between 'rx:g' and 'm:g'
[13:03] <raiph> m is a match operation that can take match adverbs; it just happens to include a regex declaration in its syntax
[13:04] <raiph> rx is a regex declaration that can't take match adverbs; it just happens to sometimes be immediately run if in sink context or rhs of ~~
```

https://github.com/rakudo/rakudo/blob/fff43fd709cd0ed9693a85d06242f0fcd9f55ba3/src/Perl6/Grammar.nqp#L3814-L3833

https://github.com/rakudo/rakudo/blob/fff43fd709cd0ed9693a85d06242f0fcd9f55ba3/src/Perl6/Actions.nqp#L8056-L8088

**Comment by WildYorkies** [comment]
@raiph is your explanation in the docs? I couldn't find it by searching `m//` or `rx//`

I think I must have found it previously in a regex guide separate from the search bar.

**Comment by raiph** [comment]
@WildYorkies Searching for `rx` leads to the general language/regex page which explains this stuff starting at the section [Adverbs](https://docs.perl6.org/language/regexes#Adverbs).

**Comment by AlexDaniel** [comment]
I'm a bit late to the party, but FWIW here are some tickets:
* [RT#130363](https://rt.perl.org/Ticket/Display.html?id=130363) [open]: ^``[@LARRY] there's no match for Any aka /./ codegens differently from m/./``
* [RT#131925](https://rt.perl.org/Ticket/Display.html?id=131925) [open]: [BUG] [REGEX] ``Smartmatch against `m//` operator mishandles junctions``

**Comment by zoffixznet** [comment]
> / ... / declares a regex. If it's used in sink context or on the right of ~~ it is also run.

Also in Bool context.

**Comment by W4anD0eR96** [comment]
Close this via 6dec94afbb06d1f265c3375
https://docs.perl6.org/language/regexes#Lexical_Conventions
