### ISSUE TITLE
The "Syntax ?" link doesn't work

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1677]
+ Reproduction procedure
  + Search "?=".
  + Click "Syntax ?" from the candidates and go "https://docs.perl6.org/syntax/?" page.

**Comment by W4anD0eR96** [comment]
@coke plz look at `htmlify.p6`, right now when we deal with URI/URL, we use both `uri_escape` and the logic in `lib/Pod/Htmlify.pm6`. It ruins many link auto-generated(@AlexDaniel #561 ). We should try to rewrite these logic.


For this specific issue, it's because
```
# https://docs.perl6.org/js/search.js
{ category: "Syntax", value: "?", url: " /syntax/?" },
```
which should be `/syntax/%3f`

**Comment by JJ** [comment]
Also related to #1851 . Looks like all operators, or many of them, including ? might be wrong. Working on that now.
