### ISSUE TITLE
look-around assertion <?[]> is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1678]
5to6-nutshell mentions:
```
(?=[abc]) becomes <?[abc]>
```

However, I couldn't find any descriptions about this syntax.

**Comment by moritz** [comment]
For the record, this is a pretty general pattern that you can insert a `?` into a `<stuff>` call to make it a look-ahead assertion, or a `<!stuff>` to make it a negated look-ahead assertion. This works for `<subrule>`, `<[charclass]>` and so on.
