### ISSUE TITLE
Default setting in method now() in doc DateTime

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#168]
I've tried to modify it in the doc directory but somehow it doesn't get through. I have made branches to be on the save side though.

What I've seen is that the default of the named parameter timezone in method now() is set to *$TZ which should be $*TZ.

**Comment by zoffixznet** [comment]
I think you've made a typo: `$TZ` and `$TZ` both look the same to me (though italics are different...)

**Comment by MARTIMM** [comment]
Yeah, I see it now, the text is the same, I had those stars in it which got interpreted by the markdown. I didn't check that., sorry for that.
So ```*$TZ``` should become ```$*TZ```

**Comment by moritz** [comment]
Thanks!
