### ISSUE TITLE
Rakudo-specific "dd" operator used in examples

### ISSUE THREAD

**Issue by jstuder-gh** [perl6/doc#1680]
There are various instances in the document where dd is used to print output (like in Language/subscripts for instance, among others). Most of these examples do not indicate that dd is a Rakudo-specific operator.

I think that it would be preferable to use more standard functionality, like "say" in instances where the value can be stringified into something meaningful and can convey the same concepts.

**Comment by coke** [comment]
Working on a test to find these; Here's a list of all the files that contain a 'dd' in an example:

```
doc/Language/faq.pod6
doc/Language/functions.pod6
doc/Language/list.pod6
doc/Language/modules.pod6
doc/Language/operators.pod6
doc/Language/quoting.pod6
doc/Language/subscripts.pod6
doc/Language/syntax.pod6
doc/Language/typesystem.pod6
doc/Language/variables.pod6
doc/Programs/01-debugging.pod6
doc/Type/Any.pod6
doc/Type/Buf.pod6
doc/Type/Dateish.pod6
doc/Type/Hash.pod6
doc/Type/Iterator.pod6
doc/Type/Method.pod6
doc/Type/Mu.pod6
doc/Type/Pair.pod6
doc/Type/Signature.pod6
doc/Type/X/Temporal/InvalidFormat.pod6
```

If a sample is explicitly about dd, add an ```:ok-test<dd>``` to indicate it, and otherwise, rework the sample to use say. Most examples will be fine with just ```say```ing the value and changing the expected output slightly.

**Comment by jstuder-gh** [comment]
Great! I can assist with the reworking of the examples sometime tonight (EST).

**Comment by coke** [comment]
Example added. Updated faq, but none of the others. You can test that things are ok with the following command:

```
TEST_FILES="doc/Language/faq.pod6 doc/Language/functions.pod6 doc/Language/list.pod6 doc/Language/modules.pod6 doc/Language/operators.pod6 doc/Language/quoting.pod6 doc/Language/subscripts.pod6 doc/Language/syntax.pod6 doc/Language/typesystem.pod6 doc/Language/variables.pod6 doc/Programs/01-debugging.pod6 doc/Type/Any.pod6 doc/Type/Buf.pod6 doc/Type/Dateish.pod6 doc/Type/Hash.pod6 doc/Type/Iterator.pod6 doc/Type/Method.pod6 doc/Type/Mu.pod6 doc/Type/Pair.pod6 doc/Type/Signature.pod6 doc/Type/X/Temporal/InvalidFormat.pod6" xt/examples-compilation.t
```

**Comment by coke** [comment]
whoops: see 738b5c82 & c6b51048 also - forgot to put a word before the #ticket syntax, so it was a comment.

**Comment by jstuder-gh** [comment]
I modified many examples to replace "dd" instances. I believe they are all taken care of. Safe to call the ticket complete?

**Comment by coke** [comment]
Thanks!
