### ISSUE TITLE
Remove or migrate Type/snapper

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1684]
https://docs.perl6.org/type/snapper

This is not a Type.

@lizmat @zoffixznet

**Comment by lizmat** [comment]
I agree.  Do you have a suggestion where to put this then?

**Comment by W4anD0eR96** [comment]
Language/Telemetry is an option.

**Comment by W4anD0eR96** [comment]
0a93d3f fixes this issue, isn't it?
