### ISSUE TITLE
show that is default works on @list and %hash

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1687]
```
my %b is default(Nil);
my $c := %b<not-there>;
my $a is default(Int) = $c;
say $a.new;
# OUTPUT: «0␤»
```

**Comment by gfldex** [comment]
add trait to `Hash` and `Array`

**Comment by moritz** [comment]
Do the traits even work on arrays and hashes?

    $ perl6 -e 'my %x is default({a => 1}); say %x.perl'
    {}
    $ perl6 -e 'my @x is default([2, 3]); say @x.perl'
    []

doesn't look like it to me.

**Comment by AlexDaniel** [comment]
> Do the traits even work on arrays and hashes?

Yes, they just do something different. e.g. ``my @x is default(42); say @x[10]``.

Some discussion: https://irclog.perlgeek.de/perl6/2018-01-05#i_15656247
