### ISSUE TITLE
nextcallee and ilk aren't indexed as routines

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1689]
The nextcallee, samewith, nextwith, nextsame, callwith, callsame routines are routines, but they don't show up when using the `/routines/` endpoing, e.g.: https://docs.perl6.org/routine/callwith

Instead links to some of them are in the `/syntax/` and others are references in `/language/functions/`

Having https://docs.perl6.org/routine/callwith work properly makes it easier for external tools (like [perl6.party blog](https://github.com/zoffixznet/perl6.party/blob/94b3ac1a1caed4b4e8007cacc9081f6b4e15a4a5/lib/Perl5/Party/Posts.pm#L64-L72)) that auto-generate documentation links for routines and types.

**Comment by W4anD0eR96** [comment]
To implement this, one can follow these steps:

1. Rewrite `/language/functions/`'s section `Re-dispatching`, organize its material as:
```
=head2 routine nextsame
 # ...
=head2 routine nextwith
 # ...
```
By doing this our `htmlify.p6` can detect them and generate `/routine/*` links.

2. `samewith` is misdocumented in `/language/control_flow`, so move it under Re-dispatch.

I cannot do that because I'm not so familiar with Re-dispatch now, maybe doc it wrong :-(

**Comment by zoffixznet** [comment]
> Rewrite /language/functions/'s section

👍 [Currently](https://docs.perl6.org/language/functions#index-entry-nextsame-nextsame) it's hard to see the details for the routine you want as the whole bunch of them is discussed in that prose.

>  I'm not so familiar with Re-dispatch

FWIW, all of these are fairly well described on https://rakudo.party/post/Perl6-But-Heres-My-Dispatch-So-Callwith-Maybe

**Comment by W4anD0eR96** [comment]
@zoffixznet I've read the post. That helps a lot.

Still a problem remains -- how to decide who is the next candidate? I have some examples but prefer a full strategy of it(as we explain LTM).

```
multi f(Int \a) { } #1
multi f(Any \a) { } #2
# 2 is the next of 1

multi f(Int \a) { } #1
multi f() { } #2
# 2 isn't the next of 1
```

and more examples on class
```
class A {
  multi method f(Int \a) { say 'a.f'; }
}

class B is A {
  multi method f(4) { say 'b.f1'; nextsame; }
  multi method f(Int \a) { say 'b.f2';  nextsame; }
  multi method f(Cool \a) { say 'b.f3';  nextsame; }
 # multi method f(Int \a where * > 2) { say 'b.f3';  nextsame; }
}

B.new.f: 4;
```

**Comment by W4anD0eR96** [comment]
Now https://docs.perl6.org/routine/callwith is reachable.

Thanks to @zoffixznet . Your post helps a lot.

**Comment by coke** [comment]
From 42344f8:

+C<samewith> calls current candidate again with arguments provided by users and
+and returns return value of the new instance of current candidate.

Note the duplicate "and"

**Comment by W4anD0eR96** [comment]
Thank you @coke .  It's better to leave a comment in that commit rather than here, isn't it?

**Comment by W4anD0eR96** [comment]
@coke can we close this issue now, or something remains?

**Comment by coke** [comment]
I put it here because the commit was done as part of this ticket. If the typo is fixed, yes, please reclose.

**Comment by zoffixznet** [comment]
Fixed in https://github.com/perl6/doc/commit/a381d7794fa4b7bc95437bb4c33e9600dadf8f12
