### ISSUE TITLE
Str method of Class Code gives other result than doc says

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#169]
Perhaps it is only in rakudo but...

```
> sub aa ($x) {return 2 * $x};
> my $b = &aa;
> say ~(&$b)
Sub object coerced to string (please use .gist or .perl to do that)  in block <unit> at <unknown file>:1
aa
```
The following code of Str can be found in the rakudo source code Code.pm where it clearly outputs a warning before returning the name.
```
    multi method Str(Code:D:) {
        warn( self.WHAT.perl ~ " object coerced to string (please use .gist or .perl to do that)"); self.name
    }
```
while the documentation states that it returns the name of the code object while the warning is not mentioned. The above code shows also that the method name() would do that.
```
> say $b.name;
aa
```
I only don't know where that method comes from. Its not defined in Code.pm nor Callable.pm.

Anyways, maybe an extra remark about the warning and a pointer to the name() method would do.

**Comment by timo** [comment]
For "deeply" built-in things that are required to work very early on in the setting, you can look into BOOTSTRAP.nqp to find definitions. There's the definition of method name in there, too.

**Comment by AlexDaniel** [comment]
So it seems like the docs should just say “use .name instead”?

**Comment by gfldex** [comment]
I agree with Rakudo that a string representation of a Code obj would look like assembly.

fixed with https://github.com/perl6/doc/commit/b351406086
