### ISSUE TITLE
Should LABELs refer to 'loop'?

### ISSUE THREAD

**Issue by CurtTilmes** [perl6/doc#1691]
https://docs.perl6.org/language/control#LABELs says "while, until, and for loops can all take a label".  

Should that also refer to 'loop' itself?

**Comment by W4anD0eR96** [comment]
sure `loop` can have a LABEL.

another problem is, it should also mention that our LABEL is unlike that in other language, see the example below:
```
OUTAHERE:
 say 42;
loop  {
    for 1,2,3 -> $n {
        last OUTAHERE if $n == 2;
    }
}

# labeled last without loop construct
```
