### ISSUE TITLE
Document aliases and illustrate with how to create :0th :1st :2nd :3rd :4th named thingies

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1696]
> [Is there a shorthand way for accepting <st nd rd th> numeric options and merging them so you can do :0th :1st :2nd :3rd fun?](https://irclog.perlgeek.de/perl6/2017-12-02#i_15523500)

```perl6
sub ordinated( :st(:nd(:rd(:th($num))))=-1 ) {
    say "I got $num."
}
ordinated(:0th); # OUTPUT: «I got 0.␤»
ordinated(:1st); # OUTPUT: «I got 1.␤»
ordinated(:2nd); # OUTPUT: «I got 2.␤»
ordinated(:3rd); # OUTPUT: «I got 3.␤»
ordinated(:4th); # OUTPUT: «I got 4.␤»
ordinated();     # OUTPUT: «I got -1.␤»
```

**Comment by treyharris** [comment]
I'll take this and increase its scope a bit since there appears to be no documentation of aliases at all, and this is a good example to illustrate.

**Comment by AlexDaniel** [comment]
Also:

- [ ] https://docs.perl6.org/language/functions#sub_MAIN should probably link to that newly written section
- [ ] And it should be searchable by “alias”.

**Comment by treyharris** [comment]
Note that the nearest thing to documenting this now appears to be [language/functions#sub_MAIN](url)

**Comment by JJ** [comment]
* Argument aliases [are documented now](https://docs.perl6.org/type/Signature#index-entry-aliases)
* That above is just a hack, which besides breaks if you simply use 1th. We can additionally document nested aliases.
