### ISSUE TITLE
cannot rebuild html

### ISSUE THREAD

**Issue by fluca1978** [perl6/doc#1703]
I'm trying to work on the html documentation locally, but I'm encountering errors when rebuild the documentation.

Head of documentation is 90659494967cc7ac3b312c1cf327cce8facbc272.
node version is v9.2.0 (using nvm as of discussion <https://github.com/perl6/doc/issues/1701>)

The first build using `make html` was fine.
After that, if I try to do another `make html` again I'm getting the following trace:

```
% make html
...
processed ./doc/Type/utf8.pod6 (cached)
found duplicate index entry is (inheritance) at #i45 #i670
found duplicate index entry :{} at #i835 #i837
found duplicate index entry compunit at #i253 #i254 #i255
found duplicate index entry increment operator at #i342 #i346
found duplicate index entry control flow at #i53 #i54 #i55 #i56 #i58 #i60 #i61 #i65 #i68 #i69 #i71 #i74 #i75 #i76 #i77 #i78 #i79 #i80 #i81
found duplicate index entry ++ at #i341 #i345
found duplicate index entry decrement operator at #i344 #i347
found duplicate index entry prefix &amp; at #i113 #i852
found duplicate index entry declarator regex at #i240 #i574
found duplicate index entry $*USAGE at #i130 #i819
found duplicate index entry invocant at #i39 #i479
ATOMDIR="./highlights/atom-language-perl6";  \
if [ -d "$ATOMDIR" ]; then (cd "$ATOMDIR" && git pull); \
else git clone https://github.com/perl6/atom-language-perl6 "$ATOMDIR"; \
fi; cd highlights; npm install .
Already up-to-date.
npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luca/.npm/_logs/2017-12-06T12_43_28_133Z-debug.log
Makefile:19: recipe for target 'init-highlights' failed
make: *** [init-highlights] Error 1

```

The npm debug log is attached.

[2017-12-06T12_43_28_133Z-debug.log](https://github.com/perl6/doc/files/1535165/2017-12-06T12_43_28_133Z-debug.log)

**Comment by fluca1978** [comment]
It seems I can build html via `make html` if I remove the `highlights/node_modules` content.
However, as far as I understand, this rebuilds all the node modules from scratch, and makes the whole process a lot longer.

**Comment by fluca1978** [comment]
Just for the record: I cannot build even after a `make clean`, same error.
I've tried also with another head a381d7794fa4b7bc95437bb4c33e9600dadf8f12 but it does not change at all.
Is my setup wrong or am I doing something worng?

**Comment by JJ** [comment]
I'm not sure... Off the top of my head I would say it's a node version error. What version are you using?

**Comment by fluca1978** [comment]
I cannot reproduce it anymore, I close this issue.
