### ISSUE TITLE
MONKEY pragma

### ISSUE THREAD

**Issue by mj41** [perl6/doc#1707]
[EVAL docs](https://docs.perl6.org/routine/EVAL) mentions "MONKEY Pragma":

`use MONKEY;  # shortcut that turns on all MONKEY pragmas `

For "pragma" is can find docs [Pragmas](https://docs.perl6.org/language/pragmas) using search. Search find nothing for "MONKEY" probably because of #1488 (Linking to pragmas). 

But 'use MONKEY;' is not described on "Pragmas" page.

**Comment by JJ** [comment]
MONKEY pragmas are not documented. @tbrowder created #808 and the next ones a long time ago. Maybe it should be time to have a go at them.
