### ISSUE TITLE
Proc.status not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1710]
Haven't checked if it's specced; especially [the candidate](https://github.com/rakudo/rakudo/blob/062c27f343a2ef4499a859734f64ac623b39632e/src/core/Proc.pm#L189-L192) that sets new status.

```
    proto method status(|) {*}
    multi method status($new_status) {
        $!exitcode = $new_status +> 8;
        $!signal   = $new_status +& 0xFF;
    }
    multi method status(Proc:D:)  {
        self!wait-for-finish;
        ($!exitcode +< 8) +| $!signal
}
```

**Comment by moritz** [comment]
It seems to be not really part of the public API. The proper API is the `exitcode` and the `signal` accessor.

I'll open a rakudo issue to make `status` a private method instead.
