### ISSUE TITLE
Should the @ be the "list context operator" in Operators?

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1711]
[Symbolic Unary Precedence](https://docs.perl6.org/language/operators#Symbolic_Unary_Precedence) has the prefix operators `+`, `~`, and others but not `@` (as in `@$listy-thing`).

**Comment by W4anD0eR96** [comment]
Not really, on the one hand

```
> @(Set(1,2,3)).^name
List
> @([1,2,3]).^name
Array
```

on the other hand, there's no token `prefix:sym<@>` in rakudo/rakudo/src/Perl6/Grammar.nqp, `@`, as `$`, `%` and `&` are sigils

https://github.com/rakudo/rakudo/blob/eaf609edb2dfe35688d8a52ebbd5744f0105ac01/src/Perl6/Grammar.nqp#L5094-L5105

**Comment by smls** [comment]
Yeah, it's special syntax, not an operator.

**Comment by jnthn** [comment]
It's a contextualizer. I note that if one types `$` into the search box, then `$ (item contextualizer)` is one of the suggested results. That doesn't currently happen if typing `@` there, but it probably should.

**Comment by W4anD0eR96** [comment]
@jnthn `@` is Positional contextualizer?

**Comment by zoffixznet** [comment]
> @ is Positional contextualizer?

The [S03 speculation](http://design.perl6.org/S03.html) calls it `The list contextualizer`

**Comment by cfa** [comment]
The confusion there is that "list contextualizer" in S03 seems to also refer to the `list` routine, which as currently [implemented](https://github.com/rakudo/rakudo/blob/master/src/core/List.pm6#L1553-L1554) does return a `List`, versus the contextualiser and `.list` method which only need to satisfy the role (also illustrated in @W4anD0eR96's examples above):

    list({:a, :b}).^name  # => List
    @(   {:a, :b}).^name  # => Seq

We could document the `list` routine alongside mention of the contextualiser (with an index entry), though I worry that the different return types might confuse users. (Similarly, the perceivable difference between `.list` and `list` might cause confusion.)

Thoughts?

**Comment by cfa** [comment]
Ah, @zoffixznet [clarified](https://irclog.perlgeek.de/perl6/2018-03-13#i_15917138) that the `list` sub behaviour is known to be inconsistent; rakudo/rakudo#1344, blocked by rakudo/rakudo#1355.

**Comment by JJ** [comment]
I've finally added it under .list https://docs.perl6.org/type/Any#index-entry-%40_list_contextualizer and used the examples above. Would that be OK?
