### ISSUE TITLE
add infix:<∘> to Operators

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1712]
For some strange reasons it's only in Callable.

**Comment by W4anD0eR96** [comment]
what is its precedence?

**Comment by AlexDaniel** [comment]
[Same as concatenation (~)](https://github.com/rakudo/rakudo/blob/nom/src/Perl6/Grammar.nqp#L4398-L4399).

**Comment by W4anD0eR96** [comment]
@gfldex Here is a fix db05b11515 . if it satisfies the issue, we can close this one :-)

**Comment by W4anD0eR96** [comment]
close via  db05b11
