### ISSUE TITLE
Operator Precedence table is missing ops

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1713]
I'm failing to find `∘` op or any of the [set ops](https://docs.perl6.org/language/setbagmix#Set/Bag_Operators) on https://docs.perl6.org/language/operators#Operator_Precedence

**Comment by W4anD0eR96** [comment]
`∘` is level "Concatenation"

most(all?) of set ops are level "Junctive or" or "Chaining infix".

see the below

https://github.com/rakudo/rakudo/blob/3405001da07b7062a19fd6343bab6112128319f3/src/Perl6/Grammar.nqp#L4424-L4492

Then, the table's third col is with title "Examples", should we document all ops?

Last, `∘` is under the head `=head1 Concatenation`, which implies its precedence.

I prefer mention set ops' precedence in https://docs.perl6.org/language/setbagmix#Set/Bag_Operators

**Comment by zoffixznet** [comment]
Ok. Thanks.

**Comment by W4anD0eR96** [comment]
FWIW, b56885bfe7 ("Improve documents on set ops")
