### ISSUE TITLE
Traps candidate? Sinkage of maps

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1718]
Just mapping stuff in sink context may make people think it's perfectly fine to do it all the time:

```
m: <foo bar ber>.map: *.say
rakudo-moar 334b87226: OUTPUT: «foo␤bar␤ber␤»
```

However, if you nest another `Seq` inside (e.g. another map), *that* Seq just becomes an item inside the first Seq and so isn't sunk and the map isn't evaluated:

```
m: <foo bar ber>.map: *.say
rakudo-moar 334b87226: OUTPUT: «foo␤bar␤ber␤»
m: <foo bar ber>.map: *.comb.map: *.say
rakudo-moar 334b87226: OUTPUT: «»
```

**Comment by AlexDaniel** [comment]
I think https://github.com/perl6/doc/commit/adc5f09c12053f1e238a0ca522304c8a854d663a doesn't explain *why* it happens.

**Comment by JJ** [comment]
In this case, I'm not 100% it's an effect of sinkage. In fact, `say` returns `True`. You would be sinking a list of Trues in the first case, and the same would apply to the second case. If you take a single element of the innermost map and sink it, it will still output something. Expected result here would be printing of the letters of every element, and a list of lists of `Trues` that is sunk.

**Comment by AlexDaniel** [comment]
The answers on StackOverflow are nice, the current documentation is not. Reopening :)

**Comment by JJ** [comment]
That's precisely why I've asked that and linked the question...
