### ISSUE TITLE
nodemap, deepmap, duckmap omit some details about Associative's handling

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1720]
The `nodemap`, `deepmap`, `duckmap` have special handling of `Associative` types, which doesn't appear to be documented.

It's a bit convoluted, but makes sense if thought as a handler of `».` hyper method call (nodemap for nodal methods and deepmap for non-nodal).

For example, the Callable is called on the *values* of Pairs if those pairs are in a Hash:
```
$ perl6 -e 'm: dd deepmap *.Str.flip, %(:4b, :60c)'
Hash % = {:b("4"), :c("06")}

$ perl6 -e 'm: dd deepmap *.Str.flip, [%(:4b, :60c),]'
[{:b("4"), :c("06")},]
```

But is called on the Pairs themselves when those are in some other Iterable:

```
$ perl6 -e 'm: dd deepmap *.Str.flip, [:4b, :60c]'
["4\tb", "06\tc"]
```

I'm not sure how to word this succinctly. Perhaps something about handling `Associative + Iterable` (e.g. Hashes) differently than non-iterable `Associative` (e.g. Pair).

------

One striking relevance of this behaviour (that might be good to mention somewhere in the docs) is in this construct, which seems to be a popular way to deep-decont stuff:

```
my @a = %(:42foo, :70bar), <a b c>; say gather { @a».take }'
(70 42 a b c)
```

The way it blows up Hashes might not be the result the user's expecting.

(N.B.: this came up when I [tried to make that construct](https://irclog.perlgeek.de/perl6-dev/2017-12-20#i_15602962) not break Pairs, but that was blocked by 6.c spec and also I realized current behaviour is more desirable in other situations)

**Comment by JJ** [comment]
What I see here is that the surprising behavior lays only in working with values in the case of `Associative`. It's what you should expect if it's a list of whatever, including Iterables.
