### ISSUE TITLE
Enums in pair notation trap (Foo => 42)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1721]
There may be a dup of this ticket but I can't find it.

See https://irclog.perlgeek.de/perl6/2017-12-21#i_15608707.

Basically “Foo => 42” will create a pair with “Foo” string as a key, even if you have a same-named enum defined earlier.

**Comment by fluca1978** [comment]
Seems to me it will override the enum only when the :{} operator is used to force non-string keys in hashes. The following piece of code does what you want:

```
enum sides <Back Front>;
my %a := { Back=>10, Front=>20 };
say %a.perl;
say %a{Back};
```

I'm not sure if this should be managed as a general trap or a note in the :{} operator section <https://docs.perl6.org/type/Hash#index-entry-%3A%7B%7D>

**Comment by AlexDaniel** [comment]
It's a general trap of pair notation.

**Comment by b2gills** [comment]
Note that if you declared the type of the keys with `%a{Sides}` then it would error out rather than do the wrong thing.

    enum Sides <Back Front>;

    # my %a{Sides} := { Back=>10, Front=>20 }; # error
    # my %a{Sides} := :{ Back=>10, Front=>20 }; # error
    # my %a{Sides} := :{ (Back)=>10, (Front)=>20 }; # error
    # my %a{Sides} = Back=>10, Front=>20; # error

    my %a{Sides} = (Back)=>10, (Front)=>20; # no error
    say %a.perl;
    say %a{Back};

**Comment by raiph** [comment]
This is probably obvious but anyway:

Another option for stopping `=>` autoquoting its lhs is to write `::Back` etc. (I slightly prefer this to `(Back)` etc.)

Another option is to use list notation: `enum Sides <Back Front> ; my %a = Back, 10, Front, 20;`.
