### ISSUE TITLE
Many examples of exception handling use STDOUT but it seems better to use STDERR

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1722]
For example, in this page: https://docs.perl6.org/language/exceptions

Current example for "Catching exceptions" is:
```
die X::IO::DoesNotExist.new(:path("foo/bar"), :trying("zombie copy"));
 
CATCH {
    when X::IO { say "some kind of IO exception was caught!" }
}
 
# RESULT: «some kind of IO exception was caught!» 
```

But I think the following is better than the former one:
```
die X::IO::DoesNotExist.new(:path("foo/bar"), :trying("zombie copy"));
 
CATCH {
    when X::IO { $*ERR.say: "some kind of IO exception was caught!" }
}
 
# RESULT: «some kind of IO exception was caught!» 
```

Are there any reasons to use STDOUT instead of STDERR?

**Comment by manchicken** [comment]
I think it may make more sense to have this say one and then elaborate to the other. 

I think an important aspect of good reference documentation is the ability to quickly understand the point being made by looking at the example. I think the simple `say` example accomplished this.

I also think a worthy goal of reference documentation is to promote best practices, so I think it would be best to start with the simple `say` but then to expand with an example using `$*ERR.say`. 

Just my thoughts. 

~ Michael D. Stemle, Jr.
