### ISSUE TITLE
Possible trap with pairs (my $p = a => $foo)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1728]
[This](https://irclog.perlgeek.de/perl6/2018-01-10#i_15676620) and [this](https://irclog.perlgeek.de/perl6/2018-01-11#i_15676648).

TL;DR:
```perl6
my $foo; 
my $p = a => $foo;
$foo = 99;
say $p # OUTPUT: «a => 99␤»
```

**Comment by AlexDaniel** [comment]
Cool, although I think it would be better if it was listed on the traps page with a link to that section.

**Comment by fluca1978** [comment]
I've added the section.
I do believe this should be explained in the Pair class introduction, not in the freeze method (it is too far to be read at glance). Reopen if this has to be improved again.
