### ISSUE TITLE
v (Version) is not indexed

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1732]
v is a syntax sugar of Version.new:
```
$ perl6 -e 'say v1.0.1 ~~ Version.new("1.0.1")'
True
```

Version:
https://docs.perl6.org/type/Version

**Comment by fluca1978** [comment]
It should be indexed now, at least it appears on my local system.
I'm not really sure the label 'v (version)' is the rightmost one, but simply 'v' seemed to me a little too less.
Reopen if that's not ok.

**Comment by JJ** [comment]
https://docs.perl6.org/type/Version#index-entry-v_%28version%29 is what is
returned here. Is that what you intended?

**Comment by fluca1978** [comment]
@JJ `v (version)` is what I added with commit  9dff74f.
I placed it in the introduction section, where the `v` exampels are shown.
