### ISSUE TITLE
minmax infix op not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1734]
> <jkramer> Isn't the minmax operator documented anywhere? It's mentioned on https://docs.perl6.org/language/operators in the precendence table, but with no explanation

> \<AlexDaniel\> m: say 5 minmax 8 minmax 3
> \<camelia\> rakudo-moar 354a38484: OUTPUT: «3..8␤»
> \<AlexDaniel\> cool

It's [documented as a method](https://docs.perl6.org/routine/minmax), and nowhere it says that there's a sub form and an infix form.

**Comment by JJ** [comment]
Any suggestion? Add an entry there?

**Comment by fluca1978** [comment]
Since it's already documented in Any, I suspect it could be documented in the operators likely `min`<https://docs.perl6.org/routine/min#language_documentation_Operators>.

If that's ok, I can work on it today or tomorrow (please assign to me in such case).

**Comment by JJ** [comment]
Done. If you need help, just let me know.
