### ISSUE TITLE
Problem with single-page perl6.xhtml

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1737]
When generated with `make html`, the page `perl6.xhtml' contains the following error:

    error on line 14156 at column 307: xmlParseEntityRef: no name

This is right behind 
    
    These infixes can be written using the UTF-8 character that represents the function (like ∈, or ∪), or they can be written with an equivalent ASCII version (like (elem) or

According to StackOverflow, it's probably an "&" somewhere. I'll try and see how it can be fixed.

**Comment by JJ** [comment]
That seems to be the problem, translated from `L<(E<VERTICAL LINE>)|/routine/(|)>)`. Since it's an example I'll see how another example can make sense (or simply eliminate this one). If anyone else has a better option, or a better way to fix the underlying bug, just tell me how. 

![screenshot from 2018-01-21 10 48 53](https://user-images.githubusercontent.com/500/35192786-ba0bea9c-fe98-11e7-8e57-dd49b04afd57.png)

**Comment by W4anD0eR96** [comment]
Links end with `.pod6` seem like useless, for there are no such hooks.

**Comment by JJ** [comment]
Right... I really have no idea what to do with that. It's a separate issue, I guess, though.
