### ISSUE TITLE
Glitch with search and `...` op

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1743]
The docs for [`...` operator](https://docs.perl6.org/language/operators#index-entry-%E2%80%A6_operators) have this index markers listed:

```perl-6
X<|...,operators>X<|...^,operators>X<|…,operators>X<|…^,operators>
```

However, only the Unicode versions are searchable. If you type `...` or `...^` no results turn up.

(P.S.: `..` doesn't show up either; dunno if it should, based on title of [the section](https://docs.perl6.org/language/operators#infix_..) alone and no index markers)

**Comment by JJ** [comment]
Would you say that's a documentation problem or a problem of the search code? In the second case, maybe we could create a test for it?

**Comment by W4anD0eR96** [comment]
search code, for more #1677
