### ISSUE TITLE
Add Perl 6 to Wikipedia's multi-paradigm programming languages list

### ISSUE THREAD

**Issue by Tyil** [perl6/doc#1744]
Wikipedia has a [Comparison of multi-paradigm programming languages](https://en.wikipedia.org/wiki/Comparison_of_multi-paradigm_programming_languages#Language_overview), which currently lacks a Perl 6. This should be rectified, but to do it properly I'll need to know which paradigms are supported and know which pages (preferably from the docs itself) to cite.

**Comment by AlexDaniel** [comment]
What would be the best page to document this? https://docs.perl6.org/language/faq?

**Comment by AlexDaniel** [comment]
Or a new page linked from https://docs.perl6.org/language.html?

**Comment by JJ** [comment]
Pretty much all of them. I'll check it out.

**Comment by JJ** [comment]
Let's try and add a reference here. Some of the things are not so easy.
- [ ] Concurrent
- [ ] Constraints
- [ ] Dataflow
- [ ] Declarative
- [ ] Distributed
- [ ] Functional
- [ ] Metaprogramming
- [ ] Generic
- [ ] Imperative
- [ ] Logic
- [ ] Reflection
- [ ] OO
- [ ] Pipelines
- [ ] Visual
- [ ] Rule-based
- [ ] Other paradigms

**Comment by JJ** [comment]
I'm going at this from the bottom. Rule-based is not, visual is not. Pipelines... [This is the document for C++](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2013/n3534.html#Proposal). Seems to me it's something like the Feed operator?

**Comment by JJ** [comment]
I would say that's pretty much it.

**Comment by JJ** [comment]
Anyone else wanting to help here? Should I assign it to myself?

**Comment by AlexDaniel** [comment]
Feel free to.

**Comment by JJ** [comment]
Done. https://en.wikipedia.org/wiki/Comparison_of_multi-paradigm_programming_languages#Language_overview
Thanks everyone!

**Comment by AlexDaniel** [comment]
1. If it is referencing Cro module, then it should be marked as “Library” (according to other entries in the table). That said, I don't understand that column altogether. It should be a No I think…
2. There's a column called `other`, and for Julia it mentions “Multiple dispatch”. Seems like something similar should be appropriate for Perl 6 also (also what about “reactive” and “native shaped arrays”?)

**Comment by AlexDaniel** [comment]
But generally it's good I think!

**Comment by AlexDaniel** [comment]
“Lazy lists”? :)

**Comment by AlexDaniel** [comment]
Grammars, Junctions, Gradual Typing… none of these are paradigms, but why do others list “Array (multi-dimensional)” and “optionally lazy”?

**Comment by JJ** [comment]
You are absolutely right. Thanks for the feedback. I'll try to change that,
but that will be tomorrow :-)

**Comment by AlexDaniel** [comment]
To be completely honest, I think that the *whole page* should be nominated for deletion. Looking deeper at the content, it's very low-quality, cluttered and unsourced. Also, the page is completely useless because everyone is trying to stretch the definition of “paradigm”. But if we're adding perl 6, I think we should be very strict about our own contributions.

**Comment by JJ** [comment]
Whoa, whoa, whoa! Having suffered deletionist librarians in the Spanish Wikipedia, I don't wish the deletion of even a single iota of knowledge in the Wikipedia. It's got its merit, but you are right about "stretching the definition of paradigm"... I would rather go for deleting that column, but anyway I would discuss it on the discussion page. It will enrich everyone involved.

**Comment by JJ** [comment]
OK, addressed @AlexDaniel 's concerns. And fixed Go row while I was at it, which had a format problem.
Closing at 1, closing at 2, closed :-)

**Comment by wayland** [comment]
I couldn't find the "where" and "but" keywords, but type constraints are not constraint-based programming ( https://en.wikipedia.org/wiki/Constraint_programming ).  I've linked a library instead.

**Comment by wayland** [comment]
When I was a student, there was a Distributed Computing research group in the computer science department.  Their operating system didn't run on a single computer, it ran across multiple computers.  It was effectively an operating system for clusters, as opposed to an operating system for a single computer.  A key part of their setup was that if a node was heavily loaded, it could bundle up a whole process, ship it to a different node, and it would just continue running there as though nothing had happened.  

Having said that, that was a distributed operating system, not a distributed programming paradigm.  But I'm not sure there *is* a distributed programming paradigm (as opposed to distributed computing, which is a thing).  

HTH,

**Comment by raiph** [comment]
Hi @wayland,

I'm confused by your comments. I looked at the Wikipedia page and saw no mention of Raku or Perl. I searched the Raku doc, and while I found lots of matches for "constraint", none seemed untoward. What am I missing?
