### ISSUE TITLE
Document how to use ｢run｣ without having to separate *all* of the arguments (also a trap?)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1745]
There was an [attempt](https://github.com/perl6/doc/commit/38ed8fbc7f1005db4cea683bb8dad3324da196ac) to recommend ``«»`` which was then [reverted](https://github.com/perl6/doc/commit/a8b908539d9999f0cc17dbc8a57da83909e6e013). This resulted in a [discussion](https://irclog.perlgeek.de/perl6/2018-01-23#i_15728317) in which a better alternative was suggested (``< >``).

I think the docs should talk about that too.

So I'm suggesting this:
```perl6
run ‘rm’, ‘--’, $file; # ← we currently show something like this
run <rm -->, $file;    # ← this should be recommended as an alternative
run «rm -- "$file"»;   # ← this should be discussed, and likely discouraged (with examples on why it is potentially dangerous)
```

**Comment by W4anD0eR96** [comment]
👍  on this, I used to have a hard time with `run` (`shell` always worked, in addition)

**Comment by AlexDaniel** [comment]
FWIW it does not hurt to look at how other languages do things: https://docs.julialang.org/en/release-0.4/manual/running-external-programs/

**Comment by JJ** [comment]
@AlexDaniel I'm OK with your suggestion. Please go ahead and change the docs.
