### ISSUE TITLE
Factor out common t/ xt/ code

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1749]
1. This basically got me started on this issue. Checking the [style guide](https://github.com/perl6/doc/blob/master/STYLEGUIDE.md), I see that some of them have been turned into tests (tabs, for instance), some are more difficult to do so (give each subroutine a self-contained introduction), and some might be, with some work, turned into one (avoid absolute URLs to the documentation). I wonder if we should do some work on the latter, turning checkable style guidelines into tests, and do something about the former, like trying to reformulate them so that they can be checked automatically in the tests.
2. Then I started to look at tests, and they seem to have some code in common. For instance, [pod-valid.t](https://github.com/perl6/doc/blob/master/t/tabs.t) and [tabs.t](https://github.com/perl6/doc/blob/master/t/tabs.t) both start with the same snippet

~~~
if @*ARGS {
    @files = @*ARGS;
} else {
    if %*ENV<TEST_FILES> {
        @files = %*ENV<TEST_FILES>.split(' ').grep(*.IO.e);
    } else {
        @files = qx<git ls-files>.lines;
    }
}
~~~

Although after that they filter files, first one selecting just those ending in `.pod6` and the other doing a more complicated thing which I would say amounts to the same. So the issue is: should we factor out this code to a common module? This would also make writing new style tests easier, by giving the test a ready-made list of files to check.

**Comment by JJ** [comment]
I see this kind of code is repeated also in some of the `xt` tests, such as this one https://github.com/perl6/doc/blob/master/xt/trailing-whitespace.t

**Comment by coke** [comment]
Yes that would be great if we could re-factor the similar code out into a helper module.

**Comment by coke** [comment]
Style tag is intended for stylistic issues regarding the documentation; changed the label to 'xt', which is a little closer.
