### ISSUE TITLE
Any trivial regex match will reset $/, that's OK but seems to be a trap?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1752]
I don't know if anybody else gets this issue often, but I definitely do. This is not exactly a language trap, but just a common mistake.

Here's the code:

```perl6
my $x = ‘test’;
my $y = ‘hello world’;
say so $y ~~ /^ $<start>=[\w+]  \s+ $<end>=[\w+] $/; # ← some complex regex capturing stuff
# … a few lines of code here
exit if ‘x’ ~~ /^‘Z’/;
# … a few lines of code here
say $<start>, ‘ ↔ ’, $<end>; # ← OOPS!!
```

Output:
```
True
Nil ↔ Nil
```

Is it worth documenting on https://docs.perl6.org/language/traps? Can anybody else confirm that this is something they get into sometimes?

**Comment by bazzaar** [comment]
Perhaps there ought to be a language section entitled “Code Scope” with different examples highlighting how scope works, in various programming tasks.

Working with regex captures it’s always in my mind (as a perpetual newbie) whether I got the scoping right.

The comment I posted on B.Duggan’s Advent2017.10 Wrapping Rats article might possibly be another example to include in such a Language section.

Barry

**Comment by AlexDaniel** [comment]
That's not exactly a scoping issue isn't it?

**Comment by bazzaar** [comment]
You’re right, apologies if I got the wrong end of the stick, it just occurred to me that a solution to the code might involve placing the exit test in different scope, but if not please disregard my previous email.

Regards,
Barry

**Comment by fluca1978** [comment]
I've added a section at the very end of the regexp explaination with a couple of simple examples to demonstrate that $/ changes.
If that is ok, please close the issue, otherwise comment.
I don't believe this should also e explained in the Match class, since it is not something related to the type itself, rather to the special $/ variable.

**Comment by AlexDaniel** [comment]
This is good, but I think a separate entry on the [traps](https://docs.perl6.org/language/traps) page in addition to that is also needed.
