### ISSUE TITLE
Implementation-specific prose about { }

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1758]
https://docs.perl6.org/routine/%7B%20%7D

> Note that this construct does not re-parse the contents; rather, the contents are always parsed as a statement list (i.e. like a block), and if the later analysis shows that it needs to be interpreted as a hash, the block is executed and coerced to Hash.

The docs should not talk about some specific implementation.

Also: https://irclog.perlgeek.de/perl6-dev/2018-02-06#i_15783715

**Comment by zoffixznet** [comment]
More commentary: https://irclog.perlgeek.de/perl6-dev/2018-02-06#i_15783715

```
14:27 	jnthn 	Funny thing about the prose: that is *not* how it's presently 
                    implemented, so far as I recall. But if we *did* implement it like
                     that, it'd probably be better. :)
14:27 		The one pass parse part is correct. But iirc, we rewrite the AST 
                    to call circumfix:<{ }> with the stuff in the block.
14:28 	Zoffix 	But the one pass parse part is implementation-specific, isn't it?
14:28 	jnthn 	No
14:28 	Zoffix 	:o
14:28 	jnthn 	Pretty sure it's laid down that Perl 6 is parsed in a single pass
14:28 	Zoffix 	TIL
14:29 	jnthn 	Otherwise, you can't execute BEGIN blocks safely :)
```

**Comment by coke** [comment]
So, given that one pass parsing is part of the language, are there any remaining issues here to address?

**Comment by coke** [comment]
woot, thanks
