### ISSUE TITLE
Expand last example in the grammars tutorial to allow comments and blank lines

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#1759]
For example, fix grammar and actions to handle this input format (key/value input with comments and blank lines allowed):

```
my $s = q:to/EOI/;
# data for one baseball player
    name = Ray Henderson # nickname and last name
    hits = 42
    homers=62
    strike-outs =    # may e empty
 
 # another player
    name = Bat Masterson
    hits = 24

EOI
```

**Comment by coke** [comment]
What document URL/file is this referring to?

**Comment by JJ** [comment]
I want to say the Grammars tutorial, but I'm not sure either...

**Comment by tbrowder** [comment]
Sorry, not too clear.  Actually, both grammar files could use it, but I was originally referring to the last example in 'doc/doc/language/grammars.pod6'.

**Comment by JJ** [comment]
Would the white space separate two players? In that case, we need a higher-level grammar to take care of that. It would certainly increase the value of the tutorial, but I think it might be better to include another example rather than expand the current one.

**Comment by JJ** [comment]
There's an additional problem here, it's that it does not work if we use the default `ws` token. It fails in the action, with:
```
No such method 'key' for invocant of type 'Any'. Did you mean 'keys'?
  in block <unit> at key-value-pairs.p6 line 18
```

**Comment by JJ** [comment]
There's an additional problem with that example, and it's that it's redefining whitespace arbitrarily just because it's using a rule instead of a token. I think I'm going ot change that, for starters, and to reduce confusion.
