### ISSUE TITLE
Not documented ::NuT and ::DeT

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#176]
Rational and all inheriting classes use this types in constructor. It is hard to guess whether non int values are acceptable while this types are not documented.

**Comment by colomon** [comment]
Numerator Type and Denominator Type.

On Tue, Oct 27, 2015 at 6:59 AM, Kamil Kułaga <notifications@github.com>
wrote:

> Rational and all inheriting classes use this types in constructor. It is
> hard to guess whether non int values are acceptable while this types are
> not documented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/doc/issues/176>.
>



-- 
Solomon Foster: colomon@gmail.com
HarmonyWare, Inc: http://www.harmonyware.com

**Comment by timo** [comment]
On 27/10/15 11:59, Kamil Kułaga wrote:
>
> Rational and all inheriting classes use this types in constructor. It 
> is hard to guess whether non int values are acceptable while this 
> types are not documented.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perl6/doc/issues/176>.
>

Hi Kamil,

Rational is just a rol and those (NuT and DenomT) are type captures, 
which means that the role is instantiated with them set to a given 
value. They themselves are not defined anywhere. You can find out what 
they are set to for Rat and FatRat like this:

   say Rat.^roles; say FatRat.^roles;
   ((Rational[Int,Int]))
   ((Rational[Int,Int]))

I'm a little bit surprised that these two have the very same types for 
NuT and DenomT, but I suppose last time they were touched it wasn't 
possible to have that part working correctly with "int, int"?

Hope that clears things up a bit!
   - Timo

**Comment by timo** [comment]
i replied to this email with this text before realizing this is in perl6/doc rather than perl6-users, so it's less than helpful. Sorry!

**Comment by teodozjan** [comment]
@timo Actually i suppose num a denum have different type to prohibit 0 in denominator. Anyway this should be documented. Now Rat type looks scary.  i will fix this misleading subject.

**Comment by AlexDaniel** [comment]
It seems to be ``NuT`` and ``DeT`` now (not ``NuT`` and ``DenomT``).

**Comment by JJ** [comment]
... And these are still not documented, right?

**Comment by coke** [comment]
From Rational:

Rational is the common role for numbers that are stored as pairs of numerator and denominator. It is parameterized by the types of the numerator and denominator.

So, there is a mention here of them, but this could probably add a sentence to explain the connection between "parameterized" and the ::NuT in the sig.
