### ISSUE TITLE
Special variable `$¢` (Cursor) is not documented

### ISSUE THREAD

**Issue by samcv** [perl6/doc#1760]
Only https://design.perl6.org/S05.html mentions it.

**Comment by fluca1978** [comment]
Uhm..it also states that the match object and the cursor start the same in the beginning of the closure, but apparently I'm not able to get it:

```
> '123' ~~ / (\d) { say $0; say $¢; } \d+ /;
｢1｣
Nil

```

Also I'm not sure if such variable has to be documented at all, since it seems to me a little too much "magical" and the documentation for the `Cursor` states:
_A user-space program usually doesn't need to deal with Cursor objects, just with their relatives, Match objects._

**Comment by JJ** [comment]
They might be useful in Grammars, for instance. So it might be necessary to document them, at least. However, it might also be necessary to find now what they actually do in the current implementation.

**Comment by JJ** [comment]
It does not seem to move:
```
 '123' ~~ / (\d) { say $/; say $¢; } (\d+) { say $/; say $¢; }/;
```

yields

```
｢1｣
 0 => ｢1｣
Nil
｢123｣
 0 => ｢1｣
 1 => ｢23｣
Nil
```

Is it maybe a not-yet-implemented feature?

**Comment by JJ** [comment]
In fact, Cursor is initalized like Match: https://github.com/rakudo/rakudo/blob/b07e7b1d0ffcafc1f9dfbb3d56eff59c8eaddbf8/src/core/Cursor.pm#L1
Nothing else. Looks to me NYI

**Comment by JJ** [comment]
Or maybe even won't be implemented; https://github.com/rakudo/rakudo/blame/b07e7b1d0ffcafc1f9dfbb3d56eff59c8eaddbf8/src/core/Cursor.pm#L1
The commit line talks about "Cursor/Match unification"

**Comment by samcv** [comment]
Hmm. Maybe this means that it should be removed or a deprecation warning added and then removed? If it's not documented/used anywhere.

**Comment by coke** [comment]
This variable does appear in a 6.c-errata test file.

**Comment by JJ** [comment]
Behavior now is different, BTW:

     m:  '123' ~~ / (\d) { say "» / »", $/; say "» ¢ »", $¢; } (\d+) { say  "» / »", $/; say  "» ¢ »", $¢; }/;  
     jmerelo, rakudo-moar a71e370bb: OUTPUT: «» / »｢1｣␤ 0 => ｢1｣␤» ¢ »｢1｣␤ 0 => ｢1｣␤» / »｢123｣␤ 0 => ｢1｣␤ 1 => ｢23｣␤» ¢ »｢123｣␤ 0 =>  ｢1｣␤ 1 => ｢23｣␤»

**Comment by AlexDaniel** [comment]
Are we all satisfied with the docs? I thought `$¢` is now identical to just `$/` after TimToady++'s `recursor` work. Am I wrong? Also, didn't we have a plan to remove `$¢`?

**Comment by JJ** [comment]
No, it's not the same as $/. Outside the regex, $/ contains the match object, $¢ is nil. Can add that to the documentation if needed.
