### ISSUE TITLE
https://docs.perl6.org/links.txt should not exist

### ISSUE THREAD

**Issue by coke** [perl6/doc#1761]
This file is created during the build, but is only used by ./util/test-links.sh

The file should be generated outside of the html folder so it's not pushed to the external site.

**Comment by JJ** [comment]
We can just delete it and add it to .gitignore, right?

**Comment by coke** [comment]
It's already in .gitignore; it's generated as part of the build; deleting it would mean that the thing that needs it doesn't have it.

**Comment by JJ** [comment]
You want to move it elsewhere then?

**Comment by coke** [comment]
Yes:
{quote}
The file should be generated outside of the html folder so it's not pushed to the external site.
{quote}
