### ISSUE TITLE
any operator | messes up the table 

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1764]
The table of Junction operators in _doc/Type/Junction.pod6_ uses the `|` which is also the table cell separator. In the rendered output that creates an extra empty column:

         any  |   any          |   |        |   at least one value evaluates to True

![screenshot 2018-02-09 16 42 24](https://user-images.githubusercontent.com/22255/36051465-3c5d14ca-0db8-11e8-92b0-2c625ac02f28.png)

**Comment by tbrowder** [comment]
On Fri, Feb 9, 2018 at 15:43 brian d foy <notifications@github.com> wrote:

> The table of Junction operators in *doc/Type/Junction.pod6* uses the |
> which is also the table cell separator. In the rendered output that creates
> an extra empty column:
>

Brian, escape the pipe symbol with a backslash. See the table pod docs.

Best regards,

-Tom

@tbrowder
