### ISSUE TITLE
Numeric seem not have method Rat

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#177]
On http://doc.perl6.org/type/Numeric#Rat I've read there is `.Rat()` method but in https://github.com/rakudo/rakudo/blob/nom/src/core/Numeric.pm there is no any also 

     $ perl6 
       > Numeric.new.Rat
     Method 'Rat' not found for invocant of class 'Numeric'

**Comment by colomon** [comment]
There are several different issues here:

1) `Numeric` is a role.  The methods `.Real`, `.Int`, `.Rat`, and `.Num` should work (or produce appropriate errors) for all actual types which do the role `Numeric`.  But `Numeric` cannot know how to implement those.  (Well, in theory the last three could be implemented in terms of `.Real`.  It might be worth doing that.)

2) I don't know how exactly it makes sense to document this in the `Numeric` documentation.  `.Real`, `.Int`, `.Rat`, and `.Num` are methods you should be able to call on any useful `Numeric` object; however, they are not defined by `Numeric` itself.

2A) I'd argue it makes sense for all those methods to be defined on `Real`.  Yet as far as I can see, only `.Rat` is right now.

3) `Numeric.new`, on the other hand, does not produce a useful `Numeric` object.  You can't do anything with it, the only difference is what error messages you get.

    m: Numeric.new.log
    camelia: rakudo-moar cd7766: OUTPUT«Cannot call log(Numeric: ); none of these signatures match:␤    (Numeric:D $: Cool $base, *%_)␤    (Numeric:D $: Numeric $base, *%_)␤  in block <unit>

**Comment by teodozjan** [comment]
This `Numeric` punning was just fast example. I didn't expect to have it implemented but if all classes that `does Numeric` should have implemented `.Rat` I would expect at least prototype or stub. Please correct me if I'm wrong.

**Comment by gfldex** [comment]
.Rat (and a few related methods) are defined in Cool _for_Rakudo_ . There are no spec tests for Numeric to have Rat directly. It's a bit of a gray area. The invocant is tested against Numeric (in Cool) so one may want to look for them in Numeric. I would count this under implementation detail.

EWONTFIX, closed
