### ISSUE TITLE
«say $!.backtrace» prints "Backtrace.new", not a backtrace

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1770]
The docs imply that    `say $!.backtrace`    would print a human-readable backtrace, but actually it just prints "Backtrace.new".  [Using Rakudo  2017.06]. Assuming this is correct behavior (I'm unqualified to judge), then it is confusing to use this construct in code examples where the reader is likely to think that an actual backtrace would appear.   Suggest changing the examples to code which produces a backtrace for human consumption...

 ref: https://docs.perl6.org/type/Exception#method_backtrace
 ref: https://docs.perl6.org/type/X::AdHoc

Please see the example for `method backtrace` in class `Exception`, and
the first general example in docs for class `X::AdHoc`.

**Comment by JJ** [comment]
It might be that in that particular case it's all it does. There's no real backtrace. I've always tried to have examples expressing intent, not syntax (#1748). Let me see what I can do in this case, and thanks for this and all the other reports.

**Comment by JJ** [comment]
Rakudo 2018.01 actually prints "Something bad happened". Docs are adapted to the last version of Rakudo, usually...
```
$ perl6 backtrace.p6 
perl6 backtrace.p6 
Something bad happened
```

**Comment by JJ** [comment]
Not in the second case:
```
Got HTTP code 404 and backtrace Backtrace.new
```
