### ISSUE TITLE
NativeCall CArray[int32] doc probably wrong for some platforms

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1772]
Ref: https://docs.perl6.org/language/nativecall#Arrays

The NativeCall doc says  "CArray[int32]" interfaces to "int* in C, an array of ints"

but this is not correct if sizeof(int) != 32 in C on the execution platform.  This is related to the issue of not having support for a "native" P6 type which is guaranteed to be a "C int".  Something like "CArray[xxx]" is needed, where "xxx" is a type guaranteed to correspond to "int" in C (and also something for "unsigned").

Corrected documentation might say

 >   CArray[int32] interfaces to "int32_t* in C, an array of 32-bit ints"

**Comment by CurtTilmes** [comment]
Fixed https://github.com/perl6/doc/commit/98b1f499f8b378b724e6f94f4e389a40bfb266b2
