### ISSUE TITLE
Suggest use "NULL" to refer to C null pointers instead of "null string"

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1774]
Ref: https://docs.perl6.org/language/nativecall#Passing_and_Returning_Values

The docs for passing Str with NativeCall say:
> Note that a <b>null string</b> can be passed by passing the Str type object; a <b>null return</b> will also be represented by the type object."

On first reading I thought "null string" might mean an empty string.   Suggest using actual C jargon to make this unambiguous, e.g. "a NULL string pointer", "a C NULL pointer", or similar, to avoid confusion with a possibly-empty string which has an actual address.

Note: In C, the symbol "NULL" (in upper case) is used to specify a null string pointer (or any kind of null pointer).  It is a macro defined by <stdlib.h> which expands to `0`, `(void *)0` or similar.

**Comment by CurtTilmes** [comment]
Closed with https://github.com/perl6/doc/commit/177013b1d6e9343d5d4df26a172efa5890e88eaf

**Comment by jimav** [comment]
Wow, you guys are on it!    It's nice to see such fast response to doc issues.
