### ISSUE TITLE
possibly-confusing example of smartmatch of Signature literals

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1777]
Ref: https://docs.perl6.org/type/Signature#Signature_Literals

There is this example:

    my $sig = :(Int $i, Str $s);
    given ('answer', 10) {
        when :(Str, Int) { say 'match' }
        when $sig { say 'mismatch' }
    } # OUTPUT: «match␤» 

A newbie reader might infer that second 'when' clause could be executed if a non-matching signature was "given" (because the action is `say "mismatch"`).   It might be better to replace the second `when` with  `default { say "mismatch" }`.

My reasoning is that people just learning something benefit greatly from examples which "make sense" to them in every respect and don't have any logic bugs (which they may assume are not bugs but indicative of them not understanding the topic deeply enough).  Just my 2¢.  I'm in awe of all the high-quality work y'all have done in the last couple of years!

**Comment by JJ** [comment]
I'm all for #1748 The problem with your suggestion is that we wouldn't actually be using the declared $sig. I'll see what I can do, anyway.

**Comment by jimav** [comment]
Still seems underdone, not ready to eat.  I posted a comment to the commit which I realize now should have been here.  Please see comment#1 at https://github.com/perl6/doc/commit/653a7994d3e18ab0963270c3e06b0ddee57ad5fa

In brief, the first `when` clause cant ever match any $sig because it is a reversed smartmatch and ~~ is not commutative; the example reverses the terms in the list (10,'answer`) but that is a complete red herring because what's in the list makes no difference, i.e.  $sig ~~ (...) will never be True for any list.

For reference, the revised example I responded to is this:

my $sig = :(Int $i, Str $s);
say (10, 'answer') ~~ $sig; # OUTPUT: «True␤» 
given $sig {
    when ('answer',10) { say 'mismatch' }
    when :(Int, Str)   { say 'match' }
    default            { say 'no match' }
}

**Comment by jimav** [comment]
Very nice, JJ.   I like how you show matching the more-general signature ($,$).

**Comment by JJ** [comment]
Thanks a lot for your feedback and for helping to get this right :-)
