### ISSUE TITLE
Next perl6/doc squashathon taking place on March 3rd

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1778]
Next [squashathon](https://github.com/rakudo/rakudo/wiki/Monthly-Bug-Squash-Day) will be devoted to this very repository, so choose carefully your issues, sharpen your toolbelt, and get ready to squash as many bugs as possible!
My suggestions: start with #114 and maybe move up the [`big`](https://github.com/perl6/doc/issues?q=is%3Aissue+is%3Aopen+label%3Abig) tag. 
Good luck!

**Comment by coke** [comment]
-1 on this being a ticket

**Comment by AlexDaniel** [comment]
Well, with 1h left for the squashathon I think we can close this :)

**Comment by JJ** [comment]
2018-02-20 3:13 GMT+01:00 Will Coleda <notifications@github.com>:

> -1 on this being a ticket
>

It was the best way to warn everyone involved. I actually missed the
previous one.

**Comment by coke** [comment]
"best way" I disagree. email, blog posts, tweets, IRC... it's not an issue to be fixed.

**Comment by JJ** [comment]
OK, point taken. Won't happen again.
However, I'd like to know which email list are you using then. I don't
usually hang out in IRC. And I haven't seen the blog posts either. As I
have said, didn't know about the Squashathon until @zoffixznet mentioned it
in some other issue.

**Comment by coke** [comment]
No, I'm saying if we want to get the word out, those are all things that can be used. I'm not saying they are being used to good advantage at the moment.

The people who are getting the alerts on these tickets, are, I expect, are mostly on IRC and therefore saw the alerts from @AlexDaniel.

**Comment by JJ** [comment]
But you're right on the money here, I shouldn't have mentioned you. Won't happen again.
