### ISSUE TITLE
Operator ::( ) not officially documented

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#178]
The ::( ) operator seems to be used in a couple of modules by now including LWP::Simple to test for SSL, lately URI and maybe Panda.  I haven't found it documented anywhere except for a very brief mention in S11.

**Comment by awwaiid** [comment]
::( ) isn't quite an operator -- rather the :: is tapping into the package name system, and the ( ) is doing a lookup. I started some docs in #224 which will hopefully clarify.

**Comment by awwaiid** [comment]
#224 has been merged, which at least starts to document this.
