### ISSUE TITLE
t/tabs.t failure

### ISSUE THREAD

**Issue by coke** [perl6/doc#1780]
New example in doc/Language/objects.pod6 uses literal tabs.

Easiest solution: rewrite example to use spaces instead.

**Comment by coke** [comment]
Now the code doesn't match the output.

My suggestion is to make the output match the program by not using escaped tabs in the code, and then not using literal tabs in the output.

Sorry that wasn't clear.

Also, probably better to have discussion about ticket requests outside of commit messages.

**Comment by JJ** [comment]
So tabs are banned from examples? Or would it better to insert them in a `:skip-test` chunk?

**Comment by coke** [comment]
Basically, yes, they're banned.

We could allow exceptions if we were specifically trying to demonstrate how tabs work (note that this exception would have to be added to xt/examples-compilation & the docs around it), but since our main target is the web site, tabs don't really add any value here.

Looking at the example, the tabs are incidental, and not a core part of what is being demonstrated, so easiest to just remove them to avoid the issue.

I also recommend running

```
TEST_FILES="doc/file/changed.pod" make test
```

or, better:

```
TEST_FILES="doc/file/changed.pod" make xtest
```
Before committing to catch these issues before they make it to travis. This allows you to quickly run the full test suite against only those files with updates so you don't have to wait for a full make xtest, which can be quite slow

**Comment by coke** [comment]
Linking 598d950fb1e4c709e001053d616b59802ee1976c which referenced this ticket but missed the leading "#"
