### ISSUE TITLE
Cross-reference .ords and .codes

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#1781]
Suggestion: refer to .ords in the documentation for .codes, and vice versa, and maybe note in .ords that .codes is the same as +.ords, but much faster.

**Comment by AlexDaniel** [comment]
> but much faster

We try not to talk about specific implementations, so that part can be crossed out.

**Comment by Juerd** [comment]
That's unfortunate, because most readers of the documentation will be real programmers writing real programs, and many will be interested in performance considerations. The documentation is a great place to provide such information; I think implementation specific things can (and should) be included, but marked as such.

**Comment by AlexDaniel** [comment]
@Juerd Str.ords was made [much faster](https://github.com/rakudo/rakudo/commit/8b7385d810) a few moments ago (for the next release, so not in master right now). I don't know how it compares with `.codes` now, but in any case that demonstrates how fragile such remarks are. Also, performance may depend on many factors so ruling out some constructs as slow and others as fast is not that great of an idea anyway. Real programmers writing real programs should use real benchmarking.

**Comment by AlexDaniel** [comment]
On a related note, I've been pushing to document tricky and harmful **bugs**, but dev consensus seems to be against it (if I recall correctly). Some exceptional things got documented anyway, but it's hard to tell where to draw the line. See this issue: https://github.com/perl6/doc/issues/1486

I think performance aspects are too early to discuss until we get a clear decision regarding implementation bugs.

**Comment by coke** [comment]
I am sure we can come up with language that indicates the possibility of going faster because less work is required, but that no guarantees are made.
