### ISSUE TITLE
Expand slice examples.

### ISSUE THREAD

**Issue by labster** [perl6/doc#1782]
~~Can't~~ ~~search~~ ~~for~~ ~~'Slice'~~.  ~~Or~~ ~~'zen~~ ~~slice'~~ ~~either.~~

~~Probably~~ ~~should~~ ~~link~~ ~~to~~ ~~https://docs.perl6.org/language/subscripts#Slices~~ ~~and~~ ~~https://docs.perl6.org/language/subscripts#Zen_slices~~

Might be useful to have an example of how to take the last N elements of an array, too. `@a[*-$N .. *]`is a bit more difficult than the trivial first N elements slice, `@a[^$N]`

**Comment by JJ** [comment]
Slice is not in one of the categories that are indexed. It's a concept, but not a class, sub, method or suchlike. 
You have a point in your last paragraph, though. If you don't mind, I'll change the subject of the issue to that.

**Comment by labster** [comment]
Concepts should be searchable, but fair enough for now.

**Comment by JJ** [comment]
Yep, but that's a different issue altogether. Feel free to open an issue to discuss it openly, though.
