### ISSUE TITLE
Explain how to _not_ bind sigilless variables

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1784]
Ref: https://docs.perl6.org/language/containers#Binding

The doc says "Sigilless variables also bind <b>by default</b> ...", but doesn't hint at what <i>non</i>-default possibilities might be.

Suggestion: Show an example using a sigilless var does _not_ bind to something when created.

(Added later) According to https://docs.perl6.org/language/variables#Sigilless_variables "sigilless variable do not have associated containers", which makes me wonder how a sigilless variable could exist if it wasn't bound to something.  If the "by default" above is simply incorrect, then the doc might be changed to say "Sigilless variables always bind, as do parameters with the trait is raw."   

But I still don't understand this: Both regular assignment `=` and bind `:=` operators can be used, e.g. `my \x = $var;` and `my \y = $var;` both compile and AFAICT do exactly the same thing.  But in that case, why doesn't Perl6 simply dis-allow normal assignment (`=`) on sigilless vars and avoid all confusion around this topic?    So if there _is_ some semantic difference, it would be helpful to describe or allude to what the difference is.

**Comment by jnthn** [comment]
Binding is the only option for a sigilless variable (in fact, calling them variables at all is a bit odd, because they cannot vary).

**Comment by JJ** [comment]
"Also" might be misplaced here. "Also, sigilless variables bind *by default*"
would be clearer here.

**Comment by JJ** [comment]
About disallowing normal assignment, that is outside our turf. Makes sense, but then it also makes sense to assume that they always bind whatever operator you use.

**Comment by jimav** [comment]
Then "by default" is misleading because it implies there is another option ("by default" means "if the user does not specify another choice").  

Better to explicitly state the situation, for example  "Sigilless variables always bind (whether `=` or `:=` is used), as do parameters with the trait `is rw`.
