### ISSUE TITLE
Test error: test OKs code that does not compile

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1787]
From #1785 , that example does not compile: 
```
Too few positionals passed; expected 1 argument but got 0
  in block <unit> at callable-containers.p6 line 3
```
But the chunk does:
```
ok 8 - doc/Language/containers.pod6 chunk 8 starts with “my &c = ->” compiles
```

**Comment by coke** [comment]
FYI, the code mentioned here no longer exists on that page. Can you post the specific problematic code here, or point to a github URL (with line numbers) that shows the code?

**Comment by coke** [comment]
Note that your message above appears to be a run time error; the code isn't executed if at all possible, only compiled.

**Comment by JJ** [comment]
The code is in the issue; I changed that so it's no longer on the page. And you are right, it's a runtime error, so it's best to just close it.
