### ISSUE TITLE
Type constraints in callable containers

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1788]
It says "The default type constraint is L<Callable|/type/Callable>.", but in fact they are `Block`s.[ `Callable`](https://docs.perl6.org/type/Callable) is a role, not a type, in fact.

**Comment by jnthn** [comment]
Would be helpful if the issue referenced where it says that. :-) But:

* Roles are most certainly types
* In a declaration like `my &foo;`, the type constraint is indeed `Callable`
* Same goes for an `&foo` parameter

**Comment by JJ** [comment]
OK, got it.
