### ISSUE TITLE
more than one 'zef'

### ISSUE THREAD

**Issue by LenW2** [perl6/doc#1789]
At least two key documents for getting started with Perl 6 have pointers
to 'zef'.  Unfortunately, they point to a disambiguation page with
TWO versions of 'zef'.  This is confusing and frankly, disconcerting,
for a user new to Perl 6.

The key documents I refer to are:
* the Perl 6 FAQ (https://docs.perl6.org/language/faq)
* Rakudo Downloads (http://rakudo.org/how-to-get-rakudo/)

The disambiguation page is:  https://modules.perl6.org/dist/zef

**Comment by JJ** [comment]
They're actually the same thing, and @ugexe is Nick Logan. But it's
confusing to send people to that page. I'll fix that. Thanks for the
report.

**Comment by JJ** [comment]
I have found the GitHub page less confusing than the other, so I've changed the link to point to that. Can't do a thing about the Rakudo page, you'd better raise the issue there, sorry.

**Comment by LenW2** [comment]
Thanks for the lightning quick response.
But, sorry, I don't see what was changed:
on the FAQ at https://docs.perl6.org/language/faq#Modules
the pointer to "zef module installer" still gets to the disambiguation page.
(Sorry I wasn't more detailed in my OP, but this pointer gets there via
https://modules.perl6.org/l/zef .)

**Comment by JJ** [comment]
Takes a while to deploy; to tell you the truth, I don't know how much. You
can follow the link to the commit to see what was changed.

**Comment by LenW2** [comment]
On second thought, it seems that changing the pointers is just a band-aid.
Since the apparent "two versions" are actually the same thing,
is there a way to make only one show up at https://modules.perl6.org/dist/zef
or to have that page have some clarifying verbiage?
(Sorry if this is making a mountain out of a molehill.)

**Comment by JJ** [comment]
It might, but it's not our turf. Far as I can tell, you can try and suggest
a change in the Perl modules itself
https://github.com/perl6/modules.perl6.org. As a matter of fact, it's not a
bandaid, it's the actual link where one of the two links point to.

**Comment by zoffixznet** [comment]
> Since the apparent "two versions" are actually the same thing,

That's a known issue, as the site currently considers author name + dist source as a dist auth and what's meant to be consdered as auth of a dist is not yet properly specced in Perl 6.

The generic modules.perl6.org URL would be https://modules.perl6.org/dist/zef:github (with `github` signifying dist source).

**Comment by LenW2** [comment]
Thanks to all who helped with this.  The pointers are now fixed on rekudo.org,
as well some more pointers on perl6.org .
