### ISSUE TITLE
Is the matching magic really nondeterministic?

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1790]
https://docs.perl6.org/language/regexes#Backslashed,_predefined_character_classes says:
```
\n matches a single, logical newline character. \n is supposed to also match a Windows CR LF codepoint pair; though it's unclear whether the magic happens at the time that external data is read, or at regex match time.
```

However, I think `newline` pragma can make it deterministic.
```
$ perl6 -e 'use newline :crlf; say $?NL.perl;'
"\r\n"
```

**Comment by coke** [comment]
phrases like "it is unclear" really don't belong in the docs, IMO.

**Comment by fluca1978** [comment]
I reword the text. I don't have a windows/perl6 machine right now, if someone can test it for better documentation it is welcome.
If what I wrote does suffice please close the ticket.

**Comment by ZzZombo** [comment]
If what needs to be tested is whether `\n` catches both `\r` (#13) and `\n` (#10) on Windows, yes, it does.
