### ISSUE TITLE
A page is missing in the documentation.

### ISSUE THREAD

**Issue by denis-beurive** [perl6/doc#1791]
Hello,

I don't know if it is worth mentioning, but I mention a bug in the WEB site.

From the page `https://docs.perl6.org/routine.html`, I clicked to the link below:

`https://docs.perl6.org/routine/.*`

The required page does not exit. Instead, I can read the following instructions :

> The page you tried to reach cannot be found. If you got here by following a link on this site, please report it on our GitHub repository so we can fix it!

Thus I report the error.

Best regards,

Denis

**Comment by fluca1978** [comment]
Also `.+` does not work, probably it is a problem of the ".symbol" URL that becomes a not good one.
Aren't these links produced from the `Routine.pod6` operators `X` directives?

**Comment by JJ** [comment]
Related: #1677 and specially #1542. Please @denis-beurive  check it and, if it's the same case, close this one as duplicate.

**Comment by denis-beurive** [comment]
I looked at the issue #1677 and at the issue #1542. 

## Issue #1677

I don't think that the issue #1677 is identical to the current one. Indeed, if I follow the procedure to reproduce the problem, then a WEB page is returned. That is : a WEB page is found (https://docs.perl6.org/syntax/?) - there is no 404 error code.

> Note : I think that there is a problem with the URL.

## Issue #1542

The issue #1542 is pretty similar, but nor identical. It is similar in the sense that the problem is related to broken links. However, it is not identical because the page involved is different.

* The current issue is related to the following page : https://docs.perl6.org/routine.html
* However, the page related to the issue #1542 is : https://docs.perl6.org/routine-operator.html

## Conclusion

These 3 issues are not identical, but they are very similar because they all involve invalid characters in the URL.

Thus, I don't know whether I should close the issue or not. Maybe these issues are all related to the same software component (that generates the URLs). In this case we should close the issue.

**Comment by JJ** [comment]
In fact, `.*` is mentioned explicitly in @rafaelschipiura comment to that issue.  In fact, it would be better if you add this and other similar examples to that comment so that it keeps centralized. But it's your call and your issue.

**Comment by denis-beurive** [comment]
OK, I'll add this issue to the issue #1542 (and close the current one).
