### ISSUE TITLE
How to interrupt `sleep-timer`

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1795]
The documentation for [`sleep-timer`](https://docs.perl6.org/routine/sleep-timer) says *"This function is just like sleep, but returns the amount of time remaining to sleep as a Duration (which will be 0 if the call was not interrupted)."* however it doesn't mention what this "interrupt" is and how to effect on purpose.

**Comment by manchicken** [comment]
So, it’s saying that if the system call didn’t get interrupted at all, this would be zero (I think). I don’t think you can interrupt that on purpose, that’d be the prerogative of the OS, and dependent on load. If you need a precise sleep timer, this is important as your overall sleep time may actually be (sleep time + interrupt time). 

This is me making some slight guesses, not having read the code behind that function. 

~ Michael D. Stemle, Jr.

**Comment by JJ** [comment]
Thanks, @fluca1978 :100:
