### ISSUE TITLE
clone-with-op is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1798]
Here is the example of clone-with-op method

```
$ perl6 -e 'my $range = 0..3; my $new-range = $range.clone-with-op(&[+] , 10); say $new-range;'
10..13
```

https://github.com/rakudo/rakudo/blob/nom/src/core/Range.pm#L623-L630

(I created this new one because #818 contains two issues in one thread and the other issue is already solved.)

**Comment by JJ** [comment]
Would it go to Ranges too?

**Comment by titsuki** [comment]
@JJ 
IMHO, at least, it requires testing in roast.
See also: https://github.com/perl6/doc/issues/835

**Comment by fluca1978** [comment]
I don't close the ticket, since it could serve to add a test in roast.

**Comment by zoffixznet** [comment]
We shouldn't be documenting things that aren't part of Perl 6 language. What Rakudo does doesn't define the language, the spec does.

I don't see `Range.clone-with-op` even in the proposals for 6.d language.

IMO, it shouldn't be added to the language:

* It's an outlier to language features we offer—the same reasoning offered in the commit implementing it can be used for some other objects, like `DateTime`, yet we don't have `.clone-with-op` for them
* The majority of cases where this method would be useful are already covered by operators `+`, `-`, `/`, and `*` applied to `Range` objects
* The results with the many of the other Callables are bizarre, invalid ranges. If we're going to claim a DIHWIDT for 99% of method's usage, why implement it at all?

```perl6
    .say with ^Inf .clone-with-op: &substr, 1; # OUTPUT: ""..^"nf"
```

It also has a bug in it:
```
$ ./perl6 -e 'with ^Inf .clone-with-op: &[andthen], 42 { .say; .infinite.say; .pick.say }'
42..^42
True
Nil
```

**Comment by jnthn** [comment]
It looks to me like `clone-with-op` was added to support the implementation of the various arithmetic operators on `Range`. It's name pretty much screams "implementation detail" too. I guess it factors out some repetition compared to if the ops all implemented the functionality directly, which is a good thing. Perhaps there's a way to move the logic into `Rakudo::Internals` instead, so we don't "leak" it into the user-facing API.
