### ISSUE TITLE
RAKUDO_VERBOSE_STACKFRAME is not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1799]
It's a pretty neat feature that dumps code around the spot where throwage happeend:

```
$ RAKUDO_VERBOSE_STACKFRAME=1 ./perl6 --ll-exception ../z.p6 
X::TypeCheck::Binding::Parameter
Constraint type check ZZ9 failed in binding to parameter '<anon>'; expected ZZ8 VLANZZ3 but got Int (0)
  in method throw at SETTING::src/core/Exception.pm line 57
  in block  at SETTING::src/core/Exception.pm line 2711
  in block  at ../z.p6 line 3
    2  
    3* try -> VLAN {}(0);
    4  $!.^name.say;

  in code  at ../z.p6 line 3
    2  
    3* try -> VLAN {}(0);
    4  $!.^name.say;

  in block <unit> at ../z.p6 line 6
    5  $!.message.say;
    6* $!.backtrace.full.print;
    7  
```

**Comment by JJ** [comment]
Where do you think this should go? Maybe retrieve the 00-programs moving it somewhere else? Related to #949 maybe?

**Comment by fluca1978** [comment]
An extension to the `Exception` documentation <https://docs.perl6.org/language/exceptions>?

**Comment by zoffixznet** [comment]
> An extension to the Exception documentation

No, it's a Rakudo-only variable. It needs to be documented with Rakudo-only stuff, not as part of the general language documentation.

There used to be a single page precisely for that, but since #949 I don't know where's what.

**Comment by JJ** [comment]
The proposal was to create a copy of the page in the Rakudo repo. The issue
is still open, so any suggestion is welcome.
