### ISSUE TITLE
defined is not indexed as a method

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1800]
[https://docs.perl6.org/routine/defined](https://docs.perl6.org/routine/defined)

![screenshot 2018-02-26 05 27 09](https://user-images.githubusercontent.com/22255/36665601-069efc3a-1ab6-11e8-8a06-4ead0d42f7bd.png)

**Comment by fluca1978** [comment]
Apparently I missed something: while the method is in place and listed in `Mu` documentation, it does not get indexed. Am I missing something?

**Comment by JJ** [comment]
@fluca1978 I have no idea how those categories work: method, routine and sub are used interchangeably. See #638
