### ISSUE TITLE
.serial is not well documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1803]
This is possibly unspecced.

Searching for `serial` doesn't show any results, although there's a [cryptic description in Any](https://docs.perl6.org/type/Any.html#serial) that's missing a `routine` or `method` prefix in the title.

Why `Any.serial`, does simply return `self` that doesn't quite explain why the method exist—I'm presuming it's to allow for 1-el-list semantics with some one of the narrower types that provide `.serial`, so that should be mentioned I think.

From Rakudo's source, I see Proc::Async, some types in Supply.pm, IO::Socket::Async, as well as RaceSeq and HyperSeq have implementation of `.serial`, but I don't know what's actually part of the specification.

**Comment by jnthn** [comment]
The `serial` method is used to make sure we're in serial list processing mode, as opposed to `hyper` or `race` (for example, `.hyper.map(&safe-thing).serial.map(&side-effecty-thing)`. We could perhaps just force people to write `.Seq` instead, but my feeling is a `.serial` method communicates the intent a bit better.

**Comment by jnthn** [comment]
One other consideration: `Supply` has a method `serial` on it which is a property saying whether the `Supply` is a serial one or not. So it's quite possible we shouldn't go re-using that name, however fitting it is, for the "leave hyper/race mode" functionality.

**Comment by timo** [comment]
perhaps this could get the name `.serially`

**Comment by JJ** [comment]
This is still not tested, and thus not specced. Should the spec go before or after the spec? Is it better if I add a request for test somewhere?

**Comment by JJ** [comment]
it is documented now, but according to [this comment](https://stackoverflow.com/questions/56057931/what-does-serial-do) it's not too clear what it does...
