### ISSUE TITLE
https://docs.perl6.org/type/Callable has NYI example

### ISSUE THREAD

**Issue by coke** [perl6/doc#1805]
First example shows two "Not Yet Implemented" samples

They were originally added in a281cb8ac46609038ac295fc4077bf44773c5e03 as part of #320; the note that they were NYI was added once we started compiling all the examples, I think.

**Comment by fluca1978** [comment]
Not sure it could be fixed:

```
> my &f:(Int) = sub bar(Int) {};
===SORRY!=== Error while compiling:
You can't adverb &f
```

**Comment by JJ** [comment]
What do you suggest? Eliminating it?

**Comment by coke** [comment]
Yes, if it's an example that isn't working, and is not being shown as an example of what not to do, it should be removed (and surrounding text updated if needed)

**Comment by JJ** [comment]
In fact, there are working examples of the same thing, only using [Callables as arguments for routines](https://docs.perl6.org/type/Signature#Constraining_signatures_of_Callables). That works. I guess it can be safely removed.
