### ISSUE TITLE
nextcallee() appears to be undocumented

### ISSUE THREAD

**Issue by lizmat** [perl6/doc#1806]
But *is* tested.

**Comment by zoffixznet** [comment]
There's some description on Rakudo.Party that can probably be stolen: https://rakudo.party/post/Perl6-But-Heres-My-Dispatch-So-Callwith-Maybe#whosnext

Should be fairly accurate.

**Comment by zoffixznet** [comment]
Looks like it is documented: https://docs.perl6.org/routine/nextcallee

**Comment by lizmat** [comment]
Ok, I thought I typed "nextcallee" in the search box, but I guess I must have typed something else.

Sorry for the noise!
