### ISSUE TITLE
... is not indexed

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1809]
I discovered this while reading about stub methods, but it's also the sequence operator. The !!! is indexed.

<img width="486" alt="screenshot 2018-03-02 13 18 21" src="https://user-images.githubusercontent.com/22255/36914934-edc5704e-1e1c-11e8-962d-98bc0625eebd.png">

**Comment by zoffixznet** [comment]
Yeah, there's something wrong with the code that processes the index annotations. Filed in https://github.com/perl6/doc/issues/1743
