### ISSUE TITLE
Doc build is broken

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1812]
See https://docs.perl6.org/build-log/ ([example](https://docs.perl6.org/build-log/build-2018-03-04T08:55+00:00.log)). I tried building locally but couldn't reproduce the issue. I am suspecting that d468b66bd01ed4f9e82ee5130bff0e0d8346541e is the offender but I can't see why. The last successful build was on the parent of d468b66bd01ed4f9e82ee5130bff0e0d8346541e.

**Comment by AlexDaniel** [comment]
@moritz installed newer rakudo and the issue disappeared. I guess it's resolved.

**Comment by moritz** [comment]
For the record, I did not install a newer rakudo, just cleaned out the build directory. Still, it worked :-)
