### ISSUE TITLE
grammar is inheritable but this feature is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1816]
See: https://github.com/perl6/roast/blob/master/S05-grammar/inheritance.t

**Comment by ronaldxs** [comment]
Discussion of grammar inheritance should also cover role(s) for regex(|rule|token) reuse.

**Comment by JJ** [comment]
Grammars are classes, so inheritance is a given. The tutorial says:
"Grammars are a special kind of class.". Would that be enough, or maybe we
should add something along the lines you have suggested?

**Comment by titsuki** [comment]
@JJ IMHO, some readers don't notice that grammar is inheritable if the documentation doesn't explicitly show the example code.
