### ISSUE TITLE
No matches for `unit` in the search index

### ISSUE THREAD

**Issue by cfa** [perl6/doc#1819]
Searching for `unit` yields no matches; this should probably lead to [modules#Loading_and_Basic_Importing](https://docs.perl6.org/language/modules#Loading_and_Basic_Importing) (which likely needs to be fleshed out a little further).

I'm also not sure whether `unit sub MAIN` is documented anywhere?

**Comment by JJ** [comment]
Does not look like it. It's not in /language/packages, either...
