### ISSUE TITLE
Merging "whitespacey" tests

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1822]
There are [three different tests](https://github.com/perl6/doc/tree/master/xt): space-after-comma, trailing-whitespace and perl-nbsp. They kinda do the same: read lines in a file, check for stuff, consider exceptions. [`space-after-comma.t`](https://github.com/perl6/doc/blob/master/xt/space-after-comma.t) is the coolest (great job, @coke and @zoffixznet) doing stuff asynchronously, using promises. 
Could we maybe graft the other two into the first and refactor so that we can easily check for regexen + exceptions in a single file?

**Comment by zoffixznet** [comment]
Sidenote: when you tag people with `@username`, you're forcefully subscribing them to all the notifications on that particular Issue. If you need to solicit a response from a person, then sure, tag them, but it's somewhat antisocial to force them to read notifications they're not interested in—especially since some Issues have a lot of [content the user needs to read in full](https://github.com/perl6/doc/issues/1778) before figuring out why notification came up in the first place.

**Comment by JJ** [comment]
Besides kudos for that program, since you have created the main test I refer to, I kinda *do* need a response from you. It's your test, after all.

**Comment by zoffixznet** [comment]
>   you have created the main test [...] It's your test, after all.

I think what you're seeing is me [fixing the typo in the filename](https://github.com/perl6/doc/commit/144f0be23ed3cffdce2c24b26d3d01d7ab356412#diff-46ffeafd4feee65cf215ed1c3c17de21), which make me show up as the first commit in history for the *current* file, but [history for previous filename name](https://github.com/perl6/doc/commits/master/xt/space-after-commma.t) shows it was [Coke] who [created it](https://github.com/perl6/doc/commit/96761b22094df050e06d283ae6b2e6a975123f0f#diff-5d0efce9925d0831c92ed8fd2337cb53).

**Comment by coke** [comment]
If someone wants to try to combine these files, that's fine, we can theoretically run everything faster,  but I'm not going to spend cycles on it.

**Comment by JJ** [comment]
I *do* have to spend cycles around here anyway, so I might as well do it here if it's OK with everyone.

**Comment by JJ** [comment]
I have been having a look at this today, including trailing-whitespace.t inside `space-after-comma.t`. Ultimately managed to make it work, but the problem is that the former is processing the file with --doc, while the latter works with it in raw fashion. That, and the fact that it's doing a single test per file are both problems, but the latter is doable. 
Several options here: First one is to just not process the file using `perl6 --doc`, for which I fail to see a good reason. Second is to take that one out of the triad and just merge `trailing-whitespace` and `perl-nbsp`. 
Thirds of course is to forget the whole thing and just close the issue while there are 272 other things to do.
