### ISSUE TITLE
new C tutorial doesn't compile

### ISSUE THREAD

**Issue by coke** [perl6/doc#1826]
83ddea53e added a nativecall C tutorial which doesn't pass xt/

I've committed some updates that mark the C code as such, and output text as such so they aren't tested, leaving these 4 chunks:

```
$ xt/examples-compilation.t doc/Language/nativecall.pod6 2>&1 | grep 'not ok'
not ok 24 - doc/Language/nativecall.pod6 chunk 24 starts with “sub getadd” compiles
not ok 25 - doc/Language/nativecall.pod6 chunk 25 starts with “class Addr” compiles
not ok 26 - doc/Language/nativecall.pod6 chunk 26 starts with “method fla” compiles
not ok 27 - doc/Language/nativecall.pod6 chunk 27 starts with “ \#!/usr/bin” compiles
```

Not sure how much effort it is to make this compile-able, but it would be nice if it passed the test. 

Note that we can use ":preamble" on a code block if we need to make something available to a different block.

**Comment by JJ** [comment]
First and last should better be skipped, right? First one is C code and the last one a script.

**Comment by coke** [comment]
C code is skippable by adding :lang<C>.  The script is  Perl 6 and should be valid code.

**Comment by coke** [comment]
:lang(c)

**Comment by JJ** [comment]
I'll check it out

**Comment by JJ** [comment]
The code at the last one works correctly:
```
$ perl6 full-example.p6 
perl6 full-example.p6 
return val: 0
Name: google.com
AF_INET SOCK_STREAM
172.217.16.238
AF_INET SOCK_DGRAM
172.217.16.238
AF_INET SOCK_RAW
172.217.16.238
AF_INET6 SOCK_STREAM
2a00:1450:4003:809::200e
AF_INET6 SOCK_DGRAM
2a00:1450:4003:809::200e
AF_INET6 SOCK_RAW
2a00:1450:4003:809::200e
```
It yields an error `Unexpected block in infix position (missing statement control word before the expression?)` which I can't really figure out in test. The other two are using data structures that haven't been declared. There are many other skipped tests here and there, some of them using dummy class names. Hope this is OK.

**Comment by coke** [comment]
You should not be using :skip-test without documenting why you're skipping the test. Please see: https://github.com/perl6/doc/blob/master/EXAMPLES.md which documents the various options you have when dealing with sample code.

The first item you skipped is Perl 6 code, not C; the method is also Perl 6 code, not C.

There was no need to remove the shebang line in the last example.

**Comment by JJ** [comment]
I know both methods are Perl6 code. I tested them outside, and they worked. I added the comment above to document why I was skipping the test. I probably shouldn't have eliminated the shebang, but then taking it out is no big deal either. 
I will try and see if some of that works, if not I'll document the skipping inline using the mechanism indicated in the page you have pointed to.
