### ISSUE TITLE
travis build installing modules it doesn't need

### ISSUE THREAD

**Issue by coke** [perl6/doc#1827]
I see in the travis builds that IO::String is being installed with zef.

IO::String is only used in xt/examples-compilation.t, which is not part of the travis test run.

It's listed as a hard dep in META6.json ; it should be optional. (and we should check all the other deps there to make sure they are used outside of xt/)

**Comment by coke** [comment]
I didn't research this, which is why I opened a ticket instead of just removing it, but isn't there a way to specify optional deps so a developer can still use zef to do the install of the deps?

**Comment by zoffixznet** [comment]
> isn't there a way to specify optional deps so a developer can still use zef to do the install of the deps

None that I know of, other than manual instructions.

It looks like all that module was used for is to ignore some output, right? I just used core way of doing that in https://github.com/perl6/doc/commit/45ce3b6a17aec2aeb07514c10bda99b64f089e7e and we no longer need that module.
