### ISSUE TITLE
travis allowing failures on OS X

### ISSUE THREAD

**Issue by coke** [perl6/doc#1828]
.travis.yml has:

matrix:
  allow_failures:
    - os: osx

added in 9d74487e8

I think the build is fine on the mac; if no one objects, I'll remove this in the next few days and see what explodes

**Comment by JJ** [comment]
:+1:

**Comment by nxadm** [comment]
@coke Create temporarely branch for the .travis.yml changes and see if Travis complains or not?

**Comment by JJ** [comment]
Nothing exploded, but now this is not tested... So maybe we could try and add it back as part of the matrix.

**Comment by JJ** [comment]
I think I'm closing this. Now build is docker and executable based. None of them work on the Mac. We might create a new one from scratch to test on the Mac, but that would be a different issue.
