### ISSUE TITLE
The release cycle of both rakudo and rakudo-star aren't disclosed

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1830]
AFAIK,
rakudo-star: released every three months.
rakudo: released every months.

**Comment by AlexDaniel** [comment]
See http://rakudo.org/about/:

> An updated compiler is released monthly.

> A Rakudo Star release is produced at least quarterly (sometimes monthly).

In general, the docs are about the language and not some specific compiler, so this particular detail does not have to be mentioned I think. Any way we can resolve this issue by not just rejecting it?

**Comment by JJ** [comment]
I see at least two options.

* Add it as a question in the FAQ
* Create a new page in the `program` directory called "implementations" mentioning this.

**Comment by nxadm** [comment]
And then again, implementations and distributions aren't the same thing.
