### ISSUE TITLE
The download page doesn't mention the difference between rakudo-star and rakudo

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1831]
This section describes the difference well:
https://docs.perl6.org/language/faq#Does_Rakudo_have_a_core_standard_library?

However, I think it's little bit difficult to find this section because this section isn't indexed.
Isn't it better to write this explanation in the download page (https://perl6.org/downloads/)?

**Comment by JJ** [comment]
The downloads page is not part of this documentation. See also #1830. Maybe close this one?

**Comment by titsuki** [comment]
https://github.com/perl6/rakudo.org seems good place to submit this kind of issue so I'll close this one.
(But it isn't ready yet)

**Comment by titsuki** [comment]
This issue was moved to: https://github.com/perl6/perl6.org/issues/93
