### ISSUE TITLE
Regex :sigspace example glitch ("foo+" should be "foo+ " ?)

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1832]
Ref: https://docs.perl6.org/language/regexes#Sigspace

The above says <<On the other hand, whitespace after a quantifier acts as normal significant whitespace; e.g., "foo+" becomes foo+ <.ws>.>>

I'm guessing that should be "foo+ " (with space after the +) not "foo+".   

This might be a problem in translation to html, or possibly even rendering in Firefox.  In any case, the "foo+" does not display with any spaces in my browser.

**Comment by jimav** [comment]
The Unicode SYMBOL FOR SPACE U+2420 (␠) could be used to represent space characters in examples where typesetting might make the presence (or number) of spaces difficult to discern.

**Comment by JJ** [comment]
That would clash with another requirement: that examples should be
cut&pasteable... Don't know in this case. It's not a pasteable example...

**Comment by coke** [comment]
```
$ ack -Q 'foo+' doc
doc/Language/regexes.pod6
1534:I<after> a quantifier acts as normal significant whitespace; e.g., "C<foo+>"
1535:becomes C«foo+ <.ws>».
```

It looks like there's no space in the source.
