### ISSUE TITLE
`lookup` ClassHOW method description is wrong

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#1837]
https://docs.perl6.org/type/Metamodel::ClassHOW#method_lookup - it says

>Returns the first matching Method with the provided name or Nil.

But in fact:
```
> Str.^lookup('foo')
(Mu)
```
Not sure if it's a regression though, but anyway worth checking.

**Comment by JJ** [comment]
Nil should be Mu, right?

**Comment by Altai-man** [comment]
Well, I see that implementation returns `nqp::null()` that resolves into `Mu`. But that's just observable behavior. I do not see any notes about Meta Object Protocol in language spec though. I see notes about introspection at http://design.perl6.org/S12.html#Introspection however `lookup` does not defined there precisely. And tests at https://github.com/perl6/roast/blob/eebd95faad80e571e068d81cbf59994faa0c613e/S12-introspection/meta-class.t#L72-L77 only test for valid behavior, but not an incorrect case. :/

We probably need to ping core members on irc to clarify what behavior is expected.

**Comment by zoffixznet** [comment]
Fix got split up into two commits accidentally; fixed in https://github.com/perl6/doc/commit/63b6c5b781 and https://github.com/perl6/doc/commit/07c4c7b3c6b34e71445f4c0b4b648374f4cbd52d
