### ISSUE TITLE
Should we stop using .xhtml?

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1845]
Which might cause the page not to render if there's a single error, and switch to HTML? https://docs.perl6.org/perl6.xhtml
There's an error in the HTML, 
![screenshot from 2018-03-15 14 44 50](https://user-images.githubusercontent.com/500/37467039-7e8d0ff0-285f-11e8-9871-a44310a1e692.png)
as well as some failing links #1825

**Comment by AlexDaniel** [comment]
I guess so, yeah. It was an interesting idea but in the long run there's probably no need for it to be xhtml.

**Comment by JJ** [comment]
Sorry, closed by mistake.

**Comment by Tyil** [comment]
The `Content-Type` is set to `text/html`, so browsers will consider it as regular HTML instead of XHTML regardless of the suffix. Browsers therefore should render it, even if it's invalid XHTML. Regardless, I'd vote for going with the new standard of HTML5 if possible.

**Comment by JJ** [comment]
There are very few, if any, links to this page outside this site. But I guess it can stay there, no harm. Only it would be interesting to add, at the top, a link to the new page. Can someone do that? Maybe @moritz ?
