### ISSUE TITLE
MODULE is documented as compile time but seems to by dynamic

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#185]
$ perl6
     > say $?MODULE
       ===SORRY!=== Error while compiling <unknown file>
       Variable '$?MODULE' is not declared
      at <unknown file>:1
      ------> say ⏏$?MODULE
     > say $*MODULE 
     Dynamic variable $*MODULE not found
     in block <unit> at <unknown file>:1

**Comment by jonathanstowe** [comment]
I think it may be NYI rather than mis-documented

**Comment by teodozjan** [comment]
$*MODULE seems to be something else than real variable(it is empty while while inside module). Closing
