### ISSUE TITLE
FAQ: "how most people enter Unicode stuff"

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1850]
Seems a frequentish question, and some people have some pretty wild ideas, like thinking we copy-paste all the Unicode ops from some website each time we need them.

Was asked just now on r/perl6: https://www.reddit.com/r/perl6/comments/85bn0b/unicode_operators/

And was asked earlier on this thread too: https://www.reddit.com/r/perl6/comments/6v63wv/201734_going_weekly_changes_in_and_around_perl_6/

**Comment by AlexDaniel** [comment]
Another relevant thread: https://www.reddit.com/r/perl6/comments/5gwurz/perl_6_advent_day_7_set_in_your_ways_perl_6s/daxzai5/?context=3

**Comment by AlexDaniel** [comment]
Maybe the A for that Q should be just “There are better ways to enter special characters”, with a link to https://docs.perl6.org/language/unicode_entry

That page, however, does not mention:
* dead keys
* custom keyboard layouts
* using default ibus features (I think if you write むげん you will be offered 無限 and ∞ as options)

Also maybe:
* templates in text editors
* potentially features of specific language modes in text editors (e.g. perl6-mode in emacs can have a feature that will automatically offer non-ascii variants)
* Perl6::Tidy doing the conversion automatically: https://github.com/drforr/perl6-Perl6-Tidy/issues/3

I guess that's a separate issue, so feel free to move that comment.

**Comment by JJ** [comment]
Editors like emacs that allow you to type the name of the character...

**Comment by titsuki** [comment]
IMHO, if there is any official cheat-sheet-like page that we can copy unicode characters from it, it is useful.

**Comment by Tyil** [comment]
@titsuki This list exists [on the docs](https://docs.perl6.org/language/unicode_ascii#Other_acceptable_single_codepoints).

@JJ Vim has the vim-perl plugin, and Atom also has a package to convert the ascii-based ops to their unicode equivalent on the fly.

**Comment by titsuki** [comment]
@Tyil Thanks, I didn't notice that page, then it should have a link to this FAQ.

**Comment by JJ** [comment]
I'm closing the original issue, if you think the Unicode entry page should be improved, please post another issue.
