### ISSUE TITLE
?? !! is pointing to the wrong place

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1851]
It points to "index", which mentions it at the end of the examples. https://docs.perl6.org/routine/??%20!!
Is that correct?

**Comment by AlexDaniel** [comment]
Yes, of course not.

I think it's documented here: https://docs.perl6.org/language/operators#infix_??_!!

**Comment by JJ** [comment]
I don't know if this is related to #561 or to something completely
different...

**Comment by cfa** [comment]
The link is broken because the ?s need to be escaped; compare

[https://docs.perl6.org/routine/??%20!!](https://docs.perl6.org/routine/??%20!!)

with

[https://docs.perl6.org/routine/%3F%3F%20!!](https://docs.perl6.org/routine/%3F%3F%20!!).

**Comment by JJ** [comment]
The problem is that it's broken on the index... So we'll have to see how that's generated and how it affects everything else.

**Comment by JJ** [comment]
Now ?? !! has disappeared from the index, so I'm reopening the issue. Related #1894

**Comment by AlexDaniel** [comment]
Wait, what's “⁇ ‼”? These are unicode characters, and we actually had support for them for a little bit (but it never ended up being in any release). But why are these characters used in the docs?

**Comment by JJ** [comment]
They're not supported any more? I thought they were...

**Comment by AlexDaniel** [comment]
Wait, but… it's much better now of course, but it's still not linked as an “infix” op, and so it doesn't even appear in this list: https://docs.perl6.org/routine-operator.html

Note that ff operator that is documented right below it works correctly (can be searched for and exists in the list of ops).

**Comment by JJ** [comment]
And well in its way of becoming the most closes issue in all of GitHub
history...
