### ISSUE TITLE
Document %a = %a, %b and %a ,= %b (and link ,= to that section for convenience)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1855]
I grepped the docs and couldn't fine any place where we show something like this:

```perl6
my %a = :11a, :22b;
%a = %a, :33x;
say %a # OUTPUT: «{a => 11, b => 22, x => 33}␤»
```

Also, this can be written using `,=`:
```perl6
my %a = :11a, :22b;
%a ,= :33x;
say %a # OUTPUT: «{a => 11, b => 22, x => 33}␤»
```

`,=` is of course not specific to hashes and behaves like any other op combined with `=`. However, it seems like `,=` is particularly useful for hashes, and people who stumble upon it in code should be able to find this section quickly.

**Comment by cfa** [comment]
It might be worth adding examples using the hash contextualiser too,

```perl6
say %(%a, :33x);  # OUTPUT: «{a => 11, b => 22, x => 33}␤»
say  (%a, :33x);  # OUTPUT: «({a => 11, b => 22} x => 33)␤»
```
