### ISSUE TITLE
xt test for links that are not links

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1856]
https://docs.perl6.org/language/modules.html has links that were not actual `<a>` tags in the produced html.

For example:

- [x] `https://spdx.org/licenses/`
- [x] `https://design.perl6.org/S22.html#license`

**Comment by AlexDaniel** [comment]
Cool! Thanks, @cfa!

By any chance, can we have a test for this?

**Comment by cfa** [comment]
Good idea; shall we re-open this or create a new issue?

**Comment by AlexDaniel** [comment]
Changed the title to repurpose this ticket. If you close something with an idea that a new ticket should be opened, open it yourself. The OP can be under a bus after you close something, no guarantee that the expected action will be taken. Don't just close issues.

**Comment by JJ** [comment]
There are now 21 errors, but most of them are links that are split over two lines. One of them, at least, is a Pod error... and come to think of it, there's no Pod6 checking, right?

**Comment by coke** [comment]
Pod checking: https://github.com/perl6/doc/blob/master/t/pod-valid.t

**Comment by JJ** [comment]
Yep, I realized later that the problem was with processing single lines.

**Comment by coke** [comment]
Re-opening issue until the tests pass.

**Comment by coke** [comment]
I see glossary has:

```
    =begin code :lang<text>
    [15:46:40] <+dalek> doc: 2819f25 | lizmat++ | doc/Language/glossary.pod:
    [15:46:40] <+dalek> doc: Add stubs for stuff inside the glossary already
    [15:46:40] <+dalek> doc: review: https://github.com/perl6/doc/commit/2819f250
    =end code
```
And this is getting caught as a failure. But this is code output; it's not plain text. Test needs to be updated to skip things in code blocks, I think.

**Comment by JJ** [comment]
Right. Will do
