### ISSUE TITLE
Searching for `$` doesn't lead user to doc about it

### ISSUE THREAD

**Issue by raiph** [perl6/doc#1861]
I saw ["I tried to find the " $ " in the documentation but couldn't find it."](https://stackoverflow.com/questions/49375773/perl-6-curried-function-hangs#comment85753649_49376083).

I think the closest the docs currently come to what that user needed is [The $ Variable](https://docs.perl6.org/language/variables#The_$_Variable). (It looks like that section could do with a mention of how `$` can be used to mark an unused parameter. Same goes for doc for `@` and `%`.)

I tried typing `$` in the search box. It does not have an entry that links to the doc section I just linked.

(There is an entry toward the end of the large menu that says `$ (variable)`. But that turns out to be an entry for `$<named> (variable)`. You can see this if you use the cursor keys to select it from the menu. The entry is both incorrectly displayed in the menu *and* has a link that lands it at the right page but at the top rather than at the right place for the *Named Attributes* section that discusses `$<named>` variables. I searched for tickets matching `$<named>` and found none. Do we need to create a further one or two new issues to cover these `$<named>` problems?)

Finally, I can also imagine folk typing `$` to get help on `$` as a sigil, and that doesn't seem to be available either, beyond the item contextualiser stuff. I'd expect a link to [Sigils](https://docs.perl6.org/language/variables#Sigils) as well as a link to *The $ variable*.

**Comment by JJ** [comment]
In fact, there should be an entry for $ (sigil)

```
=head1 Sigils
X<|$ (sigil),@ (sigil),% (sigil),& (sigil)>
```
But I don't think it's working, it goes to this 
```
{ category: "Reference", value: "& (sigil) ($ (sigil)@ (sigil)% (sigil))",
                    url: " /language/variables#index-entry-%24_%28sigil%29_%40_%28sigil%29_%2525_%28sigil%29_%26_%28sigil%29" }
```

I'll see what I can do.

**Comment by JJ** [comment]
As a matter of fact, there is a reference for a `$ variable` in the index, but it's actually an error, because it's caused by this:
```
{ category: "Reference", value: "$<named> (variable)",
                    url: " /language/variables#index-entry-variable_%24%3Cnamed%3E-variable_%2525%28%29-Named_Attributes" }
```
So it'll have to be dealt with too...
