### ISSUE TITLE
is repr('...') needs documentation

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1863]
None of the `repr` representation specifiers, as in « class Foo <b>is repr('...')</b> {  } » seem to be documented.  

Typing "repr" or "is" into the search box at https://docs.perl6.org/ does not bring up anything relevant.

**Comment by jnthn** [comment]
I'd suggest documenting the existence of the following ones:

* `P6opaque` (the default)
* `CStruct`
* `CPPStruct`
* `CPointer`
* `CUnion`
* `Uninstantiable*

And noting that all others that may exist are considered implementation-defined and subject to change at any time, without notice. The rest are of little interest to the Perl 6 language user anyway (and can only really be used in any way in conjunction with with `nqp::ops`, which are not part of the Perl 6 language).

**Comment by JJ** [comment]
Can you point to examples of usage of those? Or roast tests?

**Comment by jnthn** [comment]
`CStruct`, `CUnion`, and `CPointer` are all already in the [NativeCall](https://docs.perl6.org/language/nativecall#Structs) docs. `CPPStruct` isn't mentioned, but is linked to.

The test file `S12-meta/primitives.t` mentions `Uninstantiable`.

The test file `S12-introspection/meta-class.t` asserts that the default representation is `P6opaque`.

**Comment by jimav** [comment]
But none of those are indexed -- that is, typing "repr" into the search box at https://docs.perl6.org/ gives no hits.

The repr syntax, at least, should be documented somewhere.  Can this be indexed so it is findable?
Wherever 'repr' is described, it might be enough to link to all the different places that the various options are described.    Also, it should say what 'repr' actucally does, that is, what is the mechanism that it invokes.
