### ISSUE TITLE
LTA example of using The $ Variable more than once

### ISSUE THREAD

**Issue by jimav** [perl6/doc#1864]
ref: https://docs.perl6.org/language/variables#The_$_Variable

The fourth example in this section says
> "If you need to use the value of $ more than once in a scope, it should be copied to a new variable."

but the example code which follows doesn't actually show doing that (it shows `given ++$ { ... }` which is only a single usage.)

Also, _copying_ $ only allows reading the value more than once, not updating it.   A more general solution is to _bind_ another variable to $.  Then multiple reads & writes can be done.

Suggestion: Replace the above-quoted text and the example below it with the following:

<i>If you need to reference the same $ variable more than once, bind another variable to it (in this example it would be more straightforward to just declare `state $x` and not use the magical `$` variable):</i>

<pre>
sub foo () {
  my $x := $;
  $x++;
  say $x;
  $x = $x + 1;
}

foo() for ^3;
# OUTPUT: «1␤3␤5␤»
</pre>

(QUESTION: Is there a realistic use case for multiple-references to `$`?  That is, is there a case where `$` must be used instead of a regular `state $foo` and/or where the former is more clear and understandable?)

<br/>
<br/>

Relatedly, the examples of using the `@` and `%` state variables use the phrase "copy the value" when actually a reference is being copied.  For beginners this may be confusing.  For example, at https://docs.perl6.org/language/variables#The_@_Variable it says to "copy the value" like this:
<pre>
sub foo($x) {
    my $v = @;
    $v[$x] = $x;
    say $v;
}
</pre>
But the `$v = @` does not actually copy the array, but creates a scalar container containing a reference to the array, er, at least I think that's the correct language (see, it's confusing!)

To avoid irrelevant distractions, an example using an _explicit_ bind might be less confusing:
<pre>
sub foo($x) {
    my @v := @;
    @v[$x] = $x;
    say @v;
}
foo($_) for ^3;
</pre>

**Comment by jimav** [comment]
Upon further reflection, I wonder is it _ever_ good coding style to use `$`, `@`, or `%`  if multiple references are needed?  

The necessity of making copies, scalar references or binding other variables to the magic variable adds notheing but obfuscating complexity to my (still beginner's) eye; declaring regular `state $foo` instead would produce simpler, more readable code when multiple references are involved.

Or such is my conjecture.    

If y'all agree with this, then whole long section showing examples of multiple references could be cut and replaced with the following:     

<i>Each reference to `$`, `@`, and `%` within a lexical scope is in effect a **separate** variable.  If you need to refer to such a state variable more than once, it's probably better to declare a regular `state $foo` rather than use these magical variable names.   But if you really want to, you can bind (with `:=`) another variable to the magic variable and reference it multiple times, or assign `@` and `%` to a $scalar to get a reference to the container.</i>

(Please don't copy the above text without expert review)

If, on the contrary, using `$` etc. is required or compelling, even when multiple refs are needed, then motivating examples would be helpful.

**Comment by JJ** [comment]
It's probably not good coding style, as you say. But that could go to the "traps" section.
