### ISSUE TITLE
mkdir routine not shown in doc search

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#1867]

**Comment by JJ** [comment]
Could that be a temporary failure? It does now
https://docs.perl6.org/routine/mkdir

**Comment by tbrowder** [comment]
Yes, you can find it under “Method” but it doesn’t show under “Routine” in the search results.

**Comment by JJ** [comment]
Ah, the old #1410 and #638. In this case, it can be fixed, I guess.

**Comment by JJ** [comment]
Also related: #1800

**Comment by JJ** [comment]
Well, we are in a bit of a pickle here. Right now, `mkdir` as routine

    =head2 routine mkdir 

If I add an indexing entry `X<|mkdir (routine)> it goes to reference. If I change `routine` to `sub` it goes to, well, `sub`. Right now it's listed under the `method` category in the search menu and the `routine` directory in the site. Anyway, `mkdir` is kind of a drop in the water. Routine, method and even sub are used throughout the documentation indistinctly, see #638. Everything is processed with `htmlify.p6`, which is the subject of #1823. So I wonder if I should just drop everything, do #1823 and be done with...

**Comment by tbrowder** [comment]
@JJ, whatever you do is fine with me. I just wanted it known searching for routine mkdir was a little confusing.

**Comment by JJ** [comment]
I'm kind of getting the hang of it. But it will need a (few dozen) hours to get it right. And besides, before that, it would be better to spin off all functionality so that it can be tested independently and we don't break anything in the process.
