### ISSUE TITLE
Padding around huge graphs

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1868]
Take a look at this page: https://docs.perl6.org/type/Metamodel::ClassHOW#Type_Graph

There's some extra space before and after the graph. It's like if it was too tall.

Screenshot:

![image](https://user-images.githubusercontent.com/5507503/37878781-e11aca80-3076-11e8-85de-8abf95564f82.png)

**Comment by JJ** [comment]
Right... We'll have to play with neato...

**Comment by AlexDaniel** [comment]
It's not a graphviz issue, it's how browsers render svg images with `max-width: 100%`. Just adding `height: auto;` does the trick (although makes no sense).

**Comment by JJ** [comment]
It stopped worrying about what made sense in CSS like 10 years ago. Can you
fix that?
