### ISSUE TITLE
"Type Constraints" section on containers page contains incorrect info

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1870]
On https://docs.perl6.org/language/containers#Type_Constraints  the prose says you can rebind to a variable and remove constraint, yet the very example shown in that section shows that you get an error if you try to do that. Also, it says *"Scalar containers have Any contraint"* by default, but that's not true, as scalar variables default to Mu.

~~Also, I'm not sure, but I don't think the "constraint is a property of the container" part is true at all. 'cause `my Int \x` and `my @foo := 1, 2, 3` have type checks, yet there are no containers involved.~~

IRC: https://irclog.perlgeek.de/perl6/2018-03-26#i_15968146

**Comment by zoffixznet** [comment]
Some more from IRC: https://irclog.perlgeek.de/perl6/2018-03-26#i_15968326

```
19:48 | jnthn | The bind operator code-gens a type check
19:50 | jnthn | That's, I believe, the only place the type information is retained at the binding level
19:50 | jnthn | Variables don't really exist by runtime. Certainly not in the same way containers do
```

**Comment by JJ** [comment]
Could #1217 be related?
