### ISSUE TITLE
Improve documentation on NativeCall

### ISSUE THREAD

**Issue by nxadm** [perl6/doc#1879]
To me, the doc of NativeCall helps you to quickly create an hello world application, but from beyond there you're on your own specially when dealing with more complex datatypes. Maybe we need an "advanced" page as well.

**Comment by JJ** [comment]
We do have a few of requests of this kind, latest one #1376. Also #1513. Thanks anyways, we do need to move on this.

**Comment by nxadm** [comment]
My excuses I missed those.

C.

**Comment by JJ** [comment]
2018-03-29 10:32 GMT+02:00 nxadm <notifications@github.com>:

> My excuses I missed those.
>

No problem at all. It's a reminder we should do something about that :-).
Thanks.

**Comment by JJ** [comment]
See also #1902

**Comment by JJ** [comment]
:loudspeaker: Can you please check #1513 and see if most of your concerns are addressed? If they aren't, please create a checklist and add it here.
