### ISSUE TITLE
POD6 seems not to be interpreted in some pages

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1886]
At least in [this one](https://docs.perl6.org/language/variables#index-entry-%24%2ATHREAD). `L<>` links appear as such...

**Comment by cfa** [comment]
Have you found any other instances (and is this issue re: table contents being rendered literally)?

**Comment by JJ** [comment]
Related to perl6/Pod-To-HTML#17, which has been there for some time...

**Comment by JJ** [comment]
Related: #759

**Comment by JJ** [comment]
Not sure if this is still a problem...

**Comment by JJ** [comment]
Closing this also. It was apparently an external problem that was fixed. If it's still there, please provide an example of where it's not working now.
