### ISSUE TITLE
'andthen', 'orelse', defined-or (//) missing from search

### ISSUE THREAD

**Issue by avuserow** [perl6/doc#1893]

**Comment by JJ** [comment]
There's only [the quote construct](https://docs.perl6.org/syntax/$SOLIDUS%20$SOLIDUS).

**Comment by JJ** [comment]
`notandthen` is also missing.

**Comment by JJ** [comment]
Actually, most operators in operators.pod6 are not indexed. Apparently, `X<>` is not used in the usual way

**Comment by JJ** [comment]
The indexing terms added do not seem to be working.
