### ISSUE TITLE
Some pages are not indexed. 

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1894]
From #1893 I've realized the terms indexed there are not included in the search file for some reason. There are quite a few of them. I'm not sure why this happens, or since when it's happening. It's related to htmlify.p6 for sure, but... 
At least, these pages are not indexed:
* operators
* glossary
* classtut
* typesystem
Please edit this to add some others when you find something is missing.

**Comment by JJ** [comment]
This is the kind of code I mean

    X<Zip operator>

does not create a `Zip operator` entry in the index, for instance.

**Comment by JJ** [comment]
I'm checking other lines, which are theoretically correct, which have the same problem...

**Comment by nxadm** [comment]
The search part of the following issue is relate, the naming (>> vs >>.) isn't:
#562

**Comment by JJ** [comment]
Many entries in many pages are not indexed, including operators.pod6, classtut.pod6, and others...

**Comment by zoffixznet** [comment]
FWIW, if I delete all but one files in doc/Type/* and doc/Language and leave doc/Language/operators in and then stick a print after `find-definitions` ( https://github.com/perl6/doc/blob/11e7bc900a5fb825345b3e377844a6c5b00918cb/htmlify.p6#L319 ) that print never occurs, as if `find-definitions` never returns.

If I comment out [this part](https://github.com/perl6/doc/blob/11e7bc900a5fb825345b3e377844a6c5b00918cb/htmlify.p6#L603-L610) inside `find-definitions` and everything that depends on it, then the routine returns and indices get printed.

The problematic bit seems to be `$origins`. If I try to dump it, I get an infinilooping dump.

**Comment by JJ** [comment]
I *really* don't like to be working with the dynamic `$*DR` variable. It's just a global variable in disguise. Not clear what's happening where. It's my first target for refactoring.

**Comment by JJ** [comment]
I don't know if they are increasing or what... I keep finding more and more.

**Comment by coke** [comment]
This may be related to #1938 - some pages are not getting processed, and the errors are being hidden by the use of Promise.allof

**Comment by JJ** [comment]
We would need to do1932. When it fails, it does so silently.
