### ISSUE TITLE
Perl 6 docs do not describe default behaviour of sort() on Hash

### ISSUE THREAD

**Issue by Bowlslaw** [perl6/doc#1896]
IRC log: https://irclog.perlgeek.de/perl6/2018-04-05#i_16010857

(3:27:25 PM) Bowlslaw: ah cool, wonder why they have that in the example
(3:27:34 PM) Zoffix: Who?
(3:28:03 PM) Bowlslaw: https://docs.perl6.org/type/Hash#Looping_over_hash_keys_and_values
(3:29:15 PM) Zoffix: Guess the author of that part of the docs didn't know of the default sort
(3:29:53 PM) Zoffix: It's not even documented that that's its behaviour
(3:29:55 PM) Bowlslaw: I think it's better to be explicity when first learning, but the default sort is pretty common-sense
(3:30:06 PM) Zoffix: s: %(), 'sort', \()
(3:30:07 PM) SourceBaby: Zoffix, Sauce is at https://github.com/rakudo/rakudo/blob/7faf431fa/src/core/Map.pm6#L79
(3:30:53 PM) Zoffix: b2gills: are you sure it sorts by value too? Glancing at that code, looks like only the key
(3:30:57 PM) mcmillhj left the room (quit: Ping timeout: 260 seconds).
(3:31:19 PM) El_Che: Bowlslaw: can you create a ticket with the remark? JJMerelo is working on the docs and he appreciates issues like that
(3:31:28 PM) Zoffix: Oh, you can't have more than one key that are the same, dugh
(3:31:41 PM) Bowlslaw: I changed it in my code and i have the exact same result
El_Che eliasr 
(3:32:17 PM) Bowlslaw: El_Che: sure, i'd be happy to. Should I mention the default behaviour of sort and how it's not mentioned in the doc...?
(3:32:33 PM) Zoffix: m: (:42a, :100a, :10a, :50a, :60a).sort.say
(3:32:34 PM) camelia: rakudo-moar 7faf431fa: OUTPUT: «(a => 10 a => 42 a => 50 a => 60 a => 100)␤»
(3:32:38 PM) Zoffix: neat
(3:32:47 PM) El_Che: pretty much a copy paste of the conversation will do, I think :)

**Comment by zoffixznet** [comment]
Oh, my bad, I guess Any.sort *does* say that "cmp" operator will be used.
