### ISSUE TITLE
Semantics of HyperSeq/RaceSeq appear to be undocumented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1897]
Don't see the behaviour of calls on HyperSeq/RaceSeq documented anywhere

All I know about is this spreadsheet jnthn++ prepared before implementing them:
https://docs.google.com/spreadsheets/d/1kpSb8LoskHSbM1FQvWdQ269rlRkU8vh5A_ElpN3Qay4/edit#gid=0

IMO, it makes sense to just document those two types and list all the methods and how they behave, but I vaguely recall jnthn saying Hyper/RaceSeqs are implementation detail and shouldn't be documented or something? I forget.

**Comment by JJ** [comment]
The other reference to HyperSeq is in #1803. It might have been discussed in general, though.

**Comment by jnthn** [comment]
`HyperSeq` and `RaceSeq` themselves are user-facing. It's the hyper batcher and so forth roles that I wish to keep implementation-defined for now.

Documenting the semantics of operations of a `HyperSeq` and `RaceSeq` makes sense. The spreadsheet is an idea of where we want to end up, but of course only a fraction of that is implemented now (`map`, `grep`), so it's probably best just to implement ones that are actually done.
