### ISSUE TITLE
proto link is broken 

### ISSUE THREAD

**Issue by Gavlooth** [perl6/doc#1899]
the link https://docs.perl6.org/routine/proto is broken (404)

**Comment by fluca1978** [comment]
Should be better to indicate from which page you got the broken link. I found the only grammars page with a broken link.

**Comment by JJ** [comment]
Please don't close it before waiting for the answer.

**Comment by JJ** [comment]
Please feel free to reopen if you got the link somewhere else.

**Comment by Gavlooth** [comment]
The lis is under the section Proto regexes in https://docs.perl6.org/language/grammars#Methods_in_Grammar
