### ISSUE TITLE
Proc::Async.bind-stdout / Proc::Async.bind-stderr could use examples

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1901]
https://docs.perl6.org/type/Proc::Async#method_bind-stdout

The docs say I can give it handle to bind, so I tried:

```perl6
my ($out, $err) = IO::Handle.new, IO::Handle.new;
.bind-stdout: $out;
.bind-stderr: $err;
```

But that just gives me "get native descriptor requires an object with REPR MVMOSHandle (got Scalar with REPR P6opaque)"

So how do I do this whole binding thing?

**Comment by zoffixznet** [comment]
For record, the error was 'cause I needed to have *opened* IO::Handles

**Comment by JJ** [comment]
Closed by mistake, sorry.

**Comment by JJ** [comment]
I'm opening this again. The examples are clear enough and illustrative of the syntax, but it is not so clear how to actually interact with the opened pipe. I [have posted this question in StackOverflow](https://stackoverflow.com/questions/50313779/reading-from-a-bound-pipe-using-procasync), which I add here for future reference.
