### ISSUE TITLE
Description for all ticket labels

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1909]
We have descriptions for some labels here: https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#reporting-bugs

But now github conveniently allows label descriptions: https://github.com/perl6/doc/labels

So let's remove that stuff from CONTRIBUTING.md to make it simpler, and just use the native github feature to achieve the same (and arguably better) result.

**Comment by AlexDaniel** [comment]
Also someone renamed `meta` to `style`, and I think that's wrong.

**Comment by JJ** [comment]
I can't do much about the renaming of meta. If you feel it's an issue, open a separate one and let's discuss it out.

**Comment by coke** [comment]
the commit attached to this lists LHF which is now gone.

I would recommend removing all the descriptions and just linking to https://github.com/perl6/doc/labels ; there's no point in maintaining 2 copies of this list.

**Comment by JJ** [comment]
I don't think "good first issue" is the same as "LHF". But LHF has been
attached to some issues that have been hanging low for a long time, which
makes no sense. So I guess linking is probably better.

**Comment by AlexDaniel** [comment]
There was a discussion on this here: https://irclog.perlgeek.de/perl6/2018-04-09#i_16026272

Basically, LHF is no longer a thing in this repo.
