### ISSUE TITLE
Duplicated index entries

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1912]
When doing `make`

- [x] found duplicate index entry is (inheritance) at #i45 #i679
- [x] found duplicate index entry :{} at #i853 #i855
- [x] found duplicate index entry compunit at #i276 #i277 #i278
- [x] found duplicate index entry declarator regex at #i258 #i594
- [x] found duplicate index entry increment operator at #i361 #i365
- [x] found duplicate index entry control flow at #i53 #i54 #i55 #i56 #i58 #i60 #i61 #i65 #i68 #i69 #i71 #i74 #i75 #i76 #i77 #i78 #i79 #i80 #i81
- [x] found duplicate index entry decrement operator at #i363 #i366
- [x] found duplicate index entry compunit at #i273 #i274 #i275
- [x] found duplicate index entry sym at #i260 #i263
- [x] found duplicate index entry ++ at #i360 #i364
- [x] found duplicate index entry whenever at #i50 #i51
- [x] found duplicate index entry NFG at #i214 #i851
- [x] found duplicate index entry «=» at #i430 #i765
- [x] found duplicate index entry ∅ at #i628 #i733
- [x] found duplicate index entry prefix &amp; at #i129 #i871
- [x] found duplicate index entry $*USAGE at #i147 #i836
- [x] found duplicate index entry invocant at #i39 #i498

Among the gaggle of errors and warnings that pod2onebigpage emits. That would need a separate issue, or just point to #1823. 
This error is also found in #1910

**Comment by JJ** [comment]
For instance, the first:
```
$ grep X doc/*/*.pod6 | grep inheritance
doc/Language/classtut.pod6:X<|is (inheritance)>
doc/Language/typesystem.pod6:The L<trait|/type/Sub#Traits> X<C<is>|is (inheritance)> accepts a type object to be
```

There should be some test for this, I guess...

**Comment by W4anD0eR96** [comment]
Eliminates `:{}` duplicate 0a92a89fd744368828d6766c1d4f37c6370a76ac

**Comment by JJ** [comment]
These are the duplicated index entries right now:
```
found duplicate index entry say (Basics) at #i27 #i28
found duplicate index entry Python at #i43 #i44 #i45 #i46 #i47 #i48 #i49
found duplicate index entry «=» at #i404 #i856
found duplicate index entry declarator at #i325 #i326
found duplicate index entry »=« at #i403 #i857
found duplicate index entry whenever at #i99 #i100
found duplicate index entry $*USAGE at #i94 #i927
```

Besides, the message about duplicated entries is cryptic. I have no idea where they are...

**Comment by JJ** [comment]
Please take this into account @antoniogamiz when working with the new Perl6::Documentable #1937

**Comment by antoniogamiz** [comment]
Well, I have been investigating and it looks like the ``#ixxx` corresponds to the position of that reference in the general TOC of BigPage. 

I have made a script to find them with a clearer output => https://gist.github.com/antoniogamiz/8b628a274954adb5f364322615a159b5. 

This is the output:

~~~
found duplicates of $*USAGE at variables variables create-cli
found duplicates of »=« at unicode_ascii operators
found duplicates of $*COLLATION at variables Any
found duplicates of Python at py-nutshell py-nutshell py-nutshell py-nutshell py-nutshell py-nutshell py-nutshell
found duplicates of PERL6LIB at 5to6-nutshell 03-environment-variables
found duplicates of say (Basics) at 101-basics 101-basics
found duplicates of declarator at functions functions
found duplicates of «=» at unicode_ascii operators
~~~

I will add it as a test in the site.

**Comment by Altai-man** [comment]
@coke this might be interesting, I guess we can just copy the script to the repo `xt` and close the ticket?

**Comment by coke** [comment]
Probably requires slightly more updates than that, but yes, let's add it to xt/
