### ISSUE TITLE
spurt method on IO::Handle not indexed

### ISSUE THREAD

**Issue by coke** [perl6/doc#1917]
Search finds the spurt sub, but not the method.

**Comment by zoffixznet** [comment]
Seems to work fine for me:
![image](https://user-images.githubusercontent.com/5747918/38670269-4c3baee0-3e16-11e8-91a2-5ee0d1b6cc5f.png)

![image](https://user-images.githubusercontent.com/5747918/38670244-3add9320-3e16-11e8-9d03-23af0a7dc915.png)

**Comment by JJ** [comment]
Only the `sub spurt` is indexed:
```
{ category: "Routine", value: "spurt",
                    url: " /routine/spurt" }
```
They methods from the two classes are just attached in the same page. The same happens to `slurp`. Is that what you mean?

**Comment by coke** [comment]
When I did this search yesterday, I swear the routine result didn't include the method variants, but yes, it's there now, it's fine. Assuming it was just user error on my part.

So my only issue remaining is just a vague one about "routine" vs. sub/method/whatever, but that's a thought for another ticket.
