### ISSUE TITLE
Standardize Pod name

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1923]
Let's try and call it `Pod 6` everywhere, including the non-breaking space before the 6

**Comment by JJ** [comment]
Also #1948. Use it in the page that describes it.

**Comment by AlexDaniel** [comment]
From my comment [here](https://github.com/perl6/doc/issues/1948#issuecomment-383308089):

> Uh, actually, maybe not yet. At least not without a deep discussion.
>
> Some *random* thoughts:
>
> The thing is that we will have [an alias](https://github.com/perl6/6.d-prep/tree/master/TODO#language-extended-naming) eventually. Let's say it'll be “AAA”. With current naming of pod, it'll then be “Perl 6 Pod” and “AAA Pod” depending on context. Yes, two different names for the same thing, but that's what we want (sort of).
>
> So if we rename it to “Pod 6”, then I guess it'll stay “Pod 6” in both cases, which is nice… But then, what is “6”?
>
> I guess “pod6” will work nicely with “6lang”, but then why not “6pod”? :)

**Comment by AlexDaniel** [comment]
> But we're using Pod 6 pretty much everywhere else.

Well, maybe that's not right? I don't know.

**Comment by AlexDaniel** [comment]
Well, the point is that maybe we should be calling it “Perl 6 Pod” for now.

**Comment by AlexDaniel** [comment]
(because that leaves enough room for the upcoming alias)

**Comment by JJ** [comment]
I'd like to hear more opinions about this. Even if we leave the page title that way, it's kind of cumbersome to say Perl 6 Pod every time you mention it on the documents. We can clarify in the documentation that when we say "Pod 6" we actually mean "Perl 6 Pod" and then change that last thing to whatever, when (or if) that change happens.

**Comment by JJ** [comment]
This probably should remain open.

**Comment by JJ** [comment]
So will everyone agree on Perl 6 Pod?

**Comment by Kaiepi** [comment]
I'm ok with Perl 6 Pod

**Comment by JJ** [comment]
Should we open this back now? Pod6 or Pod(non-breaking-spce)6?

**Comment by AlexDaniel** [comment]
[This is related](https://github.com/perl6/problem-solving/issues/64), but there I propose some crazy changes.

**Comment by AlexDaniel** [comment]
Also, I think it is universally POD6 right now and nobody writes it with a nbsp, so there's no point in trying to force that. But as I mentioned, maybe the “pod” part of the name needs to be rethought too.
