### ISSUE TITLE
IO::Socket::INET.accept is vague

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1929]
[It says](https://docs.perl6.org/type/IO::Socket::INET.html#method_accept) *"In listen/server mode, waits for a new incoming connection, and returns it."* ... what is "it"? What sort of object is "it"?

**Comment by fluca1978** [comment]
Sorry, I did not realize the `JJ TPF Grant` label, repone it in case.
Why not assign the issue instead of labelling?
