### ISSUE TITLE
move p5 question from FAQ to p5 specific pages

### ISSUE THREAD

**Issue by coke** [perl6/doc#1934]
In the FAQ:

Why is wantarray or want gone? Can I return different things in different contexts?

**Comment by JJ** [comment]
We could also split the page and create a p5 specific FAQ...

**Comment by nxadm** [comment]
It's place in the language specific pages (like https://docs.perl6.org/language/5to6-perlfunc). The only reason it would deserve a FAQ entry would be in a security contexts, but I woudn't bother to single that out.
