### ISSUE TITLE
How does search logic in htmlify.p6 works?

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1935]
Let's take a look at https://docs.perl6.org/js/search.js , we generate it through https://github.com/perl6/doc/blob/master/htmlify.p6 https://github.com/perl6/doc/blob/master/template/search_template.js

now we see some `X<>` tag parsing beyond contributors' expectation, make duplicate entries or invalid entry. Besides, `category: "Reference"` occurs unexpectedly and url form like `url: " /language/regexes#index-entry-regex__%3C%7Cw%3E-regex__%3C%21%7Cw%3E-%3C%7Cw%3E_and_%3C%21%7Cw%3E%2C_word_boundary"` make `L<>` refer ugly as well as incomprehensible

since htmlify.p6 was given to birth so long ago, I cannot understand a number of its design and logic, so can anybody please explain/talk about  how search logic in htmlify.p6 works? Maybe about `write-search-file()` and subroutines it calls.

Co #1823

**Comment by JJ** [comment]
I'd really want to sit down one day and work on this. Some pages are not indexed now, some index yield errors in HTMLify... I don't know if it's worth the while to patch it or just try and find out the logic and rewrite it from scratch.

**Comment by W4anD0eR96** [comment]
This is a time when I start playing Perl 6 and learn a lot through docs.perl6.org using search method, and I'd like to assume that such a experience will reappear many times, so improving search experience is important from where I stand.

**Comment by JJ** [comment]
I don't see an easy way to solve this issue. If it's just a request for comments, I think it's gathered all the comments it's ever gonna get. Maybe you can transform it into an actionable suggestion, or if you think your question has been answered, we can just close it.

**Comment by W4anD0eR96** [comment]
Feel free to wrap it into #1823
