### ISSUE TITLE
Spin off Perl6::Documentable

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1937]
## The problem

This is one of the modules that are used in htmlify.p6 (see #1823), so far exclusively. It is barely documented, and it does not have a single test. Functionality seems clear, but it's not specified anywhere. 
It does not have downstream dependencies, so it can be safely spun off and published as an independent module, which might have only perl6/doc as a paying customer, but then it's kinda a general module for processing and storing, in memory, documentation, so it might find its usefulness outside perl6/doc, when big modules with complicated documentation layout starts to sprout. 
Anyway, isolating and clearly specifying its functionality through tests will help with a faster, safer and more efficient testing and building of the Perl6 documentation.

## Suggestions

There's a (relatively simple) way of keeping file history, so I would create a new perl6/per6-doc-documentable repo and start working on that. When it's completed and published, I (or whoever) will publish it in p6c/ and either remove it from perl6/doc or keep it as a submodule.

I'm "assigning" this issue to a bunch of you to solicit some explicit feedback. A simple thumbs up or down will do. Just deassign yourself when you're done, or if you don't want to participate. Thanks!

**Comment by coke** [comment]
I don't think pushing it to another repo will be helpful, esp. given its size, but documentation and tests are a plus. I will probably be touching parts of this on the coke/build branch.

**Comment by JJ** [comment]
Perl6::Documentable is just a couple of files. I'll check out that branch.
