### ISSUE TITLE
"Try google search" has disappeared

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1940]
## The problem

When the term in the docs.perl6.org search box is not in the index, there used to be a "Try web search" option. It was not perfect (see #1391), but it's now disappeared

## Suggestions

We *really* need specs and a test set for htmlify. But for the time being, just try to put it back where it belongs.

**Comment by AlexDaniel** [comment]
But I can still see it?

**Comment by JJ** [comment]
I couldn't see it in Firefox...

**Comment by AlexDaniel** [comment]
Firefox:
![image](https://user-images.githubusercontent.com/5507503/38925975-cae1f28e-4309-11e8-905b-8b9f71c319eb.png)

**Comment by JJ** [comment]
It was a network error, apparently. It works now. 
Anyway, it's true that we should check these things do not disappear...
