### ISSUE TITLE
make html hangs on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#1947]
I installed GraphViz, Mojolicious, Sass, and the various Perl modules this is dependent on, but when I run `make html`, after "Processing complete" prints, the process hangs on [biowait](https://man.openbsd.org/bread.9#FUNCTIONS) and forces me to kill it.

Tested on OpenBSD 6.3 GENERIC.MP#107

**Comment by JJ** [comment]
I guess that's after installing all Perl 6 without a problem, right?

**Comment by Kaiepi** [comment]
Yes

**Comment by JJ** [comment]
Can you just run `perl6 htmlify` to see what happens? Maybe it's the
parallel part that's doing that.

**Comment by Kaiepi** [comment]
That's the part that hangs

**Comment by JJ** [comment]
Even if you run it without the --parallel=1 option?

**Comment by stmuk** [comment]
What does "perl6 -v" say?

**Comment by Kaiepi** [comment]
I'm still waiting on the second build to finish

```
This is Rakudo version 2018.02.1-423-g9e6ae276a built on MoarVM version 2018.03-121-g4e129a4ec
implementing Perl 6.c.
```

**Comment by JJ** [comment]
Yep, that takes a while. You using simply `perl6 htmlify.p6`, right?

**Comment by JJ** [comment]
2018-04-21 18:57 GMT+02:00 Ben Davies <notifications@github.com>:

> I'm still waiting on the second build to finish
>
> This is Rakudo version 2018.02.1-423-g9e6ae276a built on MoarVM version 2018.03-121-g4e129a4ec
> implementing Perl 6.c.
>
>
That's a weird combination. Why not 2018.03 on 2018.03?

**Comment by Kaiepi** [comment]
>Yep, that takes a while. You using simply perl6 htmlify.p6, right?
Yep

>That's a weird combination. Why not 2018.03 on 2018.03?
Both are up to date with master, but tags don't always get recognized on my system. 2018.03 doesn't exist on my local branch

**Comment by dogbert17** [comment]
Yes, when I build the docs I never use the –parallel flag. If I do nasty things have a tendency to happen.

**Comment by JJ** [comment]
@dogbert17 going back to #1938, maybe we should just eliminate that from the Makefile.

**Comment by Kaiepi** [comment]
It still hangs with `perl6 htmlify.p6`

**Comment by JJ** [comment]
Does it produce the file I mentioned above? That is, is it running that line and hangs after it?

**Comment by Kaiepi** [comment]
Yeah, it generates the file, just never exits

**Comment by JJ** [comment]
Chalk another one for #1823. But this looks like a rakudo/moarvm bug peculiar to your platform. If you can isolate the bug, it might help if you post a Rakudo bug.

**Comment by Kaiepi** [comment]
I figured out the issue git's tagging was having with Rakudo and will test it again

**Comment by Kaiepi** [comment]
Fixing the tags on Rakudo makes the script die properly, but still only when running `perl6 htmlify.p6`

**Comment by JJ** [comment]
Do you mean exit properly? And do you mean it still has problems with `--parallel`?

**Comment by Kaiepi** [comment]
Yeah, exit properly. It still has problems with `--parallel`

**Comment by dogbert17** [comment]
When I want to build the docs, I tend to use the following:

 

perl6 htmlify.p6 --no-highlight
