### ISSUE TITLE
Change "Perl 6 Pod" in the page title to "Pod 6"

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1948]
## The problem

We're kind of standardizing the name of the documentation DSL in Perl 6 to Pod 6. It's going to be known that way in GitHub when the PR github/linguist#4083 is eventually accepted 

## Suggestions

We should maybe change the title of the page to Pod 6. Besides, an additional problem is that it shows up second on web search, after docs.perl6.org.

**Comment by AlexDaniel** [comment]
Uh, actually, maybe not yet. At least not without a deep discussion.

Some *random* thoughts:

The thing is that we will have [an alias](https://github.com/perl6/6.d-prep/tree/master/TODO#language-extended-naming) eventually. Let's say it'll be “AAA”. With current naming of pod, it'll then be “Perl 6 Pod” and “AAA Pod” depending on context. Yes, two different names for the same thing, but that's what we want (sort of).

So if we rename it to POD6, then I guess it'll stay “POD 6” in both cases, which is nice… But then, what is “6”?

I guess “pod6” will work nicely with “6lang”, but then why not “6pod”? :)

**Comment by JJ** [comment]
But we're using Pod 6 pretty much everywhere else.

**Comment by JJ** [comment]
OK, I'm closing this then. If anyone feels strongly about changing the page name, just open it up again.
