### ISSUE TITLE
Sharing Pod 6 caches

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1952]
## The problem

Several utility programs build a cache of Pod 6 documents, only they do so in different ways.

- htmlify puts it in a global variable, `$*DR`
- pod-valid.t just ditches of the file as soon as it's checked.
- pod2onepage actually *builds* and puts it in a `.precomp` data store, used as a cache. That is why when you change just one page it says `(cached)`
- p6doc creates one `index.data` file, which is not used by anyone else.

Baseline is: many programs, some of them run in sequence, load and build Perl 6 objects out of Pod 6 files only to ditch it later. We should make them use the same objects, precomputed if they are available. 

## Suggestions

Could we maybe take a look at all this and create a single cache for docs that could speed up at least local testing? Would be part of #1823, but not the whole lot, of course...

**Comment by coke** [comment]
What's left to do on this ticket? Pod::Cache is covering things from a testing standpoint.

**Comment by JJ** [comment]
Hum, not really. @finanalyst has been working on a Pod::Cached that would actually compile the Pod just once.

**Comment by coke** [comment]
Can you please clarify how Pod::Cache is insufficient? and link to the Pod::Cached work?

**Comment by JJ** [comment]
Maybe @finanalyst can clarify?

**Comment by antoniogamiz** [comment]
@coke Here is the code of Pod::cached => https://github.com/finanalyst/pod-cached
