### ISSUE TITLE
Docs homepage needs banner linked to perl6.org

### ISSUE THREAD

**Issue by COMBORICO** [perl6/doc#1954]
## The problem

The way it is currently set up, the impression is given that The Docs are a different website than perl6.org.  Not having a prominent link to perl6.org is secluding unfamiliar guests from visiting perl6.org.  This choice is made even more obvious by how the banner currently just links to its self-same page.  So the "real-estate" is currently not being availed anyhow.

## Suggestions

I propose that only the "homepage" of docs.perl6 have the banner click-able to the homepage of perl6.org.  All the other pages of docs.perl6.org can remain the same, and remain linked to the homepage of Docs.

**Comment by JJ** [comment]
Well, the banner links to the homepage, as it should. Maybe we can add a link somewhere else, or make Camelia link perl6.org.

**Comment by JJ** [comment]
Before acting on this, I'd like to hear more opinions about if this should be done, and if so, where. Please vote with thumbs up if you want a banner linked to perl6.org, thumb down if you don't.

**Comment by coke** [comment]
See #1090 for a related issue

**Comment by JJ** [comment]
It's not raising a big response, but I guess it's mostly positive. Which begs the question: does it need to be a *banner*? That would need a major design change. What would be the best way of doing this?

**Comment by JJ** [comment]
Changes on things such as this need getting into htmlify.p6, thus refactoring it (#1823 ). This is less than awesome... A proper templating engine should be used, but I'm not sure there's one now in Perl 6
