### ISSUE TITLE
Not much info on $*IN in Docs

### ISSUE THREAD

**Issue by COMBORICO** [perl6/doc#1955]
## The problem

Just a single line:

$*IN | Standard input filehandle, AKA stdin

(Apologies if I missed the page that talks about it. But I didnt' find it from an internal and external search.)

**Comment by JJ** [comment]
There's a bit [in `IO::Handle`](https://docs.perl6.org/type/IO::Handle) too. What are you looking for, specifically?

**Comment by fluca1978** [comment]
The page is <https://docs.perl6.org/language/variables>.
I don't see the point of this issue: what information is missing from such page? Moreover the same "one line statement" does apply to `S*OUT*` and `$*ERR`.

**Comment by W4anD0eR96** [comment]
Agree with @fluca1978 . We can document more about I/O in I/O page. In variable page, saying `$*IN` is standard input file handle, aka stdin is enough for me. Anyway, it can set a link from `$*IN` to relevant stuff in https://docs.perl6.org/language/io

**Comment by fluca1978** [comment]
+1 for adding documentation in io page (if needed).
I've placed a short reminder to such page at the end of the table (since links embedded are still not working).
