### ISSUE TITLE
S/// not indexed

### ISSUE THREAD

**Issue by jkramer** [perl6/doc#1959]
## The problem

It seems that substitions using uppercase S instead of s (return string with substitutions instead of modifying in place) is not documented.

## Suggestions

Add documentation for S to the regex overview page (https://docs.perl6.org/language/regexes)

EDIT: I was just told about the documentation [here](https://docs.perl6.org/language/operators#S///_non-destructive_substitution). But it probably wouldn't hurt to mention it on the regex page.

**Comment by zoffixznet** [comment]
It is: https://docs.perl6.org/language/operators#S///_non-destructive_substitution

But likely doesn't show up in search due to the indexing bug.

**Comment by JJ** [comment]
Included in #1894
