### ISSUE TITLE
Example code in IO::Socket::INET crashes

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1963]
## The problem

This [code that shows up in the examples of IO::Socket::INET](https://docs.perl6.org/type/IO::Socket::INET) apparently [crashes when closing the connection](https://stackoverflow.com/questions/50032392/perl6-iosocketinet-could-not-receive-data-from-socket-connection-reset-by-p)

This is the error with which it crashes
```
Could not receive data from socket: Connection reset by peer                    
  in block <unit> at server-io-socket.p6 line 9
```

## Suggestions

Check if this is a new bug and file a report where it belongs and/or fix the example code accordingly.

**Comment by fluca1978** [comment]
Tested on an old version, moar 2017.12, and it worked without crashing.

**Comment by fluca1978** [comment]
Tested again on 2018.04, not crashing...

```
% perl6 -v
This is Rakudo version 2018.04 built on MoarVM version 2018.04
implementing Perl 6.c.
```

**Comment by JJ** [comment]
The code that's crashing is the one in the StackOverflow question. It's very similar to the one in the example.
