### ISSUE TITLE
Adding a Perl 6 from Node.js - Nutshell page

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#1968]
## The problem

There are already a bunch of pages to help users experienced  in other languages learn Perl 6, but none for Node.js. The two languages share some common aspects, but many of them behave completely differently, e.g. promises and timeouts .

## Suggestions

If this should be written, I could write it, since Node.js is (sadly) the language I'm most experienced in. If anyone has any suggestions for language features that should be included, let me know.

**Comment by AlexDaniel** [comment]
Sure, yes! Can you start it?

**Comment by jnthn** [comment]
Yes, Node.js users are certainly an interesting potential target audience for Perl 6, in so far as they're used to working with a dynamic language and doing async, and Perl 6 provides a more nuanced static/dynamic balance and a higher-level approach to async. Actually, the experience of building a bunch of microservices in Node.js was what motivated me to write Cro. :-)

**Comment by cfa** [comment]
Bumping this as there're still a number of *TBD*s on the page.

**Comment by Kaiepi** [comment]
I won't have much time to deal with the TBDs for the next few months with the grant but I'll see what I can do. If anyone else wants to help out that'd be a big help
