### ISSUE TITLE
Separate category of Tutorial

### ISSUE THREAD

**Issue by TisonKun** [perl6/doc#1969]
Below `/language/` we have 3 pages about unicode, 2 pages about grammar, 2 or 3 pages about OO.

They mix up concept/reference with tutorial/case study. It might be better to keep high level concepts below `/language/` and move **detailed/hand by hand** tutorials (especially, several grammar tutorials) below a new category `/tutorial/`. 

Refers to #114 . It is ok to, somehow, keep redundant, but not several pages of nearly the same topic that pushes our users do cross reading (for an identical topic).

**Comment by JJ** [comment]
In principle, it seems an excellent idea. The main problem is all the
tooling around these docs, which is pretty much hardwired for the current
layout. It might be the way to finally refactor it, or maybe generalize it.
But I'm kind of wary of getting into this...

**Comment by W4anD0eR96** [comment]
@JJ That is the problem. However, I'd like to try to rearrange/rewrite grammar stuff(though it might not be done soon).
Documentation itself and how we render it are independent. This issue pays more attention to documentation itself. Anyway, thank you for working on "site" issue.

**Comment by W4anD0eR96** [comment]
​Yes, add a category is coupling with render logic.​

2018-04-27 14:20 GMT+08:00 Juan Julián Merelo Guervós <
notifications@github.com>:

**Comment by tbrowder** [comment]
Close with commit 7afe426.

**Comment by TisonKun** [comment]
@tbrowder sorry but they are all list on https://docs.perl6.org/language.html now. I see the commit and notice the GROUP things, but on the site there is no conspicuous stuff to separate groups

**Comment by tbrowder** [comment]
I have a working solution but AlexDaniel doesn’t like the looks of it.

**Comment by JJ** [comment]
This has now changed after @finanalyst work. Can you check now?

**Comment by TisonKun** [comment]
@JJ remaining there are things to do for improving the document content, the structure makes sense to me. Thanks for your reminder and @finanalyst works!
