### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#197]
`p6doc Type::Str.split` gives an error:

      $ p6doc-index build                                       
      $ p6doc Type::Str.split
        Cannot call MAIN(Str, Bool); none of these signatures match:
        ()
        ($docee)
       ($docee, Bool :$f!)
       in method throw at /home/kamil/.rakudobrew/moar-nom/install/share/perl6/runtime /CORE.setting.moarvm:1
       in sub MAIN at /home/kamil/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/p6doc:81
       in block <unit> at /home/kamil/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/p6doc:164

**Comment by stmuk** [comment]
I can't reproduce this with a fresh install of moar-nom and perl6/doc as of today.

**Comment by teodozjan** [comment]
After nuking rakudo and updating debian me too
