### ISSUE TITLE
/tmp files don't get cleaned up properly

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#1973]
## The problem
- `app.pl` leaves behind two files in `/tmp` after running
- `htmlify.pl6` leaves behind several thousand files if perl is killed before it finishes. Your OS may not be able to clear `/tmp` on boot when this happens because there are too many files to pass to `rm`

## Suggestions
- I'm working on a fix for the first issue
- Maybe a tmp dir should be made in the repo when running `htmlify.pl6` and removed after the script has finished. This would make removing files on SIGINT/SIGTERM a matter of just catching the signal and removing the entire directory

**Comment by coke** [comment]
The change was recently made it to htmlify And it’s relying on the module to remove the files when it’s done we can easily remove them as we go. I’ll Put that back tomorrow.

**Comment by Kaiepi** [comment]
> If your fixed is better, just toss mine out.

Yours is better. I was unlinking them after copying instead

**Comment by coke** [comment]
That comment was all comments; the unlink causes the build to break. (another version with closing the handle before the unlink also breaks the build.

**Comment by JJ** [comment]
So how's this going now? I'm kinda of confused. app.pl deletes its files, htmlify.p6 does not.

**Comment by coke** [comment]
... there were two complaints. one is fixed; the other is not. You can see my attempt in the commits above that had to be backed out because they broke the build.

**Comment by JJ** [comment]
Ref #1823
