### ISSUE TITLE
Pager displays codes of terminal control characters

### ISSUE THREAD

**Issue by teodozjan** [perl6/doc#198]
`p6doc FIle::Find`

```
ESC[1mFile::FindESC[0m allows you to get the contents of the given directory,
recursively, depth first. The only exported function, ESC[1mfind()ESC[0m, generates
```

It would be more user friendly to use `less -r` instead or at least warn user that should set `%*ENV<PAGER>` variable after install

**Comment by stmuk** [comment]
I can only reproduce this with the POD_TO_TEXT_ANSI environment variable set.

So its not behaviour most users should see unless they are trying to display ANSI on purpose.

**Comment by molecules** [comment]
POD_TO_TEXT_ANSI is not set on my Windows machine, but I still get that behavior from p6doc. Here is the ninth line generated from `p6doc Int`:

```
[1mInt[0m objects store integral numbers of arbitrary size. [1mInt[0ms
are immutable.
```

This is on Windows 10 (64-bit) using Rakudo-Star 2018.04.

**Comment by JJ** [comment]
p6doc sets POD_TO_TEXT_ANSI, with the comment "use Terminal::ANSIColor if available" So whatever you've set, it does not pay a lot of attention.
