### ISSUE TITLE
TOC doesn't work in 1-file docs

### ISSUE THREAD

**Issue by evb0110** [perl6/doc#1980]
## The problem
When I click a position in the Table of Contents (TOC), the URL changes, but nothing happens. So, it's impossible to navigate the huge docs in one file https://docs.perl6.org/perl6.html. 
The problem exists on Kubuntu 17.10 / Chromium and Firefox, Windows 7 / Chrome, Windows XP / Chrome, Linux Mint 18.3 / Chromium and Firefox.

## Suggestions
To fix the problem. Thanks!

**Comment by JJ** [comment]
Maybe it's not using the new module. Let me see to that and thanks for warning.

**Comment by JJ** [comment]
TOC works now, but index does not.

**Comment by evb0110** [comment]
That's much better, thanks!

**Comment by evb0110** [comment]
@JJ Thanks, everything works!
