### ISSUE TITLE
Local anchor to && is broken

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1983]
See this page: https://docs.perl6.org/routine/and

It links to [infix &&](https://docs.perl6.org/routine/and#infix_%26%26), but that is only accessible from the parent page here: https://docs.perl6.org/language/operators#infix_%26%26 (otherwise the link does not work).

**Comment by W4anD0eR96** [comment]
Since it is not that about `doc`, and there is many link issue. How about introduce a label named `link` or something?

**Comment by W4anD0eR96** [comment]
IMO label `doc` is about issues like improving document, lack of document.

**Comment by JJ** [comment]
There is a big issue for links, #561 if I remember correctly.
