### ISSUE TITLE
Translate README.md to languages

### ISSUE THREAD

**Issue by JJ** [perl6/doc#1984]
## The problem

We have right now a [Chinese version](https://github.com/perl6/doc/blob/master/README.zh.md), we could have more at least to populate search results in a number of languages.

## Suggestions

Translate to

- [x] Spanish
- [x] German
- [x] Dutch
- [x] Portuguese
- [x] French
- [x] Japanese

**Comment by fluca1978** [comment]
I placed the first italian translation of the readme, and backlinked in the official readme.

**Comment by JJ** [comment]
Thanks!

**Comment by JJ** [comment]
@terceranexus6 is working on the Japanese translation.

**Comment by JJ** [comment]
@antoniogamiz and @elenamerelo will be working on the Spanish translation.

**Comment by zaucker** [comment]
I can do a German translation.

**Comment by JJ** [comment]
Please do that!

**Comment by zaucker** [comment]
Ok, I will do the translation into German.

**Comment by Reko98** [comment]
Hey! I can do the french Readme, i'm not French but i know a little bit of that language and I have a few friends who could help me with the translation, since they study this language.
Do you want me to do it?

**Comment by JJ** [comment]
Please do it! Thanks a lot.

Or better

S'il vous plait, vous les faites. Merci beaucoup.

And that's the full extent of my knowledge of French...

**Comment by JJ** [comment]
nohighlight runs htmlify.p6, which needs node and graphviz. Mojolicious run
the local website, which is run from make run. And yes, make html has all
those dependencies.
