### ISSUE TITLE
Map.ACCEPTS documents unrelated stuff / Missing Map.ACCEPTS: Map

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1986]
There are some seemingly unrelated docs about indexing into a `Map` at the bottom of `Map.ACCEPTS` docs. The docs for the method also appear to be missing `Map.ACCEPTS: Map` that offers non-explosive `eqv` semantics (partially related: [R#1772](https://github.com/rakudo/rakudo/issues/1772))

![z](https://user-images.githubusercontent.com/5747918/39535640-6c2c6aea-4e02-11e8-993d-e486ac57931b.png)

**Comment by fluca1978** [comment]
Close via 33283d3
