### ISSUE TITLE
A DBIish example is outdated; MySQL is replaced with MariaDB on Debian Stretch

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1993]
## The problem
See: https://docs.perl6.org/language/nativecall#MySQL

This section recommends to use `apt-get install mysql-server` on debian-like system.
However, MySQL is replaced with MariaDB on Debian Stretch.
So, `apt-get install mysql-server` tries to install mariadb-client and the shared object file (i.e. libmysqlclient.so) will not be installed.

See also:
+ https://www.debian.org/releases/stretch/amd64/release-notes/ch-whats-new.html#mariadb-replaces-mysql
+ https://packages.debian.org/stretch/mysql-server
+ https://packages.debian.org/stretch/default-mysql-server

## Suggestions

I'm not sure, but a quick and dirty solution is:
```
$ wget http://ftp.br.debian.org/debian/pool/main/m/mysql-5.5/libmysqlclient18_5.5.58-0+deb8u1_amd64.deb
$ sudo dpkg -i libmysqlclient18_5.5.58-0+deb8u1_amd64.deb
```

**Comment by JJ** [comment]
Also, those examples have nothing to do with NativeCall. It does not use it.
