### ISSUE TITLE
Content of pages without ToC appears on the left side

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2000]
See https://docs.perl6.org/language/pragmas

Without ToC:

![image](https://user-images.githubusercontent.com/5507503/39672433-973395c8-5132-11e8-8c1b-bbd060ace2dd.png)

With ToC:
![image](https://user-images.githubusercontent.com/5507503/39672436-a48ba3be-5132-11e8-84d6-72d21b5ea176.png)

IMO the content should be rendered consistently.

**Comment by JJ** [comment]
When there's no TOC, the content has the class appropriately named `no-toc`. Let's see what can be done about that.

**Comment by AlexDaniel** [comment]
This didn't fix anything.

![image](https://user-images.githubusercontent.com/5507503/40471498-8e165906-5f3f-11e8-9098-8cba99349609.png)

**Comment by AlexDaniel** [comment]
Why `!important`? Seems to be working without it.
