### ISSUE TITLE
Lack of Regex Assertions Documentation

### ISSUE THREAD

**Issue by TisonKun** [perl6/doc#2009]
https://irclog.perlgeek.de/perl6/2018-05-07#i_16140539

> Tison | .ask moritz I found a regex like `regex key { <![#\[]> <-[;=]>+ }` and wonder what's the different between <![...]> and  <-[...]>. BTW, the former isn't documented.
> Tison | It looks like the former is an assertion while the latter really matches something
> Tison | our documentation on assertion only shows look-around assertions but no general assertion forms
> timotimo | yeah, if you have a ? or ! after the < it becomes a zero-width matching assertion

**Comment by JJ** [comment]
Check out @TimToady 's comment in the IRC https://irclog.perlgeek.de/perl6/2018-05-08#i_16141345
