### ISSUE TITLE
Syntax Highlights Don't Work on Some Boxes

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#201]
For example, the several code blocks following [this one](http://docs.perl6.org/type/Signature#Constraining_Defined_and_Undefined_Values) have no highlighting. I looked at the pod for both working and non-working codes and I don't see the difference:

![hs](https://cloud.githubusercontent.com/assets/5747918/11188346/559c2a22-8c58-11e5-8a95-14f1592a53ae.png)

**Comment by zoffixznet** [comment]
Based on [conversation on IRC](http://irclog.perlgeek.de/perl6/2015-11-16#i_11546549), the likely suspect is the **bolded text** in the code examples.

**Comment by moritz** [comment]
Yes, there's no way to pass text that's already marked up to a syntax hilighter.

The alternative would be to strip the markup, hilight, and then re-apply the markup, all the while preserving proper nesting of HTML tags.

If somebody wants to do it (and maintain it!) that would be great, but personally I don't think it's worth the trouble.

**Comment by zoffixznet** [comment]
At least right now, we have better things to spend dev time on than this. Closing.
