### ISSUE TITLE
p6doc - 'make html' fails

### ISSUE THREAD

**Issue by bazzaar** [perl6/doc#2014]
## The problem

Initially, whilst running 'make install' of Rakudo Star 2018.04, I noticed p6doc 'FAIL - proceeding with force install' or something like that. Rakudo Star itself installed correctly, and zef works fine because I subsequently installed cro and dependencies without a problem.

So I tried to install a local html copy of the docs, as a test. I cloned perl6/doc from github to a local dir, and found that 'make html' from within the doc directory fails. 

Two log files capture the 'make html' error :

[make_p6doc_html.txt](https://github.com/perl6/doc/files/1985556/make_p6doc_html.txt)
[npm-debug.log](https://github.com/perl6/doc/files/1985558/npm-debug.log)

## Suggestions

Hopefully the log info will help to shed light on what causes the failure.

**Comment by stmuk** [comment]
It looks like you need g++ installed for one of the node related installations.

**Comment by stmuk** [comment]
g++ shouldn't be a requirement for building star itself which should only install p6doc and not run the website generation code or tests or code with further dependencies.

Parts of the website generation code (like "make html") will need further dependencies.

**Comment by JJ** [comment]
I will check if that's clearly written in the README.md and other instructions.
