### ISSUE TITLE
pod.pod6 needs an example of a multi-line pod declarator block

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2035]

**Comment by JJ** [comment]
I am under the impression that there's a similar issue somewhere... but I couldn't find it.

**Comment by JJ** [comment]
Right, #1944. Is that what you mean?

**Comment by JJ** [comment]
Reopening due to [@tbrowder's concerns](https://irclog.perlgeek.de/perl6/2018-05-20#i_16186259)
