### ISSUE TITLE
Non-breaking space becomes normal space when rendered to the web

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2037]
See this screenshot:

![image](https://user-images.githubusercontent.com/5507503/40284396-4723cc7c-5c97-11e8-9fcf-9ec8d8b7587f.png)

It does “Perl
6”, meaning that there's no non-breaking space. Or maybe there's some other issue.

**Comment by AlexDaniel** [comment]
Sorry, what? The whole point of a non-breaking space is that it should by all means try to break the text somewhere else.

**Comment by JJ** [comment]
Well, kinda. It means that it's going to be treated just like any other character, and in this case, there were too many characters to fit in the column so it wrapped. That is why my solution was to shorten that heading, which was too long anyway. Please review page as it is now to see if it solves this particular problem, and close if it does.

**Comment by JJ** [comment]
In other words, just move "Perl 6" around or change it to other 6 characters and see where it breaks...

**Comment by JJ** [comment]
Um, it becomes a breaking space when rendered... 
![screenshot from 2018-05-21 08 16 40](https://user-images.githubusercontent.com/500/40293067-599530f2-5ccf-11e8-8e57-2d4efcb9d13b.png)
I wonder why...

**Comment by JJ** [comment]
Seeing as this is a bug in the Pod rendering engine, best option here would be to patch at the htmlify.p6 level.

**Comment by JJ** [comment]
I have done some tests patching the HTML file before output, but it's not a good solution, since it substitutes everything, even code. I'll leave it as external, and wait for rakudo/rakudo#1852 to be solved.

**Comment by JJ** [comment]
Fixed by @tbrowder in rakudo/rakudo#1854. Will close when released and used into the Rakudo version running in perl6.org.

**Comment by JJ** [comment]
This is fixes in Pod-To-HTML. Will bump up versions and redeploy it in docs.perl6.org (will have to remember how, though)

**Comment by JJ** [comment]
Just deployed everything to docs.perl6.org, looks correct. Thanks @tbrowder for the patch.
![screenshot from 2018-06-23 12 10 17](https://user-images.githubusercontent.com/500/41808501-951389e8-76de-11e8-8542-119504a316d3.png)
