### ISSUE TITLE
The UTF8-C8 section doesn't tell how to use it.

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#2043]
## The problem
https://docs.perl6.org/language/unicode#UTF8-C8

The UTF8-C8 section doesn't tell how to use it.

**Comment by rafaelschipiura** [comment]
Not for me...

**Comment by JJ** [comment]
I mean it does not have any user-accessible function one can use from a program.

**Comment by JJ** [comment]
It apparently is https://github.com/perl6/roast/blob/master/S32-str/utf8-c8.t. OK, let's see what we can do.
