### ISSUE TITLE
X::NYI - insufficient info about construction params.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#2052]
## The problem

Documentation of [X::NYI](https://docs.perl6.org/type/X::NYI) says that it inherits from Exception.

So natural assumption is to write:
```perl6
X::NYI.new( message => "Making coffee" ).throw( )
```

Which gives incomplete error message:
```
 not yet implemented. Sorry.
```

While in fact undocumented `feature` param must be used:
```perl6
X::NYI.new( feature => "Making coffee" ).throw( )
```
```
Making coffee not yet implemented. Sorry.
```

## Suggestions

Param `feature` should be documented.

**Comment by bbkr** [comment]
Thank you. Very nice explanation!

**Comment by JJ** [comment]
Thanks for the report!
