### ISSUE TITLE
What values stuff like $*DISTRO.name can have?

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2054]
Today, I needed to skip some code if the OS is a MacOS, but since I don't have a MacOS to play with, I've no idea what `$*DISTRO.name` would actually contain.

Would be nice to have a table for potential values like this, so someone writing to detect some system could find the values to test for.

**Comment by JJ** [comment]
There seem to be [like 5 or 6](https://github.com/rakudo/rakudo/blob/c71fa17d8da36b8cfcbd85584cee32566f25f059/src/core/Kernel.pm6). But it's probably *very* implementation-dependent.

**Comment by AlexDaniel** [comment]
See the comment on https://github.com/perl6/doc/commit/bc8b41d69d7cd231f5ea2fd3cc06f781c1998e4d#commitcomment-29126515.

Also maybe we should add a test that makes sure we don't talk about some specific implementation (rakudo) too much?

**Comment by JJ** [comment]
> Also maybe we should add a test that makes sure we don't talk about some
> specific implementation (rakudo) too much?
>

Well, this issue is clearly marked as not specced. It's also quite clear in
the docs added. I follow a very common sense rule when adding
implementation-dependent documentation: if people ask for it, I add it with
all the necessary caveats.

I have no idea how that test could work, also. There is another issue that
says that everything that is documented should be linked to roast. If that
was the case, it would be (relatively) easy to do: no link to roast, you
can't add it. But right now I really can't figure out how that test would
work.

**Comment by zoffixznet** [comment]
> Well, this issue is clearly marked as not specced. 

But that label is for things that can't be documented *because* they're unspecced.

> It's also quite clear in the docs added.

It wasn't clear to me at all. The link just led me to a confusing source file while saying "these values". And I *know* Perl 6; imagine a newbie reading it.

> no link to roast, you can't add it.

👍

**Comment by AlexDaniel** [comment]
> But that label is for things that can't be documented because they're unspecced.

Correct. I changed the label description now to “Wait for roast tests before documenting”, I hope that's clearer now.

**Comment by JJ** [comment]
El vie., 25 may. 2018 a las 12:03, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> But that label is for things that can't be documented because they're
> unspecced.
>
> Correct. I changed the label description now to “Wait for roast tests
> before documenting”, I hope that's clearer now.
>

Then we might need something new for "There's no roast test for this"
and/or "It's a rakudo feature", implying "document at your discretion"

**Comment by AlexDaniel** [comment]
> Then we might need something new for "There's no roast test for this"
and/or "It's a rakudo feature", implying "document at your discretion"

I think NOTSPECCED already does that. Anyway, see https://github.com/perl6/doc/issues/2057 to discuss it further.
