### ISSUE TITLE
Line length and wrapping in pod files

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2056]
I think it's a good practice to have lines in our .pod6 files wrapped at around 72 characters (with some exceptions). This is the case for many parts of the documentation, but not all contributors are doing that. In the end we have files with mixed line lengths.

Should we just autowrap the whole repo? Or should we add a file to xt/ that will give warnings for too long lines?

**Comment by AlexDaniel** [comment]
Another good reason to wrap lines is how github renders diffs:

![image](https://user-images.githubusercontent.com/5507503/40538661-f719fb84-601a-11e8-8419-0af7f1e8de88.png)

**Comment by JJ** [comment]
Yep, right. I don't have atom configured for line wrapping. I don't know if we need a test, because I've found all kind of lines and wrapping every file would be a pain... But I think this should definitely go to the guidelines.

**Comment by JJ** [comment]
Maybe wrap (no pun intended) this into #2057?
