### ISSUE TITLE
Document Caveats of .gist's Behaviour

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#206]
For example, say on long lists will actually only print the first 100 elements. This does not appear to be clearly documented in http://doc.perl6.org/type/List.

See relevant IRC discussion: http://irclog.perlgeek.de/perl6/2015-11-22#i_11580085

**Comment by zoffixznet** [comment]
Related: #207

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/0764762e57
