### ISSUE TITLE
trap of token name maybe confilct with internal token ?

### ISSUE THREAD

**Issue by araraloren** [perl6/doc#2061]
## The problem
```
my grammar Test { 
rule TOP { <CREATE> } 
token CREATE { "CREATE" }
};
say Test.parse: "CREATE"; 
#`(
Too many positionals passed; expected 1 argument but got 2
  in regex CREATE at -e line 1
  in regex TOP at -e line 1
  in block <unit> at -e line 1
)
```
Above error is cause by the name of token CREATE(it maybe a internal name), it is work fine if we change the CREATE to something other such as CREATEX.

## Suggestions

Document the trap of token name may confilct with internal name.

**Comment by JJ** [comment]
It's probably clashing with [Mu.CREATE](https://docs.perl6.org/type/Mu#method_CREATE). Might be the same for `ACCEPTS` and other like that. Well seen, will try to add some explanation to avoid that.

**Comment by Xliff** [comment]
You might want to add COALESCE to that list, as well.

**Comment by timo** [comment]
where does COALESCE come from? i don't see it anywhere in rakudo's source nor in nqp's source, so i don't think there's anything that'd call it for you at any point? like, if you have a .item, that'll be called wherever you have the grammar or a match object of that grammar in $ context, for example.

**Comment by Xliff** [comment]
Sorry. I fixed that issue. I was running into a situation where:

```perl6
token COALESCE { 'COALESCE' }
```

Would cause an error. Turning it to _COALESCE fixed the problem until I fixed the real underlying issue.
