### ISSUE TITLE
In Regexes doc not all Unicode Property infix combining operators work.

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#2064]
## The problem

Towards the end of the [Unicode Properties section of Regexes](https://docs.perl6.org/language/regexes#Unicode_Properties) there is a table of five character class combining operators but AFAIK only `+` and `-` work and the other three - `&`, `|`, `^` do not seem to combine classes.  You might use `&` conjunction to get a similar effect like the `posix_alnum` example below but that is not how the operators are presented in the documentation.

IRC discussion here: https://irclog.perlgeek.de/perl6/2018-05-26#i_16210067

```Perl6
my token posix_alnum { <+alnum - [_]> & <:ascii> };
my $latin-chars = [~] chr(0)..chr(0xFF); 
say $latin-chars.comb(/<posix_alnum>/).join

OUTPUT: 
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz␤
```
## Suggestions

If the operators don't work in this context they should be removed and the section may need a little rewriting.  The use of conjunction to get the effect of intersection might be mentioned.

**Comment by JJ** [comment]
Only [+ and - are in roast](https://github.com/perl6/roast/blob/fca87f2030d5cab6fc8460e5b195aecd9b7765b2/S05-mass/charsets.t), as far as I can tell...
