### ISSUE TITLE
Docs on independent subroutines.

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#2070]
## The problem

Following the lead of perldoc, the page about independent subroutines is missing.

## Suggestions

- [ ] <code>subs</code>Independent Subroutines

Implement the page (@JJ is on it).

**Comment by JJ** [comment]
It's not finished yet. Not even started, actually.

**Comment by rafaelschipiura** [comment]
If you like this bug report, you can keep this bug report. I closed it because I thought it was just a duplicate of #2578 .

**Comment by JJ** [comment]
Not exactly the same... This issue asked for a new page, the other asked for a whole subdirectory and was rather a request for comments. We could use one, the other or both. Solving this issue would be a temporary solution, solving the other maybe more permanent.

**Comment by rafaelschipiura** [comment]
OK, it's not a problem being bold and then having changes reverted.

**Comment by JJ** [comment]
There are many these subroutines put together in [IO](https://docs.perl6.org/type/IO#sub_shell) which, in fact, does not have to do anything with any of them.
I wonder if something would break if we created an independent-subs "type" right in the Type directory.
