### ISSUE TITLE
Docs for await in Promise should include a way to watch for broken promises

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#208]
Since `await $p1, $p2` will throw if any of the Promises were broken, we should show an example of how to check for broken promises and fetch the results for kept promises, even if some were broken.

It seems the idiomatic way is to use `await Promise.allof( $p1, $p2 )`, but currently that will throw if any of the promises is broken. jnthn++ believes that's a bug. See this conversation: http://irclog.perlgeek.de/perl6/2015-11-23#i_11585114

Once the bug  is resolved, the docs should be updated to include correct handling of broken promises, something akin to this, except with `Promise.allof()` instead of `eager`:
```perl6
my $p1 = start die "I'm dead";
my $p2 = start "I'm alive";
try eager await $p1, $p2;
say .result for grep { .status ~~ 'Kept'}, $p1, $p2;
```

**Comment by AlexDaniel** [comment]
It seems like the bug was fixed? See http://irclog.perlgeek.de/perl6/2016-07-01#i_12770142

**Comment by zoffixznet** [comment]
There's already a good example in [.allof](https://docs.perl6.org/routine/allof), so I'll close this.
