### ISSUE TITLE
L<>s in =SUBTITLE do not work

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#209]
I'm not sure if `C<>` and friends are affected as well.

If you look at http://docs.perl6.org/type.html, you'll notice some of the text in the right column is abridged:

`
class   Backtrace::Frame    Single frame of a ???
class   Tap     Subscription to a ???
role    X::Proc::Async  Exception thrown by ???
`
Looking at the actual POD for those classes, it seems the `=SUBTITLE` has an `L<...>` with the thing in side the angled brackets missing from the types list.

**Comment by JJ** [comment]
The mentioned page looks fine to me now. Can you please check?

**Comment by AlexDaniel** [comment]
I think `L<>` were simply removed, but the point is that it should work.

**Comment by JJ** [comment]
But if they've been removed here, we should open an issue about this
somewhere else and...

... you guessed it...

close this one, right?

**Comment by JJ** [comment]
This is also related to #1823. `SUBTITLES` are processed there. I wonder if we should create a label for that.

**Comment by JJ** [comment]
All Pod markup has been removed from the SUBTITLEs, so this is no longer an issue here. It might be a POD processing issue, but perl6/problem-solving#69 was created for that. So please address all additional requests there or in Rakudo proper.
