### ISSUE TITLE
output style in code examples

### ISSUE THREAD

**Issue by coke** [perl6/doc#2091]
doc/Language/5to6-nutshell.pod6 has sections like this:

```
=begin code :preamble<no strict;> :ok-test<dd>
# Perl 6
    dd $foo, $bar, @baz;
# Output
    Int $foo = 42
    Int $bar = 44
    Array @baz = [16, 32, 64, "Hike!"]
=end code
```
This puts all the code and output together as a single perl6 code block (which may or may not compile)

Other doc sections either have a separately formatted output block (which is then exempt from testing), or show the output in a comment in the code block, e.g.:

```
say @flat.elems;            # OUTPUT: «6␤»
```

We should have a uniform style for showing code output (maybe even having a CSS style and showing it as a separate block in the rendered HTML)

**Comment by JJ** [comment]
That was decided in #776. I wouldn't say this is a general issue; it might affect that page and maybe some other, but I haven't seen many others.

**Comment by coke** [comment]
That ticket says test soon- been a year, there’s no test

**Comment by JJ** [comment]
I don't see an easy way to do a test. You can test that OUTPUT is capitalized, and  that the newline character is there if there's a `say`. But in some multi-line cases, I put OUTPUT on different lines, for instance. And also there's the case you refer to here, which can only be caught by the compilation of the examples.
Baseline is: this doc should be changed, we'll have to deal with others on a case-by-case basis.
