### ISSUE TITLE
Range.in-range is not documented

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#2092]
```
> (^61).in-range(1)
True
> (^61).in-range(1, 'Second')
True
> (^61).in-range(100, 'Second')
Second out of range. Is: 100, should be in ^61
  in block <unit> at <unknown file> line 1
```

**Comment by JJ** [comment]
It's not specified. There's an issue open already: #819. I'm closing this one, if you don't mind.

**Comment by W4anD0eR96** [comment]
Thanks.

I would check if issue duplicated next time.

2018-06-05 17:50 GMT+08:00 Juan Julián Merelo Guervós <
notifications@github.com>:

**Comment by JJ** [comment]
No problem, feel free to raise any issue you find. If it's a duplicate, it
simply brings the other issue back to our attention. Thanks a lot for your
contribution.
