### ISSUE TITLE
word variant test doesn't catch mixed case issues.

### ISSUE THREAD

**Issue by coke** [perl6/doc#2093]
for example "Smart match".

Need to update the test to be case insensitive and fix the instances it finds.

**Comment by coke** [comment]
Additionally, plurals are also missed. 

e.g. "File Handles" should be "Filehandles"

**Comment by JJ** [comment]
Looks done here, right?

**Comment by coke** [comment]
Work done in: dd13765a, f4f975b5, efeabe5f
