### ISSUE TITLE
system.pod6 needs example of user interaction 

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2095]
Show an example of a running program asking for input from the user.

**Comment by JJ** [comment]
Could it be some other example? I kinda hate those entry-level programs that prompt the user for stuff. Maybe working with an environment variable? Or filtering standard output?

**Comment by tbrowder** [comment]
Well, it seems like a reasonable thing to me. And of course other examples are always helpful. 

My motivation for this suggestion is I need it for a program I’m writing for managing Apache passwords and want to present a choice to the user (me) after analyzing the state of password sets.  I can’t remember how to do it and haven’t found the right topic in the search box yet. This topic seems to be the perfect landing place for my quest.

**Comment by tbrowder** [comment]
Closed with commit 0ecbd02.
