### ISSUE TITLE
Passing arguments to tokens in Grammars is undocumented

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#2102]
## The problem
See title

## Suggestions
Document it. I don't know how this works, but I've seen it done in Roast tests so I'd rather someone more knowledgeable on how Grammars work document it

**Comment by JJ** [comment]
Tokens are just routines. I guess saying that implies you can use arguments. Regexes and rules also take arguments. But I guess it does not hurt to include some examples on how to do it.

**Comment by MorayJ** [comment]
Hopefully added the documentation requested...interpreting token as [token|regex|rule]
