### ISSUE TITLE
Document behavior  of %(), @(), $()

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2113]
See https://github.com/rakudo/rakudo/issues/1946 for a detailed description.

Currently [we say](https://docs.perl6.org/language/traps#Beware_of_empty_%22blocks%22):

> Brackets are used to declare blocks. However, empty brackets will declare a hash.

> That is why, in general, the %() form of declaring hashes is preferred.

Except that `%()` is not an empty hash :)

*EDIT: hash, of course*

**Comment by JJ** [comment]
The problem I see here is that there seems to be no safe way to declare an empty hash. I'll revise that issue for clarification, but it looks hard...

**Comment by JJ** [comment]
OK, I see. The safe way is using {}

**Comment by AlexDaniel** [comment]
I think `%()` should be a separate trap right next to it. Yes, maybe it will be deprecated, but we should document what we have now.

**Comment by jdv** [comment]
Kind of a side issue - can we not call {} chars brackets - at least curly brackets or, better yet,  braces
or curly braces.  When I read bracket I think of [] chars.

**Comment by AlexDaniel** [comment]
@jdv yes, please see https://github.com/perl6/doc/issues/2114.

**Comment by raiph** [comment]
Please see https://stackoverflow.com/a/44102980/1077672 and https://www.reddit.com/r/perl6/comments/8s2vl8/perl_6_colonpairoscopy/e12tf1r/

**Comment by JJ** [comment]
Sorry, what is WAT?

**Comment by JJ** [comment]
El sáb., 23 jun. 2018 a las 11:00, raiph (<notifications@github.com>)
escribió:

> Please note my latest attempt at formulating the {} hash vs block DWIM
> rule <https://stackoverflow.com/a/44102980/1077672>.
>
> I'm going on a trip for a week, but if everyone is happy with it I will be
> happy to integrate it into the doc a couple weeks from now.
>

if you want, we can assign it to you. I mostly agree with everything you
say.

**Comment by rafaelschipiura** [comment]
@JJ A WAT is what you get for every DWIM. http://knowyourmeme.com/memes/wat

**Comment by rafaelschipiura** [comment]
#2632 related
