### ISSUE TITLE
remove merged branches

### ISSUE THREAD

**Issue by coke** [perl6/doc#2118]
```
$ git branch -r --merged
  origin/HEAD -> origin/master
  origin/W4anD0eR96-patch-1
  origin/any-clarification
  origin/car-grant-midrat
  origin/extra-twigils
  origin/fails-like
  origin/fluca1978-backtracking
  origin/master
  origin/modules-20171223
  origin/molecules-patch-1-1
  origin/molecules-patch-2
  origin/polymod-digits
  origin/post-release
  origin/post-release-2018.03
  origin/post-release-2018.04
  origin/post-release-2018.06
  origin/rafaelschipiura-patch-1
  origin/ronaldxs-patch-1
```

**Comment by coke** [comment]
Didn't want to remove anyone else's branches on the off chance they want them, but here's a list to work off of.

**Comment by rafaelschipiura** [comment]
Here is documentation on how to do it: https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

**Comment by AlexDaniel** [comment]
Just delete all old branches with no commits ahead. There's no point in keeping them.

There's just one branch `modules-20171223` that feels like it should've been a tag, so I asked about it: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-06-23#l28

**Comment by W4anD0eR96** [comment]
Thank you @AlexDaniel , and remove my assignment.

**Comment by JJ** [comment]
I see all branches except for the last one have been deleted. It might be a good idea to delete them locally, too. Let's wait for @zoffixznet answer to delete this last one and close.

**Comment by molecules** [comment]
Feel free to delete my merged branches if they’re still there. I woukd, but I can’t seem to find them.

**Comment by zoffixznet** [comment]
> @zoffixznet answer to delete this last one and close.

No idea what that was. Deleted.
