### ISSUE TITLE
“sub link” is not searchable

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2121]
“sub link” is not searchable

**UPDATE**

nor is “sub symlink”

When searching for “link” or “symlink” neither show as a routine (although they do show as methods, which provides a “back door” to find that they are also subs).

**Comment by coke** [comment]
Apologies for update spam. Saw an empty comment, closed ticket, didn't look at title. Tried to clean up comment, deleted original (was just part of the template), but I dislike editing people's comments. Whoops.

**Comment by JJ** [comment]
There's [this doc when you search for `link`](https://docs.perl6.org/routine/link). Do you mean that?

**Comment by tbrowder** [comment]
@JJ, see my updated issue comment.
