### ISSUE TITLE
Possible Golfing in Regex Tutorial

### ISSUE THREAD

**Issue by mldevine** [perl6/doc#2126]
## The problem
https://docs.perl6.org/language/regexes#Enumerated_Character_Classes_and_Ranges
.
.
.
say "[- hey -]" ~~ /<-[ \\- \\] [ \\s ]>+/; # OUTPUT: «｢hey｣␤» 

*** In the above, we don't want '-', ']', '[' or '\s'.  '\\]' illustrates the point. The bare '[' does not illustrate the point.

## Suggestions

It would be helpful if the example remained consistent throughout when applying backslashes to all regex-meaningful characters that shouldn't match.  I recommend adding a backslash before the unwanted '[' character.

say "[- hey -]" ~~ /<-[ \\- \\] \\[ \\s ]>+/; # OUTPUT: «｢hey｣␤»

**Comment by pmichaud** [comment]
Actually, to me the backslashed '\-' doesn't prove the point, either.  '-' in character classes isn't meta, so why escape it with a backslash in the first place?

Pm

**Comment by mldevine** [comment]
My suggestion comes from p6-novice eyes (p4/5 intermediate) reading each line carefully in the tutorial.  I mentally stumbled slightly when I read the original example.  I took a few seconds and made an educated guess why the '[' didn't strictly need to be escaped, but it's tangential.  It's a very big language and it's easier for me to process one level first before contemplating the next (reducing implied/inherent/moot/spurious syntax).

The example could be replaced with:

say "[ hey ]" ~~ /<-[ \] \[ \s ]>+/; # OUTPUT: «｢hey｣␤»

Thanks,

Mark

**Comment by mldevine** [comment]
Looks like my backslashes were washed away in my reply...
