### ISSUE TITLE
NativeCall, CArray[].allocate example not working

### ISSUE THREAD

**Issue by loops** [perl6/doc#2132]
## The problem

From https://docs.perl6.org/language/nativecall#index-entry-CArray_methods

use NativeCall;
my $number_of_ints = 10;
my $ints = CArray[int32].allocate($number_of_ints);

Gives:
No such method 'allocate' for invocant of type 'NativeCall::Types::CArray[int32]'

There are other places on that page where .allocate is also referenced.

## Suggestions

Not sure, maybe allocate has been replaced somehow?

**Comment by JJ** [comment]
What version of Perl 6 are you using? I think it's the other way round, it's rather new.

**Comment by JJ** [comment]
Right, new as in [2 months ago](https://github.com/perl6/doc/blame/master/doc/Language/nativecall.pod6#L269). Upgrading to 2018.04 will probably fix that. Tell me if that's the case to close the issue, although if you thin, some note should be added indicating that, we can do that, too.

**Comment by loops** [comment]
I was at an older version, but just upgraded to:

This is Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1

And error persists.

**Comment by JJ** [comment]
It might be the next one, then. I'll check and clarify. Thanks for the
report.

**Comment by JJ** [comment]
I'm sorry, but I'm going down to 2018.03 and it's still working...

**Comment by JJ** [comment]
It starts to work in [2018.05](https://gist.github.com/Whateverable/31d1e3b6933e9fd9bbd9b09c0a5baa38), according to commitable. I'll clarify it in the docs. Thanks again for the report.

**Comment by loops** [comment]
Odd, i've tried it on two separate machines now with 2018.04.1 and get the error.  They're self compiled on Fedora Linux.  Maybe my environment has introduced some problem?    I'm testing from the repl with just:

use NativeCall; CArray[int32].allocate(5)

And getting the error.

**Comment by JJ** [comment]
El vie., 29 jun. 2018 a las 17:59, Sean (<notifications@github.com>)
escribió:

> Odd, i've tried it on two separate machines now with 2018.04.1 and get the
> error. They're self compiled on Fedora Linux. Maybe my environment has
> introduced some problem? I'm testing from the repl with just:
>
> use NativeCall; CArray[int32].allocate(5)
>

Something was wrong with _my_ environment. Got it now. Thanks!
