### ISSUE TITLE
Revise the lazy lists section

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2139]
## The problem

The main problem with [this section](/language/list#Lazy_lists) is nomenclature. Repeatedly this section refers to lazy *lists*, while most of the examples are actually lazy *arrays*. Anything which mixes in the `Iterable` role can be lazy, in fact, and that's not really well explained either. Also, it's indexed as Lazy (property of List), when it's actually a method of Iterable. `is-lazy` is a property of Iterator, not iterable, too. 

There's also the error of referring to the role `Iterable` instead of the role [`Iterator`](https://docs.perl6.org/type/Iterator#method_is-lazy), the one that actually implements all the lazy stuff., 

## Suggestions

Stop using the generic `list` and use specific denomination. Fix reference errors.

**Comment by zoffixznet** [comment]
> to lazy lists, while most of the examples are actually lazy arrays

FWIW, [lowercased `list`](https://docs.perl6.org/routine/list) refers to any `Positional` type, while [`List`](https://docs.perl6.org/routine/List) refers specifically to the List type.
