### ISSUE TITLE
Mention the status of atomicints

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2150]
According to [committable](https://gist.github.com/fa61e7efddb2f1e54a2fa30f381ad3bd), atomicints are available since rakudo 2017.08, and I think this should be mentioned. Otherwise someone using 2017.07 (which isn't even 1 year old) may be surprised that atomicints won't work with their setup.

By the way, does anybody know why atomicints are available with `use v6.c` and not just in v6.d.PREVIEW?

**Comment by jnthn** [comment]
> By the way, does anybody know why atomicints are available with use v6.c and not just in v6.d.PREVIEW?

Yes. They are used inside of the 6.c setting in order to implement a number of other concurrency primitives that are very decidedly available in 6.c. Thus they were put in the 6.c setting to make them available for that. Same goes for `Lock::Async`, which backs the `Supply` concurrency model.

**Comment by JJ** [comment]
[atomicint](https://docs.perl6.org/type/atomicint)s have their very own page. Do you mean add something to the tune of when they started to work?

**Comment by AlexDaniel** [comment]
@JJ “Note: available in rakudo starting with release 2017.08”

**Comment by JJ** [comment]
@AlexDaniel Would what's been added be enough?

**Comment by AlexDaniel** [comment]
@JJ yea
