### ISSUE TITLE
language/nativecall doesn't mention "is rw"

### ISSUE THREAD

**Issue by moritz** [perl6/doc#216]
... but it should.

**Comment by Altai-man** [comment]
Actually, it does. See https://docs.perl6.org/language/nativecall.html#Basic_use_of_Pointers - first paragraph describes it and shows an example. Can be closed or we need some wider explanation?

**Comment by Altai-man** [comment]
Closed with http://irclog.perlgeek.de/perl6/2016-08-14#i_13022429
