### ISSUE TITLE
Move out the section on declaring custom operators from the description of the Sub class

### ISSUE THREAD

**Issue by pmurias** [perl6/doc#2162]
## The problem

We are mixing together the documentation of a class and a syntactic feature

## Suggestions

Move out the description of declaring new ops to a separate page where it can grow

**Comment by JJ** [comment]
Are you referring to [this page](https://docs.perl6.org/type/Sub)?
Do you mean moving the introductory example somewhere else? Or the introductory section in general?

**Comment by AlexDaniel** [comment]
Yeah, so the third example (pretty much right on top of the page):

```
sub postfix:<♥>($a){ say „I love $a!“ }
```
If I came there wanting to learn about subs, I probably didn't want my mind to be blown like that :)

I think a special page for defining custom operators is a good idea, then we can link from the Sub page and mention that operators are functions too.

**Comment by pmurias** [comment]
The stuff about declaring operators should be moved out.
