### ISSUE TITLE
Stop using the interrobang in unrelated Sub traits example ‽

### ISSUE THREAD

**Issue by pmurias** [perl6/doc#2163]
## The problem

Interrobang is an rare character that does display in some fonts and looks like a potentially syntactic element

## Suggestions

Replace the example. 
Using something better than an nonsense world oi is also better.

**Comment by AlexDaniel** [comment]
@pmurias are you satisfied with the commit above? Or did you mean something else?

**Comment by JJ** [comment]
The commit does exactly as requested. If there is anything else, it's
better to edit the title

**Comment by pmurias** [comment]
@AlexDaniel The commits solves the issue ;)
