### ISSUE TITLE
Is type-groups.json used somewhere?

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2164]
## The problem

There's [this file](https://github.com/perl6/doc/blob/master/type-groups.json) which is not referenced anywhere else in the repo.

## Suggestions

Maybe ask @gfldex its purpose, and delete or maybe move it to a subdirectory.

**Comment by coke** [comment]
Looking at the logs: 

commit 57d5071f
Author: Wenzel P. P. Peppmeyer <wenzel.peppmeyer@gmx.de>
Date:   Sun Jan 15 15:55:46 2017

    In preparation to make /type.html decent, first shot at grouping types.

But it appears to have never been used.

Instead of moving it elsewhere in the repo, I recommend creating branch that contains it, and deleting it from master.

**Comment by coke** [comment]
File is in the "type-groups" branch
