### ISSUE TITLE
The "1-item list" in Any docs is inaccurate

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2176]
(I think I filed some general "Any improvement" Issue before, but I think it got fixed)

A lot of routines on [`Any` docs](https://docs.perl6.org/type/Any) (eg. `.classify`) say "Treats the Any as a 1-item list". However that's inaccurate.

I believe the actual behaviour is *"coerces the object to a list by calling `.list` method"*. While by default, it does indeed create a 1-item list with the object in it, nothing stops users declaring their own `.list` returning multiple items.

The "Treats the Any as a 1-item list" phrase suggests that even if you define your own `.list` the methods would not call it and still treat your object as 1-item list.

```perl6
<Zoffix_> m: class Foo { method list { <a b c> } }; dd Foo.classify: * eq "a"
<camelia> rakudo-moar 9dce63318: OUTPUT: «(my Any %{Any} = Bool::False => $["b", "c"], Bool::True => $["a"])␤»
```

**Comment by MorayJ** [comment]
So, could they say "Coerces the Any to a list by calling its .list method. By default, this will be a 1-item list"

Or is the 1-item list not necessary information? Or could it be more explicit in saying what that default list item is? (though I don't know what it is...asking)?

**Comment by zoffixznet** [comment]
> Or is the 1-item list not necessary information

I'd say that's unnecessary in all the methods but the actual docs for `.list`

**Comment by zoffixznet** [comment]
Fixed by the merged PR
