### ISSUE TITLE
Search results from `foo-to-p6` pages should be clearly marked

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2179]
I went to look up docs on Perl 6's constants. In the first result, I see entry "constant" under heading "Constant". Perfect! What could it possibly be other than the docs for **the** language's constants?

The [page the result links to](https://docs.perl6.org/syntax/constant), however, is for users of a different language that I'm not even using, confusingly showing examples with `use constant`.

IMO, the results from pages that aren't main documentation for the language, such as "$language to Perl 6" tutorials, should not be mixed in with the results for the main language. They should have a better title in the search results… "Perl 5 to Perl 6 guide" or something.

![image](https://user-images.githubusercontent.com/5747918/42778500-43adcc5a-890b-11e8-8f9e-cda5e504b980.png)

**Comment by coke** [comment]
See also #1410

**Comment by coke** [comment]
Looks like this particular confusing result is no longer present, and we have #1410 to track any remaining ones. Closing ticket.
