### ISSUE TITLE
Document | in proto signatures

### ISSUE THREAD

**Issue by MadcapJake** [perl6/doc#218]
The language/function page shows a `|`at the end of a signature but does not explain what it does.  In the signature page there is a mention that it "indicate[s] that the routine's multi definitions can have any type constraints."  However, this really could use more explaining and at the very least a link to this inside the language/function page (though more would be better).

**Comment by awwaiid** [comment]
http://docs.perl6.org/type/Signature#Capture_Parameters is the mention with some detail, and http://docs.perl6.org/language/functions#proto is the spot where it is used.

**Comment by awwaiid** [comment]
I added some clarification, hopefully it makes it better.

**Comment by MadcapJake** [comment]
Yes that was perfect, thanks @awwaiid !
