### ISSUE TITLE
No docs on the ordering of .keys and .values methods of a Hash

### ISSUE THREAD

**Issue by kjkuan** [perl6/doc#2182]
## The problem

It's not clear that a `Hash`'s `.keys` and `.values` both return objects in the same order such that you
can  update a `Hash` with another like this:
```
[23:56] <Juerd> p6: my %orig = :1a, :2b; my %new = :5b, :6c; %orig{ %new.keys } = %new.values; dd %orig
[23:56] <+camelia> rakudo-moar 49363d690: OUTPUT: «Hash %orig = {:a(1), :b(5), :c(6)}␤»
```

**Comment by b2gills** [comment]
It has been questioned if this is something that should be relied upon.

The answer is of course: **yes**.

In Synopsys 09 is the following text:

[<blockquote> … Unless %hash is altered in any way, successive calls to .keys, .kv, .pairs, .values, or .iterator will iterate over the elements in the same order.</blockquote>](https://design.perl6.org/S09.html#line_1200)
