### ISSUE TITLE
new manage-page-order.p6 script

### ISSUE THREAD

**Issue by coke** [perl6/doc#2185]
These are think should be done:

* Move the p6 script be moved to the util/ directory
* Add the new makefile target should be added to PHONY.
* Fix .gitignore to ignore these newly generated files

Should be considered:

* do this as part of the build process (on master, htmlify.p6) - (in coke/build branch, I'm working on moving things out of htmlify and using sake, happy to do that there without moving things around on master first)
* Don't generate files under the docs/ folder. we already have a confusion under html of generated vs. checked in files.  Generated artifacts might want to go elsewhere.

**Comment by tbrowder** [comment]
Is htmlify.p6 to be moved to /util also?

**Comment by tbrowder** [comment]
My proposal (and I’m working on a PR for it) is to:

1. rename “***doc***/“ to “***doc-src***/“
2. copy or generate a transformed copy of ***ALL FILES*** in “***doc-src***/“ to matching dirs in “***build***/“
3. point “***pod2bigpage***” and “***htmlify.p6***” to “***build***/“ for the build

We can leave the “***html***/“ dir alone for now.

**Comment by coke** [comment]
I had two very specific items to address here (just added a third).

There's a lot of scope creep in the comments here, but since we've opened the can of worms: my thoughts (again, this is bigger than I am proposing for just this ticket, which was just in regards to the things that were just added to the repo):

* leave doc/ alone - I'm not sure what the rename here was intended to address 
* I'm working to move most of htmlify.p6 into a separate (hopefully more parallelizable build using sake). We could move it, but it's not part of this ask.
* what's to transform? it's not a one to one for file in doc to built file.
* have html/ just contain the built site, not a combination of checked in content and generated files.
* ok to have a build/ step that contains intermediate generated files. I'm wondering if we even need these generated files, but that's beyond the scope of my ask here.
* Do we even need to have these files generated? why can't we do the sort order in the htmlify logic itself?

But anything aside from those 3 comments should be done in another ticket.

**Comment by tbrowder** [comment]
Keeping doc name is not a problem, but using ***htmlify.p6*** to provide the sort is IMHO a problem (by file name?, title?, change the order easily?). That’s why I came up with the control file: make it a bit easier for a human to choose or modify the sort order. 

The ***pod2bigpage*** exec looks at only one source dir so all files to be sourced need to be in one dir, hence my choice of copying direct or transforming the pod6 source files to the intermediate dir ***build***.

**Comment by JJ** [comment]
El mié., 18 jul. 2018 a las 23:44, Tom Browder (<notifications@github.com>)
escribió:

> Keeping doc name is not a problem, but using *htmlify.p6* to provide the
> sort is IMHO a problem (by file name?, title?, change the order easily?).
> That’s why I came up with the control file: make it a bit easier for a
> human to choose or modify the sort order.
>
> The *pod2bigpage* exec looks at only one source dir so all files to be
> sourced need to be in one dir, hence my choice of copying direct or
> transforming the pod6 source files to the intermediate dir *build*.
>

Maybe we could change that one... If you open an issue there, I could try
to have a look at it.

**Comment by tbrowder** [comment]
I think that changing pod2bigpage now would be a mistake. It looks like it relies on its single source dir to define the final page layout. And htmlify also relies on the directory structure.

A final solution, as has been mentioned elsewhere, is probably a dynamic one, but one baby step at a time in the interim.

**Comment by JJ** [comment]
Is this ripe for closing?

**Comment by JJ** [comment]
Ping? :speaker:
