### ISSUE TITLE
pod to bigpage needs to be part of this repo

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2193]
## The problem

The Pod::To::BigPage is for the doc site and doc depends heavily on it. The doc repo may be its only user.

**Comment by tbrowder** [comment]
Actually, all we need is our own copy of prog "pod2onepage" since we already include the module. That way we can modify it for our needs (unless the library needs modifying).

**Comment by JJ** [comment]
That's also an issue with pod2onepage. There's a lot of stuff in there
that's not in the library. But I guess it would be a good solution. We
could always port it back to the module.

**Comment by tbrowder** [comment]
Okay, how about putting a copy of just **pod2onepage** in **util**/ and modify it as needed here?

**Comment by JJ** [comment]
That could work...

**Comment by tbrowder** [comment]
In my forthcoming doc PR I have copied it and renamed to to **pod2onepage.p6**.  I’ll remove it before hand if there is opposition.

**Comment by rafaelschipiura** [comment]
@tbrowder why do you want to copy it instead of just changing it in the other repo?

**Comment by coke** [comment]
There is opposition.

**Comment by coke** [comment]
What problem are you trying to fix?

**Comment by tbrowder** [comment]
One thing I added was a debug option to stop processing after a small subset of files so I could more eaily see overall doc build results.

**Comment by JJ** [comment]
But that's a feature that could also be useful in the original repo.

**Comment by tbrowder** [comment]
Yes, and, as you said, it could be ported back to the original program.

**Comment by rafaelschipiura** [comment]
So close this issue?
