### ISSUE TITLE
Perl 6 in a nutshell missing

### ISSUE THREAD

**Issue by jmaslak** [perl6/doc#2196]
## The problem

This page: https://docs.perl6.org/language/004-5to6-overview

Has a link to this page, which gives a 404: https://docs.perl6.org/language/5to6-nutshell

**Comment by JJ** [comment]
All URLs have changed... Thanks for spotting it.

**Comment by JJ** [comment]
Related #2190

**Comment by rafaelschipiura** [comment]
It's working now, after the changes were reverted.
