### ISSUE TITLE
travis set up appears to be wrong for current build tool

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2198]
## The problem

A “make gen-pod6-source” step **must** occur before htmlify.p6 is run.

**Comment by JJ** [comment]
I'll have to recreate the docker container... and the rest of the configuration.

**Comment by tbrowder** [comment]
It looks like the travis build is good, but the docker is not. The website is still not rendering correctly.

**Comment by JJ** [comment]
There are two separate issues here. I'll try to find out what's the problem.

**Comment by TisonShadowsong** [comment]
could we ban docker build for now? i think we need a workaround to make website render works for now. and then @JJ  can create a branch to see how to solve the docker issue.

**Comment by JJ** [comment]
It's in the works, only I don't have time to fix it right now. Since we
have shippable and the binary-based test working, I don't think it's
essential. I'll try to fix it in a couple of days, big deadline tomorrow...

**Comment by TisonShadowsong** [comment]
@JJ  thanks!

**Comment by TisonKun** [comment]
@JJ many thanks!

**Comment by JJ** [comment]
My pleasure. Sorry for not having been able to do it before.

**Comment by tbrowder** [comment]
Closed as fixed.
