### ISSUE TITLE
https://docs.perl6.org/language/unicode_entry 404: Page Not Found

### ISSUE THREAD

**Issue by shishini** [perl6/doc#2200]
I googled "perl6 typing special chars"

Top result was this link 
https://docs.perl6.org/language/unicode_entry 

But it returns page now found

The second link from google is also page now found
https://docs.perl6.org/language/unicode_ascii

**Comment by TisonShadowsong** [comment]
@shishini I find it becomes https://docs.perl6.org/language/019-unicode_entry now.

@tbrowder why is there such strange number? could we get rid of it later? it looks magic number is not a good idea.

@moritz for now, could we set redirect or something to fix this? I don't know how to redirect.

**Comment by AlexDaniel** [comment]
I'll close this as a dup. See #2190 and other linked tickets for more info. The numbers are no longer there but the latest build [failed](https://docs.perl6.org/build-log/build-2018-07-20T19:40+00:00.log), so the fix didn't go live yet. Hopefully will be fixed today.
