### ISSUE TITLE
Clean directories when building the site

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2203]
## The problem

When a whole directory with all its files were deleted, it started to [cause problems](https://github.com/perl6/perl6-pod-to-bigpage/issues/29) with site construction

## Suggestions

Insert `git clean -fd` where needed so that it does not happen again in the future. In general, untracked directories are inoffensive, but sometimes they create files that are then processed and cause errors.

**Comment by JJ** [comment]
Related: #2202

**Comment by stmuk** [comment]
I think using "git clean" in the makefile "html" target is too dangerous since it's likely to delete developers' work in progress. 

Neither should we be assuming this repo has been deployed via git since we might have CPAN tarballs deploys one day.

It  would be safer to explicitly delete files and directories.

**Comment by JJ** [comment]
it's going to be git clean -fd. It just deletes all files and directories
that are no longer under source control. In fact, html directory has just a
few files under git control.

**Comment by tbrowder** [comment]
Closed as fixed.

**Comment by JJ** [comment]
Um, not really. I'll have to add something to the update and sync scripts.

**Comment by zoffixznet** [comment]
> @JJ JJ closed this in 2e99de6 5 hours ago

This appears to delete files generated during the build process, such as `app.js`. Reverted in https://github.com/perl6/doc/commit/f2742b8d8eeee2e3e44d45e71b1ab2d8c349d391 to see if it unbusts the broken site.

**Comment by zoffixznet** [comment]
nm, it's something else

**Comment by zoffixznet** [comment]
> nm, it's something else

Actually it *is* that commit (https://github.com/perl6/doc/commit/2e99de64569ceee97ed1cfbd575f70025f53004a) that's nuking the `html/dir`. 

On my first test, the cronjob was just using the old version of that file, before fetching with my commit

**Comment by JJ** [comment]
Right, but the problem is that it's not created by the scripts that generate the js files there... git clean -fd is needed because that's what was causing the previous build error with a directory that was created under Language, was deleted in the source tree and not built again...

**Comment by JJ** [comment]
The problem it shows in this log https://docs.perl6.org/build-log/build-2018-07-24T23:02+00:00.log does not seem to have anything to do with removing html/js. But it failed, and thus html/js was not created all over again for some reason...
