### ISSUE TITLE
The Grammar pages do not mention the implicit setting of $/.

### ISSUE THREAD

**Issue by Xliff** [perl6/doc#2210]
## The problem
The Grammar pages do not mention the implicit setting of $/.

## Suggestions
This wording should be added somewhere in the routine sections for parse and subparse:

"This routine, like m//, implicitly sets $/".

**Comment by TisonKun** [comment]
Yes, besides, we now have two page about Grammars, that is "Grammars" and "Grammars Tutorials".

**Comment by JJ** [comment]
Not sure that would go to the Grammar pages. Either $/ gets a page by
itself, or to regexes...

**Comment by Xliff** [comment]
I was planning on adding this to the routine descriptions for parse and subparse.

**Comment by JJ** [comment]
It's OK it's mentioned there, but `$/` is also set by regexes.
