### ISSUE TITLE
git clean

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#2216]
## The problem
Build process deletes files being worked by not yet committed to version control. This will destroy people's work in progress.

**Comment by JJ** [comment]
Where does that happen? What part of the build process does that?

**Comment by rafaelschipiura** [comment]
@JJ It's about your own commit: https://github.com/perl6/doc/commit/2e99de64569ceee97ed1cfbd575f70025f53004a

**Comment by JJ** [comment]
That's not user-facing code. No make target launches that script. It's only
done from a cron job in the production site. There's 0 possibility it will
destroy people's work, since it's not intended to be used in any
development environment.

**Comment by rafaelschipiura** [comment]
OK, thanks for the clarification, @JJ

**Comment by JJ** [comment]
No problem. Thanks for reviewing the commit :-)
