### ISSUE TITLE
Searching for $/ in doc.perl6.org redirects to non existing page

### ISSUE THREAD

**Issue by nxadm** [perl6/doc#222]
When searching for $/ in the searchbox, the javascript suggests "Variable: $/". That points to http://doc.perl6.org/syntax/%24%2F (not existing) instead of http://doc.perl6.org/language/variables#The_%24%2F_Variable.

Other variables, e.g. $$, do not have this problem.

**Comment by nxadm** [comment]
It looks like a duplicate of duplicate of #155.

**Comment by zoffixznet** [comment]
Indeed it is. Closing. Thanks for reporting anyway.
