### ISSUE TITLE
Use sentence case throughout titles and headings

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2223]
## The problem

This is now in the [style guide](https://github.com/perl6/doc/blob/master/writing-docs/STYLEGUIDE.md), although hidden under the reference to the Wikipedia manual of style.

## Suggestions

Sentence case implies that only the first letter of a title or heading is to be capitalized. This needs to be done consistently throughout all the documentation. Done already for #1945 (which is closed), but there are zillions of other documents with the same problem.

**Comment by MorayJ** [comment]
What would count as proper names when doing this? So from NativeCall.pod6 we've got:

`Basic use of Pointers`

and:

`Library Paths and Names`

and in numerics.pod6:

`Printing Rationals`

and:

`Available Allomorphs`

Should types be considered proper names?

Perl 6 is a proper name as that's in the guide, I think.

**Comment by MorayJ** [comment]
I've been looking at this a bit more and proposing adding this, or something similar, to the style guide:

It would mean changing all of 'method _method-name_' to 'Method _method-name_' in the Types section (eg [https://docs.perl6.org/type/Any](url)

That has been so methodical, I'm not sure that there's not a different rule being followed, which could lead to friction.

I'm happy to take this on, but I want to make sure I'm not going to end up in editing tennis with someone...
____________

All titles, subtitles and headers (=TITLE, =SUBTITLE, =head[1..Inf]) should be written in sentence case.

Sentence case has a capitalised first word with all following words fully lowercased, except for words which are proper nouns.

If a word is a proper noun, it should be written with the expected casing.

A proper noun is a noun that, in its primary application, refers to a unique entity.

Example: "Difference between methods and functions".

Methods and functions are common nouns and so do not have leading upper case letters unless at the start of a sentence.

Example: "What is Perl 6 and what is Rakudo Star?"

Perl 6 and Rakudo Star are unique entities and so are proper nouns.

Examples of proper nouns:

The names of most computer languages (Perl 5, Perl 6, Python, Lisp...)

The names of people (Larry Wall, Guido van Rossum...)

Functions, attributes, routines and methods whose signature has a specific letter casing.

Example: "Method ACCEPTS"

Example: "Method Str"

Don't use function, attribute, routine or method names as the first word in any headline.

Example: "Add - a method" # WRONG! Don't use this as a headline as the sentence case rule has changed it

Example: "Method add" # RIGHT! It's clear that the method is called 'add'

Titles, subtitles and headers should not end in a full-stop/period. Ideally they should not end with question marks or exclamation marks either.

_________________________________________________

**Comment by JJ** [comment]
In the case of method, it's also the name of a type declaration, `method`. So it makes sense to keep it in lowercase.

**Comment by MorayJ** [comment]
Ok, great. That's me thinking out loud to make sure I don't go off on a huge tangent...I'll do some of the 'Language docs that seem fairly clear cut.

**Comment by JJ** [comment]
Thanks!
