### ISSUE TITLE
A shortcut for named arguments is poorly documented

### ISSUE THREAD

**Issue by sarna** [perl6/doc#2229]
## The problem
There is a shortcut for calling a sub with named arguments when the arguments and variables have the same names - `foo(:$x)` instead of `foo(x => $x)`.
It's hard to find it, though. It's only present [here](https://docs.perl6.org/type/Signature#index-entry-named_argument) as a cryptic `$ = :(:$a);`.
## Suggestions
There should be an example - or a section - telling the reader that they can write `foo(:$x)` instead of `foo(x => $x)`.

**Comment by Scimon** [comment]
https://docs.perl6.org/language/functions#Arguments 

The docs here also cover it to a certain extent.
