### ISSUE TITLE
Proc.run is not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2233]
The https://docs.perl6.org/routine/run docs are a page long and show a bunch of stuff, but unless you read all of them and notice the very last sentence mentioning `Proc`, you may miss that `run` takes arguments like `:enc` and stuff.

Those should be at least hinted at in the shown signature and perhaps the note that it takes a bunch of args should be moved closer to the start of the prose.

**Comment by JJ** [comment]
Actually, it's documented in role IO but that's wrong, because it's not there (or is no longer there).

**Comment by JJ** [comment]
Related: #2059
