### ISSUE TITLE
The documentation for prefix let repeats itself twice

### ISSUE THREAD

**Issue by hakonhagland** [perl6/doc#2237]
The documentation for [prefix `let` ](https://docs.perl6.org/routine/let) repeats itself, and the same code example is shown twice.

**Comment by zoffixznet** [comment]
That might be on purpose. It's documented twice: on [*Variables* tutorial](https://docs.perl6.org/language/variables#prefix_let) and on [*Operators* tutorial](https://docs.perl6.org/language/operators#prefix_let)

But when you look [at the docs just for `let`](https://docs.perl6.org/routine/let) it's showing all the docs it can find, which in this case are the two duplicated sections from two different tutorials.

**Comment by JJ** [comment]
Still, as #1924 says, it's probably better to rephrase one of them. The origin of some docs is copypasta, but that does not need to show.
