### ISSUE TITLE
Some FAQ TOC links are broken

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2245]
Possibly affects TOC links elsewhere.

If you go to https://docs.perl6.org/language/faq the last 4 items in the TOC (e.g. "Why is Perl 6 called Perl?") are broken links and don't actually jump to the appropriate section.

**Comment by JJ** [comment]
The problems seems to be the automatic transformation of no-break
whitespace to mime-encoding in the TOC generation, while it seems to be
transformed to normal whitespace when actually generating the anchor. That
probably means it affects anything that includes it.
