### ISSUE TITLE
Use HTTPS URLs, where available

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2246]
We have a bunch of HTTP URLs in the docs:
```
2018.06 zoffix@VirtualBox~/R/doc (master)$ grep -FIRn 'http://' . | wc -l
1705
```

It's possible many of them actually have HTTPS versions (like [here](https://github.com/perl6/doc/commit/426579ee538737983665c822b854caeb97636213)) and perhaps we should link to HTTPS directly.

**Comment by JJ** [comment]
And we should also include a test so that it does not happen, if possible,
whitelisting those that have no alternative.
But, wow, 1705 is a lot.

**Comment by zoffixznet** [comment]
> But, wow, 1705 is a lot.

Tho in `doc/` dir it's just:
```
2018.06 zoffix@VirtualBox~/R/doc (master)$ grep -FIRn 'http://' doc | wc -l
62
```

And after running `make clean`, the whole repo:

```
$ grep -FIRn 'http://' . | wc -l                                                                                                                                                                                      
197
```

So it looks like something gens a ton of HTTP URLs or something.

**Comment by JJ** [comment]
El jue., 9 ago. 2018 a las 12:46, Zoffix Znet (<notifications@github.com>)
escribió:

> But, wow, 1705 is a lot.
>
> Tho in doc/ dir it's just:
>
> 2018.06 zoffix@VirtualBox~/R/doc (master)$ grep -FIRn 'http://' doc | wc -l
> 62
>
> And after running make clean, the whole repo:
>
> $ grep -FIRn 'http://' . | wc -l
> 197
>
> So it looks like something gens a ton of HTTP URLs or something.
>

Chalk another one for htmlify.p6...

Also there are lots in README.md and translations... Multiplied by 7, no
less.

**Comment by MorayJ** [comment]
That should be it for all of the ones that can currently change to https in doc/Types and doc/Language. Nothing in doc/Programs. I get the idea that the others are generated so need a different approach...
