### ISSUE TITLE
No apparent buf8/16/32/64 documentation

### ISSUE THREAD

**Issue by jmaslak** [perl6/doc#2264]
## The problem

Searching for "buf8" on docs.perl6.org returns no data.

## Suggestions

These buffer types should probably be documented.

**Comment by JJ** [comment]
They definitely should. Thanks.

**Comment by JJ** [comment]
There are mentions here and there, but it's definitely not described or indexed. It's [here](https://docs.perl6.org/language/nativecall#Short_tutorial_on_calling_a_C_function), for instance.
