### ISSUE TITLE
submethod is not indexed

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2265]
## The problem

(seen from  #1606) `submethod`s are apparently not indexed, such as this one:

    =head2 submethod DESTROY

in [IO::Handle](https://docs.perl.org/type/IO/Handle).

There's just this one, so maybe no one has noticed

## Suggestions

Check out what's wrong with it, and add other submethods (with differentiated implementation) somewhere if needed.

**Comment by coke** [comment]
Guessing these two lines:

https://github.com/perl6/doc/blob/master/htmlify.p6#L83

https://github.com/perl6/doc/blob/master/htmlify.p6#L915
