### ISSUE TITLE
Create a HOWTO for newcomers to the repo

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2266]
## The problem

During the BoF meeting in TPCiG, it was suggested that a how to guide to get into the documentation would be good.

## Suggestions

Create it as a markdown or POD6 page so that everyone can follow it. Link all relevant pieces of knowledge that are needed, from the POD6 specification to how to work with PRs and issues.

**Comment by finanalyst** [comment]
I just wrote a post on perl6 users and suggested this. I have begun to review documentation with the intent of drafting something.

**Comment by JJ** [comment]
Great. It will really help this hacktoberfest, and beyond.
