### ISSUE TITLE
Revise phasers page

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2268]
## The problem

[This page](https://docs.perl6.org/language/phasers) includes the `DOC` phasers in the index, but not in the table, and the role phasers the other way round. There might be some other phasers I'm missing. 

## Suggestions

We also need to include #1606, but make an overall revision for coherency and updatedness.

**Comment by MorayJ** [comment]
Phasers #2289

Pull request failed test, but think I saw that tests sometimes fail when they shouldn't? But haven't merged it in case there's an issue.

I could only see DOC missing and the COMPOSE hidden so have fixed those. More on here than on the Synopsis page (https://design.perl6.org/S04.html#Phasers)

**Comment by MorayJ** [comment]
Retriggered the test and it passed, so merged and closing this issue.
