### ISSUE TITLE
Document COMPOSE phaser as NYI (for now)

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2281]
## The problem

It's indicated as such in the [source code of the phasers page](https://github.com/perl6/doc/blob/master/doc/Language/phasers.pod6):

```
# NYI
# =head1 Object phasers
#
# =head2 X<COMPOSE|Phasers, COMPOSE>
#
# Runs when a role is composed into a class.
```

## Suggestions

Check current status and document if it's been added.

**Comment by JJ** [comment]
Far as I can tell, it's still not implemented.

**Comment by jnthn** [comment]
I've never seen the point of it, to be honest. The body of a role runs at the point a role is composed into a class.

**Comment by MorayJ** [comment]
I have uncommented the COMPOSE for the time being. I think it should be mentioned throughout, or not at all.

**Comment by MorayJ** [comment]
As nobody has reacted badly to this, I'll close this and if it seems a good idea to remove all the references to COMPOSE then it can be opened as another issue...
