### ISSUE TITLE
cmp-ok in Testing is not described correctly.

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#229]
The [current description](http://docs.perl6.org/language/testing#Comparison_of_expected_and_actual_output) suggests passing operators as strings should work. It does work for `'~~'`, but not for `==`. We should also include a way to include other operators like so:
`cmp-ok 42, &infix:[ '==' ], 42, 'ayup'`

EDIT: this actually seems to be a bug in `cmp-ok`: http://irclog.perlgeek.de/perl6/2015-12-07#i_11670988

**Comment by AlexDaniel** [comment]
(was fixed last night)
