### ISSUE TITLE
Example in Tutorial 101-basic needs an enhancement

### ISSUE THREAD

**Issue by davelikestorock** [perl6/doc#2310]
doc/doc/Language/101-basics.pod6

The first perl6 example that used to process 'scores.txt' needs to add a constraint to skip a blank line (or empty line). User that copies and pastes the content of 'scores.txt' might somehow introduce a blank line (by unconsciously stroking a 'return'); While this will lead the example to fail due to unexpected line pattern. So I would suggest to add a line to avoid this condition.

**Comment by zoffixznet** [comment]
Thanks. Fixed in https://github.com/perl6/doc/commit/f9ba0ae8d78d3078e09bfbe176cde484ba18a7a6
