### ISSUE TITLE
`start` ain't a sub

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2322]
Skimming https://docs.perl6.org/language/concurrency I saw this sentence *"This is considered to be such a commonly required pattern that it is also provided as subroutines"*, in the context of `Promise.start` and `start`

However, `start` is not a subroutine, it's a statement prefix. The docs should be corrected to reflect that in that spot and any other that calls `start` a sub.

**Comment by jonathanstowe** [comment]
On a somewhat related note there doesn't appear to be any reference to the use of ```await```  with ```Channel``` or ```Supply```, I guess that probably wants to be another issue so someone can pick it up separately. (When the document was originally created it only worked for ```Promise````)
