### ISSUE TITLE
Links broken on Testing page Reference section

### ISSUE THREAD

**Issue by CurtTilmes** [perl6/doc#2328]
I'm not sure if this is a broader issue, or just on this page -- just something I noticed.

On this page: https://docs.perl6.org/language/testing
there is a reference section: https://docs.perl6.org/language/testing#Reference
which lists the main calls, each of which used to link to the section below that described them.

e.g. `plan` links to https://docs.perl6.org/language/testing#index-entry-plan-plan%28%24count%29.html

Those links no longer resolve to valid anchors.

For example, the anchor for plan should now be https://docs.perl6.org/language/testing#Test_plans

**Comment by JJ** [comment]
The general indexing and formatting of that page does not seem to be correct. For instance, `ok` and `nok` are indexed as `ok (nok)`, plus `=item` and not `=head2` is used for every method. That reference section you mention, for instance, would be better automatically generated if the headers are correct. Thanks again for the report, I will try to fix that. I don't think, OTOH, it's a general issue.

**Comment by JJ** [comment]
I should have realized when I did #1985

**Comment by JJ** [comment]
And so yes, it's a broader issue, only it's not broadened in the sense I expected initially...

**Comment by zoffixznet** [comment]
From https://github.com/perl6/doc/commit/12908568a157d43574638b19eea907823eba6d2a

> in the new Test class description

There is no `Test` class though. `Test.pm6` is a module.

**Comment by JJ** [comment]
Right. Will fix that.
