### ISSUE TITLE
Change text in chart from "vector" to something a bit more informative

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2332]
## The problem
![captura de pantalla de 2018-09-25 10-32-03](https://user-images.githubusercontent.com/500/46002407-476d7b80-c0ae-11e8-848e-642c21d58835.png)

As said in #2331 by @toddandmargo, and also in #2315, it's not clear that clicking on "vector" takes you to the SVG file

## Suggestions

As suggested by @toddandmargo, 

> change the expando button’s name from “Stand-alone image: vector” to “Expand Chart” or just “Expand”.

I can't think of anything better. Any suggestion is welcome

**Comment by JJ** [comment]
Would "Download or view full-size vector graphics version" be better?

**Comment by JJ** [comment]
Expand or enlarge *above* chart or graph?

**Comment by ToddAndMargo** [comment]
On 09/25/2018 10:33 PM, Juan Julián Merelo Guervós wrote:
> Expand or enlarge /above/ chart or graph?

Below and center justified under the small graphic

**Comment by JJ** [comment]
Let me see if I can do that...
