### ISSUE TITLE
RFE: wording change to Inf in the documentation

### ISSUE THREAD

**Issue by ToddAndMargo** [perl6/doc#2341]
#https://docs.perl6.org/type/Num#Inf

Proposed addition to "Inf":

     The "value" Inf (Infinity) represents "without bound" or  "no limit" (meaning "all possible values") when used as an argument.  It is typically used in as an argument in routines where it represents "everything" or " no bounds", depending on the context that it is used.

Proposed removal:

     The value Inf is an instance of Num and represents value that's too large to represent in 64-bit
     double-precision floating point number (roughly, above 1.7976931348623158e308 for positive
     Inf and below -1.7976931348623157e308 for negative Inf) as well as returned from certain
     operations as defined by the IEEE 754-2008 standard.

Reason:

In the "context" that "Inf" is for in Perl 6, it falls into the category of "unicorns":  things that do not really exist.  "Inf" shares this with "Nil".  The proposed addition will quickly clue the reader into what "Inf" actually is used for.  It also conforms to the mathematical definition of "infinity".

The removed text is just a distraction and not actually even how Inf (or Nil) is used in Perl.  (Inf is used with string too and other things too.)  Leave the definition of how to create numbers to the developers.   Including this only confuses the reader.

**Comment by JJ** [comment]
It represents "no limits" independently of being used as an argument.
The current definition could be (slightly) improved by grounding it to the common, or mathematical, definition, but I fail to see how a precisely worded definition as it is now would help anyone.

**Comment by ToddAndMargo** [comment]
On 10/2/18 11:14 PM, Juan Julián Merelo Guervós wrote:
> It represents "no limits" independently of being used as an argument.
> The current definition could be (slightly) improved by grounding it to 
> the common, or mathematical, definition, but I fail to see how a 
> precisely worded definition as it is now would help anyone.

That is one of those "if you already know it, you don't need
to know it, again".  Don't always presume everyone knows what
they are doing when they are looking for wisdom.  Picture me
in your mind when you are trying to figure out if you have
given enough of an explanation.

The mathematical definition was what make me realize what you
guys were getting at. And you know me, I can be thick as a rock
at times.  So, if it worked for me, it should work for most
everyone else arriving there looking for wisdom.

And the definition of an over-run real number really confused things.

A little off the subject, but since you told me ~70% are coming from
Perl 5 to Perl 6, don't always presume they realize everything starts
counting from zero.  (p5's m/ starts at $1)
