### ISSUE TITLE
Show the slurpy part of join in examples

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2344]
## The problem

Pointed out by @CIAvash in [the perl 6 users list](https://www.nntp.perl.org/group/perl.perl6.users/2018/09/msg5861.html).

## Suggestions

Add an example of this type of usage.

**Comment by CIAvash** [comment]
Maybe they should be combined into one example? or is it too much information?
`join ', ', <a b c>, 'd', 'e' , 'f'`

**Comment by JJ** [comment]
Not really. It's still in my editor, I'll add that.
