### ISSUE TITLE
Reindex functions in other languages

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2355]
## The problem

For instance, `raw_input` in Python is indexed. Clearly labeled, but will someone in the Perl 6 documentation look for a Python function? You can find it anyway if you use Google, and it will only contribute to pollute the results

## Suggestions

Consider if it's worth the while to keep them, and if it's not, erase them. 

I'll be taking a poll, please :+1: to let them stay, :-1: for eliminating them.

**Comment by lizmat** [comment]
I find that example confusing, as it doesn't actually mention "raw_input" in the text.  So either it *should* mention that in the text, or it should not be indexed.  I think that if a term is actually mentioned in the text, it could very well be indexed (clearly labelled as being from another language if it is).

**Comment by JJ** [comment]
El jue., 4 oct. 2018 a las 14:01, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> I find that example confusing, as it doesn't actually mention "raw_input"
> in the text. So either it *should* mention that in the text, or it should
> not be indexed. I think that if a term is actually mentioned in the text,
> it could very well be indexed (clearly labelled as being from another
> language if it is).
>
>
Maybe the anchor is also wrong. If we keep it, we'll have to take care of
that.

**Comment by zoffixznet** [comment]
.oO( showing up at the bottom of search results in a "Foo-to-P6" section, same as with Perl 5 and other language results )

**Comment by JJ** [comment]
The vote has ben cast, and there's a clear majority for letting them stay. However, there are issues with placement (@zoffixznet ) and anchors (@lizmat ) so I change the issue to reflec that.

**Comment by JJ** [comment]
And, of course, the 5to6-perlfunc is special-coded in htmlify.p6, which is waiting for a refactor since #1823. So I don't think we can do that... 
However, the other languages pages are waiting for a rename #1923. So we might give those special names and process them in the same way.

**Comment by lichtkind** [comment]
Many will come (and came) from python and this documentation should work for them. Of course its not the main purpose but just add it when it makes sense.
