### ISSUE TITLE
Confusing Documentation around named parameters

### ISSUE THREAD

**Issue by barcharcraz** [perl6/doc#2359]
## The problem
I was reading the docs at https://docs.perl6.org/language/objects#Object_construction and I found the signature of `BUILD` confusing. I also noticed that https://docs.perl6.org/language/functions#Arguments does not really talk about the named parameter syntax much.

## Suggestions

A link to https://docs.perl6.org/language/functions#Arguments could be good from the object construction phase. It would also be good to have some documentation on how named parameters work and how they differ from pair constructors. It's not clear if they are a special syntax or a special case of something else.

**Comment by JJ** [comment]
You mean in the way it can define alias for attributes? I guess it wouldn't hurt to link that. Thanks for the report.
