### ISSUE TITLE
Improve the documentation of  POD links

### ISSUE THREAD

**Issue by lichtkind** [perl6/doc#2370]
## The problem

I read nothing about that issue in https://docs.perl6.org/language/pod#Links or in in Rakudo or in the converter module code. So this ticket my be one for Rakudo -I don't know yet. 

## Suggestions

 Naturally i would look to http://perldoc.perl.org/perlpod.html and suggest L < Label | SubDir / Module.pod  # anchor > (defaulting to .pod when no file ending) and as cherry on top L< Label | https://perl6.org # anchor> as well.

**Comment by JJ** [comment]
Sorry, but can you please clarify? Are you asking for a change in the Pod spec? Pods are parsed by perl6 itself...

**Comment by lichtkind** [comment]
I asked how to do a link from one POD file into another. Perl 5 can do it, so there is no reason Perl 6 can not. Either we forgot to document it, or (and myself looking into relevant sources think it is more probable) it is not implemented yet. This will be just an addition, not  a change.

**Comment by lichtkind** [comment]
yes, thank you,

than should we probably document this more clearly, because the example there is about an IP address not local file name and I assumed it just works for internet links and not local ones

**Comment by JJ** [comment]
OK, I'll change the issue to say that if you don't mind.

**Comment by lichtkind** [comment]
sure

**Comment by lichtkind** [comment]
implemented with 178d2e367586d6623e4c67f6be59767c53f12d3a

**Comment by lichtkind** [comment]
implmented with
5ddb34165f6ff786068cb0fc1b58ecc6acb8bea8 fixed: 
178d2e367586d6623e4c67f6be59767c53f12d3a
