### ISSUE TITLE
Most search results point to pages that do not exist

### ISSUE THREAD

**Issue by vrurg** [perl6/doc#2374]
## The problem

When searching for _handles_ from the search box there is a _handles trait_ item in the list of possible matches. Clicking in that item results in _404 - Not Found_ error.

## Suggestions

Perhaps a link in the index needs fixing.

**Comment by ryn1x** [comment]
@JJ if this is resolved does https://github.com/perl6/doc/blob/6f2d2afc6432e3a48916c544f414720bf7f260c5/Makefile#L11 need to be changed back to True?

Or does a new issue need to be opened to find a fix for this issue _while_ the categories are enabled?
