### ISSUE TITLE
Add allomorph examples to prompt

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2376]
## The problem

It's probably that it's not clear to the average developer what an [allomorph is in the context of prompt](https://docs.perl6.org/routine/prompt). 

## Suggestions

There are some links in the page that explain it, it's probably better if that's clarified by an example.

**Comment by zoffixznet** [comment]
:-1: as it's a minor detail and trying to illustrate some edge case where allomorphs vs. plain strings matter will just muddle up the existing example of the topical routine.

The word "allomorph" in that description is already a link and the prose mentions `val` routine as well. Anyone who cares about these minute specifics can follow the references.
