### ISSUE TITLE
Broken Link on https://docs.perl6.org/language/functions

### ISSUE THREAD

**Issue by arnesom** [perl6/doc#2402]
## The problem

The link "command line interface" on the bottom of the page (https://docs.perl6.org/language/functions) points to https://docs.perl6.org/routine/create-cli which does not exist.

## Suggestions

Fix the link to point to this page https://docs.perl6.org/language/create-cli

**Comment by nxadm** [comment]
Thank you! Fixed with commit https://github.com/perl6/doc/commit/15183a20265436cf344f122f0483cfd39aa06cee.
