### ISSUE TITLE
ensure all Perl 6 script and module names use .p6 or .pm6 suffix as appropriate

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#2419]
## The problem

Lots of example files and modules are referenced on the site, but many still use **.pl** and **.pm**
file name suffixes instead of the preferred **.p6** and **.pm6**, respectively.

## Suggestions

Find the offending files and rename them.

**Comment by JJ** [comment]
By grepping, I have found a couple of .pl6 and .pl

- [ ] `variables.pod6`
- [ ] `Attribute.pod6`

If you find some other, please add it to the list
