### ISSUE TITLE
Missing /language/create-cli and possibly other pages from live site

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2433]
https://colabti.org/irclogger/irclogger_log/perl6?date=2018-11-02#l866
> \<zostay\> FYI [https://docs.perl6.org/language/create-cli](https://docs.perl6.org/language/create-cli) is missing on docs.perl6.org

**Comment by JJ** [comment]
We turned on again the language-page sorting thing. This might be due to it.
