### ISSUE TITLE
Raku in the documentation

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2443]
## The problem

[Raku](https://docs.perl6.org/language/glossary#index-entry-Raku) has been adopted as an alternative name for Perl 6. How do we reflect that in the documentation?

**Comment by ash** [comment]
Ignore it.

**Comment by PWBENNETT** [comment]
Perl 6 is a perfect name for it. We didn't factionalize and fracture over a name change when Perl 5 broke compatibility with Perl 4.

**Comment by stmuk** [comment]
We should certainly *not* automatically replace every Perl 6 reference with "Raku" but I think a small number of top level references to "Perl 6 or Raku" should be added certainly in the FAQ and Glossary. 

Discussion of whether the alias should exist or whether the alias is wrong should be off topic. Larry is BDFL.

**Comment by tmtvl** [comment]
As long as the Raku alias isn't in widespread use, there is no real need to do anything. Maybe add a reference to it in the glossary for reference purposes.

**Comment by stmuk** [comment]
Merged #2444 for FAQ. We probably need a short glossary entry based on Larry's thoughts at 

https://colabti.org/irclogger/irclogger_log/perl6?date=2018-10-25#l584

Note he more explicitly announced the alias as "Raku" later on IRC.

**Comment by lizmat** [comment]
FWIW, I find it completely **UNACCEPTABLE** to remove comments.  That is **NOT** done.

**Comment by lizmat** [comment]
These were the comments that were removed:

ash: "ignore it" 
PWBENNNETT: "Perl 6 is a perfect name for it. We didn't  factionalize and fracture over a name change when Perl 5 broke  compatibility with Perl 4."

**Comment by zoffixznet** [comment]
> How do we reflect that in the documentation?

For at least the next 3-9 months, nothing needs to be added other than a glossary entry. Let the alias usage grow organically through user blogs and communications. In other words, let it become used frequently enough to warrant any further additions.

> in the glossary [...] We can expand it, though.

A lot of people are asking about how to pronounce "Raku", so that could be added (I pronounce it as "RAH-koo", but I guess TimToady would be the ruler of correctitude there)

**Comment by CIAvash** [comment]
There is an issue that needs to be addressed IMO, if you mention Raku everywhere and don't mention Perl 6, how are people going to find the language(website, docs)? I think this needs to be fixed before anyone starts using "Raku", otherwise people will be confused.

**Comment by MarkSenn** [comment]
I agree with CIAvash.  In https://marketing.perl6.org/id/1541379592/pdf_digital I read that "Raku Perl 6" is acceptable.  I'll probably write "Raku Perl 6" from now on but just say when not being recorded "Raku".  (My personal preference would be to go to "Raku" everywhere starting with the 6.d transition, but I understand there is enough pushback that that won't work.)

Please put the diacritical spelling and  recording of how to say "Raku" where and when you think is appropriate.  Thanks to everyone working on Raku Perl 6!

**Comment by tmtvl** [comment]
Rakudo is a single implementation, though. If a different implementation of Perl 6 (Watermelon Perl 6?) is released it might cause confusion if it isn't clear whether Rakudo Perl 6 refers to that specific implementation, or whether it is used to refer to the Perl 6 language in general.

**Comment by stmuk** [comment]
Can we close this thread? There is no relevent discussion of the original topic.

**Comment by lizmat** [comment]
You mean, rather than delete comments?

**Comment by stmuk** [comment]
@lizmat If you want to rant please do this elsewhere and don't spam this issue.

**Comment by tmtvl** [comment]
I would suggest closing the issue after we get the correct pronunciation from Larry.

**Comment by labster** [comment]
I'm pretty sure that Raku is pronounced らく.  I hope you're all up for pronouncing [ɾ].
