### ISSUE TITLE
Need to be root to install docs

### ISSUE THREAD

**Issue by tmtvl** [perl6/doc#2452]
## The problem
In the Build.pm6 we have the following line:

```Perl6
my $dest-pref = $*REPO.repo-chain.grep(/site/).first.prefix.child("doc");
```

But when I check my repo-chain, I get the following:

```Bash
% perl6 -e '.say for $*REPO.repo-chain;'
inst#/home/tmtvl/.perl6
inst#/usr/share/perl6/site
inst#/usr/share/perl6/vendor
inst#/usr/share/perl6
ap#
nqp#
perl5#
```

The `site` path requires root permissions to modify.

## Suggestions

If the user isn't root, I suggest installing the docs to their local prefix. We could get that by grepping either for `%*ENV<HOME>` or for a dotdir (I do not use rakudobrew, so I don't know if zef uses the same directory when installed with it).

**Comment by JJ** [comment]
Hum. I don't think we should do this. First, let's just assume that the person using the installation has enough privs to install it whoever they want. Let's not second-guess them by using a OS-dependent way of detecting root, and a very fragile one at that. Most people just have a sudoed user.
It would be much better if you reverted this commit, and labeled this as "meta" for discussion.

**Comment by JJ** [comment]
WRT to the OP, you don't need to be root to install docs. Just need to have permission to write in the directories you are going to install things. I use perlbrew, I don't need to be root to install anything. So that would be another reason to revert this commit.

**Comment by tmtvl** [comment]
I've deleted the branch. If we aren't going to use an OS-dependent way of changing things we should at least allow the user to customize the install directory instead of just assuming that the user either A) has root permission, or B) is using perlbrew.

If we want Perl 6 to be enterprise-quality we should future-proof it accordingly.

**Comment by JJ** [comment]
We can't do that at the documentation level. It's `zef`s task to do that. We just give it to Zef to take care of that. You want to have it elsewhere, build the documentation and run the server. That's also included.

**Comment by JJ** [comment]
And just to be clear, Perl 6 is *already* enterprise-quality.

**Comment by tmtvl** [comment]
Okay, I'll ask zef if there's something they can do, thanks for the help!

**Comment by JJ** [comment]
Sure. Good luck!
