### ISSUE TITLE
Document the use of double angle brackets in pod formatting codes

### ISSUE THREAD

**Issue by frithnanth** [perl6/doc#2453]
## The problem

The use of double angle bracket is not documented.

## Suggestions

Change the line

> All Pod formatting codes consist of a single capital letter followed immediately by a set of angle brackets.

to something like

> All Pod formatting codes consist of a single capital letter followed immediately by a set of single or double angle brackets; Unicode double angle brackets may be used.

**Comment by JJ** [comment]
Well seen.

**Comment by frithnanth** [comment]
Added some documentation; closing.

**Comment by JJ** [comment]
Please try and close from a commit... Just refer to this issue with closes #(ISSUE NUMBER)
