### ISSUE TITLE
Search should prefer exact matches, then prefix matches

### ISSUE THREAD

**Issue by coke** [perl6/doc#247]
A search for the string "str" should show Class:Str and Routine:Str as the first choices.

A search for "bef" should sort Infix:before before the exception.

**Comment by coke** [comment]
Think we need #273 first.

**Comment by coke** [comment]
Now that we have categorized matches, how do we want exact matches to be preferred:

- In each category, exact matches are shown first?
- Exact matches are pulled to the top of the category listing somehow?

**Comment by AlexDaniel** [comment]
Well, I think that the right way to think about it is to take ``o`` or ``X`` as an example. If we are going to just sort the results in each category, then it's not going to help much in ``o`` case.

Not sure if there's a perfect solution. What about having another category called “Exact matches”, listing all exact matches with actual categories in parens?
For example, type ``x`` and it will say
```
==Exact matches==
x (Routine)
```
And keep other search results below (other search results as implemented right now).

**Comment by samcv** [comment]
I think we should list exact matches first. That is what most people would expect.
This would be great:
```
==Exact Matches==
Str [Class]
Str [Routine]
```

Atm we have:
```
==blah==
blah
blah
==blah==
blah
blah
==Class==
blah
blah
blah
blah
blah
blah
Str
blah
blah
blah
```

**Comment by coke** [comment]
I have a local patch that puts exact matches at the top of the category, followed by prefix matches, with the remaining items in alphabetical order. Everything is still broken out by category.

This worth pushing?

**Comment by samcv** [comment]
That's an improvement. Sounds like a good idea to me 👍

**Comment by AlexDaniel** [comment]
Yes! Especially if you can mark the matched part with bold or something.

**Comment by coke** [comment]
Added matched part highlight as #1409
