### ISSUE TITLE
Eliminate LWP::Simple from the list of dependencies

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2472]
## The problem

It does not seem to be used anywhere. I added it in #1928 for probably no good reason.

## Suggestions

Just remove it and see what happens.

**Comment by JJ** [comment]
IO::Socket::SSL is in the same situation. It is not used directly, but I'm not sure about removing it, since it is probably used from the pod::to::* modules. I'm leaving like it is for the time being.

**Comment by coke** [comment]
There's no usage in the project, so my 2¢: rip them out and then if anything downstream breaks, *they* need to add them as deps, since we're not using them.
