### ISSUE TITLE
doc/Type/X/Syntax/Comment/Embedded.pod6 seems to be wrong

### ISSUE THREAD

**Issue by coke** [perl6/doc#2480]
## The problem

Doc indicates that

```
#`
```

is an error, but I can't get this sample syntax to error out.

Additionally, the error message listed shows

```
Opening bracket
```

Which, if we can get this to be generated, should probably say "curly brace" or "square bracket" (or just show the missing character) (which is a rakudo issue)

**Comment by JJ** [comment]
Looks like it's marked as TODO: 
https://github.com/perl6/roast/blob/b9bfe1844db25f65a4aeb351a0107f83689cb5c2/S32-exceptions/misc2.t#L184-L187

**Comment by JJ** [comment]
And this is actually a duplicate of #1385. Closing.
