### ISSUE TITLE
classes are just blocks (to some extent)

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#2481]
## The problem

```
class C {
    die "I will never live!"
};
my $c = C.new; # it will never get here
```

## Suggestions

Extend: https://docs.perl6.org/language/control#Blocks by something along the lines:

Class bodies behave like simple blocks for any top level expression that is not part of any of the special key-words (like method/has ...) that should go into a class definition.

Also, statements in a role definition are executed at compose time.

**Comment by gfldex** [comment]
This might also go into https://docs.perl6.org/language/packages .

**Comment by JJ** [comment]
I am not sure how to include this into the documentation. The basic idea, I guess, is that you can have any kind of statement in the class. Maybe in the section we talk about class variables.
