### ISSUE TITLE
slurp-rest still in docs

### ISSUE THREAD

**Issue by jdv** [perl6/doc#2492]
## The problem

https://docs.perl6.org/routine/slurp-rest says the the method is deprecated but its still in the docs;
at least on /language/io.

**Comment by JJ** [comment]
People can still use 6.c. I see no motive to remove it. The deprecation notice should be enough.

**Comment by jdv** [comment]
I disagree.  If something is deprecated or changed in some way there should  be an easy way too see that.  I like the postgres way where all the versions have their own docs and there's a "current" psuedo version.  Perhaps we could do something that for 6.c, 6.d, etc...

**Comment by JJ** [comment]
There's a clear note in the documentation. All other uses of slurp-rest in examples have been removed. Some languages (with heavy human resources support) have versioned documentation. We don't have that. When there are divergences between 6.c and 6.d, that's noted in the documenation and that's that.

**Comment by JJ** [comment]
The *examples* were removed from the docs, not the method itself, which has a clear not it's no longer used in 6.d. If that's enough for you, please close the issue.
 I kinda know postgresql is a language, but still there are some languages (like Python) that have versioned documetns.
