### ISSUE TITLE
Time for tests has doubled overnight

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2498]
## The problem

![screenshot from 2018-12-06 11 21 11](https://user-images.githubusercontent.com/500/49578077-28f6ec80-f949-11e8-95c0-35a9a50e7ec6.png)

It's gone from ~500 seconds to ~ 1000 seconds. @finanalyst 's PR #2497 which is set to eliminate disambiguation will reduce time, but it's still a problem.

## Suggestions

The problem seems to be with the change from 2018.10 to 2018.11 in the [Docker container](https://hub.docker.com/r/jjmerelo/test-perl6/) used. At the same time, Travis has changed its infrastructure to use virtual machines instead of containers. I don't know which one is to blame for this, but going back to ~30 minutes for test is unacceptable.

**Comment by JJ** [comment]
I would say it's a problem with the Perl 6 version. The whateverable-based tests, which uses an up-to-date executable, always took longer. It's been only when the docker container has been updated when it started to take longer with it.
I am going to check with other versions, to see if that's the thing. Has there been any change lately that might explain that?

**Comment by JJ** [comment]
Still, there's some other thing that we have not considered: the fact that now all files are being built from source.
Also, the travis cache is activated, but I'm not sure we are really using it. Not sure if we really can, htmlify.p6 generates everything from scratch every time...

**Comment by AlexDaniel** [comment]
What's the situation now? Is it better?

**Comment by JJ** [comment]
It's improved after elimination of the generation of the disambiguation files... That really took a long time.

**Comment by AlexDaniel** [comment]
I'm not running any tests, just created a ticket because the issue seemed serious. If there is no problem (in rakudo) please let me know.
