### ISSUE TITLE
Eliminate disambiguation from htmlify.p6

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2499]
## The problem

I don't really know what purpose it serves, or what it's done for. It's not used in the website, I don't know if it's used for p6doc, but anyway, it could be a good idea to #2295 

## Suggestions

This could be a part of #1823 . Something deeper might be needed, though...

**Comment by antoniogamiz** [comment]
As we already know its use and it looks like anyone is using it, could I make a PR deleting it?

**Comment by JJ** [comment]
You can give it a try if no one is against it, but be advised that there's code in the Makefile that uses it and maybe elsewhere.

**Comment by moritz** [comment]
I'm against it.

I built this feature because I actually use it.

**Comment by antoniogamiz** [comment]
As discussed here it looks like this functionality is useful, so I think we should close this issue.

**Comment by tbrowder** [comment]
Maybe add a comment in code stating its purpose would help curb future
issues.

**Comment by antoniogamiz** [comment]
I will document it when the times comes :D.

**Comment by JJ** [comment]
@moritz it's not clear that there's anyone else using it at the moment. And it adds a couple of minutes to the build process, to every single one of them. The issue has been here for more than six months, and no one else has raised their hand supporting it.
Whatever purpose it serves, it might be better to serve it in some other way. Since it's really independent from the rest of the build process, we could simply spin it off and run it from time to time, instead of every time the site is built, for instance. I don't know if some server features will be able to do it, but anyway we can think of many solutions.

**Comment by moritz** [comment]
@JJ the purpose is that one can link to a page that informs about different usages of a symbol or name in Perl 6. If we had a search that one could link to, like https://google.com/?q=Perl%206, that would work as well.

Saving a few minutes off the build process doesn't sound like a very convincing reason for me as user.  If it's a problem during development, add a switch that skips that step, but please don't remove it from the production site to save a few minutes.

One of Perl 6's many slogans is to torment the implementer on behalf of the user, and I've ported that to the documentation project.

**Comment by JJ** [comment]
El jue., 4 jul. 2019 a las 9:18, Moritz Lenz (<notifications@github.com>)
escribió:

> @JJ <https://github.com/JJ> the purpose is that one can link to a page
> that informs about different usages of a symbol or name in Perl 6. If we
> had a search that one could link to, like https://google.com/?q=Perl%206,
> that would work as well.
>

But we are, for the time being, sticking to a static site. So I don't think
that's possible at all.

> Saving a few minutes off the build process doesn't sound like a very
> convincing reason for me as user. If it's a problem during development, add
> a switch that skips that step, but please don't remove it from the
> production site to save a few minutes.
>
There's already a switch to skip that step, it was inserted there a long
time ago by Richard Hainsworth. We use it to turn it off for checking. Also
in general saving a few minutes off the build is, for me, a very good
reason. In the beginning, generating disambiguation pages for a few dozen
files might not seem like much, but we have now ~400 files, and it's a lot.
You have to put in the balance how many users a feature has on one hand,
and on the other hand how much that feature costs.

Anyway, my proposal above was not to outright eliminate it, but modularize
it so that it's not generated every single time we generate the site.
Another option would be to keep it so that users can switch it on for their
own version of the documentation, but not switch it on for the whole
documentation (keeping the old files, because losing URLs is also not good).

> One of Perl 6's many slogans is to torment the implementer on behalf of
> the user, and I've ported that to the documentation project.
>
None of the options above are easy on the implementer, every single one of
them needs some work. Of course, making disambiguation file generation
faster would also be a good idea. I mean, *anything* would be better than
the slogging generation we have now.

**Comment by JJ** [comment]
Come to think of it, this feature it's not even documented. I don't think it comes up in Google searches, and I doubt there's any incoming link. It's very unlikely that anyone notices if it disappears. So unless there's a very good reason to keep it, either it disappears or we generate this pages once a month or so...

**Comment by JJ** [comment]
Additionally, the disambiguation rules do not make a lot of sense. For instance, 

```
    <div class="pod-body no-toc">
    <p>&#39;with orwith without&#39; can be anything of the following</p>
    <li><a href="/syntax/with orwith without"></a> from <a href="/syntax/if">control flow if</a></li>
<li><a href="/language/control#index-entry-with_orwith_without">reference</a> from <a href="/language/control">language documentation Control flow</a></li>

    </div>
```

These are actually two versions of the same documentation, the first one generated, the second one within its original page.
if what we want is shortcuts for syntax pages or index entries, that's much better served at the server level, not at the page-generation level.
