### ISSUE TITLE
Visual differences between site and local versions of docs

### ISSUE THREAD

**Issue by finanalyst** [perl6/doc#2518]
## The problem
The visual perception of the docs at docs.perl6.org is not optimal.  For some reason, text is flowing around and below the ToC. 

However, I forked the repo to my PC, ran 'make html' then 'make run' and looked at the site using the same browser but from localhost.

The visual perception is much better in the local version - actually the same as what it used to be on the perl6.org site.

You can see the two versions here (left is docs.perl6.org, right is localhost)
![screenshot from 2018-12-21 11-16-45](https://user-images.githubusercontent.com/363676/50322869-11eff700-0512-11e9-8e30-fae6066f94ea.png)

Note that the two versions differ when the viewscreen horizontal dimension > 1040 px. At small widths, the versions appear to be the same. 

This is clearly a css question. However, since the fork I use also includes the scss files that are supposed to be used for the docs.perl6.org site, I wonder whether the scss is being generated properly.

## Suggestions

Since I have forked the repo and used the make file with no change, it seems to me that the only difference between my local environment and the environment for the site is the tool-chain required to build and run the makefile. 

Perhaps the modules on the server need to be updated and a check made to ensure the scss is being updated.

Without access to the server environment, I am not in a position to investigate the reason for the difference.

**Comment by finanalyst** [comment]
I have the error.

Pod::To::HTML was amended to start using templates. The main template introduced an extraneous ')' into the class of a div.  This threw off the CSS.

I have submitted a patch to Pod::To::HTML. This should clear up this issue.

**Comment by treyharris** [comment]
This has been merged in #2519 , but the live site is still displaying as in the left example from the OP.

![](https://user-images.githubusercontent.com/363676/50322869-11eff700-0512-11e9-8e30-fae6066f94ea.png)

Is there a second issue going on?

**Comment by JJ** [comment]
We have to actually upgrade the modules involved. Will do today.
