### ISSUE TITLE
Missing bareword-as-pair-key docs

### ISSUE THREAD

**Issue by fecundf** [perl6/doc#2520]
## The problem
https://docs.perl6.org/type/Pair introduces _many syntaxes for creating Pairs_ including `'key' => 'value'` but does not explicitly introduce the legal bareword variant `key => 'value'`.

The Rakudo Star repl, and the page itself uses bare words as keys. I'm left wondering what is accepted to the left of `=>` and what happens to non-string-looking-things in that key position.

Also is it appropriate to introduce the term "fat-comma" as the name of `=>` here?

## Suggestions

Add examples and discussion of barewords-as-keys for "fat-comma" `=>` pair creation.

**Comment by JJ** [comment]
It's also called [fat arrow](https://docs.perl6.org/language/101-basics#index-entry-fat_arrow) somewhere else. At any rate, it needs clarification. Thanks for the report.

**Comment by JJ** [comment]
I'm working through this, the problem is that there's no clear definition of what a "bareword" is. My hunch is that it's the same as what could be used to define a variable, but I'll have to go through the source to find out.

**Comment by jnthn** [comment]
I'd probably avoid using the term "bareword" in Perl 6 documentation; it carries meanings for a Perl 5 programmer that [don't apply in Perl 6](https://design.perl6.org/S02.html#Bare_identifiers). It does say:

> `=>` still autoquotes any bare identifier

Which in turn explains precisely what is allowed there: an `identifier`, which is - as you correctly guessed - the same thing that can appear in a variable after, for example, the sigil.
