### ISSUE TITLE
%?LANG

### ISSUE THREAD

**Issue by arnesom** [perl6/doc#2523]
## The problem

The search box shows as entry for "%?LANG" (under "Reference").

This links to https://docs.perl6.org/language/variables#index-entry-%2525%3FLANG

There is no mention of "%?LANG" on that page.

## Suggestions

Remove the link, or document "%?LANG".

**Comment by arnesom** [comment]
It isn't implemented (in 2018.12)

> say %?LANG
===SORRY!=== Error while compiling:
Variable '%?LANG' is not declared

**Comment by JJ** [comment]
Yep, but it should be either indexed correctly or eliminated...

**Comment by JJ** [comment]
Couple of different problems here. First one, that index entry does not actually exist. I would say all index entries with a % do not work: #1416 #2502. Second, the actual existence of that variable in the implementation. We will have to check both out...

**Comment by JJ** [comment]
https://docs.perl6.org/language/variables#index-entry-%2525%3FRESOURCES does not work either... I'm creating a new issue for this.

**Comment by JJ** [comment]
That variable is not even in Rakudo, but in nqp code. The only one that apparently works is $?LANG, but it's not tested, as far as I can see. Will continue checking this out.

**Comment by JJ** [comment]
The code that tests this in roas is commented out. 

        # is-deeply (:%?LANG), (LANG => %?LANG), 'Adverb with %? twigil works';

I will just eliminate the indexing for the time being.
