### ISSUE TITLE
ForeignCode not documented

### ISSUE THREAD

**Issue by arnesom** [perl6/doc#2528]
## The problem
ForeignCode only shows up in the Type Graph on this page: https://docs.perl6.org/type/Callable

I get the value like this:

  sub just-a-sub {}
  say &just-a-sub.^methods;  # -> (< anon > yada < anon > ...

  &just-a-sub.^methods[0].WHAT; # -> (ForeignCode)
  &just-a-sub.^methods[0].^name;  # -> ForeignCode
  &just-a-sub.^methods[0].name;   # -> < anon >

What is the difference between "name" and "^name"?

And I think that "< anon >" means that the method is anonymous (as
in the "anon" keyword), but why is there 24 of them for my dummy procedure?

## Suggestions

Document it?

**Comment by JJ** [comment]
Name is just the name of the method, `^name` is equivalent to `.HOW.name`, that is, the name of the "Higher Order Working" that is used to build the particular class.

**Comment by arnesom** [comment]
Yes, I think it should be documented - as it is something that is exposed.

The alternative is to "unexpose" it.

**Comment by jonathanstowe** [comment]
Or, you know, document that some implementations might  on occasion expose implementation specific types that are subject to change and should to all intents and purpose be ignored.  Or alternatively specify that no such implementation specific types should be exposed.

**Comment by JJ** [comment]
@jonathanstowe if there were, let's say, two implementations with different ways of doing this, documenting implementation specific stuff would not make a lot of sense, and it would be impractical. In general, we opt for making some kind of documentation, with all kind of caveats.

**Comment by JJ** [comment]
@arneson
2. It's documented that ^ == .HOW., so `^name`== `HOW.name`
3. Removing stuff from the output is not our turf. You should go to the Rakudo repo, if you think it's necessary.

**Comment by JJ** [comment]
Edited. Sorry!

**Comment by arnesom** [comment]
@JJ 

Point 2 (^ == .HOW.):

Are you sure? I get an error (in 2018.12):

```
my $a
say $a.^name; # -> Any
say $a.HOW.name
# Too few positionals passed; expected 2 arguments but got 1
#   in block <unit> at <unknown file> line 1
```
Point 3: That is above my pay grade.

**Comment by jonathanstowe** [comment]
Actually   ^ isn't exactly the same as calling the same named method on ```.HOW```  rather the equivalent code would be:

```perl6
my $a;
say $a.^name;
say $a.HOW.name($a);
```

That is the LHS object is passed to the method called on the HOW object.  I'm not sure if or where this is documented.
