### ISSUE TITLE
Needs rakudo update

### ISSUE THREAD

**Issue by awwaiid** [perl6/doc#253]
I think we need a new rakudo so that we can fix the monkey business. I don't know how to do that :)

**Comment by sylvarant** [comment]
Can you be more specific ? What monkey business ?

**Comment by awwaiid** [comment]
The new rule that you can't call EVAL without a pragma. The build now assumes that change, but the rakudo is outdated. 
http://doc.perl6.org/build-log/build-2015-12-21T19:05+0000.log

**Comment by awwaiid** [comment]
To be clear -- the docs have not been updated in 2 days now because of this

**Comment by stmuk** [comment]
It's using a new rakudo now so closing (although other issues remain)
