### ISSUE TITLE
META6.json documentation needs improvement

### ISSUE THREAD

**Issue by lizmat** [perl6/doc#2543]
"Friendly Comment: I'd like to comment that as a newcomer to perl6 I spent a significant amount of time searching for a clear specification of what's needed on a META6.json file. I found this synopsis and this documentation among others but they are not complete/up-to-date. For example source-type and source-url are not even mentioned but required in META6. I had to copy from another project to create a successful META6.json file."

https://github.com/rakudo/rakudo/issues/2591

**Comment by JJ** [comment]
Thanks for the issue.

**Comment by JJ** [comment]
FWIW, source-url is indeed mentioned. It does not mention the fact that it's compulsory, though.

**Comment by ugexe** [comment]
`source-url` is not compulsory. Please clarify unknowns with an appropriate subject matter expert before committing.

**Comment by JJ** [comment]
OK, I see the differences between customary, mandatory and optional [here](https://github.com/jonathanstowe/META6/blob/master/lib/META6.pm). Not documented anywhere else, as far as I know. Will fix.
FWIW, all commits are open for review and comment, such as you have done, and for which I am grateful. OTOH, all issues are also open for anyone to take and fix.

**Comment by jonathanstowe** [comment]
@JJ Having had a quick look at META6 and I think it may need a slight refresh as  the [auth](https://github.com/jonathanstowe/META6/blob/master/lib/META6.pm#L248) should probably be ```specification(Optional)``` now and it doesn't include ```api``` either.  If anyone feels like taking a look and checking that all attributes that may be used are there and correctly marked that would be great.

**Comment by JJ** [comment]
I'm doing it right now. Push in a second.

**Comment by JJ** [comment]
Thanks @ugexe and @jonathanstowe for review and clarification. Hope it's better now.
