### ISSUE TITLE
The X::Control role is not documented

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2551]
## The problem

It's actually an empty role:
https://github.com/perl6/nqp/blob/01da9b07c7d0a5e4eaca87225d5833e0ab5b996b/src/HLL/Compiler.nqp

But it's the base to a whole set of CX classes which are not documented either.

## Suggestions

Document the lot of them. This is part of #517 , maybe by adding a new issue we'll get to work on that...

**Comment by jnthn** [comment]
This whole area needs a bit more work in spec/implementation, and is certainly something to try and have nailed down more in Perl 6.e. I just put some initial changes into Rakudo that make [custom control exceptions](https://stackoverflow.com/questions/54155892/defining-own-control-exception/54164952) possible. However, the whole area needs a bit more consideration and fleshing out. For example, it's not currently possible to `CX::Last.new.throw` and have it work; they only work for catching the control exceptions in a `CONTROL` block. That's not an especially practical problem, but it is something that would ideally work.
