### ISSUE TITLE
p6doc broken

### ISSUE THREAD

**Issue by bpstahlman** [perl6/doc#256]
On Ubuntu, after installing p6doc using panda...
~/.rakudobrew/moar-nom/install/share/perl6/site/bin/p6doc 
===SORRY!===
Could not find MONKEY-SEE-NO-EVAL in:
    /home/bstahlman/.perl6/2015.11-668-g8401e01
    /home/bstahlman/.rakudobrew/moar-nom/install/share/perl6/site
    /home/bstahlman/.rakudobrew/moar-nom/install/share/perl6/vendor
    /home/bstahlman/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<140701962206784>
    CompUnit::Repository::NQP<140701962203376>
    CompUnit::Repository::Perl5<140701962200216>

Googled MONKEY-SEE-NO-EVAL and saw that there was a recent change in this repo involving it...

**Comment by jonathanstowe** [comment]
You need a more recent rakudo (i.e. yesterday) or an older p6doc

**Comment by bpstahlman** [comment]
Ah. Rt. I installed rakudo Friday, I think. I'll update. Thanks.

**Comment by jonathanstowe** [comment]
Yeah it's a very, very recent way of ensuring controlled access to EVAL.

**Comment by bpstahlman** [comment]
Hmm... Now I'm confused. Ran `panda build moar' again, thinking to upgrade to latest rakudo, but now I just get a different error:
===SORRY!=== Error while compiling /home/bstahlman/.rakudobrew/moar-nom/install/share/perl6/site/resources/2AF223812A0BABBAB687778EB48FD5C755F39BC5
Undeclared name:
    CompUnitRepo used at line 32

bstahlman@bstahlman-HP-EliteBook-840-G2:~$ perl6 --version
This is Rakudo version 2015.11-713-g591783d built on MoarVM version 2015.11-113-gbd56e2e
implementing Perl 6.b.

How should I be accomplishing the recommended update?

**Comment by jonathanstowe** [comment]
I'd nuke it with "rakudobrew nuke moar" and start again in the first place.

**Comment by niner** [comment]
And upgrade your panda. Must be quite old to show that error.

**Comment by bpstahlman** [comment]
I did as suggested with "rakudobrew nuke moar", then re-installed like so...
rakudobrew build moar
rakudobrew build-panda
panda install Task::Star
panda install p6doc

After all this, p6doc wasn't in my path, but running with full path...
bstahlman@bstahlman-HP-EliteBook-840-G2:~$ .rakudobrew/moar-nom/install/share/perl6/site/bin/p6doc
===SORRY!=== Error while compiling /home/bstahlman/.rakudobrew/moar-nom/install/share/perl6/site/resources/5747BBDBC3C7FD2824C2629EE92A7F0CA7588934
Undeclared name:
    CompUnitRepo used at line 32

bstahlman@bstahlman-HP-EliteBook-840-G2:~$ perl6 --version
This is Rakudo version 2015.11-716-gcfb1f37 built on MoarVM version 2015.11-113-gbd56e2e
implementing Perl 6.b.

Still seems to be an older version... Does "rakudobrew build moar" pull from an older, stable branch or something? I was expecting something newer than November...

**Comment by jonathanstowe** [comment]
No, It will remain 2015-11 until the next stable release which may or may not be Friday or sooner :)

**Comment by bpstahlman** [comment]
So what's currently considered to be the best documentation for experienced programmers wanting to get a good introduction to perl 6?

**Comment by raiph** [comment]
Stretching the word "documentation" a little, I'd say it's a combination of  http://perl6intro.org (recently written by a Perl 6 newbie); p6doc (available online at http://doc.perl6.org if you can't get the local version to work and has 5to6 docs in the Language section for those who know some Perl 5); the "speculations" at http://design.perl6.org; the last 7 years worth of advent calendars at http://perl6advent.wordpress.com; and having a chat with the likes of Larry Wall aka TimToady on the freenode IRC channel #perl6.

**Comment by bpstahlman** [comment]
Rt. Thanks. I'll try the online docs for now.

**Comment by stmuk** [comment]
I fixed the CompUnitRepo error.  It should basically work now.
