### ISSUE TITLE
Links without targets

### ISSUE THREAD

**Issue by finanalyst** [perl6/doc#2568]
## The problem
Further to the problem I raised in Issue #2549 about linking to targets inside html files that are generated from primary source files (those in 'doc/Language/' and possibly 'doc/Type/'), five links do not correspond to a generated target. Consequently, they raise a 404 error.

The data in yaml format is given at the end. Five files/links are affected. One was introduced into the documentation in the last few days!!!!!!

## Suggestions
1. Remove the above links (I will submit a PR doing this in due course). 
1. Specify that authors writing / editing primary language documents only include links to primary documents. We can then write a test that will reject an edit which introduces a reference to a file outide the `html/language` or `html/type namespaces`.
1. Remove all links in generated files with the primary reference they actually contain (I will submit a PR in due course). This does not mean that we stop generating these files as yet.

## Comments
1. One of the links below explicitly links to an 'html' file. This should not be allowed for documentation sources because it would not allow for rendering in another format.

```
--- 
- 
  file: "/syntax/use.html"
  internal: ""
  link: "/syntax/use"
  newlink: "n/a"
  found: false
  ln: 317
  fn: "doc/Language/classtut.pod6"
- 
  newlink: "n/a"
  link: "/routine/andthen"
  internal: ""
  file: "/routine/andthen.html"
  ln: 354
  fn: "doc/Language/faq.pod6"
  found: false
- 
  newlink: "n/a"
  link: "/syntax/role"
  internal: ""
  file: "/syntax/role.html"
  fn: "doc/Language/module-packages.pod6"
  ln: 17
  found: false
- 
  internal: ""
  link: "/routine/clock_gettime"
  newlink: "n/a"
  file: "/routine/clock_gettime.html"
  found: false
  fn: "doc/Language/nativecall.pod6"
  ln: 129
- 
  found: false
  fn: "doc/Language/numerics.pod6"
  ln: 680
  internal: ""
  newlink: "n/a"
  link: "/syntax/Number literals"
  file: "/syntax/Number literals.html"
- 
  newlink: "n/a"
  link: "/routine/andthen"
  internal: ""
  file: "/routine/andthen.html"
  fn: "doc/Language/traps.pod6"
  ln: 1698
  found: false
- 
  found: false
  ln: 268
  fn: "doc/Type/Array.pod6"
  file: "/routine/is default (Variable).html"
  internal: ""
  link: "/routine/is default (Variable)"
  newlink: "n/a"
- 
  found: false
  ln: 35
  fn: "doc/Type/Block.pod6"
  internal: ""
  newlink: "n/a"
  link: "/syntax/return"
  file: "/syntax/return.html"
- 
  found: false
  fn: "doc/Type/Hash.pod6"
  ln: 306
  file: "/routine/is default (Variable).html"
  internal: ""
  link: "/routine/is default (Variable)"
  newlink: "n/a"
- 
  internal: Ordinary_identifiers
  newlink: "n/a"
  link: "/syntax/ identifiers.html"
  file: "/syntax/ identifiers.html.html"
  found: false
  ln: 26
  fn: "doc/Type/Pair.pod6"
...
```

**Comment by JJ** [comment]
Thanks!

**Comment by JJ** [comment]
andthen and notandthen seem to be pretty much the same, yet one of them has its very own /routine/ page, the other does not. What a puzzle.

**Comment by JJ** [comment]
Additionally, there are two different links to "notandthen", depending on whether you use the "Reference" category or the "infix" category.
