### ISSUE TITLE
Spin off Per6::Type and Perl6::TypeGraph

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2573]
## The problem

[`Perl6::Type`](https://github.com/perl6/doc/blame/master/lib/Perl6/Type.pm6) is an ancillary class used here that has been essentially untouched for almost seven years (but for minor additions). It's not tested, or documented.

As a matter of fact, TypeGraph does most of the heavy lifting, with Perl6::Type having some methods, one of which is apparently just a private method.  

## Suggestions

Spin it off under the Perl 6 organization, and add tests and documentation. Possibly extricate the real stuff from TypeGraph and put it where it should be, in Perl6::Type.
Also check out whether those functions are not really done by something else in the ecosystem, or even in Rakudo itself.

**Comment by coke** [comment]
Adding the tests and documentation for this module can be done without moving it to a separate repository.

**Comment by JJ** [comment]
But that would mean adding even more overhead to the tests of this repo,
and more stuff that's not strictly documentation. If we need to have it
handy, we can just include it in the Docker container we use for testing.
Spinning it off will allow, besides testing, being able to approach it for
people that would not be strictly interested in the documentation.

**Comment by coke** [comment]
I'm not sure what the overhead is you're referring to. Adding a test under xt/, for example, adds no overhead to the CD pipeline.

The audience for the module is important when considering spinning it off. If we're using it solely to avoid duplication, for example, having it in a separate repository then increases the complexity of the setup required to use it and maintain it. As far as I can tell, it's not intended to be a general purpose module, but part of the tooling.

**Comment by JJ** [comment]
Related: #2584 
Spin them off as Perl6::Documentable::Type and Perl6::Documentable::Type::Graph

**Comment by JJ** [comment]
This is already published in the ecosystem. It's the turn of incorporating it to the repo.

**Comment by JJ** [comment]
[Tests are failing](https://travis-ci.org/perl6/doc/jobs/544582852). We need to update also the dockerfiles to make this work. Also using this to [solve this issue](https://github.com/JJ/alpine-perl6/issues)

**Comment by JJ** [comment]
OK, updated Dockerfiles and the tests are working now.
