### ISSUE TITLE
Indexing rules

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2575]
## The problem

This should be read as an interrogation. Indexing, indeed, rules, but indexing in this particular repo is a big mystery.

It's done mainly through two different mechanisms.
1. Automatically through simply using =headx *in some particular parts*, like `Type`
2. Explicitly by using Pod6's `X<>`. This is done mostly, or totally, here:
https://github.com/perl6/doc/blob/master/htmlify.p6#L620-L663

There are several problems.
* Page generation depends on indexing. Changing an index mark will change generated pages. I tried, on a hunch, to do it in #2221, but it resulted in disappearing pages. 
* Index escaping is inconsistent: #2535 
* Index is generated every single time HTML pages are generated, and it *takes a long time*, which has also influenced test time, for instance #2498 . There's no caching of indexes. @finanalyst is taking care of this now, but the rest of the problem remain.
* Index is not shared with p6doc: #2574 (p6doc has its own problems).
* Since it's in a script, it's not tested. We don't know either what *should* be in the index or what pages should be generated as a result of indexing. 
* Indexing via markup also creates categories: #2323 #2369 
* Indexing creates either pages or anchors. But if something with a special character is indexed, all hell breaks loose: #2502 #2527.

## Suggestions

As part of the Big Split #2542, maybe independent indexing specs and modules should be created and shared across tools.
It would be convenient also to not make indexing depend on markup, since it's difficult for someone to actually have those rules in mind when changing some documentation file. However, this is a difficult proposition, because relying only on document structure as in  #2571 might also be a problem. So it's a difficult thing to crack.

Any suggestion is welcome. Meanwhile I'll leave this issue open for discussion.

**Comment by JJ** [comment]
The thing is it might be easier to spin some things off (if not do the Big
Split) than refactor it. We need to create some modules, and test them, and
that would be much better done in an independent repo. Once they work as
intended, we can refactor this (and eventually split it, if that's the
(rough) consensus)

**Comment by antoniogamiz** [comment]
Indexing rules have been documented in [this module](https://github.com/antoniogamiz/Perl6-Documentable). I think it's time to take a look at [document file specification](https://github.com/perl6/doc/wiki/Document-file-specification) and see if they are going to be changed in some way.

**Comment by JJ** [comment]
They will be very probably changed...
