### ISSUE TITLE
Example for role uses EVAL 

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2580]
## The problem

The example for role [uses `EVAL`](https://docs.perl6.org/language/objects#Roles) for serializing and de-serializing some data structure.

## Suggestions

It's probably not a good idea to do so. Doing an EVAL of code in userland without some kind of de-tainting or processing is never a good idea. It's not really needed, either, to exemplify how roles are used.

**Comment by jonathanstowe** [comment]
Yeah that's naughty, plus it introduces it without any explanation as to why the  ```use MONKEY-SEE-NO-EVAL;``` is needed and so forth.

**Comment by JJ** [comment]
This code, BTW, [was seven years old](https://github.com/perl6/doc/blame/ced282d21da896ae1a50b6eb30cd2ca3576f693a/lib/Language/objects.pod). This is why I say we need a revision tool #2554.
