### ISSUE TITLE
Software generating $SOLIDUS links

### ISSUE THREAD

**Issue by finanalyst** [perl6/doc#2591]
## The problem
At some point in the current tool-chain link targets that are correctly specified in the pod source are having `$SOLIDUS` inserted into them. These cannot be interpreted.

My link test programs have identified the following
- ｢/routine/language$SOLIDUSobjects#Parameterized_Roles｣
	- in file ｢/type/Associative.html｣ at line 132
- ｢/routine/language$SOLIDUSoperators#index-entry-smartmatch_operator｣
	- in file ｢/language/traps.html｣ at line 510
- ｢$*ARGFILES$SOLIDUSlanguage$SOLIDUSvariables#index-entry-%2524%252AARGFILES｣
	- in file ｢/language/system.html｣ at line 108
- ｢$SOLIDUSAttribute#trait_is_DEPRECATED｣
	- in file ｢/language/traits.html｣ at line 111
- ｢$SOLIDUSNumeric#%28Thread%29_method_Numeric｣
	- in file ｢/language/contexts.html｣ at line 114
- ｢$SOLIDUSfunctions#Precedence｣
	- in file ｢/language/traits.html｣ at line 129
- ｢$SOLIDUSlanguage.html｣
	- in file ｢/language/faq.html｣ at line 185 and in 1 other files
- ｢$SOLIDUSoperators#infix_%3A%3D｣
	- in file ｢/language/containers.html｣ at line 176
- ｢$SOLIDUSoperators#infix_...｣
	- in file ｢/language/list.html｣ at line 155

For the first bad link above, the reference in `Type/Associative.pod6` is `L<parametrized role|language/objects#Parameterized_Roles>`. There is nothing outwardly wrong with this link, though perhaps it should be `L<...|/language...>`

I have so far not been able to find where in the tool chain this interpolation happens.

## Suggestions
1. Temporarily include a rewrite in `.htaccess` for `$SOLIDUS`, but care is needed because some files are named with `$SOLIDUS`, eg. `syntax/$$SOLIDUS.html`
1. Rewrite the toolchain.

**Comment by finanalyst** [comment]
After looking at these $SOLIDUS errors, it seems that quite a few of them are incorrectly written links, eg missing characters, missing paths. Since previously, the html files links were not checked, the errors were not picked up. 

The current tool-chain does seem to pick up errors but it is rendering the link in a non-standard way.

**Comment by JJ** [comment]
I'm not sure .htaccess is working properly. It might be, but some rules
added lately are not working. And it's complicated enough like it is...

**Comment by finanalyst** [comment]
All these are bad link errors and have been fixed with miminal changes

**Comment by JJ** [comment]
Thanks, Richard.

**Comment by JJ** [comment]
Refs #2542 #2529
