### ISSUE TITLE
How to specify /language.html

### ISSUE THREAD

**Issue by finanalyst** [perl6/doc#2592]
## The problem
FAQ has a link specified in `Language/faq.pod6` as `L<"Language" section|/language>` that is intended to point to `docs.perl6.org/language.html`.

Instead it points to `docs.perl6.org/language$SOLIDUS`, which is gets a 404 response. The trouble is somewhere inside htmlify (perhaps). 

The link was specified as `L<"Language" section|/language.html>` but that didn't work either. Both are valid POD6.

In the same sentence, there is a link `L<the official documentation website|/>` which is rendered by htmlify to point to `docs.perl6.org/routine/$SOLIDUS` . That in fact is a link to the file for `Infix /` and so is missed by a test program that only looks for live links.

This is a bug in the tool-chain - probably htmlify

## Suggestions
1. Rewrite the tool chain

**Comment by antoniogamiz** [comment]
Fixed in the new Documentable, closing.
