### ISSUE TITLE
String concatenation not clear.

### ISSUE THREAD

**Issue by hhg7** [perl6/doc#2597]
## The problem

String concatenation not clear.  

```
my $cmd = "databricks jobs --job-id 37 --notebook-params '\{";
put $cmd;
$cmd ,= "\"directory\": \"$s3-dir\",";
put $cmd;

```

The correct way to do this is with `~=` in Perl6, corresponding to `.=` in Perl5.  This isn't clear from https://docs.perl6.org/language/operators#Concatenation  The correct answer is found in https://docs.perl6.org/language/operators#Assignment_operators but I'm modifying a variable already assigned here, so I didn't think it would have anything to do with assignment. Also the "assignment operators" section doesn't say that it is concatenating.  So it wouldn't show up on a search.

## Suggestions

Include something like `my $s = 'a';
$s ~= 'b';    # 'ab'`

https://docs.perl6.org/language/operators#Concatenation

**Comment by b2gills** [comment]
There is no `~=` or `,=` operator.

Those are instances of the `=` meta operator combined with another infix operator.

```perl6
my @a = 1,2;
@a ,= 3;
@a [,]= 3;
@a [&infix:<,>]= 3;
```

Do we really need to discuss every combination of an infix operator and `=`?

In fact the number of such combinations is infinite.

```perl6
$a [R~]= 3; # $a = 3 ~ $a;
3 R[~=] $a; # $a = $a ~ 3;
3 R[[R~]=] $a; # $a = 3 ~ $a;
$a RR[[RR~]=] 3; # $a = $a ~ 3

@a Z[~=] < a b c >;

sub infix:<foo> (\l,\r){…}
# these 4 are all identical
$a foo= 3;
$a [foo]= 3;
$a [&[foo]]= 3;
$a [&infix:<foo>]= 3;

$a [Rfoo]= 3;
3 R[foo=] $a;
# etc…
```
