### ISSUE TITLE
Regex interpolation

### ISSUE THREAD

**Issue by van-de-bugger** [perl6/doc#2599]
## The problem

[Regex interpolation](https://docs.perl6.org/language/regexes#Regex_interpolation) documentation is too laconic:

> There are four ways you can interpolate a string into regex as a pattern. That is using `$pattern`, `$($pattern)`, `<$pattern>` or `<{$pattern.method}>`.

Ok, it very clear and understandable.

> Note that the two examples above interpolate the string lexically, while `<$pattern>` and `<{$pattern.method}>` causes implicit `EVAL`, which is a known trap.

However, the second paragraph is not. What does "interpolate the string lexically" mean? (I just re-read section "[Interpolation: qq](https://docs.perl6.org/language/quoting#Interpolation:_qq)" and did not find the term "lexical interpolation".) What the difference between `$pattern` and `$($pattern)`? Ok, "`<$pattern>` and `<{$pattern.method}>` causes implicit `EVAL`", but what does it _really_ mean? Will the result of interpolation interpreted as regex (`/$pattern/` in Perl5 notation) or literally (`/\Q$pattern\E/` in Perl5 notation)? What the trap do you talk about?

Also, it is not clear how interpolation interacts with single and double quoting, e. g. `/'$pattern'/`, `/"$pattern"/`. Will `$pattern` be interpolated? How will it be interpreted, as regex or literally?

**Comment by JJ** [comment]
One of the problems seems to be the definition of "lexical interpolation". Couple of issues refer to the same problem #2347, and even to the word itself: #2588 . So I guess we'll have to work that out first, go and do the rest later.
