### ISSUE TITLE
Set bag hash asks me to make too many decisions

### ISSUE THREAD

**Issue by isomorphisms** [perl6/doc#2613]
## The problem
There are certain things I don't want to think about unless I have to, like whether a character is wide, which lookup method to use, and whether I'm dealing with an unordered bleep or a mixed pseudo-left-invariant bloop.

## Suggestions

Please give me a generic option that will try to do something reasonable, and let me performance hack if I need to.

**Comment by treyharris** [comment]
The phrasing of your issue description sounds like you're asking for a change to the language, not a change to the docs. If so, you should try bringing it up on one of the Perl6 mailing lists or the IRC channel—we can basically only document the language as it is.

But if you're referring to a doc issue, is it with [Language/setbagmix](https://docs.perl6.org/language/setbagmix) in particular (the only real place in the docs where the variants are discussed in one place in any detail)? Can you suggest a way the issue might be resolved?

**Comment by JJ** [comment]
Please clarify what you mean by "generic option". sets, bags and mixes are different things altogether.
