### ISSUE TITLE
Cool isn't cool

### ISSUE THREAD

**Issue by isomorphisms** [perl6/doc#2614]
## The problem
I was hoping the Cool type would be cooler.

## Suggestions

Why not just call it Num or Number?

Basic arithmetic isn't cool. Nor is coercion. It's just something I want to take for granted. Surely there are cooler things in perl6.

**Comment by AlexDaniel** [comment]
From https://docs.perl6.org/type/Cool:

> Cool, also known as the Convenient OO Loop

So maybe it's not Cool but at least it's COOL.

**Comment by treyharris** [comment]
Members of type `Cool` are "cool with whatever" num-y or string-y methods you throw at it. It's the type that gives Perl 6 much of the dynamic behavior Perl 5 users are used to.

This isn't a doc issue; if you want to argue the naming should be changed, I suggest you bring it up on [perl6-language@perl.org](https://perl6.org/archive/lists/).
