### ISSUE TITLE
spellcheck issues.

### ISSUE THREAD

**Issue by coke** [perl6/doc#2615]
41278922 fixed the spell checker in general (Thank you!)  but we're now seeing many false negatives when running the test. Here's one example:

```
$ xt/aspell.t doc/Type/Thread.pod6
1..1
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)
# & instructi 6 27: instruct, instructor, instructs, instructing, instructive, instructed
not ok 1 - doc/Type/Thread.pod6 has 1 spelling errors
# Failed test 'doc/Type/Thread.pod6 has 1 spelling errors'
# at xt/aspell.t line 57
# Looks like you failed 1 test of 1
$ grep instructi doc/Type/Thread.pod6
of instructions that can (potentially) run in parallel to others. Class
```

Looks like aspell is not considering the full word when checking.

**Comment by coke** [comment]
tagging @cfa as they authored the commit.

**Comment by cfa** [comment]
Hmm, odd. I see,

    $ xt/aspell.t doc/Type/Thread.pod6
    1..1
    @(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)
    ok 1 - doc/Type/Thread.pod6 has no spelling errors

**Comment by cfa** [comment]
Does a plain

    $ aspell check doc/Type/Thread.pod6

highlight "instructi" too?

**Comment by cfa** [comment]
Also, @coke, could you please confirm that your `aspell` input matches the following?

    $ awk 'BEGIN {print "!"} {gsub("\\\\","",$0); print "^" $0}' < doc/Type/Thread.pod6 | grep instructi
    ^of instructions that can (potentially) run in parallel to others. Class

**Comment by coke** [comment]
aspell check complains about a few things, but not that.

the manual awk command emits:

```
$ awk 'BEGIN {print "!"} {gsub("\\\\","",$0); print "^" $0}' < doc/Type/Thread.pod6 | grep instructi
^of instructions that can (potentially) run in parallel to others. Class
```

**Comment by coke** [comment]
Also:

```
$ perl6 --version
This is Rakudo version 2018.12-284-g1ff9b14e8 built on MoarVM version 2018.12-45-ga9d02578a
implementing Perl 6.d.
```

**Comment by cfa** [comment]
How about

    $ locale

?

**Comment by coke** [comment]
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G4015
$ aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)

**Comment by cfa** [comment]
It looks like we have similar setups. Perhaps this will help isolate the problem (HEAD: 041fe20):

    $ md5sum doc/Type/Thread.pod6
    251b037f559a2f9c0af26dfb4e9892df	doc/Type/Thread.pod6
    $ awk 'BEGIN {print "!"} /instructi/ { print "^" $0 }' < doc/Type/Thread.pod6 \
      | aspell -a -l en_US --ignore-case --extra-dicts=./xt/aspell.pws
    @(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)
    ␤

The final ␤ is actually a blank line (a mkd workaround).

**Comment by cfa** [comment]
Also unable to reproduce on a fresh Fedora 29 image (Rakudo 2018.12, aspell 0.60.6.1).

**Comment by coke** [comment]
Running your most recent awk command, I don't see the error. Running the xt/aspell.t command, I do see it.

**Comment by cfa** [comment]
Clean work tree?

**Comment by cfa** [comment]
@coke, one last suggestion: Please try,

```
$  grep instructi .pod-cache/doc/Type/Thread.pod6
```

and share the output. It's possible that your cached, rendered POD differs from mine.

**Comment by coke** [comment]
Bingo.

```
TITLE
class Thread

SUBTITLE
Concurrent execution of code (low-level)

    class Thread {}

A thread is a sequence of instructi
```

removing .pod-cache has fixed the issue.
