### ISSUE TITLE
`put` vs `say`

### ISSUE THREAD

**Issue by ufobat** [perl6/doc#2619]
The documentation about the routine `say` says that you should use `put` if you want to have a machine readable output. That is confusing to me because it arises the question: Why is `say`  *not* giving you a machine readable format?

@JJ++ explained to me that `say` uses  `.gist`  and `put` uses `.Str`. 

IMHO the documentation about `say` should mention that `.gist` is involved and therefore it's human readable.

**Comment by uzluisf** [comment]
I'm not sure if it's what you're looking for but the [documentation](https://docs.perl6.org/routine/say#(IO)_sub_say) does mention that `say` uses `.gist` which causes it to print partial information (and possibly more human readable) of an object.

**Comment by ufobat** [comment]
Ahh, what I was reading was [Mu.say](https://docs.perl6.org/routine/say#(Mu)_method_say), which is confusing to me. You're right, `IO.say` does contain all the *usefull* information.
