### ISSUE TITLE
clone nextwith for all attributes

### ISSUE THREAD

**Issue by daxim** [perl6/doc#2620]
<https://docs.perl6.org/type/Mu#method_clone>

`class Bar` example code says 

    method clone { nextwith :foo(@!foo.clone) :bar(%!bar.clone) }

which does not really work once you want to apply it to a real example, see <https://stackoverflow.com/q/54633260>.

Replace the line with

     method clone { nextwith :foo(@!foo.clone) :bar(%!bar.clone), |%_ }

**Comment by JJ** [comment]
Thanks for the report. Will try to fix it.
