### ISSUE TITLE
"TIP: use L«smartmatch with Pairs|/type/Pair#method_ACCEPTS» to perform multiple file tests." repeated

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2621]
## The problem

That's repeated several times [all along the IO::Path](https://docs.perl6.org/type/IO::Path#method_l) docs. I am not sure what it means, or refers to in this context. 

## Suggestions

If it make sense for every one, an example would help, at least in some of them. Or simply a few examples in the introduction.

**Comment by cfa** [comment]
I believe that this is referring to the use of pairs with junctions, e.g.

```perl6
say :d & :x;                # OUTPUT: «all(d => True, x => True)␤»
say '/tmp'.IO ~~ :d & :x;   # OUTPUT: «True␤»
say '/'.IO    ~~ :d & :rw;  # OUTPUT: «False␤»
```

**Comment by JJ** [comment]
@cfa maybe adding that as an example would help.
