### ISSUE TITLE
Smartmatch with pairs is not too clear

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2622]
## The problem

Looking what the tip in #2621 referred to, I found this [text in Pair.ACCEPTS](https://docs.perl6.org/type/Pair#method_ACCEPTS):

```
uses the invocant's key as the name of the method to call on topic and check's its .Bool is the same as .Bool of the invocant's value. This form can be used to check Bool values of multiple methods on the same object, such as IO::Path, by using Junctions:
```

## Suggestions

Wording could be improved. "its .Bool is the same as" is basically a translation of [the source](https://github.com/rakudo/rakudo/blob/master/src/core/Pair.pm6). It could be explained better in other terms.

**Comment by cfa** [comment]
@JJ: let me know whether you find that clearer? If so, please close.

**Comment by JJ** [comment]
Looks great. Thanks!
