### ISSUE TITLE
dictionary files no longer all lowercase.

### ISSUE THREAD

**Issue by coke** [perl6/doc#2626]
The original words lists in xt/ were intentionally lowercase, so we didn't have to deal with either sorting issues or having multiple copies of the word in the dictionary by case.

Looks like we have many items in both files that are now case specific (and the files are sorted by case).

If this is intentional, please comment (here and in xt/aspell.t) and close the ticket, otherwise please update the pws files.

Thanks.

**Comment by cfa** [comment]
My fault; I'll push a fix this evening.
