### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by manwar** [perl6/doc#2636]
## The problem
One of the example 

say q:raw/:raw (no interpolation) even backslash has no special meaning: \\ \/;

in the page below

https://examples.perl6.org/categories/cookbook/01strings/01-00introduction.html

is throwing following error

Unrecognized adverb: :raw
at /home/manwar/github/perl6-cookbook/strings/t.pl:3
------> say q:raw⏏/:raw (no interpolation) even backslash 
Couldn't find terminator / (corresponding / was at line 3)
at /home/manwar/github/perl6-cookbook/strings/t.pl:4
------> <BOL>⏏<EOL>
    expecting any of:
        /

## Suggestions

I don't know enough to suggest any solution. I am just learning from the examples.

**Comment by jnthn** [comment]
Curious; I've never heard of `:raw`. That thing it describes is spelled `Q/.../`, which is the base quoting construct that doesn't do backslashes or anything else except the standard terminator-seeking behavior.

**Comment by manwar** [comment]
Even this one is not working?

say q:0/:0 (no interpolation) even backslash has no special meaning: \\ /;

===SORRY!=== Error while compiling /home/manwar/github/perl6-cookbook/strings/t.pl
Colons may not be used to delimit quoting constructs
at /home/manwar/github/perl6-cookbook/strings/t.pl:3
------> say q:⏏0/:0 (no interpolation) even backslash h
    expecting any of:
        colon pair (restricted)

**Comment by jnthn** [comment]
Ah, it's not in the docs, but in the examples repository. But no, there's no `:0`, `:1`, `:2`, etc. https://docs.perl6.org/language/quoting is part of the docs, and looks accurate. I'm not sure whether this issue belongs here or on the examples repository; I wasn't even aware that contained documentation-ish stuff. Maybe somebody more involved with the docs can say; I can only confirm it's wrong.

**Comment by manwar** [comment]
Shall I submit PR to cleanup the example to respect the official document?

**Comment by jnthn** [comment]
@manwar That would be wonderful. It'll be in https://github.com/perl6/perl6-examples rather than this repo.

**Comment by manwar** [comment]
I will do that tomorrow and that will be my first ever PR for Perl 6.

**Comment by JJ** [comment]
Since this has been fixed by the OP, I'm closing it. Thanks @manwar
