### ISSUE TITLE
Collation type is not documented

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#2644]
## The problem

I am not sure when exactly it was introduced, at least I don't see it in 6.d announcement(https://github.com/perl6/roast/blob/master/docs/announce/6.d.md). We have variable `$*COLLATION` mentioned:

```
➜  doc git:(master) ✗ rg 'COLLATION'
doc/Language/operators.pod6
1540:and returns an C<Order> that uses the C<$*COLLATION> order. The default behavior
1570:L<C<$*COLLATION>|/type/Any#index-entry-%24*COLLATION-%24*COLLATION> dynamic

doc/Type/Any.pod6
1319:This method is affected by the X<B<$*COLLATION>|$*COLLATION> variable, which
1330:    $*COLLATION.set(:quaternary(False), :tertiary(False));
```

Which holds instance of the `Collation` type, but no page for it.

It is also used in roast, see https://github.com/perl6/roast/blob/master/S32-str/Collation.t which was added in 2017.

## Suggestions

Document it.

Maybe @samcv can help?

**Comment by JJ** [comment]
It was introduced pretty much at that time. Maybe not part of the spec.
