### ISSUE TITLE
Routinely check Perl 6 release "additions" for every new one

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2647]
## The problem

As shown in #2632 , there's no systematic updating of documentation after releases; it's done more in a pull than in a push way, waiting for someone to notice something is missing, although in many cases programmers adding new stuff *do* add new documentation to this repo, in most cases it does not happen and has to wait for someone to notice something is missing.

## Suggestions

Create a new issue for every release, and follow through. In some cases they might be Rakudo-only additions, so exert some caution in those cases.

**Comment by Altai-man** [comment]
I am not sure it fits to the docs well. This documentation suite is:
>This documentation is intended to be universal with respect to a given version of the specification, and not necessarily tied to any specific Perl 6 implementation.

Or this is what we have in README.

I believe that what we want is documentation for the spec. So it will be good to have a select on the top of the site pages, just like other documentation suites have for their versions, but in our case it will be `v6.c` or `v6.d`(and so on in the future). Most of the text is common, but some things may be different. This way we can avoid "And in 6.d(and then .e. and so on) this thing is like that" or "This type is available only in 6.d".

I think it is indeed nice to have something for Rakudo-only features, and we have a meta-issue opened for that I believe(or I saw one long ago). But to closely follow Rakudo implementation as if it is the spec: I wonder.

**Comment by JJ** [comment]
Hi

El lun., 4 mar. 2019 a las 10:10, Altai-man (<notifications@github.com>)
escribió:

> I am not sure it fits to the docs well. This documentation suite is:
>
> This documentation is intended to be universal with respect to a given
> version of the specification, and not necessarily tied to any specific Perl
> 6 implementation.
>
> Or this is what we have in README.
>

Yep, that's all good and well in theory. In practice, there's a single
implementation. And the alternative to putting rakudo specific stuff in the
docs is not putting them anywhere. Also, "not necessarily tied" has two
implications. First, that it's not compulsory that we can use specific info
(which we do all the time), but it's not forbidden either. Second, not
documenting specific stuff means that what we document might or might not
be true, and will never be complete.

In general, we use common sense when documenting Rakudo specific stuff, and
we do so in an ad-hoc basis. I simply propose to do the same in this case.
Not all Rakudo additions are "Rakudo" additions. They are things that were
not implemented, disambiguations or clarifications. Some of them get their
own roast tests, and thus are Perl 6, not rakudo. Rakudo additions are in
fact in perl 6 releases, so maybe the title is misleading here.

I believe that what we want is documentation for the spec. So it will be
> good to have a
>

If we wanted that, we would just show the spec or update it.

> select on the top of the site pages, just like other documentation suites
> have for their versions, but in our case it will be v6.c or v6.d(and so
> on in the future). Most of the text is
>

Ugh, more tooling, no, really, please don't. There's an issue related to
release specific stuff, please comment it there. But please don't.

common, but some things may be different. This way we can avoid "And in
> 6.d(and then .e. and so on) this thing is like that" or "This type is
> available only in 6.d".
>

We have some rules for doing that which are in place already. In general,
version-specific things should be specified.

> I think it is indeed nice to have something for Rakudo-only features, and
> we have a meta-issue opened for that I believe(or I saw one long ago). But
> to closely follow Rakudo implementation as if it is the spec: I wonder.
>

As I said, the issue title might be misleading. I'll change that.

**Comment by JJ** [comment]
I have also added the first of these, generated by the script, in this issue #2672
