### ISSUE TITLE
Search input should have autofocus.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#2657]
## The problem

Searching for specific stuff on https://docs.perl6.org requires additional click on search field.

## Suggestions

Search field should have autofocus, so search term can be entered immediately after opening docs site.
BTW: It won't interfere with remaining content because so far this is the only editable input on main page.

**Comment by JJ** [comment]
Search needs a lot of improvements. Thanks a lot for the report, we'll wee what we can do.

**Comment by antoniogamiz** [comment]
https://github.com/perl6/doc/commit/f5139e6d58057fdd1b6567165db7cb097716f2bc fixs this issue.

**Comment by antoniogamiz** [comment]
Mmm I have been testing this and @chloekek is right, this provoked https://github.com/perl6/doc/issues/2836. I first thought to revert this change but after a moment I realized that we only need to add autofocus property right after the page is loaded and ready.

So we only need to add this code to `footer.html`:

~~~js
<script type="text/javascript">
$(document).ready(function() {
  $('query').autofocus = true;
});
</script>
~~~

**Comment by JJ** [comment]
Thanks!
