### ISSUE TITLE
Search selection should set most precise field.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#2658]
## The problem

When searching for "react" and pressing enter user lands on "repeat" page.
When searching for "start" and pressing enter user lands on "X::Proc::Async::AlreadyStarted" page.
It happens because similar results are shown first. And since it applies almost to every keyword it is super annoying.

## Suggestions

Keep categories and their order (they are nice) but set selection (light green highlight) on best matched item. So when enter is pressed best match is automatically chosen.

**Comment by Altai-man** [comment]
See https://github.com/perl6/doc/issues/247 and https://github.com/perl6/doc/issues/1108

**Comment by JJ** [comment]
Actually, I would say it's exactly #1108.

**Comment by coke** [comment]
Closing as a duplicate of #1108 - thanks for the report.
