### ISSUE TITLE
sigiled vs. sigilled

### ISSUE THREAD

**Issue by coke** [perl6/doc#2660]
## The problem

Both versions appear in the docs, and exceptions for each are in the .pws file

## Suggestions

I think because the emphasis is on the first syllable, the l should not be doubled. Convert the usage, remove the other entry from xt/words.pws, and maybe add this to xt/word-variants since it's a common confusion.

**Comment by kawaii** [comment]
> the l should not be doubled

@coke does this apply to `sigilless` too? Or should we keep that with the double l?

**Comment by coke** [comment]
Excellent question, I'm not sure which is right there. Whatever is decided,
let's make sure we only pick one of each.

**Comment by lucs** [comment]
"sigilless", like "soulless" or "tailless", seems preferable.

**Comment by kawaii** [comment]
Great, I guess I don't need to modify my PR then. All occurrences of the word `sigilless` use the same spelling. I think it can be merged now but I'd like someone else to cast an eye over it first as it's my first PR to the repository. :)
