### ISSUE TITLE
Visual differences between site and local versions of docs #2

### ISSUE THREAD

**Issue by hakonhagland** [perl6/doc#2667]
After building the html documentation with `make html` and then running `make run` ,
I can view the local documentation (in Google Chrome) at (e.g. for `NativeCall` module):
```
http://127.0.0.1:3000/language/modules-core#NativeCall_modules
```
but it does not look the same as the main site ( https://docs.perl6.org/language/modules-core ).

## Local appearance:

![p6doc1](https://user-images.githubusercontent.com/6708379/54241409-1cbe9480-4521-11e9-8861-f03226545c26.png)

--------
## docs.perl6.org appearance:

![p6doc2](https://user-images.githubusercontent.com/6708379/54241422-2647fc80-4521-11e9-8b16-9b384b17d553.png)

---------------

See also issue #2518

**Comment by JJ** [comment]
Maybe it's not loading the CSS files? You are running locally with make
run, right?

**Comment by hakonhagland** [comment]
Hi. Yes I am using `make run` :)

**Comment by JJ** [comment]
Sorry, I read that more carefully and saw that you said so. make run does rebuild the css files, so I don't know what could it be.

**Comment by hakonhagland** [comment]
Ok I think I found the problem, after installing `Mojolicious::Plugin::AssetPack` it seems to work

**Comment by JJ** [comment]
Great. Close the issue if you think it's OK now... Or recommend a change to some documentation if you think it's not well explained somewhere.

**Comment by hakonhagland** [comment]
The [docs says](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md): *You can either install the sass command, or the CSS::Sass Perl 5 module*. So I chose the first option:
```
$ sudo apt-get install ruby-full build-essential rubygems
$ sudo gem install sass
```
but apparently I also needed to install `Mojolicious::Plugin::AssetPack` from the second option.

Maybe that should that be clarified in the documentation?

**Comment by JJ** [comment]
Probably. Thanks for the report.
