### ISSUE TITLE
js to perl 6 nutshell example doesn't match rakudo

### ISSUE THREAD

**Issue by ntysdd** [perl6/doc#2672]
## The problem
Currently the JS to Perl 6 nutshell contains an example that doesn't match the rakudo implementation.
```
my \hash = {};
my %hash := hash;
say hash === %hash; #False
```
The current Rakudo implementation (MoarVM version 2018.10) instead say True

## Suggestions
Fix the doc, or fix the implementation.

**Comment by jnthn** [comment]
The implementation is correct; it's just aliasing the same `Hash` object.

**Comment by ntysdd** [comment]
And the '1' === 1 example?
Rakudo says False

Juan Julián Merelo Guervós <notifications@github.com> 于2019年3月14日周四 下午10:58写道：

**Comment by JJ** [comment]
This has been fixed, or is no longer there. I'll include it, just in case it was simply deleted.
