### ISSUE TITLE
map sub and slurpy documentation discrepancies. Does not detail sequences

### ISSUE THREAD

**Issue by drclaw1394** [perl6/doc#2675]
**Problem 1**
There is a discrepancy in the use of the *@ and + slurpy between the source and the docs and [https://docs.perl6.org/routine/map#(List)_routine_map]()

`sub    map(&code, *@elems --> Seq:D)# as listed in the docs`

Looking a bit deeper into in Rakudo src, the only `sub map`  I can find looks like: 

`multi sub map(&code, +values)`

Functionally these are different. Using  the sigilless `+values`  slurpy will allow  the use of a `Seq` where as the `*@` slurpy will only provide a `List` or `Array` it seems.

**Problem 2** 
Documentation [https://docs.perl6.org/type/Signature#Slurpy_(A.K.A._variadic)_parameters]() details that slurpy Arrays and Hashes can used. There is no mention that a sigiless parameter can be used or that it can result in a `Seq` type (neither `Array` or `Hash`).

## Suggestions

1. Updating the documentation around the map sub reflecting how it operates 
2. Add more information to the slurpy documentation  detailing that sigiless variable can be used to generate a `Seq`
3. Clarification / improve language describing the results of a slurpy might not be as declared e.g. 
passing a `Seq` to a `+@` slurpy is actually  `List` not an `Array` etc.

**Comment by JJ** [comment]
A sigilless type can be anything, including Seq. But so can a sigilled Scalar type. There's nothing special about a sigilless type, other that they don't force a context and can be used with any data type. 
We could certainly update the documentation. In some cases it drifts away from the actual definition (or implementation)

**Comment by drclaw1394** [comment]
Using a *$ in signature doesn't slurp up a variable of arguments but gives a compile time error in my testing:
```
sub scalarStar( *$elements) {};
scalarStar(1,2,3);

#To many arguments passed
```
It does allow passing of a `Seq` single argument.


In other testing  I get the following results:

`+$` will slurp up:

- a single `Seq` argument into a `List`
- a single `List` argument into an `Array`
- variable arguments into an `Array` 

A `+ sigiless` will slurp:

- Single `List` or `Array` to `List`
- Variable arguments into a `List`
- Single `Seq` to a `Seq`

A * sigiless 

- gives a syntax error...


It seems the only way to  get a `Seq` through a slurpy and also slurp up variable arguments is by using  the `+sigiless`. This seems pretty important in effectively using concurrency and letting the data 'flow' through a `map` call for example.  From what I can find/understand in the documentation on slurpies, there is no encouragement to use concurrency features and is confusing when trying to use them as its described.

Attached is my simple test/example file:
[slurpytest.p6.zip](https://github.com/perl6/doc/files/2977782/slurpytest.p6.zip)

**Comment by JJ** [comment]
@drclaw1394 you are very right. The problem anyway is the definition (which is also not in List) not matching the actual source. Let's take a look at that. Thanks for the report.
