### ISSUE TITLE
Examples in List are actually Arrays

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2679]
## The problem

Here are [the examples in the intro to `List`](https://docs.perl6.org/type/List):

    my @a = 1, 2, 3;

They are actually `Array`s: 

    my @a = 1, 2, 3;
    say @a.^name ;# OUTPUT: «Array␤»

## Suggestions

Revise the examples and fix them.

**Comment by uzluisf** [comment]
I gave it a try at fixing the examples.

```
my $s = (1, 2, 3);
for $s { }      # one iteration
for $s.list { } # three iterations

my $t = [1, 2, 3];
for $t { }      # one iteration
for $t.list { } # three iterations

my @a = 1, 2, 3;
for @a { }      # three iterations
for @a.item { } # one iteration
```

```
my $a = (1, 2, 3);
my $nested = ($a, $a);  # two elements 

my $flat = $nested.map({ .Slip });  # six elements, with explicit Slip 

my @b = <a b>;
@b.append: $a.list;     # The array variable @b has 5 elements, because
                        # the list $a is the sole argument to append

say @b.elems;           # OUTPUT: «5␤» 

my @c = <a b>;
@c.append: $a.list, 7;  # The array variable @c has 4 elements, because
                        # the list $a wasn't the only argument and thus
                        # wasn't flatten by the append operation

say @c.elems;           # OUTPUT: «4␤» 

my @d = <a b>;
@d.append: $a;          # The array variable @d has 3 elements, because 
                        # $a is an itemized list and as far as append is
                        # concerned a single element

say @d.elems;           # OUTPUT: «3␤» 
```

BTW, the sentence "The difference is that ... element, as long as it's part of another ." seems to be incomplete.

**Comment by JJ** [comment]
El jue., 21 mar. 2019 a las 20:06, Luis F. Uceta (<notifications@github.com>)
escribió:

> I gave it a try at fixing the examples.
>
> my $s = (1, 2, 3);
>
> for $s { }      # one iteration
>
> for $s.list { } # three iterations
>
>
>
> my $t = [1, 2, 3];
>
> for $t { }      # one iteration
>
> for $t.list { } # three iterations
>
>
>
> my @a = 1, 2, 3;
>
> for @a { }      # three iterations
>
> for @a.item { } # one iteration
>
>
> my $a = (1, 2, 3);
>
> my $nested = ($a, $a);  # two elements
>
>
>
> my $flat = $nested.map({ .Slip });  # six elements, with explicit Slip
>
>
>
> my @b = <a b>;
>
> @b.append: $a.list;     # The array variable @b has 5 elements, because
>
>                         # the list $a is the sole argument to append
>
>
>
> say @b.elems;           # OUTPUT: «5␤»
>
>
>
> my @c = <a b>;
>
> @c.append: $a.list, 7;  # The array variable @c has 4 elements, because
>
>                         # the list $a wasn't the only argument and thus
>
>                         # wasn't flatten by the append operation
>
>
>
> say @c.elems;           # OUTPUT: «4␤»
>
>
>
> my @d = <a b>;
>
> @d.append: $a;          # The array variable @d has 3 elements, because
>
>                         # $a is an itemized list and as far as append is
>
>                         # concerned a single element
>
>
>
> say @d.elems;           # OUTPUT: «3␤»
>
>
As long as they are well explained, it's OK.

>
>  BTW, the sentence "The difference is that ... element, as long as it's
> part of another ." seems to be incomplete.
>

Right.
