### ISSUE TITLE
so … what?

### ISSUE THREAD

**Issue by isomorphisms** [perl6/doc#2693]
## The problem

I don’t like this:

https://docs.perl6.org/type/Mu#method_so

> method so()
> Returns a Bool value representing the logical non-negation of an expression. One can use this method similarly to the English sentence: "If that is so, then do this thing".

## Suggestions

What is "logical non-negation" and why is it the simplest way to explain what `so` means? Please re-explain that.

**Comment by JJ** [comment]
OK
