### ISSUE TITLE
Lexical module loading section doesn't say which P6 versions have which behaviour [docs]

### ISSUE THREAD

**Issue by cxw42** [perl6/doc#2698]
## The problem

#1043 added a [doc section](https://docs.perl6.org/language/modules#Lexical_module_loading) about lexical module loading.  The docs now describe the old behaviour (register classes globally) and the new behaviour (register classes lexically) --- with old vs. new defined as of 2016!  I cannot find anywhere in the section that says "in 6.c+, `use Bar;` expressly" or anything like that.

## Suggestions

If the old behaviour is no longer pertinent, perhaps it would be sufficient to remove the discussion of the old and leave only the new.

Either way, would you please mark which language version(s) the section (or portion thereof) applies to?  

Thanks!

**Comment by JJ** [comment]
Thanks for the report. That is why I have included this issue on versioning #2690 #2647. Also, revise old documents *always*.

**Comment by JJ** [comment]
That's a very good catch, thanks. And the document itself wasn't old, but was addressing an issue that was old. My fault for not checking the code before adding it. There might be some more of this here and there...
