### ISSUE TITLE
Using sigiless variables in the Python migration doc might be LTA

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2699]
## The problem

This was mentioned by user `gks` [in `#perl6`](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-03-27#l462)

Backslashes might be more confusing than sigils, even if the result seems to be closer to Python syntax. Also [sez @jnthn](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-03-27#l491)

> There's no reason to use them

## Suggestions

`guifa` (I think he's @alabamenhu here) [suggested other syntax](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-03-27#l508). Evaluate that, or something similar.

**Comment by Kaiepi** [comment]
Sigils and containers are one of the first things I explain in the JS nutshell. Maybe the Python nutshell could use the same treatment

**Comment by JJ** [comment]
@Kaiepi yep, but still, that's not really an use case for them...
