### ISSUE TITLE
$::{'foo'} doesn't work

### ISSUE THREAD

**Issue by arnesom** [perl6/doc#2700]
## The problem
https://docs.perl6.org/language/packages#Direct_lookup

> my $foo = 12;  say $::{'foo'};
===SORRY!=== Error while compiling:
Variable '$' is not declared  ------> <BOL>⏏$::{'foo'}

It applies to this version as well:
> say $::&lt;foo&gt;;

(Both in REPL and as a program. )

> perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03

## Suggestions
I don't know if it is supposed to work, so either change the documentation or
implement it (or file an error)

I think we can live without this syntax, as this works:
> say ::{'$foo'};

**Comment by labster** [comment]
The form itself is speculated in S02, but if it's not tested, well.

> Variable '$' is not declared

The problem I see here is an LTA error, as the anonymous variable`$` doesn't have to be declared, so the error doesn't even make sense.   

Similarly, 
> > $ perl6 -e 'my $foo = 1; $::("$foo");'
> No such symbol ''
>   in block <unit> at -e line 1
> > $ perl6 -e 'my $foo = 1; $::(q<$foo>);'
> No such symbol ''
>   in block <unit> at -e line 1

That's not accurate either, or very helpful, but at least it's talking about symbols.

**Comment by JJ** [comment]
Either way, it does not belong in the documentation.

**Comment by JJ** [comment]
Maybe it would be interesting to open an issue in Rakudo about the LTA error.
