### ISSUE TITLE
Is default default a thing?

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2702]
## The problem

"default default" is repeated several times in [Signature](https://docs.perl6.org/type/Signature)

## Suggestions

We're getting into meta territory here. It might be correct since we are talking about a default value that is assigned by default. But simply saying default is OK. We don't need to acknowledge all the levels here. Maybe change it to "default value" would be easier to understand.

**Comment by JJ** [comment]
It's apparently a [common phrase](https://github.com/perl6/doc/commit/97f1ddef3d4a5d453a8220115d41bf29dcef3287); it's allowed at least in the dups test. Still. Kinda does not sound right. If everyone is OK with that, I'll just close...

**Comment by JJ** [comment]
I actually haven't found any other place it's used, neither [in Google](https://www.google.com/search?q=is+%22default+default%22+correct+in+English%3F&safe=off&client=ubuntu&hs=ESC&channel=fs&ei=NymfXK3SM8euar7DnqgP&start=10&sa=N&ved=0ahUKEwjtycHVuanhAhVHlxoKHb6hB_UQ8NMDCJEB&biw=1920&bih=930) or [in GitHub](https://github.com/search?l=Text&p=2&q=%22default+default%22&type=Code). (Or outside that document).
It's not a big deal, but I think that *default value* would be clearer here, and convey the same meaning.

**Comment by JJ** [comment]
Finally found [at least one](https://stackoverflow.com/questions/44608782/where-are-matplotlibs-default-defaults-located) I'll just close then, although I still think something like "default values used by default" might be a bit clearer. As a matter of fact, if you insert "default defaults" into google translator the translation is a bit closer to that.

**Comment by tbrowder** [comment]
@JJ, I just saw this and I agree with you. All instances of "default default[s]" should be "default value[s]."

**Comment by tbrowder** [comment]
UPDATE: Erg, I see now why the doubled "defaults" should be allowed. In the signature case, most should be "defaults value[s]" with only one or two exceptions when **specifically** referring to the attribute and then use italics or bold-faced font to highlight the attribute instead of its adjective.

**Comment by tbrowder** [comment]
I made a stab at a solution--needs other eyes to check.

**Comment by rafaelschipiura** [comment]
Looks good.
