### ISSUE TITLE
Dead link to https://docs.perl6.org/syntax/Number%20literals

### ISSUE THREAD

**Issue by drclaw1394** [perl6/doc#2704]
## The problem
Dead link to https://docs.perl6.org/syntax/Number%20literals found on page https://docs.perl6.org/routine/parse-base#(Str)_routine_parse-base

## Suggestions
Maybe the link is trying to reach https://docs.perl6.org/language/syntax#Number_literals

**Comment by JJ** [comment]
Thanks for the report. Normally there's something a bit deeper with those dead links, we'll have to investigate.

**Comment by Scimon** [comment]
I wonder why you were looking at `parse-base` today ;) ?

**Comment by drclaw1394** [comment]
LOL yes indeed . Looking for issues in the docs of course :-P .   Perl6 makes the base 35 challenge very straight forward!

**Comment by JJ** [comment]
It's very likely that happened here: b67e24c681c135175b9c4419f7fe9b8887208c94 due to the weird `syntax` page generation. Let's see if I can fix that.
