### ISSUE TITLE
Comment using in enums names that don't follow the bare-identifier syntax

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2710]
## The problem

Enums allow you to use "bare strings", as long as they follow the bare identifier syntax. If you use them with any Unicode char:

```perl6
enum Suit <♣ ♦ ♥ ♠>; say Suit::<♣>; # OUTPUT: «♣␤»  
enum Suit <♣ ♦ ♥ ♠>; say ♣ ; #OUTPUT: «(exit code 1) ===SORRY!===␤Argument to "say" seems to be malformed␤at /t…»
```

## Suggestions

Extend on the enum syntax, and include more examples.

**Comment by Xliff** [comment]
Where would you suggest this be done. there are two places and neither one seems suitable:

* https://github.com/perl6/doc/blob/master/doc/Language/enumeration.pod6
* https://github.com/perl6/doc/blob/master/doc/Type/Enumeration.pod6

(Also, for some reason the second link doesn't format properly on GitHub. Wonder what that's about. Should that be another issue?)

**Comment by JJ** [comment]
I would say the first. Never seen the second. Looks positively ugly. Some glitch in rendering. Maybe another issue.

**Comment by JJ** [comment]
Sorry, fat fingers.

**Comment by Xliff** [comment]
@JJ: There's also http://github.com/perl6/doc/blob/maser/doc/language/typesystem.pod6#enum, which looks to be the main section. I think I will see about using this one.

**Comment by Xliff** [comment]
@JJ: There's also http://github.com/perl6/doc/blob/maser/doc/language/typesystem.pod6, which looks to be the main section. I think I will see about using this one.
