### ISSUE TITLE
public build logs

### ISSUE THREAD

**Issue by daxim** [perl6/doc#2720]
External site search results are polluted by documents like <https://docs.perl6.org/build-log/build-2018-12-15T20:30+00:00.log>. This is relevant to the sysadmin, but not the documentation consuming end user. Exclude them from search indexing, or from the public Web altogether.

**Comment by JJ** [comment]
What kind of search results in that page?

I'll see what I can do anyway.

**Comment by daxim** [comment]
> What kind of search results in that page?

I searched the text `!ww` and external site search found `ww` in the log.

> 6c8f2a5

You wrote `build_log`, but URI path segment is `build-log`.

**Comment by JJ** [comment]
Right. Sorry.
