### ISSUE TITLE
Methods `target` and `pos` are documented in class `Cursor`, but that is an alias for `Match`

### ISSUE THREAD

**Issue by moritz** [perl6/doc#2736]
## The problem

`Cursor` is an alias for `Match`, but the methods `target` and `pos` are documented just for class `Cursor`

## Suggestions

Fold the documentation of `Cursor` into `Match`, and just document that `Cursor` is an alias for `Match`.

**Comment by JJ** [comment]
Some methods are part of [`NQPMatchRole`](https://github.com/perl6/nqp/blob/master/src/QRegex/Cursor.nqp), which is, well, NQP. And there are lots of methods there. Let's see...
