### ISSUE TITLE
Improve description of Attributes

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2745]
## The problem

The definition of Attribute is kind of convoluted, with the source not reflecting actually what's in there. Most methods are defined in [`BOOTSTRAPATTR`](https://github.com/rakudo/rakudo/blob/f1c80fdd9310c14208e511c61f04f264b0f4dae7/src/Perl6/Metamodel/BOOTSTRAP.nqp#L19-L45), and then baked into Attribute using the metamodel below.

The [documentation](https://docs.perl6.org/type/Attribute#index-entry-is_default_(Attribute)) also lists traits in two separate places, with some definitions repeated.

## Suggestions

Revise thoroughly and improve where possible.

**Comment by lizmat** [comment]
Looks to me that the documentation of Attribute is pretty complete.  Added documentation of methods I think are missing with ac9f8e9af878b38112a8 .

Perhaps the traits issue requires a separate issue?

**Comment by lizmat** [comment]
@JJ unless you think some documentation is still missing, this can be closed afaiac

**Comment by JJ** [comment]
Please do so. Great job.
