### ISSUE TITLE
Document NQPMatchRole methods within Match.

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2746]
## The problem

Some methods `Match` takes from [`NQPMatchRole`](https://github.com/perl6/nqp/blob/master/src/QRegex/Cursor.nqp#L69-L1136) are documented. Some are not.

## Suggestions

Check them out, document them. Start with those that are spec, continue (maybe) or mention (surely) those that are not.

* [ ] chars [tested here](https://github.com/perl6/roast/blob/master/S05-match/positions.t)
* [ ] make (not tested explicitly)

While we're at it, maybe revise the rest of the methods to check for correctness in the definition.

**Comment by moritz** [comment]
FTR I have found four instances of `Match.make` in the test suite, so I'd contest the "not tested explicitly" comment.
