### ISSUE TITLE
Repeating subsections under several sections

### ISSUE THREAD

**Issue by uzluisf** [perl6/doc#2752]
## The problem

There are several subsections (e.g., Subscripts, Syntax, etc.) repeating under [Fundamental topics](https://docs.perl6.org/language.html#Fundamental_topics). There also two [Advanced topics](https://docs.perl6.org/language.html#Advanced_topics) with repeating subsections as well.

## Suggestions

Remove the repeating sections and subsections. ;-)

**Comment by taboege** [comment]
That page is generated by htmlify and the duplicated entries come from the Perl6::Documentable::Registry being fed multiple copies of those entries. This output of the PathChecker is highly related:
```
duplicated path html/language/syntax.html
duplicated path html/language/system.html
duplicated path html/language/traits.html
duplicated path html/language/typesystem.html
duplicated path html/language/unicode.html
duplicated path html/language/unicode_ascii.html
duplicated path html/language/variables.html
duplicated path html/language/experimental.html
```

I don't know yet where the duplicate copies of the Documentables come from. A patch for the symptom could be:
``` diff
diff --git a/htmlify.p6 b/htmlify.p6
index d4c19467..2e2a35bc 100755
--- a/htmlify.p6
+++ b/htmlify.p6
@@ -905,7 +905,7 @@ sub write-index-files($manage) {
     if $manage {
         my @p-chunks;
         my @end;
-        for $*DR.lookup('language', :by<kind>).list {
+        for $*DR.lookup('language', :by<kind>).list.unique(as => *.name) {
             if .section {
                 @p-chunks.push( pod-table(@end.map({[
                     pod-link(.name, .url),
```
Maybe the Documentable::Registry should &unique its contents anyway? I don't know enough about htmlify to judge.

**Comment by JJ** [comment]
Then it's my fault. Let me fix that.

**Comment by JJ** [comment]
The problem is how that page is generated. It takes files in the directory which have been generated by make manage-pod-source. If it's not clean, it will do things like that. I really want to change that in the near future, not to mention page generation takes an inordinate amount of time.

**Comment by JJ** [comment]
And all this is because I'm rsyncing my local pages to the (provisional) document site. And I didn't clean everything properly. It's generating it again, will be ready in no time.

**Comment by uzluisf** [comment]
Glad you figured it out! @JJ++
