### ISSUE TITLE
Dead link in pod section of the Perl 5 to Perl 6 syntax page

### ISSUE THREAD

**Issue by tmtvl** [perl6/doc#2753]
## The problem

The pod section of the Perl 5 to Perl 6 guide - syntax page has a link to https://design.perl6.org/S26.html, which is dead.

## Suggestions

If the page has moved we need to change the link, otherwise I don't know, maybe just link to the normal pod page?

**Comment by moritz** [comment]
The link is dead because the server that the design.perl6.org site was hosted on had a hardware failure.

I recommend waiting until the infrastructure rebuilding efforts have been completed, I suspect we'll be able to bring back the site with the same URL as before.
