### ISSUE TITLE
Possibly wrong example in CompUnit::Repository::FileSystem docs

### ISSUE THREAD

**Issue by frithnanth** [perl6/doc#2766]
## The problem
In https://docs.perl6.org/type/CompUnit::Repository::FileSystem the example under "method candidates" reads:
```perl6
my $repo = CompUnit::Repository::FileSystem.new(prefix => $*CWD);
my $dist = $repo.candidates("Zef").head;
say "Zef version: " ~ $dist.meta<version>;
```
When I try to execute the first line I get an error:
`Type check failed in binding to parameter '$prefix'; expected Str but got IO::Path`
I found the same kind of error in the example under "method files".
## Suggestions
This seems to work:
```perl6
my $repo = CompUnit::Repository::FileSystem.new(prefix => ~$*CWD); # or $*CWD.Str or $*CWD.path or similar
```

**Comment by rafaelschipiura** [comment]
@lizmat

**Comment by lizmat** [comment]
I think this is not a documentation, but a code bug.  It should be smart enough to take a `IO::Path`.  Could you file this as a rakudo issue ?

**Comment by rafaelschipiura** [comment]
Submitted as R#2879.

**Comment by JJ** [comment]
The issue hasn't gone away with the bug filing. It should still be addressed.
