### ISSUE TITLE
Cursor should probably be taken off the type graph

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2770]
## The problem

Cursor is just another name for Match. Having it as two separate ovals in the type graph does not make a lot of sense.

## Suggestions

Take that line out.

**Comment by antoniogamiz** [comment]
I've deleted line [99](https://github.com/perl6/doc/blob/602dbaba18cea944e8d2bd818a4e4437a2c932e9/type-graph.txt#L99) from [type-graph.txt](https://github.com/perl6/doc/blob/master/type-graph.txt) and rebuilt doc site. Everything looks correct so I will close this issue.
