### ISSUE TITLE
Incorrect description in the example of post-circumfix ([ ]) operator

### ISSUE THREAD

**Issue by kjkuan** [perl6/doc#2773]
## The problem
In the doc for the postcirumfix operator [`[ ]`](https://docs.perl6.org/language/operators#circumfix_[_]) the second example is wrong:
```perl6
# The output will be (almost) the same if we attempt to flatten it using | a. k. a. the flattener, which puts it in a list context:
say .perl for | 3,2,[1,0]; # OUTPUT: «3␤2␤[1, 0]␤» 
```
Here `[1, 0]` is not itemized since we are creating a `List` instead of an `Array`; it has nothing to do with the `|` operator, which creates a `Slip` that flattens in list context (but it still won't flatten an itemized member).

So, the example produces the same output if we just do:
```perl6
say .perl for 3,2,[1,0]; # OUTPUT: «3␤2␤[1, 0]␤» 
```
but it gives the same itemized `$[1,0]` even if we use `|` on the array:
```perl6
say .perl for | [3,2,[1,0]]; # OUTPUT: «3␤2␤$[1, 0]␤» 
```
## Suggestions

Maybe don't talk about the second example at all? Or show how one can flatten an Array with nested List / Array if that's what we want to show:
```perl6
say .perl for [3,2,[1,0]]>>.List.flat; # OUTPUT: «3␤2␤1␤0␤»
```

**Comment by JJ** [comment]
Well, in the context of that operator I'm not sure the suggestion will fit. But will have a look anyway and try to fix it. Thanks for the report.

**Comment by lizmat** [comment]
I'd say, remove the whole second example.  It is only confusing.

**Comment by lizmat** [comment]
Please reopen / revert if disagree: I'm only trying to get some action on issues  :-)

**Comment by rafaelschipiura** [comment]
@lizmat Don't even need to mention that, it's how this repo works by default.
