### ISSUE TITLE
doc.perl6.org cert invalid

### ISSUE THREAD

**Issue by coke** [perl6/doc#2778]
https://docs.perl6.org/ - no issue

https://doc.perl6.org/ - Chrome 74.0.3729.131 complains about cert:

```
Your connection is not private
Attackers might be trying to steal your information from doc.perl6.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

This server could not prove that it is doc.perl6.org; its security certificate is from perl6.org. This may be caused by a misconfiguration or an attacker intercepting your connection.


```

**Comment by JJ** [comment]
It's a letsencrypt certificate created by @timotimo; but just for the main
page. I didn't know that second page existed...

Anyway, it's provisional. I guess when it's taken back to the permanent
place it will be properly signed

**Comment by lizmat** [comment]
Checking the certificate now, it says:

    Expires: Tuesday, 23 July 2019 at 14:29:07 Central European Summer Time

so closing...

**Comment by lizmat** [comment]
Oops, this is about *doc*.perl6.org, not *docs*.perl6.org.  Reopening.

**Comment by JJ** [comment]
I really don't know. doc.perl6.org is not official. My Firefox issues a warning, but does not have a problem with that. http://doc.perl6.org returns the nginx default page... So I really don't know if this needs to be fixed. If it is, we should address a number of issues.

**Comment by JJ** [comment]
Apparently you need to use the subjectAltname extension to the generation of the certificate. Maybe @timo can do that? https://www.openssl.org/docs/man1.0.2/man5/x509v3_config.html#Subject-Alternative-Name

**Comment by timo** [comment]
fixed
