### ISSUE TITLE
What does ‘serial’ do?

### ISSUE THREAD

**Issue by p6steve** [perl6/doc#2780]
## The problem

https://stackoverflow.com/questions/56057931/what-does-serial-do

**Comment by p6steve** [comment]
hi jj - for what its worth - I have relied on docs.perl6.org for a couple of years now and despite some criticisms I have heard, personally I find that it is very accurate and complete... so please do not break it!!

**Comment by JJ** [comment]
Er... I already "broke" it this morning,closing an older issue. If it's
good now, I guess it's well closed :-)

**Comment by JJ** [comment]
Ah, you mean break the docs in general? Also, we welcome any criticism as
long as it's in the form of an issue :-)

**Comment by JJ** [comment]
Other than that, this was addessed when closing #1803

**Comment by rafaelschipiura** [comment]
@p6steve We consider this already addressed. If you need further clarification, please reopen the bugs.
