### ISSUE TITLE
::Metamodel::MethodContainer is not composable

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2782]
## The problem

While checking #2764 and running all tests via xt/examples-compilation.t:

```
# class Metamodel::ParametricRoleHOW
#     does Metamodel::Naming
#     does Metamodel::Documenting
#     does Metamodel::Versioning
#     does Metamodel::MethodContainer
#     does Metamodel::PrivateMethodContainer
#     does Metamodel::MultiMethodContainer
#     does Metamodel::AttributeContainer
#     does Metamodel::RoleContainer
#     does Metamodel::MultipleInheritance
#     does Metamodel::Stashing
#     does Metamodel::TypePretense
#     does Metamodel::RolePunning
#     does Metamodel::ArrayType {}
# <anon|4044>::Metamodel::MethodContainer is not composable, so <anon|4068>::Metamodel::ParametricRoleHOW cannot compose it
not ok 4104 - doc/Type/Metamodel/ParametricRoleHOW.pod6 chunk 3 starts with “class Meta” compiles
# Failed test 'doc/Type/Metamodel/ParametricRoleHOW.pod6 chunk 3 starts with “class Meta” compiles'
# at xt/examples-compilation.t line 157
```
This is the only one that fails in ParametricRoleHOW

## Suggestions

Check the definition.

**Comment by JJ** [comment]
This does not happen if it's run independently, but it happens consistently if I run the whole set of examples.

**Comment by antoniogamiz** [comment]
I have checked both definitions https://github.com/rakudo/rakudo/blob/2019.03.1/src/Perl6/Metamodel/ParametricRoleHOW.nqp and https://github.com/rakudo/rakudo/blob/master/src/Perl6/Metamodel/ParametricRoleHOW.nqp.

It looks like they are the same.  In addition, if you try to execute `class Foo does Metamodel::MethodContainer {}; say Foo;`.
