### ISSUE TITLE
The difference between Lock and Lock::Async could be explained more plainly

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#2784]
## The problem
This is the explanation for what `Lock` does:
> A Lock is a low-level constructor for ensuring that only one thread works with a certain object at a given time, or runs a piece of code (called the critical section).

This is explained clearly and is simple to understand.

Now here is the explanation for what `Lock::Async` does: 
> An asynchronous lock provides a non-blocking non-re-entrant mechanism for mutual exclusion. The lock method returns a Promise, which will already be kept if nothing was holding the lock already, so execution can proceed immediately. For performance reasons, in this case it returns a singleton Promise instance. Otherwise, a Promise in planned state will be returned, and kept once the lock has been unlocked by its current holder. The lock and unlock do not need to take place on the same thread; that's why it's not re-entrant.

What? I don't understand a word of this.

## Suggestions
Rewrite the intro for `Lock::Async` in plain Engligh and elaborate on how the two types of locks differ.

**Comment by jnthn** [comment]
The one for `Lock::Async` is at least accurate, though indeed far too dense. The `Lock` one, for all its "plain English"-ness, is actually a bit off:

> a low-level constructor

Maybe meant "construct"?

> ensuring that only one thread works with a certain object at a given time

That's only if you make it mean that. There's no actual link between the lock and any other object, and that's often a point of confusion too.

I'll see if I can make things both more precise and more approachable (though I don't think we should shy away from using terminology that's meaningful to those with previous concurrency experience; somebody with an amount of that would probably find the `Lock::Async` description concise and informative.)
