### ISSUE TITLE
Code quality issues in xt/examples-compilation.t

### ISSUE THREAD

**Issue by coke** [perl6/doc#2798]
Based on commits added for  #2782.

* Commented out code in the file. Remove it.
* Solo is now the only option, so there's no need to call it out specifically - any instances referring to it in this text file (and in the POD and the docs) should be removed.
* Some of the extra work that was being done to support the EVAL approach is not needed to run in solo mode with -c. Much of this extra code generation can be removed. 
* The plan for the # of tests was removed. Why? Can we add it back in?

**Comment by JJ** [comment]
I'm trying to remember why, probably no good reason. I'll try to add it back in.

**Comment by JJ** [comment]
All of these issues have been addressed with d51503be0d6b25b76a87c85fed2f68b7f9d07b09 except for the last one. I don't think it's really necessary, but I can add it if needed.

**Comment by JJ** [comment]
The code was trying to solve issue #2764, which was about the amount of memory. The plan needed to have all code chunks in a single array, and counting it, and then proceeding to examine all chunks in the array one by one. This obviously contributed to the memory problems, so was eliminated. I don't see a way of adding a plan back in if you don't count the chunks in advance and then work with them. If you don't want to hold them in memory, a first pass would count them, a second would actually extract and test them. That would make everything slower again. So regarding your last question, no, I don't think we can unless you think of a better way.

**Comment by taboege** [comment]
I have some refactoring of that test `stash`ed away which processes every POD file in its own subtest, to have only one file's examples in memory at a time. I didn't benchmark it because #2764 was initially resolved earlier, but that would bring the test plan back in the sense that you see how many *files* you have left.

**Comment by JJ** [comment]
@taboege that's not actually a problem. The files are kept in `@files` so converting that into a plan could actually be done, then putting that into a subtest could be done too. But I don't see we are adding anything valuable there, other than saving the "count" we are using (to substitute it with the test number). If it does not add too much overhead, it could be done, but I see that as a different issue, and not exactly what @coke wants, which was to have a plan that includes all chunks (as it was in the beginning)

**Comment by coke** [comment]
I’d rather have a plan showing files with the sub tests unknown than nothing.

**Comment by taboege** [comment]
Please see #2812

**Comment by JJ** [comment]
If everyone's OK, I think this can be closed.

**Comment by taboege** [comment]
Is anything else wanted?

**Comment by JJ** [comment]
Looks great. Thanks!

**Comment by coke** [comment]
BTW, the reason I asked for a plan is because we want to catch issues when processing aborts for some reason (as we see in #2832)

**Comment by taboege** [comment]
Sure, I love test plans – unconditionally :-)
