### ISSUE TITLE
Nil error/warning in xt/examples-compilation.t

### ISSUE THREAD

**Issue by coke** [perl6/doc#2799]
```
xt/examples-compilation.t .. 5136/? Use of Nil in string context
  in sub starts-with at xt/examples-compilation.t line 164
```

Since there's no EVAL anymore, this must be an actual issue in the test file (more specifically in how it's processing the data for the test - but it's not thrown by trying to compile the code.)

**Comment by JJ** [comment]
Just to be sure, this is a warning, right? Does it happen in any particular file?

**Comment by JJ** [comment]
Previously, since they were EVAL'ed, "use Test" was already assumed. I had to edit all pieces of code here to include use Test, but missed this.
