### ISSUE TITLE
Colored source code

### ISSUE THREAD

**Issue by baby-gnu** [perl6/doc#28]
Hello,

Could you highlight the source code on the web site?

Regards

**Comment by moritz** [comment]
One reason that makes good syntax hilighting hard on the server side is that Perl 6 Pod allows things like this:

    =for code :allow<B L>
    L<say> "abc"B<.L<uc>>; 

And that make s the `.uc` bold and the `uc` both bold and a link. Finding support for that in a syntax hilighter is hard.

**Comment by moritz** [comment]
To elaborate on the previous point, it'd be fine to skip code blocks with `:allow<...>` from syntax hilighting (at least until we have found a solution to that challenge)

**Comment by paultcochrane** [comment]
Added syntax highlighting with [pygments](http://pygments.org/) to `htmlify.p6` via the new `Pod::To::HTML` callback mechanism in the `add_pygments_highlighting` branch (commit 56d3bae).  `pygments` needs to be installed first for this to work.  Note: this is a work in progress!  Any recommendations for improvement are most welcome :-)

It would be helpful to be able to call some of the routines from `Pod::To::HTML` within the callback so as to remove the (mostly) repeated `node2inline()` functionality.
