### ISSUE TITLE
Submethods from chapter "Object orientation" not mentioned in instant search results

### ISSUE THREAD

**Issue by hakonhagland** [perl6/doc#2816]
Searching for `submethod` at [docs.perl6.org](https://docs.perl6.org), the only result I get is [class Submethod](https://docs.perl6.org/type/Submethod) (the results shown in the autocomplete instant result dropdown list).

But there is also a section about `submethods` in chapter [Object orientation](https://docs.perl6.org/language/objects#Submethods). I wonder why this is not shown in the results? And maybe it should be fixed.

See also issue #2265 .

**Comment by JJ** [comment]
Thanks for the issue, we'll try to fix that. But the issue you mention is a different problem, namely, not indexing `=head2 submethod xxx`
