### ISSUE TITLE
Proc.pid refers to `$*PID` — but is this true?

### ISSUE THREAD

**Issue by treyharris** [perl6/doc#2821]
## The problem
In the documentation for [`Proc.pid`](https://docs.perl6.org/type/Proc#method_pid), we say:
> Returns the $*PID value of the process if available, or Nil.

The reference to `$*PID` seems a bit unusual here. _If_ the process is itself a Perl 6 program running in its own separate process from the caller, then it would be true, but in any other case the link to `$*PID` seems tenuous at best to me.

Is there a reason I'm not seeing for linking this method to the `$*PID` dynamic variable?

## Suggestions

If there is a reason for referring to `$*PID`, perhaps it should be elaborated upon. But if the sentence,

> Returns the process identity value (of the same type as `$*PID`) of the process if available, or otherwise `Nil`.

would be an acceptable substitution, I think it would be less confusing.

**Comment by JJ** [comment]
I don't think there is. Will fix.
