### ISSUE TITLE
unique, repeated and squish missing from List

### ISSUE THREAD

**Issue by taboege** [perl6/doc#2834]
## The problem

These three methods on Any link to **non-existing** documentation of the same method on List:
* [Any.unique](http://docs.perl6.org/type/Any#method_unique)
* [Any.repeated](http://docs.perl6.org/type/Any#method_repeated)
* [Any.squish](http://docs.perl6.org/type/Any#method_squish)

Not only are the links dangling, the methods are not documented on List. I looked through the entire page for links to List methods, those are the only broken ones.

## Suggestions

I don't know if the documentation is now supposed to be in Any and it was just forgotten to remove the links to List, or if the methods really got lost. Related to efforts in #1494? That has to be found out before it is fixed.

**Comment by JJ** [comment]
Good catch. I think they went to the independent routines. Will check.
