### ISSUE TITLE
Pointy Block syntax not in index

### ISSUE THREAD

**Issue by rehsack** [perl6/doc#2835]
## The problem
Many examples of Perl 6 use the pointy block syntax.

## Suggestions
Add 'pointy block' to the index, how ever. It seems, a special page is already there: https://docs.perl6.org/syntax/-%3E

For the page itself, it should be clarified that the "->" belongs to the block and how it does.

**Comment by JJ** [comment]
It's a "syntax" page, to probably the index should point there.
