### ISSUE TITLE
String length in bytes not obvious.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#2839]
## The problem

Information how to get string length in bytes (the fact that string has to be encoded first) is hard to find. Fact observed IRL.

## Suggestions

Use of Str.encode.bytes to get byte length should be mentioned in:

https://doc.perl6.org/language/5to6-perlfunc#length - For sure. Method `length` is often used in Perl5 in bytes context.

https://doc.perl6.org/type/Str#routine_chars - It would be nice to have such complementary info there.

**Comment by JJ** [comment]
I've just changed the last. I'm not too keen on maintaining, or making exhaustive, the 5 to 6 pages. They were useful at the beginning, but right now it's not so clear that people starting with Perl 6 come from Perl 5.
