### ISSUE TITLE
Methods in X::AdHoc are all wrong

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2840]
## The problem

`.payload` is the only documented method, and it's not in the source:

https://github.com/rakudo/rakudo/blob/969aa440c5e2ce2686b807af2ba3e5f43d845358/src/core/Exception.pm6#L122-L142

The methods in the source are not documented.

## Suggestions

Include real methods with caveats for non-spec ones.

**Comment by Altai-man** [comment]
>and it's not in the source:

It is in the source as an attribute: https://github.com/rakudo/rakudo/blob/969aa440c5e2ce2686b807af2ba3e5f43d845358/src/core/Exception.pm6#L123

What do we do with accessors in this case? They are technically attributes and technically provide methods.

As for missing methods: agreed.

**Comment by JJ** [comment]
We don't have any special notation for attributes, I think. Let's just
leave it that way for now.
