### ISSUE TITLE
RFE: -M switch for selective imports

### ISSUE THREAD

**Issue by ToddAndMargo** [perl6/doc#2852]
Request for enhancement.

I posted this over on the chat group and on the mailing list with no answer, so I figure it does not yet exist in Perl 6.

Please include a "-M" switch syntax for selective imports of subs from modules .
https://docs.perl6.org/language/modules#Exporting_and_selective_importing

For instance:

PrintBlue export from PrintColors.pm6 with:
      sub PrintBlue  ( **@args ) is export( :PrintBlue )  { print color('bold'), color('blue'),  |@args, color('reset'); }

There "seems" to be no syntax for importing "PrintBlue" with the -M switch.
       perl6 -I /home/linuxutil/p6lib -M "PrintColors :PrintBlue" -e 'PrintBlue( "Blue\n" );'
       Could not find PrintColors :PrintBlue at line 1 in:

The following does not work:
    -M "PrintColors :PrintBlue"
    -M"PrintColors :PrintBlue"
    -M "PrintColors::PrintBlue"
    -M PrintColors::PrintBlue
    -M "PrintColors:PrintBlue"
    -M PrintColors:PrintBlue

Many thanks,
-T 

p.s.  This does work, but it does not "-M":
    perl6 -e 'use lib "/home/linuxutil/p6lib"; use PrintColors :PrintBlue; PrintBlue( "Blue\n" );'
    Blue

**Comment by JJ** [comment]
If this is a wish list for a new Rakudo command line feature, it's better if you comment it in the Rakudo repository. The documentation should only reflect what's actually in there (regardless of its degree of perfection), I'm afraid.

**Comment by ToddAndMargo** [comment]
RFE: -M switch for selective imports
https://github.com/rakudo/rakudo/issues/2981

**Comment by JJ** [comment]
If you don't mind then, close this issue.

**Comment by ToddAndMargo** [comment]
I usually leave that to the administrator, but I will close on your request
