### ISSUE TITLE
S05.html not found

### ISSUE THREAD

**Issue by wamiks** [perl6/doc#2854]
## The problem
https://design.perl6.org/S05.html  is returning not found. This is the link in serveral doc pages on explaining LTM.

Also, it would be nice in proto section in grammars to state whether the alternations are LTM or traditional, ie first matching. I had to test to figure this out.

best,
michael

**Comment by JJ** [comment]
That site is down, and it wasn't brought up. I'll see what we can do about
it.

**Comment by uzluisf** [comment]
In the meantime, you might want to use https://github.com/perl6/specs.

**Comment by JJ** [comment]
Depends on perl6/problem-solving#68. It's a work in progress.

**Comment by JJ** [comment]
This finally came back; I'm closing.
