### ISSUE TITLE
/language/unicode_entry (Entering Unicode Characters) needs to explain XCompose

### ISSUE THREAD

**Issue by daxim** [perl6/doc#286]
[The Compose key has a much better usability](https://superuser.com/a/78724) than any other method mentioned on that page because it is largely mnemonic (hex codes are not) and XCompose not an application-specific solution. So that should definitely be explained first, and the various applications later. You can use my SU post or parts of it without needing to follow the SU terms of copying (cc by-sa 3.0). I think the default key for Compose is <kbd>RShift</kbd>+<kbd>RCtrl</kbd>.

**Comment by zoffixznet** [comment]
:+1:

**Comment by bluebear94** [comment]
:+1: too
