### ISSUE TITLE
infix Z doc has ambiguous description

### ISSUE THREAD

**Issue by Antisunny** [perl6/doc#2862]
## The problem

some words in the description is ambiguous.

[https://docs.perl6.org/routine/Z](https://docs.perl6.org/routine/Z)

> The Zip operator interleaves the lists passed to Z like a zipper, stopping as soon as **the first input list** is exhausted.

```perl6
listA Z listB
```
**the first input list** indicates `listA`? Or one of the list which is shorter?

## Suggestions

should be put as 

> stopping as soon as **the shortest input list** is exhausted.

OR

> stopping as soon as **one of the input list** is exhausted.

**Comment by Altai-man** [comment]
A nice catch! The behavior is "the shortest input list", e.g.:
```
➜  ~ perl6 -e 'say (1,2,3) Z (4,5,6,7)'
((1 4) (2 5) (3 6))
```

Would you mind making a PR? I can patch it otherwise.

**Comment by JJ** [comment]
Well, this could be read as "the *first* to be exhausted". It does not necessarily mean the first to appear. Of course, anything that makes it less ambiguous is fine.

**Comment by chloekek** [comment]
The documentation for the zip metaoperator says:

> If one of the operands runs out of elements prematurely, the zip operator will stop.
