### ISSUE TITLE
Character classes also capture

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2873]
## The problem

[Predefined character classes](https://docs.perl6.org/language/regexes#Predefined_character_classes) not only match, they also capture, putting a list of matched characters into a list

## Suggestions

Please mention that in the documentation

**Comment by jnthn** [comment]
They may be predefined, but there's nothing special about them compared to any other rule we might call. It's the calling of them with the `<alpha>` syntax that is asking for them to be captured. Call them as, for example, `<.alpha>`, and they won't be captured.

So, I'd explain this as saying that they're just built-in rules, and so subject to the usual capturing rules.
