### ISSUE TITLE
robots.txt file no longer needed

### ISSUE THREAD

**Issue by antoniogamiz** [perl6/doc#2880]
## The problem

`robots.txt` file is no longer used. By @moritz: we used to store build logs for docs.perl6.org on that site itself, but that isn't the case right now.

## Suggestions

Delete it.

**Comment by AlexDaniel** [comment]
Where are the logs now?

**Comment by JJ** [comment]
They are in the crashed hard drive. I don't think they're copied to
userspace in the new hosting. I'll have to check.
