### ISSUE TITLE
with also topicalizes on the condition

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2882]
## The problem

In [this page](https://docs.perl6.org/language/control#with,_orwith,_without) it says that with is like if, "but it topicalizes on the condition". if also topicalizes.

## Suggestions

A simple rewording will probably be enough.

**Comment by jnthn** [comment]
I think the documentation is correct already; `if` does not topicalize:

```
$ perl6 -e '$_ = 42; if 5 { .say }'
42
$ perl6 -e '$_ = 42; with 5 { .say }'
5
```

**Comment by JJ** [comment]
Ah OK. Will close then

**Comment by JJ** [comment]
What was in my mind is that if can be followed by a pointy block same as given and wit. But that's not it. Closing
