### ISSUE TITLE
Fix to `with` 404 introduced new issues into control.pod6

### ISSUE THREAD

**Issue by treyharris** [perl6/doc#2885]
## The problem
#2881 was closed with 996dd01425f6a885f1dd733dda5fb85de16cec00. However, it introduced at least two new issues I’ll illustrate with before and after screenshots, and highlights a third issue that wasn’t actually changed by the commit:

  1. The `with orwith without` headline has changed from mono:
    ![IMG_0755](https://user-images.githubusercontent.com/97895/60728907-73584000-9f0f-11e9-8ff6-9efc6a952a93.jpeg)
    to sans-serif:
    ![IMG_0757](https://user-images.githubusercontent.com/97895/60728921-7fdc9880-9f0f-11e9-83a6-4f1f3dcfdbd5.jpeg)
    which makes it mismatched with the other headings at the same level—and this is repeated in the headlines as can be seen below. It also has lost commas, which is probably a clue to:
  1. There’s an odd set of two commas before the heading:
    ![IMG_0758](https://user-images.githubusercontent.com/97895/60728991-a6023880-9f0f-11e9-9e77-b50b6105dc3b.jpeg)
    previously seen _inside the heading_ itself:
    ![IMG_0756](https://user-images.githubusercontent.com/97895/60732529-43616a80-9f18-11e9-82fd-ef97367f7745.jpeg)
    I can find no motivation for them in the text, as it goes directly from
  ```diff
  diff --git a/doc/Language/control.pod6 b/doc/Language/control.pod6
  index 947fa7ad5..546317422 100644
  --- a/doc/Language/control.pod6
  +++ b/doc/Language/control.pod6
  @@ -357,7 +357,8 @@ unless 0 { "0 is false".say }  ; # says "0 is false"
       my $c = 0; say (1, (unless 0 { $c += 42; 2; }), 3, $c); # says "(1 2 3 42)"
       my $d = 0; say (1, (unless 1 { $d += 42; 2; }), 3, $d); # says "(1 3 0)"

  -=head2 X<C<with>|control flow, with>, X<C<orwith>|control flow, orwith>, X<C<without>|control flow, without>
  +X<|control flow,with>, X<|control flow,orwith>, X<|control flow,without>
  +=head2 X<with orwith without>

   The C<with> statement is like C<if>, but tests for definedness rather than
   truth, and it topicalizes on the condition, much like C<given>:
  ```
  and, if we look at the difference from before the last edit to this section made by me in 1c57f0d08 (where I attempted to fix the mono/sans formatting issue) and now, we see:
  ```diff
    diff --git a/doc/Language/control.pod6 b/doc/Language/control.pod6
  index 29f0dd959..546317422 100644
  --- a/doc/Language/control.pod6
  +++ b/doc/Language/control.pod6
  @@ -357,10 +357,11 @@ unless 0 { "0 is false".say }  ; # says "0 is false"
       my $c = 0; say (1, (unless 0 { $c += 42; 2; }), 3, $c); # says "(1 2 3 42)"
       my $d = 0; say (1, (unless 1 { $d += 42; 2; }), 3, $d); # says "(1 3 0)"

  -=head2 X<with|control flow, with>, X<orwith|control flow, orwith>, X<without|control flow, without>
  +X<|control flow,with>, X<|control flow,orwith>, X<|control flow,without>
  +=head2 X<with orwith without>

  -The C<with> statement is like C<if> but tests for definedness rather than
  -truth.  In addition, it topicalizes on the condition, much like C<given>:
  +The C<with> statement is like C<if>, but tests for definedness rather than
  +truth, and it topicalizes on the condition, much like C<given>:

       with "abc".index("a") { .say }      # prints 0

  ```

  so, it’s some htmlify artifact, I think. @JJ -- is there a way to combine these somehow so that we get the indexing, the code typeface, and no vestigial commas?

  3. Finally, not introduced by this commit but put in the spotlight by it: are the heading levels correct, and if so, is the punctuation correctly parallel?

  ![IMG_0757](https://user-images.githubusercontent.com/97895/60729454-c088e180-9f10-11e9-805f-a93cbc91764e.jpeg)
  `else/elsif` (with a slash) is below `if`, as a constituent part; `unless` also, presumably because `unless` is the logical negation of `if`; but `with orwith without` is also headed under `if`, but without slashes.

## Suggestions

I don't know how to fix the typeface and indexing issue and the strange commas--I'm not clear enough on how htmlify works.

As for structuring, I can see an argument for this three ways:
      - `with`, `orwith`, and `without` are variants of `if` dealing with definedness rather than with truth, just as `unless` is a variant, so the current structure is correct.
    - `with` is not in any way subsequent to `if` but rather a sibling occupying the same spot in the syntax but with different semantics, so should stand at the same level as `if`, just as `for` and `while` do.
    - The entire section after `if` needs a rework. The connection is even stronger between `if` and `with` than between `if` and ‘unless’, since `with...elsif..orwith..else` and `if...orwith...elsif...else` are perfectly allowable. So, to the contrary, there should be _two sections_ where the single `if` currently stands: `if/with...elsif/orwith...else` and `unless/without`, since they occupy the same niches in the language syntax.

I tend to the last option; if others agree, I’m happy to rework the entire `if` section to consolidate it into `if/with...elsif/orwith...else` and `unless/without`—but it appears, from the issue #2881 motivating the commit that this current issue is addressing, that changes here can have ramifications of spooky action at a distance, so I’d appreciate some guidance as to how to do so without breaking the index again as my last commit apparently did with what I thought was a fairly prosaic formatting "fix":
```diff
diff --git a/doc/Language/control.pod6 b/doc/Language/control.pod6
index 29f0dd959..bf4556a14 100644
--- a/doc/Language/control.pod6
+++ b/doc/Language/control.pod6
@@ -357,10 +357,10 @@ unless 0 { "0 is false".say }  ; # says "0 is false"
     my $c = 0; say (1, (unless 0 { $c += 42; 2; }), 3, $c); # says "(1 2 3 42)"
     my $d = 0; say (1, (unless 1 { $d += 42; 2; }), 3, $d); # says "(1 3 0)"

-=head2 X<with|control flow, with>, X<orwith|control flow, orwith>, X<without|control flow, without>
+=head2 X<C<with>|control flow, with>, X<C<orwith>|control flow, orwith>, X<C<without>|control flow, without>

-The C<with> statement is like C<if> but tests for definedness rather than
-truth.  In addition, it topicalizes on the condition, much like C<given>:
+The C<with> statement is like C<if>, but tests for definedness rather than
+truth, and it topicalizes on the condition, much like C<given>:

     with "abc".index("a") { .say }      # prints 0

```

I'm not sure how to tease apart these issues, but this probably should be split into two or three issues once it's articulated here how the indexing broke:
1. The mono/sans question
2. The document structure (which is dependent on the mono/sans issue fix)

and then those two issues can fix each of those things, hopefully without re-breaking indexing.

**Comment by JJ** [comment]
Yep, there should be a way. The problem is that indexing is so arcane I'm afraid of making some changes and making it stop working. Thanks for the detailed report.
