### ISSUE TITLE
FAQ: incorrect item "Floating point math without precision loss because of Rats"

### ISSUE THREAD

**Issue by vinc17fr** [perl6/doc#291]
The FAQ contains: *Floating point math without precision loss because of Rats (rational numbers).*

First, if these are rational numbers, this is no longer floating-point math. Moreover "without precision loss" is not true because:
* Rats also have a limited precision: they are converted to Num as soon as the denominator does not fit on 64 bits.
* Except for the 4 arithmetic operations (and the integer power), the result of a math function will not be a rational number in general.

Perhaps this could be changed to: "Simple numeric computation without precision loss because of Rats (rational numbers)."

**Comment by zoffixznet** [comment]
:+1: 

Would you be able to submit a PR with the change?

**Comment by vinc17fr** [comment]
That's https://github.com/perl6/doc/pull/293.

**Comment by jonathanstowe** [comment]
If that commit is enough I'll close this.

**Comment by AlexDaniel** [comment]
Any other places where corrections are required?
