### ISSUE TITLE
Eliminate variable elements from page generation

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2915]
## The problem

Every page includes the commit with which it was generated. This is not the last commit that changed the page, but the last commit that changed anything. This means that every time you change anything, every single page changes. This breaks havoc on caches, and does not really help with hosting pages in a repo as we do with perl6docs.github.io

## Suggestions

Many options
* Just eliminate it. It's not really an information that the user needs to know, and developers can find out in many different ways.
* Put the information in a JSON file somewhere, add a link from the page.
* Put the information in a JSON file, use JS magic so that the aspect of the page does not really change (but the source code stays the same).

**Comment by antoniogamiz** [comment]
I think we could simply eliminate it. I am not sure about if it's useful or even someone actually uses it.

**Comment by Altai-man** [comment]
>This is not the last commit that changed the page, but the last commit that changed anything.

+1 for eliminating.

I suspect that `Generated on 2019-07-23T08:53:05Z [Debug: off]` line brings us the same outcome and I wonder what's its worth.
