### ISSUE TITLE
There seems to be some kind of error in the signatures page

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2921]
## The problem

There's a lonely `-->` [here](https://docs.perl6.org/type/Signature#Constraining_return_types)

## Suggestions

Check source and intent, and fix it.

**Comment by Altai-man** [comment]
It is not an error, it is a proper subsection header for explaining `-->` return form. Below `returns` and `of` are explained.
I think it can be rewritten into, maybe, `Return syntax: -->`, then below should be `Return syntax: returns` etc, to be clearer, but this is not a bug.
