### ISSUE TITLE
X::Dynamic::NotFound not documented

### ISSUE THREAD

**Issue by antoniogamiz** [perl6/doc#2928]
X::Dynamic::NotFound is also undocumented, mentioned [here](https://github.com/perl6/doc/blob/d32bc48de2fc021cf5cfc90261c5d7e1c139d373/doc/Type/Variable.pod6#L84).

**Comment by antoniogamiz** [comment]
X::Dynamic::NotFound is also undocumented, mentioned [here](https://github.com/perl6/doc/blob/d32bc48de2fc021cf5cfc90261c5d7e1c139d373/doc/Type/Variable.pod6#L84).

**Comment by JJ** [comment]
Dups #1834

**Comment by antoniogamiz** [comment]
I have changed the issue to match the second missing class, so now it's not a duplicate.
