### ISSUE TITLE
+^ is not bitwise XOR

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2939]
## The problem

[This](https://docs.perl6.org/language/5to6-perlop#Bitwise_Or_and_Exclusive_Or) says bitwise XOR is equivalent to +^. However, that changes `Bool` to `Int`

## Suggestions

Find an alternative.

**Comment by lichtkind** [comment]
I think the issue stems from the shortcut property of or and and. They return one of both values. Which one is decided on how the two num vals eval to Bool and what the bool logic of the op demands. for consistance reasons i would demand the same here even i was around many years ago when larry talked about xor being eqv to +^ , which has its own issues like dealing with reals.
