### ISSUE TITLE
Add a FAQ about "Why is Perl 6 called Perl?"

### ISSUE THREAD

**Issue by coke** [perl6/doc#294]
Answer is basically Rule number 1; but a nod to the discussions we've had over the last 15 years and a summary involving a "language family" would probably be helpful.

(now that we've cut 6.c, we're getting a fresh batch of people who are re-asking this question)

**Comment by zoffixznet** [comment]
Tagging with Hacktoberfest.... What's "Rule number 1"?

**Comment by AlexDaniel** [comment]
> What's "Rule number 1"?

http://perldoc.perl.org/5.12.4/perlhack.html#DESCRIPTION

> 1. Larry is always by definition right about how Perl should behave. This means he has final veto power on the core functionality.
