### ISSUE TITLE
Build Error: Colon pair value 'my @letters = <a b c d e f>;' too complex to use in name

### ISSUE THREAD

**Issue by Xliff** [perl6/doc#2944]
## The problem

Obtaining this error when running `htmlify.p6`:

```
An operation first awaited:
  in sub process-pod-dir at ./htmlify.p6 line 307
  in sub MAIN at ./htmlify.p6 line 204
  in block <unit> at ./htmlify.p6 line 171

Died with the exception:
    ===SORRY!=== Error while compiling /home/cbwood/Other Projects/p6-doc/build/Language/077-subscripts.pod6
    Colon pair value 'my @letters = <a b c d e f>;' too complex to use in name
    at /home/cbwood/Other Projects/p6-doc/build/Language/077-subscripts.pod6:299
    ------>  :preamble<my @letters = <a b c d e f>;>⏏<EOL>

      in sub extract-pod at /home/cbwood/Other Projects/p6-doc/lib/Pod/Convenience.pm6 (Pod::Convenience) line 127
      in block  at ./htmlify.p6 line 302
```

**Comment by tbrowder** [comment]
Can you show or point to the file containing that problem line (077-subscripts.pod6)? 

If that is a pod configuration entry it looks like it's invalid. In any case it looks like some characters might need escaping or use a different quoting bracket chars.

**Comment by JJ** [comment]
Is this something you have added to the docs? @tbrowder, OTOH, it should be valid; it's a preamble to an example, which in principle should contain arbitrary code.

**Comment by tbrowder** [comment]
Sorry, I just realized where the file name numerical prefix came from...duh...I'll look in the right place!

**Comment by tbrowder** [comment]
Where is a ":preamble" syntax defined? It looks like a configuration entry for a pod delimited block, and it may need a different quoting method to protect its value through the pod parsing.

**Comment by JJ** [comment]
El lun., 12 ago. 2019 a las 12:50, Tom Browder (<notifications@github.com>)
escribió:

> Where is a ":preamble" syntax defined? It looks like a configuration entry
> for a pod delimited block, and it may need a different quoting method to
> protect its value through the pod parsing.
>
> That's a good question. It's actually a configuration entry, as you say,
except that what's quoted is going to be interpreted as code by the example
compilation tests.

**Comment by tbrowder** [comment]
I tried my version in a plain script as following got no error:

    =begin code :preamble('my @letters = <a b>')
      some code
    = end code

**Comment by tbrowder** [comment]
I suggest this issue be closed.

**Comment by tbrowder** [comment]
The pod as shown is invalid. The msg is confusing, I agree, but I'm not sure it's fixable. However, I have entered it as a new Rakudo issue:  #3121

I am closing this issue.
