### ISSUE TITLE
Sort search categories by the number of found items

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#296]
For example, try searching for `X`. It will bring a long list of classes, but you are probably looking for an operator.

Perhaps an easy way to solve this is to sort categories by the number of found items. In other words, it should pack as many categories as possible on the top of the screen.

**Comment by zoffixznet** [comment]
#247 is related  (show exact matches first)

**Comment by coke** [comment]
-1 to this, I prefer #247.

**Comment by AlexDaniel** [comment]
It is not a replacement for #247. It is just another criteria to sort the results. I don't really see why somebody would -1 this (does it make something worse?).

**Comment by coke** [comment]
I don't want the category order to change with every search.

My preferred solution for finding the best result in the (very recently added) categorized results would be:

* #247
* List no more than X results in each category.
* List no more than Y total results. (I've seen systems where Y is based on the screen real estate available so it's never scrolling)
* Provide a search/contents page where all the items can be viewed, dynamically limited to the search criteria; Should be linked to in the menu.
* Provide a "See All" at the bottom of each category (where needed) which links to the search/contents page, limiting the search. Or perhaps a single see all at the bottom.

**Comment by zoffixznet** [comment]
> Provide a search/contents page where all the items can be viewed, dynamically limited to the search criteria; Should be linked to in the menu.

A definite +1 to that point. The real problem is the site isn't dynamic :(

**Comment by coke** [comment]
Following through on my comment of Dec 30, 2015, rejecting ticket.
