### ISSUE TITLE
"meta" is used inconsistently

### ISSUE THREAD

**Issue by Kaiepi** [perl6/doc#2966]
## The problem
There are three different ways nouns described with "meta" are written in the docs:
- meta$noun
- meta-$noun
- meta $noun

## Suggestions
There should only be one way, and there should be tests that ensure that.

**Comment by JJ** [comment]
We can use a test we already have for that. Thanks for the report.

**Comment by coke** [comment]
Looks like this test is now failing on one of the instances of "meta".

**Comment by JJ** [comment]
@coke the new regex includes the test that is commented out. And yes, there are IIRC 36 tests that are failing. I didn't have time to check if they are actually errors and fix them.

**Comment by JJ** [comment]
Well, it's an author test...  But allright, I'll do that. Thanks for the
recommendation.

**Comment by JJ** [comment]
This line:

    __PACKAGE__->meta->make_immutable;

is a false positive in faq.pod6.

Not sure how to handle this. Ideally, we should eliminate code from these checks.

**Comment by coke** [comment]
We shouldn't eliminate all code, because code includes comments and user defined names. I can work on updating the regex here.
