### ISSUE TITLE
Searching for methods with a "." prefix returns no results

### ISSUE THREAD

**Issue by yurivish** [perl6/doc#297]
Searches on http://docs.perl6.org/ for any method on with a string having a "." prefix (e.g. ".sort", ".kv") returns no results right now.

**Comment by 4d47** [comment]
I think this is correct since method name is really `sort` (without dot operator).
Also searching for methods starting with dot works (`...`, `.=`, etc) works.

**Comment by pdl** [comment]
See #155

**Comment by zoffixznet** [comment]
Yes, this falls under the #155 issue (and this particular search terms are blocked by Apache directory index). I'm going to close this.
