### ISSUE TITLE
Formatting error in the overview of perl 5 to perl 6 migration guide

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2970]
## The problem

There seems to be a problem [here](https://doc.perl6.org/language/5to6-overview) with formatting

## Suggestions

Check it out and fix it.

**Comment by antoniogamiz** [comment]
This is because `comments` is used instead of `comment` => https://github.com/perl6/doc/blob/735a673f87bba83861bcf5666da86883662eab6d/doc/Language/5to6-overview.pod6#L44
It also happens in others files.
