### ISSUE TITLE
getaddrinfo() return value description inverted

### ISSUE THREAD

**Issue by markldevine** [perl6/doc#2971]
## The problem
https://docs.perl6.org/language/nativecall#Short_tutorial_on_calling_a_C_function
4th paragraph reads:

    "The function returns a response code 0 = error, 1 = success."

My man page for getaddrinfo(3) reads as follows:

    "RETURN VALUE
           getaddrinfo() returns 0 if it succeeds, ..."

## Suggestions
Should read:

"The function returns a response code 0 = success, non-zero = error."

**Comment by JJ** [comment]
Thanks! Will check it out.
