### ISSUE TITLE
Change metadata of Type and Language files when needed 

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2973]
## The problem

In the next version, metadata will determine the kind of processing some files undergo. For instance, classes will extract the URL from the class name. At any rate `kind` and `subkind` will be used to index them, so we need to revise that metadata to avoid problems in indexing and file generation.

## Suggestions

List here files for revision.
* [ ] `independent-routines`: it's not a class, let's list it as `other`

**Comment by antoniogamiz** [comment]
This is easily fixed changing the value of `kind` to 'Language'. Headers will be equally indexed independently of `kind`.
