### ISSUE TITLE
Missing types in type-graph.txt

### ISSUE THREAD

**Issue by antoniogamiz** [perl6/doc#2976]
## The problem

The following types are missing from type-graph.txt:

- [ ] class CompUnit
- [ ] role PredictiveIterator
- [ ] enum Endian 
- [ ] class Telemetry (you need to use `use Telemetry` to instantiate it) 
- [ ] class Telemetry::Period  (you need to use `use Telemetry` to instantiate it) 
- [ ] class Telemetry::Sampler  (you need to use `use Telemetry` to instantiate it) 
- [ ] role Distribution
- [ ] class Distribution::Locally
- [ ] class Distribution::Hash
- [ ] class Distribution::Path
- [ ] class Perl
- [ ] class Collation
- [ ] class Encoding
- [ ] class Encoding::Registry
- [ ] class Compiler 
- [ ] class UInt (it's a subset)
- [ ] class Cursor 
- [ ] class Pod::Defn
- [ ] class CX::Done
- [ ] class CX::Return
- [ ] class CX::Emit
- [ ] class Routine::WrapHandle
- [ ] class Lock::Async
- [ ] class Telemetry::Instrument::ThreadPool
- [ ] class Telemetry::Instrument::Thread
- [ ] class Telemetry::Instrument::Usage
- [ ] class X::Attribute::Required
- [ ] X::Scheduler::CueInNaNSeconds
- [x] X::Proc::Async::BindOrUse

## Suggestions

Add them.

Script used to detect them: 

~~~perl6
use Perl6::Documentable::Utils::IO;
use Pod::To::Cached;
use Terminal::ANSIColor;
use Pod::Utilities;
use URI::Escape;
use Perl6::Documentable;
use Cro::HTTP::Client;
use Perl6::TypeGraph;

my $pod-cache = Pod::To::Cached.new(:source("doc"), :path(".cache-doc"), :verbose);
$pod-cache.update-cache;

# load pods using a cache
sub load($path) {
    my $new-path = $path.subst(/doc\//, "")
                    .subst(/\.pod6/, "").lc;
    $pod-cache.pod( $new-path )[0];
}


# get all pod filenames
my @pod-sources;
@pod-sources.append: get-pod-names(:topdir("doc"), :dir("Type"));

my $tg = Perl6::TypeGraph.new-from-file("type-graph.txt");

for @pod-sources -> $type {
    say $type.key unless $tg.types{$type.key}:exists;
}
~~~

Related to #2945 .

**Comment by JJ** [comment]
This extends #2302
