### ISSUE TITLE
New Documentable build broken

### ISSUE THREAD

**Issue by coke** [perl6/doc#2998]
3 points:

1) can no longer use 'make' to build the docs; after looking ...

2) I followed the directions in the README, I don't have documentable installed; so I tried to add it to the META6.json and then install it with ```zef install --deps-only .```, but:

3) Can't install it because one of the downstream deps fails. Opened a ticket in both Documentable and Pod::To::Cached where the actual failure is.

https://github.com/perl6/Documentable/issues/29

**Comment by JJ** [comment]
1. Make is no longer used to build the docs, documentable is.
2. Will check that out.
3. Thanks!

**Comment by coke** [comment]
Make was just a wrapper for htmlify before. My suggestion would be to do
the same with the new script.

**Comment by JJ** [comment]
There's a difference, though; before, htmlify.p6 was in the same repository; you need to install documentable now. Also, before the only option was make html, and now there's a different command if you want to generate the initial cache and all the html files or if you just want to update what's changed.
Will see the best way to do this, though...

**Comment by coke** [comment]
Once the META6.json deps are updated properly, doesn't matter that the script is coming from somewhere else. the same make command can be used to do the new build, and a new "update" task could be added for the other option.

**Comment by JJ** [comment]
Well, I'm kind of wary of adding Documentable to the dependencies for the
time being, and maybe in the future. All tools for building the
documentation are going to be spun off eventually, with dependencies on
this module and documentable.

Main point is that documentation is documentation. Tooling should be
developed, and used, from somewhere else. Spinning off documentable is the
first step, the roadmap is open for comments in #2996

**Comment by JJ** [comment]
Documentable now has been reported to work by the OP and others. so I'm closing this issue.
