### ISSUE TITLE
Document passing text argument to sort/cmp

### ISSUE THREAD

**Issue by hythm7** [perl6/doc#3026]
## The problem
Please document how does `cmp` works on text. does it split every word to chars then compares each char?

Please also see: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-18#l91

EDIT: s/sort/cmp

**Comment by AlexDaniel** [comment]
The docs for `sort` already say “Sorts iterables with cmp”, so as far as I'm concerned the docs for `sort` are OK. It's `cmp` that is missing documentation on how it works for strings.
