### ISSUE TITLE
need info on using Build.pm6 with ecosystem module installations

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#3028]
## The problem

I can find nothing in the docs about Build.pm6 (or Build.pm).

## Suggestions

Add info at an appropriate place in module construction and packaging. I am using it successfully now (thanks to @zostay) and can take an initial stab at it later.

**Comment by JJ** [comment]
OK, we'll do what we can, but last time I checked I think it was something that was specific to zef.

**Comment by tbrowder** [comment]
I guess it is, but, since there is no other installer on the horizon, this may be a special case.  I'll see if I can ask Nick his opinion. Note the Build.pm6 option  works well and the "hooks" capability is non-existent as far as I can tell.

**Comment by tbrowder** [comment]
I didn't ask Nick. I just inserted an innocuous reference to the file. Closed with 8fe97a4.
