### ISSUE TITLE
Generated from PODPATH at SOURCEURL

### ISSUE THREAD

**Issue by taboege** [perl6/doc#3031]
## The problem

On https://docs.perl6.org/syntax/qqx in the footer, it says

> Generated from [PODPATH](https://docs.perl6.org/syntax/SOURCEURL).

linking to https://docs.perl6.org/syntax/SOURCEURL. Apparently some substitutions fail?

**Comment by JJ** [comment]
Thanks for the report. We'll check it out immediately.

**Comment by JJ** [comment]
This has been fixed in the [test site](http://docs.p6c.org/)
