### ISSUE TITLE
Clarify use of the :delete adverb for method .trans

### ISSUE THREAD

**Issue by frithnanth** [perl6/doc#3057]
## The problem

This [page](https://docs.perl6.org/type/Str#method_trans) provides only one example for `.trans` with `:delete`:

```perl6
"a123b123c".trans('23' => '', :delete);                       # RESULT: «a1b1c»
```

I think it's not sufficiently clear what the `:delete` adverb does, since
```perl6
"a123b123c".trans('23' => '')
```
produces the same output.

## Suggestions

Two examples instead of just one would clarify the use of `:delete`:

```perl6
"a123b123c".trans('23' => '4');                                # RESULT: «a144b144c»
"a123b123c".trans('23' => '4', :delete);                       # RESULT: «a14b14c»
```

**Comment by JJ** [comment]
Thanks! We'll handle it as soon as possible.
