### ISSUE TITLE
Error in perl6 grammar documentation (online)

### ISSUE THREAD

**Issue by germanrodriguezherrera** [perl6/doc#3085]
## The problem

In: https://docs.perl6.org/language/grammars
Section: "ws"

There is an example that says that whitespace can be captured, but must be done explicitly:

> And even capture it, but you need to use it explicitly:
> 
> grammar Foo { rule TOP {\d <ws> \d} };
> my $parsed = Foo.parse: "3 3";
> say $parsed<ws>; # OUTPUT: «｢｣␤» 

However, as the example shows, nothing is captured because it is using "rule" instead of "token". The example is illustrative if one tries it out because one might have the impression that if one uses <ws> explicitly within a "rule", then, the default behavior (the implicit <.ws>'s) would we overriden. But that's clearly not the case. The space is not being captured. The actual behavior is to my opinion the more consistent and the one that needs cognitive effort. If I wanted to capture whitespace I should have started with a "token" rule.

Hope it helps,
Cheers.

**Comment by JJ** [comment]
It sure helps. Thanks a lot for your report, we'll try to fix it as soon as possible.

**Comment by germanrodriguezherrera** [comment]
Noticed that commit c0e9876265 "Adds more examples to the definition of ws" (2019-06-01) kind of corrected the issue but left "rule" when adding <ws> rather than changing it to "token", and, as rules have an implicit <.ws> it wasn't still captured.
