### ISSUE TITLE
In the docs, it says '\n\r' instead of '\r\n'

### ISSUE THREAD

**Issue by germanrodriguezherrera** [perl6/doc#3086]
## The problem

In: https://docs.perl6.org/routine/encode

The following sentence, where it says:

> If :translate-nl is set to True, it will translate newlines from \n to \n\r,

it should say:

"If :translate-nl is set to True, it will translate newlines from \n to \r\n,"

\n\r makes no sense, so that's a clear mistake in the docs.

Cheers,
German

**Comment by AlexDaniel** [comment]
Yes, of course. :) You can submit a PR to fix it.
