### ISSUE TITLE
Documenting features that are experimental in Rakudo

### ISSUE THREAD

**Issue by sylvarant** [perl6/doc#317]
Recently I had one of my perl packages fail due to the fact that the `pack` subroutine and `unpack` method had become experimental requiring a declaration of:
```perl6
use experimental :pack
```
in programs that use them.
Should this be mentioned in doc/Type/Blob.pod? 
Or do we not note the issues of rakudo in these docs ?

**Comment by jnthn** [comment]
Things being experimental isn't a Rakudo issue, but rather a deliberate
language design decision. We can document experimental things but they
should be very clearly marked as such, so people know they're taking a risk
using them.

**Comment by moritz** [comment]
Doc patches that mark those features as experimental would be very welcome.

**Comment by jonathanstowe** [comment]
I couldn't find any other example of "experimental" so I just added some text.

If there were to be more then maybe some pod notation could be added to automatically do it.
