### ISSUE TITLE
Class Str method trans

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#319]
Documentation doesn't show the declaration of method ``` trans```

Also there is a typo ```:complemet``` in the text

**Comment by zoffixznet** [comment]
Are you able to submit a PR fixing this?

**Comment by MARTIMM** [comment]
I can change the typo of course but where can I find the declaration of the method?

**Comment by MARTIMM** [comment]
Found something in rakudo/src/core/Str.pm, is this the correct one?

**Comment by zoffixznet** [comment]
Yes, it'd likely be in rakudo/src/core/Str.pm, I also see i tmentioned in [S32 spec](http://design.perl6.org/S32/Str.html).

And yes, please submit the modifications to the doc as a PR.

**Comment by MARTIMM** [comment]
You can find the changes in PR MARTIMM-patch-4 branch

**Comment by zoffixznet** [comment]
:+1: thanks a lot!

**Comment by MARTIMM** [comment]
Sorry to botter you with it again. I'm not sure about the proto type because it shows nqp code. I'd better change all of it with the one you pointed to from s32.
```
    method trans(Str $self:
                 *@changes where { all(@changes) ~~ Pair },
                 *%adverbs
                 --> Str) is export;

```
Do you agree? If so I'll change it for you.

**Comment by zoffixznet** [comment]
No, what you have right now is fine. The spec's likely outdated.

**Comment by MARTIMM** [comment]
ok
