### ISSUE TITLE
Mention smartquotes

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#332]
http://doc.perl6.org/language/unicode_entry#Unicode_characters_useful_in_Perl_6

“Unicode characters useful in Perl 6” – well, smartquotes are useful but are not listed yet.

`‘’`, `“”`, `｢｣` – these are the basic ones, but there are other ways to write it:
- `say ”Whoa!“`
- `say „This works too!”`
- `say „There are just too many ways“`
- See [Wikipedia](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table_for_all_languages) for a bigger list.

Some things to note:
- You can nest them: `say “here: “no problem” at all!”`
- It turns out that it is very useful in shell: `perl6 -e 'say ‘hello world’'` (that is, you can just copy some piece of code and not worry about the quotes)

**Comment by titsuki** [comment]
Fixed by #996
