### ISSUE TITLE
htmlify.p6 --help should show options for MAIN

### ISSUE THREAD

**Issue by coke** [perl6/doc#342]
Right now, running htmlify.p6 with --help or -? or any unrecognized option just runs with the default parameters.

**Comment by Altai-man** [comment]
Latest rakudo and htmlify.p6:
```
➜  doc git:(master) ✗ perl6 htmlify.p6 --help
Initializing ...
Usage:
  htmlify.p6 [--typegraph] [--sparse=<Int>] [--disambiguation] [--search-file] [--no-highlight] [--no-inline-python] [--parallel=<Int>] 
➜  doc git:(master) ✗ perl6 htmlify.p6 -\?
Initializing ...
Usage:
  htmlify.p6 [--typegraph] [--sparse=<Int>] [--disambiguation] [--search-file] [--no-highlight] [--no-inline-python] [--parallel=<Int>] 
➜  doc git:(master) ✗ 
```
I doubt it is necessary to print "Initializing ..." string here, we can just print it in MAIN, not in BEGIN block. But the output seems good. It can be closed?

**Comment by Altai-man** [comment]
Since this issue is pretty old already and was resolved a long time ago(see previous comment), I suppose, it can be closed.
