### ISSUE TITLE
problem when searching for ?

### ISSUE THREAD

**Issue by sergot** [perl6/doc#344]
13:56 < sergot> http://doc.perl6.org/routine/.%3F
13:57 < sergot> there is a problem when searching for ? and clicking "Postfix .?"
13:57 < [Coke]> sergot: can you open a ticket on github.com/perl6/doc/issues ?

**Comment by zoffixznet** [comment]
Thank you. This is one more case of the #155 , so I'll close this one (it'll be referenced in 155)
