### ISSUE TITLE
Missing Methods from Any-iterable-methods.pm

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#345]
It seems methods provided by the [Any-iterable-methods.pm](https://github.com/rakudo/rakudo/blob/02588190492349fabde00c5a15b873ea61a9333e/src/core/Any-iterable-methods.pm#L696) aren't showing up in the docs. The [docs for Range type](http://docs.perl6.org/type/Range) do not have any mention of the `.first` method or `.squish`, even though the class does have them available. The same applies to [Seq](http://docs.perl6.org/type/Seq), and I'm assuming any class that inherits from Any.

**Comment by JJ** [comment]
Wow, this is positively ancient.

**Comment by JJ** [comment]
I'm assuming this has got to do with the way the website is generated more than with the documentation itself, right? Could it have something to do with the fact that it's declared via `augment`?

**Comment by zoffixznet** [comment]
This issue is probably outdated. I see both `.first` and `.squish` it mentions *are* already [documented](https://docs.perl6.org/type/Any#method_squish) on the `Any` docs.

> Could it have something to do with the fact that it's declared via augment?

Maybe only because someone might've just looked at `Any.pm` in Rakudo's source to document the methods (probably not a great idea, as we need to only document specced features, not what some implementation just happens to have implemented). In general, there's no relation between the docs and how a particular implementation chooses to implement the spec.
