### ISSUE TITLE
Two different links to glossary

### ISSUE THREAD

**Issue by uvtc** [perl6/doc#353]
The faq links to one glossary: https://doc.perl6.org/language/faq#Is_there_a_glossary_of_Perl_6_related_terms%3F
but https://doc.perl6.org/language.html links to a different glossary: https://doc.perl6.org/language/glossary .

**Comment by zoffixznet** [comment]
The link should be to https://doc.perl6.org/language/glossary that is a new page that was recently added. Would you submit a PR for that?
