### ISSUE TITLE
Need docs for import

### ISSUE THREAD

**Issue by coke** [perl6/doc#359]
Pointed out by brian d foy at

https://stackoverflow.com/questions/34688662/how-can-i-declare-and-use-a-perl-6-module-in-the-same-file-as-the-program

**Comment by JJ** [comment]
As anwered by Cristoph, it's actually documented now here https://docs.perl6.org/language/modules.html#Loading_and_Basic_Importing

**Comment by JJ** [comment]
So maybe reopen it?
