### ISSUE TITLE
Add --file=operators.pod or at least --no-images

### ISSUE THREAD

**Issue by drforr** [perl6/doc#362]
Building the document tree takes quite a while on my poor little VM. It'd be nice to have a way to just rerender the file I'm working on. I'll see about doing this myself later.

**Comment by AlexDaniel** [comment]
Any progress?

**Comment by Altai-man** [comment]
Without images generation performance gain on my machine is about 1-3 seconds(1 minute for all generation process, so it's about 4-5% of the increase). I think that it doesn't make much sense to remove them anyway.
We'd better think about how can we implement partial build without any flags, such as re-generation only for files that were changed, I think. But it's already in TODO list.
Should this be closed then?

**Comment by AlexDaniel** [comment]
Also see https://github.com/perl6/doc/pull/661#issuecomment-230151179. Parallelization can speed up the build several times.

**Comment by AlexDaniel** [comment]
OK, I think that we can close this. Parallelization, caching, and general perl 6 performance improvements will make this feature irrelevant. It already is, see @Altai-man's comment above, also see [this IRC log](http://irclog.perlgeek.de/perl6/2016-07-24#i_12899515).
