### ISSUE TITLE
List $^placeholders as one of the traps

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#364]
http://doc.perl6.org/language/variables#The_^_Twigil

> Although it is possible to use nearly any valid identifier as a placeholder variable, it's recommended to use short names or ones that can be trivially understood in the correct order, to avoid surprise on behalf of the reader.

In other words, some people may be tempted to have meaningful placeholder names while expecting it to work in the order of appearance. This is definitely a potential [trap](https://doc.perl6.org/language/traps).

**Comment by nicqrocks** [comment]
Should this be under it's own section on the "traps" page (called Variables or something), or would it fit nicely under one of the current ones? I was thinking that it could possibly fit under the heading "Common Precedence Mistakes", but the more I think about it, the more I'm not so sure.

**Comment by AlexDaniel** [comment]
IMO it deserves a separate section.

Perhaps we need a new section with a heading like “Good ideas that are actually really bad” or something.

**Comment by nicqrocks** [comment]
"It Sounded Like a Good Idea at the Time..."

**Comment by AlexDaniel** [comment]
Maybe. But to me your version sounds like it is actually a fault of the language itself (i.e. these features were implemented because it sounded like a good idea).

Any other versions? :)

**Comment by nicqrocks** [comment]
Yeah your right, I didn't even think of that. :/
Well "Variables" would work, but it would not really get much use (that I can think of). Though other subheadings don't have much under them either...
What about something like "Using Shortcuts"? The only thing is that I'm not sure what would be considered a "shortcut" in Perl6.

**Comment by nicqrocks** [comment]
Added pull request #964
