### ISSUE TITLE
Supply method of Channel is not documented

### ISSUE THREAD

**Issue by gotoexit** [perl6/doc#366]
Per jnthn, Channel is supposed to have a Supply method, which returns a Supply.  I think the Supply is supposed to emit any values sent to the Channel.  The method and its behavior are currently undocumented.

**Comment by gotoexit** [comment]
Looking at the source, there's a peek method as well.  That's not documented either.

**Comment by gotoexit** [comment]
Actually, looked again.  Peek is private, thus probably doesn't need to be documented.  I experimented with Supply some and I'm not sure how it's supposed to behave.

**Comment by jonathanstowe** [comment]
Well for the design rationale it's so you can use it in a react:

```
my $channel = Channel.new;
my $p = start {
    react {
        whenever $channel {
            say $_;
        }
    }
}

await (^10).map: -> $r {
    start {
        sleep $r;
        $channel.send($r);
    }
}

$channel.close;
await $p;
```

This is from the http://doc.perl6.org/language/concurrency#Channels.

**Comment by jonathanstowe** [comment]
Added this and (Promise.Supply)
