### ISSUE TITLE
$/ (last regex match?) not documented or available

### ISSUE THREAD

**Issue by catb0t** [perl6/doc#369]
https://docs.perl6.org/syntax/%24%2F returns a `404 not found`.

Searching for `$/` in the search box also returns the same `404 not found`, and the symbol is not in  a google search for `site:docs.perl6.org regex twigil $/`, understandably.

A look at https://docs.perl6.org/syntax shows the page does not exist in that directory, probably because filenames can't have path separators in them.

If the documentation for this twigil is available, I'd like to read it, and I recommend all requests to https://docs.perl6.org/syntax/%24%2F redirect there instead.

**Comment by AlexDaniel** [comment]
Thank you for your report!

However, it is a known issue. See https://github.com/perl6/doc/issues/155

Therefore I'm closing this as a duplicate. Feel free to leave a comment on https://github.com/perl6/doc/issues/155

**Comment by catb0t** [comment]
@AlexDaniel fair enough. Where can I find documentation for this twigil (and the others mentioned), though? I can't find it on http://perldoc.perl.org.

**Comment by AlexDaniel** [comment]
http://doc.perl6.org/language/variables#The_%24%2F_Variable
