### ISSUE TITLE
Quoting adverbs not documented

### ISSUE THREAD

**Issue by jonathanstowe** [perl6/doc#376]
It could do with something in the language/quoting

**Comment by rudis** [comment]
Seems to be fixed: https://doc.perl6.org/language/quoting, any objections to close this bug?

**Comment by MadcapJake** [comment]
@rudis I don't see any documentation of adverbs in there.

**Comment by jonathanstowe** [comment]
No, still not done.  It's not a "bug" it's a suggestion or a reminder for someone to do something :)

**Comment by AlexDaniel** [comment]
Actually quoting adverbs have a good enough description on https://design.perl6.org/S02.html#Adverbs_on_quotes. Perhaps one could just copy it.

**Comment by jonathanstowe** [comment]
Pretty much, I looked at it a while ago (when I first made the issue)  some of those aren't implemented so they'd have to be checked.

**Comment by rudis** [comment]
Sorry, I missed the "adverb" part and just checked that quotes were documented.

**Comment by gfldex** [comment]
There are also at least 2 open RTs on certain combinations of quote adverbs. That's why I hesitate to list them all.

**Comment by jonathanstowe** [comment]
I keep forgetting about this, I'll go through the list of adverbs in the design document later and see which ones are actually implemented.  Getting a table of the implemented ones into the docs would be a start.

**Comment by AlexDaniel** [comment]
@jonathanstowe ping :)

**Comment by drforr** [comment]
Something to add to the Perl6::Parser test suite as well :)

**Comment by AlexDaniel** [comment]
https://github.com/perl6/doc/commit/fb0bea5fdeab897f9038ea6f0308bbcc8b95428e#commitcomment-21005020

**Comment by JJ** [comment]
This last commit closes the issue? Is everyone satisfied with it?

**Comment by AlexDaniel** [comment]
I think you're right. All of the adverbs are also searchable. This is indeed looks closed to me, thanks!
