### ISSUE TITLE
Confusion in documentation of < >

### ISSUE THREAD

**Issue by pmichaud** [perl6/doc#38]
Entering "< >" in the search box currently lists three entries:
   Postcircumfix: .< >    leads to routine/.<%20>   (currently 404 not found)
   Circumfix: < >           leads to routine/<%20>
   Quote: < >                leads to syntax/<%20>

I don't think there should be a "circumfix" entry, as < > is not an operator, nor is there a ```circumfix:«< >»``` function/routine.  As far as I can tell, it's purely a syntactic construct.

I suspect the same should be said for postcircumfix .< > -- as far as I know it's not a routine in its own right -- it's really syntactic sugar for .{< >} .  It's not an operator in its own right (e.g., that could be overloaded).

**Comment by awwaiid** [comment]
Right now these are some nodes like "This is not a real operator, just syntactic sugar that is turned into the { } postcircumfix operator at compile-time." for postcircumfix.< > -- do you think that a similar note for circumfix: < > will suffice?

**Comment by AlexDaniel** [comment]
@awwaiid I think yes.

**Comment by AlexDaniel** [comment]
OK, so:
* Postcircumfix: .< > leads to [here](https://docs.perl6.org/language/operators#index-entry-postfix_.postfix-postcircumfix_.%28_%29-postcircumfix_.[_]-postcircumfix_.{_}-postcircumfix_.%3C_%3E-postfix_.postfix). It clearly says ``In most cases, a dot may be placed before a postfix or postcircumfix:`` (implies that it is not an operator on its own), but then it also says ``Technically this is not an operator, but syntax special-cased in the compiler. ``. So no problem here.
* Quote: < > leads to [here](https://docs.perl6.org/language/quoting#index-entry-quote_qw-quote_%3C_%3E-Word_quoting%3A_qw). Again, I don't think that there's any problem with that.

However, there's now ``< >`` in **Routine** category: https://docs.perl6.org/routine/$LESS-THAN_SIGN%20$GREATER-THAN_SIGN and it says:
> The quote-words construct. Breaks up the contents on whitespace, and returns a List of the words. If a word looks like a number literal or a Pair literal, it is converted to the appropriate number.

So at this point the most appropriate title for this ticket is: **``< >`` is listed as a circumfix operator, but it is not a real operator**. Is that right?

**Comment by gfldex** [comment]
fixed with 22ddf6db07 b3dc4f2dc7 2eb85f315c
