### ISSUE TITLE
Need to SEE-NO-EVAL

### ISSUE THREAD

**Issue by fecundf** [perl6/doc#385]
2016.01 Rakudo *'s p6doc complains "use MONKEY-SEE-NO-EVAL" at c:\rakudo\bin\p6doc:83

Looks like #256 mentioned this in a different way.

**Comment by stmuk** [comment]
From the recently updated http://perl6.org/downloads/

"p6doc was broken on Windows. Fix is to, with Git in the %PATH%, "panda
--force install p6doc" and delete C:\rakudo\bin\p6doc.bat."

S

On 6 February 2016 at 19:12, fecundf <notifications@github.com> wrote:

> 201601 Rakudo *'s p6doc complains "use MONKEY-SEE-NO-EVAL" at
> c:\rakudo\bin\p6doc:83
>
> Looks like #256 <https://github.com/perl6/doc/issues/256> mentioned this
> in a different way
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/doc/issues/385>.
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by stmuk** [comment]
The windows p6doc fix at  http://perl6.org/downloads/ has been updated.

On 6 February 2016 at 21:17, Steve Mynott <steve.mynott@gmail.com> wrote:

> From the recently updated http://perl6.org/downloads/
>
> "p6doc was broken on Windows. Fix is to, with Git in the %PATH%, "panda
> --force install p6doc" and delete C:\rakudo\bin\p6doc.bat."
>
> S
>
> On 6 February 2016 at 19:12, fecundf <notifications@github.com> wrote:
>
>> 201601 Rakudo *'s p6doc complains "use MONKEY-SEE-NO-EVAL" at
>> c:\rakudo\bin\p6doc:83
>>
>> Looks like #256 <https://github.com/perl6/doc/issues/256> mentioned this
>> in a different way
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/perl6/doc/issues/385>.
>>
>
>
>
> --
> 4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by awwaiid** [comment]
Closing this since it sounds fixed.
