### ISSUE TITLE
add more detail about implicit return

### ISSUE THREAD

**Issue by jdv** [perl6/doc#388]
For instance, note that { "ret"; CATCH { default {} } } will not return "ret" which may be
counter-intuitive to some.

**Comment by salortiz** [comment]
I hope than in a future v6.x the non r-value phasers will be in some way re-moved/hidden/separated from the compiled execution tree of the block.
Meanwhile, its recommended position in the block should be at the top.

**Comment by MadcapJake** [comment]
Agreed, this tripped me up.  To my eye, `CATCH { ... }` seems similar to a conditional branch but only runs if an error occurs, so with that assumption, it follows that the previous line would be the implicitly returning one. While I would enjoy that slight change to the semantics, it's definitely important we get this documented.  The language/exceptions page could use at least one example showing a try/catch in a returning block and some discussion of this idiosyncrasy.

**Comment by AlexDaniel** [comment]
I think this may fit our [traps](https://docs.perl6.org/language/traps) page. I've been banging my head against this issue a couple of times.

**Comment by JJ** [comment]
So the position here is to add something to the traps page, right?

**Comment by AlexDaniel** [comment]
@JJ I think so, yes.

**Comment by JJ** [comment]
OK, I self-assign it, please feel free to help.

**Comment by AlexDaniel** [comment]
@JJ any progress?

**Comment by JJ** [comment]
Not really. I'll de-assign it, just in case you want to work on it.
