### ISSUE TITLE
Semaphore documentation

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#393]
Is there a reason that class Semaphore isn't defined yet? I could write a bit about it. Though I do not know yet what ```my class Semaphore is repr('Semaphore') {...``` means. I.e. the trait is repr(). I have found it in the file core/Semaphore.pm of rakudo.

Marcel Timmerman

**Comment by jonathanstowe** [comment]
the repr is a VM level representation that provides special features to the thing in question.

**Comment by moritz** [comment]
The rerpr is (mostly) an implementation detail, and doesn't need to be discussed in user-facing docs.

**Comment by MARTIMM** [comment]
Hi, I've made the documentation. You can find it in the link below(txt but it is a pod file, so you have to rename it)

[Semaphore.txt](https://github.com/perl6/doc/files/130359/Semaphore.txt)
