### ISSUE TITLE
Multiple same-named arguments

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#394]
From [S06](https://design.perl6.org/S06.html#Named_arguments):

> Perl 6 allows multiple same-named arguments, and records the relative order of arguments with the same name. When there are more than one argument, the @ sigil in the parameter list causes the arguments to be concatenated:

This does not work right now.

Some comments from @jnthn:

> jnthn: fwiw, I'd be surprised if that was ever implemented.
> jnthn: It's likely incompatible with multi-dispatch for one.
> jnthn: Should probably get tossed from the design docs, anyway.

**Comment by moritz** [comment]
@AlexDaniel did you mean to open this issue on perl6/specs instead? If not, what's the exact TODO here?

**Comment by AlexDaniel** [comment]
@moritz Whoops!
