### ISSUE TITLE
Character class negation is undocumented

### ISSUE THREAD

**Issue by mdinger** [perl6/doc#40]
Character class negation isn't documented anywhere in [regex](http://doc.perl6.org/language/regexes). I asked on IRC where they told be the syntax is `<-[abcd]>` compared with Perl5 `[^abcd]`.

This should be documented.

**Comment by pmichaud** [comment]
It's kind of documented, but not as clearly as it ought to be.  The text currently reads:

```In between the < > , you can also use the same operators for categories (+, |, &, -, ^) to combine multiple range definitions and even mix in some of the unicode categories above. Another thing you are allowed to write between the [ ] is the backslashed forms for character classes.```

The + and - "operators" it refers to are the ones that handling character class addition and negation.  I agree it's unclear as written, and there ought to be an example showing the most common negation form.

**Comment by mdinger** [comment]
Awesome! I'd also expand on how operators behave when on the endpoints they are usually binary operators and it might not be immediately apparent how they might operate as prefixes (although, now that I think about it, I can see how they might operate).
