### ISSUE TITLE
Document common case of "for 'text-file'.IO.lines -> $_ is copy { s/foo/bar/; .say }"

### ISSUE THREAD

**Issue by ronaldxs** [perl6/doc#400]
The question was discussed on IRC: http://irclog.perlgeek.de/perl6/2016-02-17#i_12057580 .  I feel it may not be obvious to newb from Perl 5 who tries (for example):
```perl6
for 'text-file'.IO.lines <-> $_ { s/foo/bar/ }
```
what to do with the error message "expected a writable container".
As a common case it may make sense to document the needed "is copy", and on IRC it was suggested the comments go with the "lines" documentation.  So, for example, the end of the lines documentation in [Cool.pod](https://github.com/perl6/doc/blob/master/doc/Type/Cool.pod).

**Comment by gfldex** [comment]
Fixed with https://github.com/perl6/doc/commit/299a655b3f8046dbb74a395294ecc7fdb4fdfe70 .
