### ISSUE TITLE
IO::Handle "replace" deprecated method ins with kv

### ISSUE THREAD

**Issue by jantz** [perl6/doc#401]
Hi,
i found `IO::Handle` method `ins` (current line number) has been 'replaced' with `kv`.
`
for "sample.txt".IO.lines.kv -> $ln, $line {
    say "[$ln] $line";
}
`
See https://github.com/rakudo/rakudo/commit/77fc44d9c0fb6025be0ed1b2506cde996f6c8db6 but `ins` is still documented.
I think we can't easy replace ins with kv because kv comes from somewhere else.
I can't find the class or role where `kv` comes from, i have no clue.

But i think it is useful to document this.

Thx.

**Comment by jantz** [comment]
I looked a bit through rakudo source and the documentation and found that `"foo.txt".IO.lines` returns a sequence. My guess is that the sequence has the feature when we ask for `.kv` to return the current position or index and the value.
But how should this documented and where? I like to see it in the `IO::Handle` docs, because for me it's the natural location for the line number.

**Comment by dogbert17** [comment]
I have removed the documentation for method ins which solves one part of this issue.

**Comment by timo** [comment]
On 02/17/2016 09:57 PM, jantz wrote:
>
> Hi,
> i found |IO::Handle| method |ins| (current line number) has been
> 'replaced' with |kv|.
> |
> for "sample.txt".IO.lines.kv -> $ln, $line {
> say "[$ln] $line";
> }
> |
> See rakudo/rakudo@77fc44d
> <https://github.com/rakudo/rakudo/commit/77fc44d9c0fb6025be0ed1b2506cde996f6c8db6>
> but |ins| is still documented.
> I think we can't easy replace ins with kv because kv comes from
> somewhere else.
> I can't find the class or role where |kv| comes from, i have no clue.
>
> But i think it is useful to document this.
>
> Thx.
>

Indeed, kv does come from somewhere else. You can see in the example
that it's used on the result of a .lines method called on the IO object.

In fact, kv comes from the List class:
http://doc.perl6.org/routine/kv#class_List

For lists, it simply gives you an index and a value.

Note, however, that usually people would assume a line number would
start at 1, not at 0. So in that example code, it might be wise to at
least point it out, or explicitly write $ln + 1 or something.

Hope that helps, and thanks for contributing to the documentation!
  - Timo

**Comment by ronaldxs** [comment]
In [5to6-perlvar](https://docs.perl6.org/language/5to6-perlvar#Variables_related_to_filehandles), $*IN.ins is still documented as the way to get the input line number like perl5 `$.`, `$NR`.  That no longer works.
