### ISSUE TITLE
printf is missing

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#407]
[printf](http://doc.perl6.org/routine/printf) is missing but [sprintf](http://doc.perl6.org/routine/sprintf) is documented.

**Comment by azawawi** [comment]
Working on it :+1:

**Comment by AlexDaniel** [comment]
Does it mean that we should not have a page for [printf](http://doc.perl6.org/routine/printf)?

**Comment by AlexDaniel** [comment]
Also, it is slightly broken. If you search for ``printf`` then you will see something like this:
![three printf results](https://files.progarm.org/2016-03-04-120751_447x232_scrot.png)

However, both ``printf FILEHANDLE`` and ``printf FORMAT, LIST`` are pointing to a wrong id. Compare [printf FORMAT, LIST (current link, broken)](http://doc.perl6.org/language/5to6-perlfunc#printf%20FORMAT%2C%20LIST) with [printf FORMAT, LIST (what it should be)](http://doc.perl6.org/language/5to6-perlfunc#printf)

**Comment by AlexDaniel** [comment]
This is really great and the situation is much better now. Thanks, @azawawi!

However, there is still no dedicated documentation for ``printf``. See this discussion: http://irclog.perlgeek.de/perl6/2016-03-04#i_12137740

Therefore I'll reopen it again.

**Comment by dogbert17** [comment]
Fixed now, see https://doc.perl6.org/routine/printf. Closing issue.
