### ISSUE TITLE
.shape is missing from the documentation

### ISSUE THREAD

**Issue by edehont** [perl6/doc#411]
The method shape returns the dimensions of an array, but is not mentioned in the documentation.
I'm unsure how and where to add this to the documentation.

**Comment by azawawi** [comment]
Maybe https://github.com/perl6/doc/blob/master/doc/Type/Array.pod ?

**Comment by edehont** [comment]
Seems to be the right place. :-)
The next thing: the docs contain entries like
```
Defined as:
    multi sub    shift(Array:D )
    multi method shift(Array:D:)
```
Where do I find that kind of information?
rakudo/src/Array.pm gives me: `method shape() { (*,) }`. That looks different.

So far I guess my addition to Array.pod would be:
`=head2 method shape

Defined as:

        method shape() { (*,) }

Usage:

    ARRAY.shape

Returns the shape of the array as a list.

Example:

    my @foo[2;3] = ( < 1 2 3 >, < 4 5 6 > );
    say @foo.shape;     # (2 3)
  
`

OK?

**Comment by azawawi** [comment]
Create a pull request please and let us see what `#perl6` gurus say :+1:

**Comment by LLFourn** [comment]
I think those gists come from something like:

.perl.say for Array.can("shape")

# method shape (Array $: *%_) { #`(Method|140420701857272) ... }

**Comment by edehont** [comment]
I created a pull request.

**Comment by azawawi** [comment]
Thanks. Waiting for Travis CI to OK to merge :+1: 

@edehont++

**Comment by azawawi** [comment]
Merged in https://github.com/perl6/doc/commit/cc82fb2004179732c3cc03c07a1d0e7919d31ad1

**Comment by moritz** [comment]
@edehont thanks for your contribution.

Regarding the question of where to find things, an easy way it use `git grep` in a clone of the rakudo repository:

    moritz@pat:~/p6/rakudo$ git grep 'method shape'
    src/core/Array.pm:    method shape() { (*,) }
    src/core/native_array.pm:        method shape() {
    src/core/native_array.pm:    method shape() { (*,) }

The interesting thing is that normal arrays aren't constraint in their shape, hence they return a placeholder (a list returning a whatever star). Only native arrays support shapes right now, which is why one of the methods in src/core/native_array.pm returns more interesting values.

**Comment by edehont** [comment]
I'm still in the sorcerer's apprentice stage where git and #perl6 are concerned... Thanks.

**Comment by edehont** [comment]
It suddenly hit me what you meant: the case of the normal array returning the whatever star should be explicitly mentioned in the docs as well.
I will add that ASAP.

**Comment by azawawi** [comment]
Thanks looking forward for your pull request :+1:

**Comment by edehont** [comment]
It's already merged. https://doc.perl6.org/routine/shape
