### ISSUE TITLE
｢val｣ is not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#412]
｢val｣ is not documented

**Comment by coke** [comment]
I assume the ask here is to document "unusual" quotes for strings?

**Comment by coke** [comment]
Looks like it's documented here:

http://docs.perl6.org/language/quoting

**Comment by AlexDaniel** [comment]
Sorry, I was speaking about **val**.
```
say val(‘25’)
```
```
25
```

**Comment by raiph** [comment]
Relevant, from S02:

http://design.perl6.org/S02.html#The_%3Aval_modifier
http://design.perl6.org/S02.html#Allomorphic_value_semantics
http://design.perl6.org/S02.html#Allomorphic_Rats
http://design.perl6.org/S02.html#Literals

From S06 (search for `val()`):

http://design.perl6.org/S06.html#Declaring_a_MAIN_subroutine

And from S15:

[Conjecture: should val() use unival on one-character strings as part of its allomorphic type process? E.g. ./fractionmagic.p6 ¾ takes the one positional argument as a RatStr.]

**Comment by raiph** [comment]
Btw, I'm pretty sure ShimmerFairy++ did the hard work of actually implementing this (twice, iirc).

**Comment by AlexDaniel** [comment]
http://doc.perl6.org/routine/val

**Comment by jonathanstowe** [comment]
Yeah I put this in when I did the rest of the allomorph stuff.
