### ISSUE TITLE
@*INC no longer exists, update 5to6

### ISSUE THREAD

**Issue by fecundf** [perl6/doc#414]
https://doc.perl6.org/language/5to6-perlvar says
    @INC... it will probably not surprise you that this is @*INC in Perl 6.

But according to Fournier "@*INC doesn't exist anymore. Any help to remove it from the docs appreciated."

I don't know how perl6.c stores/uses its module search path, if someone who does can update the doc here & wherever else appropriate, I'd much appreciate it! thanks!

**Comment by LLFourn** [comment]
@lizmat fixed it up and I put some examples:
https://github.com/perl6/doc/commit/ecba519927dcd7b38864fe16229ec7d541218ead

@lizmat note: there is a generic API to find the loaded modules of a repo. `.loaded` is part of the CompUnit::Repository API.
