### ISSUE TITLE
IntStr, NumStr, RatStr and ComplexStr  not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#418]
- [x] IntStr
- [x] NumStr
- [x] RatStr
- [x] ComplexStr

Feel free to submit a separate commit for each

**Comment by jonathanstowe** [comment]
Infact all of the "allomorphs" should be documented, that is IntStr, NumStr, RatStr and ComplexStr ...

**Comment by AlexDaniel** [comment]
@jonathanstowe good catch! I've changed the title.

**Comment by jonathanstowe** [comment]
Just picking this up.

**Comment by jonathanstowe** [comment]
Some of this stuff may want linking from the quoting and wherever MAIN is documented, but this should cover it off for the most part.

**Comment by AlexDaniel** [comment]
@jonathanstowe do you think that it requires more work under this ticket? It looks closeable to me.

**Comment by jonathanstowe** [comment]
I think it's done yeah :)
