### ISSUE TITLE
.polymod is not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#426]
Perhaps see this for some explanation: http://codegolf.stackexchange.com/questions/75623/repdigit-base-finding/75659#75659

Also this: https://design.perl6.org/S32/Numeric.html#polymod

**Comment by dogbert17** [comment]
How about the following version of the examples section?

    my $seconds = 3600;
    say $seconds.polymod(60,60,24) L<Z|routine/Z> <seconds minutes hours days>;  # ((0 seconds) (0 minutes) (1 hours) (0 days))
    say 3661.polymod(60,60,24);                                                  # (1 1 1 0)

    # another way to do calculations like the ones above without using polymod
    my $secs = 3661;
    for 60,60,24 { say $secs mod $_; $secs div= $_ }; say $secs;                 # 1\n1\n1\n0

**Comment by AlexDaniel** [comment]
It was fixed in https://github.com/perl6/doc/commit/4c2ea19c4356fba7acece6a88ab65b45e26646d1 and improved in https://github.com/perl6/doc/commit/39e8e39ecfb08e6a1cd18c761fe90e1cb4a4fa4b. 

@dogbert17++, keep it up!
