### ISSUE TITLE
Many not working links in "Sets, Bags, and Mixes" page

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#428]
Hi
In this page https://doc.perl6.org/language/setbagmix
Links in the following line(`(elem)`,`(cont)`,`(+>)`) is not working.
`Equivalent to (elem), at codepoint U+2208 (ELEMENT OF).`
`Equivalent to (cont), at codepoint U+220B (CONTAINS AS MEMBER).`
`Equivalent to (+>), at codepoint U+227D (SUCCEEDS OR EQUAL TO).`

**Comment by gfldex** [comment]
All but one 404 fixed by https://github.com/perl6/doc/commit/b359168750e59e2d636e6e07b058cf3d4f279c7f 

The last one is a missing page, I will close this ticked and open a new one for the missing page.
