### ISSUE TITLE
X<C<foobar>|foobar> does not create html anchor

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#434]
It is in the javascript index and the link goes to the document. Since there is no anchor, the link doesn't go to that anchor. As an example use "nextsame".

**Comment by zoffixznet** [comment]
That probably should be `X<< C<foobar>|foobar >>` shouldn't it, since there are `< >` inside?

**Comment by gfldex** [comment]
The content of X<> does land in the index, so it must be parsed correctly.

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/Pod-To-HTML/commit/6131c1aa95ee98aea8470af08d688c478f36407c and https://github.com/perl6/doc/commit/9dd28ba964ef90b8785026e1c3ff3da98bc546b6
