### ISSUE TITLE
Sequence examples no longer work as advertised / section could use improvement

### ISSUE THREAD

**Issue by dod38fr** [perl6/doc#444]
Hello

In page http://doc.perl6.org/language/list#Sequences , the following example:

```
  my @s := (loop { 42.say }); # Error expected Positional but got Seq
```

triggers an endlees loop instead of the error mentioned in comment (tested with rakudo 2016.03).

Although I can't say if this is a bug or a documentation error.

All the best

**Comment by zoffixznet** [comment]
Looks like that whole section needs to be rewritten. None of the examples with binding produce described results, so I think the behavior of `loop` in such form has changed.

Also, using only the `loop {...}` to make a sequence leaves out much neater things like the sequence operator: `0, 2 ... *` might be a better example to use, or at least it should be mentioned.

**Comment by JJ** [comment]
That page has evolved, and that particular example works as advertised. Can you please check if it's OK now, or suggest changes?

**Comment by zoffixznet** [comment]
This example is wrong:

```
my @s := Seq.new(<a b c>); CATCH { default { say .^name, ' ', .Str } }
# OUTPUT «Type check failed in binding to $iter; expected Iterator but got List ($("a", "b", "c"))␤  in block <unit> at <tmp> line 1␤␤» 
```

It's trying to show that you can't bind a `Seq` to a `Positional` variable, but it's constructing the `Seq` incorrectly and gets the wrong error. It's meant to be `<a b c>.Seq` and then the error message will be different; actually saying that you can't bind stuff.

> Although I can't say if this is a bug or a documentation error.

It's a [known bug](https://rt.perl.org/Ticket/Display.html?id=131845#ticket-history). IIRC it's trying to reify the `Seq` with `.perl` to show a bit of its guts in the error message and ends up reifying forever.
