### ISSUE TITLE
Allow search for variables

### ISSUE THREAD

**Issue by pmichaud** [perl6/doc#45]
Today on IRC a P6 newbie was asking for the Perl 6 equivalent of Perl 5's  `__FILE__` .  It might be nice the search box would allow searching for variables by name.

**Comment by AlexDaniel** [comment]
While ``__FILE__`` is now searchable, [compile-time variables](http://doc.perl6.org/language/variables#Compile-time_variables) are still not.

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/892fd8ea70954c66098cad8cf7faca4e178f7c1c
