### ISSUE TITLE
Classes and Objects doc: needs simple example to start with

### ISSUE THREAD

**Issue by uvtc** [perl6/doc#454]
The [Classes and Objects tut](http://doc.perl6.org/language/classtut) needs to start off with a more basic example. Something that doesn't need `bless` or that all-caps BUILD submethod. For example, the doc should start off something like:

~~~
Here is a very simple example:

    class SpaceShip {
        has $.max-phaser-bank-charge = 10;  # A constant?
        has $.curr-phaser-level;
        has $!num-days-since-last-federation-violation;
        has @.num-alien-delegates-aboard;
        has %.dangerous-cargo-name->qty; # or however you'd write this
        ...
        method set-phasers-to (...) { ... }
        method diffuse-alien-delegate-argument (...) {...}
        method misplace-dangerous-cargo (...) {...}
        method detonate-dangerous-cargo (...) {...}
    }

And a more intricate example:

    class Task {
        # currently in this doc
        ...
~~~

**Comment by jonathanstowe** [comment]
Hi,
I've added an even less elaborate example (that can be run out of the box without additional code,) and a small piece of introductory text.

**Comment by uvtc** [comment]
Thanks.

Your Pod seems to have some formatting issues though. I don't think you need the indented `=begin code` and `=end code` tags (I don't recall Pod syntax offhand though). Also, it looks like your Rectangle method is not indented.

I also think the addition would benefit from including examples of:

  * a comment after each line exemplifying one aspect of Perl 6 OO ("`# instance variable`", "`# class variable`", "`# instance method`", "`# class method`", etc.)
  * a private instance variable
  * a class variable
  * brief explanation of why you wrote `$.lower` in one place, but `$!lower` inside the method
  * no constructor? Does Perl 6 implicitly provide that? A comment would be useful here: `# Perl 6 implicitly provides a default constructor.`

**Comment by jonathanstowe** [comment]
Eugh, that's weird.

I'll fix the formatting.

**Comment by jonathanstowe** [comment]
I'd forgotten it wasn't doing tab expansion :(
