### ISSUE TITLE
Compile-time "constants" heading link broken

### ISSUE THREAD

**Issue by pmichaud** [perl6/doc#46]
On docs.perl6.org/language/variables, there's a heading called ```Compile-time "constants"``` .  Clicking on the link heading fails because of the quotation marks (%22) in the heading title.

The heading tag is incorrectly rendered as ```<h2 id="Compile-time_"constants"">``` .

My suggestion is to remove the quotation marks around "constants"; perhaps "compile-time variables" or "compile-time values" is a better wording anyway.

Pm

**Comment by paultcochrane** [comment]
This issue has been corrected in 2d0bb11.  The word "variables" was chosen to replace "constants" since the values aren't really constant, which is what the quotes were trying to convey in the original version of the text.
