### ISSUE TITLE
Regex )> and <( are not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#462]
Not really sure what they're called. Captures, but not the `$0, $1, $2...` captures:

```
<ZoffixW> m: say 'foo=bar' ~~ / \w+  '='  \w+/
<camelia> rakudo-moar f05c77: OUTPUT«｢foo=bar｣␤»
<ZoffixW> m: say 'foo=bar' ~~ / \w+ )>  '='  \w+/
<camelia> rakudo-moar f05c77: OUTPUT«｢foo｣␤»
<ZoffixW> m: say 'foo=bar' ~~ / \w+ <(  '='  \w+/
<camelia> rakudo-moar f05c77: OUTPUT«｢=bar｣␤»
<ZoffixW> m: say 'foo=bar' ~~ / \w+ <(  '='  )> \w+/
<camelia> rakudo-moar f05c77: OUTPUT«｢=｣␤»
```

**Comment by MadcapJake** [comment]
Relavant details in [S05](design.perl6.org/S05.html#Transliteration):

>The following tokens include angles but are not required to balance:

>A `<(` token indicates the start of the match's overall capture, while the corresponding `)>` token indicates its endpoint. When matched, these behave as assertions that are always true, but have the side effect of setting the `.from` and `.to` attributes of the match object. That is:
```perl6
/ foo <( \d+ )> bar /
```
>is equivalent to:
```perl6
/ <?after foo> \d+ <?before bar> /
```
>except that the scan for "foo" can be done in the forward direction, while a lookbehind assertion would presumably scan for `\d+` and then match "foo" backwards. The use of `<(...)>` affects only the positions of the beginning and ending of the match, and anything calculated based on those positions. For instance, after the match above, `$()` contains only the digits matched, and `$/.to` is pointing to after the digits. Other captures (named or numbered) are unaffected and may be accessed through `$/`.

>When used directly within quantifiers (that is, within quantified square brackets), there is only one Match object to set `.from`/`.to` on, so the `<(` token always sets `.from` to the leftmost matching position, while `)>` always sets `.to` to the rightmost position. However, the situation is different for capturing parentheses. When used within parentheses (whether or not the parens are quantified), the Match being generated by each dynamic capture serves as the target, so each such capturing group sets its own `.from`/`.to`. Hence, if the group is quantified, each capture sets its own boundaries independently.

>These tokens are considered declarative.

**Comment by AlexDaniel** [comment]
It is indexed and documented, is there anything else we want to say there?

**Comment by zoffixznet** [comment]
I think we're good. Thanks.
