### ISSUE TITLE
Document categorize-list

### ISSUE THREAD

**Issue by nkh** [perl6/doc#469]
https://doc.perl6.org/routine/categorize-list needs to be documented, explaining the difference with classify and also what a multi level classification/categorization is.

**Comment by dogbert17** [comment]
At least partly solved with https://github.com/perl6/doc/commit/d54f984b86

**Comment by zoffixznet** [comment]
Along with the above, this issue is fixed with 6b99fb88f0fd9980cf9f03acb5acf0c08d1fb81e eee5cfab34d56680e6956710c5ec163ae5328dc2 b4575c9731c8e0e9c267f194711cc4a891ad4996 782e000422c8e70f6fb4cb6670c26833affecc20 and b234967097505171da77221ff9da0dd11cab0a0d
