### ISSUE TITLE
∘ is not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#471]
``∘`` or ``o`` is not documented.

There is a function composition example here: https://perl6advent.wordpress.com/2015/12/07/day-7-unicode-perl-6-and-you/

**Comment by jonathanstowe** [comment]
Is that the function combining character? I could have sworn I saw that documented the other day.

**Comment by AlexDaniel** [comment]
Are you sure that it was on doc.perl6.org ? :)

**Comment by jonathanstowe** [comment]
No, I'm not sure at all :)

**Comment by gfldex** [comment]
it is in:
doc/Language/unicode_texas.pod
doc/Type/Callable.pod

There is no index entry. I will see to it.

**Comment by gfldex** [comment]
index fixed with https://github.com/perl6/doc/commit/64b6a263f5e40d0435f94f6de2c12239fb58ad8c
