### ISSUE TITLE
supply {} block not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#476]
If it is documented, then it's not searchable.

**Comment by jonathanstowe** [comment]
It is documented as I remember doing it :) However yes, it may not be searchable.

**Comment by jonathanstowe** [comment]
http://doc.perl6.org/language/concurrency#Supplies -but arguably it should also be in the Supply document.

**Comment by jonathanstowe** [comment]
Actually, (sorry to hijack the issue somewhat,) neither is ```on-demand``` which is somewhat associated, they could be added together.

**Comment by ab5tract** [comment]
IIRC, there is a bias to 'overdocumentation' in `doc`, in the sense that
the CONTRIBUTING file reads:

   - Duplicate small pieces of information rather than rely on linking

 By which I mean, maybe it is better to flesh out the concepts in both
locations using divergent examples. This has the benefit of contrasting
discussions and implementations across different use cases. This IME can be
a real boon to 'getting it'.

**Comment by uvtc** [comment]
@ab5tract , I agree with the CONTRIBUTING doc that duplicating small pieces is ok, but I think that *fleshing out* concepts in multiple locations leads to too much duplication, and also sometimes confusion ("Where did I read that thing about $concept? I think I found where it's documented, but the bit I'm looking for isn't there..."). It also makes it seem like there's more docs than there really are. It may also make the thorough reader feel that their reading time is being squandered ("why are they telling me this again? It's already been covered!").

If I found a concept fleshed out it two separate places, my first reaction would be to think that maybe it's a doc bug (maybe different authors accidentally duplicated work). My second reaction might be to try and discern in which of the two locations the doc is better placed. :)

I think a good way to go is: duplicate only small pieces (so you can get your point across without sending the reader on too many link-chases), but then *also* provide a link to the canonical location of the docs for $concept. That way, you're not *relying* on the links, but they're there if the reader wants them.

**Comment by gfldex** [comment]
fixed with 3d3455ddf0
