### ISSUE TITLE
errors in Language/functions.pod (includes suggested changes)

### ISSUE THREAD

**Issue by nd3i** [perl6/doc#477]
I'm not sure how to contribute edits, so I'll just drop it here:

The example code under Subroutines: https://doc.perl6.org/language/functions#Subroutines has some problems and fails to compile/work

1) The named character class **<-alpha-digit>** needs a space: **<-alpha -digit>**
2) The second substitution uses **s||** where it should use matched brackets: **s[]**
3) Neither escape sub returns a result. It modifies $_ and returns nothing and has no side-effect. Change to **S[]**
4) The replacement in the second substitution needs to convert the matched string to the character number before invoking base: $/**.ord**.base(16)
5) Tweaks: add needed semi, remove extra semis; single-quotes for strings
Use **... given $str** instead of explicitly setting $_ (cleaner)

Maybe this instead:
https://gist.github.com/nd3i/484520fdf9543a044350818bf7fc5ef6#file-functions_sub_example-p6

**Comment by dogbert17** [comment]
Should be fixed now with https://github.com/perl6/doc/commit/03dd1b59a6

**Comment by AlexDaniel** [comment]
All listed issues are indeed fixed.
