### ISSUE TITLE
sample output typo in Language/functions.pod

### ISSUE THREAD

**Issue by nd3i** [perl6/doc#479]
Defining Operators > Precedence
https://doc.perl6.org/language/functions#Precedence

Sample output:
say 1 + 2 * 3 !! 4;     # 29

Correct output is 1 + ((2 * 3) !! 4)
= 1 + (6 !! 4)
= 1 + (2 * (6 + 4))
= 1 + (2 * 10)
= 21

**Comment by AlexDaniel** [comment]
It looks like it was meant to be ``is tighter(&infix:<*>)``

**Comment by dogbert17** [comment]
Changed the result to 21. Now the text and result shown match.

https://github.com/perl6/doc/commit/ab41b988af

**Comment by AlexDaniel** [comment]
Oh, now I've noticed that it mentions ``is tighter(&infix:<*>)`` too, so indeed, it looks like the comment was wrong.

@dogbert17 Good, but now there's a problem with this phrase:
> The same effect could have been achieved with

What does it mean now? What kind of “same effect”?

**Comment by dogbert17** [comment]
Can we close this?
