### ISSUE TITLE
Infix + doesn't show up in documentation

### ISSUE THREAD

**Issue by Mouq** [perl6/doc#48]
http://doc.perl6.org/+ and http://doc.perl6.org/routine/+ list the prefix version and the regex version, but not the infix operator.

**Comment by zoffixznet** [comment]
Neither does the `-`

**Comment by paultcochrane** [comment]
I started debugging this a while ago (but got sidetracked) and IIRC, the items directly after a '=head1' were being skipped by the code which selects the items to go into `index.js` as well as the list of routines.  For instance, if you edit `lib/Language/operators.pod` and move the entry for `infix C«+|»` to directly after `=head1 Additive Precedence` (line 561 atm) and rebuild the docs (e.g. with `make html-nohiglight` (so it builds a bit faster)), then you'll find that the entry `Infix: +|` disappears from the search box and it disappears from the list of routines in `routine.html`.  Strangely enough, `infix -` *does* currently show up under http://doc.perl6.org/routine/-, so I don't know why you're not seeing it at present (it doesn't turn up in the search box, but that's probably a separate, however related, issue).

After moving `infix +|` directly under the `=head1` heading in my local build (and thus putting `infix +` and `infix -` at second and third places after the heading) made `infix +` and `infix -` then appear under `routine/+.html` and `routine/-.html` respectively.  Hopefully this information helps in debugging/investigating this issue further.

**Comment by Mouq** [comment]
Thanks @zoffixznet for the extra info @paultcochrane for the excellent debugging! That leads me to believe that it's most likely a bug in [`&find-definitions`](https://github.com/perl6/doc/blob/master/htmlify.p6#L315-L459), which is a little bit scary at the moment and really probably wants a refactor anyway. If no one gets to this earlier, I'll try to take it up this weekend.

**Comment by awwaiid** [comment]
infix + now shows up in both places -- does that just mean the symptom was relieved or that the problem is fixed?

**Comment by dogbert17** [comment]
Seems to have been fixed some time ago. According to Zoffix this can be closed.
