### ISSUE TITLE
is tighter, is equiv, is looser traits not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#480]
Perhaps this: https://perl6advent.wordpress.com/2011/12/22/day-22-operator-overloading-revisited/

**Comment by AlexDaniel** [comment]
Actually, this is probably good enough already: https://doc.perl6.org/language/functions#Precedence

Maybe just making ``is tighter``, ``is equiv``, ``is looser`` point here would be enough?

**Comment by gfldex** [comment]
fixed with ed896ceaa8
