### ISSUE TITLE
PERL6LIB env var not documented

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#481]

**Comment by tbrowder** [comment]
It IS documented in <./doc/doc/Language/5to6-nutshell.pod>, but I think it needs to be in the main docs (although I'm not sure where).

**Comment by tbrowder** [comment]
Now I think a good place to mention PERL6LIB is in modules.pod.

**Comment by sjn** [comment]
Would it be sensible to create a separate document describing all environment variables?

**Comment by sjn** [comment]
I looked around a little, and see that s

**Comment by tbrowder** [comment]
closed by pr #485
