### ISSUE TITLE
｢.nl-in｣ and ｢.nl-out｣ show as routines, not methods

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#484]
These are mentioned in some places (some listed below), but they are not searchable.
- http://doc.perl6.org/type/IO::Handle#method_lines
- http://doc.perl6.org/type/IO::Handle#method_print
- http://doc.perl6.org/routine/put#role_IO
- http://doc.perl6.org/routine/say#role_IO

**Comment by dogbert17** [comment]
This seems to be working, am I missing something?

**Comment by AlexDaniel** [comment]
Yes! It guess @zoffixznet++ made it searchable at some point.

However, right now ``nl-in`` and ``nl-out`` are listed as a “Routine”, which is wrong.

**Comment by zoffixznet** [comment]
> Yes! I guess @zoffixznet++ made it searchable at some point.

They were undocumented at the time and now they are.

> However, right now nl-in and nl-out are listed as a “Routine”, which is wrong.

Unsure why. They're both documented as methods: https://docs.perl6.org/routine/nl-out https://docs.perl6.org/routine/nl-in

Also, #1331 is not entirely unrelated here.
