### ISSUE TITLE
to-posix is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#494]
See: https://github.com/rakudo/rakudo/blob/8cbb1efd1d84fd57298e0e0813b64d8dd37140ba/src/core/Instant.pm#L24

**Comment by dogbert17** [comment]
https://github.com/perl6/doc/commit/e82d31531f

**Comment by jonathanstowe** [comment]
Looks good to me. http://doc.perl6.org/type/Instant#method_to-posix

Cheers @dogbert17

**Comment by dogbert17** [comment]
No more comments, closing issue.
