### ISSUE TITLE
Dateish.yyyy-mm-dd not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#496]
In the [Dateish source](https://github.com/rakudo/rakudo/blob/nom/src/core/Dateish.pm#L117), there's:

```perl6
method yyyy-mm-dd() { sprintf '%04d-%02d-%02d',$!year,$!month,$!day }
```

It doesn't seem to be documented

**Comment by dogbert17** [comment]
https://github.com/perl6/doc/commit/9d1a02e308

**Comment by zoffixznet** [comment]
Thanks a lot!
