### ISSUE TITLE
Poor Documentation for Dateish.formatter

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#497]
The `.formatter` is an attribute that can be set to modify how a `Dateish` thing is `.Str`ingified. The docs only mention its return value and there's no explanation for how to set your own formatter or how it will be called:

```perl6
    multi method Str(Dateish:D:) {
        &!formatter ?? &!formatter(self) !! self!formatter
    }
```

**Comment by dogbert17** [comment]
https://github.com/perl6/doc/commit/b6fa110740
