### ISSUE TITLE
IO::Special not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#498]
Here is an example on how you can stumble upon it.

Code:
```perl6
say $*IN.path
```

Result:
```
IO::Special.new(what => "<STDIN>")
```

**Comment by jonathanstowe** [comment]
It's a pain because it's just a fake IO::Path variant for the STDIO handles whereas it would be neater if the had some common antecedent.

**Comment by AlexDaniel** [comment]
It says:
```
This returns '<IN>', '<OUT>' or '<ERR>' as approriate. 
```

However:
```perl6
say $*IN.path.Str # <STDIN>
```

**Comment by jonathanstowe** [comment]
Then the class itself and/or how it is being used is broken.  And infact iit is:

```
[jonathan@coriolanus doc.master]$ perl6 -e 'say $*IN.path.r'
False
```

The *r* operator is supposed to return True for $*IN - and actually does test for ```$!what eq '<IN>'```
All of the code in the module that cares is predicated on it being one of the values indicated. 

I'll fix and then change the documentation.

**Comment by jonathanstowe** [comment]
I've fixed the class with https://github.com/rakudo/rakudo/pull/763 as it doesn't actually work as intended anyway right now, I'll fix the documentation before that goes in.
