### ISSUE TITLE
Html link to nativeInt

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#50]
On the Perl6 doc page about types ```http://doc.perl6.org/type.html``` the link to class int on the bottom of the line points to a non existing file (http://doc.perl6.org/type/nativeInt). I've found http://doc.perl6.org/type/int.html though but I'm not sure if this one is meant.

**Comment by paultcochrane** [comment]
Thanks for pointing this out!  You're right: it was supposed to point to the content located at `/type/int.html`, however the file wasn't being generated properly. Fixed as of fb88605.
