### ISSUE TITLE
5to6 mentions $*INITITME but it does not exist (typo)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#504]
From [5to6-perlvar](http://doc.perl6.org/language/5to6-perlvar):
> Replaced in Perl 6 by $*INITITME. Unlike in Perl 5, this is not in seconds since epoch, but an Instant object, which is measured in atomic seconds, with fractions.

OK, let's try it.

Code:
```perl6
say $*INITITME
```

Result:
```
Dynamic variable $*INITITME not found
  in block <unit> at -e line 1

Actually thrown at:
  in block <unit> at -e line 
```

----
```
<bartolin> AlexDaniel: is the last one not just a typo?
```
Whoops. Yep.

While we are at it, I believe that this is usually done by using ``BEGIN now``. Perhaps it should mention ```BEGIN now```?

But there is a slight difference:
Code:
```perl6
say $*INITTIME;
say BEGIN now
```

Result:
```
Instant:1462717691.553166
Instant:1462717691.709836
```

**Comment by b2gills** [comment]
It should be `say INIT now`

**Comment by AlexDaniel** [comment]
Not sure.

Code:
```perl6
say INIT now;   # ↑
say BEGIN now;  # ↑
say $*INITTIME; # ↑
```

Result:
```
Instant:1462726778.539183
Instant:1462726778.513827
Instant:1462726778.351224
```

**Comment by dogbert17** [comment]
The typo has been fixed with https://github.com/perl6/doc/commit/9da628596f
