### ISSUE TITLE
Order not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#505]
Code:
```perl6
say WHAT 4 <=> 8
```

Result:
```
(Order)
```

See also: https://github.com/rakudo/rakudo/blob/nom/src/core/Order.pm

**Comment by gfldex** [comment]
fixed with:
https://github.com/perl6/doc/commit/a90a5e51c2e1188b729ce7f2f6ba46b873ad1963
https://github.com/perl6/doc/commit/9360de4dc36ad2805ed84e93d4610c8f147c0fde
https://github.com/perl6/doc/commit/1d0235165fd757a35cabab4c8166cd00b469eabc
