### ISSUE TITLE
Int says "two main forms", but there are more.

### ISSUE THREAD

**Issue by pmichaud** [perl6/doc#507]
http://doc.perl6.org/type/Int introduces the Int type by saying "There are two main syntax forms for Int literals", then discusses the standard decimal (123) and radix (:16<BEEF>) forms.

I think the 0x, 0d, 0b, and 0o forms should also be listed as other standard syntax forms for Int literals.  I'm not exactly sure how to rephrase the text to include these literal formats, thus this issue ticket to solicit corrections.

**Comment by gfldex** [comment]
As requested wording provided in https://github.com/perl6/doc/commit/960e14c8ed .

Closing this as it is done.
