### ISSUE TITLE
Add a style guide for contributers

### ISSUE THREAD

**Issue by smls** [perl6/doc#51]
It might be good to have a style guide for people (such as myself) who are contributing POD content to this repo, so the "finished" docs end up in a consistent and professional state.

Here are a few "questions" that imo should be covered by such a guide (though I don't have good answers for all of them):

---

##### How to document multiple similar routines

I'd suggest making it a guideline to *avoid* wtiting a routine's documentation in the form

    Like [other method] except [...]

even when they're in the same class, because readers might not read the whole class page, but rather navigate to a specific routine (maybe even out of context in the /routine/ section of the website) and expect it to tell them how it works without being sent on a goose chase around the site.
In other words, give each routine documentation a self-contained introduction, and only link to related/similar routines *below* that introduction, even if that means duplicating some half-sentences multiple times.

##### How to refer to the concept of only using the .Bool/.Num/etc. coercion of a value and discarding the original information</b>

Compare:

* "it evaluates the value in boolean/numeric context"
* "it boolifies/numifies the value"
* "it uses the truthy/numeric value"
* "it reduces the value to its boolean/numeric equivalent"

Are all of these sufficiently professional and newbie-friendly? Which is preferred?

##### Whether to write 'parameter' vs 'argument'

I recently came across this in S06:
> S06: "In Perl 6 culture, we distinguish the terms parameter and argument; a parameter is the formal name that will attach to an incoming argument during the course of execution, while an argument is the actual value that will be bound to the formal parameter. The process of attaching these values (arguments) to their temporary names (parameters) is known as binding. (Some C.S. literature uses the terms "formal argument" and "actual argument" for these two concepts, but here we try to avoid using the term "argument" for formal parameters.)"

I'd suggest we follow the spec here from now on, and make this an official guideline for p6doc.

##### Whether to write 'object' vs 'value'

Is it OK to use "objects" as an umbrella term for instances of *any* Perl 6 type, including immutable value types?

Or should it be reserved for reference types, and be replaced with the phrase "objects/values" whenever we're talking about both reference and value types?
(See the introduction of [/type/Set](http://doc.perl6.org/type/Set) for an example of this usage, though this shouldn't be seen as a recommendation.)

##### Whether to use past tense or present tense when talking about Perl 5 features

Compare:

* "In Perl 5 this was used for ..., but in Perl 6 ..."
* "In Perl 5 this is used for ..., but in Perl 6 ..."

Slipping into the past there can be tempting when writing such docs, but I think we should avoid it, as it misrepresents the development status of Perl 5 (which is actively maintained both now and probably for a long time to come), and could come across as needlessly abrasive to Perl 5 programmers.

##### How to show output of sample code lines

Currently, we tend to use normal # comments both for annotating code, and for showing its output:
<pre>my @a = 2, 4, 6; # creates a new array
say @a.WHAT;     # (Array)</pre>
Though I think I've also seen this convention used somewhere:
<pre>my @a = 2, 4, 6; # creates a new array
say @a.WHAT;     #> (Array)</pre>
It could avoid ambiguity, and while it is a little uglier by itself, htmlify could detect it so we could give it special CSS rendering (think dark background with light text like a terminal) that would make its purpose extra clear to readers.

Would it be worth it?

---

**Comment by moritz** [comment]
Here are my thoughts in short: 

* +1 to having a style guide
* +1 to rather duplicating than saying "like $other_method"
* I already try to make the parameter/argument distinction; might be worth pointing  it out nonetheless
* `object` is OK for anything you can call methods on, including value objects and type objects. I tend to use "instance" for defined objects.
* +1 to present tense when talking about p5
* +0.5 to having a designated syntax for output. I'm not sure I like `#>` because it reminds me of the REPL, and the REPL doesn't require `say`. I try to avoid the ambiguity now by putting "normal" comments above the lines they comment. Note that a special syntax for output with custom rendering might interfere with syntax hilighting. If you can come up with a patch that makes it work, I'm all for it though.

**Comment by smls** [comment]
> Note that a special syntax for output with custom rendering might interfere with syntax hilighting.

Actually wouldn't the syntax highlighting work in our favor? As it would allow us to easily match the output fragments to highlight using a regex like

  / '<span class="c-Singleline">' '#>' (<-[<>]>*) </span> $$ /

on the output of pygments, without having to parse the Perl 6 code ourselves (to make sure we don't misinterpret # inside strings etc.).

**Comment by uvtc** [comment]
`#=>` makes a good "evaluates to":

    say @a.WHAT;     #=> (Array)

**Comment by moritz** [comment]
I like `#=>`, we'd need one more for "dies with this message".

**Comment by uvtc** [comment]
#:| Sump pump activated. Bailing out.

Nice feature: it matches `#=>` in that it's two characters and a space after the `#`.

Bonus: looks like a not-too-terribly happy face (which goes with the theme of "dies with this message"). Hm, actually, kind of looks like [Pepe the King Prawn muppet](http://muppet.wikia.com/wiki/Pepe_the_King_Prawn). :)

**Comment by raiph** [comment]
Aren't die messages nearly always obviously a die message?

What about just:

  # ' ... '

and if it isn't obvious a message is a warn, or die, or
whatever message:

  # die ' ... '
  # warn ' ... '

etc.

--
raiph


On Tue, Feb 24, 2015 at 2:46 PM, Moritz Lenz <notifications@github.com>
wrote:

> I like #=>, we'd need one more for "dies with this message".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/doc/issues/51#issuecomment-75830883>.
>



-- 
raiph

**Comment by smls** [comment]
> and if it isn't obvious a message is a warn, or die, or
> whatever message:
>  # die ' ... '
>  # warn ' ... '

I'd simply use `#=>` for that too (is STDERR output really so different from STDOUT output?), or in cases where it needs to be more explicit, a "normal" comment like `# dies with ' ... '` and `# warns ' ... '`.

Although I suppose `#!>` could work too.

**Comment by uvtc** [comment]
I think it certainly helps (at least, in writing books/docs) to have a specific comment style to indicate "this gets printed to stdout", in contrast to "this evaluates to" (and also in contrast to plain vanilla comments).

It hadn't ocurred to me that it would also be useful to have a specific comment style to indicate "prints this to stderr then exits".

Maybe:

~~~perl
my $x = 42;
foo($x);  # Prints, "You passed $x.",
          # then returns 1 regardless.
          #: You passed 42.
          #=> 1

# But dies if you pass in a string:
foo("a"); #X> "Khan!!"
~~~

**Comment by smls** [comment]
I really like your `#:` suggestion for "prints this string to the terminal", it's short but effective.

The `#X>` seems appropriate too; at least it succeeds in reminding me of the `X::` namespace for Perl 6 exception classes. `#X:` or `#!:` could work too, to keep it closer to the "normal" `#:`.

As for "evaluates too" (assuming we even need it), it just occured to me that `#->` might be more appropriate than `#=>`, because it would mirror the return parameter syntax from routine signatures rather than the Pair construction operator.

Although this is getting into bikeshed territory.
I guess moritz should simply choose (if, and which).

**Comment by moritz** [comment]
I tend to `#->` for output and `#!>` for errors, but I'll only start using it once markup for it exists.

**Comment by raiph** [comment]
I now see how much nicer the short versions are.

Fwiw `#=>` looks like it would clash with the special
`#=` comment (http://design.perl6.org/S26.html).

Another reason to use Moritz's `#->` instead.

--
raiph



On Sat, Feb 28, 2015 at 4:42 AM, Sam S <notifications@github.com> wrote:

> I really like your #: suggestion for "prints this string to the
> terminal", it's short but effective.
>
> The #X> seems appropriate too; at least it succeeds in reminding me of
> the X:: namespace for Perl 6 exception classes. #X: or #!: could work
> too, to keep it closer to the "normal" #:.
>
> As for "evaluates too" (assuming we even need it), it just occured to me
> that #-> might be more appropriate than #=>, because it would mirror the
> return parameter syntax from routine signatures rather than the Pair
> construction operator.
>
> Although this is getting into bikeshed territory.
> I guess moritz should simply choose (if, and which).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/doc/issues/51#issuecomment-76519236>.
>



-- 
raiph

**Comment by LLFourn** [comment]
I looked around for other style guides and found:
https://jacobian.org/writing/technical-style/#id8

I think the style suggestions in the anchored section are useful :)

**Comment by dha** [comment]
Immediate thoughts:

+1 to there being a style guide.
+1 to Perl 5 present tense (and, I probably need to go through the docs I've been writing and make sure I've done that).

**Comment by ShimmerFairy** [comment]
Just a note for terminal input/output, which seems to have been discussed quite a bit: Pod6 has the `=input` and `=output` blocks, as well as the inline `K<>` and `T<>` equivalents. `=input` and `K<>` (**k**eyboard) is for input provided by the user, e.g. via `&prompt` or REPL input. `=output` and `T<>` (**t**erminal) is for terminal output.

These blocks and codes are formatted like `=code` and `C<>`, with the difference that all formatting codes are allowed in them by default. They're also formatted similarly, with different monospace fonts suggested by the spec when possible.

Some examples of usage: REPL examples could be shown as such:

    =begin output
    > K<say "42\n";>
    42

    > K<say 21 * 2>
    42
    >
    =end output

While code samples could be formatted as something like:

    =begin code :allow<K T>
    my $a = prompt "Number? >";
    say cos($a);

    # example usage:
    # T«Number? >»K<90>
    # T<-0.44807361612917>
    =end code

This doesn't exclude the use of special comment syntaxes discussed above me, however I did want to point out the existing standard features for representing terminal output and input in Pod6. You could also make use of custom "named" blocks and `M<>` codes if extra formatting features are desired (e.g. a theoretical `M<err:...>` and/or `=Error` for standard error output), though I don't know how much rakudo supports those yet.

**Comment by moritz** [comment]
While `T<>` sounds nice in theory, it still looks cumbersome in practice, because it means one needs explicit `=begin code :allow<T>` blocks before example code, which becomes so much boilerplate that I'm not motivated to use it.

I'd rather go with `#=>` or so for output (and I'll start using it as soon as somebody implements hilighting/markup for it)

**Comment by awwaiid** [comment]
@smls how about we close this now that the STYLEGUIDE.md exists?

**Comment by AlexDaniel** [comment]
[Yeah](https://github.com/perl6/doc/blob/master/STYLEGUIDE.md).
