### ISSUE TITLE
X::Seq::Consumed is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#515]
Therefore it seems that the links in the following page https://doc.perl6.org/type/Seq#method_is-lazy is not working.

**Comment by dogbert17** [comment]
Fixed with https://github.com/perl6/doc/commit/9728090607

**Comment by jonathanstowe** [comment]
That's there http://doc.perl6.org/type/X::Seq::Consumed I'll close.

For reference, rather than create individual tickets for each missing exception class  I've created #517 to cover off the residue.
