### ISSUE TITLE
Provide (automatic) Texas variant sample code in html view, hidden by default

### ISSUE THREAD

**Issue by coke** [perl6/doc#526]
Based on a discussion in #524, it would be great if our public face on all examples (except where specifically showcasing a Texas variant) was the unicode variant; While we've been careful to provide an ASCII alternative in most cases, IMO our public face should show the unicode operators.

However, to help our users, it would be nice if block code samples had a (potentially automatically generated) Texas-safe block, which was able to be toggled. It might even be nice if the user's selection of Texas vs. Unicode was remembered, for those users who eschew unicode.

**Comment by MadcapJake** [comment]
Perhaps even just a hover over a unicode operator would show the texas variant?  Seems a bit too minor of a change to provide a toggle over whole code blocks for.

**Comment by jonathanstowe** [comment]
*Or* even a hover over that has the ascii variant *and* the codepoint number and/or how to type instructions :)

**Comment by sjn** [comment]
Jonathan Stowe said:
> 
> Or even a hover over that has the ascii variant and the codepoint number
> and/or how to type instructions :)

I like this idea, FWIW :)


- Salve

-- 
#!/usr/bin/env perl
sub AUTOLOAD{$AUTOLOAD=~/.*::(\d+)/;seek(DATA,$1,0);print# Salve Joshua Nilsen
getc DATA}$"="'};&{'";@_=unpack("C*",unpack("u*",':50,$'.#    <sjn@foo.no>
'3!=0"59,6!`%%P\0!1)46%!F.Q`%01,`'."\n"));eval "&{'@_'}";  __END__ is near! :)

**Comment by vendethiel** [comment]
I really the idea as well. The "best" would be a racket-style "click on the function or operator and you get the docs for that"

**Comment by coke** [comment]
I am now leaning away from this for two reasons:

1) More work on an already overworked doc staff.
2) The community as a whole is pushing unicode; I think the docs should lead in this effort, and it's OK to be unicode only, because
3) we still have the texas page.

**Comment by AlexDaniel** [comment]
This ticket is asking for snippets with texas versions of non-texas ops, but we don't have enough examples using non-texas variants for it to be a noticeable problem. For now this is a non-issue, but everyone is welcome to create a PR for this. Also, feel free to reopen or create a new ticket if you have something particular in mind.

I'm closing this in favor of #1520. Maybe temporarily, maybe not. But I'm pretty sure that this ticket won't move anywhere unless there's progress on #1520.
