### ISSUE TITLE
Docs on qqw say that it is equivalent to «», but it is not

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#532]
http://doc.perl6.org/syntax/qqw.html

``«»`` is equivalent to ``qqww``, not ``qqw``.

Originally reported by Dmitry Kopytov ([RT](https://rt.perl.org/Ticket/Display.html?id=128177))

**Comment by AlexDaniel** [comment]
Not sure when it was fixed, but there's no such problem anymore.

**Comment by jonathanstowe** [comment]
I think I fixed it a few weeks ago when I docced qqww or something,
