### ISSUE TITLE
lazy, eager, hyper, race not documented in statement_prefix form

### ISSUE THREAD

**Issue by MadcapJake** [perl6/doc#534]
Not sure how [these](https://github.com/rakudo/rakudo/blob/nom/src/Perl6/Actions.nqp#L2030-L2056) should be documented, but currently they are only documented as their method forms.  Would these be called subs? routines? or statement prefixes?

**Comment by AlexDaniel** [comment]
- [ ]  lazy
- [ ]  eager https://docs.perl6.org/routine/eager#(List)_routine_eager ?
- [ ]  hyper
- [ ]  race

**Comment by JJ** [comment]
Apparently [those lines have moved](https://github.com/rakudo/rakudo/blob/nom/src/Perl6/Actions.nqp#L2339-L2389) Is that correct?

**Comment by AlexDaniel** [comment]
Yes. Also the issue is still relevant and these things are indeed not documented yet.

**Comment by JJ** [comment]
No, they wouldn't. They are not documented in statement prefix form, and there is little or no documentation for other statement prefixes...
