### ISSUE TITLE
nativecast is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#537]
You can see nativecast in the following section
https://doc.perl6.org/language/nativecall#Function_Pointers
But there's no description of what nativecast is.

**Comment by jonathanstowe** [comment]
I'm going to add a section in the native call doc for the exported functions.

**Comment by jonathanstowe** [comment]
This is somewhat vague as I couldn't think of a sensible example.

**Comment by AlexDaniel** [comment]
So-o-o we kinda have something now: https://docs.perl6.org/routine/nativecast
Besides making the text more readable (there's a *huge* sentence), is there anything else we should do?

**Comment by titsuki** [comment]
@AlexDaniel 
I'll close this issue since as you can see nativecast is documented.
