### ISSUE TITLE
Add note to footer about missing docs

### ISSUE THREAD

**Issue by coke** [perl6/doc#541]
Add a note to the footer about how to note that you were unable to find the docs you were looking for. (something more specific than a link to the github doc project)

**Comment by AlexDaniel** [comment]
> something more specific

Like what? I'm asking because this issue has been open for a while, perhaps others also don't understand what it could possibly say.

**Comment by lancew** [comment]
Is this addressed already with the " This is a work in progress to document Perl 6, and known to be incomplete. Please report any issues.  "  text in the footer?

Can this issue be closed @coke ?

**Comment by coke** [comment]
That's fine. Thanks.
