### ISSUE TITLE
META6.json is not searchable

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#550]
But sorry, I'm not sure where to describe the information of the META6.json.

FYI:https://design.perl6.org/S22.html

**Comment by jonathanstowe** [comment]
It's in here http://docs.perl6.org/language/modules#Distributing_Modules but it could be a) more complete and b) searchable

**Comment by titsuki** [comment]
@jonathanstowe
Thanks for the reply !
I have changed the title of the issue.

**Comment by Altai-man** [comment]
Closed with https://github.com/perl6/doc/pull/1155.
