### ISSUE TITLE
DenomT should be replaced with DeT

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#552]
See:
https://docs.perl6.org/type/Rational#method_numerator
https://docs.perl6.org/type/Rational#method_denominator

```
$ perl6 -e 'Rat.new.numerator.WHAT.say'
(Int)
$ perl6 -e 'Rat.new.denominator.WHAT.say'
(Int)
```

```
$ perl6 --version
This is Rakudo version 2016.05-4-g7a4ca4d built on MoarVM version 2016.05
implementing Perl 6.c.
```

**Comment by b2gills** [comment]
Actually it should be `DeT` not `DenomT`

Basically Rational is a parameterized role that takes two types, one for `NuT` and one for `DeT`

    my role Rational[::NuT, ::DeT] does Real { ... }
    my class Rat is Cool does Rational[Int, Int] { ... }

So those two types **do** exist within the role, but are just aliases to the types the role is parameterized with.

Perhaps the best route would be to omit documenting the return type.  
At the very least `DenomT` should be replaced with `DeT` everywhere on that page.

**Comment by titsuki** [comment]
@b2gills
Thanks for your neat explanation !
I understand the internal mechanism.

> Perhaps the best route would be to omit documenting the return type.

hmm, I'm not sure...


> At the very least DenomT should be replaced with DeT everywhere on that page.

I think so. I'll change the title of this issue.
