### ISSUE TITLE
Example of the open method seems wrong

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#554]
See: http://doc.perl6.org/type/IO#sub_open

This example is not work.
```
my $fh = open("test", :w);
spurt $fh, "stuff\n";
spurt $fh, "more stuff\n";
$fh.seek(0, 0);   # return to the start of the file
$fh.get();        # Reading from filehandle failed: bad file descriptor
```

**Comment by zoffixznet** [comment]
The `spurt`s should be `print`s

**Comment by titsuki** [comment]
Honestly to say I found it from this post http://perlmonks.org/index.pl?node_id=1164393
But I don't have my account. :baby_chick:

**Comment by titsuki** [comment]
@zoffixznet Thanks !
