### ISSUE TITLE
Hyper operators are not searchable

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#562]
`«` `»` `<<` `>>` – none of these has a link to https://doc.perl6.org/language/operators#Hyper_Operators

**Comment by Altai-man** [comment]
Closed with https://github.com/perl6/doc/commit/d9a902c8e5efcca6ee0d074ff4e23c0651a7ce5a

**Comment by nxadm** [comment]
The postfix postfix ». / postfix >>. operator is documented here:
https://docs.perl6.org/language/operators#postfix_%C2%BB._/_postfix_%3E%3E.

There are two problems:
- it's not searchable (looking for >>. has no results, looking for >> give other usages like regex).
- the operator is documented as >>. with the dot, while elsewhere it's referenced without.

**Comment by JJ** [comment]
Yep. That page has major issues.
