### ISSUE TITLE
TODO: make anchors available for linking to sections directly

### ISSUE THREAD

**Issue by moritz** [perl6/doc#57]
When github renders a README, hoovering over the heading shows a link with an anchor to exactly that section.

I'd like to have something similar for the htmlify output, so that it becomes easy to link to a section directly.

**Comment by smls** [comment]
+1, and imo the "scroll back to the top of the page" functionality should be delegated to such a hover icon as well.

The title itself should not be a link at all.
<i>(Except if a type or routine names appear in a title (that is not its own section title), in which case that word - and not the whole title - should be a link to the corresponding doc page. But that's part of a larger plan that I will likely make a mockup and separate issue for sometime soon.)</i>

**Comment by awwaiid** [comment]
Is this something that one would change in https://github.com/perl6/Pod-To-HTML/ ?

**Comment by moritz** [comment]
@awwaiid yes, I think so.

**Comment by AlexDaniel** [comment]
Each section now has a § link next to it. Click on it and you get a link to the anchor.

I think that we can call it “fixed”, though I'm not sure when it happened.

**Comment by zoffixznet** [comment]
> though I'm not sure when it happened.

I added it May 29, 2016 in https://github.com/perl6/doc/commit/8507fd513b2772f15314b2384621c99aadd12b14  I didn't realize there was an Issue open.
