### ISSUE TITLE
no matching results red box covers search field

### ISSUE THREAD

**Issue by jsoref** [perl6/doc#574]
Visit http://doc.perl6.org/
Focus the search box and enter something that doesn't exist

Expected results:
The red box shouldn't cover the search field

Actual results (for narrow windows): it does, making it very hard to change the search.

Chrome Desktop w/ Narrow window:
![image](https://cloud.githubusercontent.com/assets/2119212/15939162/89fcf77c-2e44-11e6-826d-c943a62d9d21.png)
Firefox Android:
![image](https://cloud.githubusercontent.com/assets/2119212/15939171/95090d4a-2e44-11e6-8d7d-6c3fd51b8434.png)

**Comment by zoffixznet** [comment]
Thanks. Fixed. The fix should be on the live site within a few hours, when the generator for the next run finishes.
