### ISSUE TITLE
time on footer too specific

### ISSUE THREAD

**Issue by coke** [perl6/doc#579]
example:

2016-06-10T13:24:24.173138Z

we can definitely drop fractional seconds, and probably don't care about whole seconds at all either.

**Comment by AlexDaniel** [comment]
This commit fixes it, I think: https://github.com/perl6/doc/commit/ee767e6c5604a8a37bcd27335d74b20267bb4a68

The date will now look like ``2016-06-10T14:32:12Z``. I don't think that there is any need to drop seconds.

However, maybe we should change the format to something different? Like ``2016-06-10 14:32:12 UTC`` or something?

**Comment by coke** [comment]
I'm fine with the ISO standard date there.

**Comment by AlexDaniel** [comment]
OK then.
