### ISSUE TITLE
X::IO::Link not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#587]
It is already linked from here: http://doc.perl6.org/routine/link
And it does actually exist: https://github.com/rakudo/rakudo/blob/a80414edc1194b0852be5b19130bec670f2bb45e/src/core/IO/Path.pm#L376

**Comment by dogbert17** [comment]
49e72a2e34

**Comment by AlexDaniel** [comment]
That looks alright. Thanks!
