### ISSUE TITLE
Vow not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#588]
Linked from here: http://doc.perl6.org/language/concurrency#Promises

**Comment by coke** [comment]
This is a very small helper class with two methods that is only available in the context of the vow method. It's probably sufficient to document it there.

(e.g. you cannot even create a Vow yourself. In Java-speak, it's an inner class, and a simple one at that.)

**Comment by jonathanstowe** [comment]
Infact the entire necessary documentation of Vow can be found in the Promise.vow documentation, it's probably just remove the link from that page.

**Comment by AlexDaniel** [comment]
If so, we should make Vow point to Promise.vow.

**Comment by coke** [comment]
We can put a link to the class Vow at the 'my class Vow' definition in the vow method docs.

I would also change the text slightly - you can call keep or break on either the Vow you took, or the Promise itself (which internally proxies that to that Promise's vow.)

**Comment by JJ** [comment]
I guess it's documented now, can you please check? https://docs.perl6.org/routine/vow

**Comment by AlexDaniel** [comment]
@JJ Ehhh… There's something about it that doesn't feel right, but we can take it.

**Comment by JJ** [comment]
:+1:
