### ISSUE TITLE
is (inheritance) not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#590]
Linked from http://doc.perl6.org/language/objects#Inheritance

**Comment by gfldex** [comment]
It is provided in http://doc.perl6.org/language/classtut#Inheritance. In my eyes that's a broken link, because taking the trait `is` out of context would not make sense or create redundancy.

**Comment by AlexDaniel** [comment]
Perhaps. My point is that it should also be searchable. Currently there is only one ``is`` and it points to http://doc.perl6.org/language/testing
