### ISSUE TITLE
NaN not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#591]
Linked from http://doc.perl6.org/routine/unival#routine_unival and many other places

**Comment by gfldex** [comment]
NaN is an instance of Num (and defined) and therefore not a type. The documentation of NaN in Num is missing and the links to NaN go to the wrong spot.

**Comment by gfldex** [comment]
first fix with https://github.com/perl6/doc/commit/f59187e7e38de2517574a007497c699dfdf03822

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/84957006f73d6401d1b11c8e8d920255e41885ee
