### ISSUE TITLE
≅, =~= and $*TOLERANCE

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#601]
Tests: https://github.com/perl6/roast/blob/master/S03-operators/relational.t#L211
Some discussion: http://irclog.perlgeek.de/perl6/2016-06-17#i_12680850

**Comment by MasterDuke17** [comment]
PR #604 added some documentation. I had some new tests written, but they need refinement after the expected behavior of $*TOLERANCE was cleared up.

**Comment by AlexDaniel** [comment]
Oh, so we **do** have the documentation now. The only problem is that ``≅`` is not searchable.

As for the tests, please open a separate issue in roast repo.

**Comment by coke** [comment]
I just double checked, ≅ is searchable on docs.perl6.org. Since that was listed as the last issue, closing ticket.
