### ISSUE TITLE
“I'm taking my information” – who?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#612]
http://doc.perl6.org/language/5to6-perlfunc#SOURCES

It says:
> I'm taking my information from https://doc.perl6.org, supplemented by the design documents at https://design.perl6.org/ and input from the denizens of #perl6 on irc.freenode.org

So it says that the information is from the same website… makes sense :)

Maybe we should remove this section?

It's a leftover from S99.

**Comment by Altai-man** [comment]
Actually, this is not the only one part with such structure. I'll prepare a commit to remove all of them tomorrow, if nobody will disagree.

**Comment by AlexDaniel** [comment]
Please note that this phrase exists in ``5to6-perlsyn.pod``, ``5to6-perlfunc.pod`` and ``5to6-perlop.pod``

**Comment by Altai-man** [comment]
Can be closed.
