### ISSUE TITLE
Some glossary terms have no description and others need to be moved around since they are not in alphabetical order

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#622]
Things were added because they have to be explained in the [glossary](https://doc.perl6.org/language/glossary), but nobody bothered to write a proper description yet.

Since most of that stuff was moved from S99, perhaps it would make sense to delete some of the items. However, most of these terms actually need a description.

Please check items once they've been described or removed from the glossary. Team members can remove items from this list once they've been resolved.
- [x] bytecode
- [x] Callable
- [x] Code
- [x] Container
- [x] Cool
- [x] fiddly
- [x] handles
- [x] iffy
- [x] import
- [x] Lexing
- [x] List
- [x] machine code
- [x] Module
- [x] Multi-Dispatch
- [x] multi-method
- [x] opcode
- [x] OS
- [x] Parse Tree
- [x] Package
- [x] Perl Community
- [x] pugs
- [x] Regular Expression
- [x] Repository
- [x] Scalar
- [x] Sigilless Variable
- [x] Stub
- [x] Syntax Analysis
- [x] token
- [x] value
- [x] Variable Interpolation
- [x] whitespace
- [x] 6model

**Comment by coke** [comment]
Anything that ties to a type (or some other docs that already exist) we can remove from the glossary list.

**Comment by Altai-man** [comment]
I filled some items with links, so probably they can be marked as done.
Also, if @coke message is still valid, it will be goodl remove empty type/class/role entries I mentioned here: https://github.com/perl6/doc/issues/582#issuecomment-232970989
Is anyone against removing?

**Comment by AlexDaniel** [comment]
@Altai-man I already have some progress on this. So no, definitely not against.

**Comment by Altai-man** [comment]
I'll remove such entries tomorrow and update the table above then.

**Comment by AlexDaniel** [comment]
@Altai-man I already had it gathering dust (yay for ``git stash``!). Pushed it a minute ago, so the situation is a bit better now. Feel free to finish it though.

**Comment by Altai-man** [comment]
I removed Hash with https://github.com/perl6/doc/commit/75a689d39eb119f2028f98b9ce1aba9ae896aef3, but it wasn't mentioned in the list above.
All other entries from the main list above need writing skills, so I can't help here.

**Comment by AlexDaniel** [comment]
Closed in favor of #728. If #728 is rejected, then this issue should be reopened.
