### ISSUE TITLE
“blocked by #63642” but #63642 is “resolved”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#623]
https://github.com/perl6/doc/blame/cc46aaa8f538d124af1739798ee7dd5903790564/doc/Language/operators.pod#L167

https://rt.perl.org/Ticket/Display.html?id=63642

**Comment by jonathanstowe** [comment]
The example differs from the one given in the RT, and it's not quite clear (to me at least,) what the example in the doc is supposed to do:

```perl6
perl6 -e 'my @a = 1,2; @a ,= 3,4;
say @a.perl'
(my \Array_74336048 = [Array_74336048, (3, 4)])
```

I'd be minded to just remove the example as the above will raise more questions than it answers.
