### ISSUE TITLE
Tests for text content

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#625]
Right now the [tests](https://github.com/perl6/doc/tree/master/t) are not very useful.

It would be great if there were tests for the documentation content. For example: no space after comma (https://github.com/perl6/doc/issues/624), weird indentation (e.g. mixed tabs with spaces), trailing whitespace, etc.

I am pretty sure that there are even better ideas (spell checking, anyone?), but we should start somewhere. Let's add one or two tests, so that it's clear how to write such tests, and the rest will be figured out.

The problem is that you can't just grep for stuff, the test should parse pod properly. Basically, any clear demonstration on how to do that will solve this issue.

**Comment by coke** [comment]
Not all of these require pod parsing; e.g mixed tabs/spaces.

**Comment by zoffixznet** [comment]
It would be nice to have some sort of a mechanism to *prevent* commits that fail these tests from going in the first place.

Right now for each rogue commit, you have to go through travis build to find a failing test, then clone the repo, run the test yourself to find what exactly is breaking, and then go in and remove some rogue trailing space, run tests again to ensure you fixed the issue, then commit and push. 

Doing all that to get rid of a space is just wasted labour.

**Comment by AlexDaniel** [comment]
Let's see:
* ``you have to go through travis build log to find what's failing`` – makes sense
* ``then clone the repo`` – don't you have it cloned already? Do you clone the repo whenever you want to do any change?
* ``run the test yourself to find what exactly is breaking`` – why? If you looked at travis output (you mentioned it as step 1), then you already know where it is located.
* ``and then go in and remove some rogue trailing space`` – correct. You don't have to do it manually though, feel free to write a one-liner.
* ``run tests again to ensure you fixed the issue`` – that's a good habit and you probably want to do that every time you make any change. But if you only care about whitespace, you can run just one file.
* ``then commit and push`` – sure

Look, I do understand that we can do better, but please don't exaggerate the issue. The amount of work required is exactly the same as for fixing any other tiny mistake.

> Doing all that to get rid of a space is just wasted volunteer labour.

Or maybe after one or two times people will toggle “display [trailing] whitespace” thingy in their editors and we wont see this issue that often. Maybe not, we will see.

> I personally had to unbreak two commits in the 11 days since the tests went in. There were probably other people who had to do the same.

Again, please don't exaggerate. One of your commits is https://github.com/perl6/doc/commit/d1a4741e421298a90dcd6d411ce140e2533836b4. If you take a close look, then even on github the comment is misaligned. So the test pointed out an actual error, and it is there for exactly that purpose (you may claim that the error is irrelevant so it should not trigger a build fail, but under the same logic you can e.g. say that spelling mistakes are irrelevant, so let's not fix them… By the way, if there is any more or less reliable way to write a test for that, then let's do it).

Another commit is https://github.com/perl6/doc/commit/19462fafd253fd6bda8d92d118518d9d0b98eb6e. This one counts.

I see no other people who had to do the same.

As I've already said, we should give it a bit more time. This way we will be able to look back and see if it brought more pain than usefulness. One build fail for “irellevant” trailing whitespace is not enough to draw any conclusion.

**Comment by zoffixznet** [comment]
> why? If you looked at travis output (you mentioned it as step 1), then you already know where it is located. 

It just tells you which test failed, not why it failed and which file has the error. Maybe if you weren't so bent on invalidating people's points you'd notice that.

I'll leave all future failures for someone else to pick up. Don't worry.

**Comment by AlexDaniel** [comment]
By the way, when creating this issue I specified three possible tests that could be written. Two of them are now there, I have created a separate issue for the remaining one: https://github.com/perl6/doc/issues/666

Therefore, it can be closed. But if someone is against such changes then you're still welcome to leave a comment.

**Comment by AlexDaniel** [comment]
@zoffixznet see this https://travis-ci.org/perl6/doc/builds/141078164#L1137
