### ISSUE TITLE
item context not documented

### ISSUE THREAD

**Issue by xdg** [perl6/doc#626]
Item context is listed among operators in [S03](https://github.com/perl6/specs/blob/master/S03-operators.pod), but does not appear to be in the Language/operators documentation, nor listed on the docs site in the list of Routines.

The phrase "item context" is mentioned in only two places and not well explained in either:

```
doc/Language/5to6-perlop.pod
73:named variable, you can use item context, like so: C<$aref = item(@array)>

doc/Language/faq.pod
300:on an expression, and item context (not flattening) with C<$( ... )>
```

**Comment by AlexDaniel** [comment]
This ``item`` thing actually exists!
```perl6
my @array = 2,3,4;
my @foo = @array;
say @foo; # [2 3 4]
my @bar = item(@array);
say @bar; # [[2 3 4]]
```

**Comment by xdg** [comment]
I believe it might be equivalent to prefixing with `$`, as this example implies:

```
> my @array = 2,3,4
[2 3 4]
> my @bar = $@array
[[2 3 4]]
```

But I'm not sure that's universally true or semantically correct, so whoever documents `item` should discuss the relationship with `$` as well.
