### ISSUE TITLE
Backtracking control (:) needs a better example

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#629]
https://doc.perl6.org/language/regexes#Preventing_backtracking%3A_%3A

```
    say so 'abababa' ~~ /a .* aba/   # True
    say so 'abababa' ~~ /a .*: aba/  # False
```

Why would anybody want to write `.*:`? We need a better example.

**Comment by JJ** [comment]
Why would anyone want to match `abababa`? That's why I introduced #1748
We *do* need a better example

**Comment by JJ** [comment]
Some info [on backtracking](http://www.perlmonks.org/?node_id=149357)
