### ISSUE TITLE
Routines page needs reformatting

### ISSUE THREAD

**Issue by xdg** [perl6/doc#639]
The important thing is the name and so that should be in the first column.  The type should come second.

It's confusing to have multiple types listed (particularly when repetitive).  It might make more sense to relate type and source somehow.  E.g. "infix: see Operators; method: see Mu, Any, Foo, Bar, ..."

**Comment by tbrowder** [comment]
On Sunday, June 26, 2016, David Golden <notifications@github.com> wrote:

> The important thing is the name and so that should be in the first column.
> The type should come second.
>
> It's confusing to have multiple types listed (particularly when
> repetitive). It might make more sense to relate type and source somehow.
> E.g. "infix: see Operators; method: see Mu, Any, Foo, Bar, ..."
>

I agree with David. I'll be happy to take a stab at improving the
tables but only if the big dogs agree.

Cheers!

-Tom

>

**Comment by coke** [comment]
on https://docs.perl6.org/routine.html ? Yes, I agree, name first, type second, and having one per line is fine.

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/4a111815e292d4661e8011313280e5f4d1fa0029
