### ISSUE TITLE
lib/Type/Str.pod small changes

### ISSUE THREAD

**Issue by songzan** [perl6/doc#64]
line:178

      say split(';', "a;b;c", :all).perl;    # ("a", ";", "b", ";", "c").list 

should be:

      say split(';', "a;b;c", :all).perl    # (("a", ";"), ("b", ";"), "c").list

line: 180

      say split(';', "a;b;c", 2, :all).perl; #("a", ";", "b;c").list

should be:

      say split(';', "a;b;c" ,2, :all).perl  # (("a", ";"), "b;c").list

**Comment by paultcochrane** [comment]
Thanks! :-)

Merged in 9d93967e9b88f974627386cf997037f2bed65225.
