### ISSUE TITLE
Type Graphs weirdly placed

### ISSUE THREAD

**Issue by xdg** [perl6/doc#640]
The Type Graphs appear in arbitrary places.  E.g.
- Baggy -- at the end after "Methods" and "See also"
- Bag -- after "Creating", "Operators", "Subroutines", "See Also", but before "Routines supplied..."
- Callable -- at the end after "Methods" and "Operators"
- IO -- at the end after "Routines" and "Related Classes"
- Capture -- after "Methods" and before "Routines supplied..."
- FatRat -- before "Routines supplied..."
- Int -- after "Methods" and "Operators", before "Routines supplied"

There's obviously some logic as it's machine generated (apparently after supplied docs but before all other auto-generated docs), but having it wedged between "Methods" and "Routines supplied by" seems a weird place.  I'd suggest putting it at the bottom.

The Type Graphs are also not in the TOC (https://github.com/perl6/doc/issues/641) for a given type, so unless it happens to be visible, you don't know where to find it.

**Comment by AlexDaniel** [comment]
I think that there are two separate issues here, so I have created #641 to make it easier to work with.

**Comment by W4anD0eR96** [comment]
@AlexDaniel @xdg Where should the TypeGraph place in your opinions?

With current procedure, it follows by contents generated by the pod6 file of the very type(call it A), and below is message from A.^mro. Every type page is like this, is it confusing?

**Comment by AlexDaniel** [comment]
@W4anD0eR96 I think it's resolved now. The type graph is shown before stuff from other classes, it's exactly what I expected to see.
