### ISSUE TITLE
Routines Page Has Needlessly Repeated Content

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#642]
Some entries have word `method` repeated multiple times for each of the classes that provides it. Whatever's generating those lists needs to `.unique` the elements.

![untitled](https://cloud.githubusercontent.com/assets/5747918/16363033/2313621c-3b8c-11e6-9b4c-0c89cff72e2c.png)

**Comment by coke** [comment]
Note that the ones on the left correspond one to one with the ones on the right.

**Comment by coke** [comment]
Also note that this is related to #639

**Comment by AlexDaniel** [comment]
> Note that the ones on the left correspond one to one with the ones on the right.

I don't think that it is very practical, but at the same time I don't really want to loose this feature.

What if we squish last elements if they are identical? Some examples:
* ``sub, methods``
* ``methods``
* ``method, method, sub, methods``

Or is it even more confusing?

**Comment by coke** [comment]
squishing breaks the relationship between the 1st and 3rd columns.

Please see #639; the suggestion there to have one line per name/source avoids all the confusion.

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/f45293b0c2643e4e47820aa9f801d97897d2f031
