### ISSUE TITLE
cow not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#643]
https://github.com/rakudo/rakudo/commit/da5278ab04ae1674bb9600ea2e3506bfeae1447b

Or maybe we should wait a little bit before documenting it?

**Comment by zoffixznet** [comment]
There were some recent suggestions to modify the behaviour and lizmat wanted TimToady's feedback: http://irclog.perlgeek.de/perl6-dev/2016-06-26#i_12736210

**Comment by AlexDaniel** [comment]
OK then, it can wait. But let's keep this issue open so that we won't forget about it.

**Comment by coke** [comment]
.cow is no longer in the implementation.
