### ISSUE TITLE
Nav/footer cut off/display looks bad/unprofessional on mobile

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#645]
![screenshot_2016-06-27-08-43-11](https://cloud.githubusercontent.com/assets/5747918/16380150/4dd8446a-3c43-11e6-8032-62267af8de42.png)
![screenshot_2016-06-27-08-43-16](https://cloud.githubusercontent.com/assets/5747918/16380153/524ebd30-3c43-11e6-8cd6-6b221f96ca8f.png)

**Comment by AlexDaniel** [comment]
Can be fixed with flexbox, I guess.

**Comment by AlexDaniel** [comment]
Hm, or maybe just by removing hardcoded height.

**Comment by AlexDaniel** [comment]
Just to clarify the last screenshot, here is another one make on desktop:
![screenshot](https://files.progarm.org/2016-06-27-160256_666x365_scrot.png)

Notice the scrollbar on the right. This is the bottom of the page, but some text goes even lower…
