### ISSUE TITLE
Use SVG logos

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#646]
Inspired by https://github.com/perl6/doc/issues/645 where Camelia looks a bit blurred.

**Comment by tbrowder** [comment]
I have the svg file, but I can't find where it should be located in the doc repo.

**Comment by zoffixznet** [comment]
Closed by #647

**Comment by AlexDaniel** [comment]
Well, not really.

First of all, this image is slightly different. Original .png logo was straight vertical, but this one is slightly rotated. It's OK, I think, but I had to point out the difference. :)

However, there are many other places where this image appears:
* https://doc.perl6.org/ – homepage
* camelia-faded.png is used on the background of almost every page

**Comment by tbrowder** [comment]
On Monday, June 27, 2016, Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> Well, not really.
>
> First of all, this image is slightly different. Original .png logo was
> straight vertical, but this one is slightly rotated. It's OK, I think, but
> I had to point out the difference. :)
>
I didn't think about the rotation until I saw the generated page. I can
rotate it back to level if you want, but I think Camelia is usually shown
rotated (and it looks better as well).

> However, there are many other places where this image appears:
>
>    - https://doc.perl6.org/ – homepage
>    - camelia-faded.png is used on the background of almost every page
>
> I can provide a Camelia svg image, level or rotated, larger or
smaller, wherever needed. I'm not sure what the faded image really means
since it shows up larger but I don't see any real differences in color or
brightness (but my eyes are not as good as they used to be).

**Comment by zoffixznet** [comment]
@tbrowder the faded one is on subpages:

![shot-2016-06-27_18-46-30](https://cloud.githubusercontent.com/assets/5747918/16398419/39a3a930-3c98-11e6-8806-51661b5fc78e.jpg)

**Comment by tbrowder** [comment]
On Monday, June 27, 2016, Zoffix Znet <notifications@github.com> wrote:

> @tbrowder <https://github.com/tbrowder> the faded one is on subpages:
>

Duh (again).  Of course the first page I checked wasn't a subpage...

But I'm happy to produce suitable svg replacements for all Camelias if
desired.

Cheers!

-Tom

P.S. I hope you enjoy Toronto as much as I enjoyed TPC::NA::2016!

>

**Comment by AlexDaniel** [comment]
Not sure if we need a faded svg version. Can't we do that with css?

**Comment by JJ** [comment]
We can fade with CSS alright... If I get this correctly, you want to substitute camelia-faded.png with a scalable camelia.svg that looks faded, right?

**Comment by AlexDaniel** [comment]
Ye.

**Comment by JJ** [comment]
But Camelia has disappeared from the background, faded or otherwise. I think that happened when CSSs started to be generated automatically. Close this or change issue to "Bring Camelia back to the background!!!"?

**Comment by AlexDaniel** [comment]
There are two issues here. One is that the camelia on the home page ( https://docs.perl6.org/ ) is still png. Another is that, yes, faded camelia should come back. Unless there's a good reason not to.

**Comment by zoffixznet** [comment]
> I think that happened when CSSs started to be generated automatically

Then it was removed by accident. Oops. It still exists [on the examples site](http://examples.perl6.org/categories/euler.html)

**Comment by AlexDaniel** [comment]
Now we have double camelia on the home page:

![image](https://user-images.githubusercontent.com/5507503/37405621-c7992548-279d-11e8-8c65-3f6757fc86e8.png)

Also, the homepage image is still png. The one on the background is also possibly a little too big.

**Comment by coke** [comment]
Note that the double cameila is only there when your port width is small enough. Vanishes at a wider width.

Same with

https://docs.perl6.org/type.html

Where the (now single) camelia shows up once, but only on thin width. Additionally though, on this page she's striped because of the table.

**Comment by JJ** [comment]
We can also eliminate big Camelia and leave a bigger, faded camelia everywhere. Eliminating the background Camelia would be tricky, because we would need to assign some unique ID to the contene there so that it does not show up. If it's OK for everyone, even if small and fadded Camelia shows her whiskers behind big Camelia, I'll close this now.

**Comment by zoffixznet** [comment]
> Also, the homepage image is still png

>  she's striped because of the table.

>  shows her whiskers behind big Camelia

That's all fixed in https://github.com/perl6/doc/commit/1c4981d069


> https://docs.perl6.org/type.html Where the (now single) camelia shows up once, but only on thin width

Couldn't repo any width-sensitive issues on that page.
