### ISSUE TITLE
Squished table cells on mobile

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#650]
On page https://docs.perl6.org/type-exceptions.html

Last column is squished and can't scroll sideways:
![screenshot_2016-06-29-17-10-57](https://cloud.githubusercontent.com/assets/5747918/16468993/aa502552-3e1c-11e6-9978-64e0855b0684.png)

**Comment by JJ** [comment]
Still bad...

**Comment by MorayJ** [comment]
Fixed with #2260
