### ISSUE TITLE
Convert WANTED items to github issues.

### ISSUE THREAD

**Issue by coke** [perl6/doc#657]

**Comment by zoffixznet** [comment]
What are 'WANTED' items?

**Comment by AlexDaniel** [comment]
https://github.com/perl6/doc/blob/master/WANTED

**Comment by AlexDaniel** [comment]
Done, I think. Please review https://github.com/perl6/doc/commit/30f81a50c015946c1ffdb060afc16bb1805c3de7 and close if there are no problems.

But what is this?
```
Functions:
    * use [probably really important...]
```

**Comment by LLFourn** [comment]
@AlexDaniel `use` is doc'd on the modules page.

**Comment by AlexDaniel** [comment]
Ah, ``use``! I thought it was about ``probably``, ``really`` and ``important``… lol…

**Comment by AlexDaniel** [comment]
Ah, this can be closed now.
