### ISSUE TITLE
Add “This file is autogenerated. See style.scss” notice to style.css

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#662]
Commit https://github.com/perl6/doc/commit/de23b7ca9fcf1aa56d7c5a6ce23d00d0f4738aa3 introduces SASS, but we still keep ``style.css`` in the repo. There's no need to keep autogenerated files.

**Comment by AlexDaniel** [comment]
That being said, due to https://github.com/perl6/doc/issues/663 it is probably to keep it there… /o\

**Comment by zoffixznet** [comment]
There's a very good reason to keep it. Not every contributor will want to change the styles of the site. 

Currently, SASS processor functionality is optional, which means contributors uninterested in tweaking styles will rely on the generated `style.css` to display docs using the local webserver or the dev app.

**Comment by AlexDaniel** [comment]
I have to agree on this one, I guess. The issue is still one issue there, so I'll change the title :)
