### ISSUE TITLE
Add more build instructions, particularly for debian

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#663]
[CONTRIBUTING.md#mojolicious--web-server](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#mojolicious--web-server) assumes that people use cpanm, which is alright, but a lot of debian users rely on debian repos.
- CSS::Minifier::XS – `libcss-minifier-xs-perl`
- CSS::Sass – ???
- Mojolicious::Plugin::AssetPack – ???

**Comment by zoffixznet** [comment]
:-1: on this. The Perl 5 mantra is "do not muck the system perl" and installing system packages does. This also won't work with `perlbrew` installs. Lastly, I don't see CSS::Sass/::AssetPack in the repos anyway.

**Comment by AlexDaniel** [comment]
Not sure what the mantra is, but I am struggling to make it work. Pretty sure that I am not only one with such setup.

**Comment by AlexDaniel** [comment]
http://irclog.perlgeek.de/perl6/2016-07-03#i_12777752

**Comment by AlexDaniel** [comment]
https://github.com/perl6/doc/commit/f6d3a2448e3a91cccd56eec8ceeff2e655d2bafe kinda fixes this, but it looks like there's a problem. The output is slightly different, see this diff: https://gist.github.com/AlexDaniel/99fd82366a23de14eb335a955bca3b9a

**Comment by coke** [comment]
If the only difference is whitespace in a CSS file, seems fine.

**Comment by zoffixznet** [comment]
This Issue is actually outdated and should've been closed back when we made the build-process compile SASS instead of having it in the repo. I think it was somewhere a week or two before New years.
