### ISSUE TITLE
Docs look and work terrible

### ISSUE THREAD

**Issue by graforlock** [perl6/doc#665]
I really want/wanted to read, but bad usability of the docs page (plus no real UX), furthermore lack of modern design thought process puts the user off. Its old and not up to today's standards. Therefore, it is difficult to navigate. Perl.org with proper indexing, scrolling menu, sidebar and pagination, is currently much much better; it is balanced and readable.

I love Perl, but no one new to the language will ever read this at the current state. 

Is there anything we could do to make it look and work okay?

**Comment by zoffixznet** [comment]
> Is there anything we could do to make it look and work okay? 

Certainly. It's just a matter of agreeing on what the updated look should be like. That can be done by making a sample mockup and showing it for people to vote on.

There's also a related issue vis-a-vis typography, but I think it's evolving into general design stuff: https://github.com/perl6/doc/issues/652

> Perl.org […] is currently much much better; it is balanced and readable.

Thanks ;)

**Comment by AlexDaniel** [comment]
@graforlock are we talking about https://docs.perl6.org/ ? Just making sure, because even though it has problems, it hardly matches you description… Or so it feels to me

**Comment by graforlock** [comment]
@AlexDaniel 

Colour matching problems first; as there should be some pattern there (complementary for instance). Navigation-wise: blue anchor and green background almost never gives readable and clear navigation, those colours are not to be mixed together for readability.  

Secondly, the problem is massively long list with bright yellow zebra stripes that give the feel of stress and annoyance to the end user. Scientific term is nystagmus, i think. Especially pronounced at routines section. Too tiring to watch and not to give up.

I believe most docs and books in general do and should do well with mostly just black, white, some subtle shade of grey, plus sparse colour accents. Github does well with this approach. Two-three colours at maximum here and there to avoid distraction. Not to illuminate/stress the eye every second line, this does not help to concentrate on the actual content of the docs.  Just my impressions. Additionally, nearly all O'Reilly and major book/docs publishers like Penguin adjust to this rule. Less is better.

1) Sections should be divided by more abstract and interesting subject(s) to help users (especially new) in reading , as an example, Rust language as a good reference point), i.e :
- https://doc.rust-lang.org/book/documentation.html
2) Has a clear and proper, number based doc sections. Ascending index with an option to logically go "Next >" section as if user reading though a book, i.e :
- https://docs.python.org/3/library/index.html
3) Balance some colours on the docs site, too screamy, all of it, to actually concentrate on content without the sense of frustration. 
4) Intend to tell the story that user does not want to end too quickly. That is a challenge I agree. Raw content is not too appealing. But even http://perldoc.perl.org/perl.html does not seem to have this problem.

**Comment by AlexDaniel** [comment]
@graforlock thanks! All what you listed should be addressed.

That being said, it is a bit hard to work on such issue, especially when the title is “docs look and work terrible”. I think that it will be better if we split this into many small issues. For example, one can be “blue links on green are not very readable”, then “bright yellow stripes in long lists are annoying”, and so on.

Given that you have such a good gripe on the problems, perhaps you are the best person to start opening such issues massively?

**Comment by AlexDaniel** [comment]
Another way to tackle this problem is to start a great redesign, but unless there's someone willing to pour significant amounts of his free time into this, I think that it is much better to solve these issues one by one.

**Comment by ShimmerFairy** [comment]
I disagree on the alternating rows complaint; for me, having that for long tables of data in general makes it easier to concentrate on the table. I agree the yellow background on alternating rows isn't the best choice, I only disagree with the conjecture that alternating colors are inherently bad.

I definitely think the colors could stand some adjustment, though not in _too_ drastic a way. To me, the rainbow of colors on perl6.org is a great part of the website, and I'd be sad to see that go. (Github may have their colors balanced, but I find it too monochromatic for something like perl6.org.)

One thing I definitely agree on, however, is the organizational structure of the docs themselves. Definitely lackluster and in need of improvement. (In particular, the generated/aggregated pages are a nice idea in theory, but really fall apart in practice in my experience.)

**Comment by graforlock** [comment]
@ShimmerFairy

Altering colours, a.k.a zebra table, is nothing bad by design and it is  not that the general notion is awful. It's the choice of colours that makes it noisy and difficult to concentrate on the entries.

**Comment by gfldex** [comment]
I would like to provide an example that I mostly like:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by gfldex** [comment]
first steps to deal with usability problems:

commit c0701808139527978e89547d7c045cd4c5b8e51e
    darken comments in <pre> for more contrast

commit 231c503bcaa4f4f7e6bb7839c3d52314139b03f4
    lighten background greyness for <pre> to increase contrast

**Comment by graforlock** [comment]
Gray background definitely look better now.

I'd add that <pre> tag background also looks very well and yellowish (close to camelia style?) when put with hex color #fdf6e3, which is solarized light default. Many say its the most readable theme (arguable), but looks nice.

I will post a mock-up for the docs on the weekend. It would mostly be just bringing perl6.org to the docs. I don't want to do anything drastic.

**Comment by gfldex** [comment]
I would be careful with a tinted background for colourful text. About 10% of the population got problems with colour-vision and 1% if outright colour blind. Gimp got a plugin that simulates the effects but doesn't really match reality (I was told, my vision is quite good).

Also, we don't have a proper printable version of the docs, so we have to expect at least some pages to be printed and cheapo printers will mess up coloured backgrounds. Given that we got a frame and a different font for examples already, the background is overkill already.

So, please don't spill fancy ink into the background.

**Comment by gfldex** [comment]
2nd round of small changes

https://github.com/perl6/doc/commit/286320ed86f6c6e678fc07f96cff78ed871bbe98
give h1 a slight top padding to separate it more from the previous 

https://github.com/perl6/doc/commit/8701cfa445a773c9756e19134cc02570b806f139
Headings are links to move to the top, giving them the wrong color. 

https://github.com/perl6/doc/commit/b908f298974c9faf02a3c8304f488e52df572c81
Table headers where missing padding, making them clash with table data. 

https://github.com/perl6/doc/commit/33b2f8098d340ee55e68f56a8fca966205e15a1e
Yellow and black stripes are used by mother nature to indicate stingy
danger. Camelia may be able to bite your head off, pod tables are not. A
light gray zebra table should play better with other
Pod::FormattingCodes when we start to support them in tables.

**Comment by AlexDaniel** [comment]
So what's next? My proposal to create separate issues for every problem did not result in any issues being created (or so it seems), and this issue does not even have a TODO list. There are a bunch of commits dealing with the mentioned issues, so now what?

Without any particular plan there is no reason to keep this open. Please do something if you think there are still some problems with the site.

**Comment by coke** [comment]
There are other tickets in place to address the style of the site; Any particular UI/UX problems should have individual tickets opened (I'm not sure there are any actionable items left in this ticket)

The notes about converting this to be more book like are a big ask, and not something that I think the docs site is necessarily shooting for; (e.g. the request to have book-like sections in order for the user to read.) I think our goal is more class/functional docs, with a small amount of tutorials, at least for now.

In any case, separate tickets for separate things.

Closing this one, thanks.
