### ISSUE TITLE
Add “no space after comma” test

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#666]
This is part of https://github.com/perl6/doc/issues/625, but as other suggestions were implemented, it is probably better to create a separate issue.

See also https://github.com/perl6/doc/issues/624.

Also, this issue is interesting because it requires pod parsing.

**Comment by coke** [comment]
So, we can avoid X<> and code snippets by running the pod6 through perl6 --doc (like we do for xt/aspell.t) - we can skip any code by avoiding any lines that start with 4 spaces there. However, this still leaves lines like this that cause a false positive:

`but in Perl 6 one uses the ',' (comma). For example:`

`value by using ($var,). When used with a variable declarator just providing`

Here's the loop doing the work so far:

```
    for $out.lines -> $line {
        next if $line ~~ / ^ '    '/;
        if $line ~~ / ',' [ <!before ' '> & <!before $> ] / {
            $ok = False; last;
        }
    }
```

**Comment by coke** [comment]
I ended up putting in a bunch of one-shot exemptions to the rule in the test that deal with all the one-offs above (basically the same approach I used on aspell.t)

passing test coming shortly.
