### ISSUE TITLE
Add info about lazy lists and generators (maybe in form of a tutorial)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#667]
This issue is part of https://github.com/perl6/doc/issues/657.

WANTED file had this item:
```
Tutorials:
    * lazy lists and generators
```

**Comment by gfldex** [comment]
Lazy lists are now doced with https://github.com/perl6/doc/commit/03c49a92f6 .

Details how to create them are already provided under gather/take and infix:<...> .
