### ISSUE TITLE
When to use Set/Bag (and *Hash)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#668]
Part of https://github.com/perl6/doc/issues/657:

```
Tutorials:
    * When to use which Set/Bag/*Hash type 
```

Indeed, it is a bit confusing when you start. Is it explained anywhere? While it is possible to understand the difference by reading the docs for each of them separately, it would be nice to have one table or something to demonstrate the difference. It could even be in FAQ.

**Comment by smls** [comment]
This is kind of what the [setbagmix](https://docs.perl6.org/language/setbagmix) document was intended for.

It's rudimentary right now, though.

**Comment by JJ** [comment]
Can someone please re-check if that [`setbagmix`](https://docs.perl6.org/language/setbagmix) description is good enough? If it's not, what would you add? Or where?

**Comment by AlexDaniel** [comment]
Hm. The start of setbagmix page is actually pretty good. I find it hard to read though. Maybe a little bit of **bold** will make it more digestable?

Like:
> If you want to get the contained objects (elements) **without duplicates** and you only care whether an element is in the collection or not, you can use a Set or SetHash. (If you want to get rid of duplicates but still preserve order, take a look at the unique routine for List.)
>
> If you want to keep track of the **number of times each object appeared**, you can use a Bag or BagHash. In these Baggy containers each element has a weight (an unsigned integer) indicating the number of times the same object has been included in the collection.
>
> The types Mix and MixHash are similar, but they also allow **fractional weights**.

**Comment by AlexDaniel** [comment]
FWIW this idea can be used on a lot of texts that are otherwise super boring to read (but have useful info in them).

**Comment by JJ** [comment]
I have seen boldface is rather used for things being defined. Italics is what's used for emphasis here and there. Hope it's OK; if not, feel free to reopen.

**Comment by AlexDaniel** [comment]
The point is not to have emphasis, but to give the eyes something to catch on when skimming. See [WriteForSkimming](https://communitywiki.org/wiki/WriteForSkimming).

**Comment by JJ** [comment]
So right. Changed.
