### ISSUE TITLE
Add Pod6 tutorial

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#669]
Part of https://github.com/perl6/doc/issues/657.

It seems like there no pod6 tutorial yet.

**Comment by tbrowder** [comment]
how about starting with an entry under Language with a copy of S26?

**Comment by gfldex** [comment]
http://perl6intro.com/ is published under CC, what means we can nick it. Would need to be transformed into pod6 tho.

**Comment by gfldex** [comment]
No we can't. The docs are under artistic license and CC does not allow a change of license.
