### ISSUE TITLE
Documentation on ~~ (smartmatching) can be better

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#672]
This issue is part of https://github.com/perl6/doc/issues/657:

```
Syntax features:
    * Smartmatching: ~~, allowed RHS values, backlinks from related docs (grep)
```

While we already have something minimal on https://docs.perl6.org/routine/~~, I think that we can do better.

**Comment by ravaan** [comment]
The mentioned page  https://docs.perl6.org/routine/~~ cannot be found.

Can you please explain what is required .

**Comment by Altai-man** [comment]
@ravaan https://docs.perl6.org/routine/$TILDE$TILDE - here is the correct link.

**Comment by AlexDaniel** [comment]
http://design.perl6.org/S03.html#Smart_matching is pretty good by the way.

**Comment by JJ** [comment]
Now it cannot be found in any way. So now it needs to be *much* better.

**Comment by JJ** [comment]
Or maybe you can include [ACCEPTS](https://docs.perl6.org/routine/ACCEPTS) as its substitute

**Comment by JJ** [comment]
And it looks pretty good now. Can we close this?

**Comment by W4anD0eR96** [comment]
FWIW #1913

**Comment by AlexDaniel** [comment]
Hm OK.
