### ISSUE TITLE
What is KeyReducer?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#673]
This issue is part of https://github.com/perl6/doc/issues/657

```
API docs:
    * KeyReducer
```

What is KeyReducer?

**Comment by jnthn** [comment]
A proposed concurrency construct, that was prototyped with the early concurrency work (implemented on the JVM), but later dropped (it was never ported to Rakudo on MoarVM).

**Comment by AlexDaniel** [comment]
Not a doc issue then.
