### ISSUE TITLE
｢srand｣ not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#674]
This issue is part of https://github.com/perl6/doc/issues/657
```
Functions:
    * srand()
```

We already have it mentioned in https://docs.perl6.org/language/5to6-perlfunc#srand:
> Available in Perl 6.

It is great that it is available, but we should provide some documentation for people who don't use p5.

**Comment by gfldex** [comment]
fixed with 590cf0db8d8e04c2737b934c8efe07ede7131303
