### ISSUE TITLE
｢deepmap｣ not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#676]
This issue is part of https://github.com/perl6/doc/issues/657

```
Functions:
    * duckmap() and deepmap()
```

So what is deepmap? :)

May be related to https://github.com/perl6/doc/issues/675

**Comment by dogbert17** [comment]
gfldex++ has documented deepmap, see d3f2534e6ed5c75fe5864ccf3e40381a688b1c67

**Comment by AlexDaniel** [comment]
Indeed! @gfldex++
