### ISSUE TITLE
`.return` and `.return-rw` methods not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#678]
There looks to be a `.return` (and `.return-rw`) methods [provided by `Mu`](https://github.com/rakudo/rakudo/blob/09cc2fbfcac902dd45af89bca9872f3c354bf4f4/src/core/Mu.pm#L43-L52), but I'm [not seeing it documented](https://docs.perl6.org/type/Mu):

```
$ perl6 -e 'sub f($a) { .return with $a; return "something undef-y" }; say f "foo"; say f Nil'
foo
something undef-y

$ perl6 -e 'Mu.^can("return")[0].signature.say'
(Mu $: | is raw)
```

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/2196187eef
