### ISSUE TITLE
Sometimes shady camelia makes the text harder to read

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#681]
I've never noticed it, but indeed, sometimes it does not look very nice:

![screenshot](https://files.progarm.org/2016-07-08-024940_745x328_scrot.png)

http://irclog.perlgeek.de/perl6/2016-07-07#i_12803812

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/e402f7b04a

**Comment by pmichaud** [comment]
Perhaps just make camelia smaller, rather than remove outright?

**Comment by AlexDaniel** [comment]
Even though it is now closed, just wanted to add this nice screenshot to make the decision more obvious:

![screenshot](https://files.progarm.org/2016-07-09-002003_379x277_scrot.png)
