### ISSUE TITLE
/type/Str contains doc for method Str.val

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#683]
sub val is a sub among methods what may cause the confusion.

**Comment by W4anD0eR96** [comment]
Although how we generate `/routine/*`s can be improved, the very issue has disappeared(?)

Please check it.

**Comment by AlexDaniel** [comment]
> Methods
> …
> …
> sub val

No, that's not resolved.

**Comment by W4anD0eR96** [comment]
Most of we list all routines available below heading "Methods", while someone substitutes it with "Subroutine". It's an issue of doc conventions.

**Comment by JJ** [comment]
What is the issue? Moving the documentation elsewhere?

**Comment by JJ** [comment]
I have been checking [`Int` and it does list routines under Methods](https://github.com/perl6/doc/blob/master/doc/Type/Int.pod6#L54), although it uses the word `routine`, instead of sub. `chr` would be in the same situation as `val` right? Would changing `sub` to `routine` help here?

**Comment by JJ** [comment]
Besides, `Str` itself has several `routine`s

**Comment by JJ** [comment]
And I see there was an attempt to convert to routine which failed for some reason https://github.com/perl6/doc/commit/e66006021d55b8e72b13989cddebebd770ed37c9
