### ISSUE TITLE
invocant is searchable but :D: is not searchable

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#684]
We can see many `:D:`s in the document, for example
```
method params(Signature:D:) returns Positional
```
(Cited from https://docs.perl6.org/type/Signature#method_params )

And there is a description of `:D:` in the following page.
https://docs.perl6.org/type/Signature#Signature_Literals

However I think that the above page doesn't seem to explain the relation between `:D:` and `invocant` explicitly, and associating with the keyword `invocant` just from `:D:` is difficult for users.

**Comment by zoffixznet** [comment]
`:D:` isn't the "invocant". `:D` is a type smiley and `:` is used to demarcate the invocant in the signature, like `($: $, $)`. So there's no such thing as `:D:` as a single item. It can be written as `method params(Signature:D    :    ) returns Positional`

**Comment by gfldex** [comment]
https://docs.perl6.org/type/Signature#Parameter_Separators states:

"As an exception the first parameter may be followed by a colon instead of a comma to mark the invocant of a method."

We can't make readers read better by adding more to read. I will therefor close this ticket.
