### ISSUE TITLE
Need a complete table of operators in addition to current entry in Language

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#694]

**Comment by AlexDaniel** [comment]
What about this: https://docs.perl6.org/routine-operator.html ?

**Comment by tbrowder** [comment]
On Thursday, July 14, 2016, Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> What about this: https://docs.perl6.org/routine-operator.html ?
>
Close, but a copy could probably be modified to fit my idea.

>

**Comment by AlexDaniel** [comment]
So what's your idea exactly?

**Comment by tbrowder** [comment]
On Thursday, July 14, 2016, Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> So what's your idea exactly?
>

Something like this:

Oper | Texas | Description
====+=====+========
++     |    ++    | increment (<link to detailed description and short but
good examples>)

The table page should be found under Languages with a title of Operators.
The table should be divided into the usual categories of boolean, binary,
..., etc. (whatever the correct categories are for Perl 6).

>

**Comment by AlexDaniel** [comment]
@tbrowder can you start it?

**Comment by tbrowder** [comment]
@AlexDaniel I can put it on my Perl 6 TODO list, which is getting longer every day! Do you see this as something that should be done soon?  I'm trapped at the moment with trying to get some more public modules finished, but I can switch priorities if you want.

**Comment by AlexDaniel** [comment]
@tbrowder not really. There are some doc issues that won't move anywhere unless OP does the first step. IMO this is one of them (admittedly, some of them are mine too).

**Comment by tbrowder** [comment]
Thanks. I'll take a look and see what I can do.

**Comment by JJ** [comment]
Would this be it? https://docs.perl6.org/language/unicode_ascii#Other_acceptable_single_codepoints

**Comment by JJ** [comment]
If no one objects, I think that the existing table meets this issue, so I'm closing it.
