### ISSUE TITLE
Links to nextsame, callsame, nextwith and callwith on Metamodel::C3MRO page are broken

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#696]
See https://docs.perl6.org/type/Metamodel$COLON$COLONC3MRO

Example of a link: https://docs.perl6.org/routine/nextsame (404)

However, it is kinda documented here: https://docs.perl6.org/language/functions#index-entry-nextsame-nextsame

**Comment by gfldex** [comment]
The routines in question are not properly defined in any .pod file.

**Comment by gfldex** [comment]
In fact they are not even routines. see https://github.com/rakudo/rakudo/blob/nom/src/core/control.pm#L116

**Comment by gfldex** [comment]
fixed with https://github.com/perl6/doc/commit/e183380aaa59a77c26dc682a95576fe3b5d126cb
