### ISSUE TITLE
“::” in links is replaced with $COLON$COLON, this is too verbose

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#698]
For example: https://docs.perl6.org/type/IO$COLON$COLONSocket$COLON$COLONINET

This makes the link completely unreadable. Maybe we can replace `::` with just `-`? That's what cpan does.

Or, since we are not using windows to host perl.org, maybe we can detect the OS and allow some extra characters?

**Comment by gfldex** [comment]
infix:<:> would become infix:<-> (actually it would be /routine/-.html) what would clash with infix:<-> /what is /routine/-.html). If we replace it with something else, we have to use a char that is not used in any operator name.

We may not be hosting on windows but somebody might want to put the files on a usbstick. What still doesn't work because there is WHAT.html and what.html.

**Comment by titsuki** [comment]
If we can use zenkaku character`：` I think this is a little bit readable than `$COLON`.

For example
```
https://docs.perl6.org/type/IO：：Socket：：INET
```

**Comment by zoffixznet** [comment]
This also breaks the symmetry we have that you can visit `https://docs.perl6.org/type/TYPENAME` and get docs for that type. I frequently do it by hand in the browser, but I see some tools are broken too:

```
<Frameless> huggable: IO::Path
<huggable> Frameless, File or directory path: https://docs.perl6.org/type/IO::Path
```

A bit of out-of-box thinking... why don't we throw in a web app to serve the docs? That'd make the filenames we generate much more flexible. Or we can generate `Rewrite` rules in `.htaccess` to cater sanely-named files from fancy-pants URLs?

**Comment by gfldex** [comment]
The Rewrite rule should work nicely. There is a complete list of links under https://docs.perl6.org/links.txt to test against.

**Comment by zoffixznet** [comment]
I commited a rule that makes `https://docs.perl6.org/type/IO::Path` URLs work. So the concern I raised above is solved.

Not sure about the OP. The Rewrite doesn't change the generated URLs in the actual document. Not sure if that's a problem.

**Comment by AlexDaniel** [comment]
@zoffixznet it is. ``https://docs.perl6.org/type/X$COLON$COLONProc$COLON$COLONAsync`` looks horrifying.

**Comment by W4anD0eR96** [comment]
@AlexDaniel Seems like it's fixed

**Comment by AlexDaniel** [comment]
I don't know what fixed it but you're right.
