### ISSUE TITLE
Huge Number of Spurious Requests Generated

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#699]
There seems to be something that's generating a huge number of reqests when page loads. I get **231** requests generated when visiting [https://docs.perl6.org/type/ComplexStr](https://docs.perl6.org/type/ComplexStr)

This is very problematic for users who pay for their bandwidth or users on slow connections, such as users on mobile and wifi, or users in countries with less speedy Internet.

It looks like it's sending a HEAD request for every link on the page? During the day, I browse from a monitored corprorate network. I don't know the details of the data they gather, but I really wouldn't want them to think I'm vising millions of pages per day, instead of working.

This is also a needless load on our volunteer-donated server.

Here's a run on a regular 2G network simulation. 231 requests, half a meg transfer, and it takes half a minute to load:

![untitled](https://cloud.githubusercontent.com/assets/5747918/16842910/26936aac-49ad-11e6-83d3-08fcb09ed388.png)

**Comment by vendethiel** [comment]
It seems that the JavaScript website tries to detect broken links for every single requests on the docs:

https://github.com/perl6/doc/blob/master/html/js/main.js#L127

**Comment by coke** [comment]
This needs to be removed. We should not be running this check in everyone's browser on every page load.

**Comment by AlexDaniel** [comment]
Related to https://github.com/perl6/doc/issues/697

**Comment by gfldex** [comment]
Cache is in place. It's checking once per commit per page. If the commit changes, the cache is wiped.

**Comment by gfldex** [comment]
fixed with dcab8da86a
