### ISSUE TITLE
in-page always-on 404 checking should not be enabled.

### ISSUE THREAD

**Issue by coke** [perl6/doc#700]
Even with the caching, this should be pushed out to our users and run in JS on page load.

If we want to have solid 404 checking, it should be one of:

- part of the site build (and tested against the local copy)
- part of a standalone script that can be run against either the local copy or the deployed site
- opt in JS that developers/helpers can enable and report.

The recent caching addition makes this ticket a lower priority, but IMO we should still approach this as part of our build process.

**Comment by zoffixznet** [comment]
:+1:

TBH, I'm not sure there's much usefulness to the cache. [Statistically](https://github.com/perl6/doc/pulse) we get a doc commit every hour, so that cache would last just 1 hour.

**Comment by AlexDaniel** [comment]
It was an interesting idea but we just can't do that.

**Comment by gfldex** [comment]
fixed with dcab8da86a
