### ISSUE TITLE
Both infix ⊉ and ⊈ misses exclamation mark in their equivalent syntax

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#702]
See the following pages.
https://docs.perl6.org/routine/⊈
https://docs.perl6.org/routine/⊉

`⊈` is equivalent to ` !(<=)`. However the page title is `infix operator (<=)`.
`⊉` is equivalent to ` !(>=)`. However the page title is `infix operator (>=)`.

**Comment by gfldex** [comment]
the page title reads: "Documentation for infix ⊈"

It is _based_ on infix operator (<=), whereby text is rendered to big. If we change that it will break the layout for method disambiguation files relative to the type they are defined in.

closing this as a) PEBKAC and b) wontfix on the layout issue as it would break plenty of other stuff

**Comment by titsuki** [comment]
@gfldex I see, thanks.
