### ISSUE TITLE
Typo in role IO documentation

### ISSUE THREAD

**Issue by tushardave26** [perl6/doc#703]
Hello Author,

I was going through the role IO {} documentation and found a typo for "read-write" mode for "sub open". The current documentation has 

my $fh = open("path/to/file", :w);

while it should be

my $fh = open("path/to/file", :rw);

I believe, this is a minor error, but can someone please correct it?

Thanks.

-Tushar

**Comment by zoffixznet** [comment]
Thank you. It should be fixed on next build (in about an hour)
