### ISSUE TITLE
Minify Assets / Get Rid of Generated style.css In Repo

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#704]
Currently, we have two issues:
1. Assets are not minified which makes Google like us less and our users download more.
2. We currently store in the repo `style.css` which is an auto-generated file ([reasons](https://github.com/perl6/doc/issues/662#issuecomment-230163285)).

We can solve both of those by including minification and SASS processing as an _optional_ part of the build process that will run as part of the doc generation for docs.perl6.org, but if a contributor builds locally and they don't have prereqs for minification/SASS, they won't get that step run.

To still let users use the dev app without having the SASS-related prereqs, we can add a routes that will fetch the JS/CSS assets from https://docs.perl6.org/ if local versions aren't found.

![z](https://cloud.githubusercontent.com/assets/5747918/16849731/d76fb2d8-49c9-11e6-8006-848542573cca.png)

**Comment by AlexDaniel** [comment]
I have some questions:

1. “Assets are not minified which makes Google like us less” – What does it mean exactly? Does it mean that it affects page ranking?
1. “and our users download more” – How much are we going to win? I mean, what's the size difference after gzip? I am asking because if the difference is really small, then maybe we should not do that. Minified assets complicate micro contributions, so I'd much rather prefer a couple of stuff contributed by random people than tiny amount of saved bandwidth. That being said, if the difference is significant, then indeed we should minify.

**Comment by AlexDaniel** [comment]
Partially answering my own question 2:

Using http://compressorrater.thruhere.net/ I figured that we are going to save about that much:
```
0.4 (main.js) + 0.5 (search.js) ≈ 1 kB (optimistically)
```
So if we minify, then we are going to save about 1 kB for the initial load of js files (subsequent loads should not download these files because of caching). Is it significant? I don't think so. What do others think?

**Comment by AlexDaniel** [comment]
Ah crap! Just looked at the screenshot. :D

**Comment by zoffixznet** [comment]
> “Assets are not minified which makes Google like us less” – What does it mean exactly? Does it mean that it affects page ranking?

Google's algorithm is secret, of course, but failing mobile tests on that assessment page in the screenshot  does rank you lower for mobile viewers—so it's natural to assume failing desktop tests would have similar consequences.

>  “and our users download more” – How much are we going to win? I mean, what's the size difference after gzip? I am asking because if the difference is really small, then maybe we should not do that. Minified assets complicate micro contributions, so I'd much rather prefer a couple of stuff contributed by random people than tiny amount of saved bandwidth. That being said, if the difference is significant, then indeed we should minify.

It's 24.3KB on https://docs.perl6.org/type/ComplexStr page.

What are the complications for micro contributions? The assets will remain **unminified** in the repo. The only penalty for contributors would be extra prereqs when building a local copy of the docs, though even that can be avoided by extra Mojolicious routes ([Coke] is currently -1 on that idea)

**Comment by AlexDaniel** [comment]
> What are the complications for micro contributions?
You can work on small things directly in your browser, without even cloning a repo. If JS is minified, then it is much harder.

That being said, I have nothing against minifying CSS or HTML. So +1 for that, we should do definitely do that.

**Comment by zoffixznet** [comment]
> You can work on small things directly in your browser

You mean using GitHub editor or...?

**Comment by AlexDaniel** [comment]
> [00:44:43] «Zoffix» AlexDaniel, do you mean editing code using GitHub editor or working on the live site using some sort of plugins? RE "You can work on small things directly in your browser, without even cloning a repo."
> [00:47:41] «AlexDaniel» Zoffix: it is possible to change JS in, for example, chromium default developer tools. So yea, I meant doing quick small changes on the live site, and then suggesting them in a github issue or submitting a pull request using the github editor.
> [00:48:04] «Zoffix» OK. I'll leave JS alone

**Comment by coke** [comment]
@zoffixznet  - is there anything left to do on this ticket? if we're skipping minifying, and it looks like the .css is no longer kept int he repo...

**Comment by zoffixznet** [comment]
Oh yeah, everything was done in https://github.com/perl6/doc/commit/54fb4b3bf98e1b4991258fce330efb3bf035361c and other commits around Christmas. I forgot there was an open issue as well.
