### ISSUE TITLE
package the docs for Rakudo Star

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#705]
At some point we will have to do that. Giving the name mangling problems we got already, we may want to start thinking early.

The easy way would be to disable generation of disambiguation and per-class files. This would also mean to get rid of routine.html and type.html.

**Comment by stmuk** [comment]
The docs are shipped with Rakudo Star already so I'm not sure what you
mean...

S



On 14 July 2016 at 19:08, Wenzel P. P. Peppmeyer <notifications@github.com>
wrote:

> At some point we will have to do that. Giving the name mangling problems
> we got already, we may want to start thinking early.
>
> The easy way would be to disable generation of disambiguation and
> per-class files. This would also mean to get rid of routine.html and
> type.html.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/perl6/doc/issues/705>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEUuY_5KVYHPLw0xyEQr19_iNKSIy3ilks5qVnsPgaJpZM4JMsr1>
> .
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by gfldex** [comment]
$ ls -l rakudo-star-2016.04/modules/doc/html

drwxr-xr-x 1 dex dex   66 Jul 14 22:43 css
-rw-r--r-- 1 dex dex 1150 Apr 25 16:57 favicon.ico
drwxr-xr-x 1 dex dex   90 Jul 14 22:43 images
drwxr-xr-x 1 dex dex   86 Jul 14 22:43 js

That's not an awful lot of content. The docs are provided as source, with a build system. If you get it running (tricky process on linux, no idea on windows) it will silently fail on ntfs and hfs+ because there are plenty of case sensitive filenames. You will also need to run a webserver, because pretty much all links are absolute. Many of those absolute paths are hard coded in the individual .pod files.

Your best bet right now is to wget from the live server and ignore the files that can't be written because of case problems. That will get you relative links, what will break the build-in search, because wget can't rewrite the links provided in a .js file.

I'm not entirely sure if all biology students (my count of brave individuals in `#per6` that want to use Perl 6 in conjunction with students of biology is at 4) will get this done in a reasonable time frame.

So if Rakudo is meant to support all platforms equally well, we will have to do some work.

**Comment by gfldex** [comment]
Another complication are links from .pod files to automatically generated files (/type/Foo.html). So we can't even go and leave the generated files be, because that would cause tons of dead links.

**Comment by stmuk** [comment]
Rakudo Star doesn't contain a rakudo-star-2016.04/modules/doc/html
directory you are confusing the github source code for building the distro
with the actual distro itself (look at the target tar.gz we create and
ship).

We ship the perl6 docs in Rakudo Star as the canonical .pod6 form and they
are rendered to the screen using p6doc (this would also work with embedded
pod inside .pm6 type modules if people write this which generally they
don't).  This is exactly how perl 5 works with perldoc. There is some
support for searching pod6 using p6doc as well but this needs more work.

You mean the HTML rendered form which is less useful on the command line. I
don't think we would want to ship the docs twice in pod and html form which
would add dozens of files containing the same content to Star.  Neither are
many people going to be able to read HTML from the command line on a server
(except with something like lynx which would probably handle our HTML
badly).

And as you say there are a lot of problems with the HTML and case sensitive
file systems (also apache redirects) which don't make the use of HTML easy
for people (unless they run a duplicate setup to our servers).  Looks like
our HTML is closely coupled to a particular server setup and not useful
directly for end users (unless its totally rewritten). I think the needs of
an internet web site serving docs and a local setup serving docs are
probably different. Compare perl5's http://perldoc.perl.org/ with
http://search.cpan.org/~beppu/Pod-Server-1.14/lib/Pod/Server.pm

But perhaps one way of using HTML type docs might be to do what
http://perl6intro.com/ does in Star which is to bundle the entire web site
into one PDF file.







On 14 July 2016 at 22:03, Wenzel P. P. Peppmeyer <notifications@github.com>
wrote:

> $ ls -l rakudo-star-2016.04/modules/doc/html
>
> drwxr-xr-x 1 dex dex 66 Jul 14 22:43 css
> -rw-r--r-- 1 dex dex 1150 Apr 25 16:57 favicon.ico
> drwxr-xr-x 1 dex dex 90 Jul 14 22:43 images
> drwxr-xr-x 1 dex dex 86 Jul 14 22:43 js
>
> That's not an awful lot of content. The docs are provided as source, with
> a build system. If you get it running (tricky process on linux, no idea on
> windows) it will silently fail on ntfs and hfs+ because there are plenty of
> case sensitive filenames. You will also need to run a webserver, because
> pretty much all links are absolute. Many of those absolute paths are hard
> coded in the individual .pod files.
>
> Your best bet right now is to wget from the live server and ignore the
> files that can't be written because of case problems. That will get you
> relative links, what will break the build-in search, because wget can't
> rewrite the links provided in a .js file.
>
> I'm not entirely sure if all biology students (my count of brave
> individuals in #per6 that want to use Perl 6 in conjunction with students
> of biology is at 4) will get this done in a reasonable time frame.
>
> So if Rakudo is meant to support all platforms equally well, we will have
> to do some work.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/perl6/doc/issues/705#issuecomment-232791721>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEUuY0LKO_XuXRlJnwsmpsKUCVaan16dks5qVqQdgaJpZM4JMsr1>
> .
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by JJ** [comment]
Are we going to do something about this? Create a single downloadable zip file, perhaps? Wouldn't pointing to this site and instructions to create it be enough?

**Comment by stmuk** [comment]
The docs are shipped with Rakudo Star. See my comment above.

**Comment by JJ** [comment]
I'm closing this now then.
