### ISSUE TITLE
S26 is 404

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#709]
While one might argue that it is a [spec repo](https://raw.githubusercontent.com/perl6/specs) issue, links that are 404 is definitely a doc issue.

Given that there are reoccurring issues with S26, maybe we should point to a [raw file](https://raw.githubusercontent.com/perl6/specs/master/S26-documentation.pod) instead?

**Comment by tbrowder** [comment]
On Fri, Jul 15, 2016 at 1:23 PM, Aleks-Daniel Jakimenko-Aleksejev
<notifications@github.com> wrote:
> While one might argue that it is a spec repo issue, links that are 404 is definitely a doc issue.
> Given that there are reoccurring issues with S26, maybe we should point to a raw file instead?

Until we fix pod6 parsing limitations, I agree with pointing to the raw file.

**Comment by Altai-man** [comment]
Raw pod/6 is a bit tough to read and we have tons of links to S26. Even if it will wipe out a big part of checklink output for now, it is still somewhat strange to replace all links now and replace all links again later.
What is the state of current pod6 parsing, by the way?

**Comment by AlexDaniel** [comment]
S26 is OK now. We can close this.
