### ISSUE TITLE
Convert TODO items to github issues

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#712]
Similarly to https://github.com/perl6/doc/issues/657.

See https://github.com/perl6/doc/blob/master/TODO

**Comment by Altai-man** [comment]
https://github.com/perl6/doc/issues/715, https://github.com/perl6/doc/issues/716, https://github.com/perl6/doc/issues/717, https://github.com/perl6/doc/issues/718 - does it all or "Maybes" should be opened?

**Comment by AlexDaniel** [comment]
I think that it does not hurt to open maybes too.

**Comment by Altai-man** [comment]
Closed with https://github.com/perl6/doc/issues/720, https://github.com/perl6/doc/issues/721, https://github.com/perl6/doc/issues/722
