### ISSUE TITLE
Make type-graph.txt support more fine-grained metainfo

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#715]
...perhaps using a TOML-like syntax, and use this for grouping.

This issue is a part of TODO.

**Comment by JJ** [comment]
What would this solve or help?

**Comment by Altai-man** [comment]
I imagine that original purpose was to extend existing `type-graph.txt` to do e.g. types grouping(not sure what was the meaning here, to be honest). In case of relation database usage, this wont be necessary as you can tune things on table/query level.

**Comment by JJ** [comment]
Sounds like a +1 for closing...

**Comment by Altai-man** [comment]
Re-open if needed.
