### ISSUE TITLE
More metadata for Language/ and for routines

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#716]
This issue is a part of TODO.

**Comment by JJ** [comment]
Not sure what this means either. Metadata added to the page headers?

**Comment by JJ** [comment]
What kind of metadata do you mean here? Does anyone remember the context for this issue?

**Comment by Altai-man** [comment]
Unfortunately, no clue. I see https://github.com/perl6/doc/commit/9f1b25cea91891258bd40759929e3e308e838baf#diff-b7b1e314614cf326c6e2b6eba1540682, not sure if @Mouq can advice us something after four years.

**Comment by JJ** [comment]
I'm afraid I'll have to close this. If anyone can clarify what it means, please open it back.
