### ISSUE TITLE
Handle enum types specially in type graphs

### ISSUE THREAD

**Issue by smls** [perl6/doc#72]
In our type graphs, enum types like `PromiseStatus` are currently rendered like normal subtypes of their value type: http://doc.perl6.org/images/type-graph-Int.png

This can create confusion.

We should review all built-in enum types and then decide which of the following solutions is better:
- render enum types differently from classes
- exclude enum subtypes altogether from type graphs of class types

**Comment by moritz** [comment]
We should do both, IMHO. Render them differently from roles and classes, and only show them in the type graph of the enum itself.

**Comment by AlexDaniel** [comment]
I think this can be closed for now. Please open a new issue if any further improvements are desired.
