### ISSUE TITLE
Add "Formalities" page

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#720]
This issue is a part of TODO.

**Comment by coke** [comment]
This was added by Mouq - I don't know what a Formalities page consists of.

**Comment by Altai-man** [comment]
Then we need to cast him here or close the issue.

**Comment by AlexDaniel** [comment]
@Mouq ?

**Comment by Mouq** [comment]
Howdy. This was a TODO from Smls' [original site redesign](http://imgur.com/a/y1dHo). A better name might be "About" or similar.

**Comment by Altai-man** [comment]
I think, we don't need to create another page, since we already have `about.html`. We'd better add necessary things to `About` page and this issue can be closed.

**Comment by coke** [comment]
We don't have a list of what those things are; closing this ticket as too vague. Mouq, feel free to open a new one with specifics.
