### ISSUE TITLE
Make links automatically be formatted super pretty, as with "language>intro"

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#721]
This issue is a part of TODO.

**Comment by JJ** [comment]
Not clear what you mean here...

**Comment by AlexDaniel** [comment]
I think the idea was that things like ``L<say>`` would automatically be displayed as ``routine>say``, or something like that. IMO if no better explanation is given we can reject this, because most of the text actually expects the name to be displayed as-is without any category.

**Comment by JJ** [comment]
No clarification here, so I'm closing this.

**Comment by JJ** [comment]
I've clarified that a bit. Of course you did. Thanks.
