### ISSUE TITLE
A PDF version of the documentation

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#722]
This issue is a part of TODO.

**Comment by AlexDaniel** [comment]
I think we can reject this for now. There's really no killer feature in PDFs that would make us want to provide the documentation in that format. Anyone who *really* needs it can go to https://docs.perl6.org/perl6.xhtml and print it to file. Takes less than a minute and you get 5M file with 625 pages. Not too bad. It's totally readable although the font size is a bit too small maybe. Potentially we can provide some extra css rules for printing and that would make these PDFs even nicer, but please open a new issues for these things.
