### ISSUE TITLE
Callable: infix:<∘> docs claim both args must have arity 1

### ISSUE THREAD

**Issue by ajs** [perl6/doc#727]
Test case:

`$ perl6 -e 'my &mulneg = &prefix:<-> ∘ &infix:<*>; say mulneg(3, 4)'`

output:

`-12`

I think the docs should read:

The function combinator `infix:<∘>` or `infix:<o>` combines two functions of arity one and one or more, so that the left function is called with the return value of the right function.

**Comment by dogbert17** [comment]
Shouldn't it be 'zero or more' instead of 'one or more'?

sub f($p){ say 'f'; $p / 2 }
sub g(){ say 'g'; 4 }
my &f-g = &f ∘ &g;
say f-g();

**Comment by b2gills** [comment]
Actually the left one has to accept 1 or more, and the right one can accept any amount

    ( -> $_, $ { .say } o ->{ 'Empty',2 } )()

**Comment by gfldex** [comment]
fixed with 8c1b577279
