### ISSUE TITLE
Index Links Broken

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#736]
Recently a feature was added where *Reference* type links would point you directly to the `X<>` thing in the text. Now the URLs look weird and the anchor no longer seems to point to anything.

Sample for when searching for `throws-like`: https://docs.perl6.org/language/testing#index-entry-throws-like-throws-like%28%24code%2C_%24expected-exception%2C_%24description%3F%2C_*%2525matcher%29

**Comment by gfldex** [comment]
that's fallout from https://github.com/perl6/Pod-To-HTML/commit/6131c1aa95ee98aea8470af08d688c478f36407c
It should take \@indices if there is something in it or \$index-text but not both, for the example provided. I'm pretty sure fixing this will break something else.

**Comment by gfldex** [comment]
Also BigPage is doing it correctly so it's not the .pod6 for sure. see https://docs.perl6.org/perl6.xhtml#throws-like

**Comment by zoffixznet** [comment]
It seems this was actually just a very unlucky search term for me, because all the other index links work. Also, I tested in all browsers we support and it looks like only Firefox has issues with it.
