### ISSUE TITLE
Add Test.pm6 routine reference

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#737]
With pretty much all of our types you get [a nice list](https://docs.perl6.org/type/Date) of method names in the ToC. This is very handy if you've already used a feature in the past and just want a refresher on what the method/sub is called.

That's not the case with our [Test functions](https://docs.perl6.org/language/testing.html). If I can't remember the spelling, I have to read through section names in the ToC, trying to figure out which one the sub I'm looking for is under and then read through the prose to find the subs. Is it `eval-throws-like`, `exception-is`, or `throws-like`? `skip-rest`, `skip-all`, or `SKIP-ALL`? `bail-out`, `bailout`, or `BAIL-OUT`?

It would be handy if the page included a section with a reference list of all subs, potentially linking to text describing them. Like

------

#### Reference

* `ok` — test value is true
* `is` — test value equals to
* `like` — test value matches regex
* `throws-like` — test exception thrown by block or evaled string matches

... etc.

----

And on a related point. To me it feels [https://docs.perl6.org/language/testing.html](https://docs.perl6.org/language/testing.html) should be split up into two documents:

1. A testing tutorial that shows a few testing features, how to group and skip tests, etc; aimed at people new to testing.
2. A Test.pm6 technical reference document that lists all the testing subs, their signatures, and brief description—just like our docs for Types. (And the ToC of this document would be the solution this Issue).

Right now the two seems to be intertwined, so you're overwhelmed with the material if you're just learning testing, and at the same time drowned in prose when you just want a quick reference.

**Comment by tbrowder** [comment]
On Wednesday, August 17, 2016, Zoffix Znet <notifications@github.com> wrote:

> Closed #737 <https://github.com/perl6/doc/issues/737> via b6cb311
> <https://github.com/perl6/doc/commit/b6cb311c1e4aa54b564a0074f569b360215e0306>
> .
>
Very nice!

>
