### ISSUE TITLE
Create language/history page

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#740]
Inspired by this recent conversation: http://irclog.perlgeek.de/perl6/2016-07-22#i_12884638

Also can be considered part of https://github.com/perl6/doc/issues/728

**Comment by JJ** [comment]
This is a duplicate of #1000, which is already closed. So closing it too.

**Comment by AlexDaniel** [comment]
Oh wow… the amount of duplicates I created is amazing. More so given that I'm usually the author of both tickets :joy:
