### ISSUE TITLE
Make Trailing Whitespace Tests Optional

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#745]
As per [IRC conversation](http://irclog.perlgeek.de/perl6/2016-07-22#i_12890292), opening this ticket to suggest making trailing whitespace tests optional.

The reasoning is they often break builds and require contributors to spend time unbreaking them, even though the presence of an occasional trailing whitespaces isn't as detrimental to justify paying such a price.

In an ideal world, there'd be some block that'd prevent a commit from entering if it has trailing whitespace. In a less ideal world, there'd be an automated service unbreaking commits with such breakage. And the last option is to disable the test altogether and learn to live with trailing whitespace.

**Comment by AlexDaniel** [comment]
Personally, I am happy with this test. It went much smoother than I thought it would. In the end, I think, most contributors configured their editors to either show trailing whitespace or strip it automatically.

Those who didn't probably use ``make test`` as part of their workflow, which is good also.

This, however, cannot be said about edits made via GitHub. Indeed, that is a problem.

So while I don't mind the test becoming optional, I don't really understand what we should do next.
* Should we leave trailing whitespace mess as is?
* Should we clean it up periodically?
* Should we write a bot that will do that automatically?
* … ?

**Comment by zoffixznet** [comment]
> Should we write a bot that will do that automatically?

IMO that seems the simplest solution. Could be a simple bash script that runs on hack in a cron job.

**Comment by AlexDaniel** [comment]
So should this test be turned off for travis only (making local ``make test`` fail by default) or should we just rely on the bot completely?

**Comment by AlexDaniel** [comment]
As for the bot, I can do that.

**Comment by zoffixznet** [comment]
Yeah, turning of for travis only is the best, I think. This way if a contributor has a chance to run make test, they can spot the issues before committing.

**Comment by coke** [comment]
Resolved in 4aee722 - 'make test' now skips whitespace test. 'make xtest' runs everything.
