### ISSUE TITLE
“«» quotes are used as an alternative to double quotes” – what?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#755]
From [language/unicode_entry#Guillemets](https://docs.perl6.org/language/unicode_entry#Guillemets):
> These characters are used in French and German as quotation marks. In Perl 6 they are also used as quotation marks (in POD as an alternative to the angle brackets and in normal code **as an alternative to double quotes**)

Am I reading it correctly? Maybe not, because otherwise it is some nonsense.

**Comment by gfldex** [comment]
They can be used as an alternative to "" because .Str on a list of Str will coerce by .join(" "). The interpolation rules are the same.

**Comment by AlexDaniel** [comment]
… That does not count as an alternative. Just because a list will stringify into something that looks similar to the original code does not justify having that in the docs.
```perl6
«five     spaces».Str.say     # five spaces
```

**Comment by gfldex** [comment]
In that case it's wrong and needs to be removed.

**Comment by gfldex** [comment]
fixed with ac60df05f8
