### ISSUE TITLE
Solidify and document META6.json content

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#764]
We need to solidify what should be inside META6.json file, what format everything is, and what is optional and what is mandatory—and that should be well documented.

Based on [this IRC conversation](http://irclog.perlgeek.de/perl6/2016-07-26#i_12910337), what goes into META6.json is a bit muddy at the moment.

Based on [ugexe's comments](http://irclog.perlgeek.de/perl6/2016-07-21#i_12882031), the currently described [S22 META6.json](http://design.perl6.org/S22.html#META6.json) is up-to-date, except for what the `resources` property takes.

The properties we list in [the documentation](https://docs.perl6.org/language/modules#Distributing_Modules) however are different. I think they talk about the old `resources` format and they still mention no-longer specced `source-url` key.

The new alternative for `source-url` is `"support: { "source": ...`. However, only 26 modules out of 680 actually use it. Worse, it's specced as optional, however, [panda will die](https://github.com/tadzik/panda/blob/04a9c3d50ba0f976b81756be6c9e4c6b73296bf6/lib/Panda.pm#L136-L139) if it cannot find either `source-url` or `support.source` and from what I recall, the modules.perl6.org dist builder [will also have issues](https://github.com/perl6/modules.perl6.org/blob/master/lib/ModulesPerl6/DbBuilder/Dist/Source.pm#L55) with dists that lack any source URLs in META.

So part of this Issue would be either changing the spec and making some kind of source URL mandatory or fixing our tooling. 

My suggestion would be to go with least resistance and remove optional `support.source` property while adding a mandatory `source-url` property.

**Comment by zoffixznet** [comment]
Some potential fixes:
```
13:58 	unmatched} 	Then we just need to fix the tools that explode when no URLs are given
13:58 	ugexe 	the ecosystem could refuse to index them
13:58 		source-url could be seen as an ecosystem related meta6 extension
``

**Comment by AlexDaniel** [comment]
All modules without source-url:
```
https://raw.githubusercontent.com/zoffixznet/perl6-Pastebin-Shadowcat/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Pastebin-Gist/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-App-Nopaste/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Color/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-IRC-Client/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-WWW-Google-Time/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Lingua-Conjunction/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Number-Denominate/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-IRC-Client-Plugin-HNY/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-IRC-Client-Plugin-Factoid/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Test-Output/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-IO-MiddleMan/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Inline-Brainfuck/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-String-Quotemeta/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Acme-Anguish/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Config-From/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Quantum-Collapse/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-Pretty-Topic/master/META6.json – no source-url
https://raw.githubusercontent.com/zoffixznet/perl6-RT-REST-Client/master/META6.json – no source-url
https://raw.githubusercontent.com/masak/tardis/master/META.info – no source-url
https://raw.githubusercontent.com/masak/007/master/META.info – no source-url
https://raw.githubusercontent.com/skids/perl6xproto/master/META6.json – no source-url
https://raw.githubusercontent.com/skids/perl6-Control-Bail/master/META6.json – no source-url
https://raw.githubusercontent.com/johnspurr/Lingua-EN-Stem-Porter/master/META6.json – no source-url
https://raw.githubusercontent.com/scovit/perl6-IRC-Async/master/META6.json – no source-url
https://raw.githubusercontent.com/Altai-man/perl6-Text-Tabs/master/META6.json – no source-url
```

**Comment by Altai-man** [comment]
I've fixed last module. But I personally :+1: the idea about providing a common pattern for `META6.json` file, since inconsistency is not good.

**Comment by AlexDaniel** [comment]
Did we already decide what counts as “fixing”?

**Comment by AlexDaniel** [comment]
Like, there are currently 680 modules. If we decide that ``"support: { "source":`` is the way to go, then the amount of new modules will be like 2000 in the next, say, 2 years, meaning that even if existing modules don't switch to the recommended method, the majority of modules will be doing it right.

I don't think that the method of least resistance has any significant benefits on this stage. I'd much rather prefer solution that we can call “right” for many years to come.

**Comment by zoffixznet** [comment]
> Did we already decide what counts as “fixing”?

So far the conversation reached this: `support.source` is the specced **optional** field and `source-url` is the ecosystem *extension* that is **mandatory**, unless `support.source` is specified.

However, the source-url for all currently-added ecosystem modules can be derived from the META file URL, so I'd fix panda (and ufo, if it needs fixing) and that will let us consider `source-url` as vestigial leftover and when adding a module to our ecosystem no explicit URL will be required in the metafile

**Comment by zoffixznet** [comment]
Actually, we may not even need to fix panda, but rather ensure the [ecosystem generator panda uses](https://github.com/perl6/ecosystem/blob/master/server/updatelist.pl) fills in a `support.source` if both it and source-url are missing from the metafile

**Comment by JJ** [comment]
Can someone check if META6.json is solid enough? Either that, or totally melted. It's been two years...

**Comment by AlexDaniel** [comment]
I guess it's more about this section: https://docs.perl6.org/language/modules#index-entry-META6.json-META6.json
I don't know if that example is modern enough.

**Comment by JJ** [comment]
`support.source` has been eliminated. Looks consistent with what it said it had to be done. On the other hand, compared with [modern `META6.json`](https://github.com/softmoth/p6-Template-Mustache/blob/master/META6.json) it lacks lots of things, like `auth` or `support`

**Comment by AlexDaniel** [comment]
That should be done then to close this issue (perhaps ask on #perl6 if `auth` and `support` are actually intended to exist and were not just made up by a particular module author).

**Comment by JJ** [comment]
[`auth` is definitely here to stay](https://github.com/araraloren/perl6-terminal-table/blob/master/META6.json). Don't know about the rest. That particular META6.json is even bigger, also.

**Comment by AlexDaniel** [comment]
@JJ see also this: https://irclog.perlgeek.de/perl6-dev/2018-03-18#i_15935872

**Comment by W4anD0eR96** [comment]
https://perl6advent.wordpress.com/2016/12/16/day-16-the-meta-spec-distribution-and-compunitrepository-explained-ish/

though it might somewhat out of date
