### ISSUE TITLE
“Is there going to be a Perl 6 version 6.0.0?” – the question is weird, the answer is even weirder

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#769]
First of all, keep in mind that it is pretty much the start of our FAQ, so let's make it completely right.

> Is there going to be a Perl 6 version 6.0.0?

Why would anybody ask this question? I think that this question can only be asked if it was not released yet, but it is. Maybe my non-native ear does not get it right, but I think the question itself should make it clear that we had a release. Something like “Why the first language release is called v6.c and not v6.0.0?”.

> It was first implemented by the Rakudo Perl 6 compiler version 2015.12 and is **likely to be supported** by subsequent releases for the foreseeable future by use of the 'use 6.c' pragma**..**

Likely to be supported? We had 7 releases after 2015.12, let's have some definite answer. I know that the situation with v6.c/v6.d is a bit unclear, but it does not mean that we cannot doc the current situation.

Also, two dots on the end.

**Comment by stmuk** [comment]
People have asked this question about 6.0.0 and will continue to ask it.  It's not an unreasonable question since many people are likely to be confused by the release versioning.

I don't see any problem with "is likely to be supported".

Neither do I find opening tickets talking about "wierd" questions and answers helpful.

**Comment by coke** [comment]
In some cases, the author of the FAQ makes up the questions that they think will need to be answered - in this case, the 6.0.0 question was literally a FAQ.

**Comment by coke** [comment]
There's no explicit dates there because we literally do not know how long we will ship compilers that support v6.c.

However, to clean things up a bit, I would suggest replacing this

> It was first implemented by the Rakudo Perl 6 compiler version 2015.12 and is likely to be supported by subsequent releases for the foreseeable future by use of the 'use 6.c' pragma..


with

> v6.c of the specification was first implemented by the Rakudo Perl 6 compiler version 2015.12. When there are new versions of the specification (no release date is set yet), the goal is for a single compiler to be able to switch between versions with the use directive. For example, a future release of Rakudo will allow you to switch between v6.d and v6.c. (Note that support for v6.c may eventually be removed)

**Comment by stmuk** [comment]
690d83d0f132cc0f7e29a378f368640c7e912b1b
