### ISSUE TITLE
“As a Perl 6 beginner what should I install?” – various stuff

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#770]
> As a Perl 6 **beginner** what should I install?

> […] download Rakudo Star and install via compilation (**a simple process**)

Yea, right. Well, not that it is wrong, but what about rakudobrew? Or are there any instructions we can link to? We can definitely provide some useful information here.

EDIT: A-ha! Next question (well, it is not even a question) is ``As an intermediate to advanced user I want to track Rakudo development.``, and the answer is to use rakudobrew. So, did I get it right that as an advanced user you can just run rakudobrew and it will install everything for you, but as a beginner you have to compile it yourself somehow, and surely you can figure out how to do that yourself? ;)

> If you are a Windows 32 or 64 bit user then Rakudo Star **binaries** are also available at the rakudo site.

Binaries? What binaries? Does .msi count as a binary?

> To use panda (see below) to install library modules you will need git and Perl 5's Test::Harness.

“see below” – where? 5 questions below this answer are about something else. Sure, it talks about [faq#Modules](https://docs.perl6.org/language/faq#Modules), but let's add a link or something.

> There should be Linux and Mac binaries available shortly from vendors and third parties. Although vendor versions may be outdated.

“Shortly”! OK, debian testing [has up-to-date rakudo](https://packages.debian.org/search?keywords=rakudo), perhaps we can say that one can use rakudo from debian testing, and that the next debian stable release will include it.

**Comment by stmuk** [comment]
Rakudobrew isn't intended for beginners and it would be a mistake to recommend it to beginners. Beginners are intended to use Rakudo Star as binaries. I don't understand why you think rakudobrew would "install everything for you". Do you mean "panda"?

Yes .msi is a binary distribution.

I'm rather not see links since these aren't much use in the text form displayed by "p6doc" and only work on the web.

I don't think we should recommend specific vendor binaries since vendor binaries haven't worked well for perl 5.  It's probably just enough to say they exist.

**Comment by AlexDaniel** [comment]
> Beginners are intended to use Rakudo Star as binaries. I don't understand why you think rakudobrew would "install everything for you".

You are right, but we also have to get our docs (and not only docs) right. If we look at http://rakudo.org/how-to-get-rakudo/#Installing-Rakudo-Star, then it says that ``it is highly recommended that you install from source``, and when you go to ``Building from source`` and it will tell you to use rakudobrew…

And indeed, I've always thought that rakudobrew is much more convenient. “Oh no, I found a bug! Great, the bug was fixed in 10 minutes after my report, I'll just run ``rakudobrew build moar`` and that's it``. But that's just me.

Also, rakudobrew provides very clear instructions on what to do to get everything in your PATH, which is why I thought that it might suit beginners better. You're right, if we want people to use Star, then there's probably no reason to mention it here (especially given that the next question covers it).

That being said, there are no clear instructions on what to do if you want to install Star. Maybe we can write a straightforward up-to-date instructions on rakudo wiki, and then provide a link to that page on FAQ?

> Yes .msi is a binary distribution.

Great, so we should say that you should download .msi for that. *(Basically, I care about stuff like this: as a six year old girl who has only been using GNU/Linux, will I find such instructions clear? How would I know that .msi is what I need?)*

> I'm rather not see links since these aren't much use in the text form displayed by "p6doc" and only work on the web.

Good point actually! I agree. Now what do we do with the rest of the docs? I think that there are many links like this…

> I don't think we should recommend specific vendor binaries since vendor binaries haven't worked well for perl 5. It's probably just enough to say they exist.

OK. Fair enough.

**Comment by stmuk** [comment]
> That being said, there are no clear instructions on what to do if you want to install Star. Maybe we can write a straightforward up-to-date instructions on rakudo wiki, and then provide a link to that page on FAQ?

Personally I think most of the pages on rakudo.org aren't that useful being wordy, outdated and difficult to update via Wordpress (but this probably out of scope for this perl6/doc issue). The Star installation instructions are clearer at

http://www.perl6.org/downloads/

**Comment by b2gills** [comment]
I think that for now it might be a good idea if it mentioned that the user should make sure that vendor provided binaries support at least `v6.c` by running `perl6 -e 'use v6.c'` or  
`perl6 -e 'say q[too old] if $*PERL.version before Version.new(q[6.c])'`

**Comment by stmuk** [comment]
Thanks b2gills!

0ea7b20a11348e33823b0476de7b0a938b4c5a37
