### ISSUE TITLE
“It is the measure of how complete a Perl 6 implementation is.” – OK, so how complete is rakudo?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#772]
> **What is the Perl 6 spec?**
> 
> The "spec" refers to the official test suite for Perl 6. It's called roast and hosted on github. It is the measure of how complete a Perl 6 implementation is.

Well, my next question after reading this is “So is Rakudo complete? If not, how complete is it?”. And if we can't really say, then what kind of a measure is that?

Actually, “the measure of how complete a Perl 6 implementation is” sounds like some marketing blurb.

We have a much better description [in our glossary](https://docs.perl6.org/language/glossary#index-entry-roast), can we use it instead?

**Comment by stmuk** [comment]
Yes I think the glossary description is better in this case.

**Comment by LLFourn** [comment]
I think I wrote the above sentence. Just to answer the question:

> Well, my next question after reading this is “So is Rakudo complete? If not, how complete is it?”. And if we can't really say, then what kind of a measure is that?

Yes. It's complete in so far as it passes the spec. The completeness of an implementation can be measured as the % of tests it passes for any given version of the spec (6.c, 6.d) on any given platform.

Having said that, I have no strong feelings. Feel free to change it :)

**Comment by coke** [comment]
I don't think the roast definition in the glossary helps answer that question. I ended up rewriting it slightly to avoid the issue.
