### ISSUE TITLE
“Go there, find that thing, and then click on the link” – just provide a link, it's easier

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#773]
> I'm a Perl 5 programmer. Where is a list of differences between Perl 5 and 6?

> See the pod with the 5to6- prefix under https://docs.perl6.org/language.html

Let's just say “See [language/5to6-nutshell](https://docs.perl6.org/language/5to6-nutshell)”.
However, we should also provide a link to https://docs.perl6.org/language/rb-nutshell, perhaps requires some rewording in the question.

Now, this does not really tell about other 5to6 documents. I think that 5to6-nutshell page itself should provide these links on the top, so that we can point any Perl 5 user to that page and eventually he/she will find everything needed.

**Comment by stmuk** [comment]
718e0584f571d4a5147894abed6f341638d233f0
