### ISSUE TITLE
remove method entries saying "Perl 6 does not have ..."

### ISSUE THREAD

**Issue by coke** [perl6/doc#777]
I understand the original intent was to direct perl 5 users, but we have the p5-p6 pages for that.

Str has many of these.

**Comment by Altai-man** [comment]
Maybe I missed something, but using grep I was able to find only three lines like this. Closed with https://github.com/perl6/doc/commit/dacb35d02496bb94dabac4555d00eaaa187dc5e0?

**Comment by Altai-man** [comment]
I suppose, it can be closed. Please, reopen if needed.
