### ISSUE TITLE
“Source files generally use the standard .pm extension, and scripts or executables use .pl.”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#778]
From [modules#Basic_Structure](https://docs.perl6.org/language/modules#Basic_Structure):

> Source files generally use the standard .pm extension, and scripts or executables use .pl. However, if you wish to highlight that the file is written in Perl 6 you can use the .pm6 extension for modules, and the .p6 extension for scripts. Test files still use the normal .t extension.

This is no longer true. Or so it seems. Here are some stats from the whole ecosystem:

```
$ files=(**/*.pm6); echo "${#files[@]}"
1907
$ files=(**/*.pm); echo "${#files[@]}"
1248
$ files=(**/*.pl6); echo "${#files[@]}"
143
$ files=(**/*.pl); echo "${#files[@]}"
110
$ files=(**/*.p6); echo "${#files[@]}"
193
```

**Comment by gfldex** [comment]
On windows the shebang is ignored and there is no magic file. The only thing that counts when it comes to decide to call perl.exe or perl6.exe is the file ending. If we want to support windows, we have to use .p6. Modules are not a big issue but for sake of consistency we should make a difference too.

**Comment by molecules** [comment]
Let's recommend "p6" to avoid confusion with the sister language Perl 5.

**Comment by coke** [comment]
+1 molecules' comment to recommend .p6, or this one to recommend .pl6

**Comment by jonathanstowe** [comment]
As a matter of interest does the windows rakudo installer have the facility to create the association?  Or alternatively is there something in the ecosystem that would allow for the creation of the association which could be used by module installers?  If not then either the details of how to do this should be documented somewhere, or all of this is somewhat academic.

**Comment by coke** [comment]
Updated the doc text to also reference .pl6 and windows compatibility, and opened a ticket on the star project to track the installer issue.

**Comment by AlexDaniel** [comment]
The doc still says “Source files generally use the standard C<.pm> extension, and scripts or
 executables use C<.pl>.”, it has to be changed to ``.pm6`` and ``.p6``. Because that's what most use, *generally*.

**Comment by AlexDaniel** [comment]
And the hidden message of whole paragraph is that Perl 6 is the next version of Perl 5, and not a completely new language which is what we were trying to push so much lately.

“However, if you wish to highlight that the file is written in Perl 6 you can use the ``.pm6``”, well, then what ``.pl`` extension is for? To suggest that it is “perl” and bring even more confusion to the whole perl5/perl6 problem? Please let's fix this…

**Comment by Altai-man** [comment]
@AlexDaniel, if the paragraph is wrong, why can't we change it to just some nice and clean "The extension of X is Y, etc"? Seems like a LHF.

**Comment by AlexDaniel** [comment]
@Altai-man yea, it's not *too* hard for sure.

**Comment by coke** [comment]
Given the discussion, removing the LHF tag. I think this is more of a "what is the right answer" than "make this simple subst."

**Comment by AlexDaniel** [comment]
This question seems to be settled now. See https://irclog.perlgeek.de/perl6/2017-12-03#i_15525555

Basically, even though the docs suggest (“Source files generally use the standard .pm extension, and scripts or executables use .pl”) other extensions, .p6 and .pm6 are winning:
> \<moritz\> data from perl6-all-modules: .p6 346 vs .pl 198 vs .pl6 310
> \<moritz\> pm6 2861 vs pm 1488

So at this point it *is* a simple subst.

**Comment by pprince** [comment]
+1 vote for recommending ".p6" and ".pm6" in docs, and removing references to ".pl" and ".pm".

It probably sense, though, for the Windows installer to associate both ".p6" _and_ ".pl6" to Rakudo, yeah?

**Comment by AlexDaniel** [comment]
Yeah.

**Comment by JJ** [comment]
Agree on that too.

**Comment by jnthn** [comment]
Agree on recommending ".p6" and ".pm6" too.
