### ISSUE TITLE
Perl 6 docs don't mention pragmas in a doc search

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#784]
Moved from [RT#128801](https://rt.perl.org/Ticket/Display.html?id=128801). No message body was provided.

**Comment by MasterDuke17** [comment]
Is this a duplicate of #752?

**Comment by zoffixznet** [comment]
Yup. Thanks.

**Comment by tbrowder** [comment]
On Mon, Aug 1, 2016 at 12:02 PM, Zoffix Znet <notifications@github.com>
wrote:

> Yup. Thanks.
>
>
​Sorry, rt.perl is still not working well for me.​
