### ISSUE TITLE
Int/Real.rand is ambiguous

### ISSUE THREAD

**Issue by ajs** [perl6/doc#787]
At: https://docs.perl6.org/type/Int#routine_rand

The docs use the word "between" without clarifying the endpoint behavior. This should probably be made explicit. I went digging for the exact code, but ended up getting lost at the point that nqp doesn't actually reference where rand comes from. I'm assuming it's built into the behavior of Nums somewhere, but I was unable to find it immediately. My assumption would be that it's a real between 0 (inclusive) and n (non-inclusive).

**Comment by timo** [comment]
you can check these pieces of code:

https://github.com/MoarVM/MoarVM/blob/master/src/io/procops.c#L1138  
https://github.com/MoarVM/MoarVM/blob/master/src/math/bigintops.c#L888  
https://github.com/MoarVM/MoarVM/blob/master/src/core/interp.c#L3602  
https://github.com/MoarVM/MoarVM/blob/master/src/core/interp.c#L3892  
https://github.com/MoarVM/MoarVM/blob/master/src/core/interp.c#L3363  
https://github.com/MoarVM/MoarVM/blob/master/3rdparty/libtommath/bn_mp_rand.c  
https://github.com/MoarVM/MoarVM/blob/master/3rdparty/tinymt/tinymt64.c  

somewhere around there you should be able to hit paydirt.

**Comment by zakame** [comment]
Just checked now, if I'm reading this right it ought to be on https://github.com/MoarVM/MoarVM/blob/master/3rdparty/tinymt/tinymt64.c#L113

```c
/**
 * This function outputs floating point number from internal state.
 * This function is implemented using multiplying by 1 / 2^64.
 * @param random tinymt internal status
 * @return floating point number r (0.0 <= r < 1.0)
 */
```

So I suppose @ajs is right?  I can update the doc (which has now moved to https://docs.perl6.org/type/Int#(Real)_routine_rand) if needed.

**Comment by zakame** [comment]
Furthermore https://github.com/perl6/roast/blob/master/S32-num/rand.t#L13-L30 specifies `0 <= rand() < 1`
