### ISSUE TITLE
setup daily build of rakudo with enough modules to run doc.

### ISSUE THREAD

**Issue by coke** [perl6/doc#788]
See http://irclog.perlgeek.de/perl6/2016-08-02#i_12957335  for discussion.

Goal is to cut down on travis build times, and this could be shared with other Perl 6 projects doing travis testing.

**Comment by LLFourn** [comment]
I'd go about this by setting up an [automated docker build](https://docs.docker.com/docker-hub/builds/#/create-an-automated-build) for every commit to rakudo and package the modules inside the container. It would help for the docs and just be nice to have in general. Travis has [docker built in](https://docs.travis-ci.com/user/docker/#Using-a-Docker-Image-from-a-Repository-in-a-Build) so other projects could run their tests against the image.

**Comment by JJ** [comment]
Is this still relevant? Has the automated build been set up?

**Comment by JJ** [comment]
If the goal is to cut down travis build, we are using pre-built binaries from Whateverable. Allow me to close this as no longer relevant.

**Comment by AlexDaniel** [comment]
These builds don't come with precomped modules though, and that could potentially save ≈22% of the test time (more than 3 minutes). You decide if that's significant enough or not.

**Comment by nxadm** [comment]
Is there a list of the needed modules?

**Comment by AlexDaniel** [comment]
@nxadm yes, see this: https://travis-ci.org/perl6/doc/builds/353746161#L1490

**Comment by JJ** [comment]
There's #1765 which, for the time being, is in my own branch...
