### ISSUE TITLE
Mention how to do build-time attribute defaults

### ISSUE THREAD

**Issue by masak** [perl6/doc#79]
<masak> [backlog] should lazy attribute defaults be part of http://doc.perl6.org/language/classtut ? did someone file an issue about this?
    <masak> m: class C { has $.x = "OH HAI" }; say C.new(:x(42)).x; say C.new.x
    <camelia> rakudo-moar 86b1b2: OUTPUT«42␤OH HAI␤»
    * masak submits an issue
    <liztormato> To be clear: has $.a = 42 is not lazy but run at build time
    <masak> oh! yes, you are right. those two are not the same.

Up until that point in the conversation I was confusing "build-time" and "lazy", which are indeed different points. Leaving aside the lazy case for this issue (as the syntax is still being discussed), I think it'd make sense to document how to do the build-time default thing with attributes.

...including the nice trick with putting `die` in the rhs to make the object explode at build time if an attribute was not passed in.

**Comment by jonathanstowe** [comment]
:+1:
