### ISSUE TITLE
Description of the split routine lacks examples specifying the negative LIMIT as the argument

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#791]
See
https://docs.perl6.org/routine/split
https://github.com/perl6/roast/blob/master/S32-str/split-simple.t#L44-L45

In other languages such as Scala, Python, Perl 5, and so on, specifying the negative LIMIT as the argument of the split routine means "split as much as possible".
However, unlike other languages, Perl 6 returns empty result when specifying the negative LIMIT.

I think the above situation should be documented and exampled.

**Comment by gfldex** [comment]
We can not and should not document the absence of magic behaviour commonly found in other languages. If we actually start doing that the docs would quickly triple in size.

**Comment by titsuki** [comment]
@gfldex I see. Thanks for your reply.

**Comment by coke** [comment]
The *difference* is something that would go in a language specific intro - we have perl5-to-perl6 partial docs; but it belongs there, not in the documentation for split itself.

However, we don't list at all what happens with a negative limit, that should be doc'd.

Additionally, there's a: "Note that unlike in Perl 5, empty chunks are not removed from the result list. For that behavior, use the `:skip-empty` named argument:"

the words "unlike in Perl 5," can be removed without losing anything here.

**Comment by dogbert17** [comment]
I have removed the "unlike in Perl 5," blurb. As for the original request, how about something like:
----
Also note that specifying a negative limit will not produce any meaningful result.

    say split(';', "a;b;c", -1).perl;       # ()
---
Alternatively we could add an example among the other like (perhaps):

say split(';', "a;b;c").perl;          # ("a", "b", "c")
say split(';', "a;b;c", 2).perl;       # ("a", "b;c").Seq
**say split(';', "a;b;c", -1).perl;       # ()**

say split(';', "a;b;c,d").perl;        # ("a", "b", "c,d")
say split(/\;/, "a;b;c,d").perl;       # ("a", "b", "c,d")
say split(/<[;,]>/, "a;b;c,d").perl;   # ("a", "b", "c", "d")

**Comment by dogbert17** [comment]
To get the discussion going or possibly close the case :-) I have made the following change https://github.com/perl6/doc/commit/3ad38ad682

**Comment by titsuki** [comment]
@dogbert17

Thanks a lot !
It looks good for me.
I close this issue, since I suggested this first.
