### ISSUE TITLE
missing File::Temp dependency

### ISSUE THREAD

**Issue by zengargoyle** [perl6/doc#80]
just started with a fresh `rakudobrew build moar; rakudobrew build-panda; panda install Task::Star;` and got to this failure.  Had to manually `panda install File::Temp` before retrying.

==> Fetching p6doc
==> Building p6doc
Compiling lib/Perl6/Type.pm to mbc
Compiling lib/Perl6/TypeGraph.pm to mbc
Compiling lib/Perl6/Documentable.pm to mbc
Compiling lib/Pod/Htmlify.pm6 to mbc
Compiling lib/Pod/Convenience.pm6 to mbc
Compiling lib/Perl6/TypeGraph/Viz.pm to mbc
Compiling lib/Perl6/Documentable/Registry.pm to mbc
Compiling lib/Pod/To/SectionFilter.pm to mbc
==> Testing p6doc
t/pod-convenience.t .. ok
===SORRY!===
Could not find File::Temp in any of: file#lib, file#lib, file#/home/hayter/.panda-work/1431054053_9/blib/lib, file#/home/hayter/.panda-work/1431054053_9/lib, file#lib, file#/home/hayter/.perl6/2015.04-179-g6b4f9be/lib, inst#/home/hayter/.perl6/2015.04-179-g6b4f9be, file#/home/hayter/.rakudobrew/moar-nom/install/share/perl6/lib, file#/home/hayter/.rakudobrew/moar-nom/install/share/perl6/vendor/lib, file#/home/hayter/.rakudobrew/moar-nom/install/share/perl6/site/lib, inst#/home/hayter/.rakudobrew/moar-nom/install/share/perl6, inst#/home/hayter/.rakudobrew/moar-nom/install/share/perl6/vendor, inst#/home/hayter/.rakudobrew/moar-nom/install/share/perl6/site
t/pod-htmlify.t ...... 
No subtests run 
t/typegraph.t ........ ok
Test Summary Report
-------------------
t/pod-htmlify.t    (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=3, Tests=18,  2 wallclock secs ( 0.01 usr  0.00 sys +  2.32 cusr  0.07 csys =  2.40 CPU)
Result: FAIL
test stage failed for p6doc: Tests failed
  in method install at lib/Panda.pm:133
  in block  at lib/Panda.pm:210
  in method resolve at lib/Panda.pm:204
  in sub MAIN at /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:20
  in sub MAIN at /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
  in block <unit> at /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:87

Failure Summary
----------------
Task::Star
        *test stage failed for p6doc: Tests failed

**Comment by niner** [comment]
Fixed in commit a8dbc9a5c3f78b8b087738f9decf9b922628cfaf
Thanks for reporting!
