### ISSUE TITLE
eqv docs misleading

### ISSUE THREAD

**Issue by jdv** [perl6/doc#81]
To me them imply this would return True:

[jdv@wieldy rakudo]$ perl6 -e 'class A{has $a};say A.new(:a(5)) eqv A.new(:a(5))'
False
[jdv@wieldy rakudo]$

**Comment by paultcochrane** [comment]
@jdv I've extended the `eqv` docs to help explain this better.  Please see 4c57c157e4dae804b3922562687e9e8420b6581a for details.  If the explanation clears things up for you sufficiently, feel free to close this issue.

**Comment by jdv** [comment]
The docs are now inline with current implementation but as suggested here:

http://irclog.perlgeek.de/perl6/2015-07-25#i_10953872

hopefully the implementation will change.
