### ISSUE TITLE
pragma invocant is not implemented or documented

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#810]

**Comment by JJ** [comment]
It's now documented as NYI. Does that count as fixed? But is here, BTW https://rt.perl.org/Public/Bug/Display.html?id=130233

**Comment by jnthn** [comment]
I'm not sure there's much value in documenting things that are NYI. It's not like the documentation reader can make use of them. Further, ideas for future features are just that: ideas. Once they reach the point of being implemented, or once they are implemented and face some practical use, they often end up needing some refinement - or in the odd case it's realized they weren't a good idea in the first place. (I'm not making a judgement call on the feature in question here. There's always the chance it will show up exactly as speculated. But if history is a guide, there's just as much chance it won't.)

**Comment by JJ** [comment]
So it might be a better idea to just erase it from the documentation and close this issue, right?

**Comment by JJ** [comment]
Which I'm doing it now.
