### ISSUE TITLE
Bag and BagHash pages are almost equal

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#816]
Firstly, look at
https://docs.perl6.org/type/Bag
Secondly, look at
https://docs.perl6.org/type/BagHash

Descriptions of this two are almost equal except for some particular differences between these two types. We duplicate almost everything here: description text, examples, etc.

**Comment by b2gills** [comment]
Well they are almost identical so to a certain extent that may be expected.  
The only real difference is Bag is immutable whereas BagHash is mutable.

**Comment by AlexDaniel** [comment]
From [CONTRIBUTING.md#general-principles](https://github.com/perl6/doc/blob/master/CONTRIBUTING.md#general-principles):
> * Duplicate small pieces of information rather than rely on linking

I am not sure what was meant by that, but I think that this is our case here. Yes, 3 sections of these pages are similar, but what kind of a solution do you propose? I mean, we can create a separate page that will discuss Bag, BagHash and their differences, but we kinda already have [language/setbagmix](https://docs.perl6.org/language/setbagmix).

But if somebody visited a Bag or BagHash page, he should see at least some examples anyway.

I think that what we have now is ideal and nothing should be done. Therefore, I propose to close this.

**Comment by Altai-man** [comment]
Judging by the answers, I'd agree that we should have proper description for every type.
I'm not sure we can somehow get rid of it now, I just thought about checking the status of this. Hence, it can be closed, I suppose, but I'm still somewhat feel less than awesome approach here. If it's language `by design`, then ok.
