### ISSUE TITLE
Mark external links

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#822]
External links should look differently.

This is actually pretty common. For example, Wikipedia does that.

Typically it is implemented by adding an icon (I'd recommend svg). Maybe a unicode arrow will do (like ↗), but using unicode characters as icons is usually not the best idea.

This is also related to #710

**Comment by ahalbert** [comment]
Would this be done in the code for building the documentation, or would we have to mark each link in the pod with the icon?

**Comment by AlexDaniel** [comment]
Good question. Well, for the web version of the docs we want such links to have a css class… but I am not sure about everything else.

**Comment by ahalbert** [comment]
I realized in the POD, it's obvious that it's an external link. So we may only want to do this for formats that obscure the link destination.

**Comment by coke** [comment]
I think this is for the HTML site only; note that the style appears when running the site locally (once I installed a few Mojo modules) with 'make run', but not on the public site.

**Comment by coke** [comment]
This was fixed with 85de0d2
