### ISSUE TITLE
zavolaj seems outdated for showcasing how to use NativeCall

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#828]
zavolaj is referred in this section
https://docs.perl6.org/language/nativecall#Examples

It uses many old-fashioned NativeCall syntax

For example
- `Int` should be `int32`

```
sub fork() returns Int is native { ... }
```

https://github.com/jnthn/zavolaj/blob/master/examples/unix-fork.p6#L4
- `OpaquePointer` should be `Pointer` 

```
sub PQfinish( OpaquePointer $conn )
```

https://github.com/jnthn/zavolaj/blob/master/examples/postgresqlclient.p6#L28

I think that zavlaj should be fixed or some other module calling NativeCall (ex. DBlish) is suitable for showcasing how to use NativeCall.

**Comment by jnthn** [comment]
Given the module has migrated into Perl 6 by now, the only reason that repository still exists is because it had some examples. If they're bad examples, I suggest we remove the link to it, then I'll delete it so people won't stumble across the out-dated info when doing google searches. :-)

**Comment by jonathanstowe** [comment]
It would be better to have something well maintained and probably under the perl6 organization as an example, but I'd say that both DBIish and GTK::Simple are possibly too complex to be useful examples.

**Comment by jnthn** [comment]
I suspect DBIish and GTK::Simple count as large/complex examples, but I suspect there are smaller modules using NativeCall that can serve as simpler, good examples to point to. And the smallest examples can be included directly in the docs.

**Comment by moritz** [comment]
@jnthn I've replaced the last reference to zavolaj with a small example inline in the docs. If zavolaj has served its purpose now, you might consider deleting the repo, or maybe updating the README to say it's now a historical archive only.

**Comment by jnthn** [comment]
@moritz Agree there's not much purpose for that repo any more, and don't think the history is all that interesting; it's gone. :-)
