### ISSUE TITLE
X::TypeCheck::Splice exception description is wrong

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#833]
https://docs.perl6.org/type/X$COLON$COLONTypeCheck$COLON$COLONSplice
It seems the description is a lie for current rakudo. And example throws completely different exception.

It has to be investigated and, I suppose, rewritten.

**Comment by JJ** [comment]
The link is now [this one](https://docs.perl6.org/type/X::TypeCheck::Splice). Is it still wrong?

**Comment by JJ** [comment]
Some places it shows up in roast:
*https://github.com/perl6/roast/blob/master/S32-array/splice.t#L186
* https://github.com/perl6/roast/blob/master/S06-macros/unquoting.t#L68 and this one seems to be related to macro
