### ISSUE TITLE
Missing methods in Str

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#838]
- [ ] match
- [x]  samemark
- [x] samecase

**Comment by dogbert17** [comment]
samemark was documented a few weeks ago: https://docs.perl6.org/type/Str#routine_samemark

**Comment by dogbert17** [comment]
As for samecase, it is documented in https://docs.perl6.org/type/Cool#routine_samecase. Should we copy that documentation to Str as well?

**Comment by Altai-man** [comment]
@dogbert17 I doubt that, since it is already included in the Str type page as inherited method. See https://docs.perl6.org/type/Str#(Cool)_routine_samecase. I think, we can mark `samecase` method as documented.

**Comment by dogbert17** [comment]
Marked. Thx for the feedback.

**Comment by Altai-man** [comment]
Now `match` is documented too and this can be closed. @ahalbert++.
