### ISSUE TITLE
sprintf description is wrong

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#839]
https://docs.perl6.org/type/Str.html#sub_sprintf

Obvious problem: it claims that we have "Modifiers" such as `%ld` or `%qd` working and even provides an example. But we're not:

```
> sprintf "%ld a big number, %lld a bigger number\n", 4294967295, 4294967296;
Directive ld a big number, %lld a bigger number
 is not valid in sprintf format sequence %ld a big number, %lld a bigger number

  in any  at /home/sena/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in any panic at /home/sena/.rakudobrew/moar-nom/install/share/nqp/lib/NQPHLL.moarvm line 1
  in any statement at /home/sena/.rakudobrew/moar-nom/install/share/nqp/lib/NQPHLL.moarvm line 1
  in any TOP at /home/sena/.rakudobrew/moar-nom/install/share/nqp/lib/NQPHLL.moarvm line 1
```

Definitely less than awesome. Someone should
 * Investigate current implementation status of sprintf subroutine
 * Update/change the documentation accordingly to the real world.

**Comment by tbrowder** [comment]
this issue may be due to current, open issues with rakudo's handling of native uint64

**Comment by Altai-man** [comment]
@tbrowder it may be, but until they will be resolved, I think we need to have some warning about it. Something like simple "This is still NYI". And, of course, we need to give this section some love after the issues will be resolved.

**Comment by tbrowder** [comment]
Of course, and I am working on the docs on my side (setting my own test suite as a dup of what the docs show) and will update them after I finish the tests to show what works and what doesn't.  In the meantime, I will add a note about the current unsure state of the docs if you think that will be okay. I'll make it a PR so all can consider it before a merge, but I'll leave the merge up to someone else.

**Comment by tbrowder** [comment]
see latest PR

**Comment by Altai-man** [comment]
It seems certainly better than it was and definitely less misleading. Can be closed until the uint64 issue resolving, I suppose. @tbrowder++.
