### ISSUE TITLE
Search gives no feedback when nothing found

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#84]
Expected: some kind of "no results". Got: no feedback.

**Comment by ab5tract** [comment]
This was fixed with the merging of the 'choices' branch.

**Comment by moritz** [comment]
@ab5tract I think Juerd talked about the search box in the web page, not the p6doc command line tool. @Juerd, please correct me if I'm wrong.

**Comment by ab5tract** [comment]
Good point @moritz :)
