### ISSUE TITLE
;; is not searchable

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#841]
In roast, `;;` is used here
https://github.com/perl6/roast/blob/master/S06-multi/syntax.t#L38-L53

In the perl 6 document, the description of the `;;` is in the following page
https://docs.perl6.org/type/Signature#Long_Names

**Comment by Altai-man** [comment]
It seems `;;` has special meaning, therefore it doesn't work as needed. Local building gives us warning about unclosed tag.
Perhaps, it is a case for our https://github.com/perl6/doc/blob/master/predefined-search-items work-around.

**Comment by titsuki** [comment]
@Altai-man `C<<;;>>` doesn't seem to show warnings, so I use this form.

**Comment by titsuki** [comment]
@Altai-man hmm, it is broken again.
https://docs.perl6.org/type/Signature#Long_Names

**Comment by titsuki** [comment]
I'll try https://github.com/perl6/doc/blob/master/predefined-search-items later...

**Comment by Altai-man** [comment]
@titsuki thanks for your efforts.
