### ISSUE TITLE
sprintf and printf descriptions should have a common source

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#849]
The descriptions of format specifiers and other details of the two functions should be identical, but they aren't and they seem to have different source files.  We need a common source that, through some scripting magic, will produce the two separate final pod files.  Otherwise, one source should not go into detail but should reference the other description the way libc man pages do it.

**Comment by Altai-man** [comment]
Related https://github.com/perl6/doc/issues/839

**Comment by tbrowder** [comment]
closed with pr #870

**Comment by tbrowder** [comment]
After looking at the current state of the public view of sprintf and comparing it to Perl 5's docs, I think a slight rewrite (and more testing of some untested features) is in order.  I have started on that project in my fork and hope to finish it in a day or so with a PR for review.

**Comment by tbrowder** [comment]
still working on the sprintf revision part, but the issue is really closed because printf has links back to sprintf
