### ISSUE TITLE
Put link to github repo on doc.perl6.org footer

### ISSUE THREAD

**Issue by Juerd** [perl6/doc#85]
Had to actually google for it! :-)

Suggestion: make "work in progress" the link.

**Comment by moritz** [comment]
@Juerd, which page didn't have a link to the github repo?

Some pages like the front page have a direct link to the file on github from which it was generated; others like http://doc.perl6.org/routine.html (which aren't generated from a single file) link to the repo as a whole.

If there are pages that don't contain any link at all, that's a bug.

**Comment by Juerd** [comment]
The front page does link to a page in the repository, but because that goes directly to the raw file, I hadn't noticed that it was part of a git repo. A link to the github web interface is useful because it has the "issues" button. Perhaps a link straight to the issues page would be even better.
