### ISSUE TITLE
`sub read-n($fh, $n) {` in Language/5to6-nutshell.pod is weird for a p5 hacker

### ISSUE THREAD

**Issue by masochist** [perl6/doc#850]
Coming from perl5, when I see `sub read-n`, I immediately think "syntax error". Perhaps the doc should clarify that this doesn't do anything weird and is just a sub name? Some perspective from LISP/Scheme helps me grok this, but maybe not everyone reading this document has that context.

To be clear, this is at [this line](https://github.com/perl6/doc/blob/master/doc/Language/5to6-nutshell.pod6#L292) in the file.

**Comment by AlexDaniel** [comment]
Thank you for your report! But what about ``lookup-user``, ``do-something``, ``do-something-else``, ``do-default-thing``, ``%subs-to-export``, ``@import-list`` and so on (later in the same file)?

I don't think that we should explain that dashes are OK after every occurrence. I also don't think that 5-to-6 documents should use p5 naming conventions just to make people comfortable. Dashes are too common in perl 6.

There is nothing we can do here, therefore this issue should be closed, IMO.

**Comment by masochist** [comment]
> On Aug 21, 2016, at 15:48, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com> wrote:
> 
> Thank you for your report! But what about lookup-user, do-something, do-something-else, do-default-thing, %subs-to-export, @import-list and so on (later in the same file)?
> 
> I don't think that we should explain that dashes are OK after every occurrence.

I didn’t suggest we should specify it after every occurrence. A simple clarification (like every side-by-side example in the document) seems like a reasonable approach.

> I also don't think that 5-to-6 documents should use p5 naming conventions just to make people comfortable. Dashes are too common in perl 6.

Is your suggestion that, in a guide designed to help perl5 dev, we shouldn’t make perl5 devs comfortable? This seems to be contradictory to the purpose of the document.

> There is nothing we can do here, therefore this issue should be closed, IMO.

I gave a specific suggestion of what to do. What is the problem with the suggestion I made?

**Comment by shadowcat-mst** [comment]
It's the first example of a *user* writing code that uses - as an identifier.

Nobody was suggesting we should change to perl5 naming conventions.

Mentioning it the first time you demonstrate writing such code does not seem like a bad idea.

**Comment by zoffixznet** [comment]
@masochist I've added a brief `Identifiers` section that makes a passing mention that dashes and weird Uncidode bits are OK in P6 identifiers. Hopefully that's deconfusing enough for this Issue.

**Comment by masochist** [comment]
Thank you! This does help.
