### ISSUE TITLE
tilde metacharacter is not documented in regex.

### ISSUE THREAD

**Issue by jdoege** [perl6/doc#853]
In Synopsys S05 the tilde metacharacter is described as a helper for matching nested structures. It is implemented and works in the current Rakudo release and I think I found that it is tested and passing in Perl6/Roast. When I first saw an example of it's use, I looked in docs.perl6.org/language/regexes and docs.perl6.org/language/grammars and could not find it. As someone on IRC said, searching for "~" is problematic. :-)

**Comment by Altai-man** [comment]
Closed with https://github.com/perl6/doc/pull/1190
