### ISSUE TITLE
The "where" clause should be added to the description of multi-dispatch

### ISSUE THREAD

**Issue by jdoege** [perl6/doc#858]
In docs.perl6.org/language/functions multiple dispatch based on argument signature matching is described. Dispatch based on the number of arguments and argument type is described, but the very useful dispatch based on argument value using the where clause is not. This could be described using the traditional example from functional programming, the fibonacci sequence:

```
multi fib( Int $n where ( $n==0 ) ) { 0 }
multi fib( Int $n where ( $n==1 ) ) { 1 }
multi fib( Int $n ) { fib($n-2) + fib($n-1) } 
```

**Comment by jonathanstowe** [comment]
I would say that it should be mentioned there but probably the proper place for this to be fully documented would be in https://docs.perl6.org/type/Signature (where it is infact described, perhaps not fully enough but hey.)  The paragraph ```Dispatch can happen on the number of arguments (the arity), but also on the type:``` should probably be expanded (or altered) to something like "Dispatch can happen on the number of arguments (the arity), but also on the constraints on the variables as described in the ....", but yes the example you give would be pretty good to put in the examples afterwards.

**Comment by coke** [comment]
Note that this particular example is better written as

multi fib(0) { 0 }

So might not be the best example for where clause.

**Comment by jonathanstowe** [comment]
Something that does "even" and "odd" numbers perhaps?

**Comment by jdoege** [comment]
And, I suppose, multi fib(1) { 1 }, too. I didn't realize this syntax was valid. I hadn't seen the Signature section yet, that's excellent!
I guess what I really mean is it's a good place to briefly point out the dispatch by value capability, too. As someone new to Perl6 the documentation having small related examples and then linking to other more complete sections for complete information is valuable.
