### ISSUE TITLE
FIRST phaser doesn't return a value (yet)

### ISSUE THREAD

**Issue by frithnanth** [perl6/doc#859]
doc/Language/phasers.pod6 states:

> Phasers marked with a * have a run-time value, and if evaluated earlier than their surrounding expression, they simply save their result for use in the expression later when the rest of the expression is evaluated

FIRST is one of those phasers which are supposed to have a run time value, but so far this:

`for 1, 2, 3 -> $item { my $x = FIRST { 42 }; say $item, $x }`

returns:

`1(Any)␤2(Any)␤3(Any)␤`

**Comment by dogbert17** [comment]
Fixed with https://github.com/perl6/doc/commit/d5a91dc984
