### ISSUE TITLE
method sum() (Range) is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#861]
`method sum(Range:D:)` is tested here
https://github.com/perl6/roast/blob/master/S03-operators/range-int.t#L486-L514

**Comment by titsuki** [comment]
`method sum()` is here
https://github.com/rakudo/rakudo/blob/nom/src/core/Range.pm#L607-L611

**Comment by Altai-man** [comment]
Closed by https://github.com/perl6/doc/pull/863#issuecomment-242974415
