### ISSUE TITLE
Document enumerations

### ISSUE THREAD

**Issue by masak** [perl6/doc#87]
<jab> Where can I find the syntax for the enum statement?
    <masak> jab: described in S12, at least.
    <masak> S12:Enumerations
    <synbot6> Link: http://design.perl6.org/S12.html#Enumerations
    <jab> thanks
    <masak> dunno if docs.perl6.org has something. if not, it probably should.
    <masak> cursory search yields nothing.
    <jab> Yeah it's hard to find enum info
    * masak files issue

Enumerations are important enough to merit a page of their own, methinks. Going through the basic syntax, its variations, default values, common uses, etc.

**Comment by smls** [comment]
Not sure if there's enough to warrant a whole page. Maybe it could fit int the  `types`:**Type System** page I'm planning, though.

**Comment by dogbert17** [comment]
Might commit 36f4e8d79e39815e4ccd95bfb4388212fe13fa64 be enough?

**Comment by jsoref** [comment]
@dogbert17 : At the very least, someone needs to add something to the glossary, if only linking to the typesystem entry...

**Comment by AlexDaniel** [comment]
Great, but it does not come up in the search. Can we fix that?

**Comment by gfldex** [comment]
- enums are doced
- they show up in search
- the glossary links to the right section
