### ISSUE TITLE
It is claimed that there is sub start, but that's not very true

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#874]
From https://docs.perl6.org/type/Promise#method_start:

``` perl6
sub start(&code)
```

But:

``` perl6
say &start
```

```
===SORRY!=== Error while compiling -e
Undeclared routine:
    start used at line 1. Did you mean 'spurt', 'sort', 'sqrt'?
```

See also http://irclog.perlgeek.de/perl6/2016-08-31#i_13126595

**Comment by jnthn** [comment]
Indeed. It actually desugars into a call to the `Promise.start` method, but is parsed as a statement prefix - like gather, for example.
