### ISSUE TITLE
Most internal links in the Glossary don't work

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/doc#878]
For example, in the 'Adverb' section, the link at the bottom to 'Colon Pair and Colon List' doesn't work. It changes the url in the browser, but doesn't move you on the page. However, the ToC links do work. The one difference I can see is that the ToC links have an '_' on the end of the link (e.g., the url it has is 'https://docs.perl6.org/language/glossary#Colon_Pair_and_Colon_List_' instead of 'https://docs.perl6.org/language/glossary#Colon_Pair_and_Colon_List').

However, some links do seem to work, but I can't find a reason why the difference. E.g., in the 'Apocalypse' section, the 'TimToady' link works but the 'Exegesis' and 'Synopsis' links don't.

**Comment by ahalbert** [comment]
A clarification about @MasterDuke17's comment - I found that in his example an _ character needs to be at the end of Colon_Pair_Colon_List_ to make it work correctly.  I think github formatted it weird.

**Comment by ahalbert** [comment]
Possibly the issue is with id's in the pod that have spaces in them. TimToady has no spaces in the id, while Colon Pair and Colon List does.

**Comment by Altai-man** [comment]
We need to investigate htmlify.p6 or Pod::To::Html. Internal links here are pretty broken, not only for Glossary page, but for, for example, every method link on the page.
I tried to make situation better not so long ago and some things were fixed, but we need to create some general linking scheme in Pod::To::Html and the site itself and implement it so we won't have any dead generated links(see https://github.com/perl6/doc/issues/561). I don't have enough time for this, but I still hope some really brave folk will fight this issue.

**Comment by ahalbert** [comment]
I found a problem in Pod::To::HTML - extra whitespace is added at some point when generating the ID's. A simple fix is to trim whitespace before the id is generated in `escape_id($id)`. 

I think it would be better to not create extra whitespace, I'm looking into why the extra whitespace is being added rather than just trimming it.

**Comment by ahalbert** [comment]
I submitted a fix for this in Pod::To::HTML https://github.com/perl6/Pod-To-HTML/pull/19  . We can close this issue once it's been accepted.

**Comment by MasterDuke17** [comment]
Merged.

**Comment by MasterDuke17** [comment]
Looks good.
