### ISSUE TITLE
Channel.list “Returns a Seq” and “returns List:D” at the same time, so what is it?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#879]
From https://docs.perl6.org/type/Channel#method_list:

> Defined as:
> 
> method list(Channel:D:) returns List:D
> 
> Returns a Seq which will iterate items in the queue and removes each item from the queue as it iterates.

So does it return a List or a Seq? It would be great if we could explain what is going on there.

Also, I don't understand how can a List block until it gets all of the items. How does that work? See this question: http://irclog.perlgeek.de/perl6/2016-09-02#i_13141776

**Comment by jnthn** [comment]
Here's how it's defined:

    method Seq(Channel:D:)  { Seq.new(self.iterator) }
    method list(Channel:D:) { self.Seq.list }

So, it returns a list, based on the `Seq`. Block until you get all items? That's just `eager`.
