### ISSUE TITLE
RAKUDO_EXCEPTIONS_HANDLER not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#882]
RAKUDO_EXCEPTIONS_HANDLER (see [this](https://github.com/rakudo/rakudo/commit/aaf7c3cf573814a7027b514000c7505146f19da6) and [this](https://github.com/rakudo/rakudo/commit/826d438f7a3e1fe09c5b9ac0e370caf82a88931a)) not documented

**Comment by coke** [comment]
As a Rakudo specific variable, this is now documented on

https://github.com/rakudo/rakudo/wiki/dev-env-vars

Which is linked to from:

https://docs.perl6.org/programs/00-running#ENVIRONMENT_VARIABLES
