### ISSUE TITLE
:close flag to IO::Handle.slurp-rest not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#883]
[https://docs.perl6.org/routine/slurp-rest](slurp-rest) method [now supports](https://github.com/rakudo/rakudo/commit/4efdd949dfb6279ed4998877f015101f3c653bfb) `:close`

**Comment by dogbert17** [comment]
Should be fixed with https://github.com/perl6/doc/commit/71fde8d0a1

**Comment by zoffixznet** [comment]
Thanks!

**Comment by AlexDaniel** [comment]
Reopened because of the revert.

**Comment by zoffixznet** [comment]
Pre-emptively closing this. The docs coverage is part of the IO grant and I'll ensure the method is correctly documented. So far the `:close` parameter is on the chopping block, with another parameter being added, so the updated doc version is unlikely to need the reverted commit.
