### ISSUE TITLE
CallFrame has broken links to $?FILE and $?LINE, $?FILE and $?LINE do not mention CallFrame

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#885]
Both should mention each other properly.
- [x] https://docs.perl6.org/type/CallFrame has broken links to `$?FILE` and `$?LINE`
- [ ] CallFrame is not mentioned here https://docs.perl6.org/language/variables#Compile-time_variables

**Comment by ahalbert** [comment]
Link to `$?LINE` in call frame is `https://docs.perl6.org/type/$DOLLAR_SIGN$QUESTION_MARKLINE`
when it should be
`https://docs.perl6.org/language/variables#index-entry-%24%3FLINE`

**Comment by JJ** [comment]
Links have been changed to  https://docs.perl6.org/language/variables#Compile-time_variables
