### ISSUE TITLE
String bitwise ops don't seem to be documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#887]
I see them in the precedence table on https://docs.perl6.org/language/operators, but they don't appear in the text or search index.

I'm talking about `~^`, `~|`, `~&` (there may be more)

**Comment by dogbert17** [comment]
Look like this was fixed with https://github.com/perl6/doc/commit/704f4a011db1037e2a4a0613c09ce7aa90468520. Closing

**Comment by AlexDaniel** [comment]
Should we actually document NYI stuff?

**Comment by coke** [comment]
It's squishy, but if it's something that's in a fudged roast test, then I think it's fair game*. We're documenting the spec, not (only) rakudo's implementation.

If it's only in a Synopsis document, then I wouldn't bother.

We need to, at some point, indicate not only which language spec something is available in, but also which compilers support it (there are other tickets for this)

*I didn't check to see if these fall into that category.
