### ISSUE TITLE
Use – instead of --

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#888]
Because why not? In fact, Perl 6 is *so* unicode-friendly that using ``--`` is a bit inappropriate.

For example, you can lots of ``--`` on https://docs.perl6.org/language/classtut

**Comment by AlexDaniel** [comment]
OK. Can we have a test for this? :)
(ping @coke)

**Comment by coke** [comment]
IMO, too much of a pain to write a test, since nearly every usage of -- is going to be in code, not in the plain text.

**Comment by AlexDaniel** [comment]
OK. Well, if we care about it enough, we can reopen this issue every year or so.
