### ISSUE TITLE
Explanation of "Graphemes" and Unicode Forms Stuff

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#891]
I have a simple task to solve:

```
[13:02] <MetaZoffix> m: say "7\x[308]" ~~ /^ \d+ $/
[13:02] <+camelia> rakudo-moar f0bb58: OUTPUT«｢7̈｣␤»
[13:03] <MetaZoffix> Is there an easy way to make it look for *just* numbers without combiners?
```

But I'm not seeing any section on this in https://docs.perl6.org/language.html

By osmosis, I know I need some sort of [.NFD](https://docs.perl6.org/type/NFD) or something along the lines of that, but from a perspective of someone who's not familiar with what unicode forms there are and what they're all about, it's hard to understand what I am supposed to do to make my original operation work right.

There should be a page that explains all of this stuff.

**Comment by JJ** [comment]
[Graphemes are not explained in the documentation](https://docs.perl6.org/type/Cool#index-entry-Grapheme). Would that be enough? What else would be needed?
