### ISSUE TITLE
Is flat another way to say |? Why do we only document one?

### ISSUE THREAD

**Issue by shadowcat-mst** [perl6/doc#892]
https://docs.perl6.org/language/containers

"Flatteing, items and containers" mentions flat.

```
> say (flat @foo, 8, 9).elems
5
> say (|@foo, 8, 9).elems
5
```

seem to be equivalent but there's no mention of the slip syntax

**Comment by timo** [comment]
in an actual call, like `say(1, 2, 3)` the "flat" will not cause items of the array to become multiple positional parameters. That's why the prefix | ought to also be explained, at the very least in that context with a note pointing from here to there.

**Comment by JJ** [comment]
I have the hunch that the "single argument rule" has something to do with them not being the same. But it's true this will have to be documented.

**Comment by zoffixznet** [comment]
There isn't that much similarity between the two, let alone equivalence.

```
<Zoffix_> m: my @l := 1, 2, (3, 4, (5, 6)), [7, 8, (9, 10)]; say (|@l, 11, 12); say (flat @l, 11, 12)
<camelia> rakudo-moar f6756bb4d: OUTPUT: «(1 2 (3 4 (5 6)) [7 8 (9 10)] 11 12)␤(1 2 3 4 5 6 7 8 (9 10) 11 12)␤»
<Zoffix_> m: my @l := 1, 2; dd ($@l, $@l).flat
<camelia> rakudo-moar f6756bb4d: OUTPUT: «($(1, 2), $(1, 2)).Seq␤»
<Zoffix_> m: my @l := 1, 2; dd ($@l, $@l).map: |*
<camelia> rakudo-moar f6756bb4d: OUTPUT: «(1, 2, 1, 2).Seq␤»
<Zoffix_> m: my @l := 1, 2; dd [flat(@l), flat(@l)]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[(1, 2).Seq, (1, 2).Seq]␤»
<Zoffix_> m: my @l := 1, 2; dd [|@l, |@l]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[1, 2, 1, 2]␤»
<Zoffix_> m: my @l := 1, 2; dd [foo => |@l]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[:foo(slip(1, 2))]␤»
<Zoffix_> m: my @l := 1, 2; dd [foo => @l.flat]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[:foo((1, 2).Seq)]␤»
<Zoffix_> m: my @l := 1, 2; my %h = foo => |@l; dd [%h<foo>]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[slip(1, 2),]␤»
<Zoffix_> m: my @l := 1, 2; my %h := foo => |@l; dd [%h<foo>]
<camelia> rakudo-moar f6756bb4d: OUTPUT: «[1, 2]␤»
```

#### flat

- Flattens all non-containerized Iterables, which includes the contents of such Iterables; all the way until they're entirely flattented or you descend up to a containerized Iterable
- Creates a Seq

##### `prefix:<|>`

- Causes only the given Iterable flattened into the containing Iterable and that won't occur if the Slip is containerized
- Creates a Slip

(this doesn't comment on the `|` used in argument lists, which has nothing at all to do with slips and is a special-cased compiler feature).

**Comment by JJ** [comment]
I'll try to summarize that and improve the documentation in that area.
