### ISSUE TITLE
Experimental doc seems vestigial

### ISSUE THREAD

**Issue by shadowcat-mst** [perl6/doc#893]
Plus I know at least macros aren't coming that soon. Does this want rewriting or murdering?

**Comment by coke** [comment]
https://docs.perl6.org/language/experimental needs expanding, yes.

**Comment by AlexDaniel** [comment]
Expanding? It looks like some good stuff for rakudo wiki, but not language docs. Or am I wrong?

**Comment by coke** [comment]
Macros are an experimental part of the Perl 6 spec, with an implementation in Rakudo.

Same for anything else on the experimental page.

**Comment by JJ** [comment]
Is something left to do on this issue?

**Comment by AlexDaniel** [comment]
It feels like it was cleaned up at some point. LGTM.

**Comment by JJ** [comment]
Closing it them. Please @shadowcat-mst feel free to reopen and/or clarify.
