### ISSUE TITLE
Slight inconsistency in IO::Socket::INET example

### ISSUE THREAD

**Issue by jnthn** [perl6/doc#898]
On https://docs.perl6.org/type/IO$COLON$COLONSocket$COLON$COLONINET it shows a listener example that does not bind to localhost, and then a connect example that does. I got caught out by this; changing the connect to 127.0.0.1 fixed it.

Note that I got especially caught out 'cus I nabbed the example to base a spectest on, and it actually worked on my Ubtuntu VM. Then the test failed because of this on OSX and somebody's Debian server.

Might be worth tweaking the example to save somebody else headaches or confusion. :-)

**Comment by zoffixznet** [comment]
Already fixed in 55f3138 :smile_cat:
