### ISSUE TITLE
Missing example in variables

### ISSUE THREAD

**Issue by shadowcat-mst** [perl6/doc#906]
https://docs.perl6.org/language/variables

    Note that this is not a thread-safe construct when the same clone of the same block is run by multiple threads. Also remember that methods only have one clone per class, not per object.
    
    will continue to increment $l and append it to @x each time it is called. So it will output

Surely there should be a code sample before the 'will'

**Comment by ahalbert** [comment]
This can be closed.

**Comment by jonathanstowe** [comment]
@shadowcat-mst are you cool with it being closed?

**Comment by jonathanstowe** [comment]
BTW you can cause an issue to be closed by a commit by putting "Fixes #906" in the commit message.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by shadowcat-mst** [comment]
Looks deconfused to me. Hitting 'close'. Thanks!
