### ISSUE TITLE
.tree is not documented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#912]
There is [method .tree](https://github.com/rakudo/rakudo/blob/363a3a899f2cb342d1ca56626657e103e9d6b6f1/src/core/Any.pm#L157) that doesn't appear to be documented.

There are some tests for it in S02-lists/tree.t

No idea what it's doing and in the code there's comment `# XXX GLR Do we need tree post-GLR?`

**Comment by JJ** [comment]
It's documented now https://docs.perl6.org/routine/tree
Not excellent, but it exists.
