### ISSUE TITLE
Proc.command undocumented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#913]
`Proc` [recently received](https://github.com/rakudo/rakudo/commit/c4fd9f515d) `@.command` attribute that contains the command and its args that the Proc was run with.

If it's not in roast, it needs to be added there as well.

**Comment by gfldex** [comment]
depends on https://github.com/perl6/roast/issues/166

**Comment by zoffixznet** [comment]
There's already a round-about test for it [in Proc::Async](https://github.com/perl6/roast/blob/master/S17-procasync/basic.t#L87) so as far as being-in-roast, it is. It just needs more coverage.
