### ISSUE TITLE
Use of Nil in String contact error (with suggested patch)

### ISSUE THREAD

**Issue by kmetcalf** [perl6/doc#92]
I ran across the following bug when running p6doc:
Use of Nil in string context  in block  at lib/Pod/To/Text.pm:24

It looks like the error is actually in Rakudo.

FIX: In sub pod2text add some null strings; replace:
        when Pod::Block::Comment {  }
        when Pod::Config       {  }
with:
        when Pod::Block::Comment { "" }
        when Pod::Config       { "" }

This works for me and appears to pass the spec test.  I'm not sure if this is the correct fix, but it's one that appears to work for me.  :)

**Comment by moritz** [comment]
Fixed with rakudo/rakudo@5a6a67237fe554f933442c1e1f1af6b297299f4a.

**Comment by paultcochrane** [comment]
Closing this ticket, since the issue seems to be resolved.
