### ISSUE TITLE
Docs mention Order::Increase Order::Same Order::Decrease

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#921]
See this: https://github.com/rakudo/rakudo/blob/8cbb1efd1d84fd57298e0e0813b64d8dd37140ba/docs/deprecations#L5

**Comment by dogbert17** [comment]
Possibly fixed with https://github.com/perl6/doc/commit/5252066ddf

**Comment by AlexDaniel** [comment]
:+1:
