### ISSUE TITLE
'TMTOWTDI' explanation blocks for examples.

### ISSUE THREAD

**Issue by ab5tract** [perl6/doc#93]
It occurred to me that following the policy of 'explain in more than one place' could be extended to TMTOWTDI explanations/explorations of code examples. I'm not sure if there is existing Pod syntax for such, but having it separated out in a separate markup tag would make sense. Then the display of such communication could be toggled on/off according to some environment flags. (Or in a hidden div with a link to open via `htmlify`).

The idea here is that contextualizing the choices of, say:

``` perl6
@a.map({ .uc })  # or even $_.uc
# vs.
@a.map( *.uc )
# vs.
@a>>.uc
```

I know that there are differences between these, but the only one that I can name off the top of my head is the potential out-of-order execution of `>>`. I have a feeling that there must be implications to laziness as well. The first aspect of the TMTOWTDI blocks would be to have centralized 'include' documentation on these 'intersections of style and substance' that quickly give an overview of the technical implications of a given choice. Automatically including them in the doc could be another toggle. When off, it would show as a normal link. When on they would be included as the next paragraph after they were referenced.

Now, in a piece of code that exemplifies the situation where `>>` would clearly cause issues and thus a `map` call is _necessary_, the `=expl` blocks (for lack of a better name) would be a place where we could include that analysis in a form not suited to single-line comments in a code example.

These contextual discussions would, in my opinion, be a significant benefit to newcomers, where examples can contain uses of language feature that the reader does not yet understand.

**Comment by ab5tract** [comment]
This could also be a mechanism for toggle-able inclusion of `S99-Glossary` entries, which I've been wondering how/whether to integrate.

**Comment by AlexDaniel** [comment]
OK, this issue has been here for quite a while. Let's see.

If I understand it correctly, then the idea is to provide more than one example to show different syntax.

We probably have to admit that this is not going anywhere and it just won't happen. In perl 6 there are just too many ways to do stuff, so providing several variants in each example is going to pollute the documentation for a little or no gain.

If you don't think so, then, um… perhaps take a look at [this](https://gist.github.com/AlexDaniel/1e2d1c50963d37c5d43a)?

However, I do realize that OP has a point. Therefore, I propose to create a new page ``language/timtowtdi``. There we can discuss all of the differences between various approaches in detail, and we won't have to do enormous work for every example. In fact, after this page is written, you can then link to it from other pages if you feel that some example requires some explanation about other ways to achieve the same thing.

**Comment by coke** [comment]
I don't think we want a giant page showing all timtowtdi's - if we have them, they'd need to be contextualized - near the docs for each of the ways.

I think that a first pass of this has to have the content (making this a [docs] issue) before we worry about having a nice HTML front end to it.

**Comment by coke** [comment]
Rather than have a universal TMTOWTDI where we have multiple options per example, I think it makes sense to highlight those places specifically where there are multiple options, for teaching purposes; Otherwise, I think it's reasonable to pick a style and follow it (and we can put it in STYLEGUIDE.md)

**Comment by JJ** [comment]
This is the oldest issue now, and it chimes in with what I have been trying to do so far in examples: first, show real use cases, and second, show different ways of using it. Problem is that this issue would affect the whole wide documentation, which I guess is why it's still open. Maybe highlight some places it would be applied and create new issues for that?

**Comment by JJ** [comment]
Or change CONTRIBUTING.md for people to contribute several ways of doing something wherever possible? 
Meanwhile, I'm all for closing this. It's a nice discussion, but I can't really see an actionable issue here. And you know I'm all for closing stuff.

**Comment by ab5tract** [comment]
The idea here is that any given code example could provoke some Perl 6 dev to want to commit a functionally equivalent, yet stylistically divergent, example. Maybe even moving the equivalency from the exactly matching the existing example to the spirit of lesson being instructed.

I submitted this to `doc` rather than a change to POD6 because I considered it more website related and therefore not something that needed to be integrated into a spec that is already quite large and unknown to me. If others think it is a better fit, I can look into that, however, this was really about just changing example blocks to "lists of examples" and dealing with optionally changing between examples on the frontend (the pure `p6doc` might never get the function, for example, but some theoretical embedded viewer might choose to do so). I assume changing a single element to a list of elements is already supported in POD6?

**Comment by ab5tract** [comment]
FWIW, this was related to giving space for explaining stylistic choices that different examples employ. The idea was that this would help smooth out the learning curve for people who are confronted by advanced/new syntax in example blocks.

"Why might you choose this operator over the other?"  kind of questions, like list boolification:

~~~~
# This is currently faster than `so all @dragons` because of missing auto-threading
[&&] @dragons
~~~~

But as the example shows above, perhaps this is better resolved by the interested parties that wish to submit clarifications to do so as PRs for comments in the examples themselves.

What do you think?
