### ISSUE TITLE
Match.CURSOR not documented (or not searchable)

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#930]
Possible usage: `$/.CURSOR.pos`

**Comment by JJ** [comment]
Defined [here as part of the NQPcursormatch role](https://github.com/perl6/nqp/blob/4138401de360ca9ea18a5db93acafcfdf74aac81/src/QRegex/Cursor.nqp#L88)

**Comment by JJ** [comment]
That function returns `self`. So is there any difference between $/.pos and $/.CURSOR.pos?

**Comment by W4anD0eR96** [comment]
Searching and glancing 
1. https://github.com/perl6/nqp/blob/master/src/QRegex/Cursor.nqp
2. https://github.com/rakudo/rakudo/blob/master/src/core/Cursor.pm6
3. https://github.com/rakudo/rakudo/blob/master/src/core/Match.pm6
only 
https://github.com/perl6/nqp/blob/6debf3dbb429009bf776ea15b48027bed792a983/src/QRegex/Cursor.nqp#L88 
defined `method CURSOR() { self }`. Not only it's an internal method, but also it seems that `CURSOR` has not been used anywhere. So I prefer not to document it.

**Comment by timo** [comment]
there used to be a difference between Match and Cursor, but a few months ago both were unified into just one class

**Comment by JJ** [comment]
Which means this should be closed. Thanks!
