### ISSUE TITLE
Bad link in docs for IO

### ISSUE THREAD

**Issue by grizzlysmit** [perl6/doc#931]
I tried to follow this link [IO::Path::Unix](https://docs.perl6.org/type/IO$COLON$COLONPath$COLON$COLONUnix)  in page https://docs.perl6.org/type/IO$COLON$COLONPath and got a 404 error

the same for [IO::Path::Win32](https://docs.perl6.org/type/IO$COLON$COLONPath$COLON$COLONWin32)

[IO::Path::Cygwin](https://docs.perl6.org/type/IO$COLON$COLONPath$COLON$COLONCygwin)

and [IO::Path::QNX](https://docs.perl6.org/type/IO$COLON$COLONPath$COLON$COLONQNX)

**Comment by jonathanstowe** [comment]
It should be IO::Spec:: ...

**Comment by coke** [comment]
I think these are referencing an older (or perhaps newer that never shipped) version of IO - this whole overview section probably needs to be revisited.

**Comment by Altai-man** [comment]
Judging by quick grepping we have only one instance of each broken link here:
```
➜  doc git:(master) ✗ grep -I -r 'IO::Path::Unix' doc/*
doc/Type/IO/Path.pod6:subclasses instead: L<IO::Path::Unix>, L<IO::Path::Win32>,
```
It can be fixed with just one-liner commit, I guess?

**Comment by coke** [comment]
My concern is that maybe this section is wrong entirely, and perhaps rather
than updating the individual links, we verify the section of docs.

**Comment by Altai-man** [comment]
@coke then we need to cast someone who can do it. I'll reopen the issue then.

**Comment by zoffixznet** [comment]
> It should be IO::Spec:: ...

Not necessarily. We *do* have `IO::Path::*` subclasses. IIRC we didn't have individual pages for those before the IO Grant, which is why the links were 404s.

The links on the page work fine now, so I'm closing this.
