### ISSUE TITLE
page not found in link from https://docs.perl6.org/type/Signature

### ISSUE THREAD

**Issue by grizzlysmit** [perl6/doc#941]
Just bellow https://docs.perl6.org/type/Signature#Constraining_Slurpy_Arguments the link:
[Slurpy arguments](https://docs.perl6.org/type/Slurpy_(A$FULL_STOPK$FULL_STOPA$FULL_STOP_Variadic)_Parameters) give a 404 error not sure whether the page doesn't exist or the link is wrong

**Comment by gfldex** [comment]
fixed with e8d7ef74a9
