### ISSUE TITLE
Revise text on HyperOperators

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#944]
Two quotes from [that section](https://docs.perl6.org/language/operators#Hyper_Operators):
- `Hyper operators are defined recursively on nested arrays.`
- `Hyper operators do not descend into child lists.`

Split it into two sections. One should talk about stuff like `»…«` and another one about `@a»…`. Seems like these are a bit too different.

**Comment by JJ** [comment]
This text has changed (and improved) a lot. I will revise it anyway, but I think that most of the original concerns have been addressed.
