### ISSUE TITLE
Create page for environment variables the interpreter uses

### ISSUE THREAD

**Issue by coke** [perl6/doc#949]
e.g. search for RAKUDO_NO_DEPRECATIONS

**Comment by coke** [comment]
FYI, bad example if we're removing RAKUDO specific env vars.

**Comment by AlexDaniel** [comment]
Errr… pretty sure that this page has to be deleted. All useful info from it should be moved to https://github.com/rakudo/rakudo/wiki/dev-env-vars

**Comment by JJ** [comment]
That's two different things, removing the page and moving it to rakudo wiki or doc page. The second part will depend on what the devs there will want to do with them, right?

**Comment by coke** [comment]
One big happy family, we shouldn't remove it from here until it's listed there.

**Comment by JJ** [comment]
Big happy family with 2-year old issues that are already teething... I get your point, but still...

**Comment by coke** [comment]
Yes, I'm well aware of how old some of theses issues are, especially the ones I've opened. Patches and updates most welcome, thank you.

**Comment by AlexDaniel** [comment]
@JJ fwiw you should have access to edit rakudo wiki, and wikis are editable by all by definition. Devs are irrelevant in this case.

**Comment by JJ** [comment]
2018-02-09 19:27 GMT+01:00 Will Coleda <notifications@github.com>:

> Yes, I'm well aware of how old some of theses issues are, especially the
> ones I've opened. Patches and updates most welcome, thank you.
>

One can do what one can do. I'd happily assist with this, and indeed I have
tried to have a look at the POD and at the wiki, and I really have no idea
where to start. I only want to help, and one thing that would do that is to
focus on what the volunteers in this project can do and will do. There are
enough issues such as it is now. Even low hanging fruits are difficult to
tackle. As I said, I'm only trying to help, and I appreciate yours and
every one else's work. But there's a pile of almost 300 issues, and cutting
it down just a little tiny bit using the criterium of not kicking the ball
down the line would really help.
Words are words, and actions are actions. If it really depends on the other
repository, my proposal would be to open an issue there with reference to
this one and close this one. That way, if it really needs to be reopened we
can do it; if anything happens there, there's a  link. But taking this
burden off our shoulders might help to focus on the rest of the burden:
pages to create from scratch, build issues, many other things out there.

**Comment by JJ** [comment]
Of course I do. But wiki is markdown and POD6 is POD6. I would need a pod6
to markdown converter, and that would be just the start. I've really walked
that path this morning, I'm not putting this out of spit or laziness. Then
Rakudo is a different community. Their wiki, their rules. I don't have
writing permission there. They can happily accept the stuff, or want it to
move somewhere else or just, jeez, I don't know. I would have spent a while
converting stuff and editing the wiki for nothing. If you don't want to
erase the file, right, so be it. I have an issue with the issues
themselves. Their problem, their issue. We've already agreed that it's not
our place. I can happily do the issue and even do the conversion and insert
it right there in the issue. Then they can do whatever they want or assign
the issue in rakudo to me, and I'll happily assist.

**Comment by AlexDaniel** [comment]
@JJ wiki pages on github support different markup languages. POD5 is supported. Converting POD6 to POD5 shouldn't take enormous amounts of effort I assume (I'm speaking of doing it manually).

**Comment by JJ** [comment]
You realize that that's really the very first part of what I just said,
right? I looked at the page mentioned above and it covers just environment
variables. So that means I'll have to look for the proper place for it; and
it might be erased after all, because wikis are wikis.
Be that as it may, it might be easier to do all that than keep discussing
this, and after all, we all want the same: a great and sane perl6. So I'll
try that and come back here.

**Comment by JJ** [comment]
Well, took me a good while, basically the 24 minutes from my previous message, with one issue #1763 created in the process, but there it is https://github.com/rakudo/rakudo/wiki/Running-rakudo-from-the-command-line Can we proceed?

**Comment by zoffixznet** [comment]
I think this Issue a bit outlived itself. When it was created, only a couple of Rakudo-specific env vars were listed on it.

The latest version of the page, before it got removed, contained many more vars, including **language env vars** like `PERL6_TEST_DIE_ON_FAIL`, which should be in language docs, not in a wiki of some particular implementation.

As for the general moving of RAKUDO_ vars to the wiki, I'm not exactly sure how it helps our users to require them to go to some third-party resource and try to find the required information among pages like *"MOLD Removal SQUASHathon"* and *"save me from texas"*.

**Comment by AlexDaniel** [comment]
> find the required information among pages like "MOLD Removal SQUASHathon" and "save me from texas".

Heh. That's a good point.

**Comment by JJ** [comment]
Maybe we should change the issue title to "Create language environment variables page"? What the title said was precisely what was done, move it to the wiki.

**Comment by AlexDaniel** [comment]
@JJ please feel free to edit titles in general, and also any of my comments if you feel necessary.

**Comment by JJ** [comment]
@AlexDaniel if what we want is to have a new page, I think it's much better to open a new issue saying just that. @zoffixznet , what do you think? Let what's been closed stay closed :-)

**Comment by AlexDaniel** [comment]
@JJ Yes, that's the right way to do it I think. FWIW that's even written as a recommendation for [squashathons](https://github.com/rakudo/rakudo/wiki/Monthly-Bug-Squash-Day):

> If the ticket is asking for more than one thing, replace with new smaller tickets and close it. **If you see a lot of out-of-place discussion, try to understand the main point and create a new highly-specific ticket to replace it.**

So creating a new ticket usually makes things go easier, but having a link to the previous ticket never hurts I think.

**Comment by JJ** [comment]
... *and* the wiki :-)
(I'll close this when I -- or someone else -- creates the ticket(s))

**Comment by flussence** [comment]
Wouldn't it make more sense to just update the original file this all seems to be copy-pasted from, https://github.com/rakudo/rakudo/blob/master/docs/running.pod? I even mentioned it was perfectly good material going to waste in perl6/user-experience#9, but got no response.

**Comment by JJ** [comment]
Do you mean update it right there in the rakudo repo?

**Comment by flussence** [comment]
It would be useful to keep that file up to date, since every rakudo release tarball already contains it.
