### ISSUE TITLE
Need documentation for $*ARGFILES and the lines() function

### ISSUE THREAD

**Issue by pmichaud** [perl6/doc#96]
The lines() function and $*ARGFILES handle are currently missing from p6doc.

**Comment by jonathanstowe** [comment]
$*ARGFILES is noted in Variables.pod but is a bit slim (the way the dynamic variables are listed is somewhat weird anyway.)

**Comment by pmichaud** [comment]
Yes, I saw it mentioned in Variables.pod; I'm looking for something more complete than that.  :)

**Comment by jonathanstowe** [comment]
I noticed a while back that very few of the functions defined in io_operators.pm are documented, nor is IO::Argfiles itself which is probably the most natural place to document $*ARGFILES.

I'll take a look later.

**Comment by pmichaud** [comment]
Added this issue to WANTED.

**Comment by paultcochrane** [comment]
Initial `IO::ArgFiles` docs added in a404865bcee5cf10fb79603370485054a0d80fa1.

**Comment by paultcochrane** [comment]
Documentation about `$*ARGFILES` added in 45a260a.  The documentation can be seen by running

    p6doc IO::ArgFiles

Is this what you were looking for?  If not, what else needs to be done to achieve the required functionality?

**Comment by awwaiid** [comment]
Closing, since this appears to be done (feel free to reopen otherwise).

**Comment by tbrowder** [comment]
Docs need a good example of iterating over $*ARGFILES handles, getting paths for valid file handles, and skipping invalid file handles WITHOUT ERROR, and reporting number of invalid file handles.

**Comment by JJ** [comment]
There's also a reference to "the example above" which I can't fathom where it comes from...

**Comment by JJ** [comment]
@tbrowder I haven't found a way to skip invalid files without capturing the exception. $*ARGFILES.handles does return the handle, but they any operation on it fails.

**Comment by JJ** [comment]
As you have indicated in rakudo/rakudo#2666, it does not seem possible to skip invalid file handles without handling exceptions...
