### ISSUE TITLE
bad "is nodal" example/text

### ISSUE THREAD

**Issue by coke** [perl6/doc#966]
Confusing example in doc/Language/typesystem.pod6

What does this example code have to do with is nodal?

Text is also hard to process; a less tortured phrasing is "mark a method so hyperoperators do not descend into it"

```
=head4 trait C<is nodal>

Mark a method for hyperoperators as to be avoided for descending into.

    dd [[1,2,3],[4,5]]>>.elems;
    # OUTPUT«(3, 2)␤»
```

**Comment by dogbert17** [comment]
Have updated the docs with https://github.com/perl6/doc/commit/5af4ebd377. Dunno if it's enough to close the issue though.

**Comment by dogbert17** [comment]
With 1ca0487f I think we can close this issue
