### ISSUE TITLE
Another precedence trap: -1**5

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#971]
Sometimes I do this:

Code:
```perl6
say -1**2
```

Output:
```
-1
```

When I actually mean this:

```perl6
say (-1)**2
```

Output:
```
1
```

**Comment by LLFourn** [comment]
is it intended that infix ** be tighter than prefix - ?

**Comment by pierre-vigier** [comment]
It seems normal for me that ** is tigher that -, after a quick check, python, ruby and Octave have the same behavior as well

**Comment by labster** [comment]
Assuming only real numbers, in normal mathematical notation:

y = -x²
z = -3²

Would you expect y to be positive or negative?  The same for z?  I would definitely expect a negative number for y.

**Comment by AlexDaniel** [comment]
perhaps it means that unicode ops should have looser precedence? 🤷

**Comment by labster** [comment]
Aren't all ops Unicode?

**Comment by LLFourn** [comment]
@labster I think @AlexDaniel  means that the more mathematical notation of ² could be tighter while `**2` be looser. I expected `**` to be looser simply because it looks looser to me. What I expected is apparently not the norm so nvm me :)

**Comment by VynceMontgomery** [comment]
(subject of issue is misleading, because answer is the same either way)

- x**2 should definitely square before negating. 
-5 ** 2 sure feels to me like it should negate before squaring. 
whitespace affecting precedence is a sketchy place to be, but Perl is supposed to DWIM and in this case, it doesn't feel like - is a unary operator, it feels like it's part of the number literal. YMMV, of course.

**Comment by VynceMontgomery** [comment]
in fact, -2 is given as an example of an integer literal, and yet it appears not to be parsed that way. this seems ... wrong.

**Comment by jnthn** [comment]
Indeed, negatives are not parsed as literals (with the exception of `-Inf`), so if something gives -2 as an example of an integer literal it probably warrants a clarification.

**Comment by VynceMontgomery** [comment]
What reasoning (and evidence) is there for -Inf parsing as a literal and not as unary - applied to Inf?

**Comment by jnthn** [comment]
Can't say much about reasoning. As for evidence, I checked it in the grammar; see https://github.com/rakudo/rakudo/blob/nom/src/Perl6/Grammar.nqp#L3386

**Comment by b2gills** [comment]
Perhaps `-x ** y` should produce an error telling you to use parens to disambiguate.

**Comment by pierre-vigier** [comment]
If you write -1 to the power of 2 by hand, without parenthesis, you expect the power to take precedence on the minus, so why would perl6 act differently. Written by hand, space are not affecting precedence of the multiplication operator or the power operator.
Written by hand, if you want -1 to the power of 2 to be equal to one, you will add parenthesis, so the current behaviour seems expected, at least for me

**Comment by AlexDaniel** [comment]
@pierre-vigier but if you write ``-1 ** 2`` you definitely mean something different (although my original report says ``-1**2``).

**Comment by pierre-vigier** [comment]
Written by hand,  spaces for that expression do not matter and do not change precedence, I really don't see why they should change something in perl,  I would not treat it differently because of the spaces, and I would actually use parentheses, to elevate minus one to power 2

**Comment by AlexDaniel** [comment]
How often do you write ``**`` operator by hand?  /o\

**Comment by pierre-vigier** [comment]
For me having the **2 notation, or the superscript ² does not make any difference, it is the same operator, no? Why would they be treated differently? anyway, as i am concerned, i almost never use a statement with just that, but if you take the inverse statement, it seems odd : 
```perl
my $x = - ( 1 ** 2 );
```
i feel more confortable with:
```perl
my $x = -1**2;
 ```
But maybe the correct solution is the one proposed previously that force the usage of parentethese, to not have an error or a warning.

As a reference, if usefull, with ruby repl:
```
irb(main):001:0> -1**2
=> -1
irb(main):002:0> -1 ** 2
=> -1
irb(main):003:0> -1  **  2
=> -1
```

in python:
```
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> -1**2
-1
>>> -1 ** 2
-1
>>> -1  **   2
-1
>>>
```

perl5
```
» perl -E "say -1**2;say -1 ** 2;say -1  **  2"
-1
-1
-1
```

a search in google with -1 ** 2 also give -1
