### ISSUE TITLE
(call|next)(with

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/doc#976]
They're mentioned in https://docs.perl6.org/language/functions, but aren't really fleshed out. Also they are highlighted blue in https://docs.perl6.org/language/functions#Re-dispatching like they should be clickable, but aren't.

**Comment by AlexDaniel** [comment]
This is resolved now. You can compare it with the [previous version](https://web.archive.org/web/20170408111414/https://docs.perl6.org/language/functions#Re-dispatching). There were many commits during this period, here's one of them: https://github.com/perl6/doc/commit/42344f80f2e5d8c21f3b0f521f4dd56d42602ac3
