### ISSUE TITLE
The description of the second callable arg to splice is wrong

### ISSUE THREAD

**Issue by zostay** [perl6/doc#977]
In `Array.splice`, it says the second argument, when `Callable`, is called with two arguments. It is actually just called with one.

**Comment by coke** [comment]
FYI, "Resolves" doesn't close the ticket. try "Fixes" next time.

**Comment by zoffixznet** [comment]
"Resolves" works too, it's just the PR wasn't merged.

**Comment by coke** [comment]
Whoops, misread where that commit went, thanks!
