### ISSUE TITLE
Error in Classes Tutorial (classtut) documentation

### ISSUE THREAD

**Issue by payerle** [perl6/doc#979]
In classtut document (e.g. https://docs.perl6.org/language/classtut), I believe there is an error in the section re Introspection when describing the " ^methods" method.

In the example output, it shows methods for class Programmer (which seems to be consistent with rest of the example output).  

But in explanatory text below the example, it refers to (incorrectly I believe) the Employee class, e.g.

> The :local named argument limits the returned methods to those defined in the Employee class 

There is another reference to Employee class in the following paragraph.

I am still transitioning from Perl5 to 6, but I believe the two references to Employee class should actually be Programmer class.

**Comment by AlexDaniel** [comment]
Yea, indeed! Can you submit a pull request with the fixes? [Here is](https://github.com/perl6/doc/blob/master/doc/Language/classtut.pod6#L635) the file.

**Comment by titsuki** [comment]
@payerle
It seems that you have merged your pull request on the different repository.
After forking this repository, you can send a pull request by the following operations:
```
$ git checkout master
$ git remote add upstream git@github.com:perl6/doc.git 
$ git fetch upstream
$ git merge upstream
$ git checkout -b payerle-patch-1
# Open classtut.pod6 and fix this issue !
$ git commit -am "Update classtut.pod6: text/example discrepancy in Introspection section/master"
$ git push origin payerle-patch-1
# Send a pull request with Github GUI Interface 
```

good luck !

**Comment by payerle** [comment]
OK, thanks for the more detailed instructions.

On Fri, 21 Oct 2016, Itsuki Toyota wrote:
> 
> @payerle
> It seems that you have merged your pull request on the different repository.
> After forking this repository, you can send a pull request by the following operations:
>
>  $ git checkout master
> $ git remote add upstream git@github.com:perl6/doc.git 
> $ git fetch upstream
> $ git merge upstream
> $ git checkout -b payerle-patch-1
> # Open classtut.pod6 and fix this issue !
> $ git commit -am "Update classtut.pod6: text/example discrepancy in Introspection section/master"
> $ git push origin payerle-patch-1
> # Send a pull request with Github GUI Interface 
> 
> good luck !
> 
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.[ASZO_7rvwy4VWsPls5fXNeo7NQ4pqCypks5q2Z7zgaJpZM4KcaWc.gif]
> 
> 
>

Tom Payerle
IT-ETI-EUS 				payerle@umd.edu
4254 Stadium Dr				(301) 405-6135
University of Maryland
College Park, MD 20742-4111

**Comment by Altai-man** [comment]
It seems like a bit of misunderstanding here, since there are no PR for a week already.

With all thanks to @payerle for spotting and reporting the mistake, I'll do edit it in the main repository to close the issue.
