### ISSUE TITLE
Broken Link on method sink page

### ISSUE THREAD

**Issue by samcv** [perl6/doc#985]
https://docs.perl6.org/routine/sink
Link to: X::Proc::Unsuccessful is broken.

**Comment by AlexDaniel** [comment]
Or more generally, this: https://github.com/perl6/doc/issues/517

According to the last message ``X::Proc::Unsuccessful`` is not in roast, so if you think that it has to be documented please also create an issue in [roast repo](https://github.com/perl6/roast/issues).

**Comment by AlexDaniel** [comment]
Ah oops, no. Just reread the description:

> These are mentioned in Rakudo but not Roast

So everything is alright, probably.

**Comment by dogbert17** [comment]
The link now works.

**Comment by AlexDaniel** [comment]
OK then
