### ISSUE TITLE
IO.e, IO.d, IO.f are not searchable

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#986]
SEE: https://docs.perl6.org/language/io#Checking_files_and_directories

**Comment by gfldex** [comment]
they are defined but not doced in IO::Path and IO::Handle. As soon as those methods are doced they will be searchable automatically (for small values of searchable, a single "e" gets tons of hits that are not sorted by length).

**Comment by titsuki** [comment]
@gfldex 
Thanks! I added the "docs" tag.

SEE ALSO:
https://github.com/rakudo/rakudo/blob/nom/src/core/IO/Path.pm#L541-L554
https://github.com/rakudo/rakudo/blob/nom/src/core/IO/Handle.pm#L749-L751

**Comment by gfldex** [comment]
fixed with 027db9e
