### ISSUE TITLE
RAKUDO_ specific environment variables should be moved from 00-running

### ISSUE THREAD

**Issue by coke** [perl6/doc#990]
The ENV var section there should be for implementation agnostic variables.

There's a link now to https://github.com/rakudo/rakudo/wiki/dev-env-vars , where we can document all the rakudo-specfic variables. (All the ones that were missing are documented there, just need to move the ones that were already doc'd)

**Comment by AlexDaniel** [comment]
I think this is no longer an issue after https://github.com/perl6/doc/issues/990. Well, the page no longer exists. At least, further discussion on this can be there.
