### ISSUE TITLE
implement some kind of fuzzy matching for search

### ISSUE THREAD

**Issue by timo** [perl6/doc#999]
for example, ideally "startswith" and "starts_with" both should find "starts-with".

**Comment by coke** [comment]
The PR for was merged (prematurely?) - there is a big performance slowdown for searches with small # of characters.

One possible fix is to only use getEditDistance() if the number of input characters is (e.g.) 3 or more - for this to work, we need to find what the default search algorithm was.

I think it's this:

https://github.com/jquery/jquery-ui/blob/master/ui/widgets/autocomplete.js#L638

**Comment by coke** [comment]
Done. We now have fuzzy search with OK performance.
